- main/src/cgeo/geocaching/maps/routing/Routing.java
fix #10138: add safeguard for npe in routing
> fix #10138: add safeguard for npe in routing

- main/res/values-ca/strings.xml
- main/res/values-cs/strings.xml
- main/res/values-da/strings.xml
- main/res/values-de/strings.xml
- main/res/values-el/strings.xml
- main/res/values-fi/strings.xml
- main/res/values-it/strings.xml
- main/res/values-ja/strings.xml
- main/res/values-ko/strings.xml
- main/res/values-lb/strings.xml
- main/res/values-lv/strings.xml
- main/res/values-nb/strings.xml
- main/res/values-nl/strings.xml
- main/res/values-pl/strings.xml
- main/res/values-pt/strings.xml
- main/res/values-sk/strings.xml
- main/res/values-sv/strings.xml
- main/res/values-tr/strings.xml
- main/res/values-uk/strings.xml
- main/res/values-zh/strings.xml
- main/res/values/strings.xml
- main/src/cgeo/geocaching/utils/DebugUtils.java
rel to #10140: remove html and cdata from strings.xml resources
> rel to #10140: remove html and cdata from strings.xml resources

- main/res/values-de/strings.xml
- main/res/values-ru/strings.xml
- main/res/values/strings.xml
fix #10152: make translation indexes positional
> fix #10152: make translation indexes positional

- main/res/values/strings.xml
- Work on #10155
- Remove strings, which are reported unused by lint ( @cgeo/team Please doublecheck, as I don't know how true these lint reports are)
- Replace unmatching variables (decimal instead of string)
> Cleanup strings

- main/res/layout/folder_selection_dialog.xml
- main/src/cgeo/geocaching/storage/ContentStorageActivityHelper.java
rel to #10124: make noAction the default for all folder selections including wizard
> rel to #10124: make noAction the default for all folder selections including wizard

- main/res/values/strings.xml
> make build run again

- .idea/checkstyle-idea.xml
Set the version of checkstyle which should be used in AS to 8.41.
> update checkstyle in AS

- main/src/cgeo/geocaching/maps/DistanceDrawer.java
fix #10195: add npe safeguard to DistanceViewer
> fix #10195: add npe safeguard to DistanceViewer

- main/src/cgeo/geocaching/maps/mapsforge/v6/RenderThemeHelper.java
fix #10194: add safeguard for invalid zip files
> fix #10194: add safeguard for invalid zip files

- main/src/cgeo/geocaching/maps/MapSettingsUtils.java
OK, here we are...
closes #10201
fixes #10187
~Sorry, it's targeted to master currently. I will change it this evening... (No more time right now)~
> keep routing mode OFF/STRAIGHT always enabled in quick settings

- main/src/cgeo/geocaching/storage/DocumentContentAccessor.java
- main/src/cgeo/geocaching/utils/LocalizationUtils.java
fix #10211: loop of death on nonaccessible uri in reportproblem
> fix #10211: loop of death on nonaccessible uri in reportproblem

- main/src/cgeo/geocaching/utils/BackupUtils.java
During restoring settings also request SAF grants for folders which have not been set yet but for which are values in the settings to-be-restored. (Which is the typical situation after a fresh install.)
> check for unset SAF-folders on restore (fix #10211)

- main/src/cgeo/geocaching/utils/SystemInformation.java
Cosmetic issue only: Move this info
from end of "permissions & path" section to "program settings" section.
> system info: move settings info to settings section

- main/res/values/strings.xml
- main/src/cgeo/geocaching/ImageSelectActivity.java
fix #10219: make image title non-mandatory also for OC
> fix #10219: make image title non-mandatory also for OC

- main/src/cgeo/geocaching/AboutActivity.java
- main/src/cgeo/geocaching/utils/SystemInformation.java
fix #10209, fix #10200: gather system info async, add map info
> fix #10209, fix #10200: gather system info async, add map info

- main/src/cgeo/geocaching/storage/ContentStorage.java
> try fixing loop-of-death

- main/src/cgeo/geocaching/maps/mapsforge/v6/RenderThemeHelper.java
- main/src/cgeo/geocaching/storage/ContentStorage.java
fix #10235: handle/catch illegalargumentexception
> fix #10235: handle/catch illegalargumentexception

- main/src/cgeo/geocaching/storage/ContentStorageActivityHelper.java
- main/src/cgeo/geocaching/utils/UriUtils.java
- tests/src/cgeo/geocaching/utils/UriUtilsTest.java
fix #10234: stable against strange uris
> fix #10234: stable against strange uris

- main/src/cgeo/geocaching/connector/gc/PocketQueryListActivity.java
- main/src/cgeo/geocaching/maps/MapSettingsUtils.java
- main/src/cgeo/geocaching/maps/routing/RouteSortActivity.java
- main/src/cgeo/geocaching/settings/ViewSettingsActivity.java
Fix some lint issues about "Avoid passing 'null' as the root view (...)"
> fix some lint inflate / root view issues

- main/src/cgeo/geocaching/storage/DocumentContentAccessor.java
- main/src/cgeo/geocaching/storage/FolderUtils.java
- main/src/cgeo/geocaching/storage/PersistableFolder.java
- main/src/cgeo/geocaching/utils/LocalizationUtils.java
- main/src/cgeo/geocaching/utils/SystemInformation.java
rel to #10248: better NPE handling, enhance system information
> rel to #10248: better NPE handling, enhance system information

- main/src/cgeo/geocaching/maps/mapsforge/v6/RenderThemeHelper.java
- main/src/cgeo/geocaching/utils/SystemInformation.java
rel to #10202: put safeguard: dont scan theme files larger than 5MB
> rel to #10202: put safeguard: dont scan theme files larger than 5MB

- main/res/values/strings.xml
- main/src/cgeo/geocaching/settings/Settings.java
- main/src/cgeo/geocaching/storage/ContentStorageActivityHelper.java
- main/src/cgeo/geocaching/storage/PersistableUri.java
- main/src/cgeo/geocaching/utils/BackupUtils.java
Similar to what we have fixed for folders already: Check settings for persistable files on restore and request re-grant if setting has changed.
> check missing file permission on restoring settings (fix #10215)

- main/src/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java
- suppressions.xml
try to fix BRouter failing CI build
> try to fix BRouter failing CI build

- suppressions.xml
checkstype: fine-grain suppressions for BRouter
> checkstype: fine-grain suppressions for BRouter

- checkstyle.xml
> remove lineSeparator property from checkstyle NewlineAtEndOfFile check

- main/src/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java
Reverts #10251 partly, to get the google map back working...
> fix crash on opening Google Maps (fixes #10282)

- main/src/cgeo/geocaching/maps/mapsforge/v6/RenderThemeHelper.java
- main/src/cgeo/geocaching/utils/CollectionStream.java
- tests/src/cgeo/geocaching/utils/CollectionStreamTest.java
fix #10297: make CollectionStream robust against null-arrays
fix #10298:  catch all exceptions on theme creation
> fix #10297, fix #10298: make CollectionStream more robust, catch all exceptions on theme creation

- main/res/values/strings.xml
- main/src/cgeo/geocaching/maps/mapsforge/v6/RenderThemeHelper.java
- main/src/cgeo/geocaching/storage/extension/OneTimeDialogs.java
fix #10224: introduce otm for slow theme usage
> fix #10224: introduce otm for slow theme usage

- main/src/cgeo/geocaching/downloader/ReceiveMapFileActivity.java
- main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/RenderThemeHelper.java
- main/src/cgeo/geocaching/storage/ContentStorage.java
- main/src/cgeo/geocaching/storage/ContentStorageActivityHelper.java
- main/src/cgeo/geocaching/storage/FolderUtils.java
- main/src/cgeo/geocaching/utils/BackupUtils.java
- tests/src-android/cgeo/geocaching/storage/ContentStorageTest.java
related to #10307, fix #10313, fix #10312: limit scanned subfolders, no user error message outside debug mode
> fix #10307, fix #10313, fix #10312: limit scanned subfolders, no user error message outside debug mode

- main/src/cgeo/geocaching/storage/FileByteReader.java
- tests/src/cgeo/geocaching/storage/FileByteReaderTest.java
SAF-Helper: introduce FileByteReader
This will help implementing #10176
> SAF-Helper: introduce FileByteReader

- main/res/xml/preferences.xml
- main/src/cgeo/geocaching/settings/Settings.java
- main/src/cgeo/geocaching/utils/SystemInformation.java
As agreed upon in today's meetup two things in preparation for the next release:
- disable OSM multi-threading by default
- display number of available processors in about - system page
> Prepare release

- settings.gradle
Update to the latest version, see https://docs.gradle.com/enterprise/gradle-plugin/#release_history
> Update gradleEnterprise plugin

- build.gradle
> remove JCenter references

- main/src/cgeo/geocaching/export/TrailHistoryExport.java
see https://github.com/cgeo/cgeo/issues/10331#issuecomment-818138835 for details
> fix truncation on history trail export (fix #10331)

- main/res/layout/dialog_title_button_button.xml
- main/src/cgeo/geocaching/NavigateAnyPointActivity.java
- main/src/cgeo/geocaching/connector/internal/InternalConnector.java
- main/src/cgeo/geocaching/ui/dialog/Dialogs.java
- main/src/cgeo/geocaching/utils/EmojiUtils.java
- allow setting a cache icon while creating UDC's
- cleanup/refactoring: use ViewBindings for OneTimeMessages and EmojiUtils
- add some more useful emojis like flashlight, etc...
> allow setting a cache icon while creating UDC's

- main/src/cgeo/geocaching/brouter/mapaccess/NodesCache.java
- main/src/cgeo/geocaching/brouter/mapaccess/OsmFile.java
- main/src/cgeo/geocaching/brouter/mapaccess/PhysicalFile.java
This will migrate access to brouter tile files (rd5 files previously located in segment4) to SAF
@moving-bits would appreciate your feedback
> rel to #10176: migrate brouter tile access to SAF

- main/src/cgeo/geocaching/storage/LocalStorage.java
fix #10393: introduce null-check on file list
> fix #10393: introduce null-check on file list

- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/connector/ec/ECApi.java
- main/src/cgeo/geocaching/connector/ec/ECLogin.java
- main/src/cgeo/geocaching/connector/gc/GCConnector.java
- main/src/cgeo/geocaching/connector/gc/GCParser.java
- main/src/cgeo/geocaching/connector/oc/OCConnector.java
- main/src/cgeo/geocaching/connector/su/SuConnector.java
- main/src/cgeo/geocaching/connector/trackable/TravelBugConnector.java
- main/src/cgeo/geocaching/helper/QueryMapFile.java
- main/src/cgeo/geocaching/log/LogCacheActivity.java
- main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/RenderThemeHelper.java
- main/src/cgeo/geocaching/models/Geocache.java
- main/src/cgeo/geocaching/models/PersonalNote.java
- main/src/cgeo/geocaching/models/Trackable.java
- main/src/cgeo/geocaching/models/Waypoint.java
- main/src/cgeo/geocaching/settings/Settings.java
- main/src/cgeo/geocaching/settings/TokenPreference.java
- main/src/cgeo/geocaching/storage/DataStore.java
- main/src/cgeo/geocaching/storage/Folder.java
- main/src/cgeo/geocaching/ui/ImageListFragment.java
- main/src/cgeo/geocaching/utils/ImageUtils.java
- main/src/cgeo/geocaching/utils/Log.java
- main/src/cgeo/geocaching/utils/TextUtils.java
use `StringUtils.isNotBlank(String) `/ `StringUtils.isNotEmpty(String)` for better code readability
> Improve code readability

- main/src/cgeo/geocaching/connector/gc/GCConstants.java
- main/src/cgeo/geocaching/connector/gc/GCLogin.java
adapt login for the GC connector to recent website change regarding login
> adapt gc login to website change (fix #10434)

- main/src/cgeo/geocaching/connector/gc/GCConstants.java
> try to fix the parsing of owner id after website change

- main/src/cgeo/geocaching/connector/gc/GCConstants.java
- main/src/cgeo/geocaching/connector/gc/GCLogin.java
- main/src/cgeo/geocaching/connector/gc/GCParser.java
Edit:
There are 2 different script-sections for the settings (see details below).
~~I added a second regExpr like the one for the username of the headerSettings-section.
Probably they can be merged to one to find *"findCount": 590,* or  *"findCount": 590*, but then less information is parsed.
With the extended pattern including the "headerSettings" it is probably more restrictive.~~
The login page has also the section `headerSettings` with the findCount contained (see regExpr for username). So now this section is used for the findCount as well.
@moving-bits  please check
~~or probably on detail-page the count should not be updated?~~
#10453
```
<script type="text/javascript">
var dataLayer = [{
"username": "xxx",
"accountId": 1234,
"membershipLevel": "Premium",
"signUpDate": …
```
> update regular expression for caches count (fix #10453)

- main/res/values/strings.xml
More general problem description for our notification system, to be able to use it more often.
Also making it clearer, that we are aware of the problem.
Additionally adding to the report problem prefix, that users should check FAQ and social media first.
None
> Optimize strings for our notification system

- main/src/cgeo/geocaching/connector/gc/GCConstants.java
- main/src/cgeo/geocaching/connector/gc/GCParser.java
- tests/src-android/cgeo/geocaching/connector/gc/GCConstantsTest.java
- tests/src-android/cgeo/geocaching/connector/gc/GCParserTest.java
- tests/src-android/cgeo/geocaching/utils/TextUtilsTest.java
- tests/src/cgeo/geocaching/test/mock/GC1ZXX2.html
- tests/src/cgeo/geocaching/test/mock/GC2CJPF.html
- tests/src/cgeo/geocaching/test/mock/GC2JVEH.html
- tests/src/cgeo/geocaching/test/mock/GC3FJ5F.html
- tests/src/cgeo/geocaching/test/mock/GC3XX5J.html
Update the five cache pages used in `MockedCache`
> update mocked cache files used in MockedCache (fix #10439)

- main/res/values-de/strings.xml
I will only merge the Crowdin PR after some time for translators to catch up. Otherwise existing translations would be deleted because they are not untranslated after pushing the strings change for the source strings.
Therefore manually adding the german translations (to cover a huge user group) for our next short term release.
None
> Temporarily insert german strings for notification system

- main/res/values/strings.xml
- main/src/cgeo/geocaching/AboutActivity.java
- main/src/cgeo/geocaching/downloader/MapDownloaderFreizeitkarte.java
- main/src/cgeo/geocaching/export/FieldNoteExport.java
- main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java
- main/src/cgeo/geocaching/storage/AbstractContentAccessor.java
- main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateDialog.java
Fixes a couple of lint messages regarding
- non localizable string (also replacing three dots with ellipsis)
- toLowerCase() without locale
- string concatenation
> fix some lint errors

- main/src/cgeo/geocaching/AboutActivity.java
Rules:
- SameParameterValue
- UnusedAssignment
> some lint optimization in AboutActivity

- main/src/cgeo/geocaching/maps/mapsforge/v6/RenderThemeHelper.java
This PR, if merged, will make map theme folder scan asynchronous. This is to reduce ANRs as described in #10406 which are assumed to result from synchronus map theme folder scan on startup.
* An asynchronous folder scan will be started on application startup
* If such a scan has not finished when map viewer is first opened, then the same scan will be done synchronous (resulting in slow map viewer opening performance)
* As an additional measurement, scan will generally be restricted to a tree depth of at most 2 subdirs
* (The previously introduced scan time limit was removed instead)
This is a rather complex fix due to asynchronity of tasks. I would appreciate code review.
Related to #10406
> rel to #10406: make map theme folder scan asynchronous

- main/src/cgeo/geocaching/connector/lc/LCApi.java
Stores description and main image (if existing) for LC connector
> store description for LC connector (fix #10478)

- main/src/cgeo/geocaching/storage/ContentStorage.java
fix #10495: check for empty uri on stream opening
> fix #10495: check for empty uri on stream opening

- main/res/values/preference_keys.xml
- main/res/values/strings.xml
- main/res/xml/preferences.xml
- main/src/cgeo/geocaching/settings/SettingsActivity.java
- main/src/cgeo/geocaching/utils/DebugUtils.java
While working on some downloader issue I recognized the need to get a view on c:geo-initiated downloads and their current state, so I added this raw view on the info the system's download manager provides:
> add debug view for pending downloads

- tests/src-android/cgeo/geocaching/downloader/DownloaderTest.java
- add counter-based tests for (map/theme/tile) downloaders
- add tests for specific entries for each downloader
> add tests for downloaders

- tests/src-android/cgeo/geocaching/downloader/DownloaderTest.java
fix #10553: new counts for download test
> fix #10553: new counts for download test

- main/res/values/dimens.xml
- main/src/cgeo/geocaching/settings/ProximityPreference.java
- main/src/cgeo/geocaching/settings/SeekbarPreference.java
- main/src/cgeo/geocaching/ui/dialog/Dialogs.java
some fixes / improvements for proximity-preference-dialog:
* feature: add unit-label to edit-dialog
* feature / fix: show toast if value is too high / low
* fix: decimal input possible on switching unit-settings (no restart of settings-activity)
#10508
> Improvements for proximity-preference-dialog (rel #10508)

- main/src/cgeo/geocaching/connector/lc/LCApi.java
searchByBBox() now implements a radius calculation that allows to fill a rectangular map area. See discussion: #10569
> Fixes #10569 ALC live map loading needs optimization

- main/src/cgeo/geocaching/enumerations/CacheType.java
- tests/src-android/cgeo/geocaching/files/GPXParserTest.java
detect "Lab Cache" in GPX as ALC (fixes  #10558)
> detect "Lab Cache" in GPX as ALC

- main/src/cgeo/geocaching/StatusFragment.java
Don't use Chrome Webview for status message links (fix #10584)
> Revert "generify handling of URL opening (#10533)" partly

- main/res/layout/pq_actionbar.xml
| before | after |
|-|-|
| ![Screenshot_20210511_182402_cgeo geocaching](https://user-images.githubusercontent.com/64581222/117853211-700b0980-b288-11eb-8790-49b52c4ee332.png) | ![grafik](https://user-images.githubusercontent.com/64581222/117853199-6bdeec00-b288-11eb-92e9-e241dae41e91.png) |
> use ellipsize in pocket query activity actionbar

- main/src/cgeo/geocaching/connector/gc/GCParser.java
Preparation for "show hint if list/query has been updated since the last download" which is on my internal todo list.
> parse last updated time for bookmark lists

- main/src/cgeo/geocaching/connector/su/SuApi.java
- main/src/cgeo/geocaching/connector/su/SuApiEndpoint.java
- main/src/cgeo/geocaching/connector/su/SuConnector.java
Add possibility to ignore caches on gc.su
> su: add ignore capability

- main/src/cgeo/geocaching/settings/SettingsActivity.java
- Check profile files on Setting's start as well (fixes #10599)
- Fix a bug related to filling the profile preferences' summary (fixes #10600)
> Better user experience for internal routing settings

- main/res/values/preference_keys.xml
- main/src/cgeo/geocaching/connector/lc/LCApi.java
- main/src/cgeo/geocaching/connector/lc/LCConnector.java
- main/src/cgeo/geocaching/settings/Settings.java
now based on a completely recreated release branch from master and synced to origin.
@Lineflyer ... you can now decide which one to merge. The other one can be closed then.
> alc optimizations (3rd edition)

- main/src/cgeo/geocaching/activity/AbstractActivity.java
- main/src/cgeo/geocaching/activity/Keyboard.java
- main/src/cgeo/geocaching/connector/internal/InternalConnector.java
- main/src/cgeo/geocaching/list/StoredList.java
- main/src/cgeo/geocaching/log/AbstractLoggingActivity.java
- main/src/cgeo/geocaching/log/LogTrackableActivity.java
- main/src/cgeo/geocaching/ui/EditNoteDialog.java
- main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java
- main/src/cgeo/geocaching/ui/dialog/Dialogs.java
- generify/simplify keyboard usage
- fix some "keyboard does not pop up" issues
- remove leading and trailing whitespaces added by Android autocompletion in input dialogs
> Optimize Input Dialogs

- main/res/layout/date_range_selector_view.xml
- main/res/values/strings.xml
- main/res/values/styles.xml
- main/src/cgeo/geocaching/connector/gc/GCMap.java
- main/src/cgeo/geocaching/connector/gc/GCWebAPI.java
- main/src/cgeo/geocaching/filters/core/DateFilter.java
- main/src/cgeo/geocaching/filters/core/DateRangeGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/GeocacheFilterType.java
- main/src/cgeo/geocaching/filters/core/HiddenGeocacheFilter.java
- main/src/cgeo/geocaching/filters/gui/DateRangeFilterViewHolder.java
- main/src/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java
- main/src/cgeo/geocaching/ui/DateRangeSelector.java
- main/src/cgeo/geocaching/ui/DateTimeEditor.java
Adds a "hidden" filter (including its integration in gc.com filter search) to new filter framework
fixes #10634
> add hidden filter

- .gitattributes
Adding the translated (but not the source) changelogs to merge strategy `ours`. Doing so, they will be ignored during merge operations.
Fix #10647
No further action needed for those devs who already applied `git config --local include.path ../.gitconfig` before.
> Fix #10647 - Exclude translated changelogs from merging

- main/res/layout/map_settings_dialog.xml
- main/res/values/styles.xml
- main/src/cgeo/geocaching/filters/core/GeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/StatusGeocacheFilter.java
- main/src/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java
- main/src/cgeo/geocaching/filters/gui/GeocacheFilterActivity.java
- main/src/cgeo/geocaching/maps/AbstractMap.java
- main/src/cgeo/geocaching/maps/CGeoMap.java
- main/src/cgeo/geocaching/maps/MapSettingsUtils.java
- main/src/cgeo/geocaching/maps/MapUtils.java
- main/src/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
- main/src/cgeo/geocaching/models/Geocache.java
First integration of Filtering into the map viewer
Also fixes some bugs in saving/loading cache filters as well as filter config parsing and clear method along the way...
> filter integration into map view

- main/res/values/strings.xml
- main/src/cgeo/geocaching/CacheListActivity.java
- main/src/cgeo/geocaching/CachePopupFragment.java
- main/src/cgeo/geocaching/enumerations/CacheListType.java
- main/src/cgeo/geocaching/filters/core/GeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/StatusGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/StringFilter.java
- main/src/cgeo/geocaching/filters/core/StringGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/ValueGroupGeocacheFilter.java
- main/src/cgeo/geocaching/filters/gui/StatusFilterViewHolder.java
- main/src/cgeo/geocaching/maps/AbstractMap.java
- main/src/cgeo/geocaching/maps/CGeoMap.java
- main/src/cgeo/geocaching/maps/MapSettingsUtils.java
- main/src/cgeo/geocaching/maps/MapUtils.java
- main/src/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java
- main/src/cgeo/geocaching/maps/interfaces/MapActivityImpl.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
- main/src/cgeo/geocaching/settings/Settings.java
fix few bugs in map filter + user displayable string
> fix few bugs in map filter + user displayable string

- main/src/cgeo/geocaching/enumerations/CacheAttribute.java
- main/src/cgeo/geocaching/filters/core/AttributesGeocacheFilter.java
fix #8620: fixes filtering for attributes for oc caches for NEW filter framework
> fix #8620: filtering for attributes for oc caches

- main/res/menu/map_activity.xml
- main/res/values/strings.xml
- main/src/cgeo/geocaching/CacheListActivity.java
- main/src/cgeo/geocaching/CachePopupFragment.java
- main/src/cgeo/geocaching/enumerations/CacheListType.java
- main/src/cgeo/geocaching/filters/core/AttributesGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/DateFilter.java
- main/src/cgeo/geocaching/filters/core/GeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/GeocacheFilterType.java
- main/src/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java
- main/src/cgeo/geocaching/maps/AbstractMap.java
- main/src/cgeo/geocaching/maps/CGeoMap.java
- main/src/cgeo/geocaching/maps/MapSettingsUtils.java
- main/src/cgeo/geocaching/maps/MapUtils.java
- main/src/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java
- main/src/cgeo/geocaching/maps/interfaces/MapActivityImpl.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
- main/src/cgeo/geocaching/ui/DateRangeSelector.java
minor issues for filtering #10673 #10688 #10667 #10659 #10664 partly #10666 partly #10672
> minor issues for filtering #10673 #10688 #10667 #10659 #10664 partly #10666 partly #10672

- main/src/cgeo/geocaching/connector/gc/GCConstants.java
- main/src/cgeo/geocaching/connector/gc/GCParser.java
Adapt parser patterns to changes in geocaching.com page
#10688
> Fix #10688: Adapt patterns to changes in login page

- main/src/cgeo/geocaching/ui/DateTimeEditor.java
fix #10687: fix npe on date select
> fix #10687: fix npe on date select

- main/res/values/strings.xml
- main/src/cgeo/geocaching/downloader/AbstractDownloader.java
- main/src/cgeo/geocaching/downloader/BRouterTileDownloader.java
- main/src/cgeo/geocaching/downloader/ReceiveDownloadActivity.java
Automatically overwrite existing files on receiving a downloaded file
> auto-overwrite in map downloader (fix #10695)

- main/res/layout/cache_filter_activity.xml
- main/res/layout/checkbox_item.xml
- main/res/layout/itemrangeslider_view.xml
- main/res/values/strings.xml
- main/res/values/styles.xml
- main/src/cgeo/geocaching/enumerations/CacheType.java
- main/src/cgeo/geocaching/filters/core/DifficultyGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/DistanceGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/FavoritesGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/GeocacheFilterType.java
- main/src/cgeo/geocaching/filters/core/NumberRangeGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/TerrainGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/ValueGroupGeocacheFilter.java
- main/src/cgeo/geocaching/filters/gui/BaseFilterViewHolder.java
- main/src/cgeo/geocaching/filters/gui/CheckboxFilterViewHolder.java
- main/src/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java
- main/src/cgeo/geocaching/filters/gui/GeocacheFilterActivity.java
- main/src/cgeo/geocaching/filters/gui/ItemRangeSelectorViewHolder.java
- main/src/cgeo/geocaching/filters/gui/ToggleButtonFilterViewHolder.java
- main/src/cgeo/geocaching/filters/gui/ValueGroupFilterAccessor.java
- main/src/cgeo/geocaching/ui/ImageListFragment.java
- main/src/cgeo/geocaching/ui/ViewUtils.java
- main/src/cgeo/geocaching/ui/recyclerview/ManagedListAdapter.java
fix part of #10661: basic vs advanced filter mode
> fix part of #10661: basic vs advanced filter mode

- main/src/cgeo/geocaching/export/GpxSerializer.java
- main/src/cgeo/geocaching/files/GPXParser.java
Extends our GPX export and import to write/read assigned emoji using a cgeo extension to the GPX format
> support exporting/importig assigned emoji in GPX (fix #10700)

- main/src/cgeo/geocaching/filters/core/AttributesGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/BaseGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/DateFilter.java
- main/src/cgeo/geocaching/filters/core/DateRangeGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/DifficultyGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/GeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/IGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/LogicalGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/NumberRangeGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/SizeGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/StatusGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/StringGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/TerrainGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/TypeGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/ValueGroupGeocacheFilter.java
- main/src/cgeo/geocaching/filters/gui/AttributesFilterViewHolder.java
- main/src/cgeo/geocaching/filters/gui/CheckboxFilterViewHolder.java
- main/src/cgeo/geocaching/filters/gui/FavoritesFilterViewHolder.java
- main/src/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java
- main/src/cgeo/geocaching/filters/gui/GeocacheFilterActivity.java
- main/src/cgeo/geocaching/filters/gui/ItemRangeSelectorViewHolder.java
- main/src/cgeo/geocaching/filters/gui/StatusFilterViewHolder.java
- main/src/cgeo/geocaching/filters/gui/ToggleButtonFilterViewHolder.java
- main/src/cgeo/geocaching/filters/gui/ValueGroupFilterAccessor.java
- main/src/cgeo/geocaching/storage/DataStore.java
- main/src/cgeo/geocaching/ui/ToggleButtonGroup.java
fix filtering issues with display, grouping and cache count
> fix filtering issues with display, grouping and cache count

- main/res/layout/map_settings_dialog.xml
- main/src/cgeo/geocaching/connector/gc/GCMap.java
- main/src/cgeo/geocaching/filters/core/DateFilter.java
- main/src/cgeo/geocaching/filters/core/ValueGroupGeocacheFilter.java
- main/src/cgeo/geocaching/maps/CGeoMap.java
- main/src/cgeo/geocaching/maps/MapSettingsUtils.java
- main/src/cgeo/geocaching/maps/MapUtils.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
- main/src/cgeo/geocaching/ui/DateRangeSelector.java
- main/src/cgeo/geocaching/ui/DateTimeEditor.java
fix #10659: remove filter from mapsettings plus some bugfixes
Like for almost all changes I do on filter currently, I find bugs, code-dirties and not-yet-working-stuff to left and right which I fix on the way. Current line of PRs is almost not reviewable, I will make it quick again.
I feel the new filter becomes more and more usable...
> fix #10659: remove filter from mapsettings plus some bugfixes

- main/src/cgeo/geocaching/InstallWizardActivity.java
fix #10690: include backuputils callback into installwizard onactivityresults
> fix #10690: include backuputils callback into installwizard onactivityresults

- main/src/cgeo/geocaching/AboutActivity.java
Link to our new full changelog from about:changelog page in app
Superseeds #10665
> Link about:changelog to new full changelog (fix #10662)

- main/src/cgeo/geocaching/CacheListActivity.java
fix #7540: always refresh offline lists in cachelistactivity.onresume
> fix #7540: always refresh offline lists in cachelistactivity.onresume

- main/res/layout/cache_filter_activity.xml
- main/res/menu/map_activity.xml
- main/res/values/strings.xml
- main/src/cgeo/geocaching/filters/gui/GeocacheFilterActivity.java
- main/src/cgeo/geocaching/maps/CGeoMap.java
- main/src/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
- main/src/cgeo/geocaching/ui/ViewUtils.java
fix #10715, fix #10717, fix #10716: various filter-related small issues
Also revises the already closed #10659: force-adds filter icon to map action bar and removes its text
> fix #10715, fix #10717, fix #10716: various filter-related small issues

- main/res/values/strings.xml
- main/src/cgeo/geocaching/filters/core/GeocacheFilterType.java
- main/src/cgeo/geocaching/filters/gui/GeocacheFilterActivity.java
- main/src/cgeo/geocaching/ui/TextSpinner.java
- main/src/cgeo/geocaching/utils/TextUtils.java
fix #10672: add grouping to filters
> fix #10672: add grouping to filters

- main/src/cgeo/geocaching/maps/CGeoMap.java
Fixing some low hanging fruit/long standing TODOs/FIXMEs.
> Remove globals and pass data inside the `UPDATE_PROGRESS` message

- main/src/cgeo/geocaching/CacheDetailActivity.java
Fixes not working long click on waypoint coordinates in waypoint list
added the callback of the context-menu functions as for cache-coordinates
fix #6711
> Fix copy coordinate via long click on waypoint coordinates (fix #6711)

- main/res/values/preference_keys.xml
- main/res/values/strings.xml
- main/res/xml/preferences.xml
- main/src/cgeo/geocaching/MainActivity.java
- main/src/cgeo/geocaching/settings/Settings.java
- main/src/cgeo/geocaching/settings/SettingsActivity.java
Removes the option to have a transparent mainscreen
> remove mainscreen transparency option (fix #10744)

- main/src/cgeo/geocaching/ui/ToggleButton.java
> fix toggle button color issue

- main/res/values/strings.xml
- main/src/cgeo/geocaching/SearchActivity.java
- main/src/cgeo/geocaching/connector/gc/GCMap.java
- main/src/cgeo/geocaching/connector/gc/GCWebAPI.java
- main/src/cgeo/geocaching/filters/core/AttributesGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/DateFilter.java
- main/src/cgeo/geocaching/filters/core/DateRangeGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/FavoritesGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/GeocacheFilterType.java
- main/src/cgeo/geocaching/filters/core/IGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/LastFoundGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/LogEntryGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/LogsCountGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/NumberRangeFilter.java
- main/src/cgeo/geocaching/filters/core/NumberRangeGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/StatusGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/StringFilter.java
- main/src/cgeo/geocaching/filters/core/StringGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/ValueGroupGeocacheFilter.java
- main/src/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java
- main/src/cgeo/geocaching/filters/gui/LogEntryFilterViewHolder.java
- main/src/cgeo/geocaching/filters/gui/LogsCountFilterViewHolder.java
- main/src/cgeo/geocaching/models/Geocache.java
- main/src/cgeo/geocaching/storage/SqlBuilder.java
- main/src/cgeo/geocaching/utils/LocalizationUtils.java
fix #10635: added filters for log entry, last found and log counts
> fix #10635: added filters for log entry, last found and log counts

- main/res/layout/map_settings_dialog.xml
- main/res/values/strings.xml
- main/res/values/styles.xml
- main/src/cgeo/geocaching/maps/MapSettingsUtils.java
> use toggle button group in quicksettings

- main/src/cgeo/geocaching/ui/dialog/Dialogs.java
This will change the initial expanding to 80% (instead of 50%). The quick settings popup will therefore now even fill more screen than the old alert dialog did. A big plus for intuitive and fast usability... Furthermore, many many other bugs are fixed.
> Bottom sheet fixes

- main/res/values/strings.xml
- main/src/cgeo/geocaching/connector/gc/GCMap.java
- main/src/cgeo/geocaching/connector/oc/OCApiLiveConnector.java
- main/src/cgeo/geocaching/connector/oc/OkapiClient.java
- main/src/cgeo/geocaching/enumerations/CacheSize.java
- main/src/cgeo/geocaching/filters/core/FavoritesGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/GeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/LogsCountGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/StatusGeocacheFilter.java
- main/src/cgeo/geocaching/filters/gui/StatusFilterViewHolder.java
- main/src/cgeo/geocaching/network/Parameters.java
related to #10633: add filter search to oc
> related to #10633: add filter search to oc

- main/build.gradle
- fix typo and simplify import
- Simplify and optimize comments
> clean up main build.gradle

- main/res/values/preference_keys.xml
- main/res/values/strings.xml
- main/res/xml/preferences.xml
- main/src/cgeo/geocaching/connector/gc/GCWebAPI.java
- main/src/cgeo/geocaching/connector/oc/OkapiClient.java
- main/src/cgeo/geocaching/maps/CGeoMap.java
- main/src/cgeo/geocaching/maps/MapSettingsUtils.java
- main/src/cgeo/geocaching/maps/MapUtils.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/caches/WaypointsOverlay.java
- main/src/cgeo/geocaching/settings/Settings.java
- main/src/cgeo/geocaching/storage/DataStore.java
- main/src/cgeo/geocaching/utils/SystemInformation.java
- tests/src-android/cgeo/geocaching/CgeoApplicationTest.java
- tests/src-android/cgeo/geocaching/connector/gc/GCConnectorTest.java
- tests/src-android/cgeo/geocaching/storage/DataStoreTest.java
fix #5738, fix #10287, fix #10735: add own, found and offline log hide to map quick settings
> fix #5738, fix #10287, fix #10735: add own, found and offline log hide to map quick settings

- main/src/cgeo/geocaching/filters/core/BaseGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/GeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/StatusGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/StringFilter.java
- main/src/cgeo/geocaching/filters/gui/StatusFilterViewHolder.java
- main/src/cgeo/geocaching/utils/TextUtils.java
- main/src/cgeo/geocaching/utils/expressions/ExpressionParser.java
- tests/src-android/cgeo/geocaching/utils/TextUtilsTest.java
- tests/src/cgeo/geocaching/utils/expressions/ExpressionParserTest.java
fix #10796: make filter configuration more human-readable/writeable
> fix #10796: make filter configuration more human-readable/writeable

- main/src/cgeo/geocaching/AboutActivity.java
- main/src/cgeo/geocaching/activity/AVPActivity.java
- recreate system info on subsequent calls
- also adds unregisterOnPageChangeCallback in `onDestroy()`
> rework viewpager and about pages to fix #10832

- main/res/layout/chip_choice_view.xml
- main/res/values/styles.xml
- main/src/cgeo/geocaching/filters/gui/ChipChoiceFilterViewHolder.java
- main/src/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java
fix #10851; use ChipChoice for Cache Size Filter:
> fix #10851; use ChipChoice for Cache Size Filter

- main/src/cgeo/geocaching/models/WaypointParser.java
- tests/src/cgeo/geocaching/models/WaypointParserTest.java
Fix bug in extracting user note for waypoint with formula from personal note.
Following linebreak was not considered correctly and the next waypoint was extracted as user note for the waypoint
> Fix bug in extracting user note for waypoint with formula

- main/res/drawable/ic_menu_found.xml
- main/src/cgeo/geocaching/maps/MapSettingsUtils.java
In map settings:
use smiley for found caches
use man with flag-pole for own caches
use pencil for caches with offline log
#10850
> Change own and found icon (fix #10850)

- main/res/layout/cache_filter_generic_string.xml
- main/res/values/strings.xml
- main/res/values/styles.xml
- main/src/cgeo/geocaching/connector/oc/OkapiClient.java
- main/src/cgeo/geocaching/filters/core/GeocacheFilterType.java
- main/src/cgeo/geocaching/filters/core/LocationGeocacheFilter.java
- main/src/cgeo/geocaching/filters/gui/BaseFilterViewHolder.java
- main/src/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java
- main/src/cgeo/geocaching/filters/gui/StringFilterViewHolder.java
- main/src/cgeo/geocaching/storage/DataStore.java
- main/src/cgeo/geocaching/utils/EmojiUtils.java
fix-attempt for #8716: add location filter as text filter with suggestions, fix oc location parsing, introduce material testlayout
> fix-attempt for #8716: add location filter as text filter with suggestions, fix oc location parsing, introduce material testlayout

- main/res/layout/cache_filter_generic_string.xml
make search text fields clearable (mini change)
> make search text fields clearable (mini change)

- main/res/layout/search_activity.xml
- main/res/values/styles.xml
Use material TextInputFields with acticated "clear input" button for our searches on mainscreen:
Related to #10763 and #10885
> use material TextInputFields for mainscreen searches (rel. to #10763)

- main/src/cgeo/geocaching/filters/gui/CheckboxFilterViewHolder.java
- main/src/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java
- main/src/cgeo/geocaching/filters/gui/ValueGroupFilterAccessor.java
- main/src/cgeo/geocaching/ui/ImageParam.java
- main/src/cgeo/geocaching/ui/ViewUtils.java
- main/src/cgeo/geocaching/utils/EmojiUtils.java
* add emojis to stored-list-filter and create ImageParam class
* also introduces the class "ImageParam" to pass image parameters to methods. 
* Follow-up idea óf second point would be to create similar classes/builders "TextParam", "ActionParam" etc and use these to reduce the necessary overloads in utility classes like "Dialogs" or "ViewUtils" which are currently necessary e.g. to pass Texts as id OR String
@moving-bits I would appreciate a review by you because I extended "`EmojiUtils`" and could really use your opinion on this.
> add emojis to stored-list-filter and create ImageParam class

- main/src/cgeo/geocaching/calculator/FormulaParser.java
- main/src/cgeo/geocaching/models/WaypointParser.java
- tests/src/cgeo/geocaching/models/WaypointParserTest.java
export coordinates to PN, if formula has not PLAIN-format.
fix regular expression to fit to user note with newline and ' as end of formula
fix #10876
> Fix export of calculated WP to PN (fix #10876 )

- main/src/cgeo/geocaching/utils/SystemInformation.java
Show screen resolution in system information:
> show screen resolution in system information

- main/res/values/strings.xml
- main/src/cgeo/geocaching/connector/AbstractConnector.java
- main/src/cgeo/geocaching/connector/IConnector.java
- main/src/cgeo/geocaching/connector/ec/ECConnector.java
- main/src/cgeo/geocaching/connector/ga/GeocachingAustraliaConnector.java
- main/src/cgeo/geocaching/connector/gc/GCConnector.java
- main/src/cgeo/geocaching/connector/gc/GCMap.java
- main/src/cgeo/geocaching/connector/ge/GeopeitusConnector.java
- main/src/cgeo/geocaching/connector/internal/InternalConnector.java
- main/src/cgeo/geocaching/connector/lc/LCConnector.java
- main/src/cgeo/geocaching/connector/oc/OCConnector.java
- main/src/cgeo/geocaching/connector/oc/OkapiClient.java
- main/src/cgeo/geocaching/connector/su/SuConnector.java
- main/src/cgeo/geocaching/connector/tc/TerraCachingConnector.java
- main/src/cgeo/geocaching/connector/wm/WaymarkingConnector.java
- main/src/cgeo/geocaching/filters/core/GeocacheFilterType.java
- main/src/cgeo/geocaching/filters/core/OriginGeocacheFilter.java
- main/src/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java
fix #10880: add origin filter to new filter framework
> fix #10880: add origin filter to new filter framework

- main/src/cgeo/geocaching/connector/gc/GCMap.java
related to PR #10910: fix code review comment found by @bekuno after merge
> related to PR #10910: fix code review comment found after merge

- main/src/cgeo/geocaching/CacheDetailActivity.java
- fix NPE on editing a cache description
> avoid NPE on editing cache description (fix #10926)

- main/res/layout/dialog_edittext.xml
- main/res/layout/udc_create.xml
- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/ui/dialog/Dialogs.java
- migrate edit cache name to TextInputLayout
- migrate edit cache description to TextInputLayout (multi line, scrolling)
- migrate 'create UDC' to TextInputLayout
> migrate several input diealogs to TextInputLayout

- main/res/layout/button_icon_view.xml
- main/res/layout/cache_filter_activity.xml
- main/res/layout/cache_filter_list_item.xml
- main/res/layout/cachedetail_description_page.xml
- main/res/layout/cachedetail_details_page.xml
- main/res/layout/downloader_activity.xml
- main/res/layout/downloader_item.xml
- main/res/layout/imagelist_fragment.xml
- main/res/layout/pocketquery_item.xml
- main/res/layout/popup.xml
- main/res/layout/twotexts_button_image_item.xml
- main/res/layout/twotexts_twobuttons_item.xml
- main/res/values/styles.xml
- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/filters/gui/AttributesFilterViewHolder.java
- main/src/cgeo/geocaching/maps/routing/RouteSortActivity.java
- main/src/cgeo/geocaching/settings/ViewSettingsActivity.java
- main/src/cgeo/geocaching/ui/EditNoteDialog.java
- main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateDialog.java
- main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java
Switching from ImageButton to Button, so the border of the icon-button is shown:
rel #10769 
I left the folder and map - element without border:
I left the "reorder"-button without border:
I still have problems with buttons, for which the icon ist set programatically:
> Switch from ImageButton to Button

- main/src/cgeo/geocaching/CacheListActivity.java
- main/src/cgeo/geocaching/filters/core/StatusGeocacheFilter.java
- main/src/cgeo/geocaching/maps/CGeoMap.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
- main/src/cgeo/geocaching/models/Geocache.java
fix #10921: adjust filter bar when returning to subactivity
> fix #10921: adjust filter bar when returning to subactivity

- main/res/layout/actionbar_popup.xml
- main/res/layout/waypoint_popup.xml
- main/res/menu/cache_options.xml
- main/res/values/strings.xml
- main/src/cgeo/geocaching/AbstractDialogFragment.java
- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/CacheMenuHandler.java
- main/src/cgeo/geocaching/CachePopupFragment.java
- main/src/cgeo/geocaching/WaypointPopupFragment.java
Replace our old badly designed "popup actionbar layout" with androidX toolbar...
| old | new
|-|-|
|![grafik](https://user-images.githubusercontent.com/64581222/122559568-cc0f3d80-d03f-11eb-903c-b58bc0e79c33.png)|![grafik](https://user-images.githubusercontent.com/64581222/122559045-193edf80-d03f-11eb-9295-6603e45269a8.png)
> refactor cache/waypoints popup to androidX toolbar (fix #10757)

- main/res/layout/dialog_title_button_button.xml
- main/src/cgeo/geocaching/CacheListActivity.java
- main/src/cgeo/geocaching/connector/internal/InternalConnector.java
- main/src/cgeo/geocaching/utils/EmojiUtils.java
add ImageView and Button to show the cacheTypeIcon correctly with tint and the button with border
rel #10948
did not find a solution yet for the small emojis :-(
> add ImageView and Button to show the cacheTypeIcon correct 

- main/res/layout/imageselect_activity.xml
- put "delete" button in first position
- then "cancel", then "ok"
> re-order buttons in ImageSelectActivity (fix #10960)

- main/res/color/chip_background_selector.xml
- main/res/color/chip_textcolor_selector.xml
- main/res/values/styles.xml
https://de.wikipedia.org/wiki/Farbenblindheit
> ...Bei dieser Erkrankung handelt es sich jedoch lediglich um eine Farbenfehlsichtigkeit (Farbenanomalie), die bei ca. 5 % der Bevölkerung (überwiegend Männern) vorliegt.
The current style has not enough contrast for people with color blindness, and even I (fortunately my eyes are OK ;-)) had trouble when the sun was shining...
Therefore, I would suggest using the "filter chip" style, where the difference is much easier to recognize...
> improve chip style

- main/src/cgeo/geocaching/maps/CGeoMap.java
- main/src/cgeo/geocaching/maps/MapSettingsUtils.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
> remove unused map settings parameter

- tests/src-android/cgeo/geocaching/connector/gc/GCParserTest.java
This reverts commit bfc871b60037bc95910fb2c2c402fab563a5f094.
> Revert "temporarily disable GC watchcount test which fails due to website changes"

- main/src/cgeo/geocaching/utils/EmojiUtils.java
shows emojis in better size.
Use method to get drawable for given dp-size (as suggested from @eddiemuc in https://github.com/cgeo/cgeo/issues/10948#issuecomment-864382447), use only one calculation from desired dp-size to helper-class `EmojiPaint`.
Set suitable fontSize for the textView
Right margin still does not look very good... probably I tried margins and padding, but probably at the wrong widget / place?
fix #10948
The margin are not well defined and too many columns for tablet-landscape-mode. 
I am looking for that, but did not find a solution yet: Number of columns is calculated in respect of the screen width, but the dialog does not use the maximum possible width. So how did I get the correct dialog-width?
> fix size for emojis in emoji-select-dialog (fix #10948)

- main/src/cgeo/geocaching/maps/CGeoMap.java
fix #10999: gm singlecacheview shall not be filtered
> fix #10999: gm singlecacheview shall not be filtered

- main/src/cgeo/geocaching/connector/gc/GCParser.java
Remove unused import from `GCParser` to satisfy CheckStyle and get builds back green
> fix checkstyle finding in GCParser

- main/src/cgeo/geocaching/maps/MapProviderFactory.java
> improve loc switch touch target (fix #10977)

- main/src/cgeo/geocaching/filters/gui/GeocacheFilterActivity.java
> [filter UI] add warning if changes would be dismissed

- main/res/layout/actionbar_popup.xml
- main/res/layout/navigation_action.xml
- main/res/values/styles.xml
use new toolbar-style for androidx-toolbar to set color correctly
fix #11006
> fix dark icons on dark toolbar (fix #11006)

- build.gradle
- cgeo-contacts/build.gradle
- main/AndroidManifest.xml
- main/build.gradle
- main/src/cgeo/geocaching/brouter/expressions/BExpressionMetaData.java
- main/src/cgeo/geocaching/brouter/util/DefaultFilesUtils.java
- main/src/cgeo/geocaching/storage/ContentStorage.java
- main/src/cgeo/geocaching/storage/DocumentContentAccessor.java
- main/src/cgeo/geocaching/storage/FileContentAccessor.java
- main/src/cgeo/geocaching/storage/PersistableFolder.java
- main/src/cgeo/geocaching/utils/FileUtils.java
This PR will switch c:geo to SDK 30 with all consequences (esp. no more usage of legacy storage access)
> switch to SDK 30

- main/src/cgeo/geocaching/maps/MapProviderFactory.java
While testing the latest nightly, I noticed that my first fix in #11038 does not work properly... Therefore, another try. This time it seems fine in the emulator ;-)
> improve loc switch touch target (another try)

- main/res/menu/cache_list_options.xml
Show text for map icon in cache list (if room)
> show text for map icon in cache list (if room, fix #11033)

- main/src/cgeo/geocaching/CacheListActivity.java
fix #10976: prevent jump to list start on activity back action for cache list
> fix #10976: prevent jump to list start on activity back action for cache list

- main/src/cgeo/geocaching/maps/mapsforge/v6/caches/AbstractCachesOverlay.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/caches/CachesBundle.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/caches/GeoitemLayer.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/caches/GeoitemLayers.java
fix #11054: make waypoints hide on filter
> fix #11054: make waypoints hide on filter

- main/res/layout/popup.xml
- main/src/cgeo/geocaching/AbstractDialogFragment.java
- main/src/cgeo/geocaching/CachePopupFragment.java
- main/src/cgeo/geocaching/WaypointPopupFragment.java
- display cache geocode / waypoint "wp code" as popup title
- ~adjust "more details" button height to icon buttons~ (removed from this PR)
> optimize popup titlebar (fix #11022)

- main/res/layout/trackable_details_view.xml
Set colors for trackable's goal and detail text
> adjust trackable details colors (fix #11074)

- main/res/layout/cache_filter_list_item.xml
- main/res/layout/imagelist_item.xml
- main/res/layout/map_settings_dialog.xml
- main/res/layout/popup.xml
- main/res/layout/twotexts_button_image_item.xml
- main/res/values/dimens.xml
- main/res/values/styles.xml
* change button size and icon size:
button size: 42dp
icon size: 30dp
* adapt height of "Details"-button in cache-popup
* align routing-buttons in map-settings
rel #11065
screenshots:
https://github.com/cgeo/cgeo/issues/11065#issuecomment-873455080
https://github.com/cgeo/cgeo/issues/11065#issuecomment-873455127
https://github.com/cgeo/cgeo/issues/11065#issuecomment-873455684
https://github.com/cgeo/cgeo/issues/11065#issuecomment-873455309
> decrease button size, increase icon size

- main/res/values/strings.xml
- main/res/values/strings_not_translatable.xml
- main/src/cgeo/geocaching/AboutActivity.java
Update about: contributors' page to reflect current state
> update contributors' page

- main/res/layout/about_license_page.xml
- main/res/layout/about_system_page.xml
- main/res/layout/about_version_page.xml
- main/res/values/styles.xml
Set correct text colors for about pages (instead of using built-in default colors)
> align colors for about pages

- main/res/layout/main_activity.xml
- main/res/values/strings.xml
- main/src/cgeo/geocaching/MainActivity.java
- main/src/cgeo/geocaching/settings/Settings.java
> disable global cache type filter (fix #11095)

- .idea/checkstyle-idea.xml
- main/src/cgeo/geocaching/CacheListActivity.java
- main/src/cgeo/geocaching/connector/ec/ECApi.java
- main/src/cgeo/geocaching/connector/ec/ECConnector.java
- main/src/cgeo/geocaching/connector/lc/LCApi.java
- main/src/cgeo/geocaching/connector/lc/LCConnector.java
- main/src/cgeo/geocaching/connector/su/SuApi.java
- main/src/cgeo/geocaching/filters/core/GeocacheFilter.java
- main/src/cgeo/geocaching/loaders/CoordsGeocacheListLoader.java
- main/src/cgeo/geocaching/loaders/FinderGeocacheListLoader.java
- main/src/cgeo/geocaching/loaders/OwnerGeocacheListLoader.java
fix #10633: replace isearchbyxxx with isearchbyfilter
> fix #10633: replace isearchbyxxx with isearchbyfilter

- main/src/cgeo/geocaching/CacheDetailActivity.java
fix #11111: allow opening cache details without NPE in low power mode
> fix #11111: allow opening cache details without NPE in low power mode

- main/res/drawable/star_accent_color.xml
- main/src/cgeo/geocaching/filters/core/StatusGeocacheFilter.java
use star.svg with colorAccent as tint-color
fix #11117
> use accent color in icon for "has own vote" (fix #11117)

- main/src/cgeo/geocaching/AboutActivity.java
Fix unpacking of bundled start page id for about pages to be able to display changelog on new installs
> go to about:changelog on new installs (fix #11114)

- main/res/layout/pocketquery_item.xml
- main/res/layout/pq_actionbar.xml
- main/src/cgeo/geocaching/connector/gc/PocketQueryListAdapter.java
- avoid pq info text running into buttons
- enable line break for info text
- disable info line if no info is available
- fix actionbar text color for pq list
> fix pq list formatting (rel. to #11127)

- main/AndroidManifest.xml
declare chrome package name in AndroidManifest.xml to re-enable chrome webview
> add chrome package to AndroidManifest.xml (fix #11136)

- main/src/cgeo/geocaching/CacheDetailActivity.java
fix #11140: fix npe on opening cache link
> fix #11140: fix npe on opening cache link

- main/src/cgeo/geocaching/filters/core/DistanceGeocacheFilter.java
- main/src/cgeo/geocaching/settings/Settings.java
- main/src/cgeo/geocaching/sorting/DistanceComparator.java
- main/src/cgeo/geocaching/sorting/NameComparator.java
- main/src/cgeo/geocaching/sorting/PopularityComparator.java
- main/src/cgeo/geocaching/sorting/PopularityRatioComparator.java
- main/src/cgeo/geocaching/sorting/RatingComparator.java
- main/src/cgeo/geocaching/storage/DataStore.java
- main/src/cgeo/geocaching/ui/CacheListAdapter.java
rel to #11132: fix few sort issues, disable list load limit by default
* Disables "load list limit" by default
* Fix SQl sorting issues for distance, favorites, votes, names
* Fixes a bug at "event detection"
> rel to #11132: fix few sort issues, disable list load limit by default

- main/src/cgeo/geocaching/CacheListActivity.java
- main/src/cgeo/geocaching/connector/ConnectorFactory.java
- main/src/cgeo/geocaching/connector/capability/ISearchByFilter.java
- main/src/cgeo/geocaching/connector/ec/ECConnector.java
- main/src/cgeo/geocaching/connector/gc/GCConnector.java
- main/src/cgeo/geocaching/connector/lc/LCConnector.java
- main/src/cgeo/geocaching/connector/oc/OCApiLiveConnector.java
- main/src/cgeo/geocaching/connector/oc/OkapiClient.java
- main/src/cgeo/geocaching/connector/oc/OkapiService.java
- main/src/cgeo/geocaching/connector/su/SuConnector.java
- main/src/cgeo/geocaching/filters/core/GeocacheFilter.java
- main/src/cgeo/geocaching/loaders/AbstractSearchLoader.java
- main/src/cgeo/geocaching/loaders/CoordsGeocacheListLoader.java
- main/src/cgeo/geocaching/loaders/KeywordGeocacheListLoader.java
- main/src/cgeo/geocaching/loaders/OwnerGeocacheListLoader.java
- main/src/cgeo/geocaching/sorting/VisitComparator.java
- main/src/cgeo/geocaching/ui/CacheListAdapter.java
fix #11149: load owners correctly from connectors
Also fixes a few bugs I found left and right:
*  sort order of history in conjunction with load limit is now correct
* oc connector handles user id -> user uuid correctly now
> fix #11149: load owners correctly from connectors

- main/src/cgeo/geocaching/filters/gui/StatusFilterViewHolder.java
fix #11120: fix cut-off of status filter checkbox, remove width adjustments
> fix #11120: fix cut-off of status filter checkbox, remove width adjustments

- main/src/cgeo/geocaching/activity/TabbedViewPagerActivity.java
On opening cache details some of the sub pages cannot be created as the data is not yet available. This led to "last page shown" being reset.
This PR attempts to fix this by remembering the requested page and retrying to display it on arrival of new data until it is available (which normally happens in a fraction of a second).
> retry to display page requested initially (fix #10979)

- main/res/values/strings_not_translatable.xml
- main/src/cgeo/geocaching/utils/DebugUtils.java
Add c:geo version string to "report problem"'s e-mail subject
> add version string to 'report problem' subject (fix #11164)

- main/src/cgeo/geocaching/apps/cache/AbstractGeneralApp.java
- main/src/cgeo/geocaching/apps/cache/WhereYouGoApp.java
- main/src/cgeo/geocaching/apps/navi/AbstractPointNavigationApp.java
- main/src/cgeo/geocaching/apps/navi/AbstractRadarApp.java
- main/src/cgeo/geocaching/apps/navi/CacheNavigationApp.java
- main/src/cgeo/geocaching/apps/navi/CompassApp.java
- main/src/cgeo/geocaching/apps/navi/GeopointNavigationApp.java
- main/src/cgeo/geocaching/apps/navi/GoogleMapsApp.java
- main/src/cgeo/geocaching/apps/navi/GoogleMapsDirectionApp.java
- main/src/cgeo/geocaching/apps/navi/GoogleNavigationApp.java
- main/src/cgeo/geocaching/apps/navi/InternalMap.java
- main/src/cgeo/geocaching/apps/navi/LocusApp.java
- main/src/cgeo/geocaching/apps/navi/MapsMeApp.java
- main/src/cgeo/geocaching/apps/navi/NavigationSelectionActionProvider.java
- main/src/cgeo/geocaching/apps/navi/OruxMapsApp.java
- main/src/cgeo/geocaching/apps/navi/OsmAndApp.java
- main/src/cgeo/geocaching/apps/navi/StreetviewApp.java
- main/src/cgeo/geocaching/apps/navi/SygicNavigationApp.java
- main/src/cgeo/geocaching/apps/navi/WaypointNavigationApp.java
Fix navigation target selection popup theming
> fix theming of navigation target selection popup (fix #11147)

- main/res/layout/cachelist_spinneritem.xml
Found a way which seems to fix that issue. Not sure about side effects though due to my limited knowledge of this layout handling.
Therefore please review for unwanted effects.
#11197
|Current release with XL fonts |This PR with XL fonts|
|---|---|
|![Screenshot_20210712-151045](https://user-images.githubusercontent.com/949669/125294478-969afe80-e324-11eb-8593-387aaaa24782.png)|![Screenshot_20210712-151428](https://user-images.githubusercontent.com/949669/125294512-9c90df80-e324-11eb-9c44-0ce1a4c3e0d1.png)
> Fix #11197 - Avoid cut of list spinner with large fonts

- main/src/cgeo/geocaching/activity/TabbedViewPagerActivity.java
add NPE safeguard in `TabbedViewPagerActivity.onDestroy()`
> add NPE safeguard in TabbedViewPagerActivity (fix #11207)

- main/res/layout/about_system_page.xml
make the two buttons in about:system info fixed (non-scrolling)
> make system info buttons non-scrolling (fix #11151)

- main/src/cgeo/geocaching/connector/gc/GCConstants.java
adapt regular expression for retrieving the personal note from the GC-website to newest changes
fix #11232
>  fix regular expression to fetch personal note at gc.com (fix #11232)

- main/res/values/strings.xml
- main/src/cgeo/geocaching/settings/StartWebviewActivity.java
Add safeguard to prevent `IndexOutOfBoundsException` on "open in browser" (which has been reported on play store)
> avoid out of bounds error if no browser has been found

- main/src/cgeo/geocaching/connector/oc/OkapiClient.java
fix #11208: disallow returning of archived caches from oc
> fix #11208: disallow returning of archived caches from oc

- main/src/cgeo/geocaching/connector/gc/GCMap.java
- main/src/cgeo/geocaching/connector/gc/GCWebAPI.java
fix #11246: add gcvote request to gc online search results
> fix #11246: add gcvote request to gc online search results

- main/src/cgeo/geocaching/storage/ContentStorage.java
- main/src/cgeo/geocaching/storage/DocumentContentAccessor.java
fix #11236: add guards for initializer and createdir
> fix #11236: add guards for initializer and createdir

- main/res/layout/search_activity.xml
- main/res/values/strings.xml
- main/src/cgeo/geocaching/SearchActivity.java
- main/src/cgeo/geocaching/connector/AbstractConnector.java
- main/src/cgeo/geocaching/storage/DataStore.java
fix #11103: 
This PR will remove the function "search by found-by":
In the following screenshot you can see that it can no longer be seen :-)
(was between "Keywords" search and "Hidden by" search)
> fix #11103: remove "search by found-by" and "caches found"

- main/src/cgeo/geocaching/CacheListActivity.java
fix #11189: stay at list position after list refresh
> fix #11189: stay at list position after list refresh

- main/res/values/numbers.xml
- main/res/xml/preferences.xml
- main/src/cgeo/geocaching/settings/Settings.java
Set the load limit for lists from 10000 to 50000 for testing purpose. Should be probabaly adapted before going into production.
#rel 11191
> Set max limit for list to 50k for testing purpose (rel #11191)

- main/src/cgeo/geocaching/settings/Settings.java
See https://github.com/cgeo/cgeo/pull/11277#discussion_r673727292
> PR #11277 follow up

- main/src/cgeo/geocaching/log/CacheLogsViewCreator.java
remove and re-add header views in cache logs list to update them
> fix cache logs header not being updated (fix #11272)

- main/src/cgeo/geocaching/filters/gui/GeocacheFilterActivity.java
fix #11274: make filteractivity able to handle simple basic filters
> fix #11274: make filteractivity able to handle simple basic filters

- main/src/cgeo/geocaching/utils/MapMarkerUtils.java
Since dot_black has been changed to a vector drawable the size calculation needs to be adapted
> make another calculation vectordrawable compatible (rel. to #11248)

- main/res/menu/cache_list_options.xml
- main/res/values/strings.xml
- main/src/cgeo/geocaching/CacheListActivity.java
- main/src/cgeo/geocaching/command/DeleteListCommand.java
- main/src/cgeo/geocaching/list/StoredList.java
- main/src/cgeo/geocaching/storage/DataStore.java
- main/src/cgeo/geocaching/ui/dialog/Dialogs.java
- restore "remove list" dialog (reverts #11182)
- add option "do not ask me again" on a per-list basis
- add option to reset this flag for a list
|new dialog option|option to reset flag|option is disabled if flag not set|
|---|---|---|
|![image](https://user-images.githubusercontent.com/3754370/126626592-93ce32b5-e302-4146-90ab-0318424e0704.png)|![image](https://user-images.githubusercontent.com/3754370/126626604-e63562e7-23ba-46b1-8b64-285eb926269f.png)|![image](https://user-images.githubusercontent.com/3754370/126626619-93cd13e8-4933-44d0-9ec8-0f69c94b9ef8.png)|
> "remove list" optimizations

- main/src/cgeo/geocaching/settings/Settings.java
fix #11311: filter-related, migrate prelegacy excludefound clients correctly
> fix #11311: filter-related, migrate prelegacy excludefound clients correctly

- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/caches/CachesBundle.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/caches/LiveCachesOverlay.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/caches/StoredCachesOverlay.java
fix #11316: make sure filtercontext is set in cache overlays (fixes NPE)
> fix #11316: make sure filtercontext is set in cache overlays (fixes NPE)

- main/res/values/strings.xml
- main/src/cgeo/geocaching/connector/gc/GCConnector.java
- main/src/cgeo/geocaching/connector/gc/GCMap.java
- main/src/cgeo/geocaching/connector/oc/OCApiLiveConnector.java
- main/src/cgeo/geocaching/connector/oc/OkapiClient.java
- main/src/cgeo/geocaching/filters/core/DifficultyAndTerrainGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/GeocacheFilterType.java
- main/src/cgeo/geocaching/filters/gui/DifficultyAndTerrainFilterViewHolder.java
- main/src/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java
- main/src/cgeo/geocaching/filters/gui/GeocacheFilterActivity.java
- main/src/cgeo/geocaching/filters/gui/ItemRangeSelectorViewHolder.java
- main/src/cgeo/geocaching/ui/ItemRangeSlider.java
add new compact filter for difficulty and terrain.
Scale for range is only shown once.
I created a new GeocacheFilter and FilterViewHolder, which uses the existing ones for Difficulty and Terrain internally. 
fix #11180
> add compact D/T filter (fix #11180)

- main/res/layout/cache_filter_generic_string.xml
- main/res/layout/textspinner_view.xml
- main/src/cgeo/geocaching/filters/gui/LogsCountFilterViewHolder.java
- main/src/cgeo/geocaching/ui/ViewUtils.java
fix #11312: use spinner button style for logscount and textfilter
> fix #11312: use spinner button style for logscount and textfilter

- main/src/cgeo/geocaching/filters/gui/DifficultyAndTerrainFilterViewHolder.java
- main/src/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java
rel to PR #11296: remove usage of raw types
@murggel: found a way to make the raw types "unraw". 
Maybe at a later point in time we may try to remove the Difficulty/Terrain-Filters as well as their FilterType completely, since they are no longer used excplicitely anywhere. But this is not necessary for beta I believe :-)
> rel to PR #11296: remove usage of raw types

- main/res/values/strings.xml
- main/src/cgeo/geocaching/connector/gc/GCMap.java
- main/src/cgeo/geocaching/connector/oc/OCApiLiveConnector.java
- main/src/cgeo/geocaching/connector/oc/OkapiClient.java
- main/src/cgeo/geocaching/filters/core/GeocacheFilterType.java
- main/src/cgeo/geocaching/filters/core/RatingGeocacheFilter.java
- main/src/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java
add a rating filter to the filter framework
> add rating filter (fix #11301)

- main/res/values/strings.xml
- main/src/cgeo/geocaching/CacheListActivity.java
- main/src/cgeo/geocaching/activity/FilteredActivity.java
- main/src/cgeo/geocaching/maps/AbstractMap.java
- main/src/cgeo/geocaching/maps/CGeoMap.java
- main/src/cgeo/geocaching/maps/MapUtils.java
- main/src/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
- main/src/cgeo/geocaching/ui/dialog/SimpleDialog.java
- main/src/cgeo/geocaching/utils/FilterUtils.java
open filter-selection with long click on menu-item or filter-bar 
option to clear the current filter
* refresh of the map is currently (sometimes?) not working correct
fix #11202
> open filter-selection with long click (fix #11202)

- main/src/cgeo/geocaching/enumerations/StatusCode.java
- main/src/cgeo/geocaching/log/LogCacheActivity.java
- main/src/cgeo/geocaching/settings/AbstractCredentialsAuthorizationActivity.java
- main/src/cgeo/geocaching/ui/TextParam.java
fix #11266: extent TextParam to support CharSequence concat, use it in error messages
> fix #11266: extent TextParam to support CharSequence concat, use it in error messages

- main/res/values/preference_keys.xml
- main/src/cgeo/geocaching/connector/lc/LCApi.java
- main/src/cgeo/geocaching/settings/Settings.java
- main/templates/keys.xml
- templates/private.properties
fixes broken ALC functionality
> ALC no longer working (fix: #11001)

- main/src/cgeo/geocaching/TrackableActivity.java
- main/src/cgeo/geocaching/log/TrackableLogsViewCreator.java
Fixes both NPE on opening trackable details page and fragment error due to invalid fragment id
> fix NPE on opening trackable details page (fix #11332)

- main/src/cgeo/geocaching/maps/google/v2/GoogleMapView.java
- main/src/cgeo/geocaching/storage/extension/OneTimeDialogs.java
change map rotation notice into a OneTimeDialog (will be shown until "do not ask again" checkbox is set)
> change map rotation notice into OneTimeDialog (fix #11336)

- main/src/cgeo/geocaching/filters/core/DifficultyAndTerrainGeocacheFilter.java
- main/src/cgeo/geocaching/filters/gui/DifficultyAndTerrainFilterViewHolder.java
- main/src/cgeo/geocaching/utils/expressions/ExpressionConfig.java
- tests/src/cgeo/geocaching/utils/expressions/ExpressionConfigTest.java
fix non-functional PR-review-comments for the combined D/T filter (see comment https://github.com/cgeo/cgeo/pull/11296#discussion_r676138113)
* add method to get subConfig from ExpressionConfig
* use String-constant
* use text_label-style
rel #11180
> WIP - resolve left-overs from combined D/T filter

- main/src/cgeo/geocaching/connector/lc/LCApi.java
- check also for CONSUMER_KEY.isEmpty() to not call the LC endpoint
- integrate DATE_FORMAT in the using method because of using Locale.getDefault()
- externalize some multi used strings
- optimize some log strings
- added/corrected some Nullable/NonNull declaration
- optimized importCacheFromJSON() method
- other minor changes
> LCApi - resolve some lint/SonarLint problem and optimizations

- main/src/cgeo/geocaching/location/Viewport.java
- main/src/cgeo/geocaching/storage/DataStore.java
try to fix #11206: add some guards
> try to fix #11206: add some guards

- main/src/cgeo/geocaching/AboutActivity.java
- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/TrackableActivity.java
rel to #11204: make all fragment classes public (try to fix the problem by this)
> rel to #11204: make all fragment classes public (try to fix the problem by this)

- main/src/cgeo/geocaching/models/Trackable.java
fix #11373: make trackable loglist guaranteed writeable and final
> fix #11373: make trackable loglist guaranteed writeable and final

- main/src/cgeo/geocaching/maps/CGeoMap.java
fix #11374: handle progress 0 on cache download correctly, fix div by zero
> fix #11374: handle progress 0 on cache download correctly, fix div by zero

- main/src/cgeo/geocaching/calculator/ButtonData.java
- main/src/cgeo/geocaching/calculator/VariableData.java
- tests/src/cgeo/geocaching/calculator/FormulaParserTest.java
fix #11375: make classes used by CalcState serializable again
> fix #11375: make classes used by CalcState serializable again

- main/src/cgeo/geocaching/apps/navi/NavigationSelectionActionProvider.java
fix #11251: make NavigationSelectionActionProvider constructure take Context parameter
The underlying "Navi App infrastructure" is fully based on taking `Activity` parameters, so instead of switching them all to Context (although it seems possible for most (not all!) cases) I created some more intelligent "Activity extraction logic" to NavigationSelectionActionProvider 
Note that most often `NavigationSelectionActionProvider` gets a `ContextThemeWrapper` passed as a parameter (not an `Activity`), and thus the Activity inside must be "unwrapped". The fact that this is happening now might well be the reason why this class worked before current release (and mnot any more).
> fix #11251: make NavigationSelectionActionProvider constructure take Context parameter

- main/src/cgeo/geocaching/CacheListActivity.java
fix #10374: fix crash after refresh of filtered list
> fix #10374: fix crash after refresh of filtered list

- main/res/layout/continuousrangeslider_view.xml
- main/src/cgeo/geocaching/filters/gui/FavoritesFilterViewHolder.java
- main/src/cgeo/geocaching/filters/gui/LogsCountFilterViewHolder.java
fix #11345: remove unnecessary space for fav and logs count filter
> fix #11345: remove unnecessary space for fav and logs count filter

- main/src/cgeo/geocaching/filters/gui/GeocacheFilterActivity.java
fix #11406: make sure filtercontext is never null
> fix #11406: make sure filtercontext is never null

- main/src/cgeo/geocaching/utils/EmojiUtils.java
> add some more tool emojis

- main/src/cgeo/geocaching/ui/DateTimeEditor.java
> Fix date picker returns wrong date for logging

- main/src/cgeo/geocaching/filters/gui/StatusFilterViewHolder.java
- main/src/cgeo/geocaching/maps/MapSettingsUtils.java
see https://github.com/cgeo/cgeo/issues/11343#issuecomment-888134489
> Resort status filter and quick settings (fix #11343)

- main/src/cgeo/geocaching/utils/CalendarUtils.java
- main/src/cgeo/geocaching/utils/SystemInformation.java
The program settings section was quite messed up, so I added a separate "Filters" section and moved all map related stuff directly above the map source section (Routing mode / Live map mode / OSM multi-threading).
Furthermore, "Timezone" is added.
|before |now |
-|-
> add user time zone and reformat SystemInformation

- main/src/cgeo/geocaching/filters/core/StatusGeocacheFilter.java
consider in StatusGeocacheFilter only offline-logs which are found-logs 
* adapt filter-method with LogType.isFoundLog 
* adapt where-clause in addToSql with logType in (LogType.getFoundLogIds)
fix #11430
> Filter for "hide offline log" considers only "found" offline logs

- main/src/cgeo/geocaching/downloader/AbstractDownloader.java
- main/src/cgeo/geocaching/downloader/BRouterTileDownloader.java
- main/src/cgeo/geocaching/downloader/MapDownloaderFreizeitkarte.java
- main/src/cgeo/geocaching/downloader/MapDownloaderFreizeitkarteThemes.java
- main/src/cgeo/geocaching/downloader/MapDownloaderHylly.java
- main/src/cgeo/geocaching/downloader/MapDownloaderHyllyThemes.java
- main/src/cgeo/geocaching/downloader/MapDownloaderMapsforge.java
- main/src/cgeo/geocaching/downloader/MapDownloaderOpenAndroMaps.java
- main/src/cgeo/geocaching/downloader/MapDownloaderOpenAndroMapsThemes.java
- tests/src-android/cgeo/geocaching/downloader/DownloaderTest.java
- annotate all analyzePage with "@NonNull String page"
- annotate all checkUpdateFor with "@NonNull String page" and method with "@Nullable"
- add null check before calling analyzePage in DownloaderTest.getList()
fix #11417
> fix NPE in DownloaderTest.testOpenAndroMapsThemes

- main/res/values/strings_not_translatable.xml
- main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java
- main/src/cgeo/geocaching/maps/mapsforge/TileSourceMapyCz.java
I added support for [Mapy.cz](https://mapy.cz) map source, mostly for me as my personal fork, but I think other users could benefit from this as well, as the map quality seems overall better in Europe in my opinion.
> Add support for Mapy.cz map source

- main/AndroidManifest.xml
Added all the possible capitalizations to the URLs we support, just in case someone uses strange links (e.g. manually created).
#11453
> Fix #11453 - Add all permutations of pathPrefix for supported URLs

- tests/src-android/cgeo/geocaching/CgeoApplicationTest.java
- tests/src-android/cgeo/geocaching/activity/waypoint/AddWaypointActivityTest.java
- tests/src-android/cgeo/geocaching/activity/waypoint/AddWaypointMultiTest.java
- tests/src-android/cgeo/geocaching/activity/waypoint/AddWaypointMysteryTest.java
- tests/src-android/cgeo/geocaching/activity/waypoint/EditWaypointActivityTest.java
- tests/src-android/cgeo/geocaching/address/GeocoderTest.java
- tests/src-android/cgeo/geocaching/connector/gc/GCParserTest.java
- tests/src-android/cgeo/geocaching/log/LogTrackableActivityTest.java
- tests/src-android/cgeo/geocaching/storage/DataStoreTestHelpers.java
> replace deprecated android.test.suitebuilder.annotation.*

- main/src/cgeo/geocaching/maps/MapSettingsUtils.java
removes some vars from MapSettingsUtils which are no longer in use
> remove some unused vars from MapSettingsUtils

- tests/src-android/cgeo/geocaching/storage/DataStoreTestHelpers.java
Some typographics errors are fixed now :)
> Fixed typo

- main/src/cgeo/geocaching/connector/gc/GCParser.java
- main/src/cgeo/geocaching/enumerations/CacheType.java
- main/src/cgeo/geocaching/models/Geocache.java
- main/src/cgeo/geocaching/utils/DisposableHandler.java
- main/src/cgeo/geocaching/utils/TextUtils.java
- tests/src-android/cgeo/geocaching/CgeoApplicationTest.java
- tests/src-android/cgeo/geocaching/connector/gc/GCParserTest.java
- tests/src-android/cgeo/test/Compare.java
When working on #11445 I saw also some lint warnings.
This PR should fix them.
- fix/optimize test declarations
- add annotations Nullable/NonNull
- other minor fixes
> Optimize code / fix lint warnings

- main/res/layout/cacheslist_item.xml
- main/src/cgeo/geocaching/connector/gc/GCWebAPI.java
- main/src/cgeo/geocaching/ui/CacheListAdapter.java
- main/src/cgeo/geocaching/ui/DistanceView.java
fix #11488: make preimum caches available for basic members plus distance heuristic
> fix #11488: make preimum caches available for basic members plus distance heuristic

- main/res/layout/cacheslist_item.xml
- main/src/cgeo/geocaching/connector/gc/GCWebAPI.java
- main/src/cgeo/geocaching/connector/internal/InternalConnector.java
- main/src/cgeo/geocaching/storage/DataStore.java
- main/src/cgeo/geocaching/ui/CacheListAdapter.java
- main/src/cgeo/geocaching/ui/DistanceView.java
Test PR for the merge release -> master
#11488
> [DO NOT MERGE] Test PR for merge release->master

- main/src/cgeo/geocaching/connector/AbstractConnector.java
> add icon to 'caches hidden' in user action popup

- main/src/cgeo/geocaching/connector/gc/GCConstants.java
> Website change

- main/res/layout/waypoint_item.xml
> give visual touch feedback for waypoint compass rose

- main/src/cgeo/geocaching/activity/TabbedViewPagerActivity.java
- reverts commit 13a24c9d043771a309a2f2969358e60da7cbc668
- to avoid side effects described in #11567
- will reopen #11527
> Revert #11534 to fix #11567

- main/res/values/strings.xml
- main/src/cgeo/geocaching/filters/core/StringFilter.java
- main/src/cgeo/geocaching/storage/SqlBuilder.java
- tests/src-android/cgeo/geocaching/filters/StringGeocacheFilterTest.java
> add 'does not contain' option

- main/build.gradle
..., as the related PR are finished
> remove lint option disable 'NonConstantResourceId'

- main/src/cgeo/geocaching/CacheListActivity.java
- main/src/cgeo/geocaching/maps/MapUtils.java
- main/src/cgeo/geocaching/ui/CacheListAdapter.java
- main/src/cgeo/geocaching/utils/FilterUtils.java
fix #11572: correct filter text show logic, cleanup filter text logic
> fix #11572: correct filter text show logic, cleanup filter text logic

- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
> refresh map title after toggling "live"

- main/res/menu/cache_list_options.xml
- main/res/menu/cache_options.xml
- main/res/values/strings.xml
- main/src/cgeo/geocaching/CacheListActivity.java
- main/src/cgeo/geocaching/CacheMenuHandler.java
- main/src/cgeo/geocaching/connector/gc/BookmarkUtils.java
- main/src/cgeo/geocaching/connector/gc/GCParser.java
- main/src/cgeo/geocaching/network/Network.java
Only available for GC premium members - fix #118
> Support adding caches to bookmark lists (fix #118)

- main/res/layout/waypoint_item.xml
solves Waypoint Navigation Button To Small - fix #11600
> add padding on "navigate" button to increase clickable area

- main/src/cgeo/geocaching/connector/gc/GCMap.java
- main/src/cgeo/geocaching/connector/lc/LCApi.java
fix #11606: perform filtering in map viewer live search
> fix #11606: perform filtering in map viewer live search

- main/src/cgeo/geocaching/connector/gc/GCConstants.java
- main/src/cgeo/geocaching/connector/gc/GCParser.java
- main/src/cgeo/geocaching/network/Network.java
Update watchlist calls to match the update on GC.com
Fixes #11619
> fix watchlist (issue #11619)

- main/src/cgeo/geocaching/connector/al/ALConnector.java
Extend AL connector to check for and return ownership
> detect isOwner() for ALC (fix #11604)

- main/res/layout/downloader_item.xml
- main/src/cgeo/geocaching/InstallWizardActivity.java
- main/src/cgeo/geocaching/downloader/DownloadConfirmationActivity.java
- main/src/cgeo/geocaching/downloader/DownloadSelectorActivity.java
- main/src/cgeo/geocaching/downloader/DownloaderUtils.java
- main/src/cgeo/geocaching/downloader/MapDownloaderReceiverSchemeMap.java
- main/src/cgeo/geocaching/downloader/MapDownloaderReceiverSchemeMapTheme.java
- main/src/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
- main/src/cgeo/geocaching/settings/InfoPreferenceMap.java
- main/src/cgeo/geocaching/settings/SettingsActivity.java
> don't finish download activity when starting download & show progress

- main/src/cgeo/geocaching/connector/gc/GCConstants.java
Applied the suggested fix, tested in emulator.
> Fix #11638, Watchlist status not initialized/updated correctly

- main/src/cgeo/geocaching/enumerations/CacheType.java
- main/src/cgeo/geocaching/models/Geocache.java
Show 161 m distance circles for UDC as well, if displaying circles is enabled
> show distance circles for UDC (if circles enabled, fix #11630)

- main/res/values/strings.xml
The current string for adding a cache to the servers bookmark list it "Upload to bookmark list".
IMHO this sounds misleading as the cache is not uploaded but its simply, that the cache is added. So I suggest "Add to bookmark list", which is more understandable.
None
> Rename bookmark list string

- main/src/cgeo/geocaching/AboutActivity.java
fixes an NPE reported on Play Console
> add initialization check to about page

- main/res/drawable/ic_menu_bookmarks.xml
- main/res/menu/main_activity_options.xml
Adds a separate icon for bookmark lists to be able to distinguish between PQ and bookmark lists
> add icon for bookmark lists (fix #11685)

- main/src/cgeo/geocaching/log/LogType.java
While copy&pasting some stuff around I accidentally changed some resources that shouldn't have changed, reverting that.
> fix some accidental color changes in #11676

- main/src/cgeo/geocaching/AbstractDialogFragment.java
- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/CacheMenuHandler.java
> show navigation chooser as dialog instead of submenu inside map popup

- main/res/raw/changelog_release.md
Make `changelog_release.md` identical to `release` branch as it seems to have be manually changed on `master` which should not be done.
@moving-bits 
What about the two items in there. Are those on master or do they need to be (re)added?
Edit: Forget it, they are contained already.
Fixes #11716
> Fix #11716 - Sync changelog_release.md from release branch

- .github/workflows/branch-merge.yml
> Add automated branch merge workflow (only manual runs for now)

- main/src/cgeo/geocaching/utils/SystemInformation.java
> [rel. #11728] add system font scale to system info

- main/src/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java
- main/src/cgeo/geocaching/ui/ImageParam.java
> use cache type marker for filter dialog

- .github/workflows/branch-merge.yml
> give workflow permission to push to master

- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/CacheListActivity.java
- main/src/cgeo/geocaching/CachePopupFragment.java
- main/src/cgeo/geocaching/connector/internal/InternalConnector.java
- main/src/cgeo/geocaching/ui/ViewUtils.java
- main/src/cgeo/geocaching/utils/EmojiUtils.java
- main/src/cgeo/geocaching/utils/MapMarkerUtils.java
> cross-convert cache markers to solve tinting issue

- main/res/drawable/type_earth.xml
related to but no solving #11721, so I'm not linking to that to avoid it being closed
> new earthcache icon

- .github/workflows/branch-merge.yml
> don't use explicit username for repo token

- main/src/cgeo/geocaching/utils/calc/Calculator.java
- main/src/cgeo/geocaching/utils/calc/CalculatorException.java
- main/src/cgeo/geocaching/utils/calc/CalculatorMap.java
- main/src/cgeo/geocaching/utils/calc/CalculatorUtils.java
- tests/src/cgeo/geocaching/utils/calc/CalculatorMapTest.java
- tests/src/cgeo/geocaching/utils/calc/CalculatorTest.java
rel to #11520:  variables: introducing CalculatorMap
> rel to #11520: variables: introducing CalculatorMap

- main/res/raw/changelog_full.md
updated `changelog_full.md` to reflect recent changes of current release 2021.09.27
> updated changelog_full for release 2021.09.27

- main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateDialog.java
corrections in CoordinatesCalculateDialog.java
on second visit we enter with empty gp ... so the-not-formula-part of the coords are initialised with those of your current location
re-initialisation is now done correctly and depending on the saved coordinate-format
issue #11668
checkstyle-test : no remarks => ok
translations : none => ok
> issue 11668 : re-initialize calculated waypoint correctly

- main/src/cgeo/geocaching/AbstractDialogFragment.java
- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/CacheMenuHandler.java
> Make long tap on compass icon work again 

- main/res/layout/cacheslist_item_select.xml
- main/src/cgeo/geocaching/apps/navi/GoogleNavigationApp.java
Enable HTML in navigation target dialog for waypoint descriptions
> allow HTML in navigation target description (fix #11730)

- main/src/cgeo/geocaching/storage/DataStore.java
Extends the existing maintenance function (settings => offline data => maintenance) to remove all caches marked as "to be deleted" (= not belonging to any list + not having any offline logs), ignoring our 72h grace period, as discussed in #10039.
(To not touch any settings source code (to not interfere with settings migration) I've added this to the already existing maintenance method, without splitting that into two or renaming the method.)
> add force-removal of to-be-deleted caches to maintenance (fix #10039)

- main/src/cgeo/geocaching/NavigateAnyPointActivity.java
- main/src/cgeo/geocaching/apps/navi/GoogleNavigationApp.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
> fix icon style (fix #11732)

- main/res/drawable/ic_menu_function.xml
- main/res/layout/cachedetail_variables_page.xml
- main/res/layout/variables_list_item.xml
- main/res/values/strings.xml
- main/res/values/styles.xml
- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/VariablesViewPageFragment.java
- main/src/cgeo/geocaching/connector/oc/OkapiClient.java
- main/src/cgeo/geocaching/models/CacheVariables.java
- main/src/cgeo/geocaching/models/Geocache.java
- main/src/cgeo/geocaching/ui/TextParam.java
- main/src/cgeo/geocaching/ui/dialog/SimpleDialog.java
- main/src/cgeo/geocaching/ui/recyclerview/ManagedListAdapter.java
- main/src/cgeo/geocaching/utils/calc/Calculator.java
- main/src/cgeo/geocaching/utils/calc/CalculatorException.java
- main/src/cgeo/geocaching/utils/calc/CalculatorFunction.java
- main/src/cgeo/geocaching/utils/calc/CalculatorMap.java
- main/src/cgeo/geocaching/utils/calc/CalculatorUtils.java
- tests/src/cgeo/geocaching/utils/calc/CalculatorTest.java
rel to #11520: add first version of variables/calculator tab
> rel to #11520: add first version of variables/calculator tab

- main/res/drawable/background_gc.xml
- main/res/drawable/background_oc.xml
- main/res/drawable/background_other.xml
- main/res/drawable/marker.xml
- main/res/drawable/marker_oc.xml
- main/res/drawable/marker_other.xml
- main/res/drawable/marker_pin.xml
> optimize some vector drawables

- main/src/cgeo/geocaching/ui/DateTimeEditor.java
fix #11607
fix #11726
fix #11528
> [DatePicker] only update the date, but keep the previous time

- main/src/cgeo/geocaching/utils/DisplayUtils.java
- main/src/cgeo/geocaching/utils/MapMarkerUtils.java
> [vectorIcons] Fix cachetype marker background tinting (on Android 7-9)

- main/res/layout/cachedetail_waypoints_header.xml
- main/res/values/preference_keys.xml
- main/res/values/strings.xml
- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/settings/Settings.java
extra button above the waypoints-list to be able to hide/unhide waypoints that has been marked as visited
the checkbox has been added in layout : cachedetail_waypoints_header.xml
all necessary code to link the layout is in CacheDetailsActivity.java
new setting to keep checkbox-value : pref_hideVisitedWaypoints
issue #11681
> issue 11681 - hide visited waypoints - new branch

- main/src/cgeo/geocaching/NavigateAnyPointActivity.java
- main/src/cgeo/geocaching/apps/navi/GoogleNavigationApp.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
- main/src/cgeo/geocaching/models/Waypoint.java
- main/src/cgeo/geocaching/ui/GeoItemSelectorUtils.java
- main/src/cgeo/geocaching/utils/MapMarkerUtils.java
Make UI more consistent and avoid duplicated code...
Pre-requirement for #11591
> introduce generic geoItemSelector view creation utils

- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/VariablesViewPageFragment.java
- main/src/cgeo/geocaching/utils/calc/Calculator.java
- main/src/cgeo/geocaching/utils/calc/CalculatorException.java
- main/src/cgeo/geocaching/utils/calc/CalculatorFunction.java
- main/src/cgeo/geocaching/utils/calc/CalculatorMap.java
- main/src/cgeo/geocaching/utils/calc/CalculatorUtils.java
- main/src/cgeo/geocaching/utils/calc/Value.java
- main/src/cgeo/geocaching/utils/calc/ValueList.java
- tests/src/cgeo/geocaching/utils/calc/CalculatorMapTest.java
- tests/src/cgeo/geocaching/utils/calc/CalculatorTest.java
rel to #11520: refactorings, add first version for scan
> rel to #11520: refactorings, add first version for scan

- main/src/cgeo/geocaching/storage/ContentStorage.java
- main/src/cgeo/geocaching/utils/ContextLogger.java
rel to #11227: add logging of startup times for contentstorage
> rel to #11227: add logging of startup times for contentstorage

- main/src/cgeo/geocaching/SearchActivity.java
- main/src/cgeo/geocaching/log/LogTrackableActivity.java
- main/src/cgeo/geocaching/search/GeocacheAutoCompleteAdapter.java
- main/src/cgeo/geocaching/storage/DataStore.java
> provide search suggestions in cgeo's generic GeoItem style

- main/src/cgeo/geocaching/VariablesViewPageFragment.java
- main/src/cgeo/geocaching/models/CacheVariables.java
- main/src/cgeo/geocaching/utils/calc/Calculator.java
rel to #11520 variables: enhance cache scan, implement addMulti button
> rel to #11520 variables: enhance cache scan, implement addMulti button

- main/src/cgeo/geocaching/CacheListActivity.java
- main/src/cgeo/geocaching/filters/core/GeocacheFilterContext.java
- main/src/cgeo/geocaching/ui/CacheListAdapter.java
fix #11996: dont show defining filter config for online search
> fix #11996: dont show defining filter config for online search

- main/res/layout/cachedetail_variables_page.xml
- main/res/layout/variables_list_item.xml
- main/src/cgeo/geocaching/VariablesViewPageFragment.java
- main/src/cgeo/geocaching/ui/dialog/SimpleDialog.java
- main/src/cgeo/geocaching/utils/calc/CalculatorFunction.java
- main/src/cgeo/geocaching/utils/calc/CalculatorUtils.java
- tests/src/cgeo/geocaching/utils/calc/CalculatorUtilsTest.java
rel to #11520: fix early findings e.g. function select, confirm message, layouting. helper message
This PR intends to fix the comments placed by @Lineflyer  here: https://github.com/cgeo/cgeo/issues/11520#issuecomment-952060989
> rel to #11520: fix early findings e.g. function select, confirm message, layouting. helper message

- main/build.gradle
rel to #10128: switch used mapsforge fork to cgeo repo
> rel to #10128: switch used mapsforge fork to cgeo repo

- main/src/cgeo/geocaching/utils/EmojiUtils.java
> tint the correct icon in Emoji selection dialog

- main/res/layout/waypoint_item.xml
- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/WaypointPopupFragment.java
- main/src/cgeo/geocaching/maps/CGeoMap.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/caches/AbstractCachesOverlay.java
- main/src/cgeo/geocaching/maps/routing/RouteSortActivity.java
- main/src/cgeo/geocaching/ui/GeoItemSelectorUtils.java
- main/src/cgeo/geocaching/utils/MapMarkerUtils.java
Whenever a waypoint image is shown display it as marker
fixes #11777
fixes #11778
> always show waypoint marker with background

- main/src/cgeo/geocaching/MainActivity.java
- main/src/cgeo/geocaching/activity/Keyboard.java
> don't hide suggestions if keyboard gets closed

- main/src/cgeo/geocaching/maps/mapsforge/v6/caches/AbstractCachesOverlay.java
fix #12030: add pin to waypoints on osm
> fix #12030: add pin to waypoints on osm

- main/src/cgeo/geocaching/CacheListActivity.java
> open sort selection list on sortbar click

- main/src/cgeo/geocaching/filters/core/GeocacheFilter.java
- main/src/cgeo/geocaching/utils/FilterUtils.java
Somewhere this issue was recently mentioned off-topic, but I don't find the place anymore...
> don't clear openInAdvancedMode setting when deleting a filter

- main/src/cgeo/geocaching/utils/SystemInformation.java
rel to #12073: add stored filters to system information
> rel to #12073: add stored filters to system information

- main/src/cgeo/geocaching/filters/gui/GeocacheFilterActivity.java
- main/src/cgeo/geocaching/storage/DataStore.java
fix #12073: sync adapter and layout, remove removal of nonfiltering filters when loading saved configs
> fix #12073: sync adapter and layout, remove removal of nonfiltering filters when loading saved configs

- main/src/cgeo/geocaching/utils/calc/Calculator.java
- main/src/cgeo/geocaching/utils/calc/CalculatorUtils.java
- main/src/cgeo/geocaching/utils/calc/Value.java
- tests/src/cgeo/geocaching/utils/calc/CalculatorTest.java
fix #12062: calculator support chained floats
> fix #12062: calculator support chained floats

- main/src/cgeo/geocaching/log/LogTemplateProvider.java
- main/src/cgeo/geocaching/settings/TemplateTextPreference.java
> include [LOG] template in getAllTemplates()

- main/res/values/strings.xml
Fix incorrect capitalization in strings
#12044
> Fix #12044 - Fix capitalization of strings

- main/src/cgeo/geocaching/utils/MapMarkerUtils.java
implements a double-sized "owned" icon and fixes a marker display bug
fixes #12100
> Owned double size

- main/build.gradle
- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
- main/src/cgeo/geocaching/storage/LocalStorage.java
- main/src/cgeo/geocaching/utils/FileUtils.java
fix #12145: move mapsforge svg to own dir, delete leftovers, patch mapsforge
> fix #12145: move mapsforge svg to own dir, delete leftovers, patch mapsforge

- main/src/cgeo/geocaching/CgeoApplication.java
- main/src/cgeo/geocaching/search/SuggestionsAdapter.java
rel to #11227: fix gui blockage on quick search
> rel to #11227: fix gui blockage on quick search

- main/src/cgeo/geocaching/storage/DataStore.java
- main/src/cgeo/geocaching/utils/SystemInformation.java
add more database information to log and sysinfo
> add more database information to log and sysinfo

- main/src/cgeo/geocaching/AboutActivity.java
fix #12197: add null checks for binding var to fix npe
> fix #12197: add null checks for binding var to fix npe

- main/src/cgeo/geocaching/storage/DataStore.java
- main/src/cgeo/geocaching/utils/SystemInformation.java
rel to #12204: revert logging more db info, seems to cause startup slowness
> rel to #12204: revert logging more db info, seems to cause startup slowness

- main/res/layout/cache_information_item.xml
- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/ui/CacheDetailsCreator.java
Fixes missing display of
- cache details: owner, favorite count
- trackable details: origin
(#12205)
Also fixes NPE on tapping some of the detail entries (geocode, coordinates etc.) (#12211)
> fix values not being displayed (fix #12205)

- .idea/checkstyle-idea.xml
- main/build.gradle
... to the state before PR #11298.
Additionally optimize the remark for the checkstyle version.
> reset checkstyle-idea.xml

- main/build.gradle
> optimize main/build.gradle

- main/src/cgeo/geocaching/utils/ProcessUtils.java
rel to #12209: replace hard-coded view intent name with constant
> rel to #12209: replace hard-coded view intent name with constant

- main/src/cgeo/geocaching/settings/SettingsActivity.java
- main/src/cgeo/geocaching/settings/fragments/PreferenceMapFragment.java
- main/src/cgeo/geocaching/settings/fragments/PreferenceNavigationFragment.java
- main/src/cgeo/geocaching/settings/fragments/PreferenceOfflinedataFragment.java
- main/src/cgeo/geocaching/utils/SettingsUtils.java
- enable SAF related preference entries to open the SAF folder selection
- store selected new folder
- and update UI info accordingly
@eddiemuc 
Can you cross-check if I did miss anything regarding SAF folder selection etc.? Thanks!
> reenable SAF folder selection in settings (fix #12230)

- main/src/cgeo/geocaching/settings/fragments/PreferenceBackupFragment.java
...restore code parts which got lost & re-enable commented out code
> reactivate "start backup" (fix #12233)

- main/src/cgeo/geocaching/settings/ColorpickerPreference.java
- main/src/cgeo/geocaching/settings/fragments/PreferenceMapFragment.java
Migrates the ColorpickerPreference to be compatible with AndroidX preferences
> migrate ColorpickerPreference to AndroidX (fix #12177)

- main/res/values/preference_keys.xml
fix typo,
add translatable="false" to a key and move them to a better place.
> optimize preference_keys.xml

- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/connector/gc/GCConnector.java
- main/src/cgeo/geocaching/connector/gc/GCLogin.java
- main/src/cgeo/geocaching/models/Geocache.java
- main/src/cgeo/geocaching/utils/DisposableHandler.java
- main/src/cgeo/geocaching/utils/SimpleDisposableHandler.java
Show status error messages when refreshing a cache
> show status error messages on refresh (fix #12194)

- main/src/cgeo/geocaching/VariablesViewPageFragment.java
- main/src/cgeo/geocaching/calculator/CalcStateEvaluator.java
- main/src/cgeo/geocaching/calculator/FormulaParser.java
- main/src/cgeo/geocaching/calculator/VariableData.java
- main/src/cgeo/geocaching/models/CacheVariableList.java
- main/src/cgeo/geocaching/storage/DataStore.java
- main/src/cgeo/geocaching/ui/VariableListView.java
- main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateDialog.java
- main/src/cgeo/geocaching/utils/formulas/Formula.java
- main/src/cgeo/geocaching/utils/formulas/FormulaException.java
- main/src/cgeo/geocaching/utils/formulas/FormulaFunction.java
- main/src/cgeo/geocaching/utils/formulas/FormulaUtils.java
- main/src/cgeo/geocaching/utils/formulas/MultiFormula.java
- main/src/cgeo/geocaching/utils/formulas/Value.java
- main/src/cgeo/geocaching/utils/formulas/ValueList.java
- main/src/cgeo/geocaching/utils/formulas/VariableList.java
- main/src/cgeo/geocaching/utils/formulas/VariableMap.java
- tests/src/cgeo/geocaching/utils/formulas/FormulaTest.java
- tests/src/cgeo/geocaching/utils/formulas/FormulaUtilsTest.java
- tests/src/cgeo/geocaching/utils/formulas/MultiFormulaTest.java
- tests/src/cgeo/geocaching/utils/formulas/VariableListTest.java
- tests/src/cgeo/geocaching/utils/formulas/VariableMapTest.java
Variable calculator: introduce MultiCalculator for coordinates
> Variable calculator: introduce MultiCalculator for coordinates

- main/src/cgeo/geocaching/downloader/MapDownloaderOpenAndroMapsThemes.java
adapt OAM theme downloader to recent OAM website changes
(make third position in version string optional)
> adapt downloader to recent OAM theme page changes (fix #12249)

- main/src/cgeo/geocaching/settings/fragments/PreferenceNavigationFragment.java
Update summary on selecting a new profile for routing
> update summary on routing profile change (fix #12232)

- main/res/layout/main_activity.xml
- main/res/values/strings.xml
- main/src/cgeo/geocaching/MainActivity.java
- main/src/cgeo/geocaching/utils/BackupUtils.java
Adds "xx caches stored" at the bottom of the dashboard screen, above the location info
> add offline stored counter to dashboard (fix #11936)

- main/res/values/strings.xml
- main/src/cgeo/geocaching/settings/fragments/PreferenceOfflinedataFragment.java
- restores Settings => offline data => delete orphaned files
- adds short toasts for maintenance started / finished
> restore maintenance method (fix #12267)

- main/src/cgeo/geocaching/settings/ViewSettingsActivity.java
Adds back arrow to "view settings" screen
> add back arrow to view settings screen (fix #12269)

- main/src/cgeo/geocaching/utils/MapMarkerUtils.java
offline or online logs should have higher priority than will attend logs
fixes #12254
> lower priority for WA marker

- main/src/cgeo/geocaching/settings/fragments/PreferenceOfflinedataFragment.java
Reenable moving the database between internal and user-visible path
> reenable db move (fix #12264)

- main/src/cgeo/geocaching/settings/fragments/PreferenceOfflinedataFragment.java
- main/src/cgeo/geocaching/utils/SettingsUtils.java
reenable setting geocache data dir location
> reenable setting data dir (fix #12266)

- main/res/values/strings.xml
- main/res/xml/theme_prefs.xml
- main/src/cgeo/geocaching/activity/ActivityMixin.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/RenderThemeHelper.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/RenderThemeSettings.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/RenderThemeSettingsFragment.java
Migrates render theme settings, the remaining Android settings, to AndroidX preferences
> migrate render theme settings to AndroidX (fix #12223)

- main/src/cgeo/geocaching/settings/TemplateTextPreference.java
fix checkstyle issue in `TemplateTextPreference`
> fix Checkstyle issue

- main/res/layout-h390dp-land/activity_bottom_navigation.xml
- main/res/layout-land/activity_bottom_navigation.xml
- main/res/layout/activity_bottom_navigation.xml
- main/src/cgeo/geocaching/MainActivity.java
fix #12242: let bottomnavigation use unique voew root id
> fix #12242: let bottomnavigation use unique voew root id

- main/res/layout/coordinates_calculate_grid.xml
- main/res/layout/coordinatescalculateglobal_dialog.xml
- main/src/cgeo/geocaching/models/CalculatedCoordinate.java
- main/src/cgeo/geocaching/models/CalculatedCoordinateType.java
- main/src/cgeo/geocaching/ui/CoordinatesCalculateGrid.java
- main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateGlobalDialog.java
- main/src/cgeo/geocaching/utils/formulas/Formula.java
- tests/src/cgeo/geocaching/utils/formulas/FormulaTest.java
rel to #11520: global calculated waypoint coordinates: first draft for single-char-dialog, minor improvements
> rel to #11520: global calculated waypoint coordinates: first draft for single-char-dialog, minor improvements

- main/src/cgeo/geocaching/CacheListActivity.java
- main/src/cgeo/geocaching/MainActivity.java
- main/src/cgeo/geocaching/SearchActivity.java
- main/src/cgeo/geocaching/activity/AbstractBottomNavigationActivity.java
At least a first step towards  #12317 / #11926 
Should be tested in the nightlies whether this works for the described workflows
> keep activities alive in background (rel. to #12317 / #11926)

- main/res/drawable/ic_menu_calculate.xml
- main/res/layout/coordinates_input_dialog.xml
- main/res/layout/coordinatescalculateglobal_dialog.xml
- main/res/layout/editwaypoint_activity.xml
- main/res/layout/waypoint_item.xml
- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/EditWaypointActivity.java
- main/src/cgeo/geocaching/models/CalculatedCoordinate.java
- main/src/cgeo/geocaching/models/Waypoint.java
- main/src/cgeo/geocaching/ui/CoordinatesCalculateGrid.java
- main/src/cgeo/geocaching/ui/VariableListView.java
- main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateDialog.java
- main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateGlobalDialog.java
- main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java
- main/src/cgeo/geocaching/utils/TextUtils.java
- main/src/cgeo/geocaching/utils/formulas/DegreeFormula.java
- main/src/cgeo/geocaching/utils/formulas/Formula.java
- main/src/cgeo/geocaching/utils/formulas/FormulaException.java
- main/src/cgeo/geocaching/utils/formulas/Value.java
- main/src/cgeo/geocaching/utils/formulas/VariableMap.java
- tests/src/cgeo/geocaching/utils/formulas/FormulaTest.java
rel to #11520: calculated coordinates: error string formats, dialog navigation
> rel to #11520: calculated coordinates: error string formats, dialog navigation

- main/src/cgeo/geocaching/models/CalcState.java
- main/src/cgeo/geocaching/models/WaypointParser.java
fix #12341: add check on PN export for new calculated coordinate config
> fix #12341: add check on PN export for new calculated coordinate config

- main/src/cgeo/geocaching/downloader/MapDownloaderOpenAndroMaps.java
Adds a path and filename translations for upgrading existing OAM downloads needed due to folder structure and file name changes described in #12344
> enable upgrading from OAM v4 to v5 maps (fix #12344)

- main/src/cgeo/geocaching/downloader/CompanionFileUtils.java
- main/src/cgeo/geocaching/downloader/DownloadSelectorActivity.java
- main/src/cgeo/geocaching/downloader/DownloaderUtils.java
- main/src/cgeo/geocaching/models/Download.java
Reenable checks for map theme updates in both
- mainscreen "Update => Map data" and
- map => downloader => "Check for updates"
> reenable check for map theme updates (fix #12345)

- main/res/xml/preferences_map.xml
- main/res/xml/preferences_navigation.xml
- main/res/xml/preferences_offlinedata.xml
Removes some unwanted divider lines in preferences
> avoid unwanted divider lines in preferences (fix #12336)

- main/res/menu/cache_list_options.xml
- main/src/cgeo/geocaching/CacheListActivity.java
- main/src/cgeo/geocaching/connector/gc/AbstractListActivity.java
Adds import from bookmark lists to cache list / "stored" activity
> add import from bookmarks to cache list activity (fix #12325)

- main/src/cgeo/geocaching/CacheListActivity.java
- main/src/cgeo/geocaching/sorting/SortActionProvider.java
invert sort-order on long click on sort bar
add long-click-listener to sort_bar
fix #12257
> invert sort-order on long click on sort bar (fix #12257)

- main/src/cgeo/geocaching/storage/LocalStorage.java
rel to #12340: log migration exceptions, let cgeo continue
> rel to #12340: log migration exceptions, let cgeo continue

- main/src/cgeo/geocaching/storage/LocalStorage.java
- main/src/cgeo/geocaching/utils/FileUtils.java
rel to #12340: add more logging for debugging this
> rel to #12340: add more logging for debugging this

- main/res/layout/cachedetail_variables_page.xml
- main/res/layout/coordinatescalculateglobal_dialog.xml
- main/res/layout/variable_list_item_advanced.xml
- main/res/layout/variable_list_item_minimalistic.xml
- main/src/cgeo/geocaching/VariablesViewPageFragment.java
- main/src/cgeo/geocaching/ui/VariableListView.java
- main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateGlobalDialog.java
- main/src/cgeo/geocaching/utils/formulas/FormulaUtils.java
- main/src/cgeo/geocaching/utils/formulas/VariableList.java
- main/src/cgeo/geocaching/utils/formulas/VariableMap.java
- tests/src/cgeo/geocaching/utils/formulas/FormulaUtilsTest.java
- tests/src/cgeo/geocaching/utils/formulas/VariableListTest.java
- tests/src/cgeo/geocaching/utils/formulas/VariableMapTest.java
rel to #11520: make var list flexible in global calculation dialog
> rel to #11520: make var list flexible in global calculation dialog

- main/res/drawable/ic_menu_auto_fix_high.xml
- main/res/layout/cachedetail_variables_page.xml
- main/res/layout/coordinatescalculateglobal_dialog.xml
- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/EditWaypointActivity.java
- main/src/cgeo/geocaching/VariablesViewPageFragment.java
- main/src/cgeo/geocaching/models/CacheVariableList.java
- main/src/cgeo/geocaching/models/CalculatedCoordinate.java
- main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateGlobalDialog.java
fix #12369: update all waypoints if variables are changed
> fix #12369: update all waypoints if variables are changed

- main/AndroidManifest.xml
- main/src/cgeo/geocaching/CacheListActivity.java
- main/src/cgeo/geocaching/MainActivity.java
- main/src/cgeo/geocaching/activity/AbstractBottomNavigationActivity.java
- main/src/cgeo/geocaching/address/AddressListActivity.java
- main/src/cgeo/geocaching/downloader/DownloadSelectorActivity.java
- main/src/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
- main/src/cgeo/geocaching/settings/ViewSettingsActivity.java
Further improve switching between different bottom navigation activities.... (rel. to #11926)
> Bottom nav improvements

- main/build.gradle
see #12327
relocate PR #12327 to release
> Bump spotbugs-annotations from 4.4.1 to 4.5.2

- main/res/xml/preferences_map.xml
- main/src/cgeo/geocaching/settings/OAuthPreference.java
- main/src/cgeo/geocaching/settings/TokenPreference.java
- main/src/cgeo/geocaching/settings/fragments/PreferenceMapFragment.java
- main/src/cgeo/geocaching/settings/fragments/PreferenceNavigationNavigationFragment.java
- main/src/cgeo/geocaching/settings/fragments/PreferenceServiceGeocachingComFragment.java
- main/src/cgeo/geocaching/settings/fragments/PreferenceServiceGeocachingSuFragment.java
- main/src/cgeo/geocaching/settings/fragments/PreferenceServiceGeokretyOrgFragment.java
- main/src/cgeo/geocaching/settings/fragments/PreferenceServiceOpencacheUkFragment.java
- main/src/cgeo/geocaching/settings/fragments/PreferenceServiceOpencachingDeFragment.java
- main/src/cgeo/geocaching/settings/fragments/PreferenceServiceOpencachingNlFragment.java
- main/src/cgeo/geocaching/settings/fragments/PreferenceServiceOpencachingPlFragment.java
- main/src/cgeo/geocaching/settings/fragments/PreferenceServiceOpencachingRoFragment.java
- main/src/cgeo/geocaching/settings/fragments/PreferenceServiceOpencachingUsFragment.java
- main/src/cgeo/geocaching/settings/fragments/PreferenceServiceTwitterFragment.java
- main/src/cgeo/geocaching/utils/SettingsUtils.java
Follow-up of #11298: cleanup and restore missing functionality
- directly update authorization preference to better reflect current login state
- introduce some generic helper methods
- remove outdated WIP comments
- handle map source changes correctly
> [refactor settings] cleanup and restore missing functionality

- crowdin.yml
Try using custom PR and commit texts for Crowdin automation
#12391
> Work on #12391 - Use improved messages and labeling

- main/src/cgeo/geocaching/utils/formulas/Formula.java
- main/src/cgeo/geocaching/utils/formulas/FormulaFunction.java
- main/src/cgeo/geocaching/utils/formulas/FormulaUtils.java
- tests/src/cgeo/geocaching/utils/formulas/FormulaTest.java
- tests/src/cgeo/geocaching/utils/formulas/FormulaUtilsTest.java
fix #12385, fix #12386: diverse formual enhancements: remove random, add if+comparison, vanity, roman
> fix #12385, fix #12386: diverse formual enhancements: remove random, add if+comparison, vanity, roman

- main/lint.xml
- main/res/mipmap-anydpi-v26/ic_launcher_nightly_round.xml
- main/res/mipmap-anydpi-v26/ic_launcher_rc_round.xml
Icons were deleted in f5eb932 - now restored.
Fixes #12357
> restore deleted *round.xml icons

- main/src/cgeo/geocaching/utils/formulas/DegreeFormula.java
- main/src/cgeo/geocaching/utils/formulas/Formula.java
- main/src/cgeo/geocaching/utils/formulas/FormulaFunction.java
- main/src/cgeo/geocaching/utils/formulas/FormulaUtils.java
- main/src/cgeo/geocaching/utils/formulas/Value.java
- main/src/cgeo/geocaching/utils/formulas/VariableList.java
- tests/src/cgeo/geocaching/models/CalculatedCoordinateTest.java
- tests/src/cgeo/geocaching/utils/formulas/FormulaTest.java
- tests/src/cgeo/geocaching/utils/formulas/FormulaUtilsTest.java
fix #12406, fix #12413, fix #12417, fix #12408: remove NPE on scan, parse S/W correctly, allow var name specification using bash syntax
> fix #12406, fix #12413, fix #12417, fix #12408: remove NPE on scan, parse S/W correctly, allow var name specification using bash syntax

- main/res/layout/template_preference_dialog.xml
- main/res/values/preference_keys.xml
- main/res/values/strings.xml
- main/res/xml/preferences_logging.xml
- main/src/cgeo/geocaching/log/LogTemplateProvider.java
- main/src/cgeo/geocaching/settings/Settings.java
- main/src/cgeo/geocaching/settings/TemplateTextPreference.java
- main/src/cgeo/geocaching/settings/fragments/PreferenceLoggingFragment.java
> allow unlimited number of log templates (fix #12293)

- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/ui/ImageListFragment.java
- main/src/cgeo/geocaching/ui/VariableListView.java
- main/src/cgeo/geocaching/ui/recyclerview/ManagedListAdapter.java
- main/src/cgeo/geocaching/utils/TextUtils.java
- main/src/cgeo/geocaching/utils/formulas/VariableList.java
- tests/src/cgeo/geocaching/ui/recyclerview/ManagedListAdapterTest.java
fix #12404: make varlist filterable and correct focus handling
> fix #12404: make varlist filterable and correct focus handling

- main/src/cgeo/geocaching/settings/fragments/PreferenceOfflinedataFragment.java
Fix moving database between user storage and internal storage
> fix moving database (fix #12402)

- main/src/cgeo/geocaching/VariablesViewPageFragment.java
- main/src/cgeo/geocaching/models/CalculatedCoordinate.java
- main/src/cgeo/geocaching/ui/VariableListView.java
- main/src/cgeo/geocaching/ui/ViewUtils.java
- main/src/cgeo/geocaching/ui/recyclerview/ManagedListAdapter.java
- tests/src/cgeo/geocaching/ui/recyclerview/ManagedListAdapterTest.java
fix #12404: add own focus handler for varlist, fix some bugs with filtering along the way
> fix #12404: add own focus handler for varlist, fix some bugs with filtering along the way

- main/src/cgeo/geocaching/Intents.java
While working on some other issues I stumbled upon a hand full of intent strings no longer in use. This PR removes them.
> remove some unused intent consts

- main/src/cgeo/geocaching/enumerations/CacheAttribute.java
- main/src/cgeo/geocaching/filters/core/AttributesGeocacheFilter.java
- main/src/cgeo/geocaching/filters/gui/AttributesFilterViewHolder.java
- main/src/cgeo/geocaching/settings/Settings.java
fixes some issues introduced by #12436 when restoring filters
> store selected source(s) as part of the filter

- main/src/cgeo/geocaching/maps/mapsforge/v6/RenderThemeSettingsFragment.java
Somehow an import line got removed during some merge, although it was present in the original PR #12462. 🤔 
This PR adds the missing line.
> fix compile error

- main/src/cgeo/geocaching/models/CalculatedCoordinate.java
- main/src/cgeo/geocaching/utils/KeyableCharSet.java
- main/src/cgeo/geocaching/utils/TextParser.java
- main/src/cgeo/geocaching/utils/TextUtils.java
- main/src/cgeo/geocaching/utils/formulas/DegreeFormula.java
- main/src/cgeo/geocaching/utils/formulas/Formula.java
- main/src/cgeo/geocaching/utils/functions/Action3.java
- tests/src/cgeo/geocaching/models/CalculatedCoordinateTest.java
- tests/src/cgeo/geocaching/utils/TextParserTest.java
- tests/src/cgeo/geocaching/utils/formulas/FormulaTest.java
rel to #12378: change calculated config to something suitable for PN
> rel to #12378: change calculated config to something suitable for PN

- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/VariablesViewPageFragment.java
- main/src/cgeo/geocaching/models/CalculatedCoordinate.java
- main/src/cgeo/geocaching/models/Geocache.java
- main/src/cgeo/geocaching/models/WaypointParser.java
- main/src/cgeo/geocaching/utils/TextParser.java
- main/src/cgeo/geocaching/utils/formulas/VariableList.java
- tests/src-android/cgeo/geocaching/models/GeocacheTest.java
- tests/src/cgeo/geocaching/models/WaypointParserTest.java
- tests/src/cgeo/geocaching/utils/TextParserTest.java
fix #12378: import/export global calculated waypoints and variables
> fix #12378: import/export global calculated waypoints and variables

- main/src/cgeo/geocaching/settings/SettingsActivity.java
Fix calling "backup/restore" from home menu landing in settings' main screen
> fix calling backup/restore from home menu (fix #12479)

- main/src/cgeo/geocaching/ui/VariableListView.java
rel to #12497: tidy up shall not filter vars in var list tab
> rel to #12497: tidy up shall not filter vars in var list tab

- main/src/cgeo/geocaching/CacheListActivity.java
- main/src/cgeo/geocaching/ui/CacheListAdapter.java
rel to #12498: cleanup CacheListActivity.onResume, check change before filtering
> rel to #12498: cleanup CacheListActivity.onResume, check change before filtering

- main/src/cgeo/geocaching/MainActivity.java
> fix missing c:geo logo on main activity

- main/src/cgeo/geocaching/maps/AbstractMap.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
> fix missing target line after enabling live

- main/res/values/strings.xml
- main/src/cgeo/geocaching/CacheListActivity.java
Fixes a lint message of type "plurals candidate"
> fix lint 'plurals candidate'

- main/res/layout/waypoint_item.xml
Fix two lint messages of type "obsolete layout parameters" (removing two parameters not suitable in that context)
> fix lint: remove two obsolete layout params

- main/res/values/strings.xml
> fix lint: remove unused strings

- main/res/values-night/colors_dark.xml
- main/res/values/colors.xml
- main/res/values/colors_light.xml
Remove a couple of colors no longer in use
> fix lint: remove unused colors

- main/res/values/dimens.xml
Removes some dimension declarations no longer in use
> fix lint: remove some unused dimens declarations

- main/src/cgeo/geocaching/ui/dialog/SimpleDialog.java
This PR adds a "selectall" option to multiselect dialogs opened using SimpleDialog. For example:
> SimpleDialog multiselect: add selectall option

- main/src/cgeo/geocaching/settings/fragments/BasePreferenceFragment.java
- main/src/cgeo/geocaching/ui/VariableListView.java
- main/src/cgeo/geocaching/ui/ViewUtils.java
- main/src/cgeo/geocaching/ui/recyclerview/ManagedListAdapter.java
- main/src/cgeo/geocaching/utils/AndroidRxUtils.java
- tests/src/cgeo/geocaching/ui/recyclerview/ManagedListAdapterTest.java
fix #12510: introduce own variable list view focus handling, keep focus on correct var
Also fixes a bug where newly entered vars in calculated coordinate list view were not correctly sorted.
> fix #12510: introduce own variable list view focus handling, keep focus on correct var

- main/src/cgeo/geocaching/SearchActivity.java
rel to #12409: strip permissions from searchactivity intent before giving it back
> rel to #12409: strip permissions from searchactivity intent before giving it back

- main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
Fixes individual route not being shown on GM
> fix #12557: individual route not being shown on GM

- main/src/cgeo/geocaching/utils/TextParser.java
- main/src/cgeo/geocaching/utils/formulas/Formula.java
- tests/src/cgeo/geocaching/utils/formulas/FormulaTest.java
Fix #12496
@eddiemuc a review would be appreciated ;-)
> Allow in-line comments for variables 

- main/src/cgeo/geocaching/activity/AbstractBottomNavigationActivity.java
> Re-enable LongClick on "Stored" 

- main/src/cgeo/geocaching/models/CalculatedCoordinate.java
- main/src/cgeo/geocaching/models/CalculatedCoordinateType.java
- main/src/cgeo/geocaching/ui/CalculatedCoordinateInputGuideView.java
- main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateGlobalDialog.java
- main/src/cgeo/geocaching/utils/TextParser.java
- main/src/cgeo/geocaching/utils/TextUtils.java
- main/src/cgeo/geocaching/utils/formulas/DegreeFormula.java
- main/src/cgeo/geocaching/utils/formulas/Formula.java
- tests/src/cgeo/geocaching/models/CalculatedCoordinateTest.java
- tests/src/cgeo/geocaching/utils/TextUtilsTest.java
- tests/src/cgeo/geocaching/utils/formulas/DegreeFormulaTest.java
- tests/src/cgeo/geocaching/utils/formulas/FormulaTest.java
fix #12511: implement calculated coordinate parsing rules according to issue
> fix #12511: implement calculated coordinate parsing rules according to issue

- main/res/layout/routes_tracks_item.xml
- main/src/cgeo/geocaching/maps/RouteTrackUtils.java
- give visual feedback and show tooltip
- switch icon meaning for visibility button
(fix #12552)
> Align MultiTrackFile GUI to the rest of cgeo

- main/src/cgeo/geocaching/models/CacheVariableList.java
fix #12535: keep used vars on tidy up
> fix #12535: keep used vars on tidy up

- main/src/cgeo/geocaching/storage/extension/Trackfiles.java
> show better display name for tracks

- main/src/cgeo/geocaching/maps/RouteTrackUtils.java
As suggested in https://github.com/cgeo/cgeo/issues/12129#issuecomment-1018895864
> Allow multi-file selection while importing track

- main/res/layout/waypoint_item.xml
- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/utils/TextParser.java
- main/src/cgeo/geocaching/utils/formulas/DegreeFormula.java
- main/src/cgeo/geocaching/utils/formulas/Formula.java
- main/src/cgeo/geocaching/utils/formulas/FormulaException.java
- main/src/cgeo/geocaching/utils/formulas/FormulaFunction.java
- main/src/cgeo/geocaching/utils/formulas/VariableMap.java
- tests/src/cgeo/geocaching/utils/formulas/DegreeFormulaTest.java
- tests/src/cgeo/geocaching/utils/formulas/FormulaTest.java
- tests/src/cgeo/geocaching/utils/formulas/VariableMapTest.java
fix #12572: handle strange DMM formats
> fix #12572: handle strange DMM formats

- main/res/layout/coordinatescalculateglobal_dialog.xml
- main/src/cgeo/geocaching/storage/DataStore.java
- main/src/cgeo/geocaching/ui/VariableListView.java
- main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateGlobalDialog.java
- main/src/cgeo/geocaching/ui/dialog/SimpleDialog.java
- main/src/cgeo/geocaching/utils/formulas/Formula.java
- main/src/cgeo/geocaching/utils/formulas/FormulaFunction.java
- main/src/cgeo/geocaching/utils/formulas/IntegerRange.java
- main/src/cgeo/geocaching/utils/formulas/VariableList.java
- main/src/cgeo/geocaching/utils/formulas/VariableMap.java
- main/src/cgeo/geocaching/utils/functions/Func4.java
- tests/src/cgeo/geocaching/utils/formulas/FormulaTest.java
rel to #12384: first version of waypoint generator from variable ranges
First version for generation of waypoints from calculated coordinates
> rel to #12384: first version of waypoint generator from variable ranges

- main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
Treat individual route similar to tracks in GM (as it's already done for NewMap), which fixes the "changing visibility does not work for individual route on GM" issue.
> treat individual route similar to tracks in GM (fix #12589)

- main/src/cgeo/geocaching/utils/formulas/Formula.java
- tests/src/cgeo/geocaching/utils/formulas/FormulaTest.java
fix #12599: add support for one-char-exponents for 2 and 3
> fix #12599: add support for one-char-exponents for 2 and 3

- main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java
> fix #12616: fix npe in cid

- main/src/cgeo/geocaching/downloader/ReceiveDownloadService.java
Our downloader checks stored data for files having the same name as the downloaded file and deletes them first before copying the download to the target folder. This fails when the filename differ in capitalization only, see #12403, and results in filenames like `texas.map`, `Texas (1).map` (instead of `Texas.map`) etc.
This PR checks the target folder for the filename in different capitalizations and deletes them as well. Thus when downloading a new version of `Texas.map`, an already existing `texas.map` will be detected an deleted.
This PR also checks for filenames which only differ in "-" vs. "_" and deletes the related file as well. (We had such differences in the past with OAM maps.)
This PR only avoids new duplications, it does not check and delete already existing duplicates which …
> check downloaded files in different capitalizations (fix #12403)

- main/src/cgeo/geocaching/utils/TextParser.java
- main/src/cgeo/geocaching/utils/formulas/DegreeFormula.java
- main/src/cgeo/geocaching/utils/formulas/Formula.java
- main/src/cgeo/geocaching/utils/formulas/FormulaException.java
- tests/src/cgeo/geocaching/utils/formulas/DegreeFormulaTest.java
- tests/src/cgeo/geocaching/utils/formulas/FormulaTest.java
fix #12610: handle whitespaces in formulas as agreed in underlying issue
> fix #12610: handle whitespaces in formulas

- main/res/layout-land/coordinates_input_dialog.xml
fix #12646: fix npe in coord input dialog: add missing button in landscape mode
> fix #12646: fix npe in coord input dialog: add missing button in landscape mode

- main/res/values/strings.xml
- As we don't use the term dashboard I suggest to name it home screen here, as home is what the bottom nav button is called.
- Add "device" to make clear its the device wallpaper being used
#11867
> Improvement for wallpaper setting string

- main/res/layout/editwaypoint_activity.xml
trying to fix #12556: move hint to textlayout to avoid NPE
> trying to fix #12556: move hint to textlayout to avoid NPE

- main/src/cgeo/geocaching/settings/fragments/PreferenceOfflinedataFragment.java
mitigate NPE on maintenance notification
> mitigate NPE on maintenance notification (fix #12661)

- main/src/cgeo/geocaching/connector/gc/GCConstants.java
- tests/src/cgeo/geocaching/test/mock/GC1K1W4.html
- tests/src/cgeo/geocaching/test/mock/GC1ZXX2.html
- tests/src/cgeo/geocaching/test/mock/GC2CJPF.html
- tests/src/cgeo/geocaching/test/mock/GC2JVEH.html
- tests/src/cgeo/geocaching/test/mock/GC3FJ5F.html
- tests/src/cgeo/geocaching/test/mock/GC3XX5J.html
- tests/src/cgeo/geocaching/test/mock/GC5BRQK.html
- tests/src/cgeo/geocaching/test/mock/GC6K70B.html
pattern on geocaching.com for log count section has changed
fixes #12667
> fix pattern for GC.com log counts

- main/src/cgeo/geocaching/connector/gc/GCConnector.java
Cherry-picked the commit by @ztNFny from #12671 and pushed it on top of `release`.
Fixes #12659 
Superseeds #12671
@ztNFny Please check whether its complete
> use new page for uploading field notes

- main/src/cgeo/geocaching/connector/gc/GCLoggingManager.java
- main/src/cgeo/geocaching/connector/gc/GCWebAPI.java
fix #12673: enable posting log images again, adding verification token from website
> fix #12673: enable posting log images again, adding verification token from website

- main/res/values/strings_not_translatable.xml
Regular update to our c:geo-internal list of contributors, according to GitHub stats, in preparation for next release
> update list of contributors

- main/src/cgeo/geocaching/settings/Settings.java
> Increase history limit 

- main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
Some users have set their track history limit too high, so that they run into `OutOfMemory` exceptions in GM's `drawHistory`, as shown on Play Console stats (currently 260 occurrences for 27 users). This PR adds a try/catch block around it and logs the error to our log - better not draw a history than crash the map.
> catch OutOfMemory exception on GM.drawHistory

- main/res/values/strings.xml
- main/src/cgeo/geocaching/activity/AbstractBottomNavigationActivity.java
> Show history on long-click of "search" (fix #12687)

- main/AndroidManifest.xml
- main/src/cgeo/geocaching/models/Geocache.java
- main/src/cgeo/geocaching/service/CacheDownloaderService.java
- main/src/cgeo/geocaching/service/StopCacheDownloadServiceReceiver.java
> Allow canceling of background download (rel. to #330)

- main/src/cgeo/geocaching/CreateShortcutActivity.java
- main/src/cgeo/geocaching/connector/gc/BookmarkUtils.java
- main/src/cgeo/geocaching/ui/TextSpinner.java
- main/src/cgeo/geocaching/ui/VariableListView.java
- main/src/cgeo/geocaching/ui/dialog/ContextMenuDialog.java
- main/src/cgeo/geocaching/ui/dialog/SimpleDialog.java
- main/src/cgeo/geocaching/utils/FilterUtils.java
fix #12710: Offline log: remove selector for logtype dropdown
> fix #12710: Offline log: remove selector for logtype dropdown

- main/res/values/strings.xml
AFAIR the automatic backup feature does no longer work with reminders on the dashboard but is just performed.
If this is correct, then there is a left over: Wrong caption of the corresponding setting, which is fixed with this PR.
None
> Fix string: Auto backup is no longer a reminder

- main/res/raw/routing_fastbike.brf
- main/res/raw/routing_lookups.dat
- main/res/raw/routing_trekking.brf
- main/src/cgeo/geocaching/brouter/BRouterWorker.java
- main/src/cgeo/geocaching/brouter/core/MessageData.java
- main/src/cgeo/geocaching/brouter/core/OsmNogoPolygon.java
- main/src/cgeo/geocaching/brouter/core/OsmPath.java
- main/src/cgeo/geocaching/brouter/core/OsmTrack.java
- main/src/cgeo/geocaching/brouter/core/RoutingContext.java
- main/src/cgeo/geocaching/brouter/core/RoutingEngine.java
- main/src/cgeo/geocaching/brouter/core/StdPath.java
- main/src/cgeo/geocaching/brouter/expressions/BExpression.java
- main/src/cgeo/geocaching/brouter/expressions/BExpressionContext.java
- main/src/cgeo/geocaching/brouter/mapaccess/NodesCache.java
- main/src/cgeo/geocaching/brouter/package-info.java
- tests/src-android/cgeo/geocaching/brouter/expressions/EncodeDecodeTest.java
Update internal BRouter engine to v1.6.3 (the newest released version of BRouter)
> update internal BRouter engine to v1.6.3 (fix #12412)

- main/build.gradle
- main/src/cgeo/geocaching/connector/gc/GCWebAPI.java
- main/src/cgeo/geocaching/network/HttpRequest.java
- main/src/cgeo/geocaching/network/HttpResponse.java
- main/src/cgeo/geocaching/network/Network.java
- tests/src/cgeo/geocaching/network/HttpRequestTest.java
refactor http request response interface
> refactor http request response interface

- main/res/layout/cachedetail_variables_page.xml
fix #12718: dont cut off var tab buttons
> fix #12718: dont cut off var tab buttons

- main/res/drawable/dot_waypoint_generated.xml
- main/res/drawable/waypoint_generated.xml
- main/res/values/strings.xml
- main/src/cgeo/geocaching/EditWaypointActivity.java
- main/src/cgeo/geocaching/enumerations/WaypointType.java
- main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateGlobalDialog.java
- tests/src/cgeo/geocaching/apps/AbstractLocusAppTest.java
Stores generated waypoints using a new waypoint type.
For screenshots see https://github.com/cgeo/cgeo/issues/12626#issuecomment-1030830136
Setting "WIP" for now, as some waypoint handling features should be added. For a proposal see https://github.com/cgeo/cgeo/issues/12626#issuecomment-1030825175
> introduce new wapoint type for generated waypoints (rel. to #12626)

- main/res/layout-land/coordinates_input_dialog.xml
- main/res/layout/coordinates_input_dialog.xml
- main/res/values/strings.xml
- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/calculator/CalculatedCoordinateMigrator.java
- main/src/cgeo/geocaching/models/CalculatedCoordinate.java
- main/src/cgeo/geocaching/models/WaypointParser.java
- main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java
fix #12382: enable global calculated coords / variables for all users
> fix #12382: enable global calculated coords / variables for all users

- main/res/menu/cache_options.xml
- main/res/values/strings.xml
- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/models/Geocache.java
Add option to cache detail pages to remove all generated waypoints (similar to "remove all user-defined waypoints")
> Add menu item to remove all generated waypoints (rel. to #12626)

- main/src/cgeo/geocaching/calculator/CalculatedCoordinateMigrator.java
- tests/src/cgeo/geocaching/calculator/CalculatedCoordinateMigratorTest.java
fix #12754: migrate square brackets to normal ones
> fix #12754: migrate square brackets to normal ones

- main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java
fix #12751: open calc coord dialog in guided mode if possible
> fix #12751: open calc coord dialog in guided mode if possible

- main/res/layout/coordinatescalculateglobal_dialog.xml
- main/res/menu/cache_options.xml
- main/res/values/strings.xml
- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/VariablesViewPageFragment.java
- main/src/cgeo/geocaching/activity/AbstractActivity.java
- main/src/cgeo/geocaching/models/Geocache.java
- main/src/cgeo/geocaching/models/Waypoint.java
- main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateGlobalDialog.java
- main/src/cgeo/geocaching/utils/formulas/FormulaUtils.java
- tests/src/cgeo/geocaching/utils/formulas/FormulaUtilsTest.java
fix #12383, fix #12596: add ability to scan and copypaste calculated waypoints
> fix #12383, fix #12596: add ability to scan and copypaste calculated waypoints

- main/res/layout/calculatedcoordinate_input_guide.xml
- main/res/values/strings.xml
Fixes two hardcoded strings in waypoint calculator guided input to allow translation
None
> Coord guided mode - Make strings translatable

- main/src/cgeo/geocaching/ui/VariableListView.java
- main/src/cgeo/geocaching/utils/formulas/FormulaFunction.java
rel to #12769: show short abbrevation of function in list
> rel to #12769: show short abbrevation of function in list

- main/src/cgeo/geocaching/ui/VariableListView.java
fix #12769: insert function at cursor pos, dont delete existing content
> fix #12769: insert function at cursor pos, dont delete existing content

- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
fix #12768: stay at position on map change from google to osm
> fix #12768: stay at position on map change from google to osm

- main/res/raw/license.txt
Increment license year to current year
#12794
> Fix #12794 - Set license year

- main/res/values/strings_not_translatable.xml
This changes the target for the help button to our user guide.
As a first step the English page is targeted.
Further improvement could be to dynamically create the link based on user language.
See: https://github.com/cgeo/cgeo-guide/issues/54
https://github.com/cgeo/cgeo-guide/issues/54
> Use c:cgeo user guide for formula syntax help

- main/src/cgeo/geocaching/sorting/AbstractCacheComparator.java
fix #12803: remove suspicious code in comparator
> fix #12803: remove suspicious code in comparator

- main/res/layout/authorization_credentials_activity.xml
- main/res/layout/authorization_token_activity.xml
- main/res/layout/cache_filter_generic_string.xml
- main/res/layout/coordinates_calculate.xml
- main/res/layout/coordinates_input.xml
- main/res/layout/coordinatescalculateglobal_dialog.xml
- main/res/layout/dialog_edittext.xml
- main/res/layout/editwaypoint_activity.xml
- main/res/layout/gpx_export_individual_route_dialog.xml
- main/res/layout/imageselect_activity.xml
- main/res/layout/logtrackable_activity.xml
- main/res/layout/search_activity.xml
- main/res/layout/udc_create.xml
- main/res/layout/variable_list_item_advanced.xml
- main/res/layout/view_settings_add.xml
- main/res/values/styles.xml
As discussed in #12780: Prevent keyboard full-screen in single line text fields
> prevent keyboard fullscreen in single line text fields

- main/build.gradle
- main/res/menu/abstract_logging_activity.xml
- main/res/values/strings.xml
- main/src/cgeo/geocaching/CgeoApplication.java
- main/src/cgeo/geocaching/connector/capability/Smiley.java
- main/src/cgeo/geocaching/connector/capability/SmileyCapability.java
- main/src/cgeo/geocaching/connector/gc/GCConnector.java
- main/src/cgeo/geocaching/connector/gc/GCSmileysProvider.java
- main/src/cgeo/geocaching/connector/oc/OCConnector.java
- main/src/cgeo/geocaching/connector/oc/OCSmileysProvider.java
- main/src/cgeo/geocaching/log/AbstractLoggingActivity.java
fixes #12471
- add smiley description to the smiley
- add translation possibility
- add and fix OC smileys
> improve log smileys

- main/src/cgeo/geocaching/connector/gc/GCMap.java
fix #12807: prevent hidden npe in gcmap
> fix #12807: prevent hidden npe in gcmap

- main/src/cgeo/geocaching/utils/ImageUtils.java
fix #12804: prevent npe in imageutils
> fix #12804: prevent npe in imageutils

- main/src/cgeo/geocaching/storage/extension/Trackfiles.java
> fix #12760: show better name when selecting a gpx file

- main/src/cgeo/geocaching/maps/CGeoMap.java
- main/src/cgeo/geocaching/maps/RouteTrackUtils.java
- main/src/cgeo/geocaching/maps/Tracks.java
fix #12770: apply stored hidden flag to route on load
>  fix #12770: apply stored hidden flag to route on load

- main/res/xml/preferences_system.xml
- main/src/cgeo/geocaching/settings/fragments/PreferenceSystemFragment.java
Hide internal preference in production builds
> hide internal preference (fix #12830)

- main/res/layout/cachedetail_imagegallery_page.xml
- main/res/layout/cachedetail_images_page.xml
- main/res/layout/image_gallery_image.xml
- main/res/layout/image_gallery_view_category.xml
- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/ImageSelectActivity.java
- main/src/cgeo/geocaching/log/LogCacheActivity.java
- main/src/cgeo/geocaching/log/LogEntry.java
- main/src/cgeo/geocaching/models/Geocache.java
- main/src/cgeo/geocaching/models/Image.java
- main/src/cgeo/geocaching/storage/ContentStorage.java
- main/src/cgeo/geocaching/storage/DataStore.java
- main/src/cgeo/geocaching/ui/ImageActivityHelper.java
- main/src/cgeo/geocaching/ui/ImageGalleryView.java
- main/src/cgeo/geocaching/ui/ImageListFragment.java
- main/src/cgeo/geocaching/ui/ImagesList.java
- main/src/cgeo/geocaching/ui/ViewUtils.java
- main/src/cgeo/geocaching/utils/ImageUtils.java
- tests/src-android/cgeo/geocaching/log/LogEntryTest.java
rel to #12783: redesign image tab, add edit features for own images
> rel to #12783: redesign image tab, add edit features for own images

- main/res/values/strings.xml
- main/src/cgeo/geocaching/filters/core/DifficultyGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/NumberRangeFilter.java
- main/src/cgeo/geocaching/filters/core/NumberRangeGeocacheFilter.java
- main/src/cgeo/geocaching/filters/gui/DifficultyAndTerrainFilterViewHolder.java
- main/src/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java
- main/src/cgeo/geocaching/filters/gui/ItemRangeSelectorViewHolder.java
- tests/src-android/cgeo/geocaching/filters/NumberRangeGeocacheFilterTest.java
fix #11499: allow inclusion of caches without d/t in filter
> fix #11499: allow inclusion of caches without d/t in filter

- main/res/layout/image_gallery_category.xml
- main/res/layout/image_gallery_image.xml
- main/res/layout/image_gallery_view.xml
- main/res/values/dimens.xml
- main/res/values/strings.xml
- main/src/cgeo/geocaching/network/HtmlImage.java
- main/src/cgeo/geocaching/network/SmileyImage.java
- main/src/cgeo/geocaching/ui/ImageGalleryView.java
- main/src/cgeo/geocaching/ui/ViewUtils.java
- main/src/cgeo/geocaching/utils/ImageDataMemoryCache.java
- main/src/cgeo/geocaching/utils/MetadataUtils.java
rel to #12783: redesign formatting of image gallery
> rel to #12783: redesign formatting of image gallery

- main/res/layout/image_gallery_image.xml
- main/res/values/dimens.xml
- main/res/values/styles.xml
- main/src/cgeo/geocaching/ui/ImageGalleryView.java
rel to #12783: add round corners and min-col-count=2
> rel to #12783: add round corners and min-col-count=2

- main/src/cgeo/geocaching/maps/Tracks.java
put tracks initialization into background thread to avoid stacking db requests on UI thread
> put tracks initialization into background thread (rel. to #12873)

- tests/src-android/cgeo/geocaching/filters/DateRangeGeocacheFilterTest.java
rel to #12886: add unit tests for date filter
No change in production code
> rel to #12886: add unit tests for date filter

- main/src/cgeo/geocaching/EditWaypointActivity.java
Show correct waypoint type for generated waypoints. 
Use the underlaying adapter to retrieve possible waypoint-types
fix #12892
> Show correct waypoint type for generated waypoints. 

- main/src/cgeo/geocaching/filters/core/StatusGeocacheFilter.java
#12625 used an ill-suited icon for the new "Has userdefined waypoints" filter. Changing it to something more fitting to the other icons in that dialog
> change icon for has_user_defined_waypoints filter

- main/src/cgeo/geocaching/SearchResult.java
- main/src/cgeo/geocaching/connector/gc/GCWebAPI.java
fix #10621: enable Proxy WebAPI v2 and gc.com attribute search
> fix #10621: enable Proxy WebAPI v2 and gc.com attribute search

- main/src/cgeo/geocaching/CacheDetailActivity.java
> always show new images tab, not just when non-empty

- main/res/layout/cachedetail_details_page.xml
remove Map Preview Box that was used for static maps a long time ago
> remove legacy Map Preview Box from layout

- main/src/cgeo/geocaching/models/Geocache.java
Don't show distance-circle for archived caches.
fix #12823
> Hide distance-circle for archived caches (fix #12823)

- main/src/cgeo/geocaching/maps/RouteTrackUtils.java
- main/src/cgeo/geocaching/models/IndividualRoute.java
Adds some logging for individual route handling, active in debug mode only.
Related to #12881
> Add logging for individual route handling (rel. to #12881)

- main/src/cgeo/geocaching/maps/CGeoMap.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
> extend map actionbar also on offline map

- main/src/cgeo/geocaching/connector/al/ALApi.java
as discussed someplace else, pls review
> multiple choice questions

- main/src/cgeo/geocaching/connector/al/ALApi.java
catch some exceptions on JSON transformation
> catch some exceptions on JSON transformation

- main/res/drawable/my_location_chevron.xml
(ignore the top of the icon, that's a display error in preview)
> rounded corners and slightly increase size of position icon

- main/src/cgeo/geocaching/brouter/mapaccess/NodesCache.java
caches SAF file info in `NodesCache` for one minute to speed up calculation of route segments
> add FileInformation cache to NodesCache (rel. to #12881)

- main/src/cgeo/geocaching/ui/CacheListAdapter.java
- main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java
fix #12755: resort cache list on every location change on distance sort order
> fix #12755: resort cache list on every location change on distance sort order

- main/res/menu/cache_options.xml
- main/res/values/strings.xml
- main/src/cgeo/geocaching/CacheMenuHandler.java
- main/src/cgeo/geocaching/connector/AbstractConnector.java
- main/src/cgeo/geocaching/connector/IConnector.java
- main/src/cgeo/geocaching/connector/gc/GCConnector.java
- main/src/cgeo/geocaching/models/Geocache.java
- main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java
fix #12912: add entry 'log in browser' to cache menu
> fix #12912: add entry 'log in browser' to cache menu

- build.gradle
use gradle-versions-filter version 0.1.8 instead of 0.1.10
> use gradle-versions-filter version 0.1.8 instead of 0.1.10

- .idea/checkstyle-idea.xml
- main/res/values/strings.xml
- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/RenderThemeHelper.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/RenderThemeSettingsFragment.java
- main/src/cgeo/geocaching/settings/SeekbarPreference.java
- main/src/cgeo/geocaching/settings/Settings.java
fix #12947: add setting to manipulate mapsforge scaling settings
> fix #12947: add setting to manipulate mapsforge scaling settings

- main/AndroidManifest.xml
- main/res/layout/imagegallery_activity.xml
- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/ImageGalleryActivity.java
- main/src/cgeo/geocaching/TrackableActivity.java
- main/src/cgeo/geocaching/log/LogsViewCreator.java
- main/src/cgeo/geocaching/ui/ImageGalleryView.java
- main/src/cgeo/geocaching/utils/ImageUtils.java
rel to #12783: add image gallery to trackables, logpics and spoilers
This PR, if merged, will add new image gallery also to trackables and makes it used also for logpics and spoilers (only in dev and nightly). This will also allow uploading own images for trackables.
> rel to #12783: add image gallery to trackables, logpics and spoilers

- main/src/cgeo/geocaching/ImageViewActivity.java
- main/src/cgeo/geocaching/ui/ImageGalleryView.java
rel to #12783: add endless loop detail view and jump on back
> rel to #12783: add endless loop detail view and jump on back

- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
fix #12972: scale scale bar together with map user scale
> fix #12972: scale scale bar together with map user scale

- main/res/drawable/ic_arrow_back.xml
- main/res/layout/imageview_image.xml
- main/res/transition/smooth_transition.xml
- main/res/values/themes.xml
- main/src/cgeo/geocaching/ImageViewActivity.java
- main/src/cgeo/geocaching/ui/ImageGalleryView.java
rel to #12783: add transitions to image gallery
> rel to #12783: add transitions to image gallery

- main/src/cgeo/geocaching/VariablesViewPageFragment.java
- main/src/cgeo/geocaching/calculator/CalculatedCoordinateMigrator.java
- main/src/cgeo/geocaching/ui/VariableListView.java
fix #12977, fix #12978, fix #12979: fix various bugs related to variables
> fix #12977, fix #12978, fix #12979: fix various bugs related to variables

- main/AndroidManifest.xml
- main/src/cgeo/geocaching/unifiedmap/AbstractPositionLayer.java
- main/src/cgeo/geocaching/unifiedmap/AbstractUnifiedMapView.java
- main/src/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
- main/src/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsView.java
- main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeThemeHelper.java
- main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeThemeSettings.java
- main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeThemeSettingsFragment.java
- main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmView.java
- main/src/cgeo/geocaching/unifiedmap/tileproviders/AbstractGoogleTileProvider.java
- main/src/cgeo/geocaching/unifiedmap/tileproviders/AbstractMapsforgeTileProvider.java
- main/src/cgeo/geocaching/unifiedmap/tileproviders/AbstractTileProvider.java
- add theming support for Mapsforge VTM,
- including theme options support
- (no theme legend yet)
- hooks for a GM theming support are available in `AbstractUnifiedMapView` (but no specific implementation yet)
> UnifiedMap: add Mapsforge theming support

- main/res/values/strings.xml
- main/res/xml/preferences_appearence.xml
Just noticed today, that the settings for the quick launch buttons are not localized but still hardcoded.
This PR fixes it.
None
Targeted to `release` to have a chance of fixing before we release current beta.
> Localize quick launch button settings

- main/res/layout/image_gallery_image.xml
- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/utils/ImageUtils.java
- tests/src-android/cgeo/geocaching/connector/trackable/GeolutinsParserTest.java
rel to #12783: switch image tabs, make scale mode fitcenter
> rel to #12783: switch image tabs, make scale mode fitcenter

- main/res/layout/imageview_activity.xml
- main/res/layout/imageview_image.xml
- main/src/cgeo/geocaching/ImageViewActivity.java
rel to #12783: enhance image detail view on slide
> rel to #12783: enhance image detail view on slide

- main/res/drawable/ic_menu_image.xml
- main/res/drawable/ic_menu_open_in_browser.xml
- main/res/layout/imageview_activity.xml
- main/res/layout/imageview_image.xml
- main/res/values/preference_keys.xml
- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/ImageGalleryActivity.java
- main/src/cgeo/geocaching/ImageViewActivity.java
- main/src/cgeo/geocaching/TrackableActivity.java
- main/src/cgeo/geocaching/settings/Settings.java
- main/src/cgeo/geocaching/ui/ImageGalleryView.java
- main/src/cgeo/geocaching/utils/BranchDetectionHelper.java
rel to #12783: add more image gallery enhancements: animations + icons
> rel to #12783: add more image gallery enhancements: animations + icons

- main/res/values/preference_keys.xml
- main/res/values/strings.xml
- main/res/xml/preferences_cachedetails.xml
- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/settings/Settings.java
> add option to not ROT13 the hint

- main/src/cgeo/geocaching/ImageViewActivity.java
- main/src/cgeo/geocaching/TrackableActivity.java
- main/src/cgeo/geocaching/ui/ImageGalleryView.java
- main/src/cgeo/geocaching/utils/BackupUtils.java
fix #13014: fix npe on nonexisting imagegallery, fix npe on nonexisting jumpback in imagegallery
> fix #13014: fix npe on nonexisting imagegallery, fix npe on nonexisting jumpback in imagegallery

- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/VariablesViewPageFragment.java
- main/src/cgeo/geocaching/models/CacheVariableList.java
- main/src/cgeo/geocaching/models/Geocache.java
fix #13027: prevent crash on note recreation of calc waypoints
> fix #13027: prevent crash on note recreation of calc waypoints

- main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeThemeHelper.java
- main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmView.java
fix crash on changing map from mapsforge offline vector map with theme to mapsforge online bitmap map (without theme)
> fix crash on VTM mapsforge map change

- main/src/cgeo/geocaching/ImageViewActivity.java
- main/src/cgeo/geocaching/TrackableActivity.java
- main/src/cgeo/geocaching/connector/gc/GCParser.java
- main/src/cgeo/geocaching/models/Trackable.java
Fix #13030
- Fix NPE in trackable image gallery
- Use ImageViewActivity for enlarging trackable avatar
> Improve image gallery in context of trackable 

- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/models/WaypointParser.java
- tests/src/cgeo/geocaching/models/WaypointParserTest.java
rel to #13054: allows extraction to note also when there is no waypoint
> rel to #13054: allows extraction to note also when there is no waypoint

- main/res/layout/image_gallery_category.xml
- main/res/layout/image_gallery_image.xml
- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/ImageViewActivity.java
- main/src/cgeo/geocaching/ui/ImageGalleryView.java
- main/src/cgeo/geocaching/utils/ImageUtils.java
rel to #12783: redesign imagegallery to use gridlayout and simpler transitioning logic
> rel to #12783: redesign imagegallery to use gridlayout and simpler transitioning logic

- main/res/menu/waypoint_options.xml
- main/res/values/strings.xml
- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/utils/CheckerUtils.java
fix #13051: add possibility to check waypoint in geochecker
> fix #13051: add possibility to check waypoint in geochecker

- main/res/layout/cachedetail_imagegallery_page.xml
- main/res/layout/imageview_activity.xml
- main/res/layout/imageview_image.xml
- main/res/values/strings.xml
- main/src/cgeo/geocaching/ImageViewActivity.java
- main/src/cgeo/geocaching/models/Image.java
- main/src/cgeo/geocaching/storage/AbstractContentAccessor.java
- main/src/cgeo/geocaching/storage/ContentStorage.java
- main/src/cgeo/geocaching/storage/DocumentContentAccessor.java
- main/src/cgeo/geocaching/storage/FileContentAccessor.java
- main/src/cgeo/geocaching/ui/ImageGalleryView.java
- main/src/cgeo/geocaching/utils/ImageUtils.java
- tests/src-android/cgeo/geocaching/storage/ContentStorageTest.java
rel to #12783: allow renaming of own files in gallery
> rel to #12783: allow renaming of own files in gallery

- main/src/cgeo/geocaching/CacheListActivity.java
- main/src/cgeo/geocaching/service/CacheDownloaderService.java
> Refresh single caches in background (rel. to #330)

- main/src/cgeo/geocaching/ImageGalleryActivity.java
- main/src/cgeo/geocaching/ImageViewActivity.java
fix #13008: fix transition problems for single image galleries
> fix #13008: fix transition problems for single image galleries

- main/res/values/strings.xml
- main/src/cgeo/geocaching/models/Geocache.java
- main/src/cgeo/geocaching/service/CacheDownloaderService.java
- Some localization for background downloader
- Handle failed downloads correctly (e.g. if network connection was interrupted)
> Some improvement of background downloader

- main/res/values/preference_keys.xml
- main/src/cgeo/geocaching/connector/gc/GCLogin.java
- main/src/cgeo/geocaching/settings/Settings.java
- main/src/cgeo/geocaching/utils/SystemInformation.java
Store last login error (status & time) for gc connector as well as time for last successful login:
> add gc login status to system info (fix #13079)

- main/res/layout/cache_information_item.xml
- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/TrackableActivity.java
- main/src/cgeo/geocaching/ui/CacheDetailsCreator.java
- Replace RelativeLayout with LinearLayout for cleanup and perf, since the layout is simple
- Fix the lint error for ConstraintLayout Flow
- Fix the lint error for inflate params
- Use a custom class instead of ImmutablePair for clearer properties
> Fix lint issues in cache info item

- main/src/cgeo/geocaching/ui/VariableListView.java
fix #13124: handle npe in varlist
> fix #13124: handle npe in varlist

- main/src/cgeo/geocaching/unifiedmap/AbstractUnifiedMapView.java
- main/src/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
- main/src/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsView.java
Disable "follow my location" on manual map move for UnifiedMap GM
> UnifiedMap GM: reset followMyLocation on manual map move (fix #13096)

- main/src/cgeo/geocaching/maps/routing/InternalServiceConnection.java
Catch NPE happening locally in InternalServiceConnection
> Catch NPE in InternalServiceConnection (fix #13125)

- main/src/cgeo/geocaching/helper/QueryMapFile.java
> Catch NPE in QueryMapFile (fix #13155)

- main/src/cgeo/geocaching/settings/Settings.java
rel to #13160: allow disabling of image gallery in dev/nightlies
> rel to #13160: allow disabling of image gallery in dev/nightlies

- main/src/cgeo/geocaching/connector/gc/GCMap.java
- main/src/cgeo/geocaching/connector/gc/GCWebAPI.java
- Parse trackable count (fix #12415)
- Parse cache region
- Parse attributes (this allows client side filtering of negative attributes, currently only positive attributes are supported)
> Actually use the new capabilities of search v2

- main/res/values/strings.xml
- main/src/cgeo/geocaching/connector/al/ALApi.java
- main/src/cgeo/geocaching/filters/core/DateFilter.java
- main/src/cgeo/geocaching/filters/core/DateRangeGeocacheFilter.java
- main/src/cgeo/geocaching/utils/Formatter.java
This combines 4 small changes to work towards a proper date filtering capability for ALs. I'm submitting it now to avoid the PR getting too big, even though GUI is still missing.
- support setting a relative date in Date filters
- set the "hidden" date on AL search results
- switch AL search to SearchV4
- support the hidden since X days parameter in AL search
> AL SearchV4 with support for hidden since parameter & relative date filter backend

- main/build.gradle
- main/src/cgeo/geocaching/CacheListActivity.java
- main/src/cgeo/geocaching/maps/AbstractMap.java
- main/src/cgeo/geocaching/maps/CGeoMap.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
- main/src/cgeo/geocaching/service/CacheDownloaderService.java
- main/src/cgeo/geocaching/service/GeocacheRefreshedBroadcastReceiver.java
Creates a helper class for listening to geocache refreshed broadcasts. The helper handles registering and unregistering a broadcast receiver.
https://developer.android.com/topic/libraries/architecture/lifecycle
> Add lifecycle aware broadcast receiver

- main/src/cgeo/geocaching/location/Geopoint.java
- main/src/cgeo/geocaching/settings/Settings.java
- main/src/cgeo/geocaching/unifiedmap/AbstractUnifiedMapView.java
- main/src/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
- main/src/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsView.java
- main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmView.java
A couple of updates for `UnifiedMap`:
- hide ProgressBar on map startup
- save & restore center/zoom for default map type
- respect "zoom includes waypoints" setting for cache map
- defer mapMode from mapType
- preserve zoom and position on screen rotation
> Updates for UnifiedMap

- main/src/cgeo/geocaching/connector/gc/GCWebAPI.java
Fix NPE in new attributes web API check to prevent empty search results
> Fix NPE resulting in empty search results (fix #13200)

- main/src/cgeo/geocaching/maps/CGeoMap.java
Try setting GM broadcast receiver in `onCreate` instead of waiting until map initialization has finished
See https://github.com/cgeo/cgeo/pull/13218#issuecomment-1169478682
> try setting GM broadcast receiver earlier in lifecycle (rel. to #13218)

- main/res/values/preference_keys.xml
- main/src/cgeo/geocaching/settings/Settings.java
- main/src/cgeo/geocaching/storage/DataStore.java
Make sure DB cleanup code gets called no more frequently than every 24 hours
> restrict db cleanup to once per day (rel. to #12204)

- main/src/cgeo/geocaching/models/RouteItem.java
Adjust name parsing for AL elements in individual routes
> Fix individual routes: AL items get changed into coords only, fix #13175

- main/src/cgeo/geocaching/unifiedmap/AbstractPositionLayer.java
- main/src/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
- main/src/cgeo/geocaching/unifiedmap/UnifiedTargetAndDistancesHandler.java
- main/src/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsPositionLayer.java
- main/src/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsView.java
- main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmView.java
- enable distanceView for targets
- avoid blinking direction line on GM
> UnifiedMap: Enable distanceView for targets

- main/src/cgeo/geocaching/models/Geocache.java
- tests/src-android/cgeo/geocaching/connector/su/SuParserTest.java
- tests/src-android/cgeo/geocaching/filters/StatusGeocacheFilterTest.java
- tests/src-android/cgeo/geocaching/models/GeocacheTest.java
never return disabled state if cache is archived (fix #11428)
> Fix archived and deactivated at same time issues

- main/res/layout/dialog_background_download_config.xml
- main/res/values/strings.xml
- main/src/cgeo/geocaching/CacheListActivity.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
- main/src/cgeo/geocaching/service/CacheDownloaderService.java
- main/src/cgeo/geocaching/storage/DataStore.java
Show advanced selection dialog if some caches are already stored offline
> Background downloader enhancements

- main/res/menu/cache_list_options.xml
- main/res/menu/map_activity.xml
- main/res/values/strings.xml
- main/src/cgeo/geocaching/CacheListActivity.java
- main/src/cgeo/geocaching/maps/CGeoMap.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
As discussed in https://github.com/cgeo/cgeo/issues/330#issuecomment-1176558587:
- Call the new background downloader when using the classic menu items
- remove the additional experimental menu item
- remove legacy code for foreground downloads
- remove "nightly only" feature switches introduced for background downloader development
> Finally enable background downloader (fix #330)

- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/activity/AbstractActivity.java
- main/src/cgeo/geocaching/utils/LifecycleAwareBroadcastReceiver.java
- main/src/cgeo/geocaching/utils/LifecycleStartedBroadcastReceiver.java
More work decoupling logic from the activity methods. Helper class for local broadcast receivers that cleans itself up on activity destroy.
> Start/stop local broadcast receiver automatically using create/destroy

- main/src/cgeo/geocaching/connector/oc/OkapiClient.java
use user-defined radius in requests to OK API search instead of hardcoded 200km
> use radius from filter for OK API search

- main/src/cgeo/geocaching/service/CacheDownloaderService.java
rel. to https://github.com/cgeo/cgeo/issues/13262
- Use multithreading for background cache downloader
- add some logging to cache downloader
> Use multithreading for background cache downloader

- main/src/cgeo/geocaching/MainActivity.java
> show correct content description for MainActivity's up-indicator

- main/src/cgeo/geocaching/activity/AbstractBottomNavigationActivity.java
Correctly hide "not logged in" info as soon as a login was successful after the info got already shown...
> better handling for "not logged in" info

- main/build.gradle
Switch to the commit on maspforge with support of SAF for hillshading
related to #12210
> Android Storage Access Framework for hillshading

- main/src/cgeo/geocaching/CacheDetailActivity.java
Hide old image gallery if new one is active...
> hide old image gallery if new one is active

- main/src/cgeo/geocaching/maps/CGeoMap.java
- main/src/cgeo/geocaching/maps/google/v2/GoogleMapView.java
- main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
- main/src/cgeo/geocaching/maps/interfaces/PositionAndHistory.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
- main/src/cgeo/geocaching/maps/mapsforge/v6/layers/TapHandlerLayer.java
fixes a typo in naming of variables and method names ("tab" vs. "tap")
> fix tab/tap typo

- main/src/cgeo/geocaching/LooperLogger.java
- main/src/cgeo/geocaching/MainActivity.java
- main/src/cgeo/geocaching/maps/CGeoMap.java
- main/src/cgeo/geocaching/maps/Tracks.java
- main/src/cgeo/geocaching/utils/AndroidRxUtils.java
At some comments which scheduler should be used for which task...
> use correct schedulers

- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/log/LogCacheActivity.java
- main/src/cgeo/geocaching/ui/ImageActivityHelper.java
`AsyncTask` was deprecated in API level 30 and should be replaced...
Reference: https://developer.android.com/reference/android/os/AsyncTask
> replace some deprecated AsyncTask's with AndroidRxUtils equivalent

- main/res/values/strings.xml
- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/connector/al/ALApi.java
- main/src/cgeo/geocaching/models/Geocache.java
- main/src/cgeo/geocaching/storage/DataStore.java
- main/src/cgeo/geocaching/ui/CacheDetailsCreator.java
an attempt to handle the Linear vs Random for lab caches. Pls review. There must be some bug as I can't retrieve the property from the cache object, it always returns `false` even when upon setting it the Log() shows it was `true`. Once we have fixed this, I plan to add `RatingsAverage` and `RatingsTotalCount` according to the same pattern.
> alcIsLinear

- main/src/cgeo/geocaching/ui/ItemRangeSlider.java
rel to #13261: enable graphical selection of same value for d/t in filter
> rel to #13261: enable graphical selection of same value for d/t in filter

- main/src/cgeo/geocaching/models/RouteItem.java
Fix map crash on loading an individual route containing a lab adventure
> fix map crash on individual route with lab adventure (fix #13324)

- main/src/cgeo/geocaching/connector/gc/GCParser.java
Avoids termination of activity on adding a cache to a bookmark list in debug mode.
> avoid crash on add to bookmark in debug mode (fix #13335)

- main/res/layout/variable_list_item_advanced.xml
- main/res/layout/variable_list_item_minimalistic.xml
stop lint complaining about hardcoded non-translatable label texts on variables tab
> fix lint hardcodedText in variables tab

- main/res/values/strings.xml
Remove several unused smiley strings
> fix lint: remove unused smiley strings

- main/res/values/strings.xml
- main/res/xml/preferences_map.xml
Map settings has a lot of stuff, add 2 new subsections to structure it better
> more subsections in map settings

- main/res/layout/logcache_activity.xml
- main/res/layout/logtrackable_activity.xml
- main/src/cgeo/geocaching/CacheListActivity.java
- main/src/cgeo/geocaching/activity/AbstractActionBarActivity.java
- main/src/cgeo/geocaching/activity/AbstractActivity.java
- main/src/cgeo/geocaching/activity/ActivityMixin.java
- main/src/cgeo/geocaching/log/LogCacheActivity.java
- main/src/cgeo/geocaching/log/LogTrackableActivity.java
> #13337 show loading indicator in log screens

- main/res/values/strings.xml
- main/src/cgeo/geocaching/log/LogTemplateProvider.java
- main/src/cgeo/geocaching/utils/Formatter.java
> add "DAYOFWEEK" as log variable

- main/src/cgeo/geocaching/CacheDetailActivity.java
Avoid NPE in CacheDetailActivity.onReceive when currently no cache is active/loaded
> fix NPE in CacheDetailActivity.onReceive (fix #13366)

- main/res/values/preference_keys.xml
- main/res/xml/preferences_services_geocaching_com.xml
- main/src/cgeo/geocaching/connector/gc/GCConstants.java
- main/src/cgeo/geocaching/connector/gc/GCLogin.java
- main/src/cgeo/geocaching/connector/gc/GCMemberState.java
- main/src/cgeo/geocaching/connector/gc/GCParser.java
- main/src/cgeo/geocaching/network/StatusUpdater.java
- main/src/cgeo/geocaching/settings/Settings.java
Unchecking the checkbox will disable the language switch. (default=enabled)
> add possibility to disable language switch

- main/src/cgeo/geocaching/log/LoggingUI.java
Provide "needs maintenance" and "needs archive" entries for gc connector for quick offline log menu
> provide NM/NA for quick offline logs for GC connector (rel. to #13343)

- main/src/cgeo/geocaching/log/LogTrackableActivity.java
https://github.com/cgeo/cgeo/pull/13377 broke TB logging, fix that
Also use dialogs instead of toasts in TB log activity to be in line with cache log activity
> fix tb logging

- main/src/cgeo/geocaching/connector/gc/GCConstants.java
- main/src/cgeo/geocaching/connector/gc/GCParser.java
- tests/src-android/cgeo/geocaching/CgeoApplicationTest.java
Remove owner parsing for PM caches viewed by basic members as discussed in #13228
> remove owner parsing for PM caches viewed by basic members

- main/src/cgeo/geocaching/connector/gc/GCConstants.java
- main/src/cgeo/geocaching/connector/gc/GCParser.java
> make TB logtype parsing language independent

- main/src/cgeo/geocaching/permission/PermissionHandler.java
- main/src/cgeo/geocaching/sensors/GeoData.java
Ask for fine permission if only coarse location is granted. relevant starting with Android 12.
fix #12152
> Handle missing fine location permission

- tests/src/cgeo/geocaching/location/GeopointTest.java
> minor code format changes

- main/src/cgeo/geocaching/downloader/package-info.java
Update downloader doc, adjusting to renamed files and slightly changed workflow
> Update downloader doc

- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
Prevents an NPE on routing mode change
> Prevent NPE in routing mode change (fix #13413)

- main/src/cgeo/geocaching/ui/ImageListFragment.java
> remove number of image default name if only one image is chosen

- main/res/values/preference_keys.xml
- main/src/cgeo/geocaching/settings/Settings.java
- main/src/cgeo/geocaching/storage/DataStore.java
- Call REINDEX every 90 days + when requesting maintenance manually
- Remove VACUUM
> REINDEX in regular intervals, remove VACUUM (rel. to #13423)

- main/src/cgeo/geocaching/connector/gc/GCLogin.java
fix https://github.com/cgeo/cgeo/issues/13228#issuecomment-1256904501 ff.
> catch crash in GCLogin.getWebsiteLanguage

- main/res/values/preference_keys.xml
- main/res/xml/preferences_services.xml
- main/src/cgeo/geocaching/network/Network.java
- main/src/cgeo/geocaching/settings/Settings.java
- remove “Identify as Android Browser” setting (close #13430)
- Identify as c:geo in user agent (fix #6611)
> User argent changes

- main/res/layout/filter_sort_bar.xml
> use action bar text color for filter info bar (fix #13456)

- main/res/values/strings.xml
- main/src/cgeo/geocaching/filters/core/StatusGeocacheFilter.java
- main/src/cgeo/geocaching/filters/gui/StatusFilterViewHolder.java
fix #13449: add status filter for DNF
> fix #13449: add status filter for DNF

- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/ImageGalleryActivity.java
- main/src/cgeo/geocaching/TrackableActivity.java
- main/src/cgeo/geocaching/utils/ImageUtils.java
> use image cache for log/spoiler image activity

- main/src/cgeo/geocaching/CacheListActivity.java
- main/src/cgeo/geocaching/list/PseudoList.java
show "delete from device" instead of "delete from list" if list is not offline
> fix menu item description

- main/res/values/strings.xml
In #13468 a new filter for DNF was introduced. I think however the label should not use the abbreviation but "Did not find" instead.
#13468 
#13449
> Do not use abbreviation DNF

- tests/src-android/cgeo/geocaching/downloader/DownloaderTest.java
Allow for a broader range of available routing tiles
> adapt test to increased number of routing tiles (fix #13485)

- main/res/values/strings.xml
- main/src/cgeo/geocaching/downloader/DownloaderUtils.java
- main/src/cgeo/geocaching/downloader/PendingDownloadsActivity.java
- remove hardcoded status messages in download status
- fix typo in error var
- use correct error var in "unknown error" status message
> cleanup: remove hardcoded status messages in download status

- main/res/layout/logcache_activity.xml
Removes unexpected text in resource file
> fix lint: unexpected text in resource file

- main/src/cgeo/geocaching/apps/cachelist/MapsMeCacheListApp.java
- main/src/cgeo/geocaching/utils/ProcessUtils.java
- main/src/cgeo/geocaching/utils/ShareUtils.java
Add missing flags required when targeting Android 12 (targetSDK 31)
@fm-sys 
As I've copied from your code ;-)
Can you cross-check whether using `FLAG_IMMUTABLE` is the right thing in those three places? Thanks.
> add missing pending intent flags (rel. to #13036)

- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/EditWaypointActivity.java
- main/src/cgeo/geocaching/connector/al/ALApi.java
closes #13491
Was more or less a one-liner to get image rendering working... Furthermore, I did some cleanup in `ALApi`.
-|-
> Display images in waypoints (v2)

- main/src/cgeo/geocaching/storage/DataStore.java
Somehow I managed to enter a TAB char, which breaks CheckStyle - replace it by spaces.
> fix CheckStyle: replace tab by spaces

- main/src/cgeo/geocaching/utils/formulas/FormulaUtils.java
- tests/src/cgeo/geocaching/utils/formulas/FormulaUtilsTest.java
fix #12867: make coordinate scan in text more reliable
see new unit tests for examples. All examples from issue #12867 should be covered
> fix #12867: make coordinate scan in text more reliable

- tests/src/cgeo/geocaching/location/GeopointTest.java
Reverts cgeo/cgeo#13433
As far as I understood this code is no longer necessary... @eddiemuc?
> Revert "minor code format changes"

- main/src/cgeo/geocaching/utils/ImageUtils.java
rel to #13138: make scanning for images in HTML much more performant
> rel to #13138: make scanning for images in HTML much more performant

- main/src/cgeo/geocaching/filters/core/AndGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/BaseGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/DateFilter.java
- main/src/cgeo/geocaching/filters/core/FavoritesGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/LogsCountGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/NumberRangeFilter.java
- main/src/cgeo/geocaching/filters/core/OrGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/StatusGeocacheFilter.java
- main/src/cgeo/geocaching/filters/core/StringFilter.java
- main/src/cgeo/geocaching/filters/core/UserDisplayableStringUtils.java
- main/src/cgeo/geocaching/filters/core/ValueGroupGeocacheFilter.java
- tests/src-android/cgeo/geocaching/filters/UserDisplayableStringTest.java
displayString-logic for min-max-filters
*-* -> * (normally this will not be displayed)
*-x -> <x
x-* -> >x
x-y -> x-y
fix #11409
> Improve user-display-string for D/T Filter and other

- main/res/values/strings.xml
- main/src/cgeo/geocaching/utils/ImageUtils.java
rel to #13551: fix nullpointerexception in ImageUtils.forEachImageUrlInHtml
> rel to #13551: fix nullpointerexception in ImageUtils.forEachImageUrlInHtml

- cgeo-contacts/build.gradle
- main/build.gradle
- mapswithme-api/build.gradle
- tests/AndroidManifest.xml
Set targetSdkVersion 31 also for the other sub projects and the tests. 
Additionally, set minSdkVersion 21 for tests and fix typo.
> targetSdk 31 part 2

- main/res/layout/unifiedmap_googlemaps.xml
- main/src/cgeo/geocaching/ui/TouchableWrapper.java
- main/src/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsView.java
UnifiedMap / GM: Detect taps on cluster of markers (short/long tap), not only on the map itself
> UnifiedMap (GM): Detect taps on cluster of markers

- main/src/cgeo/geocaching/unifiedmap/AbstractUnifiedMapView.java
- main/src/cgeo/geocaching/unifiedmap/LoadInBackgroundHandler.java
- main/src/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
- main/src/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsView.java
- main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmView.java
Enables live mode (and retrieving search results in background) for plain map type
> UnifiedMap: Enable live mode for PlainMap type

- main/src/cgeo/geocaching/unifiedmap/AbstractUnifiedMapView.java
- main/src/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
- main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeThemeHelper.java
- main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmView.java
- main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/legend/RenderThemeLegend.java
- main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/legend/ThemeLegend.java
- main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/legend/ThemeLegendElevate.java
- main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/legend/ThemeLegendFreizeitkarte.java
Adapts theme legend for UnifiedMap (OSM offline only)
> UnifiedMap: theme legend for OSM offline themes

- main/src/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
- main/src/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsThemeHelper.java
- main/src/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsView.java
- main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeThemeHelper.java
- main/src/cgeo/geocaching/unifiedmap/tileproviders/AbstractMapsforgeOfflineTileProvider.java
- main/src/cgeo/geocaching/unifiedmap/tileproviders/AbstractTileProvider.java
- main/src/cgeo/geocaching/unifiedmap/tileproviders/GoogleMapSource.java
Support built-in themes for GM
> UnifiedMap: add GM theming support (fix #13574)

- main/res/layout/cachedetail_imagegallery_page.xml
- main/res/layout/image_gallery_image.xml
- main/res/layout/imagegallery_view.xml
- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/ImageViewActivity.java
- main/src/cgeo/geocaching/TrackableActivity.java
- main/src/cgeo/geocaching/network/HtmlImage.java
- main/src/cgeo/geocaching/ui/ImageGalleryView.java
- main/src/cgeo/geocaching/utils/CategorizedListHelper.java
- main/src/cgeo/geocaching/utils/MetadataUtils.java
- tests/src/cgeo/geocaching/utils/CategorizedListHelperTest.java
rel to #13138: replace imagegalleryview self-made views with recyclerview
> rel to #13138: replace imagegalleryview self-made views with recyclerview

- main/res/layout/imageview_image.xml
- main/res/values/strings.xml
- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/ImageViewActivity.java
- main/src/cgeo/geocaching/models/Geocache.java
- main/src/cgeo/geocaching/ui/ImageGalleryView.java
fix #13138: make image details open also in large cache lists
> fix #13138: make image details open also in large cache lists

- main/src/cgeo/geocaching/ui/TextSpinner.java
- main/src/cgeo/geocaching/ui/dialog/SimpleDialog.java
- tests/src/cgeo/geocaching/ui/SimpleDialogTest.java
fix #13578: fix ioobe in SimpleDialog + TextSpinner
> fix #13578: fix ioobe in SimpleDialog + TextSpinner

- main/src/cgeo/geocaching/unifiedmap/AbstractUnifiedMapView.java
- main/src/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsThemeHelper.java
- main/src/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsView.java
- main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmView.java
(Code cleanup, no functional change)
- add more annotations
- move some methods to more plausible categories
- align order of inherited methods between `AbstractUnifiedMapView`, `GoogleMapsView` and `MapsforgeVtmView`
- remove some unused code
> UnifiedMap: MapViews code cleanup and alignment

- main/src/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
Prevents a crash happening on closing and reopening UnifiedMap (GM)
> UnifiedMap (GM): Avoid crash on map end/restart

- main/src/cgeo/geocaching/ImageViewActivity.java
fix #13622: ImageViewActivity: add handling of single uris and empty intents
> fix #13622: ImageViewActivity: add handling of single uris and empty intents

- main/src/cgeo/geocaching/CacheDetailActivity.java
- restore position after editing waypoints
- move to bottom when creating new waypoint
- stay at list position when deleting waypoint
fix https://github.com/cgeo/cgeo/issues/1905
> Fix waypoint scroll pos

- main/src/cgeo/geocaching/LooperLogger.java
fix potential ConcurrentModificationException in LooperLogger
Exception occured to me during development. This PR will fix the problem
> fix potential ConcurrentModificationException in LooperLogger

- main/res/xml/preferences_map.xml
add dependencies for hillshading preferences, greys-out dependent preferences if hillshading is disabled
> add hillshading preferences dependencies

- main/res/layout/cachedetail_imagegallery_page.xml
- main/src/cgeo/geocaching/CacheDetailActivity.java
- main/src/cgeo/geocaching/settings/Settings.java
This PR, if merged, will enable new image gallery in production and remove "experimental" status
> Enable new image gallery in production

- main/src/cgeo/geocaching/models/WaypointParser.java
- main/src/cgeo/geocaching/utils/formulas/FormulaUtils.java
- tests/src-android/cgeo/geocaching/models/GeocacheTest.java
- tests/src/cgeo/geocaching/calculator/FormulaParserTest.java
- tests/src/cgeo/geocaching/models/WaypointParserTest.java
- tests/src/cgeo/geocaching/utils/formulas/FormulaUtilsTest.java
rel to #12380: remove calc coord legacy code: rewrite parser for existing f-plain coordinates in pcn
> rel to #12380: remove calc coord legacy code: rewrite parser for existing f-plain coordinates in pcn

- main/res/raw/changelog_bugfix.md
- main/src/cgeo/geocaching/address/MapQuestGeocoder.java
The fix is tested and working, we should however check before merging, whether the old URL was used for a specific reason (e.g. better conditions for FOSS apps) or is just outdated.
#13677
> Fix #13677 - Update mapquest API URL

- main/src/cgeo/geocaching/connector/gc/GCParser.java
- main/src/cgeo/geocaching/connector/oc/OkapiClient.java
- main/src/cgeo/geocaching/connector/su/SuParser.java
- main/src/cgeo/geocaching/models/Geocache.java
fix #13674: reset and not just add spoiler images on cache data refresh
> fix #13674: reset and not just add spoiler images on cache data refresh

- main/src/cgeo/geocaching/utils/formulas/Formula.java
- main/src/cgeo/geocaching/utils/formulas/FormulaUtils.java
- tests/src/cgeo/geocaching/utils/formulas/FormulaTest.java
- tests/src/cgeo/geocaching/utils/formulas/FormulaUtilsTest.java
fix #13644: allow usage of square brackets in formulas
> fix #13644: allow usage of square brackets in formulas

- main/res/values/strings.xml
Related to #13676 I had the idea, that it is probably more convenient for the user anyway to get proper mitigation info directly in c:geo rather than a link to our FAQ.
I hope this will reduce the support requests regarding "Captcha".
> Related to #13676 - Provide more info directly in error message

- main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeThemeHelper.java
- main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/legend/RenderThemeLegend.java
- main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/legend/ThemeLegendOSMPaws.java
Adds theme legend for the new osm.paws.cz map source / theme to UnifiedMap
> UnifiedMap: Add map legend for osm.paws.cz theme (rel. to #13600)

- main/src/cgeo/geocaching/CgeoApplication.java
- main/src/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsView.java
Move internal utility function to a more appropriate place
> move app hashkey info to more appropriate place

- gradle/wrapper/gradle-wrapper.properties
from version 7.5 to 7.5.1.
See release notes at https://docs.gradle.org/7.5.1/release-notes.html
This is a bug fix release, no problems found so far.
> Upgrade gradle

- main/src/cgeo/geocaching/SearchActivity.java
Default cache search field to prefix after selecting search hit
Fixes #13748
> Default cache search field to prefix after selecting search hit

- main/res/values/strings.xml
- main/src/cgeo/geocaching/filters/core/DateFilter.java
- main/src/cgeo/geocaching/filters/core/DateRangeGeocacheFilter.java
- main/src/cgeo/geocaching/filters/gui/DateRangeFilterViewHolder.java
- main/src/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java
rel to #13152: add relative date filtering for hidden date.
> rel to #13152: add relative date filtering for hidden date

- main/res/menu/cache_list_options.xml
- main/res/values-ca/strings.xml
- main/res/values-cs/strings.xml
- main/res/values-da/strings.xml
- main/res/values-de/strings.xml
- main/res/values-el/strings.xml
- main/res/values-es/strings.xml
- main/res/values-fi/strings.xml
- main/res/values-fr/strings.xml
- main/res/values-it/strings.xml
- main/res/values-ja/strings.xml
- main/res/values-ko/strings.xml
- main/res/values-lt/strings.xml
- main/res/values-nb/strings.xml
- main/res/values-nl/strings.xml
- main/res/values-pl/strings.xml
- main/res/values-pt/strings.xml
- main/res/values-ru/strings.xml
- main/res/values-sk/strings.xml
- main/res/values-sv/strings.xml
- main/res/values-tr/strings.xml
- main/res/values/strings.xml
- main/src/cgeo/geocaching/CacheListActivity.java
- main/src/cgeo/geocaching/ui/CacheListAdapter.java
Adds an "select next 100" option to cache list menu in select mode
> Add 'select next 100' option for cache lists

- main/src/cgeo/geocaching/files/GPXTrackOrRouteImporter.java
- main/src/cgeo/geocaching/files/GPXWptAsTrackParser.java
Fix failing GPX import of flopp.net generated GPX files
> Add parsing of flopp.net GPX files as tracks (fix #13661)

- README.md
> change readme for the moved project structure

- main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgePositionLayer.java
Fixes an update problem with route/track segments on UnifiedMap
> UnifiedMap: Update TrackLayer after adding track/route elements

- main/AndroidManifest.xml
- main/src/main/java/cgeo/contacts/ContactsAddon.java
- main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
- main/src/main/java/cgeo/geocaching/connector/AbstractConnector.java
- main/src/main/java/cgeo/geocaching/contacts/ContactsHelper.java
- main/src/main/java/cgeo/geocaching/contacts/IContactCardProvider.java
- main/src/main/java/cgeo/geocaching/permission/PermissionAction.java
- main/src/main/java/cgeo/geocaching/permission/PermissionContext.java
- main/src/main/java/cgeo/geocaching/utils/ActivitySavedState.java
- main/src/main/res/values/strings.xml
rel to #13777: integrate Contacts Plugin into c:geo, add PermissionAction + ActivitySavedState
> rel to #13777: integrate Contacts Plugin into c:geo, add PermissionAction + ActivitySavedState

- main/project/rawimages/ic_launcher.svg
Add new cgeo svg logo in the repo
- #13808
geokrety/geokrety-website/issues/810
> fix #13808: Add c:geo svg logo

- main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
- main/src/main/java/cgeo/geocaching/CompassActivity.java
- main/src/main/java/cgeo/geocaching/InstallWizardActivity.java
- main/src/main/java/cgeo/geocaching/MainActivity.java
- main/src/main/java/cgeo/geocaching/permission/PermissionAction.java
- main/src/main/java/cgeo/geocaching/permission/PermissionContext.java
- main/src/main/java/cgeo/geocaching/settings/SettingsActivity.java
- main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceAppearanceFragment.java
- main/src/main/java/cgeo/geocaching/utils/ParcelableValue.java
- main/src/main/res/values/strings.xml
fix #13816: ask for read storage permission for wallpaper
> fix #13816: ask for read storage permission for wallpaper

- main/build.gradle
solve android studio classpath problems related to VTM
> solve android studio classpath problems related to VTM

- main/build.gradle
- main/src/main/java/cgeo/geocaching/files/GPXTrackOrRouteImporter.java
- main/src/main/java/cgeo/geocaching/location/GeoObject.java
- main/src/main/java/cgeo/geocaching/location/GeoObjectList.java
- main/src/main/java/cgeo/geocaching/location/IGeoDataProvider.java
- main/src/main/java/cgeo/geocaching/location/Viewport.java
- main/src/main/java/cgeo/geocaching/maps/AbstractMap.java
- main/src/main/java/cgeo/geocaching/maps/CGeoMap.java
- main/src/main/java/cgeo/geocaching/maps/RouteTrackUtils.java
- main/src/main/java/cgeo/geocaching/maps/Tracks.java
- main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapUtils.java
- main/src/main/java/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
- main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
- main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/AbstractRouteLayer.java
- main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/GeoObjectLayer.java
- main/src/main/java/cgeo/geocaching/models/Route.java
- main/src/main/java/cgeo/geocaching/unifiedmap/AbstractPositionLayer.java
- main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
- main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsPositionLayer.java
- main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsUtils.java
- main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeMapsUtils.java
- main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgePositionLayer.java
- main/src/main/java/cgeo/geocaching/utils/GeoJsonUtils.java
- main/src/test/java/cgeo/geocaching/utils/GeoJsonUtilsTest.java
rel to #13793: support display of geojson for mapsforge
> rel to #13793: support display of geojson for mapsforge

- main/src/androidTest/java/cgeo/geocaching/connector/gc/GCParserTest.java
- main/src/androidTest/java/cgeo/geocaching/models/GeocacheTest.java
- main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
- main/src/main/java/cgeo/geocaching/EditWaypointActivity.java
- main/src/main/java/cgeo/geocaching/activity/AbstractActivity.java
- main/src/main/java/cgeo/geocaching/models/CacheArtefactParser.java
- main/src/main/java/cgeo/geocaching/models/Geocache.java
- main/src/main/java/cgeo/geocaching/storage/DataStore.java
- main/src/main/java/cgeo/geocaching/utils/CommonUtils.java
- main/src/main/java/cgeo/geocaching/utils/formulas/VariableList.java
- main/src/main/res/layout/cachedetail_description_page.xml
- main/src/main/res/values/strings.xml
- main/src/test/java/cgeo/geocaching/models/CacheArtefactParserTest.java
fix #13838: allow var sync also from waypoint notes, enhance sync algorithm
> fix #13838: allow var sync also from waypoint notes, enhance sync algorithm

- main/src/main/java/cgeo/geocaching/storage/DocumentContentAccessor.java
DocumentContentAccessor: add debug-level logging.
Related to SAF discussion, trying to help with debugging those cases
> DocumentContentAccessor: add debug logging

- build.gradle
to be compatible to AS Spotbugs plugin
See
https://plugins.jetbrains.com/plugin/14014-spotbugs 
https://github.com/spotbugs/spotbugs-gradle-plugin#spotbugs-version-mapping
> Update spotbugs plugin

- main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapObjects.java
- main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapObjectsQueue.java
- main/src/main/java/cgeo/geocaching/maps/google/v2/MapObjectOptions.java
rel to #13793: google cgeo integration, add support for polygons
> rel to #13793: google cgeo integration, add support for polygons

- main/src/main/java/cgeo/geocaching/activity/AbstractActivity.java
fix #13751: update waypoint list after adding waypoint via scan
> fix #13751: update waypoint list after adding waypoint via scan

- main/src/main/java/cgeo/geocaching/utils/TextUtils.java
- main/src/test/java/cgeo/geocaching/utils/TextUtilsTest.java
fix #13869: rework HTML recognition method
For Reviewers: check new unit test examples -> anything missing /incorrect?
> fix #13869: rework HTML recognition method

- main/src/main/java/cgeo/geocaching/maps/CGeoMap.java
fix #13919: fix npe for routefilechekc on missing viewport
> fix #13919: fix npe for routefilechekc on missing viewport

- main/src/main/java/cgeo/geocaching/downloader/MapDownloaderOpenAndroMaps.java
- main/src/main/java/cgeo/geocaching/settings/ViewSettingsActivity.java
Fix two lint findings regarding Locale
> Fix two lint findings regarding Locale

- main/src/main/java/cgeo/geocaching/maps/CGeoMap.java
- main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
- main/src/main/java/cgeo/geocaching/sensors/GeoData.java
- main/src/main/java/cgeo/geocaching/settings/Settings.java
- main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
- main/src/main/res/values/preference_keys.xml
Use last known map position as fallback location when no location data (GPS) is available and "follow my location" was disabled.
> Use last known map position as fallback (fix #13275)

- main/src/main/java/cgeo/geocaching/connector/gc/AbstractListAdapter.java
> in PQ list always show the "Preview" PQ button

- main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/RenderThemeHelper.java
- main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/legend/RenderThemeLegend.java
- main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/legend/ThemeLegendVoluntary.java
- main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeThemeHelper.java
- main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/legend/RenderThemeLegend.java
- main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/legend/ThemeLegendVoluntary.java
- main/src/main/res/values/strings_not_translatable.xml
Adds basic theme legend for "Voluntary V5" theme (areas, symbols) for both Mapsforge and VTM offline maps.
> Add theme legend for 'Voluntary' theme (fix #13947)

- main/src/main/java/cgeo/geocaching/CacheMenuHandler.java
fix #13937: handle case of yet-unloaded-cache in cachedetails menu handler
> fix #13937: handle case of yet-unloaded-cache in cachedetails menu handler

- main/src/main/java/cgeo/geocaching/network/SmileyImage.java
> Prevent NPE in SmileyImage (fix #13713)

- main/src/main/java/cgeo/geocaching/maps/AbstractMap.java
- main/src/main/java/cgeo/geocaching/maps/CGeoMap.java
- main/src/main/java/cgeo/geocaching/maps/RouteTrackUtils.java
- main/src/main/java/cgeo/geocaching/maps/Tracks.java
- main/src/main/java/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
- main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
- main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/AbstractRouteLayer.java
- main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/RouteLayer.java
- main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/TrackLayer.java
- main/src/main/java/cgeo/geocaching/settings/ColorpickerPreference.java
- main/src/main/java/cgeo/geocaching/storage/extension/Trackfiles.java
- main/src/main/java/cgeo/geocaching/ui/ColorPickerUI.java
- main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
- main/src/main/res/layout/routes_tracks_item.xml
- main/src/main/res/values/strings.xml
Allow assigning an individual color for each loaded track
> Allow individual coloring of tracks

- main/src/main/java/cgeo/geocaching/utils/AsynchronousMapWrapper.java
- main/src/test/java/cgeo/geocaching/utils/AsynchronousMapWrapperTest.java
adds AsynchronousMapWrapper: abstraction to make async updates to mapobjects, derived from GoogleMapObjectsQueue
First step to create asynchronous map updates for all maps used in c:geo (VTM, Mapsforge, Google)
> adds AsynchronousMapWrapper: abstraction to make async updates to mapobjects, derived from GoogleMapObjectsQueue

- main/AndroidManifest.xml
- main/src/main/java/cgeo/geocaching/apps/navi/CruiserNavigationApp.java
- main/src/main/java/cgeo/geocaching/apps/navi/NavigationAppFactory.java
- main/src/main/res/values/preference_keys.xml
- main/src/main/res/values/strings.xml
- main/src/main/res/values/strings_not_translatable.xml
Rudimentary addition of Cruiser as navigation app
Do not merge yet - build is intended for testing by @devemux86.
> Add Cruiser as navigation app

- main/src/main/res/xml/preferences_navigation_navigation.xml
Fix navigation menu settings by adding template for Cruiser
> Fix navigation menu settings (fix #13976)

- main/src/main/java/cgeo/geocaching/files/GPXTrackOrRouteImporter.java
- main/src/main/java/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
- main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/AbstractRouteLayer.java
- main/src/main/java/cgeo/geocaching/models/Route.java
- main/src/main/java/cgeo/geocaching/utils/GeoJsonUtils.java
fix for checkstyle "info" messages
> fix import orders

- main/src/main/java/cgeo/geocaching/files/GPXTrackOrRouteImporter.java
- main/src/main/java/cgeo/geocaching/utils/EnvironmentUtils.java
- main/src/main/java/cgeo/geocaching/utils/SystemInformation.java
fix #13979: check memory before opening very large track files
> fix #13979: check memory before opening very large track files

- main/src/main/java/cgeo/geocaching/CgeoApplication.java
- main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceAppearanceFragment.java
fix #13982: update application level locale on user locale change in settings
> fix #13982: update application level locale on user locale change in settings

- main/src/main/java/cgeo/geocaching/ImageViewActivity.java
- main/src/main/java/cgeo/geocaching/ui/ImageGalleryView.java
- main/src/main/java/cgeo/geocaching/utils/ImageUtils.java
fix #13984: handle image orientation correctly
> fix #13984: handle image orientation correctly
