cgeo/cgeo

main/src/cgeo/geocaching/maps/DefaultMap.java, main/src/cgeo/geocaching/models/RouteItem.java, main/src/cgeo/geocaching/ui/GeoItemSelectorUtils.java, main/src/cgeo/geocaching/unifiedmap/AbstractGeoitemLayer.java, main/src/cgeo/geocaching/unifiedmap/AbstractPositionLayer.java, main/src/cgeo/geocaching/unifiedmap/AbstractUnifiedMapView.java, main/src/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/cgeo/geocaching/unifiedmap/UnifiedMapType.java, main/src/cgeo/geocaching/unifiedmap/googlemaps/GoogleGeoitemLayer.java, main/src/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsView.java, main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeGeoitemLayer.java, main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmView.java
- enable display of `SearchResult` on UnifiedMap (used for displaying both lists and actual search results)
- calculate & show map title
- handle tap events (cache/waypoint popups and selection popup)
=> show lists on UnifiedMap, show title (rel. to #12926)

main/res/values/preference_keys.xml, main/res/values/strings.xml, main/res/values/strings_not_translatable.xml, main/res/xml/preferences_map.xml, main/res/xml/preferences_services_geocaching_com.xml, main/res/xml/preferences_services_send_to_cgeo.xml, main/src/cgeo/geocaching/settings/fragments/PreferenceMapFragment.java
This ALSO addresses #13547 by replacing all android:text with android:summary in preference pages
=> add a preference category for hillshading, add explanatory text and link to wiki

main/res/raw/changelog_base.md, main/res/values-night/colors_dark.xml, main/res/values/colors.xml, main/res/values/colors_light.xml, main/src/cgeo/geocaching/CacheDetailActivity.java, main/src/cgeo/geocaching/CachePopupFragment.java, main/src/cgeo/geocaching/WaypointPopupFragment.java, main/src/cgeo/geocaching/activity/AbstractActivity.java, main/src/cgeo/geocaching/utils/TextUtils.java
- Apply different colors for name of archived caches for dark/light theme
- Remove coloring in cache details list (only show it in top bar of cache view and map popup)
This is draft and DNM, because its not applying the correct theme color for top bar and popup.
Its however working in list and in dropdown on home screen.
For better debugging I temporarily assigned 
GREEN = light theme
BLUE = dark theme
It looks like this now..dark theme is not applied everywhere:
| Dark | Light |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/949669/197186590-d0dbd33e-dfd4-45d6-9584-c4d1fa7071a1.png) | ![image](https://user-images.githubusercontent.com/949669/197187015-dc4ec537-7377-4dad-b41b-acf9a834246f.png) |
| ![image](https://user-images.githubusercontent.com/949669/197186750-cd295 …
=> Fix #13541 - Use better coloring for archived caches

main/src/cgeo/geocaching/ui/CacheListAdapter.java
fix #13579: catch outdated positions when accessing geocache list to prevent ioobe
=> fix #13579: catch outdated positions when accessing geocache list to prevent ioobe

main/src/cgeo/geocaching/unifiedmap/AbstractGeoitemLayer.java, main/src/cgeo/geocaching/unifiedmap/LayerHelper.java, main/src/cgeo/geocaching/unifiedmap/googlemaps/GoogleGeoitemLayer.java, main/src/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsPositionLayer.java, main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/ClearableVectorLayer.java, main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeGeoitemLayer.java, main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgePositionLayer.java, main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmView.java, main/src/cgeo/geocaching/unifiedmap/tileproviders/AbstractMapsforgeOfflineTileProvider.java, main/src/cgeo/geocaching/unifiedmap/tileproviders/AbstractMapsforgeOnlineTileProvider.java, main/src/cgeo/geocaching/unifiedmap/tileproviders/MapsforgeMultiOfflineTileProvider.java
- OSM: put all tracks + individual route on a single layer; same for history line, to have a constant number of layers
- GM/OSM: fix z-index order for elements / layers
- use identical z-indexes for GM and OSM
- GM/OSM: allow waypoints as cache markers
=> UnifiedMap: layer handling fixes + extensions

main/src/cgeo/geocaching/utils/BackupUtils.java
remove local checkstyle error report in BackupUtils
This removes a checkstyle error which I always get when running it locally. For whatever reason it does not seem to occur on server side:
=> remove local checkstyle error report in BackupUtils

main/src/cgeo/geocaching/connector/gc/GCConstants.java, main/src/cgeo/geocaching/connector/gc/GCParser.java, tests/src-android/cgeo/geocaching/CgeoApplicationTest.java
- adapt tb location parsing to recent website changes (as agreed upon with HQ)
- re-enable tb location tests
- tb 12345 (a tb currently in the hands of the owner)
- tb 12347 (a tb in the hands of a user other than owner)
- tb 12351 (a tb marked missing)
- tb TB6P14F (a tb currently in a cache)
- and one of my own tb which is currently in my own hand (so similar to first case, but owner being the user currently logged in)
=> language-independent 'tb spotted' parsing (rel. to #13552)

main/src/cgeo/geocaching/unifiedmap/tileproviders/MapsforgeMultiOfflineTileProvider.java
Restores "Combined OSM map" capability
Displaying Hessen and NRW as separate maps, using "combined" feature:
=> UnifiedMap: Restore combined OSM feature (fix #13594)

main/src/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsPositionLayer.java, main/src/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsView.java
Remove objects from positionLayer for GM in `onPause` (similar to what's done already for VTM)
=>  UnifiedMap (GM): Clear layer in onPause (fix #13591) 

main/res/layout/about_version_page.xml, main/res/layout/cache_filter_generic_string.xml, main/res/layout/checkbox_item.xml, main/res/layout/continuousrangeslider_view.xml, main/res/layout/editwaypoint_activity.xml, main/res/layout/itemrangeslider_view.xml, main/res/layout/map_settings_button.xml, main/res/layout/search_activity.xml, main/res/layout/waypoint_item.xml, main/res/values/strings.xml
Before releasing a new version, Play Store does a prelaunch flight on several (virtual) devices, analyzing the resulting user experience. For c:geo there are quite a few results regarding accessibility (eg: missing labels) and other categories (eg: overlapping items, depending on translation). This PR intends to fix a couple of them.
=> fix several errors mentioned by prelaunch flight

main/res/values/preference_keys.xml, main/res/xml/preferences_services_gcvote_com.xml, main/src/cgeo/geocaching/settings/Settings.java
- disable GCVote for all new users by default
- disable GCVote for all existing users (by renaming the preference key), users can manually re-enable it
=> Disable GCVote for all users (+ per default) (rel. to #13599)

.idea/checkstyle-idea.xml, main/build.gradle
fixes #13597
The checkstyle version number for gradle was not changed according to the AS version. With checkstyle 9.2.1 https://checkstyle.sourceforge.io/releasenotes.html#Release_9.2.1 there was a bugfix for "ParameterAssignment does not detect problem for Lambda parameters".
Also update to the current 10.3.x version aligned to codacy.
=> Update checkstyle version

main/res/layout/variable_list_item_minimalistic.xml
Remove the hint for variable name in calculated waypoint view, which (due to its length) lead to additional line spacing.
=> Fix calculated vars line spacing (fix #13616)

cgeo-contacts/build.gradle, main/build.gradle, mapswithme-api/build.gradle
In this way we can update some google library which need this.
This will be done later on the dedicated PR
- androidx.annotation
- androidx.appcompat
- play-services-location
- play-services-maps
Unclear: com.google.android.material.
I got some strange errors. This needs a separate check.
Not able to update: androidx.core.
This needs compileSdkVersion 33.
=> use compileSdkVersion 32

main/src/cgeo/geocaching/VariablesViewPageFragment.java
fix #13618: store vars before cache if cache was not offline before
=> fix #13618: store vars before cache if cache was not offline before

main/res/layout/image_gallery_category.xml, main/res/layout/image_gallery_image.xml, main/res/layout/imagegallery_view.xml, main/src/cgeo/geocaching/CacheDetailActivity.java, main/src/cgeo/geocaching/ui/ImageGalleryView.java
fix #13586: ImageGallery: fix flickering and self-scrolling
The key fix is the replacement of `scrollToPosition` with `scrollToPositionWithOffset`. I am not exactly sure why the `WithOffset `doesn't have the strange side effects of the simple `scrollToPosition`, but I am glad it works...
The other changes are fine-tuning and cleaning up some mess I found on the way
=> fix #13586: ImageGallery: fix flickering and self-scrolling

main/src/cgeo/geocaching/CgeoApplication.java
Remove Android 3.0 Honeycomb reflection to show the three-dot-menu even if the device has a hardware menu button. This feature was introduced in 786eccacbb285696d504d08ba02c61400ce063a2 and had only worked on Android 3.0 - 4.3
=> Remove forced overflow menu hack (fix #13641)

main/src/cgeo/geocaching/ui/ImageGalleryView.java
rel to #13586: minor image gallery fix: scroll image gallery such that target image ends up roughly in middle
=> rel to #13586: minor image gallery fix: scroll image gallery such that target image ends up roughly in middle

main/src/cgeo/geocaching/models/Geocache.java, main/src/cgeo/geocaching/utils/formulas/VariableList.java
fix #13652: prevent re-inserting empty vars into variable list on scanning pcn
=> fix #13652: prevent re-inserting empty vars into variable list on scanning pcn

main/res/values/strings_not_translatable.xml
FZK themes downloader used a hard-coded "2012" folder name. Meanwhile we have a generic "latest" available, so let's use that.
=> switch FZK themes download URL to generic 'latest'

main/AndroidManifest.xml, main/build.gradle, main/res/values/themes.xml, main/src/cgeo/geocaching/SplashActivity.java
Instead of directly calling our `SplashActivity` with home-grewn theme, use AndroidX SplashScreen compatibility lib with according theme
=> use AndroidX SplashScreen compat lib (fix #13640)

main/src/cgeo/geocaching/ui/ImageGalleryView.java
fix #13682: prevent npe on imagegallery camery select when intent is null
=> fix #13682: prevent npe on imagegallery camery select when intent is null

main/res/values/strings.xml, main/src/cgeo/geocaching/utils/formulas/FormulaFunction.java, main/src/cgeo/geocaching/utils/formulas/FormulaUtils.java
fix #13659: add trunc function to formula
This PR adds the "trunc" function to c:geo, which truncs a comma-separated value (synonym: floor). It can resolve the issue in the discussion #13659 in yet another way.
=> fix #13659: add trunc function to formula

main/src/cgeo/geocaching/utils/MapMarkerUtils.java
fixes a logic error resulting in wrong marker values being displayed
fixes #13684
=> fix math in DT marker calculation

main/src/cgeo/geocaching/ui/ContinuousRangeSlider.java
fix #13715: ensure that min max slider values are within range and in right order
=> fix #13715: ensure that min max slider values are within range and in right order

.github/dependabot.yml, main/build.gradle
The crashes described in #13730/#13731 point to java.nio not supported. Dependency on this got introduced by an update of apache.commons.compress - which this PR therefore reverts.
=> Revert "Bump commons-compress from 1.20 to 1.22"

main/src/cgeo/geocaching/storage/extension/LastTrackableAction.java
Do not set newly acquired tb to "visit" automatically, if "auto visit" is not enabled.
=> Do not set new TB to visit mode automatically (fix #13720)

main/res/xml/preferences_services_geocaching_com.xml, main/src/cgeo/geocaching/settings/fragments/PreferenceServiceGeocachingComFragment.java
gc.com preference was still using a nested `PreferenceScreen` which is not supported by AndroidX preferences. Switching this into a `PreferenceCategory` resolved the problem.
The new category will be displayed for basic members only, and only if gc.com service is activated.
=> reenable gc.com basic member settings (fix #13724)

main/build.gradle, main/src/cgeo/geocaching/downloader/DownloaderUtils.java, main/src/cgeo/geocaching/downloader/ReceiveDownload.java, main/src/cgeo/geocaching/downloader/ReceiveDownloadService.java, main/src/cgeo/geocaching/downloader/ReceiveDownloadWorker.java
Using a ForegroundService gets more and more restricted with newer Android versions. Starting with Android 12, an app running in the background is no longer allowed to start a `ForegroundService` which blocks receiving downloads when c:geo was put into background meanwhile.
This PR mitigates this by using a `Worker` instead of a `ForegroundService` (as recommended by Google).
Optional things (that could be implemented as separate PR) are:
- Do we need to support import tasks running longer than ten minutes? Then we need to adapt to something like this: https://developer.android.com/topic/libraries/architecture/workmanager/advanced/long-running
- Do we want to use a `ForegroundService` (which might be a bit more responsive) when available (= app is in foreground state)? Then we need to be …
=> Use Worker instead of ForegroundService for receiving downloads

main/src/cgeo/geocaching/connector/gc/GCWebAPI.java
Correctly detect archived caches in search results. 
Though, I'm still wondering why this didn't come up before...?
=> Correctly detect archived caches in search results (fix #13619)

main/res/values/attrs.xml, main/res/xml/preferences_map.xml, main/res/xml/preferences_offlinedata.xml, main/src/cgeo/geocaching/settings/SeekbarPreference.java
Add pseudo logScaling to our custom SeekbarPreference implementation and use it for sliders with large ranges
Add stepSize to our custom SeekbarPreference implementation and use it where exact values doesn't make much sense
e.g. suggested in https://github.com/cgeo/cgeo/issues/11191#issuecomment-882013224
=> Add pseudo logScaling and stepSize to SeekbarPreference implementation 

main/src/cgeo/geocaching/filters/core/NumberRangeFilter.java, main/src/cgeo/geocaching/filters/core/NumberRangeGeocacheFilter.java, main/src/cgeo/geocaching/filters/core/UserDisplayableStringUtils.java, main/src/cgeo/geocaching/filters/gui/DistanceFilterViewHolder.java, main/src/cgeo/geocaching/filters/gui/FavoritesFilterViewHolder.java, main/src/cgeo/geocaching/filters/gui/LogsCountFilterViewHolder.java, tests/src-android/cgeo/geocaching/filters/UserDisplayableStringTest.java
adapt filter display string: 
* use "less/greater than or equal to" instead of "less/greater than"
* use "equal" if range is limited to min or max value
"Favorites: < 2.0" => "Favorites: ≤ 2.0"
"Favorites: < 0.0" => "Favorites: ≤ 0.0" (not really correct, but otherwise the logic in the filter has to be changed)
rel #13603
=> rel #13603: correct filter display string for minimum / maximum values

main/build.gradle, main/res/layout/route_sort_item.xml, main/res/values/strings_not_translatable.xml, main/src/cgeo/geocaching/maps/routing/RouteSortActivity.java, main/src/cgeo/geocaching/storage/DataStore.java
- This change replaces the legacy DragSortListView library with RecyclerView using build-in AndroidX drag sort implementation (fix #9884)
- don't discard current sorting when turning screen
=> migrate RouteSortActivity to Recyclerview

main/src/cgeo/geocaching/storage/DataStore.java
fix #13434: DataStore.updateCacheCount: pass exceptions correctly to emitter
This is a best-try to handle the observed problem. I assume that the exception is simply not passed the right way towards the subscriber (where it is handled in a good way, by logging it), this PR tries to fix that.
I would appreciate a review from someone with more knowledge about RxJava than I have. 
I also assume that the error happens in situations where the database is no longer available, which can happen either at app closing or during backup. Any support tickets which might be linked to this?
=> fix #13434: DataStore.updateCacheCount: pass exceptions correctly to emitter

main/res/values/preference_keys.xml, main/res/values/strings.xml, main/res/xml/preferences_map.xml, main/src/cgeo/geocaching/settings/fragments/PreferenceMapFragment.java
Group the two settings related to `UnifiedMap` into a separate category to avoid misunderstandings as described in the related issue:
This category will only be visible when hidden pref key `showUnifiedMap` is set to true.
=> Group UnifiedMap prefs in separate category (rel. to #13750)

main/src/cgeo/geocaching/utils/formulas/DegreeFormula.java, tests/src/cgeo/geocaching/utils/formulas/DegreeFormulaTest.java
fix #13763: prevent numberformatex on parsing degree formulas with multiple dots
=> fix #13763: prevent numberformatex on parsing degree formulas with multiple dots

main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgePositionLayer.java
Prevents crash of UnifiedMap on adding a waypoint to an empty route.
VTM `LineDrawable` crashes on adding if it consists of only a single point
=> UnifiedMap: Prevent crash on adding wpt to route

main/AndroidManifest.xml, main/build.gradle, main/src/main/java/cgeo/geocaching/SplashActivity.java, main/src/main/res/values/themes.xml
This reverts commit 0c688c70f392f66201b6d755f60b7fa8a3a5ed7c.
Revert splash screen details to the technical implementation before PR #13650, as that PR did not resolve the original lint issue, led to new display problems (and the "old" behavior seems to work pretty well even on recent Android versions).
:heart: git: creating this PR was as simple as doing a `git revert xxx`, despite the changed project structure...
=> Revert "use AndroidX SplashScreen compat lib (fix #13640)"

main/src/main/java/cgeo/geocaching/CacheListActivity.java
Presets the "new list" name box with name of the file that triggered the GPX import
=> Preset list name with GPX filename on import (fix #13782)

main/build.gradle
Declare vtm natives as runtimeonly, trying to solve android studio issues
I started to experience issues with my local Android Studio similar to what @moving-bits had describes some weeks ago (one by one classes started to "disappear" from the knowledge of Android Studio, were marked red etc).
I had the impression that this is caused by VTM native libraries being part of compile path. Removing them from this path resolved the issue for me. This is what this PR is doing (->moving it to "runtimeOnly"). VTM seems to work with this change, at least in the emulator.
@moving-bits does this also solve your problems? If yes, maybe we should merge it?
=> declare vtm natives as runtimeonly to solve android studio issues

main/AndroidManifest.xml
Add READ_EXTERNAL_STORAGE permission to manifest
#13826
Tested and working in emulator (permission is requested as soon as wallpaper feature is activated)
=> Fix#13826 - Add permission to read external storage

main/src/main/java/cgeo/geocaching/storage/ContentStorageActivityHelper.java
don't show file copy dialog on clean install (fix #11846)
=> don't show file copy dialog on clean install

main/src/main/java/cgeo/geocaching/TrackableActivity.java
fix #13805: remove old image gallery for trackables
=> fix #13805: remove old image gallery for trackables

main/src/main/java/cgeo/geocaching/CacheListActivity.java
Prevents NPE on GPX file import when trying to infer a default for list name
=> Prevent NPE on setting list name memento (fix #13841)

main/src/androidTest/java/cgeo/geocaching/downloader/DownloaderTest.java
- Configure list size test (currently 55)
- Configure the list entries test (currently 50)
- Configure the map size test according to new file size (currently 297MB)
fixes #13853
=> adjust Mapsforge downloader tests

main/src/main/java/cgeo/geocaching/utils/formulas/Formula.java, main/src/test/java/cgeo/geocaching/utils/formulas/FormulaTest.java
fix #13843: recognize whitespace before closing parenthesis
=> fix #13843: recognize whitespace before closing parenthesis

main/src/androidTest/java/cgeo/geocaching/apps/cache/WhereYouGoAppTest.java, main/src/main/java/cgeo/geocaching/CacheDetailActivity.java, main/src/main/java/cgeo/geocaching/apps/cache/WhereYouGoApp.java
currently the WIG-recognition fails if both download and details page are linked. Fix that by recognizing only the ID
fixes #13822
=> recognize WIG-links if both details.aspx and download.aspx are linked

main/src/main/java/cgeo/geocaching/files/GPXTrackOrRouteImporter.java
Import GPX track files without proper namespace identifier as version 1.0 track files (fallback solution).
=> Import GPX track files with missing namespace id (fix #13852)

.github/dependabot.yml, cgeo-contacts/build.gradle, main/build.gradle
... because of transitive dependency to other `commons-xxx` packages.
=> Ignore updates to the apache 'commons-text' package

main/src/main/java/cgeo/geocaching/maps/CGeoMap.java, main/src/main/java/cgeo/geocaching/maps/MapUtils.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
On creating a new route by using long-tap, "Append to route", no routing quick settings icon was displayed on map. This PR fixes this.
=> Fix missing routing symbol after 'append to route' (fix #13850)

main/src/main/java/cgeo/geocaching/models/IndividualRoute.java
Until now only the last segment got recalculated on adding a segment. This PR adapts this behavior if new segment got prepended.
=> Add route calculation for prepending points (fix #13849)

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java, main/src/main/res/values/strings.xml
When a Mystery (unknown) cache includes a link to an Adventure Lab cache assume that it's a Bonus for that Adventure Lab and allow starting the Adventure Lab from Details tab - just like for ALCs opened in c:geo
fixes #13832
=> enable Lab-button also for bonus caches with link to lab

main/src/androidTest/java/cgeo/geocaching/downloader/DownloaderTest.java, main/src/main/java/cgeo/geocaching/downloader/AbstractMapDownloader.java, main/src/main/java/cgeo/geocaching/downloader/MapDownloaderOpenAndroMaps.java, main/src/main/java/cgeo/geocaching/downloader/MapDownloaderOpenAndroMapsThemes.java, main/src/main/res/values/strings_not_translatable.xml
Add support for "Voluntary MF5" theme for OAM maps:
- offer theme when downloading maps from OAM
- check for theme updates
- don't download Elevate theme automatically, if Voluntary is already present
- adapt tests for OAM themes
=> Add support for 'Voluntary MF5' OAM theme (fix #13866)

tests/src-android/cgeo/geocaching/downloader/DownloaderTest.java
Portugal map size has exceeded the limits set by our test for Mapsforge data, so adapt the test's limits
=> Adapt Mapsforge test to new Portugal map size (fix #13889)

main/src/main/java/cgeo/geocaching/MainActivity.java, main/src/main/res/values/strings.xml
Displays either "(Basic)" or "(Premium)" after connector status info on home screen (for GCConnector only):
Not sure if we should make those strings translatable or not. How does GC handle this?
=> Display GC member state on home screen (rel. to #13796)

main/src/androidTest/java/cgeo/geocaching/files/GPXParserTest.java, main/src/androidTest/res/raw/no_connector_dupliactes.gpx, main/src/main/java/cgeo/geocaching/files/GPXParser.java
While reading / importing caches from a gpx-file, use the whole name as geocode for unknown_connector (unknown-connector supports any text as geocode)
fix #13794
=> GPX-Parser: read name as geocode for unknown_connector (fix #13794)

main/src/main/java/cgeo/geocaching/models/Waypoint.java, main/src/test/java/cgeo/geocaching/models/WaypointTest.java
For server-side waypoints, always the original description / note will be taken, even if it's an empty one.
An empty description of a waypoint will be only overwritten for user-defined waypoints with an already existing description.
fix #11762
=> synchronize empty waypoint description (fix #11762 )

main/proguard-project.txt
as found in the nightlies:
~~~
00:33:35  > Task :main:minifyBasicNightlyWithR8
00:34:29  WARNING:Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /srv/jenkins/jobs/cgeo nightly/workspace/main/build/outputs/mapping/basicNightly/missing_rules.txt. 00:34:29
00:34:29  WARNING:R8: Missing class org.slf4j.impl.StaticLoggerBinder (referenced from: void org.slf4j.LoggerFactory.bind() and 3 other contexts) 
~~~
This is not shown with `buildType.name == 'debug'`.
=> add proguard rule for slf4j

main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgePositionLayer.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmView.java
Fix crash due to layer groups being added on resume but never removed (no method for this, so make sure they are only added once).
=> UnifiedMap VTM: fix crash on resume

main/src/main/java/cgeo/geocaching/ui/VariableListView.java
fix #13908: variable list: show empty text instead of null for null formulas
=> fix #13908: variable list: show empty text instead of null for null formulas

main/src/main/java/cgeo/geocaching/connector/gc/GCMap.java
fix #13891: on gc.com owner search: dont put status to search if archived caches should be returned
=> fix #13891: on gc.com owner search: dont put status to search if archived caches should be returned

main/src/main/java/cgeo/geocaching/maps/Tracks.java, main/src/main/java/cgeo/geocaching/storage/extension/Trackfiles.java
Correctly preserve `isHidden` state for tracks on changing a track's `displayName`
=> Preserve visibility state on trackfile name change

.github/ISSUE_TEMPLATE/bug_report.yml
Set the current c:geo version number as templete.
Maybe this should be integrated as a step in the release workflow.
=> Update bug_report.yml with current version number

main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeThemeHelper.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeThemeSettingsFragment.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/VtmThemes.java, main/src/main/res/values/preference_keys.xml, main/src/main/res/values/strings.xml
Supports selecting one of the built-in VTM theme variants:
|OSMARENDER|DEFAULT|NEWTRON|
|---|---|---|
|![image](https://user-images.githubusercontent.com/3754370/215326692-97e575d5-83a0-43d5-8ad5-bbf4c3930953.png)|![image](https://user-images.githubusercontent.com/3754370/215326716-09219752-8453-4ab1-87ae-7e857980c9b9.png)|![image](https://user-images.githubusercontent.com/3754370/215326730-d78d21a7-b458-4657-8f16-9c336d371f69.png)|
Although VTM uses a new DEFAULT theme, c:geo users are more accustomed to the OSMARENDER variant, so this is what c:geo will keep using as predefined theme variant.
Switching a variant is done using theme options.
=> UnifiedMap VTM: support built-in theme variants

main/src/main/java/cgeo/geocaching/CompassActivity.java
fix #13921: catch npe on uninitialized compassactivity
=> fix #13921: catch npe on uninitialized compassactivity

main/src/main/java/cgeo/geocaching/storage/ContentStorageActivityHelper.java
fix #13935: contentstoragehelper, use correct copychoice parameter instead of nullable runningintentdata
=> fix #13935: contentstoragehelper, use correct copychoice parameter instead of nullable runningintentdata

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
fix #13933: avoid npe on not yet initialized adjustvarsync button in cachedetails
=> fix #13933: avoid npe on not yet initialized adjustvarsync button in cachedetails

main/src/main/res/layout-land/compass_activity.xml
fix #13921 (the real fix): correct landscape compass layout to use new location-status
This is the real fix. Cause of the problem was that in compass landscape layout the new field location status was missing.
=> fix #13921 (the real fix): correct landscape compass layout to use new location-status

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
fix #13936: select text only if selection bounds are met to prevent indexoutofboundsexception
=> fix #13936: select text only if selection bounds are met to prevent indexoutofboundsexception

main/src/main/java/cgeo/geocaching/storage/DocumentContentAccessor.java, main/src/main/java/cgeo/geocaching/utils/BackupUtils.java
fix #13938: contentstorage: correctly catch illegalargumentexception in ensureFolder
=> fix #13938: contentstorage: correctly catch illegalargumentexception in ensureFolder

main/src/main/java/cgeo/geocaching/maps/RouteTrackUtils.java, main/src/main/res/layout/routes_tracks_item.xml, main/src/main/res/values/strings.xml
Adds a "refresh" button for individual route to route/track menu which triggers a forced reload of the route's caches in the background.
=> Refresh caches in route (fix #13382)

main/src/main/java/cgeo/geocaching/about/SystemInformationViewModel.java
Catches RxJava error before converting it to LiveData, preventing a crash.
Instead, the error is logged and the result is set to `null` (pretty much same as not loaded in this case).
Prevents a crash documented in #13553.
=> Catch RxJava error before converting to LiveData

main/src/main/java/cgeo/geocaching/apps/navi/NavigationAppFactory.java, main/src/main/res/layout/select_dialog_item.xml
Fixes font size and line spacing of cache/waypoint popup's navigation menu
|Cache details|Cache popup before|Cache popup after|
|---|---|---|
|![image](https://user-images.githubusercontent.com/3754370/216838066-eb51f4bf-9863-41ac-81df-3275b8b4957d.png)|![image](https://user-images.githubusercontent.com/3754370/216838068-cb5b9d85-bd86-4631-a063-946912ad509d.png)|![image](https://user-images.githubusercontent.com/3754370/216838075-345f0a88-1494-42d3-bc11-e14f03f7ae1b.png)|
=> Fix cache popup navigation menu font size

main/AndroidManifest.xml, main/src/main/java/cgeo/geocaching/connector/gc/ImportBookmarkLinks.java
Tapping on a link to a public/shared gc bookmark lists will now trigger GPX import for this list.
(On Android 12+ app settings might need to be adjusted to open the link in c:geo, see https://www.cgeo.org/faq#android12)
=> Add option to import public bookmark lists (fix #13566)

main/src/main/java/cgeo/geocaching/files/GPXParser.java
Fixes skipping all but one user-created waypoints on GPX import (for GPX files having been created as GPX export by c:geo).
=> Fix skipping some user-created waypoints on GPX import (fix #13972)

main/src/androidTest/java/cgeo/geocaching/utils/InstrumentedFormulaUtilsTest.java, main/src/main/java/cgeo/geocaching/utils/formulas/FormulaUtils.java
fix #13994: make coordinate parsing regex fit for android regex implementation
=> fix #13994: make coordinate parsing regex fit for android regex implementation

main/AndroidManifest.xml, main/src/main/java/cgeo/geocaching/InstallWizardActivity.java
Restricts requesting WRITE_EXTERNAL_STORAGE to SDK 28 or less
tested successfully against API 29 in emulator
see discussion in #13997
=> restrict WRITE_EXTERNAL_STORAGE request to maxSDK 28

main/AndroidManifest.xml, main/src/main/res/layout/logs_item.xml, main/src/main/res/values-land/dimens.xml, main/src/main/res/values/dimens.xml
Enlarge column width for log item description column in landscape mode as a simple mitigation for #14014
Not sure about possible side-effect of having to remove "orientation" from `AndroidManifest` for `CacheDetailActivity` to make the view recognize orientation change to recalculate the layout, so we should keep an eye on it in the nightlies.
=> Widen log description column in landscape mode (rel. to #14014)

main/src/main/java/cgeo/geocaching/ui/ImageActivityHelper.java, main/src/main/res/values/strings.xml
Explain reason when acquiring log image fails due to format error
=> Make image format error message clearer (rel. to #14038)

main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/GoogleTerrainSource.java, main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/TileProviderFactory.java, main/src/main/res/values/strings.xml
Adds Google Terrain maps as tileprovider for UnifiedMap
=> Add Google Terrain tileprovider to UnifiedMap (rel. to #14043)

main/AndroidManifest.xml, main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/RenderThemeSettings.java, main/src/main/java/cgeo/geocaching/settings/SettingsActivity.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeThemeSettings.java, main/src/main/res/values/themes.xml
Since `SettingsActivity` is derived from `AppCompatActivity` meanwhile, specific theming instructions for settings are no longer needed, so let's remove them.
=> Remove outdated specific theming for settings

main/src/main/java/cgeo/geocaching/activity/AbstractBottomNavigationActivity.java, main/src/main/java/cgeo/geocaching/maps/CGeoMap.java, main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapView.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsView.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmView.java, main/src/main/java/cgeo/geocaching/utils/FilterUtils.java, main/src/main/res/layout/filter_sort_bar.xml
To gain more vertical space on the map (esp. in landscape mode) you can hide the action bar on demand by short-tapping on a free space of the map. Unhiding is done the same way.
For screenshots see https://github.com/cgeo/cgeo/issues/13315#issuecomment-1450862440.
=> Hide map's action bar on demand

main/src/main/java/cgeo/geocaching/EditWaypointActivity.java, main/src/main/java/cgeo/geocaching/maps/CGeoMap.java, main/src/main/java/cgeo/geocaching/models/Geocache.java, main/src/main/java/cgeo/geocaching/models/Waypoint.java, main/src/main/java/cgeo/geocaching/storage/DataStore.java
Make `EditWaypointActivity` assign new waypoints a (generated) prefix.
- Editing a waypoint will already assign a prefix if none exists and waypoint is detected as new.
- This will fail, though, for adding new waypoints, as they are currently not being recognized as new.
- This is due to the following code in `onCreate` (`waypointId = extras.getInt(Intents.EXTRA_WAYPOINT_ID);`), which assigns "0", if the value for waypoint id is missing in the intent. "0" is regarded a valid waypoint id, though, therefore this (newly to be created) waypoint will not be regarded as new, therefore the prefix check skipped.
Solution: Add the "new waypoint" marker (= -1) to calling intent on adding a new waypoint.
=> Assign prefix on adding waypoints (rel. to #14053)

main/src/main/java/cgeo/geocaching/activity/OAuthAuthorizationActivity.java, main/src/main/java/cgeo/geocaching/activity/TokenAuthorizationActivity.java, main/src/main/java/cgeo/geocaching/settings/AbstractCredentialsAuthorizationActivity.java
Currently our authorization screens for geocaching service do not support the up icon in action bar, you have tap the back key.
This PR fixes it for all services based on token, OAuth or credentials authorization.
=> Enable up navigation in service authorization screens

main/src/main/java/cgeo/geocaching/CacheListActivity.java, main/src/main/java/cgeo/geocaching/maps/CGeoMap.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/java/cgeo/geocaching/utils/FilterUtils.java, main/src/main/res/layout/filter_sort_bar.xml
In contrast to map activities `CacheListActivity` should not use the extra spacer above the filter bar.
=> Remove actionBarSpacer in CacheListActivity (fix #14065)

main/src/main/res/layout-land/map_settings_button.xml
To gain more visible vertical map space, move quick settings buttons to the left in landscape mode.
(See #13315 for discussion. I decided to put them to the left instead of to the right to not interfere with zoom controls and (maximized) distance info.)
=> Move quick settings buttons to the left in landscape (rel. to #13315)

main/src/androidTest/java/cgeo/geocaching/connector/ConnectorFactoryTest.java, main/src/androidTest/java/cgeo/geocaching/connector/trackable/GeokretyConnectorTest.java, main/src/androidTest/java/cgeo/geocaching/models/TrackableTest.java, main/src/main/java/cgeo/geocaching/connector/ConnectorFactory.java
Workaround for TB namespace conflicts for TB starting with "GK":
Leave out GeoKrety TB connector of list of TB connectors, if GeoKrety connector is not activated. In this case no GeoKrety TB will be searched for online.
Be aware, though, that Geokrety TB already stored locally in the database will still be retrieved by the TB search.
=> TB namespace conflict workaround for disabled GK connector (rel. to #13097)

main/src/androidTest/java/cgeo/geocaching/CgeoApplicationTest.java
Tests are currently failing on CI due to paged search result no longer contains the cache being tested against on the first result page. Therefore select a cache further up in the result set.
=> Fix failing searchByOwner test

main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapView.java
#14082 and #14079 had logically conflicting changes, leading to both PR worked in itself flawlessly, but not in combination.
This PR resolves this.
=> Resolve conflicting changes to GMv2

main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapObjectsQueue.java
rel to #13993: GoogleMaps remove objects from internal storage to correctly sync operations
A less invasive version to mitigate #13993. 
Thanks to @moving-bits s comment on PR #14070, which got me thinking again! On quick succession of removal and reading same objects (equal in content but different object) the first one was "removed" several times, leading to the new ones NOT being deleted from the requestedToAdd queue. This PR should fix that.
=> rel to #13993: GoogleMaps remove objects from internal storage to correctly sync operations

main/src/main/java/cgeo/geocaching/ui/CheckableItemSelectActivity.java
Pressing back key will now not only store the results but also return to previous settings screen, same as arrow in the header does.
=> Support back key to finish CheckableItemSelectActivity (fix #14086)

main/build.gradle, main/src/main/java/cgeo/geocaching/CgeoApplication.java, main/src/main/java/cgeo/geocaching/utils/Log.java, main/src/main/java/cgeo/geocaching/utils/SystemInformation.java, main/src/main/java/cgeo/geocaching/utils/TransactionSizeLogger.java
rel to #14109: add transaction size logging in debug mode, restructure logging
This PR adds transaction size logging to c:geo using the library TooLargeTool, see https://github.com/guardian/toolargetool. This is meant for analyzation of #14109. Transaction Size Logging is activated in debug mode 
This PR also adds a "log settings" information into system information
**This PR also removes the logging behaviour of ending c:geo in debug mode whenever an error is logged!** I never understood this "feature", because it effectively restraints people from running c:geo in debug mode. It is exactly those error situations that we are usually interested in, and it is of no use if c:geo ends when they happen...
=> rel to #14109: add transaction size logging in debug mode, restructure logging

main/src/main/java/cgeo/geocaching/utils/SettingsUtils.java
While working on sortable quicklaunchitems I stumbled upon unknown preference types (`Set<String>` in this case) neither being stored nor documented in settings backup. This is no longer a problem for quicklaunch items, as those are stored as string meanwhile, but let's at least document if we ever find an unknown type on creating a settings backup.
=> Document unknown settings types

main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceAppearanceFragment.java, main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceOfflinedataFragment.java, main/src/main/res/values/preference_keys.xml, main/src/main/res/values/strings.xml, main/src/main/res/xml/preferences_appearence.xml, main/src/main/res/xml/preferences_offlinedata.xml
Move the following settings from "Offline data" to "Appearance" settings into a new category "Cache Lists":
- List load limit
- Config info item line 1
- Config info item line 2
=> Move cache list config to appearance screens (rel. to #14073)

main/src/main/java/cgeo/geocaching/settings/ColorpickerPreference.java
Removes the divider lines above ColorpickerPreferences (but allows them below to cater category separator lines)
=> Remove divider lines above ColorpickerPreference (fix #14126)

main/src/main/res/color/settings_primary_selector_light.xml, main/src/main/res/color/settings_primary_selector_night.xml, main/src/main/res/color/settings_secondary_selector_light.xml, main/src/main/res/color/settings_secondary_selector_night.xml, main/src/main/res/values/colors.xml
Since moving settings activities to `AppCompatActivity` some special treatment is no longer needed, including a couple of resource files and color values, which this PR removes.
=> Remove settings' resources no longer needed

main/src/main/java/cgeo/geocaching/utils/MapMarkerUtils.java
Make d/t marker resources identifiable by id rather than accessing them by name only. Also fixes a couple of "unused res" lint messages
=> Use d/t marker resources by id when possible

main/src/main/java/cgeo/geocaching/brouter/expressions/BExpressionContext.java
BRouter `BExpression` lacked defining a locale in most string comparisons
=> Set locale in BRouter parsing

main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapView.java
Since our GMv2 implementation uses a self-written `onSingleTapUp` handler, we need to make it aware of map controls to prevent firing in those cases. This PR excludes
- zoom in / zoom out-buttons
- compass rose
from handling in `onSingleTapUp`
=> Exclude GM map controls from onSingleTapUp (fix #7569) (fix #14136)

main/src/main/java/cgeo/geocaching/utils/SystemInformation.java
Fix some formatting issues in system information:
- make geocaching connectors a sub list for proper indentation
- format permissions as list
- move render theme path to other map settings (before SAF info)
=> fix formatting of system information

main/src/main/java/cgeo/geocaching/connector/gc/BookmarkUtils.java, main/src/main/java/cgeo/geocaching/connector/gc/GCConstants.java, main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java, main/src/main/java/cgeo/geocaching/network/Network.java
the existing calls to https://www.geocaching.com/api/proxy/web/v1/lists now require a "X-Verification-Token" header, the value of which can be obtained from cache pages: input[name="__RequestVerificationToken"]
There's also a new API for managing lists - https://www.geocaching.com/plan/api/lists/ - but this PR doesn't switch to that as it's not required (yet?)
Targeted against release as this should be in the next bugfix
=> fix adding caches to GC lists / creating GC lists

main/src/main/java/cgeo/geocaching/network/Send2CgeoDownloader.java
forces to redownload the cache, if send2cgeo imports a cache, that is already in the database
fix #14110
=> Send2cgeo: force to  redownload the cache on importing via send2cgeo (fix #14110)

main/src/main/java/cgeo/geocaching/enumerations/CacheListInfoItem.java, main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceAppearanceFragment.java, main/src/main/java/cgeo/geocaching/utils/Formatter.java, main/src/main/res/values/preference_keys.xml, main/src/main/res/values/strings.xml, main/src/main/res/xml/preferences_appearence.xml
- Supports "last logs smiley row" in configurable info items (can be in a separate row or "flowing" in text)
- Reduces configurable info items to one setting (instead of two)
- Supports "newline" items, so that user can determine number of lines on their own
=> Add last logs smiley row to configurable info items ( #14084)

main/src/main/java/cgeo/geocaching/CacheListActivity.java, main/src/main/java/cgeo/geocaching/connector/gc/AbstractListActivity.java
Bookmark lists are now downloaded as GPX instead of ZIP, breaking our list import. This is the fix for release
=> fix bookmark list import

main/src/main/java/cgeo/geocaching/connector/gc/ImportBookmarkLinks.java
Bookmark lists are now downloaded as GPX instead of ZIP, breaking our list import. This is the fix for newly introduced functionality on master, not yet in release. It's required in addition to #14168
=> fix import of public bookmark lists

main/src/main/java/cgeo/geocaching/maps/CGeoMap.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
Do not store calculated route in map activity bundle to avoid "transaction too large" errors on bundling/unbundling. Will lead to route recalculation on activity recreation.
=> Do not store route in bundle (rel. to #14109)

main/src/main/java/cgeo/geocaching/connector/oc/OkapiClient.java, main/src/main/java/cgeo/geocaching/models/Geocache.java, main/src/main/java/cgeo/geocaching/models/Waypoint.java
fixes deletion of user defined waypoints on update cache from OC with defined user-coordinates on website.
Waypoints are now getting merged instead of overwritten.
fix #14100
to discuss, if the coordinates from the user-coordinates on website should be overtaken in c:geo as modified cache-coordinates
=> merge waypoints on refresh from Okapi (fix #14100)

main/src/main/java/cgeo/geocaching/models/IndividualRoute.java
Update route on screen only after having fully reloaded it, to avoid race conditions as shown in related issue
=> Avoid race conditions on reordering route (fix #14135)

main/src/main/res/values/styles.xml
Hopefully fix #14162 by explicitly setting correct overflow button color
=> force correct overflow button color (fix #14162)

main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/PositionLayer.java
Catch NPE on drawing position marker, when marker is not available
(This is currently the most prominent crash on Play statistics for release 2023.03.25 (in terms of "user affected"))
=> Catch NPE on drawing position marker in NewMap

main/src/main/java/cgeo/geocaching/maps/MapOptions.java
This PR aims to mitigate the issue described in #12225, losing navigation geocode on mapsource change.
Should be thoroughly tested for any unwanted side-effects, therefore targeting this to `master` only.
=> Preserve target geocode on mapsource change (rel. to #12225)

main/src/main/java/cgeo/geocaching/CacheListActivity.java, main/src/main/java/cgeo/geocaching/activity/AbstractBottomNavigationActivity.java, main/src/main/java/cgeo/geocaching/maps/CGeoMap.java, main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapView.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsView.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmView.java, main/src/main/java/cgeo/geocaching/utils/FilterUtils.java, main/src/main/java/cgeo/geocaching/utils/HideActionBarUtils.java, main/src/main/res/layout-h390dp-land/activity_bottom_navigation.xml, main/src/main/res/layout-land/activity_bottom_navigation.xml
Implements the approach proposed in https://github.com/cgeo/cgeo/issues/14161#issuecomment-1508089543:
Do not move the map view beneath the action bar, when "hide on tap" is disabled.
Additionally extracts the map hiding methods into their on class (instead of being buried in `FilterUtils`) and uncouples it from `FilterUtils.initializeFilterBar()`.
=> Keep old mapsize when 'tap to hide actionbar' is disabled

main/src/main/java/cgeo/geocaching/utils/Formatter.java
replaces the (sometimes visible) dot used as separator in the "recent logs smiley group" by "zero-width" unicode char \\u200b
=> replace dot smiley separators by zero-width space (rel. to #14204)

main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/TapHandlerLayer.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GeoItemTestLayer.java, main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/ILayer.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/IndividualRouteLayer.java
For Unified Map: Extends `ILayer.onTap` to distinguish between taps and long taps and remove route items on long taps only.
=> UnifiedMap: Remove indiv. route items on long tap only (fix #14213)

main/src/main/java/cgeo/geocaching/utils/SettingsUtils.java
Catch `null` values while documenting unknown setting types when performing a settings' backup.
(Also lowers the message level to "warning" instead of "error".)
=> Catch null settings values on performing backup (fix #14218)

main/src/main/res/layout-land/compass_activity.xml
Align compass status view to parent's bottom in landscape mode to avoid overlapping texts
=> Fix compass status view alignment in landscape mode (fix #14203)

main/src/main/java/cgeo/geocaching/service/CacheDownloaderService.java, main/src/main/res/layout/dialog_background_download_config.xml, main/src/main/res/values/strings.xml
Add a "refresh caches, but keep their assigned lists" option to cache download options available in map and "show as list":
=> Add 'refresh and keep list' to cache download options (fix #14190)

main/src/main/java/cgeo/geocaching/CacheListActivity.java, main/src/main/java/cgeo/geocaching/storage/DataStore.java, main/src/main/res/menu/cache_list_options.xml, main/src/main/res/values/strings.xml
Adds "Append to individual route" to cache lists' "Manage caches" menu.
I've decided to not call route optimization automatically - it's a different task, and as you can see the optimization's results only on map anyway, let's keep that function to be called from there.
=> Provide 'Append to individual route' to cache list options

main/src/main/java/cgeo/geocaching/maps/CGeoMap.java, main/src/main/java/cgeo/geocaching/maps/MapUtils.java, main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapView.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/main/java/cgeo/geocaching/models/IndividualRoute.java, main/src/main/java/cgeo/geocaching/ui/dialog/SimplePopupMenu.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapViewModel.java, main/src/main/res/values/strings.xml
Adds a "long tap" context menu for caches/waypoints on map, providing (up to) the following items:
- append to route
- prepend to route
- remove from route
- remove from route end
- remove from route start
This allows to add a cache/waypoint multiple times to a route, specifically as both start and end point to create a round-trip.
Long tap on a cache/waypoint will now always trigger this context menu, no longer auto-toggle route item (as discussed in related issue among others.)
Implemented for `NewMap` only currently, to gather some feedback.
|Screenshot 1|Screenshot 2|
|---|---|
|![image](https://user-images.githubusercontent.com/3754370/233858783-c16f82cd-a738-443f-bcb3-afcbf6d1f050.png)|![image](https://user-images.githubusercontent.com/3754370/233858791-ef9d1910-67fe-4f6e-b7a4-77cf11 …
=> NewMap: Add long-tap context menu for caches/waypoints (rel. to #13176)

main/src/main/java/cgeo/geocaching/StatusFragment.java, main/src/main/java/cgeo/geocaching/utils/MapMarkerUtils.java
To make dynamic icon loading for our notifications more flexible we intentionally use resource reflection, thus we can safely ignore the lint messages triggered by this
=> Fix lint: intended use of DiscouragedApi for notification server

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/main/java/cgeo/geocaching/ui/TextParam.java, main/src/main/java/cgeo/geocaching/ui/ViewUtils.java
fix #14202: make calls to Linkify.addLinks safe and catch RuntimeExceptions
=> fix #14202: make calls to Linkify.addLinks safe and catch RuntimeExceptions

main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java, main/src/main/res/values/strings.xml
1. check length before posting log and show toast, if log is empty ("c:geo couldn\'t submit your log cause it is empty. Please be so kind and leave some nice words to the owner.")
2. show reason for failing posting log
3. check empty log on sending post request and set logResult accordingly
fix #13476
to discuss - if 2) and 3) is sufficient or if 1) is the better implementation
=> show message on sending empty log (fix #13476)

main/src/main/java/cgeo/geocaching/connector/AbstractConnector.java, main/src/main/java/cgeo/geocaching/connector/IConnector.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/caches/AbstractCachesOverlay.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/caches/WaypointsOverlay.java, main/src/main/java/cgeo/geocaching/models/Geocache.java, main/src/main/java/cgeo/geocaching/models/Waypoint.java
Assign waypoints a unique id (`geocode` + `getGpxId()`) to avoid waypoints having the same prefix being removed in NewMap's waypoints layer handling. See https://github.com/cgeo/cgeo/issues/14053#issuecomment-1530188394 for details.
Attempts to fix issue #13675 (and the rest of #14053 and #12999)
=> NewMap: Give waypoints unique id (rel. to #13675, #14053)

main/src/main/java/cgeo/geocaching/CompassActivity.java, main/src/main/res/layout-land/compass_activity.xml, main/src/main/res/layout/compass_activity.xml, main/src/main/res/layout/compass_hint_and_status.xml
Display hint in compass views in a text field instead of as a toast:
(Hint can be toggled using the hint button in action bar, default is hint off)
=> Display hint in compass in textfield (fix #14108)

main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapView.java
fix #14278: stay stable if map source is not google in google maps
=> fix #14278: stay stable if map source is not google in google maps

main/src/main/java/cgeo/geocaching/utils/SystemInformation.java
Fix indentation for persisted doc uri in sysinfo
=> Sysinfo: Fix indentation for persisted doc uri

main/src/androidTest/java/cgeo/geocaching/activity/AboutActivityTest.java, main/src/main/java/cgeo/geocaching/AboutActivity.java, main/src/main/res/layout/about_changes_page.xml, main/src/main/res/values/strings.xml, main/src/main/res/values/strings_not_translatable.xml
- Fix link to "full changelog" in about:changelog (was still pointing to old folder structure)
- Extract Uri to `strings_not_translatable.xml`
- give label string var a more meaningful name
=> Fix link to full changelog

main/src/main/java/cgeo/geocaching/CacheListActivity.java, main/src/main/java/cgeo/geocaching/Intents.java, main/src/main/java/cgeo/geocaching/connector/gc/BookmarkUtils.java, main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java, main/src/main/java/cgeo/geocaching/loaders/PocketGeocacheListLoader.java, main/src/main/java/cgeo/geocaching/models/GCList.java
For previewing PQs we're currently using https://www.geocaching.com/seek/nearest.aspx?pq= which is one of those old pages with lots of HTML, also limited to 20 results/page.
There's also a "preview on map" option, loading to https://www.geocaching.com/map/default.aspx?pq= which loads the actual data as geojson from https://tiles01.geocaching.com/map.pq?pq=..&st=..
This is a "nice" data format (json) and seems to deliver up to 1000 items.
Cache information that can be obtained this way:
- name
- geocode
- type
- archived
- disabled
- coordinates
- found
- userModifiedCoordinates
Missing info compared to old search page:
- d/t rating
- placed date
- size
- owner name
- favorite count
I think the advantage of getting more than 20 caches more than makes up the "loss" in information about …
=> load PQ preview from map instead of legacy search results (#14290)

main/src/main/java/cgeo/geocaching/settings/SeekbarPreference.java
Fix a couple of issues with `Seekbar` in certain combinations of the allowed parameters:
- `logScaling` and setting a minimum value did not work well in conjunction
- `stepSize` sometimes lead to max value being unreachable
- manually entering min value sometimes did not move slider to left-most position
- manually editing the value sometimes displayed weird current values
Hopefully all of those are fixed now, and `logScaling` and `stepSize` are integrated into the regular structure of `progressToValue()` and `valueToProgress()` methods.
=> Fix a couple of Seekbar issues (fix #14288)

main/src/main/res/layout/emojiselector_item.xml
Replace hard-coded "white" color in EmojiSelector with parametrized `colorText` to allow for color-adjustment of some style-aware emojis
=> Fix hard-coded color in EmojiSelector (fix #14311)

main/src/main/java/cgeo/geocaching/connector/al/ALApi.java, main/src/main/java/cgeo/geocaching/connector/gc/GCLogin.java
This is an attempt to finally get the "true found state" for Adventure Lab Caches. The `SearchV4` method, when called with the user's `publicGuid` is supposed to return that state.
My tests on the emulator showed that indeed the true found state is reported once the `publicGuid` is provided to the `SearchV4` API method.
Please note: When explicitly fetching a Lab Cache by its ID, we still use the method [/api/Adventures/{id}](https://labs-api.geocaching.com/swagger/ui/index#!/Adventures/Adventures_Get) which does **not** return the true found state, however once the lab is on the map, it got there as a result of using the SearchV4 API, which now provides that state and it seems that state is cached when subsequently loading the cache detailed view. Please also note that this method: …
=> #13481 AL found state

main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/PositionLayer.java
Mapsforge's AndroidBitmap can be non-null, but the referenced bitmap being destroyed already, still leading to an NPE as mentioned in the referenced issue.
This PR adds a check for `isDestroyed()`.
=> Avoid NPE in PositionLayer.draw (fix #14295)

main/src/main/java/cgeo/geocaching/maps/AbstractMap.java, main/src/main/java/cgeo/geocaching/maps/CGeoMap.java, main/src/main/java/cgeo/geocaching/maps/MapUtils.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/res/menu/map_longclick.xml
Adds "set as target" option to map's long tap menu:
=> Add 'set as target' to map's long tap popup (fix #13539)

main/src/main/res/values/strings.xml, main/src/main/res/values/strings_not_translatable.xml
Mark startscreen config items name references as non-translatable
=> Mark startscreen config items names as non-translatable (fix #14337)

main/src/main/java/cgeo/geocaching/connector/AbstractConnector.java, main/src/main/java/cgeo/geocaching/connector/IConnector.java, main/src/main/java/cgeo/geocaching/connector/al/ALConnector.java, main/src/main/java/cgeo/geocaching/connector/internal/InternalConnector.java, main/src/main/java/cgeo/geocaching/models/Geocache.java, main/src/main/java/cgeo/geocaching/utils/MapMarkerUtils.java, main/src/main/res/drawable/marker_rating_notsupported.xml
fixes #14343
for D/T cache marker differentiate between "not supported by connector" -> "-" and "information missing" -> "?"
Afaik AL is the only connector not supporting DT, so this change effects only those as of right now
=> DT marker: differentiate between missing and not supported

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java, main/src/main/java/cgeo/geocaching/ui/dialog/EditNoteDialog.java, main/src/main/res/menu/menu_ok_cancel.xml, main/src/main/res/values/strings.xml
in Edit Personal Note dialog add a third button to perform a "save and upload" (if the connector supports it) instead of saving, then clicking the "upload" button in Description view
=> add a "Save and upload" button in Edit Personal Note dialog

main/src/main/java/cgeo/geocaching/connector/gc/GCConnector.java, main/src/main/java/cgeo/geocaching/connector/gc/GCMap.java, main/src/main/java/cgeo/geocaching/filters/core/GeocacheFilterType.java, main/src/main/java/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java, main/src/main/res/values/strings.xml
adds a new "Event Date" filter which is actually just a "Hidden Date" filter but with relative range reaching into the future, not the past
fixes #14330
=> add a relative date filter looking into the future to filter events by date

main/src/main/java/cgeo/geocaching/utils/MapLineUtils.java
Currently map line widths on UnifiedMap VTM are way too heavy. It looks to me like the manual adjustment to display density is no longer needed since the recent changes to VTM map layers. This PR adjusts `MapLineUtils` accordingly.
|NewMap|VTM before|VTM after|
|---|---|---|
|![image](https://github.com/cgeo/cgeo/assets/3754370/70c624c7-6ade-4507-a8b4-997e2bfed8ec)|![image](https://github.com/cgeo/cgeo/assets/3754370/b3dcdd11-abed-4d67-8ea5-a46d99addec2)|![image](https://github.com/cgeo/cgeo/assets/3754370/52fbc93b-b681-4fdf-862a-2303bb04c76d)|
|CGeoMap|Google Map Unified|
|---|---|
|![image](https://github.com/cgeo/cgeo/assets/3754370/0634ca2b-aa42-4d8c-967f-df444df56902)|![image](https://github.com/cgeo/cgeo/assets/3754370/416fd3be-d6d7-4574-b25c-e5c8f63f39f4)|
(taken on a different …
=> UnifiedMap: Try to fix line widths

main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java
Fixes crash on screen rotation, as `onMapReadyTasks` are undefined of first call to `onViewCreated` (but only on subsequent calls).
=> UnifiedMap: Fix crash on VTM screen rotation (rel. to #13575)

main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsFragment.java
Fix crashes on screen rotation of UnifiedMaps GM, which are caused by activity not being available when `onMapReady` gets called directly after screen rotation.
=> UnifiedMap: Fix crashes on GM screen rotation (rel. to #13575)

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
On activity init BRouter is not yet ready and returns empty routes, which get converted to straight connections. 
The callback for Routing.connect() therefore needs to reload the route, not only refresh its display.
Whether we want to leave in the `viewModel.reloadIndividualRoute();` line after the `Routing.connect()` line is a matter of taste: Shall the uncalculated route be displayed already, or do we wait for a calculated route?
=> UnifiedMap: Fix initial load of individual route (fix #14363)

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java, main/src/main/java/cgeo/geocaching/CachePopupFragment.java, main/src/main/java/cgeo/geocaching/connector/gc/GCLogin.java, main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java, main/src/main/java/cgeo/geocaching/enumerations/StatusCode.java, main/src/main/res/values/strings.xml
Use GC-specific error message in GC connector-related files only, and remove GC-specific text in general contexts.
=> Replace connector-specific string in general message (fix #14377)

main/src/main/res/drawable/ic_menu_camera.xml, main/src/main/res/drawable/ic_menu_file_add.xml, main/src/main/res/drawable/ic_menu_image_multi.xml
update buttons in image gallery to a) use current material design look, b) use filled (instead of outline) for "add file"
Old:
New:
=> update button icons in image gallery

main/src/main/java/cgeo/geocaching/downloader/PendingDownloadsActivity.java
When opening the list of pending downloads, c:geo currently displays a modal info box, if there are no pending downloads currently. This PR changes this to a short toast and finishes the list activity.
=> Pending downloads: Replace modal dialog by toast

main/src/main/java/cgeo/geocaching/downloader/AbstractDownloader.java, main/src/main/java/cgeo/geocaching/downloader/BRouterTileDownloader.java, main/src/main/java/cgeo/geocaching/downloader/ReceiveDownload.java, main/src/main/res/values/strings.xml
Extends download by integrity checks capabilities (after download, but before copying, and after copying).
`BRouterTileDownloader` hooks into the first one and does an integrity check before copying the file.
Second type of integrity check could be used by OSM offline map downloaders (but is not yet implemented for them).
=> Add integrity check to tile downloader (fix #10416)

main/src/main/java/cgeo/geocaching/location/ProximityNotification.java, main/src/main/java/cgeo/geocaching/settings/ButtonPreference.java, main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/java/cgeo/geocaching/settings/SettingsActivity.java, main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceMapContentBehaviorFragment.java, main/src/main/java/cgeo/geocaching/storage/PersistableUri.java, main/src/main/res/layout/preference_button_widget.xml, main/src/main/res/values/attrs.xml, main/src/main/res/values/preference_keys.xml, main/src/main/res/values/strings.xml, main/src/main/res/xml/preferences_map_content_behavior.xml
Extension to proximity notifications to let users select their own audio files for proximity notification.
Uses SAF file picker to select one or two audio files. Resetting to built-in tone is possible by pressing the "delete" icon beside the file selection.
=> Support for user-selected audio for proximity notifications

main/src/main/java/cgeo/geocaching/settings/ProximityPreference.java, main/src/main/res/values/numbers.xml
- fix wrong initialization of ProximitySeekbar's max progress value
- raise max value for routing threshold from 120 to ~250~ 1000 km
=> Fix default max for ProximitySeekbar (fix #14394)

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java, main/src/main/java/cgeo/geocaching/utils/DisposableHandler.java, main/src/main/java/cgeo/geocaching/utils/ProgressBarDisposableHandler.java, main/src/main/java/cgeo/geocaching/utils/ProgressButtonDisposableHandler.java, main/src/main/java/cgeo/geocaching/utils/SimpleDisposableHandler.java, main/src/main/res/layout/cachedetail_details_page.xml, main/src/main/res/layout/tabbed_viewpager_activity_refreshable.xml, main/src/main/res/values/strings.xml
Replace most dialogs when performing network actions from CacheDetails view with progress bar. Only one not replaced is the initial cache loading.
fixes #14358
fixes #14355
see these issues for more reasoning
PR also includes #14356 due to some rewrites, will rebase once that one is merged
=> Replace progress dialogs with inline views in cache listing

main/src/main/java/cgeo/geocaching/MainActivity.java, main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/res/layout/main_activity.xml, main/src/main/res/values/preference_keys.xml, main/src/main/res/values/strings.xml, main/src/main/res/xml/preferences_services_geocaching_com.xml
Optionally polls message center for unread messages and displays a notification on home screen if so.
Notification handling is the same as for other update infos:
- notification text + blue badge on home screen bottom navigation icon
- a short tap opens the message center in the browser
- a long top closes the notification without opening the message center
This functionality can be activated in settings => services => geocaching.com, default is "off".
=> Display info on home screen for unread messages

main/build.gradle
Updates both Mapsforge and VTM to v0.19
(Removes usage of specific commit id of Mapsforge to support hillshading on SAF, as this is part of v0.19 meanwhile)
=> Update Mapsforge & VTM to v0.19.0

main/src/main/java/cgeo/geocaching/MainActivity.java, main/src/main/java/cgeo/geocaching/connector/gc/GCConstants.java, main/src/main/java/cgeo/geocaching/enumerations/QuickLaunchItem.java
As discussed in our last team meeting: Make message center available on home screen even when unread messages notification is disabled.
This PR adds a quicklaunch item which the user can activate. Tapping on it opens message center in the browser.
=> Add message center quicklaunch item

main/src/main/java/cgeo/geocaching/CacheListActivity.java
Disables some menu entries in cache lists, when list is empty:
- Upload modified coordinates
- Upload coordinates for all caches
- Show attribute list
=> Disable some menu entries for empty lists (fix #14412)

main/src/main/res/values/strings.xml
Remove the temporary string in strings.xml, as the error is solved in the meantime, the issue https://github.com/material-components/material-components-android/issues/1346 is fixed.
=> Remove the temporary string in strings.xml

main/src/main/java/cgeo/geocaching/MainActivity.java, main/src/main/java/cgeo/geocaching/activity/AbstractBottomNavigationActivity.java, main/src/main/java/cgeo/geocaching/enumerations/QuickLaunchItem.java, main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceAppearanceFragment.java, main/src/main/res/drawable/ic_empty_placeholder.xml, main/src/main/res/values/preference_keys.xml, main/src/main/res/values/strings.xml, main/src/main/res/xml/preferences_appearence.xml
Makes the last bottom navigation item customizable:
- default (= nearby search)
- empty
- any of the quick launch items (same as on home screen)
Configuration is in settings => appearance => Custom Menu Entry
This is an alternative to #14405.
Example: Last item replaced by "pocket queries":
Configuration dialog: (updated)
=> Make last bottom navigation item customizable

main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/GeoObjectLayer.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/TapHandlerLayer.java, main/src/main/java/cgeo/geocaching/models/geoitem/GeoGroup.java, main/src/main/java/cgeo/geocaching/models/geoitem/GeoPrimitive.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GeoItemTestLayer.java, main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GoogleV2GeoItemLayer.java, main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeV6GeoItemLayer.java, main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeVtmGeoItemLayer.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/TracksLayer.java, main/src/main/java/cgeo/geocaching/utils/GeoJsonUtils.java, main/src/test/java/cgeo/geocaching/models/geoitem/GeoItemTest.java
rel to #14391: add polygon hole support for vtm and google.
Support for mapsforge is not added because mapsforge Polygon object don't naturally support holes. Holes are only supported in new unified map.
=> rel to #14391: add polygon hole support for vtm and google

main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java
Currently even an empty log text is saved for future use and therefor overrides the last "useful" log-text
This PR saves only non-empty-log-text for using it in "repeat last log".
Saving an empty log is still possible.
rel #14371 ("Insert last log" discarded when adding image first)
=> save only non-empty-log-text to be used as "repeat last log" (rel #14371)

main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java
De-HTML parsed "TB spotted by" username to avoid double encoding on TB page.
=> De-HTML parsed username for trackable's spottedName (fix #14442)

main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/res/xml/preferences_map_sources.xml
see https://github.com/orgs/cgeo/discussions/73
(Will trigger some "unused string", "unused method" and "hardcoded string" lint messages, which should be ignored for the time being.)
=> Temporarily disable OSM multithreading for testing purposes

main/src/main/res/values/strings_not_translatable.xml
- BRouter tile downloads should use https
- Freizeitkarte downloads cannot use https, as their certificate refers to www sudomain, neither "repository" nor "download"
=> Check/adapt downloader URL for https

main/src/main/java/cgeo/geocaching/ImageViewActivity.java, main/src/main/res/layout/imageview_image.xml
Enable selection context menu on image (EXIF) description for copying of text, translation etc.
Text limitation to 380 chars is removed (to be able to see/copy the complete description, which is helpful for some mysteries), but `TextView` size is limited to 7 lines to keep maximum size similar to today.
Additional info:
Enabling the selection context menu requires the `TextView` to enable "isSelectable" and "isFocusable" attributes. Tapping on image description will therefore no longer show/hide the image description. The other two ways for hiding/unhiding the description (tapping on the image or tapping the small arrow beside image description) are still available, though.
=> Allow selecting, copying etc. of image description (EXIF info) (fix #14415)

main/src/main/java/cgeo/geocaching/settings/ViewSettingsActivity.java
Currently editing any setting requires you to enter a string for its value. This is ok for most settings' types, but pretty cumbersome for type boolean. This PR provides a selection box for type boolean settings:
|old|new|
|---|---|
|![image](https://github.com/cgeo/cgeo/assets/3754370/1c961f98-c1e2-4322-b453-24777f9189dc)|![image](https://github.com/cgeo/cgeo/assets/3754370/1f2c2f4a-3596-47ab-b05c-df083d19fade)|
=> Provide selction dialog for editing boolean settings

main/src/main/res/values/preference_keys.xml, main/src/main/res/xml/preferences_navigation_navigation.xml
Add missing XML configuration for OrganicMaps entry in navigation menu definition
Also aligns preference key value for OrganicMaps to the other navigation preference keys
=> Add missing navigation menu XML entry for OrganicMaps (fix #14466)

main/src/main/java/cgeo/geocaching/apps/cachelist/MapsMeCacheListApp.java, main/src/main/java/cgeo/geocaching/apps/navi/MapsMeApp.java, mapswithme-api/src/com/mapswithme/maps/api/MapsWithMeApi.java
- Add maps.me installation check, greying out navi menu entries when not installed
- Removes maps.me auto-download dialog (silently fails in that case)
- maps.me installed check is based on intent resolving, so no specification of package names needed for that
=> Remove maps.me auto-download + add install check (fix #14474)

main/src/main/java/cgeo/geocaching/maps/routing/RouteSortActivity.java
Displaying waypoints along a route should use short geocodes, same as caches already do. Especially important if you make stages of lab adventures part of your route.
=> Use short geocode for waypoints in RouteSort activity

main/src/main/java/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/TileSourceOpenTopoMap.java, main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/OpenTopoMapSource.java, main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/TileProviderFactory.java, main/src/main/res/values/strings_not_translatable.xml
Adds OpenTopoMap as map provider for both `NewMap` and `UnifiedMap`, including attribution etc.
=> Add OpenTopoMap as map provider for Mapsforge and VTM (fix #9470)

main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/res/xml/preferences_map_sources.xml
Looking at the logs for our current beta version, the SIGABRT crashes still do happen, so it's not fixed by restricting Mapsforge to single-threaded rendering. Let's revert that restriction then.
=> Revert "Temporarily disable OSM multithreading for testing purposes"

organicmaps-api/src/main/AndroidManifest.xml, organicmaps-api/src/main/java/app/organicmaps/api/OrganicMapsApi.java
Switches OrganicMaps installation check to intent resolution so that we do not have to check for several different package names manually.
=> Switch OrganicMaps install check to intent resolution

main/src/main/java/cgeo/geocaching/CacheListActivity.java, main/src/main/res/menu/cache_list_options.xml
Removes outdated unlabelled(!) "show on map" menu entry that only appeared when only one cache list navigation app is present. This did not happen for a long while, as "internal map" and "maps.me" have always been marked as being present, but with the removal of "maps.me is always marked as being installed", this menu entry got triggered again.
(See https://github.com/cgeo/cgeo/issues/14500#issuecomment-1676116938 for more info)
=> Remove outdated 'show on map' menu entry (fix #14500)

main/src/main/java/cgeo/geocaching/address/AddressListActivity.java
Instead of passing the MapQuestGeocoder fallback value directly, we now provide a function that is only called in case of an error.
=> Fix #13679: Call MapQuestGeocoder lazily

main/build.gradle
As per Play Store requirements set `targetSDK` to 33. (Apps not supporting `targetSDK` 33 will be blocked from updating on Play Store starting end of August, see #14499.)
=> Set targetSDK to 33

main/build.gradle, main/proguard-project.txt
replaces  #14224
As result of the update, we can now remove the proguard configuration for okhttp. This entries are now part of okhttp, see https://github.com/square/okhttp/commit/cf088f852e41bc61b02cea9859a1cd3763aff778 .
=> Bump okhttpVersion from 4.10.0 to 4.11.0

main/src/main/java/cgeo/geocaching/CgeoApplication.java
Add c:geo version info to logfile (fix #14530)
(Using `Log.e()` to make sure it's included in a logfile and not filtered out by log level)
=> Add c:geo version info to logfile (fix #14530)

main/src/main/java/cgeo/geocaching/files/GPXTrackOrRouteParser.java
Correctly reset `temp` point for imports with multiple track files. (Brought up by user on support claiming GPX import not working for him. Ticket 181488.)
=> Fix GPX import with multiple tracks

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
Limits fav ratio on cache details page to a maximum of 100%
=> Limit fav ratio to 100% on cache details page (fix #14543)

main/src/main/java/cgeo/geocaching/network/HtmlImage.java, main/src/main/java/cgeo/geocaching/ui/ViewUtils.java, main/src/main/java/cgeo/geocaching/utils/ImageUtils.java
fix #14521: ensure minimum image size for display
Fix is to apply a minimum size onto all images displayed in listing. Currently hardcoded at 20dp (width + height). Looks now like this:
=> fix #14521: ensure minimum image size for display

main/src/main/java/cgeo/geocaching/activity/AbstractNavigationBarActivity.java, main/src/main/java/cgeo/geocaching/storage/DataStore.java
rel to #14375: lock all database access and differentiate between access and changing using read-write-lock
A different approach to solve #14375: introduce a read-write-lock-mechanism onto DataStore:
* each access to the database requires a read-lock
* each "database-changing" access which requires a "close" (e.g. backup restore move) requires a write-lock
That way in theory all dangling cursors and insert/update/delete operations should be finished when the "write" lock is aquired and close/reopen should be save.
Would that be the better way to solve #14375? Of course this requires discipline when introducing new database interaction - it must always aquire a lock.
@moving-bits
=> rel to #14375: lock all database access and differentiate between access and changing using read-write-lock

main/AndroidManifest.xml, main/src/main/java/cgeo/geocaching/ImageEditActivity.java, main/src/main/java/cgeo/geocaching/Intents.java, main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java, main/src/main/java/cgeo/geocaching/ui/ImageActivityHelper.java, main/src/main/java/cgeo/geocaching/ui/ImageListFragment.java, main/src/main/res/layout/imageedit_activity.xml, main/src/main/res/menu/abstract_logging_activity.xml, main/src/main/res/values/strings.xml
rel to #14514: redesign GUI for image edit
Following the layout discussed in the issue, when merging this PR layout will look like this:
* "delete" was removed completely, "ok/cancel" was moved into action bar using symbols
* title was changed from cache title to constant "edit image"
* order of input elements was changed to the order suggested in issue
=> rel to #14514: redesign GUI for image edit

main/build.gradle
see eg. from CI:
~~~
22:08:37  emulator-5554 shell run-as cgeo.geocaching mkdir /data/data/cgeo.geocaching/shared_prefs/ ...
22:08:37  Process 'command '/opt/android-sdk-linux/platform-tools/adb'' finished with non-zero exit value 1mkdir: '/data/data/cgeo.geocaching/shared_prefs/': File exists
~~~
=> avoid mkdir 'error' message "File exists" on CI

main/lint.xml
- change paths to changed c:geo "main" structure
- add ignore filter for changelog files
- compact filter for rating files
- add an IconDuplicates ignore entry
@moving-bits Adding the routing_dummy.brf file to c:geo source was intentional, wasn't it?
@ztNFny Using the same attributes_kids* file was  intentional, wasn't it?
=> optimize lint configuration

main/src/androidTest/java/cgeo/geocaching/downloader/DownloaderTest.java, main/src/main/java/cgeo/geocaching/downloader/AbstractDownloader.java, main/src/main/java/cgeo/geocaching/downloader/DownloadSelectorActivity.java, main/src/main/java/cgeo/geocaching/models/Download.java, main/src/main/res/drawable/downloader_folder_back.xml
Navigate up when using back key and show different icon for "(one level up)" folder.
From time to time, I was struggling with the fact that back key finishes the download activity instead of navigating up. This annoyed my every time so much that I finally fixed this thing.
As I introduced a special `isBackDir` flag anyway, I also gave it a new dedicated icon on the fly:
=> Navigate up when using back key

main/src/main/java/cgeo/geocaching/ImageEditActivity.java, main/src/main/java/cgeo/geocaching/ImageViewActivity.java, main/src/main/java/cgeo/geocaching/activity/ActivityMixin.java, main/src/main/java/cgeo/geocaching/ui/ImageActivityHelper.java, main/src/main/java/cgeo/geocaching/ui/ImageGalleryView.java, main/src/main/java/cgeo/geocaching/utils/ImageUtils.java, main/src/main/java/cgeo/geocaching/utils/ViewOrientation.java
fix #14514: make image edit performant (rotate/flip)
No new GUI elements. 
* Image rotation/flip is now just saved using exif "orientation" flag
* Saving image changes are only done if necessary (on "external edit" and on "leave and save") and using ExifInterface (->no need to load file into memory and performing matrix operation)
* Image Size is also only loaded if really necessary (on entering activity, on getting image back from external editor). 
* Image Size retrieving method was performance-improved in ImageUtils
View Orientation information was encapsulated in new class ViewOrientation
=> fix #14514: make image edit performant (rotate/flip)

main/src/main/java/cgeo/geocaching/settings/SettingsActivity.java
Use fragment backstack when navigating up in `SettingsActivity` and fall back to default `navigateUp` behavior, if no fragment left on backstack
=> Use fragment backstack on navigateUp in settings (fix #14552)

main/build.gradle, main/src/main/java/cgeo/geocaching/maps/AbstractMap.java, main/src/main/java/cgeo/geocaching/maps/CGeoMap.java, main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleCacheOverlayItem.java, main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java, main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapItemFactory.java, main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapView.java, main/src/main/java/cgeo/geocaching/maps/interfaces/MapItemFactory.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/MapsforgeMapItemFactory.java, main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/AbstractGoogleTileProvider.java
- Updates Google Maps rendering engine
- comes with a mitigation for long-tap function to avoid #14534
TODO: needs to toggle `draggable` property on cache markers depending on renderer type, therefore setting draft state for now
=> Update GM to latest renderer (when available) ( #12023)

main/src/main/java/cgeo/geocaching/settings/PreferenceTextAlwaysShow.java, main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/java/cgeo/geocaching/settings/SettingsActivity.java, main/src/main/java/cgeo/geocaching/settings/fragments/BasePreferenceFragment.java, main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceAppearanceFragment.java, main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceBackupFragment.java, main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceCachedetailsFragment.java, main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceLoggingFragment.java, main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceMapContentBehaviorFragment.java, main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceMapSourcesFragment.java, main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceNavigationFragment.java, main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceOfflinedataFragment.java, main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceServicesFragment.java, main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceSystemFragment.java, main/src/main/java/cgeo/geocaching/settings/fragments/PreferencesFragment.java, main/src/main/res/values/preference_keys.xml, main/src/main/res/values/strings.xml, main/src/main/res/xml/preferences.xml, main/src/main/res/xml/preferences_backup.xml, main/src/main/res/xml/preferences_map_content_behavior.xml, main/src/main/res/xml/preferences_navigation.xml, main/src/main/res/xml/preferences_system.xml
Show fewer settings in default config mode, as proposed in [internal discussion](https://github.com/orgs/cgeo/discussions/78).
To toggle extended settings, see switch "extended settings" in system's config.
Some things are not yet working fully:
- ~some descriptive texts are missing yet~
- ~"Offline settings" cannot be reached currently~
- ~toggling basic/extended settings requires restart of current settings screen~
- ~search index has not been tested with yet~
- toggling basic/extended settings closes system settings
=> Distinguish between default and extended config mode

main/src/main/java/cgeo/geocaching/maps/CGeoMap.java
Forward last navigation target to destination drawer in map init by calling `setTarget()` (bug fix for GMv2)
=> GMv2: Re-set navigation target on map init (fix #14575)

main/src/main/java/cgeo/geocaching/maps/CGeoMap.java
Removes individual route from GMv2 map display on deleting the route
=> GMv2: Remove individual route from map on deletion (fix #14535)

main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java
rel to #13309: log dialog: leave fav checkbox available if set
=> rel to #13309: log dialog: leave fav checkbox available if set

main/src/main/java/cgeo/geocaching/ui/CacheListAdapter.java, main/src/main/java/cgeo/geocaching/ui/GeoItemSelectorUtils.java, main/src/main/java/cgeo/geocaching/utils/TextUtils.java
- Mark past events by italics
- Refactoring: Use `TextUtils.coloredCacheText` in more places instead of individually composing attributes
=> Mark past events by italics (fix #14523)

main/src/main/java/cgeo/geocaching/settings/fragments/PreferencesFragment.java, main/src/main/res/xml/preferences.xml
Hide offline data settings in basic config mode instead of only disabling them (to be consistent with other extended settings)
=> Hide offline data settings in basic config mode

main/src/main/java/cgeo/geocaching/utils/ScalableDrawable.java
`ScalableDrawable` assumed drawables to be squares and failed correct scaling on non-squares, which this PR fixes.
=> Support scaling of non-square drawables (rel. to #14612)

main/src/main/java/cgeo/geocaching/utils/SystemInformation.java
Streamline permission info block in system information
- remove common prefix "android.permission." from permission info
- remove doubled ":"
|before|after|
|---|---|
|![image](https://github.com/cgeo/cgeo/assets/3754370/425d010c-1636-4945-af7b-082785b6e1ba)|![image](https://github.com/cgeo/cgeo/assets/3754370/ed5d4996-3576-42bc-b93b-71df37ab9141)|
=> Streamline permissions info in system information

main/src/main/res/xml/preferences.xml
Removes the PreferenceCategory ("heading") from settings' main screen, just draws the divider between "extended settings" switch and other settings. For screenshot see https://github.com/cgeo/cgeo/pull/14606#issuecomment-1721705749
=> Remove PreferenceCategory from settings main screen

main/build.gradle, main/src/main/java/cgeo/geocaching/MainActivity.java, main/src/main/java/cgeo/geocaching/SearchActivity.java
We have some code and library remainders from our former scanner app integration. Without starting a scan there's no need for checking for an `ActivityResult` :-) and the integration lib can be removed as well.
Not sure, though, whether the `requestCode == Intents.SEARCH_REQUEST_CODE` code block is still required. Does not seem to be directly related to the scanner integration, but I cannot find a call to it from within c:geo either. I left the code part in for now, to be on the safe side.
=> Remove remainders from scanner integration (rel. to #11530)

main/src/main/res/values/strings.xml
"-" as a string does not need to be translated, IMHO, therefore marking it as non-translatable
=> Mark '-' strings as non-translatable

main/src/main/java/cgeo/geocaching/models/CacheArtefactParser.java, main/src/main/java/cgeo/geocaching/models/Waypoint.java, main/src/test/java/cgeo/geocaching/models/CacheArtefactParserTest.java
Exports the visited-flag as {v} into the personal note, if waypoint is visited.
syntax: @Name (F) **{v}** Coordinates "note"
fix #14428
writes {v} to indicated, that the waypoint is visited. If flag is not set, but existing waypoint is visited, the merged waypoint will be visited.
=> Write visited flag to personal note (fix #14428)

main/src/main/java/cgeo/geocaching/InstallWizardActivity.java, main/src/main/java/cgeo/geocaching/activity/AbstractNavigationBarActivity.java, main/src/main/java/cgeo/geocaching/storage/extension/OneTimeDialogs.java, main/src/main/java/cgeo/geocaching/ui/dialog/Dialogs.java, main/src/main/res/values/strings.xml
Shows a OneTimeDialog informing about required POST_NOTIFICATIONS permission and optionally starts configuration wizard.
Happens on API33+ systems only, and only if notification permission is missing.
=> Show permission update info on API33+ w/o notification permission

main/src/main/java/cgeo/geocaching/settings/SeekbarPreference.java, main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceAppearanceFragment.java, main/src/main/java/cgeo/geocaching/utils/MapMarkerUtils.java, main/src/main/res/values/preference_keys.xml, main/src/main/res/values/strings.xml, main/src/main/res/xml/preferences_appearence.xml
Adds settings' UI for icon scaling options as discussed in https://github.com/cgeo/cgeo/pull/14388#issuecomment-1622076437
Two caveats:
- I needed to rename the preference key, as seekbar preferences require an `int` preference, but for some reason I had created the scaling factors as `long` values. This will reset icon scaling factors once on upgrade.
- ~Currently a restart of c:geo is required to bring changed settings into effect.~
~I've tried resetting the marker cache + updating the scaling factor variables in `MapMarkerUtils` on changing the scaling settings' values, but on opening the map the next time within the same session, no markers got drawn and the map crashed eventually, without any useful info in Logcat. Any ideas?~
=> Add UI for icon scaling options (rel. to #14388)

main/src/main/java/cgeo/geocaching/connector/gc/GCConnector.java, main/src/main/java/cgeo/geocaching/connector/gc/GCConstants.java, main/src/main/java/cgeo/geocaching/connector/gc/GCLoggingManager.java, main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java, main/src/main/java/cgeo/geocaching/connector/gc/GCWebAPI.java, main/src/main/java/cgeo/geocaching/log/TrackableLog.java, main/src/main/java/cgeo/geocaching/network/Cookies.java, main/src/main/java/cgeo/geocaching/network/HttpRequest.java, main/src/main/java/cgeo/geocaching/network/HttpResponse.java, main/src/main/java/cgeo/geocaching/network/Network.java, main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/res/values/preference_keys.xml, main/src/test/java/cgeo/geocaching/utils/TextUtilsTest.java
First implementation for new GC.com Log API.
To activate usage of new API by c:geo, a new hidden boolean setting `feature_new_gc_log_api` must be added and set to value `true`. 
With this activated the following should work via new logging API:
* Simple logging of geocaches, e.g. log date, type, text
* Adding of images to a log (including name + description)
* Automatic trackable status setting to "visited"/"dropped" according to setting in c:geo
The following will NOT work for the new setting:
* "add to favorites" setting in log will be ignored (-> as of now it is not clear whether this can be handled by new API)
* Logging of Trackables seems to be using the new API too on website, but was not yet touched in c:geo
The implementation is to be considered a first try. Alpha testing is …
=> New GCLog API: Basic Cache logging + images + trackable status

main/src/main/java/cgeo/geocaching/activity/ActivityMixin.java, main/src/main/java/cgeo/geocaching/connector/gc/GCLoggingManager.java, main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java, main/src/main/java/cgeo/geocaching/connector/gc/GCWebAPI.java
New GCLogApi: make it work for nonmigrated users + restore log favorite capability
Builds on top of #14635 and adds:
* Ability to log for not-yet-migrated users
* Restore ability to add favorite point directly in log dialog 
Still open:
* Trackable Logging
=> New GCLogApi: make it work for nonmigrated users + restore log favorite capability

main/src/main/java/cgeo/geocaching/utils/EmojiUtils.java, main/src/main/java/cgeo/geocaching/utils/MapMarkerUtils.java, main/src/main/res/drawable/type_marker_multi.xml
implements the remaining items from #14502 per https://github.com/cgeo/cgeo/issues/14502#issuecomment-1676448955:
- for linear ALCs use emoji-numbers instead of puzzle icon. As those only cover 0-9 stage numbers > 10 stage are handled by substracting 10 from the stage count -> stage 10 is displayed as 0
- for all waypoints show the associated cache type as marker in top-left (if no custom cache icon (emoji) is set for the cache)
=> [14502] for linear labs use numbers as waypoint marker, for all WPs show type icon as overlay

main/src/main/java/cgeo/geocaching/brouter/util/DefaultFilesUtils.java
Fixes `UnusedResource` error, also first step for testing whether new "elevation only" mode can be useful for c:geo
=> Include routing elevation conf file in DefaultFiles (fix #14572)

cgeo-contacts/build.gradle, main/build.gradle, mapswithme-api/build.gradle, organicmaps-api/build.gradle
Set targetSdk 33 for all other projects to stay in line with `main`.
Follow up changes should not be necessary, imho.
=> targetSdk 33 for subprojects

main/src/main/java/cgeo/geocaching/maps/CGeoMap.java, main/src/main/java/cgeo/geocaching/maps/DistanceDrawer.java, main/src/main/java/cgeo/geocaching/maps/MapDistanceDrawerCommons.java, main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapView.java, main/src/main/java/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java, main/src/main/java/cgeo/geocaching/maps/interfaces/PositionAndHistory.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/DistanceView.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/main/java/cgeo/geocaching/maps/routing/Routing.java, main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapViewModel.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/NavigationTargetLayer.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/UnifiedTargetAndDistancesHandler.java, main/src/main/res/values/preference_keys.xml, main/src/main/res/values/strings.xml, main/src/main/res/xml/preferences_map_content_behavior.xml
Show elevation info for current position on map (if activated in settings, default=false).
BRouter routing tiles provide LIDAR-based elevation info, so it's taken from that, if available. Otherwise looks for available GNSS altitude info (if available).
Elevation info is displayed top-right, below distance infos (if applicable):
=> Show elevation info for current position on map

main/src/main/java/cgeo/geocaching/ui/ViewUtils.java, main/src/main/java/cgeo/geocaching/ui/dialog/SimpleDialog.java, main/src/main/res/layout/simpledialog_filtered_selection.xml
Adds a filter box to `SimpleDialog.selectMultiple()`:
- Filter will only be displayed when there are 10 entries or more initially.
- Entry for "Select all" reflects the number of visible elements and only gets applied to visible elements.
- Entry for "Select all" will not be filtered out.
- Filtered-out but still checked elements are part of the result.
- Uses a custom layout for the `AlertDialog` to be able to inject the filter box. Therefore requires a custom adapter as well (as it's already done in `SimpleDialog.selectSingle()`).
- Checkbox state of "Select all" can become invalid currently when used in combination with filtering.
- Tested only with "Select lists for cache" for now.
Setting draft state for now due to the last two items.
@eddiemuc 
Can you cross-check if I haven't …
=> Add filtering to SimpleDialog.selectMultiple (rel. to 14602)

main/src/main/java/cgeo/geocaching/maps/CGeoMap.java
fixes #14649 (Waypoint icon shown behind cache icon) by not drawing the waypoint icon on map if waypoint coords are the same as cache coords.
I added a special case if the waypoint has a note - this would e.g. be a multi stage with description - if the user has set the cache coords to stage coords.
=> don't draw waypoints without note at cache coords

main/src/main/java/cgeo/geocaching/maps/MapDistanceDrawerCommons.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/UnifiedTargetAndDistancesHandler.java
Reenables display of (straight) distance info when "show straight distance info" is enabled in settings and routing mode is set to STRAIGHT
=> Fix missing distance info in certain setting (fix #14688)

main/src/main/java/cgeo/geocaching/ui/dialog/SimpleDialog.java, main/src/main/res/values/styles.xml, main/src/main/res/values/themes.xml
Fix font size of new multi selection dialog. Item spacing is a bit too dense compared to the old dialog, so setting WIP for now.
=> Fix dialog formatting issues for multi select (rel. to #14602)

main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceAppearanceFragment.java, main/src/main/res/values/strings.xml
- rename item to "Custom Menu Item" (instead of Custom Menu Entry)
- display a explanatory description (in addition to current value)
=> Extend settings description for custom menu item (fix #14473)

main/src/main/java/cgeo/geocaching/ui/dialog/SimpleDialog.java
Sets text size in dialogs based on `SimpleDialog.selectSingle()` to our default text size, as we have done for `selectMulti()` already (but does not change item spacing).
=> Fix text size in selectSingle dialogs (rel. to #14602)

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java, main/src/main/java/cgeo/geocaching/storage/DataStore.java, main/src/main/res/menu/cache_options.xml, main/src/main/res/values/strings.xml
We already have a "append all to route" for cache lists. This PR adds "append all to route" for waypoints, to be called from waypoint list. Useful for multis or lab adventures.
=> Add 'append all to route' for waypoints

main/src/main/java/cgeo/geocaching/location/ProximityNotification.java, main/src/main/res/values/strings.xml
Put proximity info ("14 meters: GCxxxx Cache name") in both notification title and content, as some devices show title first (and cut off content).
=> Put proximity info in notification title (fix #14673)

main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceMapSourcesFragment.java
PreferenceCategory pref_fakekey_unifiedmap has 2 entries but only one of them was hidden depending on R.string.pref_showUnifiedMap
=> hide the whole "unified map" preferences category if not enabled instead of only 1 setting

main/src/main/java/cgeo/geocaching/utils/BackupUtils.java, main/src/main/res/values/strings.xml
When restoring a backup which includes persisted URI, the user needs to regrant access to those files.
We had this for persisted track file and removed functionality when we switched to supporting multiple track files with a different storage method. Now we have persisted URI for proximity notification audio files and need to re-enable this mechanism.
=> Regrant Uri permissions on restore

main/src/main/java/cgeo/geocaching/InstallWizardActivity.java, main/src/main/res/values/strings.xml
- Change: Moves restore functionality to "config services" screen
- Fix: "Next" button gets renamed to "Done" as soon as you select one of the three options
- Change: Removed "Advanced settings" screen to reduce number of config screens
- Fix: Request notification permission directly after location permissions, so that permissions are in the same block
=> Integrate restore in wizard's config services screen (rel. to #14706)

main/src/main/java/cgeo/geocaching/maps/MapSettingsUtils.java, main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceNavigationFragment.java, main/src/main/res/xml/preferences_navigation.xml
- Hide pref title "Max. distance for routing calculation" if no routing option is available
- Hide routing profile options if not using internal routing
- Hide user1/2 options in map quick settings and their label if not using internal routing
=> Show only available routing options (fix #14721)

build.gradle
it is not usable for c:geo from gradle 7.6.
See discussion https://github.com/cgeo/cgeo/pull/13791.
=> remove taskinfo

main/src/main/java/cgeo/geocaching/ui/GeoItemSelectorUtils.java, main/src/main/java/cgeo/geocaching/unifiedmap/LoadInBackgroundHandler.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapViewModel.java, main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GoogleV2GeoItemLayer.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/GeoItemsLayer.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/IndividualRouteLayer.java, main/src/main/res/drawable/marker_routepoint_large.xml, main/src/main/res/values/strings.xml
- re-enable item click listener on unified map
- show WPs on unified map
- correctly show coord-only-points when being clicked on unified map
- only consider coord-only-points when tap was a longTap on unified map
=> re-enable item click listener on unified map

main/src/main/java/cgeo/geocaching/maps/MapDistanceDrawerCommons.java, main/src/main/java/cgeo/geocaching/maps/routing/RoutingMode.java, main/src/main/java/cgeo/geocaching/ui/TextParam.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/UnifiedTargetAndDistancesHandler.java, main/src/main/res/drawable/elevation.xml
Replaces Unicode characters by icons for distance and elevation symbols in map view.
Uses selected routing type-specific icons instead of generic "wavy line" symbol, if applicable.
=> Use icons for distance and elevation info (fix #14744)

main/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
fixes #14758
some launchers seem to pick the round icon and that one wasn't adaptive. Fixed by making round equal to normal
=> make round icon adaptive as well

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapViewModel.java, main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsFragment.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/CacheCirclesLayer.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/GeoItemsLayer.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java, main/src/main/java/cgeo/geocaching/utils/CompactIconModeUtils.java
Enables the map quick settings menu. Most of its functions do work already, including changing routing mode.
Functions yet missing are:
=> UnifiedMap: Enable map quick settings

main/src/main/java/cgeo/geocaching/MainActivity.java
Additionally check network availability before displaying GC connector-specific error message to avoid displaying an outdated error message when no network is available
=> Suppress outdated conn error msg on network not available (fix #14740)

main/src/main/java/cgeo/geocaching/unifiedmap/layers/UnifiedTargetAndDistancesHandler.java
Attempts to avoid flickering of distance views happening on some devices by updating distance views only if their content has actually changed (comparing both icon and text contents)
=> Try to avoid flickering of distance views (rel. to #14765)

main/build.gradle
> `coreLibraryDesugaringEnabled` is a feature in Android's build system that enables developers to use modern language features and APIs on older Android versions. Some benefits of using this feature include the ability to write more expressive, modular, and maintainable code, as well as leveraging the latest language features available in Java. However, there are also potential downsides to using `coreLibraryDesugaringEnabled`, including performance overhead, increased APK size, compatibility issues, and debugging issues. Developers should consider these pros and cons before deciding to use this feature in their Android projects.
___
Some cool Java features like `Streams` are only natively supported starting with API 24 while we are still targeting API 21. However, google provides a …
=> Enable coreLibraryDesugaring to provide access to modern java APIs on old API levels

main/src/main/java/cgeo/geocaching/ui/GeoItemSelectorUtils.java
Use `TextParam` and `ImageParam` in `GeoItemSelectorUtils` for consistent text alignment and icon sizing
|before|after|
|---|---|
|![image](https://github.com/cgeo/cgeo/assets/3754370/9db15a47-9731-49b4-a97f-a92c40505d83)|![image](https://github.com/cgeo/cgeo/assets/3754370/dd091613-b458-4a74-8475-789ea341f85f)|
=> GeoItemSelector: consistent icon size and alignment

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/ElevationChart.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/TracksLayer.java
Enable tracks for elevation chart:
- make tracks clickable
- add prefix to their key to make them identifiable
- allow elevation chart to get completely new data
- show "no elevation data available" in the chart if no elevation data is available
@fm-sys 
One thing is missing, though: How can I observe changes to the track? That may happen if someone changes the routing mode.
(`UnifiedMapViewModel.setTrack` is called in this case, but how to trigger an observer for this, delivering the key of the related track?)
=> UnifiedMap: Enable tracks for elevation chart

main/src/main/java/cgeo/geocaching/models/geoitem/GeoItem.java, main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GeoItemLayer.java
fix #14811: handle invalid GeoItems passed to GeoItemLayer: don't draw them
=> fix #14811: handle invalid GeoItems passed to GeoItemLayer: don't draw them

main/src/main/res/layout-land/unifiedmap_activity.xml, main/src/main/res/layout/unifiedmap_activity.xml, main/src/main/res/values/strings.xml
PR fixes both the two lint errors and the superfluous "xmlns:tools" attribute mentioned in https://github.com/cgeo/cgeo/pull/14779#discussion_r1382976210
=> Some lint fixes

main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java
fix #14825: parse gc personal note as html with special linebreak handling
=> fix #14825: parse gc personal note as html with special linebreak handling

main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java
fix #14825: unescape html entities in gc.com personal notes, better solution than before
=> fix #14825: unescape html entities in gc.com personal notes, better solution than before

main/src/main/res/layout/compass_activity.xml, main/src/main/res/layout/compass_hint_and_status.xml
Brings hint in `CompassActivity` to front (portrait mode only) and adds a background to the hint view:
|small font sizes|large font sizes|
|---|---|
|![image](https://github.com/cgeo/cgeo/assets/3754370/0ea774fa-39be-422e-800d-706dfa4a8bb0)|![image](https://github.com/cgeo/cgeo/assets/3754370/592dd5f8-9855-40aa-87a6-0f29743147b0)|
=> Bring compass hint to front + add background (fix #14831)

main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceSystemFragment.java, main/src/main/java/cgeo/geocaching/storage/extension/OneTimeDialogs.java, main/src/main/res/values/preference_keys.xml, main/src/main/res/values/strings.xml, main/src/main/res/xml/preferences_system.xml
Resets all internal data for one-time messages' view status.
(I needed this for debugging a different thing, so I added it to preferences => system => debug)
=> Add option to reset all one-time messages

main/src/main/java/cgeo/geocaching/downloader/CompanionFileUtils.java, main/src/main/java/cgeo/geocaching/downloader/DownloadSelectorActivity.java, main/src/main/java/cgeo/geocaching/models/Download.java, main/src/main/res/drawable/downloader_needsupdate.xml, main/src/main/res/drawable/downloader_ok.xml, main/src/main/res/layout/downloader_item.xml
Adds a badge to existing downloads' symbols in the download selector, 
- either green - download already exists and is up to date
- or yellow - download exists, but an update is available
(Additionally adds some descriptive texts for easier debugging - implements `toString()` for `Download` and `DownloadedFileData`)
=> Download selector: Highlight existing downloads (fix #14819)

main/src/main/java/cgeo/geocaching/maps/RouteTrackUtils.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/ElevationChart.java, main/src/main/res/layout/routes_tracks_item.xml, main/src/main/res/menu/map_routetrack_context.xml, main/src/main/res/values/strings.xml
- shows popup menu when doing a long-tap on individual route, supporting edit, show/hide, center for now
- adds an overflow menu to elevation chart with the same entries
currently implemented for individual route only, partly prepared for tracks (but no items yet)
=> Context menu for routes/tracks on map and elevation chart

main/src/main/java/cgeo/geocaching/maps/MapUtils.java, main/src/main/res/layout/popup.xml, main/src/main/res/layout/waypoint_popup.xml
The hint got cut off inside the popup. Fix this by adding a ViewTreeObserver and recalculate PeekHeight.
=> Avoid hint cutoff

main/src/main/java/cgeo/geocaching/ui/dialog/SimpleDialog.java, main/src/main/java/cgeo/geocaching/utils/FilterUtils.java
fix #14856: re-add clear button to map long-press filter select dialog
=> fix #14856: re-add clear button to map long-press filter select dialog

gradle.properties, main/build.gradle
Since Gradle 7.6 it is possible to use a configuration cache to speed up the build time.
It was necessary to rework some tasks to be able to work use configuration caching. Additionally The code was a bit optimized.
=> use configuration cache

main/src/main/java/cgeo/geocaching/AbstractDialogFragment.java
apply the same tweak we use for CacheDetails to show more toolbar icons also to CachePopup and WaypointPopup.
Causes the toolbar to show up to 4 icons instead of 2 (if there's space)
=> more toolbar icons for Cache/Waypoint Popup

main/src/main/java/cgeo/geocaching/AbstractDialogFragment.java, main/src/main/java/cgeo/geocaching/ui/CacheDetailsCreator.java, main/src/main/res/values/strings.xml
Applies compact D/T line for the new cache details view in maps, as discussed in yesterdays's dev meeting.
(D/T only, no FP part)
=> Use compact D/T view for cache details in map

main/src/main/res/layout-land/unifiedmap_activity.xml
We forgot to include `@layout/map_detailsfragment` in unified map landscape...
=> [unified map] fix cache/WP popup in landscape

main/src/main/java/cgeo/geocaching/MainActivity.java, main/src/main/java/cgeo/geocaching/permission/PermissionContext.java, main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/java/cgeo/geocaching/settings/SettingsActivity.java, main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceAppearanceFragment.java, main/src/main/res/values/strings.xml, main/src/main/res/values/themes.xml
Triggered by a ticket on support (c:geo requesting READ_EXTERNAL_PERMISSION without having a setting for it) I dived into requirements for wallpaper. Currently we are reading the wallpaper as an image file from external storage (which requires this permission), but apparently there is a way to show the wallpaper without the need of manually reading the image file, just by adding an option to the theme.
=> Show wallpaper without need for READ_EXTERNAL_STORAGE permission

main/src/main/java/cgeo/geocaching/maps/DefaultMap.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapType.java
Support starting UnifiedMap via bottom navigation, if `useUnifiedMap` is enabled
=> UnifiedMap: Support start via bottom navigation (fix #14895)

main/build.gradle
see https://github.com/cgeo/cgeo/pull/13969
For ReleaseNotes see https://developer.android.com/jetpack/androidx/releases/browser#version_15_2
Important changes since 1.4.0
- Added CustomTabsIntent.Builder#setInitialActivityHeightPx, which allows developers to specify the initial launch height of a Custom Tab, and optionally the resize behavior (fixed or resizable).
- Added CustomTabsIntent.Builder#setToolbarCornerRadiusDp which allows developers to specify the toolbar's top corner radius. 
- Added CustomTabsIntent.Builder#setCloseButtonPosition which allows developers to set the position of the close button on the toolbar. 
- Added an onActivityResized callback method to interface CustomTabsCallback to let developers know when a Custom Tab is resized. 
- Make parts of CustomTabsCallback …
=> Bump androidx.browser:browser from 1.4.0 to 1.5.0

main/src/androidTest/java/cgeo/geocaching/utils/FormatterTest.java, main/src/main/java/cgeo/geocaching/utils/Formatter.java, main/src/main/res/layout/popup.xml, main/src/main/res/values/strings.xml
As discussed in our last dev meeting here's a small proposal for rearranging the buttons in cache bottom sheet. It's for discussion only for now, therefore not yet implemented for cache details activity (where it probably should look the same as here).
Changes are:
- Move "More details" button (with optional hint button) to the end
- Move "Edit lists", "Refresh", "Delete" and "Store" buttons into a single horizontal row. (As it can be either "Store" or "Delete", a maximum of three buttons is displayed here)
- Text for "stored ago" and "lists" go to the left of those buttons
- Text for "stored ago" is a bit shortened and without line break
- On enabling hint this will be displayed between the row with the small buttons and the large "More details" button, divided by a separator, so that …
=> Rearrange buttons in cache bottom sheet

main/src/main/java/cgeo/geocaching/models/geoitem/GeoIcon.java, main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GoogleV2GeoItemLayer.java, main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeVtmGeoItemLayer.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/PositionLayer.java
I tried my best to extend geoItemLayer to our requirements, and implement this styling flag in VTM and gmapV2. It's not necessary to implement it for old mapsforge, as that map cannot be rotated at all, so this flag is useless.
@eddiemuc I would aprechiate a short review. thx!
=> introduce flat marker mode (fix #14479)

main/src/main/java/cgeo/geocaching/maps/routing/Routing.java
Prevent NPE in `getElevation()` when routing service is not yet connected
=> Fix cause for NPE in getElevation()

main/src/main/java/cgeo/geocaching/maps/MapUtils.java, main/src/main/res/layout-land/map_detailsfragment.xml
Cache/waypoint side sheet (landscape format):
- Don't show 'swipe to open'
- Make free space below side sheet touchable (to allow map movements on tablets)
=> Don't show 'swipe to open' in landscape format (fix #14982)

main/src/main/res/values/strings.xml, main/src/main/res/xml/preferences_map_sources.xml
Removes the "experimental" warnings in settings' category and detail description and adds a "beta" note to the category name
=> UnifiedMap: Replace 'experimental' warning with 'beta' info

main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java
Fixes mapping a single cache (without waypoints) or waypoint for UnifiedMap VTM.
(Does NOT fix mapping a list or a cache having waypoints, so NOT fixing zooming to bounds which are an area, not a point)
=> UnifiedMap: Fix single cache zoom (rel. to #15003)

main/src/androidTest/java/cgeo/geocaching/connector/gc/GCLogAPITest.java, main/src/androidTest/java/cgeo/watchdog/WatchdogTest.java
rel to #2012: activate gc logging api unit tests in Watchdog Tests
This PR will activate the GC Logging API Unit tests on c:geo CI inside Watchdog Tests. 
This means that on each CI Watchdog test run a series of cache/trackable log create/edit/delete events it executed by the gc test user configured in CI. Other CI runs (e.g. PR request runs) are not affected
=> rel to #2012: activate gc logging api unit tests in Watchdog Tests

main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/IProviderGeoItemLayer.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java, main/src/main/java/cgeo/geocaching/utils/AsynchronousMapWrapper.java
rel to #14948: unified map: put another animation before bound animation to avoid missing map width/height
=> rel to #14948: unified map: put another animation before bound animation to avoid missing map width/height

main/src/androidTest/java/cgeo/geocaching/connector/gc/GCParserTest.java, main/src/main/java/cgeo/geocaching/connector/gc/GCConstants.java, main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java
fix #15043: adapt scan pattern for gc.com cache inventory
Fix will aloow to scan for both "old" pattern and "new" pattern on gc.com pages. Inventory is filled again, and TBs can be accessed from it:
=> fix #15043: adapt scan pattern for gc.com cache inventory

main/src/main/java/cgeo/geocaching/activity/AbstractNavigationBarActivity.java
fix #15054: prevent npe in AbstractNavigationBarActivity when broadcast before view initialization
=> fix #15054: prevent npe in AbstractNavigationBarActivity when broadcast before view initialization

main/src/androidTest/res/raw/log_with_2tb.htm, main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java, main/src/main/res/layout/logcache_activity.xml, main/src/main/res/layout/logtrackable_activity.xml
Increase log length to 5000 characters
Since 2 November 2023 the allowed log length has been increased to 5000 characters.
See also:
https://forums.geocaching.com/GC/index.php?/topic/394827-release-notes-website-new-geocache-and-trackable-logging-flow-november-2-2023/
=> Increase log length to 5000

main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceMapContentBehaviorFragment.java, main/src/main/java/cgeo/geocaching/utils/MapMarkerUtils.java, main/src/main/res/values/preference_keys.xml, main/src/main/res/values/strings.xml, main/src/main/res/xml/preferences_map_content_behavior.xml
as discussed in yesterday's dev meeting
marked as WIP
Setting is configurable in settings => map content & behavior => waypoints
Edit: to be discussed, whether the little green check mark should still be displayed, if semi-transparency is configured
=> Mark visited waypoints with semi-transparent bg (optional)

main/AndroidManifest.xml, main/build.gradle, main/src/debug/res/values/strings_debug.xml, main/src/main/java/cgeo/geocaching/settings/ViewSettingsActivity.java, main/src/main/java/cgeo/geocaching/utils/ApplicationSettings.java, main/src/main/java/cgeo/geocaching/utils/BackupUtils.java
From time to time I need to debug some code on my primary device which is a real hassle currently. This PR makes our manifest app id independent (use relative names and remove unnecessary usage of parent activity flag) and adds a applicationIdSuffix to developer builds. This allows c:geo dev builds to be installed in parallel to the main version.
=> use different app id for debug builds

main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceMapSourcesFragment.java, main/src/main/res/xml/preferences_map_sources.xml
While debugging a different issue I found Google Maps on that specific emulator always crashing, but I had no (easy) way to select a different tile provider for UnifiedMap (Settings => Map sources => Select Map Source is for the old map implementation only). This PR adds an option to the UnifiedMap section in Settings => Map Sources where the user can select a different tile provider (externally called "Map Source")
=> UnifiedMap: Add tile provider selection in settings

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
Got a user on support who claimed not seeing a map selection menu in UnifiedMap. After some investigation I could reproduce this error on a device with a small screen, that lead to the "map selection" icon being put into the overflow menu (instead of the taskbar), thus it could no longer function as a view anchor for the tileprovider popup menu. This PR creates a mitigation for this situation.
=> UnifiedMap: Fix missing map selection on small screens

main/src/main/java/cgeo/geocaching/settings/fragments/BasePreferenceFragment.java, main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceMapSourcesFragment.java, main/src/main/res/values/preference_keys.xml, main/src/main/res/xml/preferences_map_sources.xml
Cleanup for settings with regard to UnifiedMap:
- show UnifiedMap settings in basic settings mode
- special handling for `showUnifiedMap` and `useUnifiedMap` no longer needed in settings, as UnifiedMap is published to nightlies meanwhile
=> UnifiedMap: Cleanup settings

main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/AbstractMapsforgeOfflineTileProvider.java, main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/MapsforgeMultiOfflineTileProvider.java
Do not adjust map boundaries on VTM tilesource change to include current map position (which may be 0/0 on initially opening the map!) - position & zoom level get restored in a different place
=> UnifiedMap: Avoid zooming out extremely on map start (fix #15040)

main/src/main/java/cgeo/geocaching/AbstractDialogFragment.java, main/src/main/java/cgeo/geocaching/WaypointPopupFragment.java
Currently cache/waypoint sheet stays open after opening cache details from sheet info, thus it will be visible again after closing the cache details. This PR fixes this behavior.
=> Close cache/waypoint sheet on opening cache details

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
Displaying a cache list should take the "zoom includes waypoints" setting into account when calculating zoom level / bounds.
This is related to #15033 (and should actually fix the "waypoints out of viewport" part), ~but VTM seems to zoom to different bounds than the ones given (not fully including the bounds given). Need to investigate further for that part, but this PR is meaningful anyway.~
=> UnifiedMap: Respect 'zoom includes waypoints' setting for search results

main/src/main/java/cgeo/geocaching/activity/AbstractNavigationBarMapActivity.java
Since retaining cache/waypoint sheet state on rotation etc., sheet was also recreated when returning from `CacheDetailsActivity` called by swiping up in the sheet. - This PR fixes this by (delayed) closing the sheet after starting `CacheDetailsActivity` on swipe-up.
=> sheet info: (Delayed) close on swipe-up

main/src/main/java/cgeo/geocaching/maps/routing/Routing.java
Apply own package name (which is non-constant since support of dual installations) when connecting to internal routing service
Related to #15101
=> Fix internal brouter connection for dual installations

main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java
Adds some margin to `zoomToBounds` for UnifiedMap VTM
(Google Maps does this implicitly, so it needs to be implemented in a map-specific way.)
=> UnifiedMap VTM: Add margins to zoomToBounds (fix #15033)

main/src/main/java/cgeo/geocaching/utils/MapMarkerUtils.java
Attempts to fix the artefacts described in #15084, but still shows some of them (therefore marked as draft).
Even though the created waypoint marker gets marked as mutated (which marks all elements of the `LayerDrawable` as mutated) still somehow the marker displayed on the map switches to a semi-transparent one.
Details / test case:
- Have "semi transparency for visited waypoints" enabled
- Display a map with visited and unvisited waypoints
- Even if a waypoint of an unvisited waypoint may be ok in the beginning, it switches to being marked as visited (with semi-transparency) after some time, if you open and close this marker. It looks like once there has been a single waypoint marker with semi-transparency, all waypoint markers being drawn after that one get semi-transparency as well, …
=> Mark waypointMarker as mutated

build.gradle, main/build.gradle, main/src/main/java/cgeo/geocaching/CgeoApplication.java, main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeVtmGeoItemLayer.java
fix #15029: stops rendering of dark edges, stops painting routes when zooming out
Note: this PR links c:geo to Snapshot libraries of VTM because the changes needed on VTM side are not yet in its latest release
=> fix #15029: stops rendering of dark edges, stops painting routes when zooming out

main/src/main/java/cgeo/geocaching/maps/CGeoMap.java, main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java, main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapView.java, main/src/main/java/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java, main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/java/cgeo/geocaching/unifiedmap/LocUpdater.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java, main/src/main/res/menu/map_activity.xml, main/src/main/res/values/preference_keys.xml, main/src/main/res/values/strings.xml
Add support for "Autorotation (precise)" and "Autorotation (low power)" modes 
- "precise" = updates every 80ms / min heading diff = 1° (downgrades to default mode, if speed > 5 km/h or no speed readings)
- "low power" = updates every 500ms / min heading diff = 10°
Implemented for UnifiedMap only, other maps use "low power" mode.
@fm-sys / @eddiemuc 
I've tried to implement the different suggestions, but please cross-check if your needs are covered.
=> UnifiedMap: Support precise & low poper map autorotation modes

main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java
=> UnifiedMap VTM: Skip animation on zoomToBounds

main/src/main/java/cgeo/geocaching/maps/DefaultMap.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapType.java
Up until now UnifiedMap only supported geocaches as targets, and even if selected navigation to a waypoint, it chose the waypoint's geocache's coordinates as target. This PR fixes this behavior.
=> UnifiedMap: Support waypoints as targets

main/src/main/java/cgeo/geocaching/downloader/CompanionFileUtils.java
Prevents the crash in #15130 (trying to read a companion file that can be seen via SAF, but cannot be read)
=> Catch NPE on reading companion file that's currently unavailable

main/build.gradle
see https://github.com/FasterXML/jackson/wiki/Jackson-Releases and https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.13
Higher versions of Jackson need minSdk 26.
=> Update jacksonVersion from 2.12.5 to 2.13.5

main/src/main/java/cgeo/geocaching/downloader/AbstractDownloader.java, main/src/main/java/cgeo/geocaching/downloader/DownloaderUtils.java, main/src/main/java/cgeo/geocaching/downloader/MapDownloaderOpenAndroMaps.java, main/src/main/java/cgeo/geocaching/downloader/ReceiveDownload.java, main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/res/values/preference_keys.xml, main/src/main/res/values/strings.xml, main/src/main/res/xml/preferences_map_sources.xml
Optionally keep temporary downloaded files, but only for map sources that support this (currently OAM maps only).
Setting for this is in settings => map sources => keep temporary files (visible in extended settings mode only).
=> Downloader: Optionally keep temporary files for further processing

main/src/main/java/cgeo/geocaching/SwipeToOpenFragment.java, main/src/main/res/drawable/rounded_corners_top.xml, main/src/main/res/layout-land/swipe_up_indicator.xml, main/src/main/res/layout/fragment_swipe_to_open.xml, main/src/main/res/layout/popup.xml, main/src/main/res/layout/swipe_up_indicator.xml, main/src/main/res/layout/waypoint_popup.xml
Related to #14881 
Adds a "swipe up" indicator to cache/waypoint info sheet (in portrait mode only)
=> Info sheet: Add swipe up indicator

main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/PositionLayer.java
Adds checks for arrow dimensions to let the user continue using the map even when rotation arrow is missing.
It's just a mitigation for #15158, but won't close it,
=> NewMap: Prevent crash on missing rotation arrow

main/src/main/java/cgeo/geocaching/SearchActivity.java
Mitigation for #13312 for gc.com-only users:
Disables keyword search for a user, if he/she is a gc.com basic member and only active connectors are gc.com and/or lab adventures.
=> Disable keyword search for gc.com basic members

main/src/main/java/cgeo/geocaching/utils/BackupUtils.java
Related to https://github.com/cgeo/cgeo/issues/15160#issuecomment-1877772111
Uploading a database file using Android Studio did assign a date/time stamp of "0" - which is the same value BackupUtils use internally as "file not accessible". Which lead to me not being able to read such modified backups.
This PR changes the "file not accessible" flag to "-1" and uses a constant throughout BackupUtils.
=> Enable restoring of backups date/time property set to 0

main/src/main/java/cgeo/geocaching/ui/ViewUtils.java, main/src/main/java/cgeo/geocaching/utils/MapMarkerUtils.java, main/src/main/java/cgeo/geocaching/utils/builders/InsetBuilder.java, main/src/main/java/cgeo/geocaching/utils/builders/InsetsBuilder.java
fix #15169: redesign MapMarkerUtils/InsetBuilder to mutate all created drawables
This PR refactors MapMarkerUtils (and the InsetBuilder-classes) to mutate ALL "base" drawables used in the markers on the point of their creation. This should be ok memory-wise because the created markers are always cached and reused anyway.
@moving-bits , @ztNFny since you are the experts in these classes, I would be glad if you could take a look at the code
=> fix #15169: redesign MapMarkerUtils/InsetBuilder to mutate all created drawables

main/src/main/java/cgeo/geocaching/maps/RouteTrackUtils.java, main/src/main/res/values/strings.xml
PR fixes some minor issues in routes / tracks popup dialog
* use translatable string for the title of the dialog to change the name
* update visibility after hide / show a loaded track
no one yet, but I can create one
* The title of the dialog for changing the name of a loaded track (long click on track name) was not translated
* The state of the "visibility"-button is not updated, when clicking on it
=> fix some issues in routes / tracks popup dialog

main/AndroidManifest.xml
Implicitly fixes #15120
Instead of messing around with the fragments (;-)) I took a different path: 
The blank sheet effect is caused by the keyboard which takes some time to vanish. By specifying that the activity should be rendered below the keyboard, the blank sheet bug will no longer happen.
I applied this change only to the map activities, as it would make some activities unusable. (e.g. the text fields in "search" wouldn't be accessible). However, I couldn't find such problems in our map activity. We only use the keyboard in some text input dialogs, but they are placed properly at the screen even with this PR applied.
=> Don't adjust activity layout according to keyboard

cgeo-contacts/build.gradle, main/build.gradle, ruleset.xml
Codacy did not detect our `pmd-ruleset.xml`.
I found in the codacy docs (https://docs.codacy.com/v6.0/repositories-configure/configuring-code-patterns/), that this name is not supported. We have to use `ruleset.xml`
=> rename pmd ruleset

main/src/main/java/cgeo/geocaching/downloader/AbstractDownloader.java, main/src/main/java/cgeo/geocaching/downloader/DownloaderUtils.java, main/src/main/java/cgeo/geocaching/downloader/MapDownloaderFreizeitkarte.java, main/src/main/java/cgeo/geocaching/downloader/MapDownloaderHylly.java, main/src/main/java/cgeo/geocaching/downloader/MapDownloaderOSMPaws.java, main/src/main/java/cgeo/geocaching/downloader/MapDownloaderOpenAndroMaps.java
When map downloaded initiates a map download, it also checks for required theme file. If that cannot be found, it initiates that download as well.
For Hylly, it used a fixed url prefix for the theme file, but their website now (?) placed the files into the same subfolder as the map, so let's use that one.
=> Fix Hylly theme download error 404 (fix #11793)

checkstyle.xml
updates checkStyle config:
- missing final on method parameter => severity warning instead of info
- missing final on local variable => severity warning instead of info
- import order => severity warning instead of info
- nested ifs: allow 2 (instead of default 1)
do not merge, PR contains some test bugs
fixes #15142
=> Update CheckStyle config

main/src/main/java/cgeo/geocaching/ui/ImageActivityHelper.java
fix #15195: allow only certain image mime types for image selection in c:geo
=> fix #15195: allow only certain image mime types for image selection in c:geo

main/src/main/java/cgeo/geocaching/utils/BackupUtils.java, main/src/main/res/values/strings.xml
Includes active track files into database backup/restore.
"active" meaning: those, which are selected for display on the map, disregarding their enabled/disabled state.
(Contents of configured GPX folder are not backed up by this feature.)
Backup/restore is performed when database gets backed up or restored, no separate selection for track files provided. (This is intentionally, as "active" track files are referenced in the database, and this data should be kept in sync.)
=> Include active trackfiles in backup (rel. to #14706)

main/src/main/java/cgeo/geocaching/utils/formulas/FormulaFunction.java, main/src/main/java/cgeo/geocaching/utils/formulas/FormulaUtils.java, main/src/main/res/values/strings.xml
fix #15138: add a new formula function to select multiple single chars:
=> fix #15138: add a new formula function to select multiple single chars

main/src/main/java/cgeo/geocaching/utils/config/JsonConfigurationUtils.java
fix #15236: re-enable start on filter name for unsaved changes
=> fix #15236: re-enable star on filter name for unsaved changes

main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java
To apply theme option changes, we had a `applyTheme` in `onStart`, which led to `applyTheme` being called twice on map startup. This PR fixes this.
=> UnifiedMap VTM: apply theme only when necessary

main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java
fix #15254: make reuse last log work again on immediate log send
=> fix #15254: make reuse last log work again on immediate log send

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
When using a waypoint as target, center map on it (in contrast to mapping a geocache, which zooms to boundaries of cache including waypoints (if configured)).
Related to support ticket 261131
=> UnifiedMap: Set waypoint as center in target mode

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
viewModel.waypoints seems to require a `notifyDataChanged()` after adding a waypoint to display it (at least in some cases / on some devices)
Related to #15137
=> UnifiedMap: Try to fix missing waypoint display on setting as target

main/src/main/res/values/strings.xml
Shorten map titles from "Live map" to "Live" and from "Offline map" to "Offline", as proposed in the related issue.
=> Shorten map titles to 'Live' and 'Offline' (fix #14369)

main/src/main/java/cgeo/geocaching/SearchActivity.java
Search page's geocode search and keyword search both get reset to "GC" after starting a search, which doesn't make sense for the keyword field. This PR fixes that by emptying the keyword field after starting a search.
=> Reset keyword search to empty (fix #14280)

main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/RenderThemeSettingsFragment.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeThemeSettingsFragment.java
Reduce map scale slider range to what we allow for cache markers. (fix #14965)
=> Harmonize map scale slider range

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
In some situations mapping a cache with waypoints those did not become visible immediately, but only after performing some other action (like opening and closing quick settings).
This PR adds a change notification to resolve this.
related to support ticket 502852
=> UnifiedMap: Notify on waypoint list change

main/AndroidManifest.xml, main/src/main/java/cgeo/geocaching/settings/SettingsActivity.java, main/src/main/res/raw/changelog_base.md, main/src/main/res/values/strings_not_translatable.xml
Allows deep linking to specific c:geo settings. Useful for linking from changelog / manual / FAQ to a certain setting.
Format is `cgeo-setting://<prefkey>`, eg.: `cgeo-setting://theme_setting` for theme switching etc.
This PR also links the changelog entry about UnifiedMap to the switch for enabling/disabling UnifiedMap.
=> Enable linking to specific preferences

main/src/main/java/cgeo/geocaching/utils/formulas/DegreeFormula.java, main/src/test/java/cgeo/geocaching/utils/formulas/DegreeFormulaTest.java
fix #15287: interpret heimsphere letters as vars in middle of formula
=> fix #15287: interpret heimsphere letters as vars in middle of formula

main/src/main/java/cgeo/geocaching/utils/SystemInformation.java, main/src/main/java/cgeo/geocaching/utils/UriUtils.java
Shortens system info, partly for privacy reasons:
- only LIVE and OFFLINE filters are documented, for stored filters we show only the amount
- shorten PATH info (printable Uri and some stats)
|before|after|
|---|---|
|![image](https://github.com/cgeo/cgeo/assets/3754370/869070c8-deab-4e46-b182-0a90f1a9f12a)|![image](https://github.com/cgeo/cgeo/assets/3754370/71e5a743-78b7-43f2-b110-f09342808b27)|
=> Shorten system info for filters and paths (fix #10411)

main/src/main/res/layout/simpleitemlist_view.xml
fix #15276: show scrollbar on long item selection lists
=> fix #15276: show scrollbar on long item selection lists

main/src/main/java/cgeo/geocaching/activity/AbstractNavigationBarMapActivity.java
Tries to fix the crash on info sheet removal by force-commiting and allowing state-loss.
Related to (and hopefully fixes) issue #15247.
Closes #15311 (for a short discussion see over there)
=> Try to fix sheetRemoveFragment crash (rel. to #15247)

main/src/main/java/cgeo/geocaching/models/Geocache.java, main/src/main/java/cgeo/geocaching/models/Image.java, main/src/main/java/cgeo/geocaching/utils/ImageUtils.java
Recognizes image URLs in personal note and add them to images tab, treating them the same as Listing / Log images.
- Image URLs are recognized using a regex.
- Because of this the URL must contain .(jpeg|jpe|jpg|png|webp|gif|svg)
- Performance shouldn't be an issue as notes are limited to 2500 chars on GC, longer notes could appear in c:geo but are unlikely
- I added a new category "Personal Note" to images tab
- not sure whether that is needed or they should go into the existing "Own", but the images in that category are editable from the images tab, so they are different in behaviour.
- The category is placed below Own, before Listing, as I think those images are more likely to be needed than listing images
=> show images linked in "personal note" in Images tab

main/build.gradle, main/src/main/java/cgeo/geocaching/CgeoApplication.java, main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeVtmGeoItemLayer.java
rel to #15029: set vtm transparent attribute on a per-line basis
This PR upgrades VTM to latest version on VTM master, in order to use new "per-line" transparency flag (see VTM  https://github.com/mapsforge/vtm/pull/1100)
=> rel to #15029: set vtm transparent attribute on a per-line basis

main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java
Fix compass rose not turning accordingly on device rotation.
VTM seems to send a `Map.POSITION_EVENT` only if both position and rotation changes, so we need to update compass rose on both events.
=> UnifiedMap VTM: Fix compass rose orientation (fix #15297)

main/src/main/java/cgeo/geocaching/unifiedmap/AbstractMapFragment.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsFragment.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java
Workaround related to #15100 ("black boxes" in @murggel's use case)
@ztNFny @murggel 
Can you please retest your "black boxes" use-cases with this build?
It's up to current `release` branch with those few changes seen below, and for me the black boxes do not appear in the described use-case any longer.
=> UnifiedMap VTM: Don't reset tilesource on enabling live mode

main/src/main/java/cgeo/geocaching/Intents.java, main/src/main/java/cgeo/geocaching/maps/CGeoMap.java, main/src/main/java/cgeo/geocaching/maps/DefaultMap.java, main/src/main/java/cgeo/geocaching/maps/MapOptions.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/caches/CachesBundle.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/caches/SinglePointOverlay.java
Add WP prefix to the intent, so that the old map implementations have stage number available when creating the single waypoint target icon.
(UnifiedMap is not affected, as it puts the whole waypoint into the intent, not just coords and geocode)
=> Fix linear WP losing its number on setting as target (fix #15210)

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
Show bottom navigation in UnifiedMap, when hitting the "map" icon after a successful address search (and thus entering map in "coords target" mode)
=> UnifiedMap: Show bottom navigation in 'coords target' mode

main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GoogleV2GeoItemLayer.java, main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeVtmGeoItemLayer.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/TracksLayer.java, main/src/main/java/cgeo/geocaching/utils/MapLineUtils.java
Align display of geojson between Google Maps and OSM.
#15333 mentions 2 issues:
detail-level of the polygons:
I addressed this by setting dropDistance() to 1 instead of 2
display-style of polygons:
- strokeWidth() was divided by 2, I removed that division. The removed division leads to track lines being twice as wide now though (see screenshot below), seems they don't get the same width set as before?
- fill alpha was applied twice. fillAlpha() applies it from the fill color, but that already includes the alpha (caluclated in GeoJsonUtils.colorFromJson()), so we get alpha = alpha * alpha.
Either fillColor() needs to get only the rgb component of the argb value or - what I did in the current state of the PR or set fillColor() to the value without alpha: …
=> fix #15333: geojson display on unifiedmap

main/src/main/java/cgeo/geocaching/filters/core/BooleanGeocacheFilter.java, main/src/main/java/cgeo/geocaching/filters/core/GeocacheFilterType.java, main/src/main/java/cgeo/geocaching/filters/core/IndividualRouteGeocacheFilter.java, main/src/main/java/cgeo/geocaching/filters/gui/BooleanFilterViewHolder.java, main/src/main/java/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java, main/src/main/res/values/strings.xml
Implements a "contained in individual route" filter, like suggested in #11532.
I've abstracted a generic `BooleanGeocacheFilter`, so that we can potentially split up our way too long status filter in a next step.
=> Add "contained in individual route" filter (fix #11532)

main/src/main/java/cgeo/geocaching/ui/TextParam.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/UnifiedTargetAndDistancesHandler.java
The icon for the currently selected navigation method in large view is overly large, adjust it to text height
Before
After
=> current navigation method icon shouldn't be larger than text

main/src/main/java/cgeo/geocaching/connector/al/ALApi.java, main/src/main/java/cgeo/geocaching/connector/al/ALConnector.java, main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/res/values/preference_keys.xml, main/src/main/res/values/strings.xml, main/src/main/res/xml/preferences_services_geocaching_com_adventure_lab.xml
Back while we weren't aware of methodically retrieving the true found state of a LC in the context of a logged in user, we had controls to manually set the found state to either `found it` or `did not find`.  A few months ago we found appropriate  API methods to determine that state and consequently the explicit controls via the UI are no longer necessary.
This PR implements a change to turn those controls off.
=> supportSettingFoundState - ssue #14672

main/src/main/java/cgeo/geocaching/brouter/core/OsmTrack.java
see discussion in https://github.com/cgeo/cgeo/issues/14759#issuecomment-1958864817
=> Internal routing: Don't throw exception on error while reading rawtrack

main/src/main/java/cgeo/geocaching/connector/internal/InternalConnector.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
`NewMap` does a complete reload of all layers, including `StoredOverlay` in `onResume()`. `UnifiedMap`doesn't do this, but on the downside needs to be notified of new UDC.
=> UnifiedMap: Reload caches/waypoints in onResume (fix #15341)

main/src/androidTest/java/cgeo/geocaching/CgeoApplicationTest.java, main/src/main/java/cgeo/geocaching/EditWaypointActivity.java
Looks like GC has fixed the "TB spotted" links on the TB page (*), so add GC code to the now failing test.
(*) not sure if only on some machines or already system-wide, haven't received a reply from GC yet, thus keeping the related issue open for now.
=> Fix TB spotted test

main/src/main/java/cgeo/geocaching/ui/ViewUtils.java
Reported on support: "search by coordinates" crashes the app when called without having entered coordinates before. This used to work. (ticket 897982)
Caused by c97a75c022e21c3e098643b3f055674f919f6d5c (which removed an array length check in calling method) and fixed with this PR.
=> Fix search by coordinates with empty coordinates

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
Puts loading of caches and waypoints into background for map types `UMTT_List` and `UMTT_SearchResult` (= loading of lists of caches)
=> UnifiedMap: put loading caches for lists into background (fix #15389)

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
The setting "Show routing menu" (enabled by default) allows users to disable the long-tap menu on map, thus adding/removing caches to the route quickly. On unified map that setting is ignored for all caches that have a waypoint (= for most caches) due to https://github.com/cgeo/cgeo/pull/14993
This PR makes unified map respect the users choice in all cases.
=> respect "Show routing menu" setting

main/src/main/res/layout/authorization_credentials_activity.xml, main/src/main/res/layout/authorization_token_activity.xml, main/src/main/res/layout/calculatedcoordinate_input_guide.xml, main/src/main/res/layout/coordinates_input.xml, main/src/main/res/layout/coordinates_input_single.xml, main/src/main/res/layout/coordinatescalculateglobal_dialog.xml, main/src/main/res/layout/dialog_edittext.xml, main/src/main/res/layout/editwaypoint_activity.xml, main/src/main/res/layout/formula_edittext_view.xml, main/src/main/res/layout/fragment_edit_note.xml, main/src/main/res/layout/gpx_export_individual_route_dialog.xml, main/src/main/res/layout/imageedit_activity.xml, main/src/main/res/layout/logcache_activity.xml, main/src/main/res/layout/logtrackable_activity.xml, main/src/main/res/layout/simple_dialog_title_view.xml, main/src/main/res/layout/simple_dialog_view.xml, main/src/main/res/layout/template_preference_dialog.xml, main/src/main/res/layout/udc_create.xml, main/src/main/res/layout/variable_list_item_advanced.xml, main/src/main/res/layout/variable_list_item_minimalistic.xml, main/src/main/res/layout/view_settings_add.xml, main/src/main/res/layout/wherigo_thing_details.xml
Use TextInputEditText instead of plain EditText when nested within TextInputLayout (fix #15357)
=> Use TextInputEditText instead of plain EditText

main/src/main/java/cgeo/geocaching/CacheListActivity.java, main/src/main/java/cgeo/geocaching/CacheListSpinnerAdapter.java, main/src/main/java/cgeo/geocaching/list/StoredList.java, main/src/main/java/cgeo/geocaching/ui/SimpleItemListModel.java, main/src/main/java/cgeo/geocaching/ui/SimpleItemListView.java, main/src/main/java/cgeo/geocaching/ui/TextSpinner.java, main/src/main/java/cgeo/geocaching/utils/CommonUtils.java, main/src/main/java/cgeo/geocaching/utils/formulas/FormulaUtils.java, main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java, main/src/test/java/cgeo/geocaching/utils/CommonUtilsTest.java
fix #15194, fix #15363: autogroup list by name part, add list icon to list spinner
This PR tries to resolve the mentioned feature request by auto-grouping all stored list names after the name part before the first found `-` character. This may e.g. look like this:
With groups deflated:
=> fix #15194, fix #15363: autogroup list by name part, add list icon to list spinner

main/AndroidManifest.xml
Related to #14619
One of the requirements for SDK34 update is to declare the service type for all services used by our app, see [foreground service type](https://developer.android.com/about/versions/14/behavior-changes-14#fgs-types)
=> SDK34: Add foreground service types

main/src/main/res/drawable/expand_collapsed.xml, main/src/main/res/layout/simpleitemlist_item_view.xml
change the "collapsed" icon in simple dialog groups from up-arrow to right-arrow
new:
old:
=> change collapsed group icon to right-arrow instead of up-arrow

main/src/main/java/cgeo/geocaching/utils/ImageUtils.java
use BitmapCompat instead of Bitmap for scaling (log) images as it provides much higher quality images (that are also smaller)
Before:
After:
=> use BitmapCompat for scaling log images

main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/RenderThemeSettingsFragment.java, main/src/main/java/cgeo/geocaching/settings/BackupSeekbarPreference.java, main/src/main/java/cgeo/geocaching/settings/SeekbarPreference.java, main/src/main/java/cgeo/geocaching/settings/fragments/BasePreferenceFragment.java, main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceNavigationFragment.java, main/src/main/java/cgeo/geocaching/ui/ProximityPreferenceUI.java, main/src/main/java/cgeo/geocaching/ui/SeekbarUI.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeThemeSettingsFragment.java, main/src/main/res/layout/preference_generic_extendable.xml, main/src/main/res/layout/seekbar.xml, main/src/main/res/values/attrs.xml, main/src/main/res/values/preference_keys.xml, main/src/main/res/xml/preferences_appearence.xml, main/src/main/res/xml/preferences_backup.xml, main/src/main/res/xml/preferences_map_content_behavior.xml, main/src/main/res/xml/preferences_map_sources.xml, main/src/main/res/xml/preferences_navigation.xml, main/src/main/res/xml/preferences_services.xml
- splits `SeekbarPreference` into pref & UI parts (to be able to use seekbar preferences in both xml preferences and programmatically)
- adds support for title/summary fields in custom preferences (getting rid of some plain preferences used for title/summary only)
- provides a `preference_generic_extendable.xml` layout file for extendable preference layouts
(sorry, no `ContinuousRangeSlider` integration yet)
=> Split SeekbarPreference into pref & UI parts (fix #15372)

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
When selecting a different filter this new filter seems to be applied on top of the old one. This PR fixes that by reloading all caches, making applying a new and clearing a filter work as expected.
=> re-add all caches to map before applying a new filter (fixes #15399)

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java, main/src/main/java/cgeo/geocaching/CachePopupFragment.java, main/src/main/java/cgeo/geocaching/ui/dialog/EditNoteDialog.java, main/src/main/res/drawable/ic_menu_note.xml, main/src/main/res/drawable/ic_menu_note_edit.xml, main/src/main/res/layout/popup.xml
add a "Edit personal note" button to CachePopup for quick access to editing the note.
As all the "storing the note and handling updates" stuff is in CacheDetailActivity, not in EditNoteDialog, an intermediate CacheDetailActivity is started and finished.
=> add "Edit Personal Note" button to CachePopup

main/src/main/java/cgeo/geocaching/CgeoApplication.java, main/src/main/java/cgeo/geocaching/settings/fragments/BasePreferenceFragment.java, main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceAppearanceFragment.java, main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceMapSourcesFragment.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeThemeHelper.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeThemeSettingsFragment.java, main/src/main/res/values/preference_keys.xml, main/src/main/res/values/strings.xml, main/src/main/res/xml/preferences_appearence.xml
- re-adds userScale for VTM, and makes text scale / symbol scale global (instead of theme-specific)
- settings are in settings => appearance => unified map
- changing any of those three settings forces an app restart on closing the settings activity
- setting gets applied in CGeoApplication
=>  UnifiedMap VTM: make map scales global (fix #15059)

main/src/main/java/cgeo/geocaching/EditWaypointActivity.java
If you add projection to a predefined waypoint, it will not be shown an reopening the waypoint.
Steps to reproduce:
add projection to a predefined waypoint
save the waypoint
reopen the waypoint => "no projection" is selected in the spinner
=> don't set "no projection" for not own waypoint-activity
found by myself, didn't create an issue yet
=> fix: show user-defined projection for predefined waypoints

main/src/main/res/xml/preferences_appearence.xml
Due to refactored SeekbarPreference, VTM scaling options can now be coded without intermediary `Preference` tags.
=> UnifiedMap VTM: Simplify scaling preference code

main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/res/values/preference_keys.xml
yet another stab at #15100: (updated description)
- destroy map fragment in `onPause` and recreate on returning to calling map
- alternatively (configurable by setting feature key, see further down): destroy map fragment only if a sub-map is requested, and restart activity after returning to calling map
- so far no differentiation between GoogleMaps and VTM, though only the latter seems to need this cycle. can be added later, if this PR actually fixes #15100
=> UnifiedMap: recycle map fragment on calling sub activity (rel. to #15100)

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
One idea for speeding up loading cache lists: 
Apply filter already on loading caches (in contrast to: loading ALL caches first, then filter some of them out)
@ztNFny 
Can your cross-check if that speeds up your use-case? (as time permits)
=> UnifiedMap: Apply list filter already on loading caches (fix #15414)

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
Apply standard "reload caches" procedure on receiving "cache has changed" broadcast to respect current filter and other settings
=> UnifiedMap: Reload caches on receiving broadcast (fix #15404)

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
Due to refactoring of map spinner some intermediary methods are no longer required
=> UnifiedMap: Remove some intermediary methods no longer required

main/src/main/java/cgeo/geocaching/maps/CGeoMap.java
fix #15463: prevent NPE when objects are null
=> fix #15463: prevent NPE when objects are null

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
rel to #15462: try to reduce database accesses for list loading
A first step to work on performance issues on loading of large lists into unified map: load all caches from DB at once (not cache-by-cache).
@moving-bits could you take a look at this PR?
=> rel to #15462: try to reduce database accesses for list loading

main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/RenderThemeSettings.java, main/src/main/java/cgeo/geocaching/settings/SettingsActivity.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeThemeSettings.java, main/src/main/res/layout-land/layout_settings.xml
Two column mode for settings in landscape mode is not supported by theme options, so hide it in landscape mode for theme options
=> Hide right column for theme options in landscape mode (fix #15459)

main/src/main/java/cgeo/geocaching/activity/ActivityMixin.java, main/src/main/java/cgeo/geocaching/files/GPXTrackOrRouteImporter.java, main/src/main/java/cgeo/geocaching/maps/RouteTrackUtils.java, main/src/main/res/values/strings.xml
Add track name to toast on import error
This PR, if merged, will add the route/track name to the error toast when an import into map fails:
=> Add track name to toast on import error

main/build.gradle
A new release of VTM has been published, including the temporary fixes required for UnifiedMap, so let's switch back to regular release path for VTM
=> Bring VTM sources back to regular release (0.21.0)

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapViewModel.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/CacheCirclesLayer.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/GeoItemsLayer.java, main/src/main/java/cgeo/geocaching/utils/livedata/CollectionLiveData.java
rel to #15492: introduces CollectionLiveData which helps prevent concurrent-modification-exceptions on unified map model objects
Unified map deals with multiple livedata collection objects and reads/modifies them in various locationss and threads. To control this better, this PR introduces class CollectionLiveData which controls such access via a read/write lock.
This PR introduces CollectionLiveData and applies it to the caches object in the unified map viewmodel
Feedback/review is requested for this PR as it changes view model updates on collections significantly.
=> rel to #15492: introduces CollectionLiveData which helps prevent concurrent-modification-exceptions on unified map model objects

main/src/main/java/cgeo/geocaching/CacheListActivity.java, main/src/main/java/cgeo/geocaching/activity/AbstractNavigationBarActivity.java, main/src/main/java/cgeo/geocaching/maps/DefaultMap.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapType.java
UnifiedMap does not work with `SearchResult` on displaying a list content but with list id only, which lead to current filter being ignored. This PR applies the current filter instead of using a default (empty) one.
=> Apply filter on mapping a list content (fix #15485)

main/src/main/java/cgeo/geocaching/maps/MapUtils.java, main/src/main/res/layout/dialog_selected_position.xml, main/src/main/res/menu/map_longclick.xml, main/src/main/res/values/strings.xml
Implements the ideas described in https://github.com/cgeo/cgeo/pull/15429#issuecomment-2002128498:
- Combines map long-tap menu entries for "Show coordinates" and "Elevation (map)" into a single "Selected position" entry
- Tapping on it opens a dialog with following options:
- Display coordinates (format switchable)
- Display elevation from map
- Display distance to current position (straight line)
Closes #15429
=> Improve selected position info

main/src/main/res/layout-land/layout_settings.xml
Second column is used in landscape only, including the vertical divider, so add hints for the checking tools.
=> Fix lint: inconsistent layout (fix #15592)

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
no need to handle location update if map fragment is gone (due to sub-map having been requested)
=> UnifiedMap: Fix NPE in location update

.github/workflows/avd-build-and-cache.yml, .github/workflows/tests.yml, .github/workflows/watchdog.yml
From GHA "avd_cache_update" result at https://github.com/cgeo/cgeo/actions/runs/8687394730.
`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-java@v3.`
=>  Update GH action setup-java

main/src/main/java/cgeo/geocaching/connector/gc/GCLogin.java
as discussed in today's dev call: reset internal login data structure when encountering a race condition while logging in
hopefully mitigates #14950
=> reset login info on encountering race condition

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
As of my limited understanding of the filtering and loading stuff of caches - but debugging and trying:
when on `UnifiedMapActivity::reloadCachesAndWaypoints`  not only the `loadInBackgroundHandler` is initialized for `UMTT_PlainMap`
but the map data is refreshed (filter on `viewModel.caches` is applied (again(?)) via `UnifiedMapActivity::refreshMapData`) everything works fine.
fix #15470
This PR is not a fix for #15614
=> Fix filtering caches on live map

main/src/main/java/cgeo/geocaching/connector/gc/GCLogAPI.java
fix retrieving the CSRF token for some TB logs
make getting the TB html page conditional as it's only required for RETRIEVE logs
all log pages seem stable in their use of the new CSRF call now, so removing the legacy code, fixing https://github.com/cgeo/cgeo/issues/15648
=> fix TB logging, remove legacy code, only fetch TB log page if required

main/src/androidTest/java/cgeo/geocaching/CgeoApplicationTest.java, main/src/androidTest/java/cgeo/geocaching/test/mock/MockedCache.java, main/src/main/java/cgeo/geocaching/connector/gc/GCConstants.java, main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java
- do not terminate detection on JS-escaped double quotes in username
- check for and unescape JS-escaped Unicode characters
- along the way: shortens username detection regexp to look for username only, as findcount is detected otherwise meanwhile
(switching to reading `serverParameters` seems to be non-feasable here, as it is not yet available during login)
=> Refine username detection during login

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
Show "use current list" option on creating a UDC on UnifiedMap (if appropriate, meaning: if map currently displays contents of a list)
Fix #15662
=> UnifiedMap: Show 'use current list' option on creating UDC

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
Trigger a reload of caches/waypoints after enabling live mode to load caches from live map.
Related to https://github.com/cgeo/cgeo/issues/15386#issuecomment-2080153730 (first part)
=> UnifiedMap: Reload after enabling live mode (rel. to #15386)

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
attempt to fix a NPE in UnifiedMapActivity which was apparently introduced by a conflict resolution merge in https://github.com/cgeo/cgeo/commit/74d93a20d0408549ee4442c811f37332cbefdfc8
=> avoid NPE in refreshListChooser(), fixes #15676

main/src/main/java/cgeo/geocaching/storage/extension/Trackfiles.java
Attempts to fix #15567 by
- ensuring `Trackfile.getDisplayname()` never returns an empty or null display name (return a placeholder instead)
- calling sort on returning list of trackfiles only if result set is non-empty
This PR is a shot in the dark, as I have not been able yet to reproduce this error in my environment.
=> Ensure non-empty display name for trackfiles (rel. to #15567)

main/src/main/java/cgeo/geocaching/CacheListActivity.java, main/src/main/java/cgeo/geocaching/connector/gc/GCMap.java, main/src/main/java/cgeo/geocaching/connector/gc/GCWebAPI.java
fix #15689: enable finding archived owner caches again (introducing parameter sa=1 in gc.com websearch)
=> fix #15689: enable finding archived owner caches again (introducing parameter sa=1 in gc.com websearch)

main/src/androidTest/java/cgeo/geocaching/test/CgeoTestUtils.java, main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeVtmGeoItemLayer.java
rel to #15462: add batch-processing of marker add/remove for VTM
This PR creates its own version of the VTM MarkerLayer to allow adding/removing items w/o triggering a costly "populate" with each item action. "populate" is called once per batch only.
Please review carefully.
=> rel to #15462: add batch-processing of marker add/remove for VTM

main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceMapSourcesFragment.java, main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/TileProviderFactory.java, main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/UserDefinedMapsforgeOnlineSource.java, main/src/main/res/values/preference_keys.xml, main/src/main/res/values/strings.xml, main/src/main/res/xml/preferences_map_sources.xml
Allows user-entered Uri for tile provider and selection of "User-defined tile provider" if such provider is configured:
Implemented for UnifiedMap only.
(Default value is: no user-defined tile provider configured)
=> Support user-defined tile providers (rel. to #15041)

main/src/main/java/cgeo/geocaching/maps/AbstractMap.java, main/src/main/java/cgeo/geocaching/maps/CGeoMap.java, main/src/main/java/cgeo/geocaching/maps/MapSettingsUtils.java, main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
With my limited understanding of the BackgroundHandler and loading caches - but with debugging and trying:
If no `loadInBackgroundHandler` is set, then the caches / waypoints have to be reloaded via `reloadCachesAndWaypoints` to adapt to the possible changes made in the settings-popup.
Reloading and recreating the loadInBackgroundHandler is only done, if the relevant settings have changed.
Therefore I enhanced the `SettingsCheckboxModel` with the possibility to get that information.
fix #15611
fix #15614
fix #15661
=> Refresh map data after opening / closing settings dialog

main/src/androidTest/java/cgeo/geocaching/CgeoApplicationTest.java, main/src/androidTest/java/cgeo/geocaching/test/CgeoTestUtils.java, main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GeoItemLayer.java, main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/IProviderGeoItemLayer.java, main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeVtmGeoItemLayer.java, main/src/main/res/values/preference_keys.xml
rel to #15462: VTM caching of markersymbols
This PR introduces caching of created MarkerSymbols for VTM
=> rel to #15462: VTM caching of markersymbols

main/src/main/java/cgeo/geocaching/ui/GeoItemSelectorUtils.java
Adds event date to map's item selector for event type-caches:
=> Add event date to cache selector (fix #15704)

main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/res/xml/preferences_navigation.xml
- If you have a fresh install of c:geo and create a route, c:geo will now automatically ask you if it should try to download missing routing tiles
- does not affect existing installations
=> Enable internal routing and auto tile download by default (fix #15701)

main/src/main/java/cgeo/geocaching/export/IndividualRouteExportTask.java
Use only a single track segment when exporting an individual route as track
=> Export individual route as track with single segment (fix #15684)

main/build.gradle, main/src/main/java/cgeo/geocaching/apps/AbstractLocusApp.java, main/src/test/java/cgeo/geocaching/apps/AbstractLocusAppTest.java
replaces #15700.
As the locus connector now integrates the cache size virtual, we can now map caches with this size in c:geo to the virtual size in Locus.
=> Update locus with CacheSize "Virtual"

main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java, main/src/main/java/cgeo/geocaching/utils/TextUtils.java, main/src/main/res/values/strings.xml
ticket #926180: remove separate log length check
c:geo contained a separate log length check in addition to the "log text counter" in the text field. This length check counted line break as two characters. This seems to be a legacy thing, as of now gc.com counts line breaks only as one character. Thus this PR removes the separate check.
This solves a problem reported in the mentioned support ticket with log lengths close to 5000 characters
=> ticket #926180: remove separate log length check

main/src/main/java/cgeo/geocaching/downloader/MapDownloaderHylly.java
(make parsing size fraction optional)
=> Adapt to hylly website change (fix #11793)

main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeThemeHelper.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeThemeSettingsFragment.java
(dynamically created checkbox for "buildings in 3D" option missed initialization, see https://github.com/cgeo/cgeo/issues/15723#issuecomment-2156435095)
=> UnifiedMap VTM: Initialize 'buildings 3D' checkbox

main/src/main/java/cgeo/geocaching/CacheListActivity.java
Use correct sortContext for search with target-coords:
The created sortContext (with target-coords) in CacheListAdapter.onCreate was overwritten by CacheListAdapter.initAdapter, hence the target-coords got lost.
No need to create the sortContext in initAdapter.
fix #15618
=> fix #15618: Don't overwrite sortContext 

main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/java/cgeo/geocaching/unifiedmap/AbstractMapFragment.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsFragment.java, main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsThemeHelper.java, main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/AbstractGoogleTileProvider.java, main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/GoogleSatelliteSource.java, main/src/main/res/raw/googlemap_style_details.json, main/src/main/res/values/preference_keys.xml, main/src/main/res/values/strings.xml
rel to #15770: add google map options and hybrid map
* corrects a bug: Google Map option "Satellite" does now use "Hybrid" again (like in old map)
* adds Google Map options to show "traffic" as well as "(3d) buildings", both defaulting to false
=> fix #15770: add google map options and hybrid map

main/src/main/java/cgeo/geocaching/CachePopupFragment.java, main/src/main/java/cgeo/geocaching/service/CacheDownloaderService.java, main/src/main/java/cgeo/geocaching/ui/ViewUtils.java, main/src/main/res/values/strings.xml
- download caches in background when triggering a store / refresh from cache popup
- disable the refresh / store buttons when starting the download
- update popup contents on having successfully received the cache data
=> Move cache store/refresh from popup into background

main/src/main/java/cgeo/geocaching/filters/core/StatusGeocacheFilter.java, main/src/main/java/cgeo/geocaching/filters/gui/StatusFilterViewHolder.java, main/src/main/res/values/strings.xml
Add a "corrected coordinates" filter in addition to the existing "Solved Mystery" filter which only ever applies to Type=Mystery or the "Has user defined waypoints" filter which only applies if there's a custom waypoint as well - which doesn't exist if the coords are coorected on gc.com or the custom waypoint is deleted.
Without this new filter it's impossible to filter a list to show only e.g. "Type=Wherigo AND Corrected Coordinates"
=> add "corrected coordinates" filter

main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java, main/src/main/java/cgeo/geocaching/log/LogUtils.java, main/src/main/res/values/strings.xml
fix #15748: allow favorite point change on log editing
I had to change the wording of the favorite point checkbox in the log dialog so it matches both the "create log" and the "edit log" situation:
Before: Add this cache to favorites (%d remaining)
After: Make this cache a favorite (%d remaining)
=> fix #15748: allow favorite point change on log editing

main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java
fix #15666: don't offer offline save after failed edit log send
=> fix #15666: don't offer offline save after failed edit log send

main/src/main/java/cgeo/geocaching/loaders/CoordsGeocacheListLoader.java, main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/res/values/preference_keys.xml, main/src/main/res/values/strings.xml, main/src/main/res/xml/preferences_services.xml
fix #15696: introduce search limit for coord/address searches, same as for nearby searches
=> fix #15696: introduce search limit for coord/address searches, same as for nearby searches

main/src/main/java/cgeo/geocaching/MainActivity.java, main/src/main/java/cgeo/geocaching/activity/AbstractNavigationBarActivity.java, main/src/main/java/cgeo/geocaching/downloader/DownloaderUtils.java, main/src/main/res/layout/main_activity.xml
Adds a short notification on main screen if location permission has not been granted currently. (This is similar to "check for map updates" notification, but without "blue dot" badge.)
Short tap on that notification opens the permission request, long-tap dismisses the notification, as suggested in https://github.com/cgeo/cgeo/issues/15799#issuecomment-2174993229,
=> show notification for missing location permission (rel. to #15799)

main/src/main/res/xml/preferences_services.xml
Opening settings currently crashes with `ClassNotFoundException`. `ProximityPreference` got replaced by `SeekbarPreference` on branch `master`, which this PR adapts to.
=> Follow-up to #15696: Fix preference name on master branch

main/src/main/java/cgeo/geocaching/maps/MapSettingsUtils.java, main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceNavigationFragment.java, main/src/main/res/values/strings.xml
Once you selected a profile for the user-defined profiles 1 or 2, you can't get rid of it easily (go to the settings and delete the key).
This PR adds an entry "(none)" to the profile-selection-list (like for the launch-buttons)
=> Add "none"-entry to routing-profiles-selection

main/src/main/java/cgeo/geocaching/ui/CacheDetailsCreator.java, main/src/main/java/cgeo/geocaching/utils/MapMarkerUtils.java
A quick stab at adding the circle marker to popup to fix https://github.com/cgeo/cgeo/issues/15505
=> DT indicator in CachePopup

main/src/main/java/cgeo/geocaching/network/HttpRequest.java
various requests may produce a HTTP 429 Too many requests, e.g. live map on GC.com (https://github.com/cgeo/cgeo/issues/14601)
This PR adds logging for that case and also a Toast to inform the user about the throttling.
Not sure where in the code to put this kind of error handling - it's a universal thing (that's where I put it for now) but maybe it should be handled case-specific? So setting feedback required for now.
Also hardcoded strings for now ;-)
=> add logging and toast for HTTP 429 (Too many request)

main/src/main/java/cgeo/geocaching/CacheListActivity.java, main/src/main/java/cgeo/geocaching/ui/CacheListAdapter.java
Currently cache list gets refreshed completely on refreshing caches for every cache update received, which leads to frequent flickering until the last update got received.
This PR only updates the view for the received cache, thus avoids the flickering.
=> Avoid flickering on cache list refresh (rel. to 15461)

main/src/main/java/cgeo/geocaching/network/HttpRequest.java
To get our beta user up and running again, switch the "error 429 / slow down" toast to debug mode for now.
If no one objects I'll start building a new beta version including this PR in two hours or so.
I'll try to come up with something less blocking in a separate PR.
=> Show http 429 warning in debug mode only

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
Allow hint text rotation independantly from "show hint encoded" setting.
=> Enable hint rotation independantly from setting (fix #15887)

main/src/main/java/cgeo/geocaching/service/CacheDownloaderService.java
Currently there is a system notification "1 cache downloaded" for every cache you store or update using the cache infosheet, which can get pretty annoying. This PR changes this behavior to not show the final "1 cache downloaded" system notification, if only a single cache got triggered for current `CacheDownloaderService" and that download has been completed successfully. The progress notification is still being displayed (and removed on finishing the download, as is today).
Fixes #15881
=> Don't show notification after succ. cache download from infosheet

main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeThemeHelper.java
Store/load currently selected theme per tileprovider for OSM offline maps (UnifiedMap only currently)
If no tileprovider-specific theme is stored, fall back to last used theme.
Example: If you use both OpenAndroMaps and Freizeitkarte with their respective themes, switching from one to the other will load the related theme automatically, no manual switching necessary any more.
=> UnifiedMap: Store theme tileprovider-specific (rel. to #15850)

main/src/main/java/cgeo/geocaching/ui/CacheListActionBarChooser.java, main/src/main/java/cgeo/geocaching/ui/ImageParam.java, main/src/main/res/layout/cachelist_chooser_actionbar.xml
Applies correct tint to own drawables for ActionBar list chooser (default list icons + dropdown indicator).
Tint does not get applied for emoji list icons.
=> Apply tint for ActionBar chooser in light mode (fix #15883)

main/src/main/java/cgeo/geocaching/downloader/DownloaderUtils.java, main/src/main/res/values/strings.xml
On Android 7.0 - 9.0: Check for WRITE_EXTERNAL_STORAGE permission being granted before enqueing a download via integrated download manager, and display an error message on missing permission.
=> Show warning on missing WRITE_EXTERNAL_STORAGE permission (fix #15823)

main/src/androidTest/java/cgeo/geocaching/downloader/DownloaderTest.java
Mapsforge seems to have two more countries in Europe with state-specific sub maps, therefore need to adapt the Mapsforge downloader test
=> Adapt MapsforgeDownloader test to new map structure

main/AndroidManifest.xml
API34 requires separate `<uses-permission ... />` for each foreground service type it uses. This PR adds the missing ones + declares them as `minSdkVersion` 34.
=> Add missing service type declarations for API 34 (fix #15900)

main/AndroidManifest.xml
Currently integrated BRouter service is declared as service type "location", which seemed to be obvious, as it performs routing calculation based on given locations. But reading the [service type specs](https://developer.android.com/about/versions/14/changes/fgs-types-required), type location seems to be meant for something different, for "Long-running use cases that require location access, such as navigation and location sharing." But BRouter service itself does not need location access, it simply calculates a route between two given sets of coordinates. Additionally, BRouter service is able to run with location permissions not being granted, whereas the docs for service type location explicitly list granted location permissions as a runtime prerequisite for this service type. Thus I …
=> Switch BRouter foreground service type to dataSync

main/src/main/java/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/PositionLayer.java, main/src/main/java/cgeo/geocaching/models/TrailHistoryElement.java, main/src/main/java/cgeo/geocaching/storage/DataStore.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/PositionLayer.java, main/src/main/java/cgeo/geocaching/utils/GeoHeightUtils.java
On Android 14+ systems use the new feature to retrieve MSL-based altitude (see [docs](https://developer.android.com/reference/android/location/Location#getMslAltitudeMeters())), if such data is available for current location.
=> Use MSL altitude if available (fix #14424)

main/src/main/java/cgeo/geocaching/models/IndividualRoute.java
While refactoring a `updateRoute(routeUpdater);` got removed inadvertently, leading to routes no longer being updated on adding a geo item. This PR fixes this.
=> Fix #15904: Route not updating on appending a geo item

main/src/main/java/cgeo/geocaching/models/RouteItem.java, main/src/main/java/cgeo/geocaching/unifiedmap/LayerHelper.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/res/drawable/background_gc_hightlighted.xml
This is a technical demo for highlighting the active cache on the map (so far UnifiedMap only).
As soon as you tap on a cache (which opens the cache info sheet), a "corona" is being displayed around the cache icon. (Same could be done for waypoint icons and for compact icon variants.)
From looking at `marker.xml` and `marker_pin.xml` as well as `MapMarkerUtils.createCacheMarker` I would have expected a different result, though. Both drawables have 36dp width and height, and their viewports are 36/36 as well, so I would have expected, that `marker_pin.xml` is sort of an overlay to `marker.xml` (which would fit at being treated as inset).
Thus: aligning another drawable at "bottom center" should create an exact overlay, if that drawable has the same size.
But it does not, it aligns to the …
=> UnifiedMap: Highlight selected cache/waypoint (fix #15801)

main/src/main/java/cgeo/geocaching/utils/formulas/IntegerRange.java, main/src/test/java/cgeo/geocaching/utils/formulas/FormulaTest.java
Formula: allow big-sizes integet ranges (disallow usage of negation), alternative to PR ä15941
This PR allows integer ranges of any size w/o consuming too much memory. Disadvantage is that this implementation does not support negation operator any more (^).
=> Formula: allow big-sizes integet ranges (disallow usage of negation), alternative to PR ä15941

main/src/main/java/cgeo/geocaching/unifiedmap/LoadInBackgroundHandler.java
For UnifiedMap use a similar logic as for old map to compare whether the current viewport requires a new request to server for LiveMap results. Previous implementation was triggered with *any* zoom change.
partially fixes #15942
=> improve map viewport comparison for live map

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java, main/src/main/java/cgeo/geocaching/CachePopupFragment.java, main/src/main/java/cgeo/geocaching/apps/navi/NavigationAppFactory.java, main/src/main/java/cgeo/geocaching/maps/MapUtils.java
Long-tapping on navigation button in cache infosheet leads to stacking of navigation app selection, as the menu items fires multiple times.
This PR prevents this by disabling the menu item (and the dialog re-enabling it on dismissal).
=> Prevent stacking of navigation popups (fix #15937)

main/src/main/res/layout/cacheslist_activity.xml, main/src/main/res/values-night/colors_dark.xml
- Set solid black as background color in dark mode
- Fix cache list: missing divider color
=> Make dark background solid black + fix cache list divider (fix #15864)

main/build.gradle, main/src/main/java/cgeo/geocaching/list/StoredList.java
fix #15938: fix sort order for lists, make _ on top of uppercase letters
@moving-bits : this PR changes the version of datatables to be included. I was not able to compile otherwise since SNAPSHOT version seems not to be available on jitpack.io
=> fix #15938: fix sort order for lists, make _ on top of uppercase letters

main/src/androidTest/java/cgeo/geocaching/connector/gc/GCParserTest.java, main/src/main/java/cgeo/geocaching/connector/gc/GCConstants.java, main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java
fix #15993: parse spoiler images with uppercase image type suffix eg JPG (eg GC601B)
=> fix #15993: parse spoiler images with uppercase image type suffix eg JPG (eg GC601B)

main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceMapSourcesFragment.java, main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/AbstractMapsforgeOnlineTileProvider.java, main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/AbstractMapsforgeTileProvider.java, main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/UserDefinedMapsforgeOnlineSource.java, main/src/main/res/values/strings.xml
Supports individual parametrization of tileprovider uri (UnifiedMap only).
If parameters {X} and {Y} are not found, `/{Z}/{X}/{Y}.png` is added automatically (migration support).
Also adds a restart to c:geo on changing tileprovider uri.
=> UnifiedMap: Support parametrized tileprovider uri (fix #15884)

main/src/main/java/cgeo/geocaching/location/Units.java, main/src/main/java/cgeo/geocaching/utils/GeoHeightUtils.java
Show elevation on home screen in "meters" or "feet", do not scale to "kilometers" or "miles".
Additionally:
- use internationalization for formatting number (decimal "points")
- use identical formatter for elevation info on home screen and for position info on map
=> Do not scale elevation on main screen (fix #16046)

main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceSystemFragment.java, main/src/main/res/values/preference_keys.xml, main/src/main/res/xml/preferences_system.xml
Toggles testDir preference behavior:
Instead of having it included by default and removing it in non-developer builds, do not have it included by default, but add it dynamically in developer builds (to avoid the effect of vanishing blank space as described in #16071).
=> Show testDir preference in developer builds only (fix #16071)

main/src/main/java/cgeo/geocaching/settings/AbstractClickablePreference.java, main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceServiceGeocachingComFragment.java, main/src/main/res/values/strings.xml
If gc connector is activated, but credentials are missing, show a prominent warning hint:
=> Show warning for activated gc connector without credentials (fix #16061)

main/src/androidTest/java/cgeo/geocaching/connector/gc/GCParserTest.java, main/src/main/java/cgeo/geocaching/connector/gc/GCConstants.java, main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java, main/src/main/java/cgeo/geocaching/models/Geocache.java, main/src/main/java/cgeo/geocaching/models/Image.java, main/src/main/java/cgeo/geocaching/utils/ImageUtils.java, main/src/main/res/values/preference_keys.xml, main/src/main/res/values/strings.xml, main/src/main/res/xml/preferences_services_geocaching_com.xml
Since 2016 there's actually some code to load original instead of "/display/", but only for that 1 out of 4 generated sizes. And it applies only to listing background and spoiler images (but not to inline images which are more commonly used today).
PR adds code to handle all 5 sizes, applies it to all listing images, always requests the original one and fixes some smaller issues.
Open question:
- (How) do we let the user decide about the prefered size (New setting?)?
- What's the default size?
- Is it the same for all types of images (listing, listing background, TB, log)?
Open todos:
- Apply the same to logs, TBs. 
- Rewrite the listing html code before loading it to apply the different image size there as well - right now it only applies to images tab, resulting in the image (maybe) …
=> Dynamic image size

main/src/main/java/cgeo/geocaching/unifiedmap/mapsforge/MapsforgeFragment.java
(new mapsforge library with enabled rotation feature recommends to increase the tile cache)
=> UnifiedMap Mapsforge: Increase tile cache size (due to map rotation)

main/src/main/java/cgeo/geocaching/unifiedmap/mapsforge/MapsforgeFragment.java
If map rotation center is shifted away from view center, map's overdraw factor should be adjusted for cleaner map display
=> UnifiedMap Mapsforge: Adjust overdraw factor in driving mode

main/src/main/res/values/strings.xml, main/src/main/res/xml/preferences_map_sources.xml
Adds a checkbox setting to Settings => Map Sources => Unified Map section to enable Mapsforge engine in addition to VTM in UnifiedMap
=> UnifiedMap Mapsforge: Add setting to toggle usage

main/src/main/java/cgeo/geocaching/settings/TemplateTextPreference.java
Sets focus on text (or title) input field of `TemplateTextPreference` and opens the keyboard.
=> Set focus in TemplateTextPreference (fix #16072)

main/src/main/java/cgeo/geocaching/maps/RouteTrackUtils.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/ElevationChart.java, main/src/main/res/menu/map_routetrack_context.xml, main/src/main/res/values/strings.xml
Change to route/track tap handling in UnifiedMap (as discussed in https://github.com/cgeo/cgeo/issues/16064#issuecomment-2353638351):
- short tap on route/track no longer opens/closes elevation chart
- long tap on route/track with no elevation chart offers "Show elevation chart" as first menu option
- long tap on route/track with opened elevation chart closes it
=> UnifiedMap: Move 'show elevation chart' to long tap menu (fix #16064)

main/src/main/res/values/strings.xml
hillshading download check used some strings still mentioning "routing". This PR generalizes those string to make it working for both routing data and hillshading data
=> Generalize some strings used in routing/hillshading downloads

main/src/main/java/cgeo/geocaching/connector/trackable/TravelBugConnector.java
"Open in browser" was open for TB logs due to outdated URL
=> fix "Open in browser" for TB logs (#16115)

main/src/main/java/cgeo/geocaching/models/Waypoint.java
Projection for predefined waypoints are not considered on extracting to PN.
If predefined waypoint has projection, the waypoint is now considered as user-modified and the projection gets written to the PN.
On adding waypoints from PN the projeciton is also now considered, if coords of the waypoint are empty
=> Fix projection for predefined waypoint

main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java, main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/java/cgeo/geocaching/ui/DateTimeEditor.java, main/src/main/res/values/preference_keys.xml
add a long-tap listener to set the (log) date to the previously used date.
Alternative: I'd like to have extended MaterialDatePicker with a 3rd button, but that class is final and I really don't want to implement so much stuff for just that 3rd button (there are PRs for that open at the upstream repo for a long time)
=> logging: long-tap on date to set "previous date" (fixes #16085)

main/src/main/java/cgeo/geocaching/MainActivity.java, main/src/main/java/cgeo/geocaching/downloader/DownloaderUtils.java, main/src/main/java/cgeo/geocaching/maps/MapProviderFactory.java, main/src/main/java/cgeo/geocaching/models/Download.java, main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/TileProviderFactory.java, main/src/main/res/menu/main_activity_options.xml, main/src/main/res/menu/map_activity.xml, main/src/main/res/values/strings.xml
Adds a "Delete offline data" to the "Manage offline data" menu entry, which opens a dialog offering all downloaded files for deletion (maps, themes, routing tiles, hillshading tiles):
Also removes "Delete offline maps" from map selection menus.
=> Manage downloaded files (fix #16118)

main/src/main/res/values/strings.xml
"Save images" title previously used is wrong as images are saved regardless, this setting only affects log images. Because of this wording issue I was about to re-implement this as I didn't realize the setting already existed.
=> reword "pref_logimages" setting

main/src/main/java/cgeo/geocaching/maps/AbstractMapSource.java, main/src/main/java/cgeo/geocaching/maps/MapProviderFactory.java, main/src/main/java/cgeo/geocaching/maps/interfaces/MapSource.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/res/values/strings.xml
Fix broken detection for old map whether the provider supports hillshading https://github.com/cgeo/cgeo/pull/15415
(it was using the UnifiedMap TileSource previously so it worked in tests but it didn't actually work)
=> fix hillshading detection in legacy map

main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/caches/AbstractCachesOverlay.java
`NewMap` Mapsforge: Catch IllegalStateException on removing map items (that are not assigned currently), currently most prominent error on Play Store for current release 2024.09.18
=> Mapsforge: Catch IllegalStateException on unassigning layers

main/src/main/java/cgeo/geocaching/unifiedmap/mapsforge/MapsforgeFragment.java
zooming to given bounds needs to set map center as well. 
Added this for UnifiedMap Mapsforge (as old `NewMap` has in `zoomToViewport`)
=> UnifiedMap Mapsforge: Fix zoomToBoundsDirect (fix #16135)

main/src/main/java/cgeo/geocaching/unifiedmap/mapsforge/MapsforgeFragment.java
UnifiedMap Mapsforge: Take driving mode into account when calculating tile cache size
(see related [discussion](https://github.com/mapsforge/mapsforge/discussions/1545) on Mapsforge for details)
=> UnifiedMap: Consider driving mode when calculating tile cache size

main/src/main/java/cgeo/geocaching/MainActivity.java, main/src/main/java/cgeo/geocaching/wherigo/WherigoGame.java, main/src/main/res/menu/main_activity_options.xml
Wherigo: add wherigo player entry in main overflow menu
Referencing this comment https://github.com/cgeo/cgeo/issues/10087#issuecomment-2394972522
I feel like the Wherigo Player deserves at least an overflow menu entry in main activity. Also compared with other stuff mentioned here which is probably used only by some users (pocket queries, bookmar lists, utility program), the player doesn't seem less important.
=> Wherigo: add wherigo player entry in main overflow menu

main/src/main/java/cgeo/geocaching/wherigo/WherigoGame.java
fix #16164: Wherigo: prevent npe on null sound data
=> fix #16164: Wherigo: prevent npe on null sound data

main/src/main/java/cgeo/geocaching/utils/DebugUtils.java
rel to #16164: add System.err and .out to standard logcat exerpt
Handling #16164 I realized that we need to include also System.out and System.err output in the standard logfiles generated by c:geo. Otherwise it won't be possible to analyze and fix Wherigo-related errors
=> rel to #16164: add System.err and .out to standard logcat exerpt

main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/RenderThemeSettingsFragment.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforge/MapsforgeThemeSettingsFragment.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeThemeSettingsFragment.java
`SeekbarUI` supports settings title and summary meanwhile, a separate `Preference` is no longer needed.
|before|after|
|---|---|
|![image](https://github.com/user-attachments/assets/2ab14cba-4ec9-453d-b0fd-c32b17c6db24)|![image](https://github.com/user-attachments/assets/c9f8f732-3712-43be-9d14-2ad7a9d743be)|
=> Use condensed layout for Mapsforge map scaling settings

main/build.gradle
With the latest update of androidx.work:work-runtime we have now CI errors.
~~~
08:50:50  Could not load custom lint check jar file /home/jenkins/.gradle/caches/transforms-3/af359fe1ec3ff3d6c14449f8d6618922/transformed/work-runtime-2.9.1/jars/lint.jar 
08:50:50  java.lang.UnsupportedClassVersionError: androidx/work/lint/WorkManagerIssueRegistry has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
~~~
The build is marked a success, so probably the problem was not detected.
=> downgrade androidx.work:work-runtime

main/src/main/java/cgeo/geocaching/unifiedmap/AbstractMapFragment.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsFragment.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforge/MapsforgeFragment.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java
- UnifiedMap: Fix crash on resuming Google Maps
- Move `repaintRotationIndicator()` from `UnifiedMapActivity` to `AbstractMapFragment`
=> UnifiedMap: Fix crash on resuming Google Maps (fix #16180)

main/src/main/java/cgeo/geocaching/CacheListActivity.java, main/src/main/res/menu/cache_list_options.xml
Adds an option to remove selected/all caches from all lists, effectively marking them as "to be deleted" (which they will after the grace period). Suports undo.
Closes #16110 (which deleted selected / all caches immediately from database after a confirmation dialog)
=> Add option to remove caches from all lists (fix #15402)

main/build.gradle
Updates both Mapsforge and VTM to the newly released v0.22.0 (to include Mapsforge rotation etc. from a regular release).
Also changes source for VTM to Jitpack, as it does seem to be no longer available from the old source.
=> Update Mapsforge and VTM to v0.22.0

main/src/main/res/values/themes.xml
Reduces the extra space between toolbar's back button and following content:
|before|after|
|---|---|
|![image](https://github.com/user-attachments/assets/a5526b2a-b549-4322-8b9f-4bbcaeed06c9)|![image](https://github.com/user-attachments/assets/d38f0dee-98b3-4aa5-a280-fc23dc0a861e)|
|![image](https://github.com/user-attachments/assets/c42cf7b1-7751-4d56-8704-37e0b17ca256)|![image](https://github.com/user-attachments/assets/a2d2b7a5-c6b6-4828-b472-f62e0cd503e7)|
(Related to discussion in https://github.com/cgeo/cgeo/issues/16151#issuecomment-2406914336)
=> Reduce toolbar space between back button and content

main/src/main/java/cgeo/geocaching/connector/gc/GCConstants.java, main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java
GC removed the event date + start / end times from listings. Because of this it's no longer possible to see the event times anywhere in c:geo and functions relying on these dates, like creating calendar entries, are failing.
With this PR the event times are manually prefixed to the events description, making it appear and function exactly like before the change.
fixes #16229
Targeted against release as this is a breaking change.
=> manually add event date + start/end time to listing text

main/src/androidTest/java/cgeo/geocaching/storage/DataStoreTest.java, main/src/main/java/cgeo/geocaching/storage/DataStore.java
Fetch cache-data for unsaved caches without merging from already downloaded cache-data, so the newest version is used
For stored caches merging / gathering missing data from existing cache is performed, so no data will be lost (preserve current behaviour)
fix #16175 
PR #16226 is prerequisite for thia PR to fix failing test (Fix the date-format in GC40)
=> Fetch cache-data for unsaved caches without merging data from cache cache (fix #16175)

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java, main/src/main/java/cgeo/geocaching/EditWaypointActivity.java, main/src/main/java/cgeo/geocaching/models/Geocache.java
For waypoint "original coordinates" 
* rename the function "set as cache-coordinates" to "reset in c:geo" (same string used as in the dialog for reseting from context-menu)
* delete the waypoint "original coordinates" and reset the flag for corrected coordinates
rel #15735
=> Improve reset to original coordinates (rel #15735)

main/src/main/java/cgeo/geocaching/wherigo/WherigoCartridgeDialogProvider.java
fix #16234: avoid NPE on Wherigo cartridge delete
=> fix #16234: avoid NPE on Wherigo cartridge delete

main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/main/res/layout/map_mapsforge_v6.xml
Fixes separator between zoom controls of old Mapsforge map:
|before|after|
|---|---|
|![image](https://github.com/user-attachments/assets/cbb05e5e-48a2-4c47-8b50-5935d611ec28)|![image](https://github.com/user-attachments/assets/905cb2eb-0210-4db0-89d4-bb90d4bd9767)|
=> Fix zoom controls for old Mapsforge map (rel. to #16225)

main/src/main/java/cgeo/geocaching/apps/cachelist/MapsMeCacheListApp.java, main/src/main/java/cgeo/geocaching/service/CacheDownloaderService.java, main/src/main/java/cgeo/geocaching/utils/ProcessUtils.java, main/src/main/java/cgeo/geocaching/utils/ShareUtils.java, main/src/main/java/cgeo/geocaching/wherigo/WherigoDialogManager.java, main/src/main/java/cgeo/geocaching/wherigo/WherigoGameService.java
Starting with API level 31, declaring a `PendingIntent` as either immutable or mutable is mandatory, but this flag is provided for API 23+ only. As we currently support API 21+, we need to add a build version check.
This PR adds the two missing build version checks + extracts the check into a helper method.
=> Fix lint: Flag PendingIntent.FLAG_IMMUTABLE not supported for API < 23

main/src/main/java/cgeo/geocaching/utils/FilterUtils.java, main/src/main/res/values/strings.xml
If a filter is currently active, but no filter is saved (only "temporary" filter), the long click on the filter-icon does nothing. At least I should have the possibility to clear the current active filter.
first proposal
second proposal
I reused the current dialog-box and just kept the "clear" button, that is, why it looks probably weird.
=> Clear filter should be possible, if no filter is defined

main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java, main/src/main/java/cgeo/geocaching/models/Geocache.java, main/src/main/res/values/strings.xml
On creating a quick offline log show a confirmation prompt if cache already has an offline log stored and
- the old offline log has a log text
- the old and new log texts are different
to avoid accidentally overwriting written log texts with empty logs 
fixes #16244
=> confirm overwriting log on quick offline log

main/src/main/java/cgeo/geocaching/ui/SimpleItemListModel.java, main/src/main/java/cgeo/geocaching/ui/SimpleItemListView.java, main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java, main/src/main/java/cgeo/geocaching/wherigo/WherigoCartridgeDialogProvider.java, main/src/main/java/cgeo/geocaching/wherigo/WherigoDialogManager.java, main/src/main/java/cgeo/geocaching/wherigo/WherigoInputDialogProvider.java, main/src/main/java/cgeo/geocaching/wherigo/WherigoPushDialogProvider.java, main/src/main/java/cgeo/geocaching/wherigo/WherigoThingDialogProvider.java, main/src/main/java/cgeo/geocaching/wherigo/WherigoUtils.java, main/src/main/java/cgeo/geocaching/wherigo/WherigoViewUtils.java, main/src/main/res/layout/wherigo_activity.xml, main/src/main/res/layout/wherigo_dialog_title_view.xml, main/src/main/res/menu/wherigo_options.xml, main/src/main/res/values/strings.xml
fix #16266: change layout and gui elements according to issue
This PR fixes everything menationed in the issue with one exception: Wherigo Dialog elements still have an actionbar element. In addition, a "back" arrow was implemented inside those action bars. All in all with this PR the "wherigo screens look like activities" pattern is realized/completed.
=> fix #16266: change layout and gui elements according to issue

main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/java/cgeo/geocaching/utils/Formatter.java, main/src/main/res/values/preference_keys.xml, main/src/main/res/values/strings.xml, main/src/main/res/xml/preferences_appearence.xml
added a new "Localization" section in Settings where I grouped the new option with the old unit and language:
available configurable date formats:
in use:
fixes https://github.com/cgeo/cgeo/issues/16285
fixes https://github.com/cgeo/cgeo/issues/16249
=> make short date format configurable

main/src/main/res/drawable/map_pin.xml
map long-click marker is currently taken out of Google Maps and looks strange, replace it with a c:geo styled one
new
old
=> make map click marker cgeo-styled

main/src/androidTest/java/cgeo/geocaching/downloader/DownloaderTest.java, main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java, main/src/main/java/cgeo/geocaching/wherigo/WherigoDownloader.java
fix #16312: Wherigo: prevent loss of resume dialog when opening cartridge details
=> fix #16312: Wherigo: prevent loss of resume dialog when opening cartridge details

main/src/main/res/values/strings.xml, main/src/main/res/values/strings_not_translatable.xml
(fixed format strings' examples like eg. "17/2/24" should not be translated)
=> Make date format values non-translatable (rel. to #16286)

main/src/main/res/drawable/bearing_indicator.xml, main/src/main/res/drawable/map_bearing_background.xml, main/src/main/res/drawable/map_button_background.xml, main/src/main/res/drawable/map_button_background_bottom.xml, main/src/main/res/drawable/map_button_background_top.xml, main/src/main/res/drawable/map_zoomin.xml, main/src/main/res/drawable/map_zoomin_btn.xml, main/src/main/res/drawable/map_zoomout.xml, main/src/main/res/drawable/map_zoomout_btn.xml, main/src/main/res/layout-land/map_settings_button.xml, main/src/main/res/layout/map_distanceinfo.xml, main/src/main/res/layout/map_settings_button.xml, main/src/main/res/layout/map_zoom_control.xml, main/src/main/res/values/colors.xml, main/src/main/res/values/styles.xml
As requested by @moving-bits a [long time ago](https://github.com/cgeo/cgeo/pull/13063#issuecomment-1146778743) this PR now adds a shadow effect to all map buttons (zoom, quick settings, location, compass).
Small but unavoidable side effect: The buttons get a bit darker. This is because the buttons have white background with a slight transparency and the shadow is drawn behind the whole button - so also behind the transparent part.
As the buttons are already #FFF there's no way to make them whiter to offset the shadow. Reducing the transparency would make them whiter - but also less transparent, which they already are only slightly.
Alternative: We remove the transparency completly. (Transparency levels between old and none don't work, even old has only little transparency, any tuning …
=> add shadows to map overlay buttons

main/src/main/java/cgeo/geocaching/maps/DefaultMap.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapType.java, main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java, main/src/main/java/cgeo/geocaching/wherigo/WherigoThingDialogProvider.java
if map filter context is explicitly set to GeocacheFilterContext.FilterType.TRANSIENT don't enable Live mode, no matter what map type is displayed
@moving-bits there's a lot of "magic" happening in determining when to show which caches (only selected, stored, live) that's quite intransparent even after debugging this code. Thus I'm asking for your review as most of this seems to come from you.
Maybe this magic could also be replaced by a more transparent implementation, but I fear that'd be a big rewrite. Or maybe it's not so magic after all and I'm just missing something??
fixes https://github.com/cgeo/cgeo/issues/16338
=> don't enable live map for WIG mapping

main/src/main/res/layout/search_activity.xml
Restyling the search dialog by removing the 3-times duplicated information what to search by turning the button into an icon button
before:
after:
=> optimize space usage in search activity

main/src/main/java/cgeo/geocaching/unifiedmap/AbstractMapFragment.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforge/MapsforgeFragment.java
Restricts UnifiedMap Mapsforge's zoom to zoom min/max given by tile provider, even for `zoomToBounds()` call (which is called in UMTT_Viewport mode used by WIG player). This is relevant especially for online tile providers, which do not provide map tiles for higher zoom levels.
=> UnifiedMap Mapsforge: restrict zoom to min/max zoom (fix #16352)

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java, main/src/main/java/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java, main/src/main/res/menu/cache_options.xml, main/src/main/res/values/strings.xml
Allow changing coordinates for UDC by using a menu entry "set coordinates", which opens the coordinate input dialog:
|menu|dialog|calculate|
|---|---|---|
|![image](https://github.com/user-attachments/assets/50b1690e-6c86-4ce7-9b9f-e9b7937f658b)|![image](https://github.com/user-attachments/assets/167b6757-6053-4918-bab8-6d4b3b0244b8)|![image](https://github.com/user-attachments/assets/c18b6ee4-0f60-4323-8f6e-ce0f8db5ae43)|
@eddiemuc 
When using calculated coordinates, I need a `calcStateString`, which would normally be stored in a waypoint. Do we have a place for it on cache level already, and how would I retrieve the new calc string, if a user changes the formula?
Setting WIP label for now
=> Allow changing coordinates for UDC

main/src/main/java/cgeo/geocaching/utils/SystemInformation.java
System information: Print tileprovider info instead of mapsource info, if UnifiedMap is enabled
=> Add tileprovider to system info

main/src/main/java/cgeo/geocaching/settings/Settings.java
As discussed in today's dev meeting:
Use VTM as default for UnifiedMap for now for smoother update transition for upcoming beta.
This should be changed back to UnifiedMap Mapsforge as soon as we have reached enough stability to make UnifiedMap Mapsforge the default map (and degrade the old map types).
=> UnifiedMap: Use VTM as default for now

main/src/main/java/cgeo/geocaching/connector/gc/GCConstants.java, main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java, main/src/main/java/cgeo/geocaching/utils/Formatter.java
revert back to using the HTML as source for event date as that one is in events timezone
see https://github.com/cgeo/cgeo/issues/16367 for discussion
=> Revert "use eventCacheData JS object as event time source"

main/src/main/java/cgeo/geocaching/downloader/DownloaderUtils.java, main/src/main/java/cgeo/geocaching/maps/MapProviderFactory.java, main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/TileProviderFactory.java
Adds "Delete offline data" to map sources menus, which triggers the offline data selection dialog (same as can be reached via home screen => manage offline data => delete offline data)
=> Allow deleting offline data from map context (rel. to #16357)

main/src/main/java/cgeo/geocaching/log/CacheLogsViewCreator.java, main/src/main/java/cgeo/geocaching/log/LogsViewCreator.java, main/src/main/java/cgeo/geocaching/log/TrackableLogsViewCreator.java, main/src/main/res/drawable/ic_menu_open_in_browser.xml, main/src/main/res/drawable/ic_menu_rot13.xml, main/src/main/res/menu/cache_options.xml
=> refine icons in log context menu, consistenly use the same icon for "open in browser"

main/src/androidTest/java/cgeo/geocaching/filters/TypeGeocacheFilterTest.java, main/src/main/java/cgeo/geocaching/enumerations/CacheType.java, main/src/main/java/cgeo/geocaching/filters/core/TypeGeocacheFilter.java, main/src/main/java/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java, main/src/main/res/values/strings.xml
added "Specials" and "Others" types to cache filter
new groups are:
Other: Unknown, GC HQ, Ape
Special Event: Mega, Giga, CCE, HQ Party, Maze, Block Party
fixes #16376
=> add filters for special events and other cache types

main/src/main/java/cgeo/geocaching/downloader/MapDownloaderMapsforge.java
Make Mapsforge map downloader recognize file names that end in "-1.map", "-2,map" etc.
=> Downloader: Recognize file names containing numbers (fix #16383)

main/src/main/res/drawable/ic_menu_rot13.xml
replaces https://github.com/cgeo/cgeo/commit/fddee1615b75cd4b99d4b5f2dff89bdaa7efd7fc
=> proper fix of the missing icon tint on rot13 icon

main/src/main/java/cgeo/geocaching/MainActivity.java, main/src/main/java/cgeo/geocaching/settings/Settings.java
If a user has used an email address as login to GC, automatically switch to username on retrieving username info for connector info on main screen. (Avoids errors on detecting cache ownership, see linked issue.)
=> Auto-fix email used as login to GC (fix #16397)

main/src/main/java/cgeo/geocaching/activity/AbstractNavigationBarMapActivity.java, main/src/main/java/cgeo/geocaching/network/HttpRequest.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/res/drawable/warning.xml, main/src/main/res/layout/unifiedmap_activity.xml, main/src/main/res/values/strings.xml
This is an alternative approach to #15889: 
Show a small notification icon below the compass rose, if http 429 limit is reached. Tapping on that icon reveals the specific error message (with server name):
By this you get a visual indicator, if network requests fail due to limit having been reached, but that indicator does not block a huge part of the map (as in the linked PR). As a regular user you can act accordingly, but if you are unfamiliar with this warning, you can tap on it to get more info.
Positioning and formatting of the icon TBD.
Closes #15889
=> Show http 429 warning notification

main/src/main/res/layout-land/unifiedmap_activity.xml, main/src/main/res/layout/map_429warning.xml, main/src/main/res/layout/unifiedmap_activity.xml
Extends support for http 429 warning to landscape mode.
Also fixes icon default state (see https://github.com/cgeo/cgeo/pull/15889#issuecomment-2525044730)
=> UnifiedMap Support http 429 warning in landscape mode

main/src/main/java/cgeo/geocaching/maps/CGeoMap.java, main/src/main/java/cgeo/geocaching/maps/MapProviderFactory.java, main/src/main/java/cgeo/geocaching/maps/MapUtils.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/HillShadingLayerHelper.java, main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java, main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/TileProviderFactory.java, main/src/main/res/values/preference_keys.xml, main/src/main/res/xml/preferences_map_sources.xml
download routing/hillshading buttons were visible when they shouldn't be
change the logic for activating hillshading buttons from 1 master toggle in preferences to "any hillshading files are downloaded"
=> fix hillshading and routing download button visibility

main/src/main/java/cgeo/geocaching/SearchActivity.java, main/src/main/java/cgeo/geocaching/models/Download.java, main/src/main/java/cgeo/geocaching/search/AutoCompleteAdapter.java, main/src/main/java/cgeo/geocaching/search/GeocacheAutoCompleteAdapter.java, main/src/main/java/cgeo/geocaching/search/SearchAutoCompleteAdapter.java, main/src/main/java/cgeo/geocaching/ui/GeoItemSelectorUtils.java, main/src/main/res/drawable/search_identifier.xml, main/src/main/res/layout/cacheslist_item_select.xml, main/src/main/res/layout/search_activity.xml, main/src/main/res/layout/search_card.xml, main/src/main/res/layout/search_suggestion.xml
supersedes  https://github.com/cgeo/cgeo/pull/16433
- several bugfixes for cardsearch:
-- keyword search suggestion was broken
-- wrong adapter sometimes used
-- visual tweaks
-- change geocode icon
-- add missing tint
- unrelated fix:
-- wrong icon was used in delete offline data dialog
- inline search suggestions (instead of dropdown)
-- search terms are highlighted in results
-- For all but Geocode search no history function is implemented yet but all the UI logic should be there now (not a regression, just a missing feature ;-))
@fm-sys maybe the "remember search terms and suggest them" part is where you could add as per our discussion in the last dev call - as time permits of course!
=> Cardsearch fixes and inline search suggestions

main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/AbstractMapsforgeOnlineTileProvider.java
(fix error reported by Play Store stats for current beta 2024.12.17-RC)
=> UnifiedMap Mapsforge: Fix NPE in online tile provider

main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/AbstractMapsforgeOfflineTileProvider.java
As proposed in https://github.com/cgeo/cgeo/issues/16430#issuecomment-2560807345: uses default `LabelLayer` instead of `ThreadedLabelLayer`
=> UnifiedMap Mapsforge: Use LabelLayer instead of ThreadedLabelLayer

main/build.gradle, main/src/main/java/cgeo/geocaching/maps/mapsforge/AbstractMapsforgeMapSource.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/CgeoAdaptiveClasyHillShading.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/DownloadLayer.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/HillShadingLayerHelper.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/MultiRendererLayer.java, main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/RendererLayer.java, main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/res/values/preference_keys.xml, main/src/main/res/values/strings.xml, main/src/main/res/xml/preferences_map_sources.xml
updates mapsforge to a recent build to be able to use AdaptiveClasyHillShading
switch algorithm to AdaptiveClasyHillShading
adds an user-facing option to enable HQ HS
fixes #16438
=> update mapsforge, use AdaptiveClasyHillShading (hq disabled)

main/src/main/java/cgeo/geocaching/utils/formulas/FormulaFunction.java, main/src/main/java/cgeo/geocaching/utils/formulas/FormulaUtils.java, main/src/main/java/cgeo/geocaching/utils/formulas/Value.java, main/src/main/java/cgeo/geocaching/utils/formulas/ValueList.java, main/src/test/java/cgeo/geocaching/utils/formulas/FormulaUtilsTest.java
rel to #16444: enable substring to be zerobased or onebased, enhance error handling
Enables easy parameterized switch between zero-index-based and one-index-based usage of `FormulaUtils.substring`. Also enhances error handling and unit test coverage.
This PR will NOT change any logic though
=> rel to #16444: enable substring to be zerobased or onebased, enhance error handling

main/src/main/java/cgeo/geocaching/log/LogTrackableActivity.java
to enable LogTrackableActivity to distinguish between GeoKrety and Travelbug brands in ambiguous cases
=> Send TB brand to TB logging activity (fix #16443)

main/src/main/java/cgeo/geocaching/CacheMenuHandler.java, main/src/main/res/drawable/ic_menu_gpx.xml, main/src/main/res/menu/cache_options.xml, main/src/main/res/values/strings.xml
add a new share option to share the cache including coordinates (and indicator whether they are original, modified or final WP) and PN
Also add some icons to the menu :-)
=> option to share cache with user data (coords, PN)

main/src/main/java/cgeo/geocaching/connector/gc/AbstractListActivity.java, main/src/main/java/cgeo/geocaching/connector/gc/BookmarkListActivity.java, main/src/main/java/cgeo/geocaching/connector/gc/PocketQueryListActivity.java, main/src/main/res/values/strings.xml
change switch labels for PQ / lists activities from "show all" to specific strings "New only" for lists and "Downloadable only" for PQs. For the old "show all" it's not clear what the other option actually does.
supersedes https://github.com/cgeo/cgeo/pull/16483
=> change list switch labels

main/src/androidTest/java/cgeo/geocaching/filters/GeocacheFilterTest.java
The 2 new filters "LIST_ID" and "VIEWPORT" (https://github.com/cgeo/cgeo/commit/857a61bfc44aeef83cdd6e395dff780b021cf961) has to be considered in getFilledInstance.
The intention of the assert is, that all filters are considered in the generic filled test (at least, if not considered, then on purpose)
=> Fix failing tests: Consider new filters in test

main/src/androidTest/java/cgeo/geocaching/connector/gc/GCConnectorTest.java
fix failing gc viewport test due to archived cache
A junit test was failing because one of the caches used was archived today. This PR fixes the broken testcase
=> fix failing gc viewport test due to archived cache

main/src/main/java/cgeo/geocaching/filters/gui/GeocacheFilterActivity.java, main/src/main/java/cgeo/geocaching/utils/FilterUtils.java
group cache filters by string before ":"
fixes https://github.com/cgeo/cgeo/issues/16526
=> enabling grouping for stored filters

main/src/androidTest/java/cgeo/geocaching/connector/internal/InternalConnectorTest.java, main/src/main/java/cgeo/geocaching/connector/internal/InternalConnector.java, main/src/main/java/cgeo/geocaching/storage/DataStore.java, main/src/main/res/values/strings.xml
fixes https://github.com/cgeo/cgeo/issues/15992 by generating a random ID for UDCs in range ZZ[0-9A-Z]{4}. 1,8 million possibilities should be random enough 😉
also some cleanup that was supposed to be done in 2020 :-)
And a bugfix for getting the default name and description that was previously broken (due to the provided string being "" instead of null)
=> generate random IDs for UDCs

main/build.gradle
An official release 0.23.0 got published yesterday, so we can move from specific build back to official release
=> Update Mapsforge to newly released 0.23.0

main/src/main/res/layout/logcache_activity.xml, main/src/main/res/values/strings.xml
| Rename filter and sort from inventory to "Trackables Count" |Rename cache-page "Inventory" to "Trackables"|Keep "Inventory" for log-page|
|---|---|---|
|<img src="https://github.com/user-attachments/assets/cf905f19-0652-4dce-86fc-86066ceff706" height="250">|<img src="https://github.com/user-attachments/assets/6b0806b1-3ec2-468a-81f6-caec0047c003" width="250">|<img src="https://github.com/user-attachments/assets/fb524ce1-de79-4114-9414-8488e2b0b707" width="350">|
fix #16500
"Has Trackables" is already correct
Just for information: The place where "Move to Inventory" is used, is never called
=> Rename inventory to trackables where applicable

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
fix #16537: avoid map jumping to desert on map data changes
=> fix #16537: avoid map jumping to desert on map data changes

main/src/main/java/cgeo/geocaching/utils/MapMarkerUtils.java, main/src/main/res/drawable/marker_usermodifiedcoords_original.xml
adds a cache map marker for the case that a cache has modified coords but those are equal to the original cache coordinates.
The visibility isn't perfect but as this is a corner-case that should happen seldomly it's ok enough imho
fixes https://github.com/cgeo/cgeo/issues/16551
=> Warning if corrected coords = final coords

main/src/main/java/cgeo/geocaching/CacheListActivity.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/java/cgeo/geocaching/utils/MenuUtils.java, main/src/main/res/menu/cache_list_options.xml, main/src/main/res/menu/map_activity.xml, main/src/main/res/values-night/colors_dark.xml, main/src/main/res/values/colors_light.xml
Tinting the icons properly requires some elaborate workarounds to determine whether the icon is shown in toolbar or overflow menu. Those are redrawn frequently which requires even more workarounds (those are all in the helper method in MenuUtils)
=> add icons to map + list overflow menu

main/src/main/java/cgeo/geocaching/location/GeopointParser.java, main/src/test/java/cgeo/geocaching/location/GeoPointParserTest.java, main/src/test/java/cgeo/geocaching/models/CacheArtefactParserTest.java
add parser for DD,DDDDDDD format used by e.g. Google Maps in German/Russian
fixes https://github.com/cgeo/cgeo/issues/16382
This will require some good testing though, the coordinate format seems to be prone to false positives - hence marking as Feedback required.
=> add parser for DD,DDDDDDD format

main/src/main/java/cgeo/geocaching/unifiedmap/layers/WherigoLayer.java
fix #16587: Wherigo: handle zones with invalid/too-close coordinates
=> fix #16587: Wherigo: handle zones with invalid/too-close coordinates

main/src/main/java/cgeo/geocaching/filters/core/GeocacheFilterContext.java, main/src/main/java/cgeo/geocaching/ui/dialog/SimpleDialog.java, main/src/main/java/cgeo/geocaching/utils/FilterUtils.java, main/src/main/res/values/strings.xml
Show the last used filter in filter-selection-dialog, if no filter is active.
So it will be easier, to disable temporarily the current filter and enable the one before.
Fixed name is currently the "active" variant
fix #16512
=> Show lastUsedFilterName in filter-dialog

main/src/main/java/cgeo/geocaching/location/GeopointParser.java, main/src/test/java/cgeo/geocaching/location/GeoPointParserTest.java
Fix the regexpr to consider only 1 digit for longitude value before comma (in `getParseInputs` /  `removeSpaceAfterSeparators`)
The other parsers were able to deal with the not removed space, because this was supported in their own regexpressions.
Since I didn't want to change to much for the existing parsers, I added a new method for the special format
#16382
=> [rel #16382] Consider not only 2 digits minimum for deg comma parser

main/src/main/java/cgeo/geocaching/downloader/CompanionFileUtils.java, main/src/main/java/cgeo/geocaching/downloader/ReceiveDownload.java, main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/AbstractMapsforgeOfflineTileProvider.java, main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/AbstractMapsforgeVTMOfflineTileProvider.java, main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/AbstractTileProvider.java, main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/TileProviderFactory.java
Allow configuring displayname for offline map sources downloaded with c:geo:
|map selection|folder data|companion file|
|---|---|---|
|![image](https://github.com/user-attachments/assets/976004de-ca4d-4839-8b69-13b195455316)|![image](https://github.com/user-attachments/assets/d5dee193-82ae-4919-8907-a31d0f88b49f)|![image](https://github.com/user-attachments/assets/1d317e95-2039-40e6-8d83-df422d8db678)|
Only `displayname` property in companion file needs to be changed, everything else is untouched. Updating such a map source does work, `displayname` gets preserved. Map sources are sorted by `displayname` within their respective categories.
=> UnifiedMap: Set displayName for downloaded offline maps (fix #16586)

main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java
fixes https://github.com/cgeo/cgeo/issues/16609
code had && instead of ||. Changed the condition to be more readable
=> hide "report problem" when editing a log

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java, main/src/main/java/cgeo/geocaching/models/Waypoint.java, main/src/main/res/menu/waypoint_options.xml, main/src/main/res/values/strings.xml
Allow manually setting a "geofence" radius on a per-waypoint basis. Those circles are shown on map if "Circles" option in map quick settings is enabled:
|Waypoint context menu|Editing geofence radius|Result on map|
|---|---|---|
|![image](https://github.com/user-attachments/assets/04acd998-9a11-43cd-bc53-1caa1993bdd3)|![image](https://github.com/user-attachments/assets/44a0b00d-ce5c-4895-89a7-88a5063817c5)|![image](https://github.com/user-attachments/assets/8c68a3e0-83f9-49f2-bb64-bb826050a568)|
This feature is built on top of #16618 (show geofence circles for lab stages) and allows setting a value manually for non-lab waypoints.
=> Allow manual setting of geofence radius (fix #16436)

main/src/main/java/cgeo/geocaching/ui/TextParam.java, main/src/main/java/cgeo/geocaching/ui/ViewUtils.java, main/src/main/java/cgeo/geocaching/wherigo/WherigoCartridgeDialogProvider.java, main/src/main/java/cgeo/geocaching/wherigo/WherigoThingDialogProvider.java, main/src/main/java/cgeo/geocaching/wherigo/WherigoUtils.java, main/src/main/java/cgeo/geocaching/wherigo/WherigoViewUtils.java, main/src/main/res/layout/button_wherigo_view.xml, main/src/main/res/values/styles.xml
fix #16627: make custom button texts case sensitive
Note: the "custom button" is faked in the above image for demonstration purposes. If a cartridge provides a very long text for a button it would look like this
=> fix #16627: make custom button texts case sensitive

main/src/main/java/cgeo/geocaching/settings/SeekbarPreference.java
fix #16635: SeekbarPreference: remove seekbarui from other view before reassigning it
=> fix #16635: SeekbarPreference: remove seekbarui from other view before reassigning it

main/AndroidManifest.xml
As discussed in #16472: Remove the Play Store restriction to _require_ GPS, make it optional.
=> Enable c:geo listing for GPS-less devices (fix #16472)

main/src/main/java/cgeo/geocaching/location/Viewport.java, main/src/main/java/cgeo/geocaching/models/geoitem/GeoItemUtils.java, main/src/main/java/cgeo/geocaching/models/geoitem/GeoStyle.java, main/src/main/java/cgeo/geocaching/unifiedmap/LiveMapGeocacheLoader.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapViewModel.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/GeoItemsLayer.java
fix #16617: unified live map: don't call server after partial/error result when too close to previous position
=> fix #16617: unified live map: don't call server after partial/error result when too close to previous position

main/src/main/java/cgeo/geocaching/helper/UsefulAppsActivity.java, main/src/main/res/values/strings.xml, main/src/main/res/values/strings_not_translatable.xml
Since having an integrated Wherigo player, a reference to WhereYouGo in "useful apps" list is no longer required
=> Remove WhereYouGo from 'useful apps' list

main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java
Same as #16670, but targeted to `release` (rebase of #16670 did not work)
Closes #16670
=> show "Save" for log only for new logs (fixes #16668)

main/build.gradle
- VTM 0.23 just got released, see https://github.com/mapsforge/vtm/releases
- we are using Mapsforge in v0.23 already on `release`, so let's get them on par
=> Update VTM to 0.23.0 to be on par with Mapsforge library

main/build.gradle
Reverts #16678 (see https://github.com/cgeo/cgeo/pull/16707#issuecomment-2695521606)
=> Revert "Update VTM to 0.23.0 to be on par with Mapsforge library"

main/build.gradle
Updates Mapsforge and VTM to v0.24 (and jts-core, which is a dependency for VTM, to v1.20)
supersedes #16706 
supersedes #16707
=> Update Mapsforge and VTM to v0.24

main/src/main/java/cgeo/geocaching/location/Units.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/ElevationChart.java
Elevation charts "follows current location", marking the closest nearby point on the current track and adapting the x-axis labels to it. Maximum allowed distance between current location and point on track is 100m. Minimum distance between two updates is 50m.
=> Follow my location in elevation chart (fix #15763)

main/src/main/java/cgeo/geocaching/connector/al/ALApi.java
There are no related issues, however, while I was investigating: #16193 I noticed that the stage number in LCs is now shown twice. This is just a change to remove the now unnecessary stage number which was inserted into the stage text at a time where the "white dots" with those numbers weren't there yet.
=> LC: Preserve user note on refresh

main/src/main/java/cgeo/geocaching/utils/MapMarkerUtils.java, main/src/main/res/drawable/marker_stagenum_1.xml, main/src/main/res/drawable/marker_stagenum_10.xml, main/src/main/res/drawable/marker_stagenum_2.xml, main/src/main/res/drawable/marker_stagenum_3.xml, main/src/main/res/drawable/marker_stagenum_4.xml, main/src/main/res/drawable/marker_stagenum_5.xml, main/src/main/res/drawable/marker_stagenum_6.xml, main/src/main/res/drawable/marker_stagenum_7.xml, main/src/main/res/drawable/marker_stagenum_8.xml, main/src/main/res/drawable/marker_stagenum_9.xml, main/src/main/res/values/colors.xml
As some phones use a font where number emojis are white which leads to invisible numbers replace them with vector drawables that always render properly - and also add a "10"
=> vectors instead of emojis for stage numbers

build.gradle, gradle.properties, main/build.gradle
As discussed in today's dev meeting: 
Temporarily revert AGP & MF updates to become Java 11-compatible again to test next nightly with Java 11.
=> Revert updates for AGP & Mapsforge to be Java 11-compatbile for testing purposes

main/src/androidTest/java/cgeo/geocaching/address/GeocoderTest.java
Android Geocoder seems to have a different resolution for the address give for the test meanwhile, so let's adapt the coordinates used by the test
=> Fix geocoder test

main/src/main/java/cgeo/geocaching/CacheListActivity.java
Adds "move multiple caches to another list" function to list opened by "show as list" 
Behavior will be:
Move: remove from existing list-assignment and add only to the new one
Copy: keep existing list assignment and add to the new list
The entries are only shown, if there are stored caches in the list.
If no stored caches are in the list, the entries for storing the caches offline should be used instead.
In case of mixed caches (stored and unstored caches), the unstored caches will be downloaded and stored in the selected list.
fix #15733
=> Enable move-to / copy-to for all lists (fix #15733)

main/src/main/java/cgeo/geocaching/connector/AbstractConnector.java, main/src/main/java/cgeo/geocaching/connector/IConnector.java, main/src/main/java/cgeo/geocaching/connector/internal/InternalConnector.java, main/src/main/java/cgeo/geocaching/filters/core/OriginGeocacheFilter.java, main/src/main/java/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java, main/src/main/res/values-ca/strings.xml, main/src/main/res/values-cs/strings.xml, main/src/main/res/values-da/strings.xml, main/src/main/res/values-de/strings.xml, main/src/main/res/values-el/strings.xml, main/src/main/res/values-es/strings.xml, main/src/main/res/values-fi/strings.xml, main/src/main/res/values-fr/strings.xml, main/src/main/res/values-it/strings.xml, main/src/main/res/values-ja/strings.xml, main/src/main/res/values-ko/strings.xml, main/src/main/res/values-lt/strings.xml, main/src/main/res/values-lv/strings.xml, main/src/main/res/values-nb/strings.xml, main/src/main/res/values-nl/strings.xml, main/src/main/res/values-pl/strings.xml, main/src/main/res/values-pt/strings.xml, main/src/main/res/values-ru/strings.xml, main/src/main/res/values-sk/strings.xml, main/src/main/res/values-sv/strings.xml, main/src/main/res/values-tr/strings.xml, main/src/main/res/values-uk/strings.xml, main/src/main/res/values-zh-rTW/strings.xml, main/src/main/res/values/strings.xml
* Show internal connector per default for selectable connectors in filter. `isActive()` method returns true as @eddiemuc suggested.
* Add displayName to IConnector to make connector-name translatable as @fm-sys suggested
fix #14832
I use already existing translation for "User defined caches" (goto_targets_list), but I did not reuse the key, I introduced a new key to be independent.
=> Show internal connector as active in filter and add display name (fix #14832)

main/AndroidManifest.xml
- Reverts the changes in `AndroidManifest.xml` that came with #16593, #16600 and #16611 to get rid of the side-effects mentioned in #16777
- adds API 31+ compatible replacements for opening local gpx, gwc and map files
@Lineflyer @ztNFny 
Can you cross-check, if this version works for you and also avoids the problems you have described in #16608?
=> Add API 31+ filtering for local file access

main/AndroidManifest.xml
This partly reverts commit 55798a7fe37937d66d536451e1d4d65e979f8efa (only reverts the AndroidManifest.xml-related part) to (hopefully) fix the issues described in #16777, as so far they are already part of current release 2025.03.06
=> Partly revert local map file detection

main/src/main/java/cgeo/geocaching/log/LogsViewCreator.java, main/src/main/java/cgeo/geocaching/ui/ExpandableTextView.java, main/src/main/res/layout/logs_item.xml, main/src/main/res/values/strings.xml
Per default show log entries with a maximum of 5 lines. If a log entry is longer, a vertical ellipsis symbol is being displayed. Long-tapping on the log entry will expand the view.
|collapsed state|expanded state|
|---|---|
|![image](https://github.com/user-attachments/assets/3a28b4f8-dec5-430e-917c-24ccb7c19445)|![image](https://github.com/user-attachments/assets/a9238a0d-5fe9-49ab-83b5-ca86c68b69c8)|
Edit: If a log item is collapsible, a menu item will be added to the log entry's context menu to either collapse or expand the log item:
|non collapsible|collapsed|expanded|
|---|---|---|
|![image](https://github.com/user-attachments/assets/8dc747e3-f078-45ed-af62-5a1338de63e3)|![image](https://github.com/user-attachments/assets/d5593165-ca63-473b-be14-b3a8a5e1761f)|![image](https://github.c …
=> Collapse long log entries per default (fix #16789)

.github/actions/cgeo-preferences/action.yml, .github/workflows/tests.yml, .github/workflows/watchdog.yml
- Only run watchdog from cgeo repo
- Check for secret presence and fail is missing
+ Run the test workflow from any branch
+ Only allow one run per ref branch or tag
+ Allow only one concurrent live run over all branches (using https://github.com/suzuki-shunsuke/lock-action?tab=readme-ov-file, that creates a new branch `lock__unit-test` to maintain the lock and history)
#15608
=> Only run watchdog from cgeo repo + Check for secret presence and fail is missing

.github/workflows/tests.yml
Build the APK first, then block for lock
- #15608
=> CI micro optim: Build binary first then block for live tests

.github/workflows/tests.yml
While all my tests went fine yesterday, this WF https://github.com/cgeo/cgeo/actions/runs/14227542305/attempts/1 failed with "the bug" (timeout killing the emulator process [and child]). I'm suspecting that in this case, as the tests failed, the `gradlew` command returned with an exit code and the workaround wasn't applied. Here we also apply the workaround on `gradlew` failure - and return with an error too
=> ci: Force kill crashpad_handler even on error

.github/workflows/tests.yml, .github/workflows/watchdog.yml
- check access to secrets explicitly
- use trigger `pull_request_target` and add safety guards on user permission over cgeo repo.
> This event runs in the context of the base of the pull request, rather than in the context of the merge commit, as the pull_request event does. This prevents execution of unsafe code from the head of the pull request that could alter your repository or steal any secrets you use in your workflow. This event allows your workflow to do things like label or comment on pull requests from forks. Avoid using this event if you need to build or run code from the pull request.
#16804
=> Allow running Unit Tests on PR from forks

.github/workflows/tests.yml
Should not cancel jobs for branches master and release
=> ci: Don't cancel workflows for master/release branches

main/src/main/java/cgeo/geocaching/CacheListActivity.java, main/src/main/java/cgeo/geocaching/command/MakeListUniqueCommand.java, main/src/main/java/cgeo/geocaching/ui/CacheListAdapter.java, main/src/main/res/menu/cache_list_options.xml, main/src/main/res/values/strings.xml
New entry "Remove from other lists" in "Manage caches"-menu  works for all caches in list and for selection (menu"Manage list" is now disabled for select-mode)
Existing entry  "Show Attribute Overview" in "Manage caches"-menu works now on selected caches
rel #16195 
Some more GUI-improvements
Avoid unnecessary calls:
* Get upfront necessary options
* Get list of selected or all caches only once
* Count checked caches only if select-mode is active
* Handover checkedCount
Improve Labels:
* No count for delete past events
* No count for clear offline logs
* No count for upload modified coordinates
* Add count for export-entries in select-mode
Improve Visibility:
* Disable "Manage list"-menu  in select-mode
* Disable "Import"-menu in select-mode
* Hide "Clear offline log", if no caches with …
=> Improve cache list menu (rel #16195)

main/src/main/java/cgeo/geocaching/export/GpxExport.java, main/src/main/java/cgeo/geocaching/export/GpxSerializer.java, main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/res/layout/gpx_export_dialog.xml, main/src/main/res/values/preference_keys.xml, main/src/main/res/values/strings.xml
I have made an attempt to make the data elements that get included in a gpx export configurable. By default, the logs get included and also travel bugs. I wouldn't know what tool importing the GPX would be interested in the logs, nor the travel bugs. And if such a tool exists, well, then configure the new options accordingly.
Now there is one problem: I am on the road again with my very old and slow laptop, I have a hard time even compiling the code and running the emulator takes forever. Having said this: It seems my if-conditions don't evaluate correctly as the logs and travel bugs are always included even if I uncheck the checkboxes in the UI.
@moving-bits : Could you have a quick look at it?
=> config_gpx_export_details

main/src/main/java/cgeo/geocaching/wherigo/WherigoViewUtils.java, main/src/main/res/values/strings.xml
Replaces Wherigo "Send error report by email" option by "Copy error message to clipboard":
=> Remove 'Send email' option for Wherigo problem reports

main/src/main/java/cgeo/geocaching/settings/TemplateTextPreference.java, main/src/main/res/layout/button_icon_view.xml
Adds a "delete" button alongside each logging template. Short tap on this icon opens the delete dialog.
Old long tap behavior is removed.
=> Add delete button to template preferences (fix #16805)

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java, main/src/main/res/values/strings.xml
As discussed in the last dev meeting: Do not offer c:geo's internal Wherigo player on cache details page if no credentials for gc service are configured. Instead show an info message + forward to connector's settings page:
=> Ask for Wherigo credentials if necessary

main/src/main/java/cgeo/geocaching/maps/DefaultMap.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java, main/src/main/java/cgeo/geocaching/wherigo/WherigoThingDialogProvider.java, main/src/main/java/cgeo/geocaching/wherigo/WherigoUtils.java, main/src/main/res/values/strings.xml
rel to #16779: wherigo zone: add compass and copy coordinate
Adds to Wherigo Player:
* ability to navigate to a zone using compass
* ability to copy zone center coordinates to clipboard
* long-tap on a zone on map is no longer recognized. This allows users to do other stuff in map zone area available on long-tap eg create user-defined cache
* set zone center as target when opening map (to get routing and distance info for it)
=> rel to #16779: wherigo zone: add compass and copy coordinate

main/src/main/java/cgeo/geocaching/wherigo/WherigoDownloader.java, main/src/main/res/values/strings.xml
Displays an error message on Wherigo download if website reports "EULA not set":
=> Wherigo: Display EULA error message (fix #16772)

gradle.properties
Test PR to check whether this avoids effects like #16727 or #16867
If this works, we can use this as a fall back and quick fix, and try to investigate further into detailed ProGuard rules.
=> Disable R8 full mode optimizations (test)

main/src/main/java/cgeo/geocaching/downloader/DownloadSelectorActivity.java, main/src/main/java/cgeo/geocaching/downloader/DownloaderUtils.java, main/src/main/java/cgeo/geocaching/downloader/MapDownloaderOpenAndroMapsBackgroundMaps.java, main/src/main/java/cgeo/geocaching/models/Download.java, main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/java/cgeo/geocaching/storage/PersistableFolder.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/MBTilesLayerHelper.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java, main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/AbstractMapsforgeVTMOfflineTileProvider.java, main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/AbstractTileProvider.java, main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/TileProviderFactory.java, main/src/main/res/layout/downloader_activity.xml, main/src/main/res/menu/map_mapview.xml, main/src/main/res/values/preference_keys.xml, main/src/main/res/values/strings.xml, main/src/main/res/values/strings_not_translatable.xml
Support background maps in `.mbtiles` format for VTM (display, download, update, settings).
|Default "world.map"|background map|
|---|---|
|![image](https://github.com/user-attachments/assets/78d66a3b-2984-4179-8aa4-336f56bf7bfd)|![image](https://github.com/user-attachments/assets/07014883-128e-4c1f-9979-12340e8e91f3)|
Using regular "world.map" is fast, but has nearly no detail info. Using country-specific maps instead requires much device space + is very slow in low zoom levels. An alternative is using bitmap based overview maps like those provided by [OpenAndroMaps](https://www.openandromaps.org/downloads/ubersichts-karten). Those maps are provided in `.mbtiles` format, which is supported by VTM.
|enable/disable|start downloader|downloader|
|---|---|---| …
=> UnifiedMap VTM: Add background map capability

main/src/main/java/cgeo/geocaching/downloader/DownloaderUtils.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/MBTilesLayerHelper.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/mbtiles/MBTilesFile.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/mbtiles/MBTilesLayer.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/mbtiles/MBTilesMapWorkerPool.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/mbtiles/MBTilesRenderer.java, main/src/main/java/cgeo/geocaching/unifiedmap/layers/mbtiles/MBTilesRendererJob.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforge/MapsforgeFragment.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java, main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/AbstractMapsforgeOfflineTileProvider.java, main/src/main/java/cgeo/geocaching/utils/FileUtils.java
Similar to #16869, but for Mapsforge. Currently implements reading capability for `.mbtiles` maps itself, but I'll try to get that part integrated into official Mapsforge library.
|zoom level 3|zoom level 4|zoom level 5|
|---|---|---|
|![image](https://github.com/user-attachments/assets/7a88ebb8-601e-45b4-acf3-7cf89ecccb2c)|![image](https://github.com/user-attachments/assets/17a17280-1bea-4baf-81dc-1adcc2500bdd)|![image](https://github.com/user-attachments/assets/b43ae860-913b-4bb0-8827-7efee6cafe7d)|
|zoom level 6|zoom level 7|zoom level 8|
|---|---|---|
|![image](https://github.com/user-attachments/assets/4869851c-7427-48cf-9ae7-dfaea94ff422)|![image](https://github.com/user-attachments/assets/e2ea1c52-d0e8-4d98-8224-9acc17e482bb)|![image](https://github.com/user-attachments/assets/00fe1 …
=> UnifiedMap Mapsforge: Add background map capability

main/src/main/java/cgeo/geocaching/apps/cache/WhereYouGoApp.java, main/src/main/java/cgeo/geocaching/wherigo/WherigoCartridgeDialogProvider.java, main/src/main/java/cgeo/geocaching/wherigo/WherigoGame.java, main/src/main/java/cgeo/geocaching/wherigo/WherigoUtils.java, main/src/main/java/cgeo/geocaching/wherigo/WherigoViewUtils.java, main/src/main/res/values/strings.xml, main/src/test/java/cgeo/geocaching/wherigo/WherigoUtilsTest.java
fix #16822: wherigo, add possibility to contact cartridge author via wherigo.com
Allows user to navigate to cartridge detail page on wherigo.com in both the cardtridge info dialog and the error dialog. The later is meant so the user may contact the cartridge author (via wherigo.com) if he/she wants to report an error to him/her.
=> fix #16822: wherigo, add possibility to contact cartridge author via wherigo.com

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java, main/src/main/java/cgeo/geocaching/utils/OfflineTranslateUtils.java, main/src/main/res/values/strings.xml
This PR tries to preserve HTML during offline translation of a cache description.
|Original|Translated|
|---|---|
|![image](https://github.com/user-attachments/assets/c196e3e9-222d-4ba4-ab7b-7615ebfcb68f)|![image](https://github.com/user-attachments/assets/2e1afab9-2282-4539-b0fa-3504d49a05cb)| 
Partly works already, images are preserved, as well as most formatting, but only _some_ links:
|Original|Translated|
|---|---|
|![image](https://github.com/user-attachments/assets/01d91d10-23d7-4d5e-ae2c-e372da1cb895)|![image](https://github.com/user-attachments/assets/d12a729d-15dc-401e-a5e7-71406b849884)|
Also, depending on the specific source text, sometimes paragraphs are lost:
|Original|Translated|
|---|---|
|![image](https://github.com/user-attachments/assets/5b2dfb93-c922-4083-b138-72e1d0f9e …
=> WIP: Make offline translation preserve HTML

main/src/androidTest/java/cgeo/geocaching/utils/InstrumentedFormulaUtilsTest.java, main/src/main/java/cgeo/geocaching/utils/formulas/FormulaUtils.java, main/src/test/java/cgeo/geocaching/utils/formulas/FormulaUtilsTest.java
Copy/Paste of formula in GC53XAF `N ab cd.efg E 00u vw.xyz` leads in current implementation to `N ab cd.efg E 00u vw.*yz`
A new function was introduced to replace the letter x with the multiply-sign. So the automatic replacement in scanning the coordinates is not necessary anymore.
This PR removes the automatic replacement of `x`
rel #13844
rel PR #16692
=> Remove automatic replacement of x while scanning coordinates in formula

main/src/main/java/cgeo/geocaching/utils/FileNameCreator.java
Fixes the initialization of the file name counter in `FileNameCreator.java`.
Previously, the counter was initialized with `1` and used `addAndGet(1)`, which caused the first generated file name to have a suffix of `2`.
Fixes #13186
- Updated `AtomicInteger` initialization to start at `0`
=> Fix #13186: Correct file naming counter during file name creation

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java, main/src/main/java/cgeo/geocaching/utils/OfflineTranslateUtils.java
#16910 introduced two bugs that the translation box did not become visible again after successful translation (+ even if it would have come, the spinner would have been spinning endlessly when there was no hint in the cache to be translated). This PR fixes both issues.
=> Fix translation box missing after translation

main/src/main/java/cgeo/geocaching/models/geoitem/ToScreenProjector.java, main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GeoItemLayer.java, main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeV6GeoItemLayer.java, main/src/main/java/cgeo/geocaching/unifiedmap/mapsforge/MapsforgeFragment.java
fix #16280: mapsforge, manually accomodate for rotation in coord projection
=> fix #16280: mapsforge, manually accomodate for rotation in coord projection

main/build.gradle
Remove the rule to set the type as warning. Now it is back to error. With PR #16904 the lint error was fixed.
=> set lint check UnsafeImplicitIntentLaunch to default

main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/res/values/preference_keys.xml
Date formatter "Y" uses "week years" in contrast to "y" using "years" (which is what we need here)
(https://docs.oracle.com/javase/8/docs/api/java/util/GregorianCalendar.html#week_year)
=> Fix short date formatting (fix #16925)

main/src/main/java/cgeo/geocaching/CacheListActivity.java, main/src/main/res/menu/cache_list_options.xml, main/src/main/res/values/strings.xml, main/src/main/res/values/strings_not_translatable.xml
- Fixes a UI inconsistency by moving "Upload modified coordinates" and "Upload coordinates for all caches" into the "Export" submenu.
- Renames the submenu to "Export / Upload" to better reflect its contents.
- Updates string labels of existing export actions to begin with "Export" for clarity and consistency.
- Adds icons to the new upload entries to match the visual style of other items.
Fixes #16625
=> Fix #16625: Move upload entries and update labels

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java, main/src/main/java/cgeo/geocaching/SearchActivity.java, main/src/main/java/cgeo/geocaching/filters/gui/DistanceFilterViewHolder.java, main/src/main/java/cgeo/geocaching/log/LogTrackableActivity.java, main/src/main/java/cgeo/geocaching/ui/dialog/NewCoordinateInputDialog.java
Extends the earlier work to utilise the new dialog in these additional places
- User define cache 'Set Coordinates' option
- Search card 'Coordinates'
- Logging a Geokrety TB
PR16799 
PR16889
Also included these improvements
- Constructor is no longer public as recommended by @eddiemuc 
- The 'My coordinates' button now shows accuracy as per the old dialog
I have tested the above use cases and replicated the same functionality as before except in these cases
1. User defined cache does not have a button to use the 'cache coordinates' - seem pointless when the purpose is to change the existing coordinates 
2. GK TB does not have the 'calculate coordinates' button. The rational here is you are dropping a TB in or visiting a cache so you must presumably already have the coordinates and do not …
=> Use new coordinate entry dialog in all places except waypoint page

main/src/main/java/cgeo/geocaching/EditWaypointActivity.java, main/src/main/java/cgeo/geocaching/filters/gui/GeocacheFilterActivity.java, main/src/main/java/cgeo/geocaching/maps/routing/RouteSortActivity.java, main/src/main/java/cgeo/geocaching/ui/CheckableItemSelectActivity.java
Adds the missing super calls as a quick mitigation for the lint errors to unblock upgrading other libs.
As using `onBackPressed` is deprecated meanwhile, we should switch to setting an `OnBackPressedDispatcher` in the long run.
=> Fix lint: Add missing calls to super.onBackPressed() (fix #16978)

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java, main/src/main/java/cgeo/geocaching/CacheListActivity.java, main/src/main/java/cgeo/geocaching/CompassActivity.java, main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java, main/src/main/java/cgeo/geocaching/log/LoggingUI.java, main/src/main/java/cgeo/geocaching/models/Geocache.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/java/cgeo/geocaching/utils/ShareUtils.java, main/src/main/res/values/strings.xml
- Add share intent in `LogCacheActivity`.
- Add `startForCreateForResult()` in `LogCacheActivity` to support request code.
- The share text prefix changes based on the log type (e.g., `FOUND_IT`, `DIDNT_FIND_IT`, `NOTE`, `NEEDS_MAINTENANCE`, and `NEEDS_ARCHIVE`) to provide more meaningful context for social media sharing.
- Add snackbar confirmation in `CacheDetailActivity`, `CacheListActivity`, `CompassActivity`, and `UnifiedMapActivity` after the user posts a log.
- Add `logVisitForResult()` in `Geocache` to launch the log activity with a result callback.
- Update `LoggingUI` to use `logVisitForResult()`.
From `CacheListActivity`:
From `CacheDetailActivity`:
From `CompassActivity`:
From `UnifiedMapActivity`:
Sharesheet:
#16882
=> #16882: Add snackbar for log visit with share option

main/src/main/java/cgeo/geocaching/log/LoggingUI.java
fixes #16969 by showing NA/NM logtypes only for caches from GC + not owned
=> don't show NA/NM logtypes for own caches (fixes #16969)

main/src/main/java/cgeo/geocaching/AbstractDialogFragment.java, main/src/main/java/cgeo/geocaching/CacheDetailActivity.java, main/src/main/java/cgeo/geocaching/CachePopupFragment.java, main/src/main/java/cgeo/geocaching/ui/CacheDetailsCreator.java
- Adds long-tap actions to cache infosheet: GC code, cache title, coordinates, personal note/hint
- Switches long-tap for emoji selector to short tap to resolve the collision
=> Add long-tap action to cache infosheet (fix #17003)

main/src/main/java/cgeo/geocaching/SearchActivity.java, main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/res/layout/cacheslist_item_select.xml, main/src/main/res/layout/search_activity.xml, main/src/main/res/layout/search_suggestion.xml, main/src/main/res/values/preference_keys.xml, main/src/main/res/values/strings.xml
Remembers the last entered search string verbatim, for 
- geocode search (where strings currently only got stored on successful searches), and for
- address search (where only the resulting geocoded string got stored currently
Fixes #16970
=> Remember most recent search item verbatim for geocode and address

main/src/main/java/cgeo/geocaching/connector/oc/OkapiClient.java
Define the open Caches at OCPL as follow:
~~~
'Moving'   =>  CacheType.LOCATIONLESS
'Other'    =>  CacheType.UNKNOWN
'Podcast'  =>  CacheType.VIRTUAL
'Own'      =>  CacheType.LOCATIONLESS
~~~
fixes #16992
see https://github.com/opencaching/opencaching-pl/issues/2520
@andrixnet OK?
=> Add some missing OC cache types

main/src/main/java/cgeo/geocaching/list/StoredList.java
Moving the lists from the "last selection" to the "top group", while current lists remain unchecked as well in the "top group" to easily "recheck" them.
(Un)checking list-entries does not move the lists to the / from the "top group"
Open "Pick the lists" 
Select "Last selection": add checked last selected list (keep original selection unchecked at top)
Change selection does not move 
Select "Last selection" again (no more moving)
fix #17007
=> Fix  #17007:  Move "recently used" lists in list selection dialog to the top

main/src/androidTest/java/cgeo/geocaching/connector/gc/GCParserTest.java, main/src/androidTest/java/cgeo/geocaching/models/GeocacheTest.java, main/src/main/java/cgeo/geocaching/connector/al/ALApi.java, main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java, main/src/main/java/cgeo/geocaching/connector/su/SuParser.java, main/src/main/java/cgeo/geocaching/files/GPXParser.java, main/src/main/java/cgeo/geocaching/models/Geocache.java, main/src/main/java/cgeo/geocaching/storage/DataStore.java
Don't store parsed waypoints directly in db. Otherwise the merging of already stored information gets lost.
Storing waypoints is done in saveCache after merging already stored cache anyway
fix #16193 
fix #16932
=> Merge alc waypoints with already stored ones

main/src/main/java/cgeo/geocaching/utils/MapMarkerUtils.java
`getStageNumberMarker()` sometimes fails with `ResourceNotFoundException`, which can happen if given stage number is 0 somehow (imported lab stage?). PR adds a safeguard for this.
=> Fix crash on lab stageNum == 0

main/src/androidTest/java/cgeo/geocaching/log/LogEntryTest.java, main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java, main/src/main/java/cgeo/geocaching/log/LogEntry.java, main/src/main/java/cgeo/geocaching/storage/DataStore.java, main/src/main/java/cgeo/geocaching/utils/TextUtils.java, main/src/test/java/cgeo/geocaching/utils/TextUtilsTest.java
Keep time of time-stamp of stored own logs, if online log has same date.
Also for offline log, if the log-text is empty (to support keeping time-stamp for logging via field-notes)
fix #9653
fix #16898
=> Preserve time-stamp of own log on refreshing the cache (fix #9653)

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java, main/src/main/java/cgeo/geocaching/settings/Settings.java, main/src/main/java/cgeo/geocaching/settings/fragments/BasePreferenceFragment.java, main/src/main/java/cgeo/geocaching/ui/CompassMiniView.java, main/src/main/java/cgeo/geocaching/ui/NavigationActionProvider.java, main/src/main/res/layout/compass_action_view.xml, main/src/main/res/values/preference_keys.xml, main/src/main/res/values/strings.xml, main/src/main/res/xml/preferences_cachedetails.xml
- Replace the static compass icon in the action bar of `CacheDetailActivity` with a dynamic, rotating `CompassMiniView` with the same behavior seen in the cache list view. The click and long click actions on the compass icon still work, triggering default and secondary navigation as before.
- Add a user setting: "Show direction in cache detail view"
The user can toggle whether the dynamic compass arrow appears in the detail view. If disabled, the original compass icon will appear instead. It is enabled by default.
#431
=> #431: Add CompassMiniView in cache detail view

main/src/androidTest/java/cgeo/geocaching/test/mock/GC40.java, main/src/androidTest/res/raw/mock/GC40.html
Fixes the error found in https://ci.cgeo.org/job/cgeo-CI_PR-build/12338/testReport/cgeo.geocaching/CgeoApplicationTest/testSearchByGeocodeBasis/
(Website change, cache details seem to be stripped now, no longer returning blank lines (multiple `<br>`) at the beginning of long description)
=> Fix mocked cache with HTML at beginning of description

main/src/main/java/cgeo/geocaching/unifiedmap/layers/ElevationChart.java, main/src/main/res/values/preference_keys.xml
Allows enlarging the elevation chart's height by tapping on its title to get more details "on a view". Toggle state gets remembered.
=> Allow elevation chart to be resized

main/src/main/java/cgeo/geocaching/apps/navi/GoogleNavigationApp.java
Replaces outdated `ll` parameter for GoogleNavigationApp by `q` parameter
=> Replace outdated parameter in GoogleNavigationApp (rel. to #15978)

main/src/main/java/cgeo/geocaching/wherigo/WherigoViewUtils.java
fix #17115: Wherigo, consider html symbols when showing author and cartridge name in cartridge selector
=> fix #17115: Wherigo, consider html symbols when showing author and cartridge name in cartridge selector

main/src/androidTest/java/cgeo/geocaching/log/LogEntryTest.java, main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java, main/src/main/java/cgeo/geocaching/log/LogEntry.java, main/src/main/java/cgeo/geocaching/storage/DataStore.java, main/src/main/java/cgeo/geocaching/utils/TextUtils.java, main/src/test/java/cgeo/geocaching/utils/TextUtilsTest.java
Keep time of time-stamp of stored own logs, if online log has same date.
Also for offline log, if the log-text is empty (to support keeping time-stamp for logging via field-notes)
fix #9653
fix #16898
PR #16930 didn't save the online logs, if no merging with already offline logs was necessary, so no new online logs were saved which led to #17064
PR #17067 reverted this wrong behavior, this PR always saves the online logs
=> Preserve time-stamp of own log on refreshing the cache (fix #9653) (restore pr #16930)

main/build.gradle, main/src/main/res/values-v35/themes.xml, main/src/main/res/values/themes.xml
As discussed in our last dev meeting: Let's try targetSDK 35 early in the current dev cycle, as some breaking changes are to be expected from reading the docs.
~One is already very visible directly after start: The new edge-to-edge mode hides UI elements under the topbar (eg: in settings), therefore setting WIP label for now.~ (that seems to be fixed as of Jul 5th)
=> Set targetSDK to 35

main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java
Check for serviceLogId, because log was recreated and could hence not found via `contains(log)`
Fix #17135
=> fix #17135: Avoid doubled log-entries

main/src/main/java/cgeo/geocaching/CreateShortcutActivity.java
Don't know if this is just a me-problem, but our c:geo shortcuts did look really ugly, at least on my device:
Remove our custom painted c:geo logo from the shortcut icon, and let the launcher badge the icon instead (some launchers still will not, but that's IMHO not our problem):
=> remove self-painted overlay from shortcuts (fix #12649)

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java, main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GeoItemLayer.java
UnifiedMap, GeoItemLayer: add better logging to analyze problems with nonclickable items
This PR improves logging inside UnifiedMapActivity and GeoItemLayer. It is designed to analyze the problem with non-clickable items which @murggel was experiencing. It is at the same time designed in a way that it can stay in the code permanently (and might be useful to analyze future, not-yet-known problems).
=> UnifiedMap, GeoItemLayer: add better logging to analyze problems with nonclickable items

main/src/main/java/cgeo/geocaching/wherigo/WherigoPushDialogProvider.java
fix #17232: Wherigo, display no symbols on push dialog buttons when not default ok button
=> fix #17232: Wherigo, display no symbols on push dialog buttons when not default ok button

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
Remove the restriction on showing only caches with valid coordinates on the map.
Now caches with valid coordinates or having at least one waypoint with valid coordinates are shown.
So generated waypoints are shown on the map (their cache doesn't have a coordinate)
fix #13683
Implementing  a function to the map to display multiple waypoints as mentioned from @eddiemuc  in https://github.com/cgeo/cgeo/issues/13683#issuecomment-1321104426 was not necessary IMHO, since that implementation is already contained in displaying a single cache. 
So that means a more complex refactoring of displaying only waypoints on the map....
So for displaying a single waypoint there is already a cache for that purpose, which contains the waypoint.
=> fix #13683: Show generated waypoints on map

main/src/main/java/cgeo/geocaching/CacheListActivity.java, main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceSystemFragment.java, main/src/main/java/cgeo/geocaching/ui/ContinuousRangeSlider.java, main/src/main/java/cgeo/geocaching/ui/SimpleItemListModel.java, main/src/main/java/cgeo/geocaching/ui/ViewUtils.java, main/src/main/java/cgeo/geocaching/ui/dialog/ContextMenuDialog.java, main/src/main/java/cgeo/geocaching/ui/dialog/SimpleDialog.java, main/src/main/java/cgeo/geocaching/ui/dialog/SimpleDialogExamples.java, main/src/main/java/cgeo/geocaching/utils/offlinetranslate/TranslatorUtils.java, main/src/main/res/values/preference_keys.xml, main/src/main/res/values/strings.xml, main/src/main/res/xml/preferences_system.xml
SimpleDialog: cleanup
While looking at #17264 I realized that there are some long-overdue refactorings necessary to SimpleDialog. AMong some minor cleanups, SimpleDialog still didn't use the JDK function classes (Consumer, Predicate and so on) but instead our own versions (Func1, Action1 etc). This is no longer necessary for a long time.
As part of this I created a (currently sketchy) Test Dialog class SImpleDialogTest. It helped me greatly already to identify two bugs. I would love to keep it in code for future changes to SimpleDialog to easily test them. I made this accessible through a new Button in System dialog right under "View Database". This seemed to fit since "View Database" is also a development-nrea option. Hope thats ok..
=> SimpleDialog: cleanup

main/src/main/java/cgeo/geocaching/storage/DataStore.java
After keeping the log-time-stamp of own logs, they are now always newer than the ones fetched from the server and so sorting should only consider only the day. Then sorting during the day after log-Id
fix #17291
=> fix #17291: Sort logs with different time-stamps correctly

main/src/androidTest/java/cgeo/geocaching/connector/gc/GCParserTest.java, main/src/androidTest/java/cgeo/geocaching/connector/gc/TrackablesTest.java, main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceServiceGeocachingComFragment.java, main/src/main/java/cgeo/geocaching/utils/ImageUtils.java, main/src/main/res/values/preference_keys.xml, main/src/main/res/values/strings.xml, main/src/main/res/xml/preferences_services_geocaching_com.xml
GC has 5 sizes for each image and we currently have a logic for the user to select to load a specific one of those (actually not for thumb as that one is tiny and of no use). However there's currently no option to NOT rewrite the request but instead load whatever the listing owner used when creating the listing.
Also setting that new "unchanged" size as default as that's what you get with any other app.
=> add an option to not change the size of images loaded from GC

main/src/main/res/values/strings.xml
Info: Multiple substitutions specified in non-positional format of string resource string/waypoint_added_current_location.
See eg. https://ci.cgeo.org/job/cgeo-CI_PR-build/12850/console
=> fix lint string multiple parameters

main/src/main/res/values-v35/themes.xml
Found coincidentally, that the feature edge-to-edge enforcement might cause UI problems on Android 15 for some apps.
The indicated workaround was to opt out of this feature on Android 15.
This is most probably not a fix and AFAICS this will not work for Android 16 to opt out.
This means the underlying issue needs to be resolved to make c:geo compatible with this edge-to-edge feature
I did quickly run it on an emulator and the UI glitches in text field paddings are gone.
Could not check the map top padding as this problem was not visible in the emulator even before.
#17157 and maybe #17151
Did not record the precise source for this workaround, however this might be a starting point for further investigation:
https://developer.android.com/about/versions/15/behavior-changes-15?hl=de#edge-to-e …
=> Related to #17157 - Workaround for UI glitch API35

main/src/main/java/cgeo/geocaching/models/Geocache.java, main/src/main/java/cgeo/geocaching/storage/DataStore.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
rel to #10927: Live Map Status updates on found, disabled and archived
This PR serves three different purposes which however are interconnected code-wise:
* Issue #10927: fixes status update from live data for stored caches not only for disabled but also for archived and found caches
* A bug I noticed myself: when a stored cache is logged from c:geo, database is now updated too
* #17358: Sometimes cache items become "unclickable" on map. Analysis shows that this might be related to caches sometimes "loosing" their coordinates (for yet unknown reasons). This PR adds logging to analyze this case further.
=> rel to #10927: Live Map Status updates on found, disabled and archived

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
Show waypoints for mapType which enableLiveMap, not only for visible caches.
So waypoints in the visible area are shown, even if the cache-coordinates are outside of the considered viewport
fix #17311
=> fix #17311: Show waypoints for mapType which enableLiveMap, not only for visible caches.

main/src/main/java/cgeo/geocaching/unifiedmap/AbstractMapFragment.java
fixes #17297 by adding an explicit numm-check in case the fragment is destroyed in the meantime
=> null check

main/build.gradle, main/src/main/java/cgeo/geocaching/CacheDetailActivity.java, main/src/main/java/cgeo/geocaching/activity/AbstractActionBarActivity.java, main/src/main/java/cgeo/geocaching/activity/AbstractActivity.java, main/src/main/java/cgeo/geocaching/activity/AbstractNavigationBarMapActivity.java, main/src/main/java/cgeo/geocaching/filters/gui/GeocacheFilterActivity.java, main/src/main/java/cgeo/geocaching/settings/SettingsActivity.java, main/src/main/res/layout/cache_filter_activity.xml, main/src/main/res/layout/generic_recyclerview.xml, main/src/main/res/layout/tabbed_viewpager_activity.xml, main/src/main/res/layout/tabbed_viewpager_activity_refreshable.xml, main/src/main/res/values-v35/themes.xml, main/src/main/res/values/themes.xml
First steps in adapting c:geo to the new API 35 edge to edge enforcement. It mimics today's behavior, not making any actual use of edge to edge yet.
Current status (list probably to be extended):
Especially for map view, edge to edge mode might be useful, see the following sample screen:
(~Some elements are missing yet (bug), eg. current target (for cache map etc.), distance infos and (maybe) filter bar.~ => implemented meanwhile, screenshot is outdated.)
This is a screenshot with "hide action bar on tap" active, normally the action bar would be shown as well. But IMHO the immersive effect is quite useful on map view, therefore I'd like to propose some further steps here - will create a separate issue for it for further discussion. (Edit: See #17356)
=> Adapt c:geo to edge2edge enforcement of target API 35

main/src/androidTest/java/cgeo/geocaching/utils/ColorUtilsTest.java, main/src/main/java/cgeo/geocaching/activity/AbstractActivity.java, main/src/main/java/cgeo/geocaching/utils/ColorUtils.java
Due to the change to lighter action-bar color and using dark text color, the text on the systembar is hardly visible
This PR changes the setting windowLightStatusBar and windowLightNavigationBar accordingly
rel #17203
=> Use dark text on light systembars (rel #17203)

main/src/main/java/cgeo/geocaching/models/IndividualRoute.java, main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
Avoid clearing / updating route, if it is already loading / updating from database
(but I don't know yet, why / how that happens, has something to do with AndroidRxUtils.andThenOnUi in IndividualRoute::reloadRoute
fix #15412
=> fix #15412: avoid doubled route items

main/AndroidManifest.xml
Ignore lint warnings about missing domain validation for these links, as we will never get domain attribution to c:geo for them...
=> fix lint: AppLinkWarning

main/src/main/java/cgeo/geocaching/wherigo/WherigoLocationProvider.java
Wherigo Player: provide location accuracy/precision
Via support I was informed that some cartridges need the location accuracy/precision to function. This PR lets the player provide this value.
=> Wherigo Player: provide location accuracy/precision
