main/AndroidManifest.xml
main/src/main/java/cgeo/geocaching/InstallWizardActivity.java
main/src/main/java/cgeo/geocaching/permission/PermissionContext.java
main/src/main/res/values/strings.xml

fix #13988: reenable write external storage permission for older sdks

fix #13988: reenable write external storage permission for older sdks

---

main/src/main/java/cgeo/geocaching/MainActivity.java
main/src/main/java/cgeo/geocaching/ui/LocationStatusView.java

fix #13991: force coordinates in compass also on address in main

fix #13991: force coordinates in compass also on address in main

---

main/src/main/java/cgeo/geocaching/utils/ImageUtils.java

fix #14000: remove imageuri-not-readable messages for every image

fix #14000: remove imageuri-not-readable messages for every image

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
main/src/main/java/cgeo/geocaching/ui/dialog/SimpleDialog.java
main/src/main/res/layout/cachedetail_description_page.xml
main/src/main/res/layout/cachedetail_waypoints_page.xml
main/src/main/res/layout/dialog_custom_title_content.xml
main/src/main/res/values/strings.xml

fix #13883
setting as draft, as I couldn't test my PR cause of #14011

align margins and optimize out of sync dialog 

---

main/src/main/java/cgeo/geocaching/maps/RouteTrackUtils.java
main/src/main/java/cgeo/geocaching/ui/ColorPickerUI.java

show correct initial track color (fix #14018)

show correct initial track color (fix #14018)

---

main/src/main/java/cgeo/geocaching/ui/ColorPickerUI.java
main/src/main/res/layout/preference_colorpicker.xml

[ColorPickerUI] show opaqueness as percentage value

---

main/src/main/java/cgeo/geocaching/Intents.java
main/src/main/java/cgeo/geocaching/downloader/AbstractMapDownloader.java
main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

Map downloader notifies maps on successful receiving of map file, so that they can update their map lists

Update map list on receiving map file (fix #14003)

---

main/src/main/java/cgeo/geocaching/downloader/AbstractMapDownloader.java
main/src/main/java/cgeo/geocaching/downloader/AbstractThemeDownloader.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/RenderThemeHelper.java

Do not install a map or theme downloaded via integrated downloader automatically

Do not install downloaded map/theme automatically (fix #14002)

---

main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/PositionLayer.java

Fix crash reported on Play stats, happening on drawing position heading marker for Mapsforge being null

Fix crash on drawing position marker

---

main/src/main/java/cgeo/geocaching/brouter/core/ProfileCache.java
main/src/main/java/cgeo/geocaching/maps/routing/RouteOptimizationHelper.java
main/src/main/java/cgeo/geocaching/maps/routing/RouteSortActivity.java
main/src/main/java/cgeo/geocaching/ui/dialog/SimpleProgressDialog.java
main/src/main/res/layout/progressdialog.xml
main/src/main/res/menu/menu_ok_cancel.xml
main/src/main/res/values/preference_keys.xml
main/src/main/res/values/strings.xml

~WIP~ Text outdated, see updates below...
This is a basic implementation of a route optimization routine. Not much of a UI, so far, only a button to start it, and results are written to log only. PR implements both hill climbing algorithm and simulated annealing algorithm, as they have different characteristics depending on input set.
Tested it with route sets of 5, 12, 48 and 68 points. For the two larger sets time to calculate the initial distance matrix takes pretty long (four minutes in the emulated device, whereas the two search runs take less than 50s combined in this case).
Some questions:
- ~Is BRouter able to do multiple route calculations in parallel / is it thread safe?~ => yes, except creating `rawtrack` files (which are not relevant here)
- ~How to distribute the N*(N-1) …

Route optimization (experimental feature)

---

main/src/main/java/cgeo/geocaching/models/Route.java

fix #14028: fix nonconnected routes from gpx
@fm-sys : this would fix the problem on release. Codechange is almost same as on master (just one class name changed due to refactoring)

fix #14028: fix nonconnected routes from gpx

---

main/src/main/java/cgeo/geocaching/maps/MapUtils.java
main/src/main/res/values/strings.xml

Replace hard-coded string "Checking available routing data..." by translatable string

Fix constant string / make string translatable

---

main/src/main/java/cgeo/geocaching/maps/AbstractMap.java
main/src/main/java/cgeo/geocaching/maps/CGeoMap.java
main/src/main/java/cgeo/geocaching/maps/RouteTrackUtils.java
main/src/main/java/cgeo/geocaching/maps/Tracks.java
main/src/main/java/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/AbstractRouteLayer.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/RouteLayer.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/TrackLayer.java
main/src/main/java/cgeo/geocaching/settings/ColorpickerPreference.java
main/src/main/java/cgeo/geocaching/storage/extension/Trackfiles.java
main/src/main/java/cgeo/geocaching/ui/ColorPickerUI.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/utils/MapLineUtils.java
main/src/main/java/cgeo/geocaching/utils/functions/Action4.java
main/src/main/res/layout/preference_colorpicker.xml
main/src/main/res/layout/preference_colorpicker_widget.xml
main/src/main/res/values/attrs.xml
main/src/main/res/values/numbers.xml
main/src/main/res/values/strings.xml
main/src/main/res/xml/preferences_map.xml

fix #14019
The "select track color" dialog will show an additional slider for customizing the track width.
Example:

support setting line width per track (fix #14019)

---

main/src/main/res/menu/menu_ok_cancel.xml
main/src/main/res/values/strings.xml

Replace a string constant by translatable string

Make string constant translatable

---

main/src/main/java/cgeo/geocaching/maps/routing/RouteSortActivity.java

Suppress lint message complaining about string concat in a place where it doesn't make sense + prevent a possible NPE in the same place.

Fix possible NPE + suppress lint about string concat

---

main/src/main/java/cgeo/geocaching/maps/CGeoMap.java
main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapProvider.java
main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapView.java

Adds Google Terrain as map provider to GMv2 and do some clean up

Add Google Terrain as map provider to GMv2 (fix #14043)

---

main/src/main/java/cgeo/geocaching/location/Viewport.java
main/src/main/java/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/main/java/cgeo/geocaching/models/geoitem/GeoGroup.java
main/src/main/java/cgeo/geocaching/models/geoitem/GeoIcon.java
main/src/main/java/cgeo/geocaching/models/geoitem/GeoItem.java
main/src/main/java/cgeo/geocaching/models/geoitem/GeoPrimitive.java
main/src/main/java/cgeo/geocaching/settings/Settings.java
main/src/main/java/cgeo/geocaching/unifiedmap/AbstractUnifiedMapView.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GeoItemLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GeoItemTestLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GoogleV2GeoItemLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/IProviderGeoItemLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeV6GeoItemLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeVtmGeoItemLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsView.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmView.java
main/src/main/java/cgeo/geocaching/utils/AsynchronousMapWrapper.java
main/src/main/java/cgeo/geocaching/utils/ImageUtils.java
main/src/main/res/values/preference_keys.xml
main/src/test/java/cgeo/geocaching/utils/GeoJsonUtilsTest.java

unifiedmap: create unified geoitemlayer

unifiedmap: create unified geoitemlayer

---

main/src/main/java/cgeo/geocaching/location/Geopoint.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/TapHandlerLayer.java
main/src/main/java/cgeo/geocaching/models/geoitem/GeoGroup.java
main/src/main/java/cgeo/geocaching/models/geoitem/GeoIcon.java
main/src/main/java/cgeo/geocaching/models/geoitem/GeoItem.java
main/src/main/java/cgeo/geocaching/models/geoitem/GeoItemUtils.java
main/src/main/java/cgeo/geocaching/models/geoitem/GeoPrimitive.java
main/src/main/java/cgeo/geocaching/models/geoitem/GeoStyle.java
main/src/main/java/cgeo/geocaching/unifiedmap/AbstractUnifiedMapView.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GeoItemLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GeoItemTestLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GoogleV2GeoItemLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/IProviderGeoItemLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeV6GeoItemLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeVtmGeoItemLayer.java
main/src/main/java/cgeo/geocaching/utils/GeoJsonUtils.java

Unified Geoitem Layer: first version of tap-handling

Unified Geoitem Layer: first version of tap-handling

---

main/src/main/java/cgeo/geocaching/CacheListActivity.java
main/src/main/java/cgeo/geocaching/activity/AbstractBottomNavigationActivity.java
main/src/main/java/cgeo/geocaching/enumerations/CacheListType.java

allow opening recently viewed caches as list (fix #14049)

---

cgeo-contacts/build.gradle
main/build.gradle
mapswithme-api/build.gradle

Set `compileSDK` to 33 to be able to upgrade some dependencies.

Set compileSDK to 33

---

main/AndroidManifest.xml
main/src/main/java/cgeo/geocaching/Intents.java
main/src/main/java/cgeo/geocaching/MainActivity.java
main/src/main/java/cgeo/geocaching/enumerations/QuickLaunchItem.java
main/src/main/java/cgeo/geocaching/models/InfoItem.java
main/src/main/java/cgeo/geocaching/settings/Settings.java
main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceAppearanceFragment.java
main/src/main/java/cgeo/geocaching/ui/CheckableItemSelectActivity.java
main/src/main/res/layout/info_item.xml
main/src/main/res/values/preference_keys.xml
main/src/main/res/xml/preferences_appearence.xml

Make quick launch buttons on home screen sortable.
This is also a prerequisite for upcoming work on #13278.

Make quicklaunch buttons sortable

---

main/src/main/java/cgeo/geocaching/CacheListActivity.java
main/src/main/java/cgeo/geocaching/MainActivity.java
main/src/main/java/cgeo/geocaching/enumerations/CacheListInfoItem.java
main/src/main/java/cgeo/geocaching/enumerations/QuickLaunchItem.java
main/src/main/java/cgeo/geocaching/maps/routing/RouteSortActivity.java
main/src/main/java/cgeo/geocaching/settings/Settings.java
main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceOfflinedataFragment.java
main/src/main/java/cgeo/geocaching/ui/CacheListAdapter.java
main/src/main/java/cgeo/geocaching/ui/CheckableItemSelectActivity.java
main/src/main/java/cgeo/geocaching/utils/Formatter.java
main/src/main/res/values/preference_keys.xml
main/src/main/res/values/strings.xml
main/src/main/res/xml/preferences_offlinedata.xml

- Make cache list info items configurable
- Add migration for quicklaunch items and showListsInCacheList

Make cache list info items configurable

---

main/src/main/java/cgeo/geocaching/activity/AbstractBottomNavigationActivity.java
main/src/main/java/cgeo/geocaching/settings/Settings.java
main/src/main/res/values/strings.xml

Add possibility to clear recently viewed caches and handle special case that no caches were recently viewed.

add possibility to clear recently viewed caches

---

main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapView.java

Partly resolve #14066 by trying to remove false triggerings of action bar hide on double tapping or tapping zoom controls. Implemented for GMv2 only to test this solution.
@fm-sys 
Can you give it a try in your environment? Thanks.

Resolve false triggerings of action bar hide (rel. to #14066)

---

main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapView.java
main/src/main/java/cgeo/geocaching/utils/FilterUtils.java

Replaces #14080
Use view animator for layout changes caused by actionbar toggling

Mitigate hiding of compass in GMv2 and add animations (rel. to 14066)

---

main/src/main/java/cgeo/geocaching/unifiedmap/AbstractPositionLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsPositionLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgePositionLayer.java

apply track width and color at unified map

apply track width and color at unified map

---

main/src/main/java/cgeo/geocaching/models/geoitem/GeoGroup.java
main/src/main/java/cgeo/geocaching/models/geoitem/GeoIcon.java
main/src/main/java/cgeo/geocaching/models/geoitem/GeoItem.java
main/src/main/java/cgeo/geocaching/models/geoitem/GeoItemUtils.java
main/src/main/java/cgeo/geocaching/models/geoitem/GeoPrimitive.java
main/src/main/java/cgeo/geocaching/models/geoitem/GeoStyle.java
main/src/main/java/cgeo/geocaching/models/geoitem/ToScreenProjector.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GeoItemLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GeoItemTestLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GoogleV2GeoItemLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/IProviderGeoItemLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeV6GeoItemLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeVtmGeoItemLayer.java
main/src/main/java/cgeo/geocaching/utils/AsynchronousMapWrapper.java
main/src/main/java/cgeo/geocaching/utils/CommonUtils.java
main/src/test/java/cgeo/geocaching/models/geoitem/GeoItemTest.java
main/src/test/java/cgeo/geocaching/test/AssertUtils.java
main/src/test/java/cgeo/geocaching/unifiedmap/geoitemlayer/GeoItemLayerTest.java

GeoItemLayer: add unit tests and performance enhancements

GeoItemLayer: add unit tests and performance enhancements

---

build.gradle

agp downgrade

---

main/src/main/java/cgeo/geocaching/enumerations/CacheListInfoItem.java
main/src/main/java/cgeo/geocaching/enumerations/QuickLaunchItem.java
main/src/main/java/cgeo/geocaching/models/InfoItem.java
main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceOfflinedataFragment.java

Make sure info items are initialized when calling settings, even when CacheList etc. have not been called before

Initialize InfoItem pref on first run (rel. to 14087)

---

main/src/main/res/layout/unifiedmap_googlemaps.xml
main/src/main/res/layout/unifiedmap_mapsforgevtm.xml

UnifiedMap: Remove a layer of layout elements no longer needed, similar to what has been done with #13188 for CGeoMap/NewMap.

UnifiedMap: Remove unnecessary layout layer

---

main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

[NewMap] don't hide actionbar on long press

[NewMap] don't hide actionbar on long press

---

main/src/main/java/cgeo/geocaching/ui/CheckableItemSelectActivity.java
main/src/main/res/layout/checkable_item_select_activity.xml
main/src/main/res/layout/info_header.xml
main/src/main/res/values/strings.xml

Use drag & drop to select entries (instead of using buttons) as suggested in #14087

Two row-layout for CheckableItemSelectActivity (fix #14087)

---

main/src/main/java/cgeo/geocaching/files/GPXTrackOrRouteImporter.java
main/src/main/java/cgeo/geocaching/location/GeoObjectList.java
main/src/main/java/cgeo/geocaching/location/GeopointConverter.java
main/src/main/java/cgeo/geocaching/maps/AbstractMap.java
main/src/main/java/cgeo/geocaching/maps/CGeoMap.java
main/src/main/java/cgeo/geocaching/maps/RouteTrackUtils.java
main/src/main/java/cgeo/geocaching/maps/Tracks.java
main/src/main/java/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/AbstractRouteLayer.java
main/src/main/java/cgeo/geocaching/models/Route.java
main/src/main/java/cgeo/geocaching/models/geoitem/GeoGroup.java
main/src/main/java/cgeo/geocaching/models/geoitem/GeoItemUtils.java
main/src/main/java/cgeo/geocaching/models/geoitem/GeoStyle.java
main/src/main/java/cgeo/geocaching/models/geoitem/IGeoItemSupplier.java
main/src/main/java/cgeo/geocaching/unifiedmap/AbstractPositionLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/RouteLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GeoItemLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsPositionLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgePositionLayer.java
main/src/main/java/cgeo/geocaching/utils/AsynchronousMapWrapper.java
main/src/main/java/cgeo/geocaching/utils/CommonUtils.java

Unified GeoItemLayer: refactoring and first version of RouteLayer

Unified GeoItemLayer: refactoring and first version of RouteLayer

---

main/src/androidTest/java/cgeo/geocaching/downloader/DownloaderTest.java

fix failing test for Freizeitkarte - they added a 4th theme

---

main/src/main/java/cgeo/geocaching/downloader/MapDownloaderOpenAndroMapsThemes.java

fix update check for Voluntary/Velocity themes

---

main/src/main/java/cgeo/geocaching/ui/ViewUtils.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/utils/FilterUtils.java

- Fix loading indicator position when actionBar is hidden
- Fix distance info position when actionBar is hidden

Fix loading indicator position when ActionBar is hidden (fix #14133)

---

main/src/androidTest/java/cgeo/geocaching/downloader/DownloaderTest.java

Test needs to be fixed on `release` branch as it checks some external change not related to c:geo internal code changes

Fix fzk tests on release branch

---

main/src/main/java/cgeo/geocaching/enumerations/CacheSize.java

fixes #13795
not sure whether this should be merged. See https://github.com/cgeo/cgeo/issues/13795#issuecomment-1369584410

differentiate size "not chosen" and "other" for GC.com

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java

Preserve scroll position when using "render complete description" button
https://user-images.githubusercontent.com/64581222/229358204-c01caef8-3529-4e27-a3f4-a3a5154546d8.mp4

rel. to #14158 - preserve scroll position

---

main/src/main/java/cgeo/geocaching/maps/routing/RouteOptimizationHelper.java

fixes error in round-trip route optimization that cause it to be linear instead of round-trip

fix round-trip route optimization

---

main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/main/java/cgeo/geocaching/maps/routing/RouteOptimizationHelper.java

Avoid crash on cancelling route optimization

Avoid crash on cancelling route optimization (fix #14173)

---

main/src/main/java/cgeo/geocaching/utils/Formatter.java

Mitigation for truncated smileys on first line when a smiley line wraps
(see https://github.com/cgeo/cgeo/issues/14163#issuecomment-1501177328 for details)

Avoid truncation of first smiley row on line breaks (fix #14163)

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
main/src/main/java/cgeo/geocaching/HandleLocalFilesActivity.java
main/src/main/java/cgeo/geocaching/brouter/core/KinematicPrePath.java
main/src/main/java/cgeo/geocaching/brouter/core/RoutingEngine.java
main/src/main/java/cgeo/geocaching/brouter/core/StdModel.java
main/src/main/java/cgeo/geocaching/brouter/mapaccess/DirectWeaver.java
main/src/main/java/cgeo/geocaching/brouter/util/BitCoderContext.java
main/src/main/java/cgeo/geocaching/brouter/util/SortedHeap.java
main/src/main/java/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/RenderThemeHelper.java
main/src/main/java/cgeo/geocaching/settings/Settings.java

Code cleanup: Remove a couple of unused local vars / class members / class methods

Codacy: remove some unused vars/methods

---

main/src/main/java/cgeo/geocaching/maps/MapUtils.java
main/src/main/java/cgeo/geocaching/maps/RouteTrackUtils.java
main/src/main/java/cgeo/geocaching/maps/Tracks.java
main/src/main/java/cgeo/geocaching/unifiedmap/AbstractPositionLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/AbstractUnifiedMapView.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapViewModel.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GeoItemTestLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/ILayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsPositionLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsView.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/IndividualRouteLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/PositionLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/TracksLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgePositionLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmView.java
main/src/main/java/cgeo/geocaching/utils/ConstantLiveData.java
main/src/main/java/cgeo/geocaching/utils/Event.java

This migrates only the track part, not yet routes...

migrate tracks layer for unified map

---

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmView.java

Animate position and zoom changes on VTM

Animate position changes on VTM

---

main/src/main/java/cgeo/geocaching/models/geoitem/GeoPrimitive.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GeoItemLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GeoItemTestLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GoogleV2GeoItemLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/IProviderGeoItemLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeV6GeoItemLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeVtmGeoItemLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgePositionLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmView.java
main/src/main/java/cgeo/geocaching/utils/AsynchronousMapWrapper.java
main/src/main/java/cgeo/geocaching/utils/GroupedList.java
main/src/test/java/cgeo/geocaching/unifiedmap/geoitemlayer/GeoItemLayerTest.java
main/src/test/java/cgeo/geocaching/utils/GroupedListTest.java

Unifiedmap / GeoItemLayer: enhance zlevel support

Unifiedmap / GeoItemLayer: enhance zlevel support

---

main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsView.java

Show compass rose on rotated UnifiedMap GoogleMaps map, even if "hide action bar on tap" is enabled

UnifiedMap: Show compass rose on rotated GM (fix #14214)

---

main/src/main/java/cgeo/geocaching/downloader/DownloadSelectorActivity.java
main/src/main/java/cgeo/geocaching/downloader/DownloadSelectorMapListTask.java
main/src/main/java/cgeo/geocaching/downloader/DownloadSelectorMapUpdateCheckTask.java

Make AsyncTask MapListTask static to prevent leaks

Extract DownloadSelector tasks to prevent leaks

---

main/lint.xml

Add CustomSplashScreen to lint ignore list

Fix lint: accept custom splash screen

---

main/src/main/java/cgeo/geocaching/log/LogTrackableActivity.java
main/src/main/java/cgeo/geocaching/log/LogTrackableTask.java

Extract LogTrackableActivity.Poster task to prevent leaks

Extract LogTrackableActivity.Poster task

---

main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java
main/src/main/java/cgeo/geocaching/log/LogCacheTask.java

Extract LogCache.Poster task to prevent leaks

Extract LogCacheActivity.Poster task

---

main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

Attempts to fix issue #12225 by reverting a single code line change from 4245f781b3bfc3efd7fa088cb50fc4760b516a7c.

NewMap: Do not fully reset target on enabling live mode (rel. to #12225)

---

main/src/main/java/cgeo/geocaching/connector/oc/OkapiClient.java

fix #14254: add online attribute filtering for opencaching

fix #14254: add online attribute filtering for opencaching

---

main/src/main/java/cgeo/geocaching/files/GPXTrackOrRouteImporter.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/GeoObjectLayer.java

rel to #14264: correct problems in scanning geojson simplestyle properties and merging with defaults.
Also sets the default fill color to a transparent version of the default stroke color.
Example:
Geojson for example:
```
{
"type": "FeatureCollection",
"features": [
{
"type": "Feature",
"properties": {
"stroke": "#4931bf",
"stroke-width": 6,
"stroke-opacity": 0.8,
"fill": "#eeff00",
"fill-opacity": 0.5
},
"geometry": {
"coordinates": [
[
[
-16.98173915416504,
32.7671270233774
],
[
-16.98173915416504,
32.705140585702398
],
[
-16.90879275322979,
32.705140585702398
],
[
-16.90879275322979,
32.7671270233774
],
[
-16.98173915416504,
32.7671270233774
]
]
],
"type": "Polygon"
},
"id": 0
},
{
"type": "Feature",
"properties": {
"marker-color": "#cd2323",
"marker-size": "medium"
},
"geometry": { …
```

rel to #14264: correct problems in scanning geojson simplestyle properties and merging with defaults

---

main/src/main/java/cgeo/geocaching/connector/ILoggingWithFavorites.java
main/src/main/java/cgeo/geocaching/connector/UserInfo.java
main/src/main/java/cgeo/geocaching/connector/gc/GCLoggingManager.java
main/src/main/java/cgeo/geocaching/connector/oc/OCApiLiveConnector.java
main/src/main/java/cgeo/geocaching/connector/oc/OkapiClient.java
main/src/main/java/cgeo/geocaching/connector/oc/OkapiLoggingManager.java
main/src/main/java/cgeo/geocaching/connector/su/SuLoggingManager.java
main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java
main/src/main/res/values/strings.xml

Hello, I noticed that there is no possibility to log a cache with recommendation (aka GC favorite) on opencaching.pl site. I decided to implement this small feature. I'm not advanced in Java/android developmen, so reach me if I did something wrong.
Fixes #3879
Change bases on taking `rcmds_left` field from user query from OKAPI: https://opencaching.pl/okapi/services/users/user.html

Support for cache recommendation for opencaching based services

---

main/src/main/java/cgeo/geocaching/service/CacheDownloaderService.java
main/src/main/res/values/strings.xml

In map - store offline: If user requests to "refresh existing caches, but keep list assignments", ask for a list to store new caches in (if necessary)

Ask for list on 'refresh caches and keep list' (fix #14274)

---

main/src/main/java/cgeo/geocaching/InstallWizardActivity.java
main/src/main/java/cgeo/geocaching/MainActivity.java
main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceBackupFragment.java
main/src/main/java/cgeo/geocaching/utils/BackupUtils.java
main/src/main/java/cgeo/geocaching/utils/SystemInformation.java

Add date/time of last auto backup to sysinfo

Add date/time of last auto backup to sysinfo

---

main/src/main/java/cgeo/geocaching/network/HtmlImage.java
main/src/main/java/cgeo/geocaching/utils/ImageUtils.java

fix #14304: add basic SVG support to c:geo. Should fix issue with non-displayed certitude-logos

fix #14304: add basic SVG support

---

main/src/main/java/cgeo/geocaching/MainActivity.java

As discussed in yesterday's team meeting: Do not display gc.com error while logging in

Do not display gc.com error while logging in

---

main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/PositionLayer.java

As discussed in yesterday's team meeting: Extend logging around `createBitmap` in Mapsforge map's `PositionLayer`, trying to catch the cause for #14295.

Extended logging for Mapsforge PositionLayer (rel. to #14295)

---

main/src/main/java/cgeo/geocaching/apps/navi/AbstractPointNavigationApp.java

Suppress waypoints with empty or invalid coords in navi target selector

Suppress wpts with invalid coords in navi target selector (fix #14336)

---

main/src/main/java/cgeo/geocaching/utils/MapMarkerUtils.java

fix map marker caching

---

main/src/main/java/cgeo/geocaching/unifiedmap/layers/UnifiedTargetAndDistancesHandler.java

Fix 'super size' target distance toggling

---

main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java
main/src/main/java/cgeo/geocaching/utils/HideActionBarUtils.java

Fix initial position of compass rose when starting to rotate VTM map

Fix initial position of VTM compass rose (fix #14349)

---

main/src/main/java/cgeo/geocaching/filters/core/StoredSinceGeocacheFilter.java
main/src/main/java/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java
main/src/main/res/values/strings.xml

replace "Last details update" filter with a generic date filter as discussed in #14366
New:
Old:

replace "Last details update" filter with a generic date filter

---

main/src/main/java/cgeo/geocaching/maps/routing/RouteOptimizationHelper.java
main/src/main/java/cgeo/geocaching/storage/extension/OneTimeDialogs.java

add "don't ask again" option to Route Optimization confirmation dialog

add "don't ask again" option to Route Optimization dialog

---

main/src/main/java/cgeo/geocaching/downloader/ReceiveDownload.java

Delete partial files remaining after an interrupted copying of downloaded files

Delete broken copy on failed transfer of download (fix #10815)

---

main/src/main/java/cgeo/geocaching/maps/RouteTrackUtils.java

Code cleanup: Resort to single CSAH in RouteTrackUtils

Code cleanup: Resort to single CSAH in RouteTrackUtils

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
main/src/main/java/cgeo/geocaching/CachePopupFragment.java
main/src/main/java/cgeo/geocaching/WaypointPopupFragment.java
main/src/main/java/cgeo/geocaching/activity/AbstractActivity.java
main/src/main/java/cgeo/geocaching/connector/internal/InternalConnector.java
main/src/main/java/cgeo/geocaching/maps/CGeoMap.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/caches/AbstractCachesOverlay.java
main/src/main/java/cgeo/geocaching/maps/routing/RouteSortActivity.java
main/src/main/java/cgeo/geocaching/settings/Settings.java
main/src/main/java/cgeo/geocaching/ui/CacheListAdapter.java
main/src/main/java/cgeo/geocaching/ui/GeoItemSelectorUtils.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/GeoItemsLayer.java
main/src/main/java/cgeo/geocaching/utils/MapMarkerUtils.java
main/src/main/java/cgeo/geocaching/utils/ScalableDrawable.java
main/src/main/java/cgeo/geocaching/utils/builders/InsetBuilder.java
main/src/main/res/values/preference_keys.xml

Extend map scaling options (experimental)

Extend scaling options

---

main/src/main/java/cgeo/geocaching/log/LogTrackableActivity.java

For log type selection when logging caches we switched to `TextSpinner` component a while ago (instead of using a `ContextMenu`). 
This PR does the switch for trackable log types.
@eddiemuc 
Did I miss anything while applying `TextSpinner` here?

Replace ContextMenu by TextSpinner for TB log type (fix #11271)

---

main/src/main/java/cgeo/geocaching/brouter/BRouterConstants.java
main/src/main/java/cgeo/geocaching/brouter/BRouterWorker.java
main/src/main/java/cgeo/geocaching/brouter/IInternalRoutingService.aidl
main/src/main/java/cgeo/geocaching/brouter/InternalRoutingService.java
main/src/main/java/cgeo/geocaching/brouter/core/OsmTrack.java
main/src/main/java/cgeo/geocaching/brouter/core/ProfileCache.java
main/src/main/java/cgeo/geocaching/brouter/core/RoutingContext.java
main/src/main/java/cgeo/geocaching/brouter/core/RoutingEngine.java
main/src/main/java/cgeo/geocaching/brouter/core/VoiceHintProcessor.java
main/src/main/java/cgeo/geocaching/brouter/expressions/BExpression.java
main/src/main/java/cgeo/geocaching/brouter/expressions/BExpressionContext.java
main/src/main/java/cgeo/geocaching/brouter/mapaccess/NodesCache.java
main/src/main/res/raw/routing_dummy.brf
main/src/main/res/raw/routing_fastbike.brf
main/src/main/res/raw/routing_lookups.dat
main/src/main/res/raw/routing_trekking.brf

Updates internal BRouter engine to v1.7.1

Update internal BRouter to v1.7.1

---

main/src/androidTest/java/cgeo/geocaching/test/mock/GC40.java
main/src/androidTest/res/raw/mock/GC40.html

Fix test for temporarily disabled GC40

Fix test for temporarily disabled GC40

---

main/src/main/java/cgeo/geocaching/brouter/core/OsmTrack.java
main/src/main/java/cgeo/geocaching/brouter/core/VoiceHint.java
main/src/main/res/raw/routing_fastbike.brf
main/src/main/res/raw/routing_trekking.brf

Updates internal BRouter to v1.7.2

Updates internal BRouter to v1.7.2

---

main/build.gradle
main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/AbstractGoogleTileProvider.java

see #12023
supersedes #13258
implemented for both GMv2 and UnifiedMap GM

Update Google Maps to latest renderer (when available) (fix #12023)

---

main/src/main/java/cgeo/geocaching/maps/CGeoMap.java
main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapView.java
main/src/main/java/cgeo/geocaching/maps/interfaces/MapViewImpl.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/CoordsMarkerLayer.java
main/src/main/res/drawable/coords_indicator.xml

Implements search center indicator for GMv2 and NewMap, which will be shown on address search if you tap on the "map" icon. Related to #7783.

Implement search center indicator for GMv2 & NewMap

---

main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/GeoObjectLayer.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/Polygon.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeV6GeoItemLayer.java

fix #14391: add polygon-with-holes support for mapsforge

fix #14391: add polygon-with-holes support for mapsforge

---

main/src/main/java/cgeo/geocaching/activity/AbstractBottomNavigationActivity.java

Adds missing check for menu component used for landscape mode

Fix crash on screen rotation when using custom button (fix #14465)

---

main/src/main/java/cgeo/geocaching/unifiedmap/LayerHelper.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapViewModel.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/CoordsIndicatorLayer.java

Implements search center indicator for UnifiedMap.
In conjunction with #14449 this fixes #7783.
(BTW: First time for me working with the new UM layers and UM viewmodel - quite nice to work with!)

Implement search center indicator for Unified Map

---

main/src/main/java/cgeo/geocaching/activity/AbstractBottomNavigationActivity.java

User superclass `NavigationBarView` instead of the two involved sublasses.

Simplify component identification for screen rotation (rel. to #14467)

---

main/src/main/java/cgeo/geocaching/models/Waypoint.java

fix #14501: avoid NPE on null-List being passed as method parameter

fix #14501: avoid NPE on null-List being passed as method parameter

---

main/src/main/java/cgeo/geocaching/maps/MapSettingsUtils.java
main/src/main/java/cgeo/geocaching/settings/Settings.java

Show proximity notification master toggle when at least one notification is enabled
Fixes the specific issue mentioned in https://github.com/cgeo/cgeo/issues/13745#issuecomment-1676769453

Show PN master toggle in quick settings (rel. #13745)

---

main/src/main/res/values/strings.xml

Removes several strings no longer in use

Lint: Remove unused strings

---

organicmaps-api/src/main/java/app/organicmaps/api/OrganicMapsApi.java

Update to stay at par with OrganicMaps API (https://github.com/organicmaps/api-android)

Bring OrganicMapsApi.java at par with OrganicMaps API

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java

Crash condition introduced by https://github.com/cgeo/cgeo/pull/14359

fix crash on adding a cache to favorites, then very quickly returning to map

---

build.gradle
main/build.gradle

see https://docs.gradle.org/7.5.1/userguide/task_configuration_avoidance.html

optimize gradle

---

main/src/main/java/cgeo/geocaching/ImageSelectActivity.java
main/src/main/java/cgeo/geocaching/utils/ImageUtils.java
main/src/main/java/cgeo/geocaching/utils/UriUtils.java
main/src/main/res/drawable/ic_menu_flip.xml
main/src/main/res/drawable/ic_menu_rotate_right.xml
main/src/main/res/layout/imageselect_activity.xml

rel to #14515: first draft of log image edit (rotate, flip, external app)

rel to #14515: first draft of log image edit (rotate, flip, external app)

---

main/build.gradle
main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/AbstractGoogleTileProvider.java

This reverts commit 004e2e55d9abd5c16fd19986f58da3086f903f1f.
Reverts the upgrade to the new Google Maps renderer due to the issues described in #14534.

Revert "Update GM to latest renderer (when available)"

---

main/src/main/java/cgeo/geocaching/utils/MapMarkerUtils.java

fix bug in scaling of emojis (introduced in 2ce9196563d1922d0a42948fd5e34e2b32d74ab8)

fix scaling of emojis

---

main/src/main/java/cgeo/geocaching/connector/bettercacher/BetterCacherConnector.java

rel to #7911: fix npe

---

main/src/androidTest/java/cgeo/geocaching/utils/ImageUtilsTest.java

image scan: add unit test

---

main/src/main/java/cgeo/geocaching/utils/MapMarkerUtils.java

fix more bugs in scaling of emojis (introduced in https://github.com/cgeo/cgeo/commit/2ce9196563d1922d0a42948fd5e34e2b32d74ab8)
my work on #14502 will add even more scalings so with the 6 we already had I decided to store them in a map instead

fix scaling of emojis on waypoint icons

---

main/src/main/java/cgeo/geocaching/settings/Settings.java
main/src/main/java/cgeo/geocaching/settings/TextPreference.java
main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceLoggingFragment.java
main/src/main/java/cgeo/geocaching/ui/ImageListFragment.java
main/src/main/res/values/preference_keys.xml
main/src/main/res/values/strings.xml
main/src/main/res/xml/preferences_logging.xml

fix #14516: allow edit of log image caption default praefix

fix #14516: allow edit of log image caption default praefix

---

main/build.gradle
main/src/main/java/cgeo/geocaching/apps/AbstractLocusApp.java

Update locus-api-android to 0.9.50

---

main/src/main/java/cgeo/geocaching/apps/AbstractLocusApp.java
main/src/test/java/cgeo/geocaching/apps/AbstractLocusAppTest.java

Add mappings for
- CacheType.ADVLAB
- WaypointType.GENERATED
Add tests

locus connector updates

---

main/src/main/java/cgeo/geocaching/MainActivity.java
main/src/main/java/cgeo/geocaching/activity/AbstractNavigationBarActivity.java
main/src/main/java/cgeo/geocaching/activity/CustomMenuEntryActivity.java
main/src/main/java/cgeo/geocaching/command/AbstractCommand.java
main/src/main/java/cgeo/geocaching/connector/gc/AbstractListActivity.java
main/src/main/java/cgeo/geocaching/enumerations/CacheListType.java
main/src/main/java/cgeo/geocaching/enumerations/QuickLaunchItem.java
main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/main/java/cgeo/geocaching/settings/Settings.java
main/src/main/java/cgeo/geocaching/settings/SettingsActivity.java
main/src/main/java/cgeo/geocaching/settings/ViewSettingsActivity.java
main/src/main/res/layout-h390dp-land/activity_navigationbar.xml
main/src/main/res/layout-land/activity_navigationbar.xml
main/src/main/res/layout/activity_navigationbar.xml
main/src/main/res/menu/activity_navigationbar_menu.xml

Keep bottom navigation when item called via custom bottom navigation menu entry, but don't show it when called via menu or quicklaunch item.

Show bottom navigation when called from custom menu entry (fix #14552)

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
main/src/main/java/cgeo/geocaching/SearchResult.java
main/src/main/java/cgeo/geocaching/connector/AmendmentUtils.java
main/src/main/java/cgeo/geocaching/connector/ConnectorFactory.java
main/src/main/java/cgeo/geocaching/connector/bettercacher/BetterCacherAPI.java
main/src/main/java/cgeo/geocaching/connector/bettercacher/BetterCacherConnector.java
main/src/main/java/cgeo/geocaching/connector/capability/ICacheAmendment.java
main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java
main/src/main/java/cgeo/geocaching/filters/core/CategoryGeocacheFilter.java
main/src/main/java/cgeo/geocaching/filters/core/GeocacheFilter.java
main/src/main/java/cgeo/geocaching/filters/core/GeocacheFilterType.java
main/src/main/java/cgeo/geocaching/filters/core/TierGeocacheFilter.java
main/src/main/java/cgeo/geocaching/filters/core/ValueGroupGeocacheFilter.java
main/src/main/java/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java
main/src/main/java/cgeo/geocaching/loaders/LiveFilterGeocacheListLoader.java
main/src/main/java/cgeo/geocaching/loaders/SearchFilterGeocacheListLoader.java
main/src/main/java/cgeo/geocaching/maps/CGeoMap.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/caches/LiveCachesOverlay.java
main/src/main/java/cgeo/geocaching/models/Category.java
main/src/main/java/cgeo/geocaching/models/Geocache.java
main/src/main/java/cgeo/geocaching/models/Tier.java
main/src/main/java/cgeo/geocaching/storage/DataStore.java
main/src/main/java/cgeo/geocaching/ui/CacheDetailsCreator.java
main/src/main/java/cgeo/geocaching/unifiedmap/LoadInBackgroundHandler.java
main/src/main/java/cgeo/geocaching/utils/CommonUtils.java
main/src/main/res/values/strings.xml

rel to #7911: add filters (map/list) for category and tier

rel to #7911: add filters (map/list) for category and tier

---

main/src/main/java/cgeo/geocaching/connector/gc/GCWebAPI.java
main/src/main/java/cgeo/geocaching/network/HttpRequest.java

HttpRequest: small refactorings

HttpRequest: small refactorings

---

main/src/main/java/cgeo/geocaching/connector/bettercacher/BetterCacherAPI.java

rel to #7911: change to new cgeo specific fulldata API

rel to #7911: change to new cgeo specific fulldata API

---

main/src/main/java/cgeo/geocaching/connector/capability/IDifficultyTerrainMatrixNeededCapability.java
main/src/main/java/cgeo/geocaching/connector/gc/GCConnector.java
main/src/main/java/cgeo/geocaching/connector/gc/GCMap.java
main/src/main/java/cgeo/geocaching/connector/gc/GCWebAPI.java
main/src/main/java/cgeo/geocaching/filters/core/DifficultyTerrainMatrixGeocacheFilter.java
main/src/main/java/cgeo/geocaching/filters/core/GeocacheFilterType.java
main/src/main/java/cgeo/geocaching/filters/gui/DifficultyTerrainMatrixFilterViewHolder.java
main/src/main/java/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java
main/src/main/java/cgeo/geocaching/ui/CheckboxMatrixView.java
main/src/main/java/cgeo/geocaching/ui/ViewUtils.java
main/src/main/java/cgeo/geocaching/utils/expressions/ExpressionParser.java
main/src/main/res/layout/checkboxmatrix_view.xml
main/src/main/res/values/strings.xml
main/src/main/res/values/styles.xml
main/src/test/java/cgeo/geocaching/utils/expressions/ExpressionConfigTest.java
main/src/test/java/cgeo/geocaching/utils/expressions/ExpressionParserTest.java

fix #14579: add difficulty terrain matrix filter

fix #14579: add difficulty terrain matrix filter

---

main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceSystemFragment.java
main/src/main/java/cgeo/geocaching/settings/fragments/PreferencesFragment.java
main/src/main/res/xml/preferences.xml
main/src/main/res/xml/preferences_system.xml

make extended settings more prominent

---

main/src/main/java/cgeo/geocaching/settings/SettingsActivity.java

Fixes https://github.com/cgeo/cgeo/pull/14588#issuecomment-1718347123

Use fragment backstack on onBackPressed in settings

---

main/AndroidManifest.xml
main/src/main/java/cgeo/geocaching/permission/PermissionContext.java
main/src/main/res/values/strings.xml

- add POST_NOTIFICATION permission to `AndroidManifext.xml`
- add POST_NOTIFICATION permission to system information

Add notification permission to manifest and system info

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
main/src/main/java/cgeo/geocaching/connector/bettercacher/BetterCacherAPI.java
main/src/main/java/cgeo/geocaching/connector/bettercacher/BetterCacherConnector.java
main/src/main/java/cgeo/geocaching/filters/core/CategoryGeocacheFilter.java
main/src/main/java/cgeo/geocaching/filters/core/TierGeocacheFilter.java
main/src/main/java/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java
main/src/main/java/cgeo/geocaching/models/Geocache.java
main/src/main/java/cgeo/geocaching/storage/DataStore.java
main/src/main/java/cgeo/geocaching/ui/CacheDetailsCreator.java
main/src/main/java/cgeo/geocaching/utils/LazyInitializedSet.java

rel to #7911: fix geocaching merge problem with tier and categories

rel to #7911: fix geocaching merge problem with tier and categories

---

main/src/main/res/values/arrays.xml
main/src/main/res/values/preference_keys.xml
main/src/main/res/values/strings.xml

Remove some strings and array definitions no longer needed after settings cleanup in #14576

Fix some remainders from settings cleanup

---

main/src/main/res/values/styles.xml

Removes two style definitions no longer in use (probably since quite some time)

Fix lint: remove two unused styles

---

main/src/main/java/cgeo/geocaching/InstallWizardActivity.java

Integrate notifications permission into install wizard (Android API 33+ only)

Integrate notifications permission into install wizard (fix #14608)

---

main/src/main/java/cgeo/geocaching/utils/LazyInitializedSet.java

fix npe in lazyinitializedset

---

main/src/main/java/cgeo/geocaching/filters/gui/DifficultyTerrainMatrixFilterViewHolder.java
main/src/main/java/cgeo/geocaching/ui/CheckboxMatrixView.java
main/src/main/res/layout/checkboxmatrix_view.xml

fix #14637: layout problems with difficulty-terrain-matrix-filterview

fix #14637: layout problems with difficulty-terrain-matrix-filterview

---

main/src/main/java/cgeo/geocaching/connector/oc/OkapiClient.java

See description of the issue for more details
Extract visitedDate from the logs of the current user if the logType is either 2 (found it) or 10 (attended)
#14582
I am not sure  whether `getUserName()` gets me the uername from Opencaching.de or Geocaching.com. In my tests it worked, which may be due to tha fact that I am using the same username on OC and GC. Could somebody check if I am using the right approach for getting the username?

Issue 14582 (visitedDate not shown on UI)

---

main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java
main/src/main/java/cgeo/geocaching/connector/gc/GCWebAPI.java
main/src/main/java/cgeo/geocaching/connector/trackable/TravelBugLoggingManager.java
main/src/main/java/cgeo/geocaching/log/LogTrackableActivity.java
main/src/main/java/cgeo/geocaching/network/HttpResponse.java

New GCLogAPI: enable logging of trackables
Follow-up on PR #14647: enable logging of trackables

New GCLogAPI: enable logging of trackables

---

main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java
main/src/main/java/cgeo/geocaching/settings/Settings.java
main/src/main/res/layout/logcache_activity.xml

enable new log api for developer builds

enable new log api for developer builds

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
main/src/main/java/cgeo/geocaching/VariablesViewPageFragment.java
main/src/main/java/cgeo/geocaching/activity/AbstractActivity.java
main/src/main/java/cgeo/geocaching/filters/gui/CheckboxFilterViewHolder.java
main/src/main/java/cgeo/geocaching/list/StoredList.java
main/src/main/java/cgeo/geocaching/ui/dialog/CoordinatesCalculateGlobalDialog.java
main/src/main/java/cgeo/geocaching/ui/dialog/SimpleDialog.java

As a first step towards #14602 replace self-built list selection dialogs with calls to `SimpleDialog`

Replace 'select list' dialogs by SimpleDialog (rel. to 14602)

---

main/src/main/java/cgeo/geocaching/maps/CGeoMap.java
main/src/main/java/cgeo/geocaching/maps/MapDistanceDrawerCommons.java
main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/TargetView.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/UnifiedTargetAndDistancesHandler.java
main/src/main/res/layout/map_distanceinfo.xml

- unify more parts of maps' distance views to `UnifiedMap`
- make it more flexible

Restructured DistanceView

---

main/src/main/java/cgeo/geocaching/settings/Settings.java

enable gclogapi in nightlies

---

main/src/main/java/cgeo/geocaching/connector/gc/GCWebAPI.java

fix strange log image error message on trackable log error

fix strange log image error message on trackable log error

---

main/src/androidTest/java/cgeo/geocaching/filters/NamedFilterGeocacheFilterTest.java
main/src/main/java/cgeo/geocaching/filters/core/GeocacheFilter.java
main/src/main/java/cgeo/geocaching/filters/core/GeocacheFilterType.java
main/src/main/java/cgeo/geocaching/filters/core/NamedFilterGeocacheFilter.java
main/src/main/java/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java
main/src/main/java/cgeo/geocaching/filters/gui/NamedFilterFilterViewHolder.java
main/src/main/java/cgeo/geocaching/ui/TextSpinner.java
main/src/main/res/values/strings.xml

fix #14600: introduce a filter to include named filters

fix #14600: introduce a filter to include named filters

---

main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

left-over from pn quick settings

Remove outdated log message 'configured pn'

---

main/build.gradle

supersedes #14120
fixes #14430

Bump lifecycleVersion from 2.5.1 to 2.6.1, fix Duplicate class errors

---

main/src/main/java/cgeo/geocaching/connector/gc/GCWebAPI.java
main/src/main/java/cgeo/geocaching/connector/trackable/TravelBugLoggingManager.java
main/src/main/java/cgeo/geocaching/network/HttpResponse.java

fix #14681: fall back to old log flow if new flow doesn't work
Problem is that I can't really test whether this works with my current users

fix #14681: fall back to old log flow if new flow doesn't work

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java

PR #14645 deleted too much code in `CacheDetailActivity` - this PR restores the relevant part for parsing coord.info links

Fix c:geo no longer being able to open coord.info links (fix #14705)

---

main/src/main/res/layout/search_activity.xml

Edit:
Solution is now to disable autofill hoping that this will disable password suggestions, despite the text fields still being declared as visible passwords.
fixes #14710

Fix #14710 - Do not use autofill for geo and tracking code

---

main/src/main/java/cgeo/geocaching/CreateShortcutActivity.java
main/src/main/res/values/strings.xml

User `ShortcutManagerCompat` lib for creating dynamic shortcuts instead of the old way of just returning an intent result to be compatible to Android 14

Use ShortcutManagerCompat lib for creating shortcuts (fix #14694)

---

main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java
main/src/main/java/cgeo/geocaching/settings/Settings.java
main/src/main/res/layout/logcache_activity.xml

This PR, if merged, enables new gc log APi for beta

gclogapi: enable for beta

---

main/src/main/java/cgeo/geocaching/connector/al/ALApi.java

An attempt to address the issue of `searchByGeocode()` not giving us the true found state of a lab cache. The envisioned solution is to do a subsequent `search()`, which actually seems to be superfluous since we actually got the searched object, however, we got it without the found state. The `search()` function gives us the found state so we merge that into the object we wanted to fetch in the first place. This fix is a circumvention for a missing functionality in the api we're using.
issue #14672
I have not been able to verify whether this fix actually resolves the referenced issue. Reason is that I don't have a userid which I can use. It only works with a premium account, however, with my premium account I don't do lab caches ;)
P.S.: I have removed two methods which were flagged as …

ALC Loosing Found State (issue #14672)

---

main/src/main/java/cgeo/geocaching/connector/gc/GCConstants.java
main/src/main/java/cgeo/geocaching/connector/gc/GCWebAPI.java
main/src/main/java/cgeo/geocaching/utils/JsonUtils.java

fix #14681: parse and fill geocachereferencecode for gc trackable retrieve logging

fix #14681: parse and fill geocachereferencecode for gc trackable retrieve logging

---

main/AndroidManifest.xml
main/src/main/java/cgeo/geocaching/downloader/DownloadNotificationReceiver.java
main/src/main/java/cgeo/geocaching/downloader/PendingDownloadsActivity.java

open downloader activity when clicking on system downloader notification
note that this does not yet open the correct subfolder as this would be much more complex. Still way better than nothing ;-)

open downloader activity when clicking on system downloader notification

---

main/src/main/java/cgeo/geocaching/maps/MapSettingsUtils.java

Hide user routing profile buttons in map quick settings for which the user has not selected any user profile yet.

Hide user routing profile buttons if none defined (rel. to #14700)

---

main/src/main/java/cgeo/geocaching/maps/MapDistanceDrawerCommons.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/UnifiedTargetAndDistancesHandler.java

Restructures the way distance data is collected and interpreted back to the same way it was before #14668, but keeping the technical refactoring etc.
Attempts to fix issue #14763 and maybe #14765.
I was not able to reproduce any of those two issues, so I cannot check the effectiveness of this PR.
Thus: Can anyone out there having one or both of those issues check the build from this PR?
(Otherwise we might put it into the nightlies, update related issues, and wait a bit for feedback.)

Restructure distance data collection

---

main/src/main/java/cgeo/geocaching/connector/gc/GCWebAPI.java
main/src/main/java/cgeo/geocaching/utils/JsonUtils.java
main/src/test/java/cgeo/geocaching/utils/JsonUtilsTest.java

fix #14746: use local timezone for jackson json instead of UTC

fix #14746: use local timezone for jackson json instead of UTC

---

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

- [unified map] make sure added caches always have coords
e.g. PM-only caches have no coords for BMs
- [unified map] make sure newly loaded caches do not disappear

Small unified map fixes

---

main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsFragment.java

This fixes the bug that GMap gestures are not detected on a real phone, cause taps were interpreted as move. This bug was not noticed while development, cause mouse clicks are way more accurate.

[unified map] replace custom gesture progressing with GestureDetector

---

main/AndroidManifest.xml
main/src/main/java/cgeo/geocaching/connector/gc/ImportBookmarkLinks.java
main/src/test/java/cgeo/geocaching/connector/gc/ImportBookmarkLinksTest.java

- Added support for using c:geo to open coord.info short urls for bookmarks
None known
It has not (yet) been spun up, not on virtual or a phone as APK.
Comments and suggestions welcome.

Short form bookmark url support

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
main/src/main/res/layout/cachedetail_details_page.xml

remove partially broken Bettercacher box that should have been removed already per decision in https://github.com/cgeo/cgeo/issues/7911#issuecomment-1712914001

remove BC box from cache details (#14786)

---

main/build.gradle
main/src/main/java/cgeo/geocaching/maps/routing/RouteOptimizationHelper.java
main/src/main/java/cgeo/geocaching/maps/routing/Routing.java
main/src/main/java/cgeo/geocaching/models/Route.java
main/src/main/java/cgeo/geocaching/models/RouteOrRouteItem.java
main/src/main/java/cgeo/geocaching/models/RouteSegment.java
main/src/main/java/cgeo/geocaching/ui/GeoItemSelectorUtils.java
main/src/main/java/cgeo/geocaching/unifiedmap/LayerHelper.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/ElevationChart.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/ElevationChartUtils.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/IndividualRouteLayer.java
main/src/main/java/cgeo/geocaching/utils/DisplayUtils.java
main/src/main/res/drawable/circle.xml
main/src/main/res/layout-land/unifiedmap_activity.xml
main/src/main/res/layout/elevation_block.xml

First draft of elevation chart, implemented for `UnifiedMap`.
I switched to AppDevNext/AndroidChart, as discussed in [#14768](https://github.com/cgeo/cgeo/issues/14768#issuecomment-1784198635).

UnifiedMap: Elevation chart for individual route (rel. to 14768)

---

main/src/main/java/cgeo/geocaching/models/geoitem/GeoIcon.java
main/src/main/java/cgeo/geocaching/ui/ImageParam.java
main/src/main/java/cgeo/geocaching/ui/TextParam.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GeoItemLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GeoItemTestLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/IProviderGeoItemLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeVtmGeoItemLayer.java
main/src/main/java/cgeo/geocaching/utils/AsynchronousMapWrapper.java
main/src/main/java/cgeo/geocaching/utils/ImageUtils.java

rel to #14787: add icon-switching markers to geoitem test layer

rel to #14787: add icon-switching markers to geoitem test layer, try fix VTM refresh problem

---

main/src/androidTest/java/cgeo/geocaching/downloader/DownloaderTest.java
main/src/main/java/cgeo/geocaching/connector/bettercacher/BetterCacherAPI.java
main/src/main/java/cgeo/geocaching/network/HttpRequest.java
main/src/main/java/cgeo/geocaching/network/HttpResponse.java

rel to #14806: introduce timeout for http calls to bettercacher.org

rel to #14806: introduce timeout for http calls to bettercacher.org

---

main/src/main/java/cgeo/geocaching/unifiedmap/LayerHelper.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java
main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/AbstractGoogleTileProvider.java
main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/AbstractMapsforgeOfflineTileProvider.java
main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/AbstractMapsforgeOnlineTileProvider.java
main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/AbstractMapsforgeTileProvider.java
main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/AbstractTileProvider.java
main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/CyclosmSource.java
main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/MapsforgeMultiOfflineTileProvider.java
main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/OpenTopoMapSource.java
main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/OsmDeSource.java
main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/OsmOrgSource.java
main/src/main/res/layout/unifiedmap_mapsforgevtm_fragment.xml

Adds map attribution for mapsforge online & offline maps (including combined map)

UnifiedMap: Add map attribution (fix #14803)

---

main/src/main/java/cgeo/geocaching/ui/GeoItemSelectorUtils.java
main/src/main/java/cgeo/geocaching/ui/ImageParam.java

Fixes color of "route" icon in `GeoItemSelectUtils`

UnifiedMap: Apply tint to route symbol in selector (fix #14798)

---

main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/AbstractMapsforgeOfflineTileProvider.java
main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/MapsforgeMultiOfflineTileProvider.java

Add/fix support for switching preferred language at combined map type

UnifiedMap: Support language switch for combined map type (fix #14802)

---

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapViewModel.java

Adds proximity notifications to UnifiedMap

UnifiedMap: add proximity notifications (fix #12927)

---

main/src/main/java/cgeo/geocaching/TrackableActivity.java

PR https://github.com/cgeo/cgeo/pull/14645 deleted too much code in TrackableActivity - this PR restores the relevant part for parsing coord.info TB links

Fix c:geo no longer being able to open TB links (fix #14833)

---

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

Enables one-time messages in UnifiedMap

UnifiedMap: Activate OneTimeMessages

---

main/src/main/java/cgeo/geocaching/maps/MapUtils.java
main/src/main/java/cgeo/geocaching/storage/extension/OneTimeDialogs.java
main/src/main/res/values/strings.xml
main/src/main/res/values/strings_not_translatable.xml

Remove the "long tap" one-time message from all maps

Remove 'long tap' one-time message from maps

---

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

Adds `GeocacheChangedBroadcastReceiver` to `UnifiedMap`

UnifiedMap: Recognize geocache changes (fix #14804)

---

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

Enable adding waypoints to current target cache on UnifiedMap

UnifiedMap: Enable adding waypoints to current target (fix #14799)

---

main/src/main/java/cgeo/geocaching/log/LogTrackableActivity.java

rel to #14642: if wanted default type not possible, select best default

rel to #14642: if wanted default type not possible, select best default

---

main/src/main/java/cgeo/geocaching/AbstractDialogFragment.java
main/src/main/java/cgeo/geocaching/CachePopupFragment.java
main/src/main/java/cgeo/geocaching/WaypointPopupFragment.java
main/src/main/java/cgeo/geocaching/maps/MapUtils.java

There were quite some places which call `getActivity().finish()`. However, since the popup isn't using its own activity anymore, this would now close the map, which is not the wanted behavior.

don't close map when clicking on popup buttons

---

.idea/checkstyle-idea.xml
main/build.gradle

Update checkstyle according to codacy, see https://docs.codacy.com/release-notes/cloud/cloud-2023-09/#tool-versions

checkstyle 10.12.3

---

main/src/main/java/cgeo/geocaching/SwipeToOpenFragment.java
main/src/main/java/cgeo/geocaching/maps/MapUtils.java

fix https://github.com/cgeo/cgeo/issues/14868
close https://github.com/cgeo/cgeo/pull/14873

clear callbacks to avoid UpSwipeAction to be executed multiple times

---

main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java
main/src/main/java/cgeo/geocaching/log/LogCacheTask.java
main/src/main/java/cgeo/geocaching/log/LoggingUI.java
main/src/main/java/cgeo/geocaching/models/Geocache.java

same as https://github.com/cgeo/cgeo/pull/14855 but for offline logs

Notify map after OFFLINE logging cache from popup

---

main/src/main/java/cgeo/geocaching/ui/GeoItemSelectorUtils.java
main/src/main/java/cgeo/geocaching/ui/TextParam.java

fix #14871: add option to ImageParam on TextParam to use intrinsic drawable bounds

fix #14871: add option to ImageParam on TextParam to use intrinsic drawable bounds

---

main/src/main/java/cgeo/geocaching/ui/TextSpinner.java

fix #14890: preent NPE on null value in TextSpinner

fix #14890: prevent NPE on null value in TextSpinner

---

main/src/main/java/cgeo/geocaching/maps/CGeoMap.java
main/src/main/java/cgeo/geocaching/maps/MapUtils.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

When using the "check for missing download data" menu entry, open BRouter download activity, if external routing is configured.

Open BRouter download if external routing is configured

---

main/src/main/java/cgeo/geocaching/MainActivity.java
main/src/main/java/cgeo/geocaching/settings/Settings.java

PR #14884 introduced a bug, always displaying wallpaper, which this PR fixes

Fix wallpaper issue

---

main/src/main/java/cgeo/geocaching/connector/gc/GCConnector.java
main/src/main/java/cgeo/geocaching/connector/gc/GCLoggingManager.java
main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java
main/src/main/java/cgeo/geocaching/connector/gc/GCWebAPI.java
main/src/main/java/cgeo/geocaching/connector/trackable/TravelBugLoggingManager.java
main/src/main/java/cgeo/geocaching/settings/Settings.java
main/src/main/res/values/preference_keys.xml

New GC Log API: remove legacy code

New GC Log API: remove legacy code

---

main/src/main/java/cgeo/geocaching/connector/gc/ImportBookmarkLinks.java
main/src/main/java/cgeo/geocaching/connector/gc/util/AggregatedUrlToIdParser.java
main/src/main/java/cgeo/geocaching/connector/gc/util/SingleUrlToIdParser.java
main/src/main/java/cgeo/geocaching/connector/gc/util/UrlToIdParser.java
main/src/test/java/cgeo/geocaching/connector/gc/ImportBookmarkLinksTest.java

- Refactored `ImportBookmarkLinks` using some of the tools made available by #14181
- Refactored `ImportBookmarkLinksTest` to use `Parameterized`
- Moved `UrlToIdParser` and implementing classes to separate files to allow for re-use elsewhere
- #14777
- #14181

Refactored ImportBookmarkLinks using newly available tools from Java 1.8

---

main/src/main/java/cgeo/geocaching/CgeoApplication.java
main/src/main/java/cgeo/geocaching/Intents.java
main/src/main/java/cgeo/geocaching/MainActivity.java
main/src/main/java/cgeo/geocaching/activity/AbstractNavigationBarActivity.java
main/src/main/java/cgeo/geocaching/utils/MessageCenterUtils.java

We hat a lot of `UndeliverableException` in Play Store logs, due to `MainActivity` being stopped and not able to receive the notifications sent by RxJava. I did some refactoring therefore, moving mc polling to `CGeoApplication` and using local broadcast receivers for notifications. Also added setting a badge on HOME icon on receiving messages.

Fixes for Message Center notifications

---

main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java
main/src/main/java/cgeo/geocaching/models/Image.java
main/src/main/java/cgeo/geocaching/storage/DataStore.java

rel to #2012: collect and store log image ids to enable log edit later

rel to #2012: collect and store log image ids to enable log edit later

---

main/src/androidTest/java/cgeo/geocaching/CgeoApplicationTest.java
main/src/androidTest/java/cgeo/geocaching/SearchResultTest.java
main/src/main/java/cgeo/geocaching/SearchCacheData.java
main/src/main/java/cgeo/geocaching/SearchResult.java
main/src/main/java/cgeo/geocaching/connector/gc/GCConnector.java
main/src/main/java/cgeo/geocaching/connector/gc/GCMap.java
main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java
main/src/main/java/cgeo/geocaching/connector/gc/GCWebAPI.java
main/src/main/java/cgeo/geocaching/connector/oc/OkapiClient.java
main/src/main/java/cgeo/geocaching/filters/core/LogEntryGeocacheFilter.java
main/src/main/java/cgeo/geocaching/models/Geocache.java

fix #14827: GC.com: switch foundby-search to web api, remove legacy search result parsing for nearest.aspx

fix #14827: GC.com: switch foundby-search to web api, remove legacy search result parsing for nearest.aspx

---

main/src/main/java/cgeo/geocaching/CachePopupFragment.java
main/src/main/java/cgeo/geocaching/SwipeToOpenFragment.java
main/src/main/java/cgeo/geocaching/maps/MapUtils.java
main/src/main/res/layout/fragment_swipe_to_open.xml

Several fixes related to the cache bottom sheet

cache bottom sheet fixes

---

main/src/main/res/drawable/downloader_needsupdate.xml
main/src/main/res/drawable/downloader_ok.xml

update map downloader icons

---

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

Improve single cache map layout and live mode switching

[unified map] live mode handling

---

main/src/main/java/cgeo/geocaching/ui/GeoItemSelectorUtils.java
main/src/main/java/cgeo/geocaching/ui/SimpleItemListModel.java
main/src/main/res/layout/cacheslist_item_select.xml

fix #14894: fix layoout of cache list item

fix #14894: fix layoout of cache list item

---

main/src/main/java/cgeo/geocaching/CachePopupFragment.java
main/src/main/java/cgeo/geocaching/WaypointPopupFragment.java

Sends update notification for cache on closing cache/waypoint "popup" (on destroying its view)

Update cache when closing cache/waypoint popup (fix #14938)

---

main/src/androidTest/java/cgeo/geocaching/CgeoApplicationTest.java
main/src/main/java/cgeo/geocaching/CacheListActivity.java
main/src/main/java/cgeo/geocaching/connector/al/ALConnector.java
main/src/main/java/cgeo/geocaching/connector/capability/ISearchByFilter.java
main/src/main/java/cgeo/geocaching/connector/ec/ECConnector.java
main/src/main/java/cgeo/geocaching/connector/gc/GCConnector.java
main/src/main/java/cgeo/geocaching/connector/gc/GCMap.java
main/src/main/java/cgeo/geocaching/connector/gc/GCWebAPI.java
main/src/main/java/cgeo/geocaching/connector/oc/OCApiLiveConnector.java
main/src/main/java/cgeo/geocaching/connector/su/SuConnector.java
main/src/main/java/cgeo/geocaching/loaders/CoordsGeocacheListLoader.java
main/src/main/java/cgeo/geocaching/loaders/FinderGeocacheListLoader.java
main/src/main/java/cgeo/geocaching/loaders/KeywordGeocacheListLoader.java
main/src/main/java/cgeo/geocaching/loaders/LiveFilterGeocacheListLoader.java
main/src/main/java/cgeo/geocaching/loaders/OwnerGeocacheListLoader.java
main/src/main/java/cgeo/geocaching/loaders/SearchFilterGeocacheListLoader.java
main/src/main/java/cgeo/geocaching/sorting/AbstractCacheComparator.java
main/src/main/java/cgeo/geocaching/sorting/AbstractDateCacheComparator.java
main/src/main/java/cgeo/geocaching/sorting/EventDateComparator.java
main/src/main/java/cgeo/geocaching/sorting/GeocacheSort.java
main/src/main/java/cgeo/geocaching/sorting/GeocacheSortContext.java
main/src/main/java/cgeo/geocaching/sorting/HiddenDateComparator.java
main/src/main/java/cgeo/geocaching/sorting/LastFoundComparator.java
main/src/main/java/cgeo/geocaching/sorting/SortActionProvider.java
main/src/main/java/cgeo/geocaching/ui/CacheListAdapter.java
main/src/main/res/values/strings.xml

fix #14912: support sort in online searches esp foundby at gc.com

fix #14912: support sort in online searches esp foundby at gc.com

---

main/src/main/res/layout/cache_offlinebox.xml
main/src/main/res/layout/cachedetail_details_page.xml
main/src/main/res/layout/popup.xml

Adapt the new "offlinebox" layout from cache "popup" for cache details page:

Unify offlinebox layout for cache details and popup

---

main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeThemeHelper.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeThemeSettingsFragment.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java

Fix problems described in https://github.com/cgeo/cgeo/issues/13593 by disabling the problematic map scale.
close #14354, which basically did the same thing but for all three theme settings

Map scaling - temporary fix

---

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

All elements which are part of `menu/map_activity.xml` are implemented meanwhile.

[unified map] finalize onOptionsItemSelected

---

main/src/main/java/cgeo/geocaching/unifiedmap/LocUpdater.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsFragment.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/PositionLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java

Alternative approach for implementing autorotation mode. See comments in #14973 and #14481
closes #14976, #14481

Alternative approach for implementing autorotation mode (fix #14481)

---

main/src/main/java/cgeo/geocaching/connector/gc/GCAuthAPI.java
main/src/main/java/cgeo/geocaching/connector/gc/GCLogin.java
main/src/main/java/cgeo/geocaching/connector/gc/GCWebAPI.java

rel to #2012: refactor GCWebAPI before adding log edit: clean up API access

rel to #2012: refactor GCWebAPI before adding log edit: clean up API access

---

main/src/main/java/cgeo/geocaching/settings/Settings.java
main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceMapSourcesFragment.java
main/src/main/res/values/preference_keys.xml
main/src/main/res/xml/preferences_map_sources.xml

IMHO it's time for our nightly users to try out unified map

enable unified map for nightly users (can be disabled via settings)

---

.idea/checkstyle-idea.xml
main/build.gradle

... according to codacy, see https://docs.codacy.com/release-notes/cloud/cloud-2023-11/

 Update checkstyle

---

main/src/main/java/cgeo/geocaching/maps/MapStarUtils.java
main/src/main/java/cgeo/geocaching/maps/MapUtils.java
main/src/main/java/cgeo/geocaching/models/Geocache.java
main/src/main/java/cgeo/geocaching/models/RouteItem.java
main/src/main/java/cgeo/geocaching/ui/dialog/SimplePopupMenu.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapViewModel.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/GeoItemsLayer.java
main/src/main/java/cgeo/geocaching/utils/CollectionDiff.java
main/src/main/java/cgeo/geocaching/utils/CommonUtils.java
main/src/main/res/values/strings.xml

rel to #14547: show waypoint connection via star lines

rel to #14547: show waypoint connection via star lines

---

main/src/androidTest/java/cgeo/geocaching/connector/gc/GCLogAPITest.java
main/src/main/java/cgeo/geocaching/connector/ImageResult.java
main/src/main/java/cgeo/geocaching/connector/NoLoggingManager.java
main/src/main/java/cgeo/geocaching/connector/ec/ECLoggingManager.java
main/src/main/java/cgeo/geocaching/connector/gc/GCLogAPI.java
main/src/main/java/cgeo/geocaching/connector/gc/GCLoggingManager.java
main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java
main/src/main/java/cgeo/geocaching/connector/oc/OkapiClient.java
main/src/main/java/cgeo/geocaching/connector/su/SuApi.java
main/src/main/java/cgeo/geocaching/log/LogCacheTask.java
main/src/main/java/cgeo/geocaching/utils/ImageUtils.java
main/src/main/java/cgeo/geocaching/utils/UriUtils.java

rel to #2012: enhance gc.com log api to allow edit/delete for logs/images

rel to #2012: enhance gc.com log api to allow edit/delete for logs/images

---

main/src/main/res/layout/waypoint_popup.xml

as discussed in yesterday's dev meeting

Swap edit and cache buttins in waypoint sheet

---

main/src/androidTest/java/cgeo/geocaching/CgeoApplicationTest.java
main/src/main/java/cgeo/geocaching/log/LogEntry.java

CgeoApplicationTest for trackables: add comments

CgeoApplicationTest for trackables: add comments

---

main/src/main/java/cgeo/geocaching/ui/RepeatOnHoldListener.java
main/src/main/java/cgeo/geocaching/unifiedmap/AbstractMapFragment.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsFragment.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java
main/src/main/res/layout-land/unifiedmap_activity.xml
main/src/main/res/layout/map_zoom_control.xml
main/src/main/res/layout/unifiedmap_activity.xml
main/src/main/res/layout/unifiedmap_mapsforgevtm_fragment.xml

Use self-written zoom control for all map types and implement continuous zooming when keep touching zoom control

Map zoom controls

---

main/src/main/java/cgeo/geocaching/connector/AbstractLoggingManager.java
main/src/main/java/cgeo/geocaching/connector/ILoggingManager.java
main/src/main/java/cgeo/geocaching/connector/ImageResult.java
main/src/main/java/cgeo/geocaching/connector/LogResult.java
main/src/main/java/cgeo/geocaching/connector/NoLoggingManager.java
main/src/main/java/cgeo/geocaching/connector/StatusResult.java
main/src/main/java/cgeo/geocaching/connector/capability/ILogin.java
main/src/main/java/cgeo/geocaching/connector/ec/ECApi.java
main/src/main/java/cgeo/geocaching/connector/ec/ECConnector.java
main/src/main/java/cgeo/geocaching/connector/gc/GCConnector.java
main/src/main/java/cgeo/geocaching/connector/gc/GCLogAPI.java
main/src/main/java/cgeo/geocaching/connector/gc/GCLoggingManager.java
main/src/main/java/cgeo/geocaching/connector/gc/GCWebAPI.java
main/src/main/java/cgeo/geocaching/connector/oc/OCApiLiveConnector.java
main/src/main/java/cgeo/geocaching/connector/oc/OkapiClient.java
main/src/main/java/cgeo/geocaching/connector/oc/OkapiLoggingManager.java
main/src/main/java/cgeo/geocaching/connector/su/SuApi.java
main/src/main/java/cgeo/geocaching/connector/su/SuConnector.java
main/src/main/java/cgeo/geocaching/connector/su/SuLoggingManager.java
main/src/main/java/cgeo/geocaching/connector/trackable/GeokretyLoggingManager.java
main/src/main/java/cgeo/geocaching/connector/trackable/TravelBugLoggingManager.java
main/src/main/java/cgeo/geocaching/enumerations/StatusCode.java
main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java
main/src/main/java/cgeo/geocaching/log/LogCacheTask.java
main/src/main/java/cgeo/geocaching/log/LogEntry.java
main/src/main/java/cgeo/geocaching/log/LogTrackableActivity.java

rel to #2012: connect to new logging api and refactor

rel to #2012: connect to new logging api and refactor

---

main/src/main/java/cgeo/geocaching/ui/RepeatOnHoldListener.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

as requested in https://github.com/cgeo/cgeo/issues/15003#issuecomment-1857074721

[unified map] change map zoom interval

---

main/src/main/java/cgeo/geocaching/storage/DataStore.java

Make DB downgrade work on freshly created database

Make DB downgrade work on freshly created database

---

main/src/main/java/cgeo/geocaching/ui/ViewUtils.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GoogleV2GeoItemLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeV6GeoItemLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeVtmGeoItemLayer.java

rel to #15003: vtm stroke line widths: fix rounding problem (would affect thin lines more than thick lines)

rel to #15003: vtm stroke line widths: fix rounding problem (would affect thin lines more than thick lines)

---

main/src/androidTest/java/cgeo/geocaching/models/GeocacheTest.java
main/src/main/java/cgeo/geocaching/CacheMenuHandler.java
main/src/main/java/cgeo/geocaching/calendar/CalendarAdder.java
main/src/main/java/cgeo/geocaching/log/CacheLogsViewCreator.java
main/src/main/java/cgeo/geocaching/models/Geocache.java
main/src/main/java/cgeo/geocaching/utils/CalendarUtils.java

Rebases PR #13249 to the current master
Use CalendarUtils.isPastEvent instead of Geocache.isPastEvent -> remove Geocache.isPastEvent
Use sharing functions directly from ShareUtils instead of wrapper-methods of Geocache... -> Remove wrapper-methods from Geocache
I will create a follow PR to remove the Connector-related methods to a ConnectorUtility-class

Cleanup of GeoCache class (rebase PR 13249)

---

main/src/main/java/cgeo/geocaching/activity/Progress.java
main/src/main/java/cgeo/geocaching/utils/AndroidRxUtils.java
main/src/main/java/cgeo/geocaching/utils/CommonUtils.java
main/src/main/java/cgeo/geocaching/utils/workertask/DelegateWorkerTaskControl.java
main/src/main/java/cgeo/geocaching/utils/workertask/ProgressDialogFeature.java
main/src/main/java/cgeo/geocaching/utils/workertask/WorkerTask.java
main/src/main/java/cgeo/geocaching/utils/workertask/WorkerTaskConfiguration.java
main/src/main/java/cgeo/geocaching/utils/workertask/WorkerTaskControl.java
main/src/main/java/cgeo/geocaching/utils/workertask/WorkerTaskEvent.java
main/src/main/java/cgeo/geocaching/utils/workertask/WorkerTaskEventType.java
main/src/main/java/cgeo/geocaching/utils/workertask/WorkerTaskLogic.java
main/src/test/java/cgeo/geocaching/utils/CommonUtilsTest.java
main/src/test/java/cgeo/geocaching/utils/workertask/WorkerTaskTest.java

rel to #2012: new async task tooling for activity background worker tasks

rel to #2012: new async task tooling for activity background worker tasks

---

main/src/main/java/cgeo/geocaching/activity/ActivityMixin.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapState.java

Also works for map source change

UnifiedMap: Preserve center & zoom on rotation (fix #15039)

---

main/src/main/java/cgeo/geocaching/connector/AbstractLogin.java
main/src/main/java/cgeo/geocaching/connector/capability/ILogin.java
main/src/main/java/cgeo/geocaching/connector/ec/ECApi.java
main/src/main/java/cgeo/geocaching/connector/ec/ECConnector.java
main/src/main/java/cgeo/geocaching/connector/gc/GCConnector.java
main/src/main/java/cgeo/geocaching/connector/gc/GCLogAPI.java
main/src/main/java/cgeo/geocaching/connector/gc/GCLoggingManager.java
main/src/main/java/cgeo/geocaching/connector/oc/OCApiLiveConnector.java
main/src/main/java/cgeo/geocaching/connector/su/SuConnector.java
main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java
main/src/main/java/cgeo/geocaching/log/LogCacheTask.java
main/src/main/java/cgeo/geocaching/log/LogUtils.java
main/src/main/java/cgeo/geocaching/models/Geocache.java
main/src/main/java/cgeo/geocaching/ui/ImageListFragment.java
main/src/main/java/cgeo/geocaching/ui/dialog/SimpleDialog.java
main/src/main/java/cgeo/geocaching/utils/workertask/ProgressDialogFeature.java
main/src/main/java/cgeo/geocaching/utils/workertask/WorkerTask.java

rel to #2012: allow log edit and delete (first draft version)

rel to #2012: allow log edit and delete (first draft version)

---

main/src/main/java/cgeo/geocaching/utils/workertask/WorkerTask.java
main/src/main/java/cgeo/geocaching/utils/workertask/WorkerTaskLogic.java
main/src/test/java/cgeo/geocaching/utils/workertask/WorkerTaskTest.java

rel to PR #15053: fix failing workertask unit test, add error handling

rel to PR #15053: fix failing workertask unit test, add error handling

---

main/src/main/java/cgeo/geocaching/connector/AbstractLoggingManager.java
main/src/main/java/cgeo/geocaching/connector/ILoggingManager.java
main/src/main/java/cgeo/geocaching/connector/gc/GCLoggingManager.java
main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java
main/src/main/java/cgeo/geocaching/log/LogUtils.java

rel to #2012: various small fixes to log edit and delete

rel to #2012: various small fixes to log edit and delete

---

main/src/main/java/cgeo/geocaching/utils/MapLineUtils.java

Fine-tine line width for UnifiedMap

UnifiedMap: Adjust line width (rel. to #15003)

---

main/src/main/java/cgeo/geocaching/unifiedmap/LoadInBackgroundHandler.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

De-clutter Logcat window in AS by downgrading a couple of log message from error level to debug level

UnifiedMap: Downgrade some log messages to debug level

---

main/src/main/java/cgeo/geocaching/MainActivity.java
main/src/main/java/cgeo/geocaching/permission/PermissionContext.java
main/src/main/java/cgeo/geocaching/settings/Settings.java
main/src/main/java/cgeo/geocaching/settings/SettingsActivity.java
main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceAppearanceFragment.java
main/src/main/res/values/strings.xml
main/src/main/res/values/themes.xml

Cherry-picks #14884 for `release` as we get support tickets for it from time to time

Show wallpaper without need for READ_EXTERNAL_STORAGE permission

---

main/src/main/java/cgeo/geocaching/connector/ImageResult.java
main/src/main/java/cgeo/geocaching/connector/LogResult.java
main/src/main/java/cgeo/geocaching/connector/StatusResult.java
main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java
main/src/main/java/cgeo/geocaching/log/LogUtils.java

rel to #2012: fix intermixing problems with new and edit log

rel to #2012: fix intermixing problems with new and edit log

---

main/src/main/java/cgeo/geocaching/location/Viewport.java
main/src/main/java/cgeo/geocaching/models/geoitem/GeoPrimitive.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/TracksLayer.java
main/src/main/java/cgeo/geocaching/utils/CommonUtils.java
main/src/main/java/cgeo/geocaching/utils/GeoJsonUtils.java

fix #15074: relax GeoJson parsing to handle data errors / invalid polylines

fix #15074: relax GeoJson parsing to handle data errors / invalid polylines

---

main/src/main/java/cgeo/geocaching/unifiedmap/LocUpdater.java

UnifiedMap: Reduce CPU consumption of map by reducing location update frequency from 'update immediately' to 2-5 per second
(twice per second as default, as in our old maps, and five times per second as a compromise for autorotation mode. Could probably reduced further - need to try in real life)

UnifiedMap: Reduce CPU consumption of map (fix #15073)

---

main/src/main/java/cgeo/geocaching/AbstractDialogFragment.java
main/src/main/java/cgeo/geocaching/CachePopupFragment.java
main/src/main/java/cgeo/geocaching/WaypointPopupFragment.java
main/src/main/java/cgeo/geocaching/activity/AbstractNavigationBarMapActivity.java
main/src/main/java/cgeo/geocaching/maps/AbstractMap.java
main/src/main/java/cgeo/geocaching/maps/CGeoMap.java
main/src/main/java/cgeo/geocaching/maps/MapUtils.java
main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java
main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapView.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapViewModel.java

Restores cache/waypoint sheet after screen rotation (or other activity restarts)
Implemented for UnifiedMap, CGeoMap (GM) and NewMap (Mapsforge)

Restore cache/waypoint sheet after rotation

---

main/src/main/java/cgeo/geocaching/AbstractDialogFragment.java
main/src/main/java/cgeo/geocaching/CachePopupFragment.java
main/src/main/java/cgeo/geocaching/WaypointPopupFragment.java
main/src/main/java/cgeo/geocaching/activity/AbstractNavigationBarMapActivity.java
main/src/main/java/cgeo/geocaching/maps/CGeoMap.java
main/src/main/java/cgeo/geocaching/maps/MapUtils.java
main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java
main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapView.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

Sheet info: Remove old layout listeners before setting new one
Also moves all sheetInfo methods to common map fragment class

Sheet info: Remove old layout listeners before setting new one

---

main/src/main/java/cgeo/geocaching/AbstractDialogFragment.java

Set distance info only if distance info view already exists

---

main/src/main/java/cgeo/geocaching/log/LogTrackableActivity.java

rel to #14642: repair trackable logtype default selection

rel to #14642: repair trackable logtype default selection

---

main/src/main/java/cgeo/geocaching/InstallWizardActivity.java
main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java
main/src/main/java/cgeo/geocaching/utils/BackupUtils.java
main/src/main/java/cgeo/geocaching/utils/DebugUtils.java
main/src/main/java/cgeo/geocaching/utils/FilterUtils.java
main/src/main/java/cgeo/geocaching/utils/ShareUtils.java

fix #15094: restore default ok action on dialogs

fix #15094: restore default ok action on dialogs

---

main/src/main/java/cgeo/geocaching/settings/SettingsActivity.java
main/src/main/java/cgeo/geocaching/settings/fragments/BasePreferenceFragment.java
main/src/main/java/cgeo/geocaching/settings/fragments/PreferencesFragmentContent.java
main/src/main/java/cgeo/geocaching/settings/fragments/PreferencesFragmentRoot.java
main/src/main/res/layout-land/layout_settings.xml
main/src/main/res/layout/layout_settings.xml

Uses a two-column layout for settings in landscape mode

Use two column layout for settings in landscape mode

---

main/src/main/java/cgeo/geocaching/WaypointPopupFragment.java
main/src/main/java/cgeo/geocaching/ui/CacheDetailsCreator.java

Use wide note view for waypoints in sheet info

---

main/src/main/java/cgeo/geocaching/ImageEditActivity.java
main/src/main/java/cgeo/geocaching/ImageViewActivity.java
main/src/main/java/cgeo/geocaching/network/HtmlImage.java
main/src/main/java/cgeo/geocaching/network/SmileyImage.java
main/src/main/java/cgeo/geocaching/ui/ImageGalleryView.java
main/src/main/java/cgeo/geocaching/utils/ImageDataMemoryCache.java
main/src/main/res/layout/imageedit_activity.xml

rel to #2012: prepare log image edit

rel to #2012: prepare log image edit

---

main/src/main/java/cgeo/geocaching/network/HtmlImage.java

fix codacy issues

---

main/src/androidTest/java/cgeo/geocaching/connector/oc/OkapiClientTest.java

Add a reason for the ignored test.

Make CI Lint happy

---

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

(to avoid zooming out first, then zooming back)

UnifiedMap: Skip default center and zoom on tilesource change

---

main/src/main/java/cgeo/geocaching/activity/AbstractNavigationBarActivity.java

Fixes #15112 (long tap listener assignment, if bottom / side nav has only four buttons)

Bottom Nav: Fix long tap listener assignment

---

main/src/main/java/cgeo/geocaching/ImageEditActivity.java
main/src/main/java/cgeo/geocaching/ImageViewActivity.java
main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java
main/src/main/java/cgeo/geocaching/network/HtmlImage.java
main/src/main/java/cgeo/geocaching/ui/ImageActivityHelper.java
main/src/main/java/cgeo/geocaching/ui/ImageExtendedView.java
main/src/main/java/cgeo/geocaching/ui/ImageGalleryView.java
main/src/main/java/cgeo/geocaching/ui/ImageListFragment.java
main/src/main/java/cgeo/geocaching/utils/ImageLoader.java
main/src/main/java/cgeo/geocaching/utils/ImageUtils.java
main/src/main/java/cgeo/geocaching/utils/MetadataUtils.java
main/src/main/java/cgeo/geocaching/utils/ViewOrientation.java
main/src/main/res/layout/image_gallery_image.xml
main/src/main/res/layout/imageextendedview_view.xml
main/src/main/res/layout/imagelist_item.xml

rel to #2012: refactor and unify handling of images in gallery and lists to allow log image edit

rel to #2012: refactor and unify handling of images in gallery and lists to allow log image edit

---

main/src/main/java/cgeo/geocaching/log/LogActivityHelper.java
main/src/main/java/cgeo/geocaching/utils/workertask/WorkerTask.java

Refactor Workertask logging and usage

Refactor Workertask logging and usage

---

main/src/main/java/cgeo/geocaching/maps/CGeoMap.java
main/src/main/java/cgeo/geocaching/maps/DistanceDrawer.java
main/src/main/java/cgeo/geocaching/maps/MapDistanceDrawerCommons.java
main/src/main/java/cgeo/geocaching/maps/MapUtils.java
main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapView.java
main/src/main/java/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
main/src/main/java/cgeo/geocaching/maps/interfaces/PositionAndHistory.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/DistanceView.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/UnifiedTargetAndDistancesHandler.java
main/src/main/res/menu/map_longclick.xml
main/src/main/res/values/strings.xml

- Swaps elevation info on map to GPS data (fix #14757)
- Adds map-based elevation info to long-tap popup (map, cache, waypoint)

Show elevation info in long-tap menu

---

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

Some fixes to UnifiedMap "set as target" mode:
- if waypoint is set as target: only display this waypoint, but do so without checking "display waypoint limit"
- if cache is set as target: only display its waypoints, not those from other caches in given viewport
- also attempts to fix #15137

UnifiedMap: Show waypoint if set as target

---

main/src/main/java/cgeo/geocaching/ui/FormulaEditText.java
main/src/main/java/cgeo/geocaching/ui/VariableListView.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java
main/src/main/java/cgeo/geocaching/utils/formulas/FormulaUtils.java
main/src/main/res/layout/formula_edittext_view.xml

rel to #12600: create an Edit-Field for formulas (meant for vars in waypoint projection)

rel to #12600: create an Edit-Field for formulas (meant for vars in waypoint projection)

---

main/src/main/java/cgeo/geocaching/activity/AbstractNavigationBarActivity.java
main/src/main/java/cgeo/geocaching/apps/cachelist/InternalCacheListMap.java
main/src/main/java/cgeo/geocaching/maps/DefaultMap.java
main/src/main/java/cgeo/geocaching/ui/TwoLineSpinnerAdapter.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapType.java

First draft of list selection, when UnifiedMap got started with a list, see #13573
One drawback, though: Due to the additional space for the cache list spinner, the map title gets shortened quite a bit:

UnifiedMap: Allow cache list selection

---

main/src/main/res/values/strings.xml
main/src/main/res/values/strings_not_translatable.xml

Updates list of contributors reflecting 2023's contributions

Update list of contributors (2023)

---

main/src/main/java/cgeo/geocaching/connector/gc/GCLogAPI.java
main/src/main/java/cgeo/geocaching/log/LogTypeTrackable.java
main/src/main/java/cgeo/geocaching/network/HttpRequest.java

fix failing trackable logging (see Watchdog Tests)

fix failing trackable logging (see Watchdog Tests)

---

main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java

Fix NPE in LogCacheActivity for missing trackable actions

Fix NPE in LogCacheActivity for missing trackable actions

---

main/src/main/java/cgeo/geocaching/settings/SettingsActivity.java

Avoid overlapping preference screens on upKey/backKey

---

main/project/rawimages/arrow_north_east.svg
main/project/rawimages/arrow_top_right.svg
main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
main/src/main/java/cgeo/geocaching/EditWaypointActivity.java
main/src/main/java/cgeo/geocaching/SearchActivity.java
main/src/main/java/cgeo/geocaching/enumerations/ProjectionType.java
main/src/main/java/cgeo/geocaching/location/DistanceUnit.java
main/src/main/java/cgeo/geocaching/location/Geopoint.java
main/src/main/java/cgeo/geocaching/models/CacheVariableList.java
main/src/main/java/cgeo/geocaching/models/Waypoint.java
main/src/main/java/cgeo/geocaching/settings/Settings.java
main/src/main/java/cgeo/geocaching/storage/DataStore.java
main/src/main/java/cgeo/geocaching/ui/FormulaEditText.java
main/src/main/java/cgeo/geocaching/ui/TextParam.java
main/src/main/java/cgeo/geocaching/ui/TextSpinner.java
main/src/main/java/cgeo/geocaching/ui/ViewUtils.java
main/src/main/java/cgeo/geocaching/utils/formulas/FormulaException.java
main/src/main/java/cgeo/geocaching/utils/formulas/VariableMap.java
main/src/main/res/drawable/arrow_north_east.xml
main/src/main/res/drawable/arrow_top_right.xml
main/src/main/res/layout/editwaypoint_activity.xml
main/src/main/res/layout/waypoint_item.xml
main/src/main/res/values/attrs.xml
main/src/main/res/values/preference_keys.xml
main/src/main/res/values/strings.xml
main/src/test/java/cgeo/geocaching/utils/CommonUtilsTest.java

rel to #12600: allow usage of variables in waypoint projection

rel to #12600: allow usage of variables in waypoint projection

---

main/src/main/java/cgeo/geocaching/ui/TextParam.java

fix #15178: show text again in popup dialogs / fix TextParam applyTo

fix #15178: show text again in popup dialogs / fix TextParam applyTo

---

main/src/androidTest/java/cgeo/geocaching/connector/gc/GCLogAPITest.java
main/src/androidTest/java/cgeo/geocaching/log/LogEntryTest.java
main/src/androidTest/java/cgeo/geocaching/storage/DataStoreTest.java
main/src/androidTest/java/cgeo/geocaching/storage/DataStoreTestHelpers.java
main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java
main/src/main/java/cgeo/geocaching/log/LogEntry.java
main/src/main/java/cgeo/geocaching/log/LogUtils.java
main/src/main/java/cgeo/geocaching/log/LoggingUI.java
main/src/main/java/cgeo/geocaching/log/OfflineLogEntry.java
main/src/main/java/cgeo/geocaching/models/Geocache.java
main/src/main/java/cgeo/geocaching/storage/DataStore.java
main/src/main/java/cgeo/geocaching/utils/CommonUtils.java

refactor builder pattern LogEntry and OfflineLogEntry: make non-generic

refactor builder pattern LogEntry and OfflineLogEntry: make non-generic

---

main/src/main/java/cgeo/geocaching/connector/gc/GCLoggingManager.java
main/src/main/java/cgeo/geocaching/log/LogsViewCreator.java
main/src/main/java/cgeo/geocaching/settings/Settings.java
main/src/main/res/values/preference_keys.xml
main/src/main/res/values/strings.xml

fix #2012: introducing edit and delete log

fix #2012: introducing edit and delete log

---

main/src/main/res/drawable/rounded_corners_top.xml
main/src/main/res/layout/swipe_up_indicator.xml

improve swipe up indicator color scheme

---

main/src/main/java/cgeo/geocaching/utils/formulas/FormulaUtils.java
main/src/test/java/cgeo/geocaching/utils/formulas/FormulaUtilsTest.java

fix #15173: restrict formula scan regex to make evil regex situation more unlikely

fix #15173: restrict formula scan regex to make evil regex situation more unlikely

---

main/src/androidTest/java/cgeo/geocaching/activity/WaypointActivityTest.java
main/src/main/java/cgeo/geocaching/EditWaypointActivity.java
main/src/main/java/cgeo/geocaching/settings/Settings.java
main/src/main/res/layout/editwaypoint_activity.xml
main/src/main/res/values/preference_keys.xml

fix #12600: enable waypoint projection with variables
Details about this feature can be found here: https://github.com/cgeo/cgeo/pull/15165#issuecomment-1879226154

fix #12600: enable waypoint projection with variables

---

main/src/main/java/cgeo/geocaching/SwipeToOpenFragment.java
main/src/main/res/layout/fragment_swipe_to_open.xml

fix gap while swiping up in cache popup.
That's how it was before the PR:

[cache popup] fix gap while swiping up

---

main/src/main/java/cgeo/geocaching/log/LogTrackableActivity.java

fix #14642: rework trackable log type logic completely, fixing the problem with it

fix #14642: rework trackable log type logic completely

---

main/src/main/java/cgeo/geocaching/TrackableActivity.java
main/src/main/java/cgeo/geocaching/connector/gc/GCConstants.java
main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java
main/src/main/java/cgeo/geocaching/models/Trackable.java

fix #15207: adapt to trackable spotted cache html changes on gc.com

fix #15207: adapt to trackable spotted cache html changes on gc.com

---

main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java
main/src/main/java/cgeo/geocaching/log/OfflineLogEntry.java
main/src/main/res/values/strings.xml

fix #15212: ask for confirmation on unsent log edit changes

fix #15212: ask for confirmation on unsent log edit changes

---

main/src/main/res/values/strings.xml

As suggested in https://github.com/cgeo/cgeo/pull/15208#issuecomment-1897201340

[Contacts Integration] enhance menu string

---

main/src/main/java/cgeo/geocaching/location/Units.java
main/src/main/java/cgeo/geocaching/maps/MapUtils.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/UnifiedTargetAndDistancesHandler.java

Displays elevation info in either "ft" or "m", according to current imperial units' setting.

Show elevation in ft/m according to settings (fix #15239)

---

main/src/main/java/cgeo/geocaching/utils/formulas/FormulaFunction.java
main/src/main/java/cgeo/geocaching/utils/formulas/FormulaUtils.java

fix #15248: make trunc work for negative numbers

fix #15248: make trunc work for negative numbers

---

main/src/main/java/cgeo/geocaching/models/CacheArtefactParser.java
main/src/main/java/cgeo/geocaching/models/Waypoint.java

fix #15243: allow parsing of waypoint projection in personal note

fix #15243: allow parsing of waypoint projection in personal note

---

main/src/main/java/cgeo/geocaching/unifiedmap/AbstractMapFragment.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java

Sets map "center" to app. 25% from bottom, if "followMyLocation" is active and map rotation is set to one of the "auto" modes.
Currently VTM only.

UnifiedMap VTM: Implement "driving mode" (rel. to #15257)

---

main/src/main/java/cgeo/geocaching/unifiedmap/AbstractMapFragment.java
main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsFragment.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java

No functional changes, but code cleanup & formatting for UnifiedMap fragments:
- remove code which is commented out
- insert same subheadings for segments in all three files
- bring segments and their methods into the same order in all three files

UnifiedMap: code cleanup & formatting for map fragments

---

main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceNavigationFragment.java
main/src/main/res/values/strings.xml
main/src/main/res/xml/preferences_navigation.xml

Make settings for navigation user profiles distinguishable

---

main/src/main/java/cgeo/geocaching/EditWaypointActivity.java
main/src/main/java/cgeo/geocaching/models/CacheArtefactParser.java
main/src/main/java/cgeo/geocaching/models/Waypoint.java
main/src/main/java/cgeo/geocaching/storage/DataStore.java
main/src/test/java/cgeo/geocaching/models/CacheArtefactParserTest.java

fix #15284: prevent duplication on parsing waypoints with projection from text

fix #15284: prevent duplication on parsing waypoints with projection from text

---

main/src/main/java/cgeo/geocaching/models/Waypoint.java
main/src/main/java/cgeo/geocaching/utils/formulas/Formula.java

rel to #15296: might fix crash on projection formulas with unfilled vars

rel to #15296: might fix crash on projection formulas with unfilled vars

---

main/build.gradle

externalize appID

---

.idea/checkstyle-idea.xml
main/build.gradle

to the version used at codacy (10.13.0)

 Update checkstyle version

---

main/src/main/java/cgeo/geocaching/CgeoApplication.java

rel to #15100: deactivate VTM transparent line rendering to solve strange artefacts

rel to #15100: deactivate VTM transparent line rendering to solve strange artefacts

---

main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java

fix #15298: dont add empty log on online log send

fix #15298: dont add empty log on online log send

---

main/src/androidTest/java/cgeo/geocaching/connector/gc/GCLogAPITest.java
main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
main/src/main/java/cgeo/geocaching/CacheListActivity.java
main/src/main/java/cgeo/geocaching/connector/AbstractLoggingManager.java
main/src/main/java/cgeo/geocaching/connector/ILoggingManager.java
main/src/main/java/cgeo/geocaching/connector/StatusResult.java
main/src/main/java/cgeo/geocaching/connector/gc/GCLogAPI.java
main/src/main/java/cgeo/geocaching/connector/gc/GCLoggingManager.java
main/src/main/java/cgeo/geocaching/enumerations/StatusCode.java
main/src/main/java/cgeo/geocaching/log/LogActivityHelper.java
main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java
main/src/main/java/cgeo/geocaching/log/LogTrackableActivity.java
main/src/main/java/cgeo/geocaching/log/LogUtils.java
main/src/main/java/cgeo/geocaching/log/LogsViewCreator.java
main/src/main/java/cgeo/geocaching/models/Geocache.java
main/src/main/res/values/strings.xml

fix #15307: allow to give a reason text when deleting a log

fix #15307: allow to give a reason text when deleting a log

---

main/src/main/java/cgeo/geocaching/CgeoApplication.java

rel to #10087: enable CGeoApplication to listen/provide active activity

rel to #10087: enable CGeoApplication to listen/provide active activity

---

main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GeoItemLayer.java

rel to #10087: add mass replacement method for GeoItemLayer

rel to #10087: add mass replacement method for GeoItemLayer

---

main/src/main/java/cgeo/geocaching/models/geoitem/GeoIcon.java
main/src/main/java/cgeo/geocaching/utils/ImageUtils.java

rel to #10087: support text labels in map

rel to #10087: support text labels in map

---

main/src/main/java/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java
main/src/main/java/cgeo/geocaching/list/StoredList.java

fix #15340: change filter list default symbol

fix #15340: change filter list default symbol

---

main/src/main/java/cgeo/geocaching/unifiedmap/LayerHelper.java

reordered some UnifiedMap layers
This affects only OSM for some reason, not sure how Google Maps layers are layered??

reorder layers (fixes #15334)

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java

On storing changes to a Geocache in `CacheDetailActivity` not only store this change to the database, but send a broadcast notification that this cache has changed, so that map (and other activities) can pick up that change accordingly.

Send notification broadcast on storing changed geocache

---

main/src/main/java/cgeo/geocaching/EditWaypointActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

fixes #15348
fixes #15352
fixes #15345 (the follow-up part for waypoints)

UnifiedMap: Update waypoints on receiving cache change notification

---

main/src/main/java/cgeo/geocaching/ui/ColorPickerUI.java

Converts opaqueness value to percent for direct input

Fix input formatting in ColorPickerUI (fix #15354)

---

main/src/main/java/cgeo/geocaching/ui/GeoItemSelectorUtils.java
main/src/main/res/drawable/ic_menu_route.xml

fix #15359: remove tinting, add explicit route icon for usage in menu

fix #15359: remove tinting, add explicit route icon for usage in menu

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
main/src/main/java/cgeo/geocaching/storage/extension/OneTimeDialogs.java
main/src/main/res/values/strings.xml

As discussed in yesterday's dev meeting: Add a deprecation notice for "go to" functionality.

Add 'go to' deprecation notice

---

main/src/main/java/cgeo/geocaching/unifiedmap/LayerHelper.java

draw direction line above route line, like on old maps

direction (red) should be above route (blue) line

---

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

Clean up for `UnifiedMapActivity`: deal with comments - remove outdated ones, add savedState handling for routeTrackUtils bundle

UnifiedMapActivity: Clean up comments

---

main/src/main/java/cgeo/geocaching/connector/oc/OkapiLoggingManager.java

fix #15387: allow recommendation of oc caches again

fix #15387: allow recommendation of oc caches again

---

main/src/main/java/cgeo/geocaching/CacheListActivity.java
main/src/main/java/cgeo/geocaching/filters/core/GeocacheFilter.java
main/src/main/java/cgeo/geocaching/filters/gui/GeocacheFilterActivity.java
main/src/main/java/cgeo/geocaching/maps/MapUtils.java
main/src/main/java/cgeo/geocaching/utils/FilterUtils.java
main/src/test/java/cgeo/geocaching/utils/FilterUtilsTest.java

_(filtername)*_
put brackets around filter name
append asterix "*"
change to italic
fix #11356 
implementation after voting see https://github.com/cgeo/cgeo/issues/11356#issuecomment-1962923694

change format for filter, if it is saved different (fix #11356)

---

main/src/main/java/cgeo/geocaching/list/StoredList.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/main/java/cgeo/geocaching/ui/SimpleItemListModel.java
main/src/main/java/cgeo/geocaching/ui/SimpleItemListView.java
main/src/main/java/cgeo/geocaching/ui/ViewUtils.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/utils/CommonUtils.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java
main/src/main/res/layout/simpleitemlist_item_view.xml
main/src/test/java/cgeo/geocaching/utils/CommonUtilsTest.java

rel to #15194: adjust stored list grouping according to feature requests

rel to #15194: adjust stored list grouping according to feature requests

---

main/src/main/java/cgeo/geocaching/CachePopupFragment.java

support long click in cache popup on "edit list" for moving the cache to a different list.
fix #15275

support move to list in cache popup (fix #15275)

---

main/src/main/java/cgeo/geocaching/list/StoredList.java
main/src/main/java/cgeo/geocaching/ui/CacheListActionBarChooser.java
main/src/main/java/cgeo/geocaching/ui/SimpleItemListModel.java
main/src/main/java/cgeo/geocaching/ui/SimpleItemListView.java
main/src/main/res/drawable/ic_menu_list_group.xml
main/src/main/res/layout/simpleitemlist_item_view.xml

Right-align icons as per discussion in https://github.com/cgeo/cgeo/issues/15194

right-aligned expand/collapse icons in SimpleDialog and custom default list icons

---

main/src/main/java/cgeo/geocaching/unifiedmap/AbstractMapFragment.java
main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsFragment.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java

fix NPE in #15416

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
main/src/main/java/cgeo/geocaching/ui/ImageGalleryView.java

fix #15410: imagegallery: save and apply image gallery photo state on screen turn

fix #15410: imagegallery: save and apply image gallery photo state on screen turn

---

main/src/main/java/cgeo/geocaching/list/StoredList.java
main/src/main/java/cgeo/geocaching/settings/Settings.java
main/src/main/java/cgeo/geocaching/ui/SimpleItemListModel.java
main/src/main/java/cgeo/geocaching/ui/SimpleItemListView.java
main/src/main/res/values/preference_keys.xml

rel to #15194: save last state of reduced groups

rel to #15194: save last state of reduced groups

---

main/src/main/java/cgeo/geocaching/unifiedmap/LayerHelper.java

UnifiedMap VTM: scales hidden behind caches #15431

---

main/src/main/java/cgeo/geocaching/connector/gc/GCMap.java

rel to #15386: set viewport search limit to 500 for gc.com

rel to #15386: set viewport search limit to 500 for gc.com

---

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

fixes https://github.com/cgeo/cgeo/issues/15440

fix map crashes on applying filter

---

main/src/main/java/cgeo/geocaching/CacheListActivity.java

fix #15451: fix NPE

---

main/src/main/java/cgeo/geocaching/connector/gc/ImportBookmarkLinks.java
main/src/main/java/cgeo/geocaching/models/GCList.java

Fixes downloading bookmark lists (which was broken due to website change)

Fix downloading bookmark lists

---

main/src/main/java/cgeo/geocaching/list/StoredList.java
main/src/main/java/cgeo/geocaching/utils/CommonUtils.java
main/src/test/java/cgeo/geocaching/utils/CommonUtilsTest.java

fix #15464: put selected lists back on top

fix #15464: put selected lists back on top

---

main/src/androidTest/java/cgeo/geocaching/CgeoApplicationTest.java
main/src/main/java/cgeo/geocaching/connector/gc/GCConstants.java
main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java

fix #15264: reenable cache links in tb logs

fix #15264: reenable cache links in tb logs

---

main/src/main/java/cgeo/geocaching/list/StoredList.java

rel to #15478: place selected lists on top ungrouped

rel to #15478: place selected lists on top ungrouped

---

main/src/main/java/cgeo/geocaching/list/StoredList.java
main/src/main/java/cgeo/geocaching/ui/SimpleItemListModel.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoUtils.java

fix #15472: make stored list text filter recognize group names again

fix #15472: make stored list text filter recognize group names again

---

main/src/main/java/cgeo/geocaching/filters/core/GeocacheFilter.java
main/src/main/java/cgeo/geocaching/filters/gui/GeocacheFilterActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

fix #15514: repair named filter handling on filter quickchange

fix #15514: repair named filter handling on filter quickchange

---

main/src/main/java/cgeo/geocaching/storage/extension/Trackfiles.java

rel to #15508: make trackfiles sorted by name

rel to #15508: make trackfiles sorted by name

---

main/src/main/java/cgeo/geocaching/log/CacheLogsViewCreator.java
main/src/main/java/cgeo/geocaching/log/LogActivityHelper.java
main/src/main/java/cgeo/geocaching/log/OfflineLogEntry.java
main/src/main/java/cgeo/geocaching/ui/dialog/ContextMenuDialog.java
main/src/main/res/values/strings.xml

fix #15498: log save needs recognize add/remove of tb inventory, add context menu for offline log entries

fix #15498: log save needs recognize add/remove of tb inventory, add context menu for offline log entries

---

main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java

fix #15474: save inventory tb state on log save

fix #15474: save inventory tb state on log save

---

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

see https://github.com/cgeo/cgeo/issues/15496#issuecomment-2016615714

UnifiedMap: Remove delay on re-setting center/zoom (fix #15496)

---

main/src/main/java/cgeo/geocaching/filters/core/GeocacheFilter.java
main/src/main/java/cgeo/geocaching/filters/gui/GeocacheFilterActivity.java
main/src/main/java/cgeo/geocaching/utils/FilterUtils.java
main/src/test/java/cgeo/geocaching/filters/core/GeocacheFilterTest.java

enhance conflict resolving for fixing filter-name
see comment https://github.com/cgeo/cgeo/pull/15515#issuecomment-2021573663

fix conflict resolving for FilterNaming

---

main/src/main/java/cgeo/geocaching/ui/dialog/SimpleDialog.java

fix #15520: dont allow storing cache w/o selecting at least one list

fix #15520: dont allow storing cache w/o selecting at least one list

---

main/src/main/java/cgeo/geocaching/connector/gc/GCConstants.java
main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java

fix #15543: adapt to gc.com login page change

fix #15543: adapt to gc.com login page change

---

main/src/main/java/cgeo/geocaching/maps/CGeoMap.java
main/src/main/java/cgeo/geocaching/maps/DistanceDrawer.java
main/src/main/java/cgeo/geocaching/maps/MapDistanceDrawerCommons.java
main/src/main/java/cgeo/geocaching/maps/MapUtils.java
main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapView.java
main/src/main/java/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
main/src/main/java/cgeo/geocaching/maps/interfaces/PositionAndHistory.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/DistanceView.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/PositionLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapViewModel.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/NavigationTargetLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/PositionLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/UnifiedTargetAndDistancesHandler.java

as discusses in the related issue
example screenshot:

Move elevation info to position indicator (fix #14756)

---

README.md

The "Starting points for contribution" section links to 2 closed projects.
Reference "Good first issues" and high priorities issues, instead.
N/A

Update readme to remove links to closed projects

---

main/src/main/java/cgeo/geocaching/utils/TextUtils.java

fix #15567: prevent npe on tracks with null displayname

fix #15567: prevent npe on tracks with null displayname

---

main/src/main/java/cgeo/geocaching/connector/gc/GCWebAPI.java
main/src/main/java/cgeo/geocaching/network/HttpRequest.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapViewModel.java
main/src/main/java/cgeo/geocaching/utils/livedata/CollectionLiveData.java

rel to #15551: tweak gc.com cache search parameters

rel to #15551: tweak gc.com cache search parameters

---

main/src/main/java/cgeo/geocaching/connector/gc/GCConstants.java
main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java

make found counter detection a bit more flexible to positional changes in JS array

Fix found counter detection (rel. to #15562)

---

main/src/androidTest/java/cgeo/geocaching/CgeoApplicationTest.java
main/src/androidTest/res/raw/tb3f206.htm
main/src/androidTest/res/raw/tbxatg.htm
main/src/main/java/cgeo/geocaching/connector/gc/GCConstants.java
main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java

TB parsing fixes (mitigating the recent website changes)
- added aria attribute in trackable icon / type parsing (optional, since not used in all places)
- new HTML structure for log entities

Some fixes for TB parsing

---

main/src/androidTest/res/raw/tb11jzk.html
main/src/androidTest/res/raw/tb14wfv.html
main/src/androidTest/res/raw/tb2j1vz.html
main/src/androidTest/res/raw/tb3f206.htm
main/src/androidTest/res/raw/tb4bpqk.html
main/src/androidTest/res/raw/tb4cwjx.html
main/src/androidTest/res/raw/tb84bz5.html
main/src/androidTest/res/raw/trackable_tb2r124.htm
tests/scripts/update-trackables

- adjusts `update-trackables` script to changed source folder structure and adds some progress info
- updates existing tb file copies
- adds tb file copies for tb2j1vz and for tb4bpqk as requested in https://github.com/cgeo/cgeo/pull/15556#pullrequestreview-1984697976

Fix update_trackables script + update downloaded tb files

---

main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsFragment.java

UnifiedMap GM: Disable auto rotation by tapping on compass rose

---

main/src/main/java/cgeo/geocaching/connector/gc/GCConstants.java
main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java

"findCount" source seems to have changed again (or there are variations depending on login state)

Findcount adaption (simplified version)

---

main/src/main/java/cgeo/geocaching/unifiedmap/LoadInBackgroundHandler.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

on mapping list or search result: reload caches/waypoints on crossing waypoint limit

Show/hide waypoints if crossing limits (fix #15532)

---

main/src/main/java/cgeo/geocaching/connector/gc/GCLogAPI.java

emergency fix for posting logs #15633

fix posting logs (#15633)

---

main/src/main/java/cgeo/geocaching/connector/gc/GCLogAPI.java

addresses https://github.com/cgeo/cgeo/issues/15633#issuecomment-2063589379

fix getting the csrf token for more scenarios

---

main/src/main/java/cgeo/geocaching/connector/gc/GCLogAPI.java
main/src/main/java/cgeo/geocaching/log/LogActivityHelper.java

fixes #15587
for own logs NO body must be provided, for other logs a body must be provided

fix deleting own logs on GC

---

main/src/main/java/cgeo/geocaching/utils/ImageUtils.java

fix #15526: prevent NPE on bitmaps will null config

fix #15526: prevent NPE on bitmaps will null config

---

main/src/main/java/cgeo/geocaching/utils/SystemInformation.java

related to #15620/#15621 and others

Append configured routing modes to system information

---

main/src/main/res/drawable/ic_menu_foundlog.xml
main/src/main/res/menu/cache_list_context.xml
main/src/main/res/menu/cache_options.xml
main/src/main/res/menu/logging_ui.xml
main/src/main/res/menu/map_activity.xml

Changes log icon from "edit pen" to "smiley":
fixes #15619

change "log" icon to smiley

---

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

On mapping a single cache filter the waypoints in `reloadCachesAndWaypoints`
related #15611
does not fix the refresh problem on changing the setting in the settings-popup-dialog

Fix filtering waypoints for current cache in map-view

---

main/src/main/java/cgeo/geocaching/filters/gui/CheckboxFilterViewHolder.java
main/src/main/java/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java
main/src/main/java/cgeo/geocaching/filters/gui/StoredListsFilterViewHolder.java

style list selection dialog in "Stored Lists" filter #15540

---

main/src/main/res/layout/cache_offlinebox.xml

Use different edit lists icon as discussed in #15709

new edit lists icon

---

main/src/main/java/cgeo/geocaching/files/AbstractTrackOrRouteParser.java
main/src/main/java/cgeo/geocaching/files/GPXTrackOrRouteParser.java
main/src/main/java/cgeo/geocaching/models/RouteSegment.java

Reads elevation info from GPX tracks to be able to display an elevation chart

Read elevation info from track (fix #15683)

---

main/src/main/java/cgeo/geocaching/unifiedmap/AbstractMapFragment.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsFragment.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/NavigationTargetLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/UnifiedTargetAndDistancesHandler.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java

UnifiedMap: Fix compass rose hidden behind distance views

---

main/src/main/java/cgeo/geocaching/connector/ConnectorFactory.java
main/src/main/java/cgeo/geocaching/connector/IConnector.java
main/src/main/java/cgeo/geocaching/connector/oc/OCApiConnector.java

(fix #15702)
Adds credentials check for OC based connectors

Enable install wizard credential check for OC connectors

---

main/src/main/res/layout-h390dp-land/map_detailsfragment.xml
main/src/main/res/layout-land/map_detailsfragment.xml
main/src/main/res/layout/map_detailsfragment_sidesheet.xml

UnifiedMap: Show info sheet's toolbar in landscape mode
(when enough height is available) (rel. to #15309)

UnifiedMap: Show info sheet's toolbar in landscape mode

---

main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java

Resets state of "followMyLocation" to `false` on manually moving the map (which nearly always includes a slight movement).
UnifiedMap VTM only (as UnifiedMap Google already behaves like that).

UnifiedMap VTM: reset followMyLocation on manual zoom/move (fix #15590)

---

main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeThemeHelper.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeThemeSettingsFragment.java
main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/AbstractMapsforgeOfflineTileProvider.java
main/src/main/res/values/preference_keys.xml
main/src/main/res/values/strings.xml

Adds an option to VTM theme options: "Show buildings in 3D" (default: true)

UnifiedMap VTM: toggle buildings 2D/3D

---

main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeVtmGeoItemLayer.java
main/src/main/java/cgeo/geocaching/utils/ContextLogger.java

rel to #15726: vtm markersymbol: catch exception and add logging

rel to #15726: vtm markersymbol: catch exception and add logging

---

main/src/main/java/cgeo/geocaching/location/GeopointParser.java

rel to #15687: solve anr on parsing PN with many coords by limiting to max of 20

rel to #15687: solve anr on parsing PN with many coords by limiting to max of 20

---

main/src/main/java/cgeo/geocaching/settings/Settings.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeVtmGeoItemLayer.java
main/src/main/res/values/preference_keys.xml

rel to #15726: VTM, make atlas usage optional

rel to #15726: VTM, make atlas usage optional

---

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/NavigationTargetLayer.java

Updates route to current navigation target on changing routing mode even if GPS is currently disabled.
(rel. to #15652)

UnifiedMap: Recalculate route to nav target on routing mode change

---

main/src/main/java/cgeo/geocaching/connector/gc/GCLogAPI.java
main/src/main/java/cgeo/geocaching/connector/trackable/TravelBugLoggingManager.java

fix loading of available logtypes for TBs

---

main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsThemeHelper.java
main/src/main/res/raw/googlemap_style_details.json
main/src/main/res/values/strings.xml

Google Map: add 'Details' theme

Google Map: add 'Details' theme

---

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapViewModel.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/CacheCirclesLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/GeoItemsLayer.java
main/src/main/java/cgeo/geocaching/utils/livedata/CollectionLiveData.java

fix #15492: avoid concurrentmodificationexception for waypoints and cacheStars

fix #15492: avoid concurrentmodificationexception for waypoints and cacheStars

---

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

correctly update forceCompactIconMode

---

main/src/main/java/cgeo/geocaching/connector/gc/GCLogin.java

Enhance logging in case of GCLogin errors
I worked on support ticket  #283395 which is about gc login problems. The user sent a log but it was still hard to analyze because some detailled into is missing in our log files. This PR adds some more info to the log in case of GC logging failures

Enhance logging in case of GCLogin errors

---

main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsThemeHelper.java

fix merge error on master

---

main/src/main/java/cgeo/geocaching/ui/CacheListAdapter.java
main/src/main/java/cgeo/geocaching/ui/DistanceView.java

Sorts the result of the search for target-coordinates according to the target-coordinates and not according to the current coordinates.
rel #15618

Search for coordinates: Show direction and distance to target and not to current position

---

main/build.gradle
mapswithme-api/build.gradle
organicmaps-api/build.gradle

Let's start testing with targetSDK == 34

set targetSDK to 34

---

main/AndroidManifest.xml

fixes https://github.com/cgeo/cgeo/issues/15834

add "FOREGROUND_SERVICE_DATA_SYNC" permission

---

main/src/main/java/cgeo/geocaching/address/AddressListActivity.java
main/src/main/java/cgeo/geocaching/storage/DataStore.java
main/src/main/java/cgeo/geocaching/utils/SystemInformation.java

This PR adds some logging and system information to c:geo. It is information which I missed to work on a couple of support tickets in the past and hope will help for future support tickets.

Adding logging and system information

---

main/src/main/java/cgeo/geocaching/models/CacheArtefactParser.java

fix support ticket 510559: priorize pn var scanning in backup brackets

fix support ticket 510559: priorize pn var scanning in backup brackets

---

main/src/main/java/cgeo/geocaching/utils/formulas/FormulaUtils.java
main/src/main/java/cgeo/geocaching/utils/formulas/Value.java

fix support ticket 671703: enable vanity function for long strings

fix support ticket 671703: enable vanity function for long strings

---

main/src/main/res/values/strings.xml

Proposal for improved text according to discussion in #15841

Fix #15841 - Improve orphaned data description

---

main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapView.java
main/src/main/java/cgeo/geocaching/unifiedmap/AbstractMapFragment.java
main/src/main/java/cgeo/geocaching/utils/HideActionBarUtils.java

Merge separate implementations for compass positioning of GMv2 and UnifiedMap into a single method, along the way fixing compass rose positioning with active filterbar for UnifiedMap.

Deduplicate code and fix #15862

---

main/build.gradle
main/src/main/java/cgeo/geocaching/DBInspectionActivity.java
main/src/main/res/layout/dbinspection_activity.xml

Small improvements / fixes for DB inspection:
- Fix repeated 'cannot be edited' message
- Add some padding to table selector / action buttons

Fix repeated 'cannot be edited' message

---

main/src/main/java/cgeo/geocaching/models/RouteItem.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/utils/MapMarkerUtils.java

- Fix highlighting for scaled geo items
- Fix highlighting for waypoints
- Extract highlighting to MapMarkerUtils

Some highlighting fixes

---

main/src/main/java/cgeo/geocaching/utils/formulas/VariableList.java

in method VariableList.toMap consider null-value as empty string
fix #15589

Consider null in VariableList.toMap correctly (fix #15589)

---

main/build.gradle
main/src/androidTest/java/cgeo/geocaching/ExampleInstrumentationTest.java
main/src/debug/res/values/strings_debug.xml

...just playing around what CI thinks about it...

developer app id gradle script enhancements

---

main/src/main/res/layout-land/map_settings_button.xml
main/src/main/res/layout/cache_filter_activity.xml
main/src/main/res/layout/cache_filter_list_item.xml
main/src/main/res/layout/cache_offlinebox.xml
main/src/main/res/layout/cachedetail_description_page.xml
main/src/main/res/layout/cachedetail_details_page.xml
main/src/main/res/layout/image_gallery_category.xml
main/src/main/res/layout/map_settings_button.xml
main/src/main/res/layout/map_settings_dialog.xml
main/src/main/res/layout/search_activity.xml
main/src/main/res/layout/simple_dialog_title_view.xml

https://github.com/cgeo/cgeo/pull/15915 added "hint" to Button / ImageView elements instead of the intended tooltipText which should only be used for TextView as placeholder text

hint should be tooltipText on buttons

---

main/src/main/java/cgeo/geocaching/CacheListActivity.java
main/src/main/java/cgeo/geocaching/list/StoredList.java
main/src/main/java/cgeo/geocaching/ui/CacheListActionBarChooser.java
main/src/main/java/cgeo/geocaching/ui/SimpleItemListModel.java
main/src/main/java/cgeo/geocaching/ui/SimpleItemListView.java
main/src/main/java/cgeo/geocaching/ui/dialog/SimpleDialog.java

fix #15935: open list selection with previous selected list in view

fix #15935: open list selection with previous selected list in view

---

main/src/main/java/cgeo/geocaching/connector/gc/GCMap.java
main/src/main/java/cgeo/geocaching/filters/core/AttributesGeocacheFilter.java

fix #15912: dont issue exclude attribute filter towards gc.com server  (not supported)

fix #15912: dont issue exclude attribute filter towards gc.com server  (not supported)

---

main/src/main/res/layout/authorization_credentials_activity.xml
main/src/main/res/layout/authorization_token_activity.xml

fix #15950: add password toggle option to password fields

fix #15950: add password toggle option to password fields

---

main/src/main/java/cgeo/geocaching/connector/gc/GCConstants.java
main/src/main/java/cgeo/geocaching/connector/trackable/GeokretyConnector.java

fix #15143: reenable geokrety search using trackingcodes

fix #15143, fix #15959: reenable geokrety search using trackingcodes

---

main/src/main/java/cgeo/geocaching/connector/trackable/GeokretyConnector.java

Fixes the first two issues in #15965 / failing tests
- GeokretyConnectorTest.testCanHandleTrackable
- TrackableTest.testTrackableUrl

Fixes for GK.canHandleTrackable (rel. to #15965)

---

main/src/main/java/cgeo/geocaching/ui/ImageActivityHelper.java

fix #15972: log images, allow opening non-local data

fix #15972: log images, allow opening non-local data

---

main/src/main/java/cgeo/geocaching/list/AbstractList.java
main/src/main/java/cgeo/geocaching/list/StoredList.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/main/java/cgeo/geocaching/ui/SimpleItemListModel.java
main/src/main/java/cgeo/geocaching/ui/SimpleItemListView.java
main/src/main/java/cgeo/geocaching/ui/TextSpinner.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsThemeHelper.java
main/src/main/java/cgeo/geocaching/utils/CommonUtils.java
main/src/main/java/cgeo/geocaching/utils/ItemGroup.java
main/src/main/java/cgeo/geocaching/utils/formulas/FormulaUtils.java
main/src/main/java/cgeo/geocaching/utils/functions/Func5.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java
main/src/main/res/layout/simpleitemlist_item_view.xml
main/src/test/java/cgeo/geocaching/utils/CommonUtilsTest.java
main/src/test/java/cgeo/geocaching/utils/ItemGroupTest.java

fix #15938: allow more hierarchy levels for stored list grouping

fix #15938: allow more hierarchy levels for stored list grouping

---

main/src/main/res/values-de/strings.xml
main/src/main/res/values/strings.xml

Rename sort-criteria "Date logged"  to "Date Logged (Own Logged)" to avoid confusion
rel. #14426

Rename sort-criteria "Date logged"  to "Date Logged (Own Logged)"

---

main/build.gradle

related to https://github.com/cgeo/cgeo/issues/15938#issuecomment-2296666155 / https://github.com/cgeo/cgeo/pull/15988#issue-2473811170

Use version numbers for dbi imports instead of -snapshot

---

main/AndroidManifest.xml
main/src/main/java/cgeo/geocaching/CgeoApplication.java
main/src/main/java/cgeo/geocaching/ui/notifications/NotificationChannels.java
main/src/main/java/cgeo/geocaching/ui/notifications/Notifications.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoDialogManager.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoGame.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoGameService.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoLocationProvider.java

rel to #10087: add wherigo service and basic notifications

rel to #10087: add wherigo service and basic notifications

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
main/src/main/java/cgeo/geocaching/apps/cache/WhereYouGoApp.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoDownloader.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoGame.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoUtils.java
main/src/main/res/layout/cachedetail_details_page.xml

Wherigo: add cartridge download button to cache details

Wherigo: add cartridge download button to cache details

---

main/src/main/java/cgeo/geocaching/ui/FormulaEditText.java

Fix NPE on waypoint-projection
Function `ensureFormula `does only ensure a valid formula but formula == null is still possible after that
checking for formula != null
If formula is null, the variables are created from the formulaString (has to compile for that)
fix #16041
fix #15756

Fix NPE on waypoint-projection (fix #16041)

---

main/src/main/java/cgeo/geocaching/connector/gc/GCLogin.java
main/src/main/java/cgeo/geocaching/ui/DialogWebView.java
main/src/main/res/layout/gc_manual_login.xml

Repair GC Manual login: show soft keyboard on textfield click

Repair GC Manual login

---

main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeVtmGeoItemLayer.java

fix #15998: unhighlights cache when logging from cache popup

fix #15998: unhighlights cache when logging from cache popup

---

main/src/main/java/cgeo/geocaching/MainActivity.java
main/src/main/java/cgeo/geocaching/settings/AbstractCredentialsAuthorizationActivity.java

Fix Manual login: show manual login only if there are credentials

Fix Manual login: show manual login only if there are credentials

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java

fix #16058: prevent npe on editpersonalnote when cache is null

fix #16058: prevent npe on editpersonalnote when cache is null

---

main/src/main/java/cgeo/geocaching/location/Units.java

(refers to elevation on current position, activated with "show elevation" in settings => map content)

Show current elevation on map without fraction (rel. to #16046)

---

main/src/main/java/cgeo/geocaching/utils/formulas/FormulaUtils.java
main/src/test/java/cgeo/geocaching/utils/formulas/FormulaUtilsTest.java

fix #16043: adjust formula scan parameters

fix #16043: adjust formula scan parameters

---

main/src/main/java/cgeo/geocaching/location/Units.java
main/src/main/java/cgeo/geocaching/location/Viewport.java
main/src/main/java/cgeo/geocaching/maps/DefaultMap.java
main/src/main/java/cgeo/geocaching/ui/ViewUtils.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapType.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoLocationProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoThingDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoUtils.java
main/src/main/res/layout/wherigo_activity.xml

Wherigo: add display on map actions

Wherigo: add display on map actions

---

main/src/main/java/cgeo/geocaching/maps/MapProviderFactory.java
main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/TileProviderFactory.java
main/src/main/res/menu/map_activity.xml

Feature request from our [last dev meeting](https://github.com/orgs/cgeo/discussions/42#discussioncomment-10307873): Separate online and offline map sources / tile providers by a visible line.

Add separator between offline and online map sources

---

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/GeoItemsLayer.java

fix #16015: handle update of cache or waypoint coordinates for unified map

fix #16015: handle update of cache or waypoint coordinates for unified map

---

main/src/main/java/cgeo/geocaching/maps/MapDistanceDrawerCommons.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/UnifiedTargetAndDistancesHandler.java

#15541 removed elevation info from distance view section, thus the description needs to be updated

Update outdated comment (rel. to #15541)

---

main/src/main/java/cgeo/geocaching/utils/CheckerUtils.java

fixes https://github.com/cgeo/cgeo/issues/16081

fix #16081: detect geocheck.EU.org checker

---

main/src/main/java/cgeo/geocaching/enumerations/QuickLaunchItem.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/RenderThemeHelper.java
main/src/main/java/cgeo/geocaching/ui/WherigoMediaView.java
main/src/main/java/cgeo/geocaching/utils/AudioClip.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoDialogManager.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoDownloader.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoGame.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoLocationProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoObjectType.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoUtils.java

Wherigo: add basic audio support

Wherigo: add basic audio support

---

main/build.gradle
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforge/MapsforgeFragment.java

Update Mapsforge lib to include latest fixes for rotation gesture (UnifiedMap)

UnifiedMap: Update Mapsforge map rotation

---

main/src/main/java/cgeo/geocaching/unifiedmap/mapsforge/MapsforgeFragment.java

Restore old behavior: Enable rotation gesture in manual rotation mode only

UnifiedMap Mapsforge: Enable rotation gesture in manual rot mode only

---

main/src/main/java/cgeo/geocaching/models/Geocache.java
main/src/main/java/cgeo/geocaching/utils/ImageUtils.java

fix #16086: multiple images in Personal Note not added to images tab

---

main/src/main/java/cgeo/geocaching/files/AbstractTrackOrRouteParser.java
main/src/main/java/cgeo/geocaching/files/GPXTrackOrRouteParser.java

Fix elevation info on importing tracks with multiple segments

Fix elev. info on importing tracks with multiple segments (fix #16082)

---

main/src/main/java/cgeo/geocaching/maps/CGeoMap.java
main/src/main/java/cgeo/geocaching/maps/MapDistanceDrawerCommons.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/UnifiedTargetAndDistancesHandler.java
main/src/main/res/layout/map_distanceinfo.xml

As discussed in [#15706](https://github.com/cgeo/cgeo/issues/15706#issuecomment-2351658465): Refactor distance views to be static TextViews below target / supersize info instead of dynamically creating/removing them.

Refactor distance views (rel. to #15706)

---

main/src/main/java/cgeo/geocaching/CachePopupFragment.java

Fixes an NPE reported by Play Store logs

Prevent NPE in cache/waypoint info sheet

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java

Prevent NPE in updateOfflineBox reported by Play Store logs

Prevent NPE on updating offline box

---

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

Simplify old code-segments from `NewMap` to avoid access to mapType.followMyLocation  where mapType is null
see https://github.com/cgeo/cgeo/pull/16097#discussion_r1769621736

Avoid NPE in unified map activity

---

main/src/androidTest/java/cgeo/geocaching/brouter/util/CheapAngleMeterTest.java
main/src/main/java/cgeo/geocaching/LooperLogger.java
main/src/main/java/cgeo/geocaching/apps/AbstractLocusApp.java
main/src/main/java/cgeo/geocaching/apps/navi/MapsMeApp.java
main/src/main/java/cgeo/geocaching/brouter/core/FormatJson.java
main/src/main/java/cgeo/geocaching/brouter/core/FormatKml.java
main/src/main/java/cgeo/geocaching/brouter/core/OsmTrack.java
main/src/main/java/cgeo/geocaching/connector/ConnectorFactory.java
main/src/main/java/cgeo/geocaching/connector/al/ALApi.java
main/src/main/java/cgeo/geocaching/maps/routing/Routing.java
main/src/main/java/cgeo/geocaching/models/Geocache.java
main/src/main/java/cgeo/geocaching/network/Tls12SocketFactory.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java
main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/TileProviderFactory.java
main/src/main/java/cgeo/geocaching/utils/MapMarkerUtils.java
main/src/main/java/cgeo/geocaching/utils/SystemInformation.java
main/src/main/java/cgeo/geocaching/utils/config/LegacyFilterConfigParser.java

- Fix some string concatenation in StringBuilder issues
- Fix collection to array conversions
- Make TileProviderFactory pure utility class
- Fix empty string comparisons
- Mark some inner classes as static
- Remove exceptions declarations which are too specific
- Fix some BRouter tests with static methods called via instance

More code cleanups

---

main/src/androidTest/java/cgeo/geocaching/connector/trackable/TravelBugConnectorTest.java
main/src/androidTest/java/cgeo/geocaching/models/TrackableTest.java

After the Url fix in #16117 the test needs to be adapted to this change

Fix Uri in testGetUrl

---

main/src/androidTest/java/cgeo/geocaching/connector/gc/GCParserTest.java
main/src/androidTest/java/cgeo/geocaching/connector/gc/TrackablesTest.java
main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java
main/src/main/java/cgeo/geocaching/maps/MapProviderFactory.java
main/src/main/java/cgeo/geocaching/network/Tls12SocketFactory.java
main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/TileProviderFactory.java
main/src/main/java/cgeo/geocaching/utils/formulas/FormulaUtils.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java

greenify PR build

---

main/src/androidTest/java/cgeo/geocaching/connector/gc/GCParserTest.java
main/src/main/java/cgeo/geocaching/files/GPXTrackOrRouteParser.java

greenify release build

---

main/src/main/java/cgeo/geocaching/enumerations/QuickLaunchItem.java
main/src/main/java/cgeo/geocaching/location/Units.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/WherigoLayer.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoCartridgeDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoCartridgeInfo.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoGame.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoThingListDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoThingType.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoUtils.java
main/src/main/res/layout/cachedetail_details_page.xml
main/src/main/res/layout/wherigo_activity.xml
main/src/main/res/layout/wherigo_cartridge_details.xml

WherigoPlayer: refining gui workflow, first dialog with html considerations, starting to create unique list layout

WherigoPlayer: refining gui workflow, first dialog with html considerations, starting to create unique list layout

---

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapType.java

Enable live-option for showing map after search for address / coordinate 
(restore behavior of old map)
Consider UnifiedMapTypeType.UMTT_TargetCoords as "Live-Map"-able

[UnifiedMap] enable live for adress search

---

main/AndroidManifest.xml
main/src/main/java/cgeo/geocaching/settings/Settings.java
main/src/main/java/cgeo/geocaching/ui/SimpleItemListModel.java
main/src/main/java/cgeo/geocaching/ui/SimpleItemListView.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/WherigoLayer.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoCartridgeDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoCartridgeInfo.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoDownloader.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoGame.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoGameService.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoInputDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoPushDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoThingDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoThingListDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoThingType.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoUtils.java
main/src/main/res/layout/wherigo_activity.xml
main/src/main/res/layout/wherigo_cartridge_details.xml
main/src/main/res/layout/wherigo_thing_details.xml
main/src/main/res/layout/wherigo_thing_list.xml
main/src/main/res/layout/wherigolist_item.xml

Wherigo Player: ready for master

Wherigo Player: ready for master

---

main/src/main/java/cgeo/geocaching/unifiedmap/layers/UnifiedTargetAndDistancesHandler.java

Fixes the "no distance info being shown with routing mode = straight" issue as described in https://github.com/cgeo/cgeo/issues/15706#issuecomment-2385715890

Show straight distance fix (rel. to #15706)

---

main/src/main/java/cgeo/geocaching/maps/MapSettingsUtils.java
main/src/main/java/cgeo/geocaching/ui/ViewUtils.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

UnifiedMap: Don't show compass rose if rotation mode == OFF (related to #16151)

UnifiedMap: Don't show compass rose if rotation mode == OFF

---

main/src/main/java/cgeo/geocaching/utils/DebugUtils.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoCartridgeDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoCartridgeInfo.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoErrorDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoGame.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoInputDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoLocationProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoPushDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoSaveFileHandler.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoSavegameInfo.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoThingDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoUtils.java
main/src/main/res/layout/wherigo_activity.xml
main/src/main/res/layout/wherigo_cartridge_details.xml
main/src/main/res/layout/wherigo_thing_details.xml

fix #16170: wherigo dialog bugs

fix #16170: wherigo dialog bugs

---

main/src/main/java/cgeo/geocaching/unifiedmap/AbstractMapFragment.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/res/layout-land/unifiedmap_activity.xml

- Prevent NPE after screen rotation ( #16190)
- Show compass rose & follow me button in landscape mode

UnifiedMap: Prevent NPE after screen rotation ( #16190)

---

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/res/layout/map_bearingindicator.xml

Also handle taps on image's background
Related to discussion in https://github.com/cgeo/cgeo/issues/16151#issuecomment-2400913210

UnifiedMap: Increase touch size for followMyLocation

---

main/AndroidManifest.xml
main/src/main/java/cgeo/geocaching/ui/dialog/SimpleDialog.java
main/src/main/java/cgeo/geocaching/wherigo/IWherigoDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoCartridgeDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoCartridgeInfo.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoDialogManager.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoErrorDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoGame.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoInputDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoPushDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoSaveFileHandler.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoSavegameInfo.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoThingDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoThingListDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoUtils.java
main/src/main/res/layout/wherigo_activity.xml
main/src/main/res/layout/wherigo_thing_details.xml
main/src/main/res/values/themes.xml

Wherigo: complete gui flow

---

main/AndroidManifest.xml
main/src/main/java/cgeo/geocaching/storage/extension/OneTimeDialogs.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoCartridgeDialogProvider.java
main/src/main/res/menu/main_activity_options.xml
main/src/main/res/values/strings.xml

Wherigo: add one-time-message

---

main/project/rawimages/video_library_24dp.svg
main/src/main/java/cgeo/geocaching/wherigo/IWherigoDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoCartridgeDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoCartridgeInfo.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoDialogManager.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoDownloader.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoErrorDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoGame.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoGameService.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoInputDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoPushDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoSavegameInfo.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoThingDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoThingListDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoThingType.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoUtils.java
main/src/main/res/drawable/ic_menu_select_play.xml
main/src/main/res/layout/wherigo_activity.xml
main/src/main/res/layout/wherigo_cartridge_details.xml
main/src/main/res/layout/wherigo_thing_details.xml
main/src/main/res/layout/wherigo_thing_list.xml
main/src/main/res/values/strings.xml

Wherigo: internationalize / localize texts

Wherigo: internationalize / localize texts

---

main/src/main/java/cgeo/geocaching/maps/MapSettingsUtils.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/RenderThemeSettingsFragment.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforge/MapsforgeFragment.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforge/MapsforgeThemeSettingsFragment.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeThemeHelper.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java

- remove some unused (or constant) parameters
- remove some commented-out or unused code
- remove some unnecessary type casts
- add some implicit null checks (`requireXXX()` instead of `getXXX()`)
- simplifies collection empty check

UnifiedMap: Some code cleanup

---

main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java
main/src/main/res/drawable/wherigo_close.xml
main/src/main/res/drawable/wherigo_download.xml
main/src/main/res/drawable/wherigo_icon_inventory.xml
main/src/main/res/drawable/wherigo_icon_locations.xml
main/src/main/res/drawable/wherigo_icon_search.xml
main/src/main/res/drawable/wherigo_icon_tasks.xml
main/src/main/res/drawable/wherigo_load.xml
main/src/main/res/drawable/wherigo_save.xml
main/src/main/res/layout/wherigo_activity.xml

another batch of WIG UI stuff ;-)
- fix missing icon tints and format the files (fixes https://github.com/cgeo/cgeo/issues/16227)
- remove the large "details" button in favor of a "i" icon in toolbar
- remove the title view in favor of setting the activity title

WIG UI tuning

---

main/src/main/java/cgeo/geocaching/connector/gc/GCConstants.java
main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java

adjusts the regexp to work for all languages and adds a additional try-catch to avoid issues on furture website changes

adjust event time recognition

---

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/res/drawable/map_followmylocation_btn.xml
main/src/main/res/drawable/map_followmylocation_off_btn.xml
main/src/main/res/drawable/map_zoom_divider.xml
main/src/main/res/drawable/map_zoomin.xml
main/src/main/res/drawable/map_zoomin_btn.xml
main/src/main/res/drawable/map_zoomout.xml
main/src/main/res/layout/map_zoom_control.xml
main/src/main/res/values/colors.xml
main/src/main/res/values/styles.xml

fixes https://github.com/cgeo/cgeo/issues/16212
https://github.com/cgeo/cgeo/issues/16212

finetune map button layout

---

main/src/main/java/cgeo/geocaching/ui/dialog/SimpleDialog.java
main/src/main/java/cgeo/geocaching/utils/LocalizationUtils.java
main/src/main/java/cgeo/geocaching/wherigo/IWherigoDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoCartridgeDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoDialogManager.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoErrorDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoGame.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoInputDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoPushDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoThingDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoThingListDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoUtils.java
main/src/main/res/layout/wherigo_activity.xml
main/src/main/res/layout/wherigo_cartridge_details.xml
main/src/main/res/values/strings.xml

rel to #16224: enable wherigo player to pause and unpause dialogs

rel to #16224: enable wherigo player to pause and unpause dialogs

---

main/src/main/java/cgeo/geocaching/EditWaypointActivity.java
main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java
main/src/main/java/cgeo/geocaching/files/GPXParser.java
main/src/main/java/cgeo/geocaching/filters/core/StatusGeocacheFilter.java
main/src/main/java/cgeo/geocaching/models/Geocache.java

Remove check for filled final waypoint from filter `corrected coordinates`
Introduce method `createOriginalWaypoint` to avoid duplicate code
fix #16247

Remove filled final from corrected coordinates filter

---

main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoCartridgeDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoCartridgeInfo.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoSavegameInfo.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoUtils.java
main/src/main/res/values/strings.xml

fix #16220: Wherigo: add option to delete savefiles on save and load

fix #16220: Wherigo: add option to delete savefiles on save and load

---

main/src/main/java/cgeo/geocaching/models/CacheVariableList.java
main/src/main/java/cgeo/geocaching/models/Geocache.java
main/src/main/java/cgeo/geocaching/storage/DataStore.java

Update the member `finalDefined` after recalculation of waypoint
Store it in Database
rel #16247

Update finalDefined for calculated waypoint

---

main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/TileProviderFactory.java

Consider `AbstractMapsforgeVTMOfflineTileProvider` and `MapsforgeVTMMultiOfflineTileProvider` also for separated offline-maps

Add separator for VTM-offline-maps

---

main/src/main/java/cgeo/geocaching/wherigo/IWherigoDialogControl.java
main/src/main/java/cgeo/geocaching/wherigo/IWherigoDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoCartridgeDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoDialogManager.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoErrorDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoGameService.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoInputDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoPushDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoThingDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoViewUtils.java

Wherigo: refactor DialogManager

Wherigo: refactor DialogManager

---

main/src/main/java/cgeo/geocaching/ui/dialog/Dialogs.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoGame.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoUtils.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoViewUtils.java
main/src/main/res/drawable/map_quick_wherigo.xml
main/src/main/res/layout-land/map_settings_button.xml
main/src/main/res/layout/map_settings_button.xml
main/src/main/res/layout/wherigo_map_quickinfos.xml

fix #16237: introduce wherigo map quickinfos

fix #16237: introduce wherigo map quickinfos

---

main/src/main/java/cgeo/geocaching/utils/HideActionBarUtils.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoInfoBarView.java
main/src/main/res/layout/activity_navigationbar.xml
main/src/main/res/layout/unifiedmap_activity.xml
main/src/main/res/layout/wherigo_info_bar_view.xml

fix #16238: add wherigo actionbar to most important activities when wherigo is running

fix #16238: add wherigo actionbar to most important activities when wherigo is running

---

main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/CyclosmSource.java
main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/CyclosmVTMSource.java
main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/MapToolkitVTMHillshadingSource.java
main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/MapilionVTMHillshadingSource.java
main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/OpenTopoMapSource.java
main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/OpenTopoMapVTMSource.java
main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/OsmDeSource.java
main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/OsmDeVTMSource.java
main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/OsmOrgSource.java
main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/OsmOrgVTMSource.java
main/src/main/res/values/strings_not_translatable.xml

Use resource-string for map-names in unified map
https://github.com/cgeo/cgeo/pull/16260#issuecomment-2433385979

Use resource-string for map-names

---

main/src/main/java/cgeo/geocaching/CacheListActivity.java

Do not ask user for list deletion when returning from PQ or bookmark list selection and having an empty cache list.
(relevant for this workflow: Create a new list, start PQ/BM list selection, get queried on returning to cache list)

Do not ask on empty list after PQ download start (fix #16192)

---

main/src/main/java/cgeo/geocaching/utils/MapMarkerUtils.java

for owned caches with offline log show the log marker instead of owner marker

show offline log marker for owned caches (fixes #16284)

---

main/AndroidManifest.xml
main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoGame.java
main/src/main/res/layout/cachedetail_details_page.xml

rel to #16279: wherigo: fix diverse findings in wherigo player

rel to #16279: wherigo: fix diverse findings in wherigo player

---

.idea/checkstyle-idea.xml
main/build.gradle

Update checkstyle accordingly to codacy.

checkstyle update

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoCartridgeDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoCartridgeInfo.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoGame.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoSaveFileHandler.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoSavegameInfo.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoUtils.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoViewUtils.java
main/src/main/res/layout/wherigo_activity.xml
main/src/main/res/layout/wherigo_map_quickinfos.xml
main/src/main/res/values/strings.xml

fix #16219: wherigo: add cache context via cache detail selection and save file

fix #16219: wherigo: add cache context via cache detail selection and save file

---

main/src/main/java/cgeo/geocaching/utils/formulas/VariableList.java

fix #16310: fix npe in variablelist on changevariable

fix #16310: fix npe in variablelist on changevariable

---

main/src/main/java/cgeo/geocaching/log/LogUtils.java

fixes https://github.com/cgeo/cgeo/issues/16283
after submitting a log update cache status if appropiate, e.g.
found = mark as found
archive = mark as archived
needs maintainance = set NM attribute
...

update cache status on sending a log

---

main/build.gradle
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeV6GeoItemLayer.java

Make position marker on UnifiedMap Mapsforge rotate according to map rotation.
Builds upon a quick addition to the Mapsforge library - thanks @devemux86!

UnifiedMap Mapsforge: Rotate position marker (rel. to #16307)

---

main/src/androidTest/java/cgeo/geocaching/downloader/DownloaderTest.java
main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
main/src/main/java/cgeo/geocaching/network/HtmlImage.java
main/src/main/java/cgeo/geocaching/utils/TextUtils.java
main/src/main/java/cgeo/geocaching/utils/html/HtmlStyle.java
main/src/main/java/cgeo/geocaching/utils/html/HtmlUtils.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoGame.java
main/src/main/res/values/strings.xml
main/src/test/java/cgeo/geocaching/utils/html/HtmlUtilsJunitTest.java

fix #16300: add html syntax highlighting to description style options

fix #16300: add html syntax highlighting to description style options

---

main/src/androidTest/java/cgeo/geocaching/downloader/DownloaderTest.java
main/src/main/java/cgeo/geocaching/models/CacheVariableList.java

rel to #16314: cachevariablelist: fix npe on nonavailable cache

rel to #16314: cachevariablelist: fix npe on nonavailable cache

---

main/src/main/java/cgeo/geocaching/utils/SystemInformation.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoCartridgeInfo.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoErrorDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoGame.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoSavegameInfo.java
main/src/main/res/layout/simple_dialog_title_view.xml
main/src/main/res/layout/simple_dialog_view.xml
main/src/main/res/layout/wherigo_cartridge_details.xml
main/src/main/res/layout/wherigo_thing_details.xml
main/src/main/res/values/strings.xml
main/src/main/res/values/styles.xml

fix #16313: wherigo: enhance error handling and dialog texts

fix #16313: wherigo: enhance error handling and dialog texts

---

main/AndroidManifest.xml

fix #16327: wherigo activity, anr on jumping back from map, changed launchMode to singleTop

fix #16327: wherigo activity, anr on jumping back from map, changed launchMode to singleTop

---

main/src/main/java/cgeo/geocaching/MainActivity.java
main/src/main/java/cgeo/geocaching/connector/gc/GCLogin.java
main/src/main/res/values/strings.xml

show "manual login" button only if login failed due to captcha
fixes https://github.com/cgeo/cgeo/issues/16331
make GC login errors localizable
fixes https://github.com/cgeo/cgeo/issues/16337

show "manual login" button only if login failed due to captcha

---

main/src/main/java/cgeo/geocaching/MainActivity.java
main/src/main/java/cgeo/geocaching/activity/AbstractNavigationBarActivity.java
main/src/main/java/cgeo/geocaching/activity/CustomMenuEntryActivity.java
main/src/main/java/cgeo/geocaching/enumerations/QuickLaunchItem.java
main/src/main/java/cgeo/geocaching/ui/BadgeManager.java
main/src/main/java/cgeo/geocaching/ui/ViewUtils.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoCartridgeDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoGame.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoInfoBarView.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoUtils.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoViewUtils.java
main/src/main/res/layout/wherigo_info_bar_view.xml
main/src/main/res/values/strings.xml

Wherigo: adjust error handling, badges and wherigo bar

Wherigo: adjust error handling, badges and wherigo bar

---

main/src/main/res/values/styles.xml

fix #16341: set button icon tint to text color

fix #16341: set button icon tint to text color

---

main/src/main/java/cgeo/geocaching/ui/ImageGalleryView.java
main/src/main/java/cgeo/geocaching/ui/SectionHeader.java
main/src/main/res/layout/about_contributors_page.xml
main/src/main/res/layout/about_version_page.xml
main/src/main/res/layout/cachedetail_description_page.xml
main/src/main/res/layout/cachedetail_details_page.xml
main/src/main/res/layout/image_gallery_category.xml
main/src/main/res/layout/imagelist_fragment.xml
main/src/main/res/layout/logcache_activity.xml
main/src/main/res/layout/search_activity.xml
main/src/main/res/layout/section_header.xml
main/src/main/res/layout/trackable_details_view.xml
main/src/main/res/layout/usefulapps_item.xml
main/src/main/res/layout/wherigo_activity.xml
main/src/main/res/values-night/colors_dark.xml
main/src/main/res/values/attrs.xml
main/src/main/res/values/colors_light.xml
main/src/main/res/values/styles.xml

redesign section headlines and unify their style across activities
| ![Screenshot_20241117_170321](https://github.com/user-attachments/assets/74824104-a39e-4a06-9679-872f50800496)  | ![Screenshot_20241117_171824](https://github.com/user-attachments/assets/031433cf-87a0-4b8c-b03b-70a6aa1f22f7)  |
|---|---|
|  ![Screenshot_20241117_170909](https://github.com/user-attachments/assets/c5a05091-d080-43bb-b423-2347fa1efa0b) | ![Screenshot_20241117_171823](https://github.com/user-attachments/assets/807a3e57-7c10-4b7c-bce0-fc7478406106)  |
| ![Screenshot_20241117_172201](https://github.com/user-attachments/assets/646c5565-9e77-41ad-b004-cb37136c85a8)  | ![Screenshot_20241117_171821](https://github.com/user-attachments/assets/28c67ca4-afe8-4073-b9d1-f830b6fe964d)  |

redesign of section separators

---

main/src/main/res/values-night/colors_dark.xml
main/src/main/res/values/colors_light.xml

tweak divider colors

---

main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GeoItemTestLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeV6GeoItemLayer.java

rel to #16307: fix zlevel handling of unifiedmap mapsforge geoitemlayer

rel to #16307: fix zlevel handling of unifiedmap mapsforge geoitemlayer

---

main/src/main/res/drawable/ic_menu_rot13.xml

|old|new|
|---|---|
|![image](https://github.com/user-attachments/assets/4e242807-e182-4578-8071-e85a8938d8f9)|![image](https://github.com/user-attachments/assets/3a0b1f3d-d38f-48fe-ae9a-ca31e48fd28f)|

Fix tint of rot13 icon

---

main/src/main/java/cgeo/geocaching/maps/DefaultMap.java
main/src/main/res/values/strings.xml

Wherigo: display warning when mapping zones and unified map is disabled

Wherigo: display warning when mapping zones and unified map is disabled

---

main/src/main/res/layout-land/unifiedmap_activity.xml
main/src/main/res/layout/unifiedmap_activity.xml
main/src/main/res/layout/unifiedmap_googlemaps_fragment.xml
main/src/main/res/layout/unifiedmap_mapsforge_fragment.xml
main/src/main/res/layout/unifiedmap_mapsforgevtm_fragment.xml

As discussed in the teem meeting...

Add used map implementation name to unified map badge

---

main/src/main/java/cgeo/geocaching/wherigo/WherigoGame.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoLocationProvider.java

fix #16398: wherigo set deviceid and platform

fix #16398: wherigo set deviceid and platform

---

main/src/main/java/cgeo/geocaching/downloader/DownloaderUtils.java

Offer manually downloaded map files in "Manage offline data => Delete offline data" in addition to those downloaded by integrated map downloader.

Delete offline data: List manually downloaded maps (fix #16357)

---

main/src/main/java/cgeo/geocaching/CacheListActivity.java
main/src/main/java/cgeo/geocaching/MainActivity.java
main/src/main/java/cgeo/geocaching/activity/AbstractNavigationBarActivity.java
main/src/main/java/cgeo/geocaching/maps/DefaultMap.java
main/src/main/java/cgeo/geocaching/settings/PreferenceCategory.java
main/src/main/java/cgeo/geocaching/settings/Settings.java
main/src/main/java/cgeo/geocaching/settings/fragments/BasePreferenceFragment.java
main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceAppearanceFragment.java
main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceMapSourcesFragment.java
main/src/main/java/cgeo/geocaching/utils/SystemInformation.java
main/src/main/res/values/preference_keys.xml
main/src/main/res/values/strings.xml
main/src/main/res/xml/preferences_appearence.xml
main/src/main/res/xml/preferences_map_sources.xml

See #16399
Setting WIP for now, as it should not be included in the upcoming beta version/feature release, but only in the one after this (as discussed in our last dev meeting).

Preparations to set Unified map as default

---

main/AndroidManifest.xml
main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
main/src/main/java/cgeo/geocaching/utils/html/HtmlUtils.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoViewUtils.java

Wherigo Player: handle wherigo.com URLs
This PR enables handling of URLs to www.wherigo.com:
* it allows users to let such URLs be handled by c:geo (same as WhereYouGo)
* it replaces links to wherigo.com in cache listings to be handled by internal player

Wherigo Player: handle wherigo.com URLs

---

main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeV6GeoItemLayer.java

See https://github.com/cgeo/cgeo/issues/16430#issuecomment-2543550292

Try to avoid deadlock on layer removal (rel. to #16430)

---

main/src/main/java/cgeo/geocaching/unifiedmap/mapsforge/MapsforgeFragment.java

rel to #16430: move addObserver from onstart to onresume to match removeObserver in onPause

rel to #16430: move addObserver from onstart to onresume to match removeObserver in onPause

---

main/src/androidTest/java/cgeo/geocaching/downloader/DownloaderTest.java
main/src/main/java/cgeo/geocaching/downloader/MapDownloaderOpenAndroMaps.java
main/src/main/java/cgeo/geocaching/downloader/MapDownloaderOpenAndroMapsThemes.java
main/src/main/java/cgeo/geocaching/downloader/MapDownloaderReceiverSchemeMapTheme.java
main/src/main/res/values/strings_not_translatable.xml

- Add support for OAM Elevate_Winter theme in theme downloader
- Get all OAM themes from OAM download server (and simplify code along the way)

Support Elevate Winter theme in map downloader

---

main/src/main/java/cgeo/geocaching/WaypointPopupFragment.java

(fixes an error reported by Play Store stats for current beta 2024.12.17-RC)

Prevent NPE on missing waypoint in waypoint infosheet

---

main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeV6GeoItemLayer.java
main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeV6ZLevelGroupLayer.java

fix #16435: Unified Mapsforge, add zLevel-awareness across layers

fix #16435: Unified Mapsforge, add zLevel-awareness across layers

---

main/src/main/java/cgeo/geocaching/unifiedmap/mapsforge/MapsforgeFragment.java

see https://github.com/cgeo/cgeo/issues/16430#issuecomment-2566522437

UnifiedMap Mapsforge: Try to avoid 'invalid/free'd bitmap' error

---

main/src/main/java/cgeo/geocaching/models/LegacyCalculatedCoordinateMigrator.java

fixes https://github.com/cgeo/cgeo/issues/16471
targeted against release

catch null waypoints in migration

---

main/src/main/java/cgeo/geocaching/maps/MapUtils.java

fixes https://github.com/cgeo/cgeo/issues/16476

fix crash in HS downloader

---

main/src/main/java/cgeo/geocaching/settings/SeekbarPreference.java

fixes https://github.com/cgeo/cgeo/issues/16473
not sure this is the best way to solve it?

don't reuse same seekbar in different holders

---

main/src/main/java/cgeo/geocaching/MainActivity.java
main/src/main/java/cgeo/geocaching/enumerations/QuickLaunchItem.java

Provides checks for conditions that need to be fulfilled for a specific QuickLaunchItem + applies check to quick launch items on home screen

Check conditions for QuickLaunchItems (rel. to #16460)

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java

Recreation of `CacheDetailActivity` happens on screen rotation or switching between apps, all of which ended speech service. This PR restarts speech service in such cases on recreating `CacheDetailActivity`.

Resume speech service after activity restart (fix #14234)

---

main/src/androidTest/java/cgeo/geocaching/filters/GeocacheFilterTest.java
main/src/main/java/cgeo/geocaching/filters/core/GeocacheFilterType.java
main/src/main/java/cgeo/geocaching/filters/core/InventoryCountFilter.java
main/src/main/java/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java
main/src/main/java/cgeo/geocaching/filters/gui/NumberCountFilterViewHolder.java
main/src/main/java/cgeo/geocaching/models/Geocache.java
main/src/main/res/values/strings.xml

Add filter for inventory count
rel #15939

rel #15939: add inventory count filter

---

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

fix #16461: really update geocaches in map cache when changed

fix #16461: really update geocaches in map cache when changed

---

main/src/main/java/cgeo/geocaching/utils/formulas/FormulaUtils.java
main/src/test/java/cgeo/geocaching/utils/formulas/FormulaTest.java
main/src/test/java/cgeo/geocaching/utils/formulas/FormulaUtilsTest.java

fix #16490: handle formula checksum zero

fix #16490: handle formula checksum zero

---

main/src/main/java/cgeo/geocaching/log/LogUtils.java

fix #16494: mark edited logs as friend log

fix #16494: mark edited logs as friend log

---

main/src/main/java/cgeo/geocaching/models/Geocache.java

fix #16505: make storing geocaches working again

fix #16505: make storing geocaches working again

---

main/src/main/java/cgeo/geocaching/unifiedmap/LiveMapDataHandler.java
main/src/main/java/cgeo/geocaching/unifiedmap/LiveMapGeocacheLoader.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapType.java
main/src/main/java/cgeo/geocaching/utils/HideActionBarUtils.java

LIveMap fixes: hide map progressbar correctly, overwrite stored data with live data on map

LIveMap fixes: hide map progressbar correctly, overwrite stored data with live data on map

---

main/src/androidTest/java/cgeo/geocaching/connector/gc/GCConnectorTest.java
main/src/main/res/layout/map_distanceinfo.xml
main/src/main/res/values/strings.xml

fix livemap visuals

---

main/src/main/java/cgeo/geocaching/unifiedmap/AbstractMapFragment.java
main/src/main/java/cgeo/geocaching/unifiedmap/LiveMapDataHandler.java

rel to #16452: quick fix live updates on map panning

rel to #16452: quick fix live updates on map panning

---

main/src/main/java/cgeo/geocaching/SearchResult.java
main/src/main/java/cgeo/geocaching/connector/ec/ECApi.java

rel to #16452: add logging

---

main/src/main/java/cgeo/geocaching/filters/gui/GeocacheFilterActivity.java
main/src/main/java/cgeo/geocaching/utils/FilterUtils.java

correcting a small error - and making some stuff nicer ;-)

better subgroup handling

---

main/src/main/java/cgeo/geocaching/filters/core/GeocacheFilter.java
main/src/main/java/cgeo/geocaching/unifiedmap/AbstractMapFragment.java
main/src/main/java/cgeo/geocaching/unifiedmap/LiveMapDataHandler.java
main/src/main/java/cgeo/geocaching/unifiedmap/LiveMapGeocacheLoader.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

rel to #16499: refactor live map algorithm part 1
This PR should clean up the structures.

rel to #16499: refactor live map algorithm part 1

---

main/src/main/java/cgeo/geocaching/maps/CGeoMap.java
main/src/main/java/cgeo/geocaching/maps/RouteTrackUtils.java
main/src/main/java/cgeo/geocaching/maps/Tracks.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/main/java/cgeo/geocaching/ui/ColorPickerUI.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/ElevationChart.java
main/src/main/res/layout/routes_tracks_item.xml
main/src/main/res/menu/map_routetrack_context.xml

- Offer identical menu entries for
- routes/tracks quick settings
- long tap on track/route in map (UnifiedMap only)
- elevation chart's menu (UnifiedMap only)
- Make elevation chart and other functions available in quick settings
- Remove some duplicated code in this area
See https://github.com/cgeo/cgeo/issues/15707#issuecomment-2573827523 for (updated) screenshots

Unify track/route menus

---

main/src/main/java/cgeo/geocaching/CacheListActivity.java
main/src/main/java/cgeo/geocaching/maps/DefaultMap.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapType.java

Show center indicator for mapping a list which comes from an adress-search / coordinats-search
rel #PR 15794 https://github.com/cgeo/cgeo/pull/15794#issuecomment-2171872478

Show center indicator on mapping list-search with address / coordinates

---

main/src/main/java/cgeo/geocaching/ui/ViewUtils.java
main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsFragment.java

fix #16549: enable google map fragment to defer position setting until map is available

fix #16549: enable google map fragment to defer position setting until map is available

---

main/src/main/java/cgeo/geocaching/SearchResult.java
main/src/main/java/cgeo/geocaching/connector/AmendmentUtils.java
main/src/main/java/cgeo/geocaching/connector/ConnectorFactory.java
main/src/main/java/cgeo/geocaching/location/Viewport.java
main/src/main/java/cgeo/geocaching/settings/Settings.java
main/src/main/java/cgeo/geocaching/unifiedmap/LiveMapDataHandler.java
main/src/main/java/cgeo/geocaching/unifiedmap/LiveMapGeocacheLoader.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapViewModel.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/GeoItemsLayer.java
main/src/main/java/cgeo/geocaching/utils/AndroidRxUtils.java
main/src/main/res/values/preference_keys.xml
main/src/main/res/values/strings.xml
main/src/test/java/cgeo/geocaching/location/ViewportTest.java

fix #16499: enhance live map status info and algorithm

fix #16499: enhance live map status info and algorithm

---

main/src/main/java/cgeo/geocaching/unifiedmap/LiveMapDataHandler.java
main/src/main/java/cgeo/geocaching/unifiedmap/LiveMapGeocacheLoader.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

fix #16565, fix #16566: fix unifiedmap live issues

fix #16565, fix #16566: fix unifiedmap live issues

---

main/src/main/java/cgeo/geocaching/settings/SeekbarPreference.java
main/src/main/java/cgeo/geocaching/ui/ProximityPreferenceUI.java

fix #16553: make seekbarpreference usable again

fix #16553: make seekbarpreference usable again

---

main/src/main/java/cgeo/geocaching/models/Geocache.java
main/src/main/java/cgeo/geocaching/utils/MapMarkerUtils.java

caching of the marker was broken, also adding support for large icon

fixes and improvements to "corrected coords = final coords" marker

---

main/src/main/java/cgeo/geocaching/maps/RouteTrackUtils.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/res/drawable/ic_menu_clear_target.xml
main/src/main/res/drawable/ic_menu_import.xml
main/src/main/res/layout/routes_tracks_dialog.xml
main/src/main/res/menu/cache_list_options.xml
main/src/main/res/menu/map_routetrack_context.xml
main/src/main/res/values/strings.xml

Tweak the routes/tracks bottomsheet and fix some bugs
New:
Comparison old vs new:
Old:
fixes https://github.com/cgeo/cgeo/issues/16561

Routing bottom sheet

---

main/src/main/java/cgeo/geocaching/settings/Settings.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/res/values/preference_keys.xml

fixes https://github.com/cgeo/cgeo/issues/16511

long-tap on map selection to switch to previous map

---

main/src/main/java/cgeo/geocaching/ui/ProximityPreferenceUI.java
main/src/main/res/values/attrs.xml

fix #16578: move highRes attribute into Seekbar XML stylables

fix #16578: move highRes attribute into Seekbar XML stylables

---

main/AndroidManifest.xml
main/src/main/java/cgeo/geocaching/downloader/ReceiveDownload.java

Support opening '.map' files locally (rel. to #16582)

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
main/src/main/java/cgeo/geocaching/CacheListActivity.java
main/src/main/java/cgeo/geocaching/ui/ToggleItemType.java
main/src/main/java/cgeo/geocaching/utils/MenuUtils.java
main/src/main/res/drawable/ic_menu_calendar.xml
main/src/main/res/drawable/ic_menu_dnf.xml
main/src/main/res/drawable/ic_menu_reset_found.xml
main/src/main/res/drawable/ic_menu_textstyle.xml
main/src/main/res/drawable/ic_menu_vote.xml
main/src/main/res/menu/abstract_logging_activity.xml
main/src/main/res/menu/activity_navigationbar_menu.xml
main/src/main/res/menu/cache_list_context.xml
main/src/main/res/menu/cache_list_options.xml
main/src/main/res/menu/cache_options.xml
main/src/main/res/menu/compass_activity_options.xml
main/src/main/res/menu/logging_ui.xml
main/src/main/res/menu/main_activity_options.xml
main/src/main/res/menu/map_activity.xml
main/src/main/res/menu/map_longclick.xml
main/src/main/res/menu/map_mapview.xml
main/src/main/res/menu/map_routetrack_context.xml
main/src/main/res/menu/menu_ok_cancel.xml
main/src/main/res/menu/search_activity_options.xml
main/src/main/res/menu/settings_activity_options.xml
main/src/main/res/menu/trackable_activity.xml
main/src/main/res/menu/view_settings.xml
main/src/main/res/menu/waypoint_options.xml
main/src/main/res/values-night/colors_dark.xml
main/src/main/res/values/colors_light.xml

More menu icons - and a cleanup of our menus

more menu icons

---

main/src/main/java/cgeo/geocaching/CacheListActivity.java
main/src/main/java/cgeo/geocaching/list/StoredList.java
main/src/main/java/cgeo/geocaching/storage/DataStore.java
main/src/main/res/layout/createlist.xml
main/src/main/res/layout/createlist_item.xml
main/src/main/res/menu/cache_list_options.xml
main/src/main/res/values/strings.xml
main/src/main/res/values/styles.xml

Adds a parent list dropdown selector to create list / rename list dialog, if such lists exist:
|Create list 1|Create list 2|Create list 3|
|---|---|---|
|![Screenshot_1737808497](https://github.com/user-attachments/assets/fee801f9-488c-4ece-90c6-96c19ea00a07)|![Screenshot_1737805983](https://github.com/user-attachments/assets/64a264f7-ec93-4c1a-85ad-91ea3a5b864a)|![Screenshot_1737805999](https://github.com/user-attachments/assets/5a3056fe-352f-4231-bdf7-2cfcc4b96e17)
|Rename list with parent lists|Create list without parent lists|Rename lists without parent lists|
|---|---|---|
|![Screenshot_1737807890](https://github.com/user-attachments/assets/158e968e-1d3b-474e-9f5b-7ec22d4cbe8e)|![Screenshot_1737808474](https://github.com/user-attachments/assets/b11666ad-b99a-43b5-a732-4592ed35dfa6)|![ …

Add parent list selector to create/rename list dialogs

---

main/AndroidManifest.xml

see https://github.com/cgeo/cgeo/issues/16582#issuecomment-2614984673

Consolidate local file handling to HandleLocalFilesActivity

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java

Make sure that a cache is stored when editing a cache from map popup

fix missing local save when editing PN from popup

---

main/src/main/java/cgeo/geocaching/ui/ToggleItemType.java
main/src/main/res/values/strings.xml

see https://github.com/cgeo/cgeo/pull/16581#discussion_r1931164225

Fix icons and hints for toggle talking (rel. to #16581)

---

main/src/main/java/cgeo/geocaching/downloader/ReceiveDownload.java

Preserve original file name on importing a local map file

Preserve map file name on local file map import

---

main/src/main/java/cgeo/geocaching/connector/gc/GCMap.java

Cherry-picked and squashed the two relevant commits from #16623 and targeted them to `release`
Closes #16623

Do not pass name field to GC search in this scenario (fix #16607)

---

main/src/main/java/cgeo/geocaching/utils/MenuUtils.java
main/src/main/res/menu/cache_list_options.xml
main/src/main/res/menu/cache_options.xml
main/src/main/res/menu/map_activity.xml
main/src/main/res/menu/map_mapview.xml
main/src/main/res/values/preference_keys.xml

- move menu tinting from xml to java
- mutate drawables before tinting

overflow menu tint tuning

---

main/src/main/java/cgeo/geocaching/ui/ProximityPreferenceUI.java

Rounding of double should be done before subtract and casting to int 
fix PR #12863

Fix small ProximityPreference-value (fix #12863)

---

main/src/main/java/cgeo/geocaching/connector/internal/InternalConnector.java
main/src/main/java/cgeo/geocaching/storage/DataStore.java

Migrate UDC geocodes from ZZ1000-based numbers to random ones. This is a 1-time routine - if after the update a ZZ1000 geocode is imported it'll stay untouched
fixes https://github.com/cgeo/cgeo/issues/16628

migrate UDC geocodes to random ones

---

main/src/main/java/cgeo/geocaching/downloader/CompanionFileUtils.java
main/src/main/java/cgeo/geocaching/downloader/MapDownloaderFreizeitkarte.java
main/src/main/java/cgeo/geocaching/downloader/MapDownloaderOSMPaws.java
main/src/main/java/cgeo/geocaching/downloader/MapDownloaderOpenAndroMaps.java
main/src/main/java/cgeo/geocaching/settings/Settings.java
main/src/main/res/values/preference_keys.xml

See https://github.com/cgeo/cgeo/issues/16586#issuecomment-2631647307 and discussion further down

Downloading maps: Add option to skip auto-renaming

---

main/src/main/java/cgeo/geocaching/utils/xml/XmlUtils.java
main/src/test/java/cgeo/geocaching/utils/xml/XmlNodeTest.java
main/src/test/java/cgeo/geocaching/utils/xml/XmlUtilsTest.java
main/src/test/res/xml/ZUG.IN.ZWEI.TEILEN.gpx

rel to #16616: xmlpullparser: enable parsing of utf8 bom

rel to #16616: xmlpullparser: enable parsing of utf8 bom

---

main/src/main/java/cgeo/geocaching/wherigo/WherigoLocationProvider.java

fix #16624: provide correct altitude to wherigo player

fix #16624: provide correct altitude to wherigo player

---

main/src/main/java/cgeo/geocaching/storage/ContentStorageActivityHelper.java
main/src/main/res/values/strings.xml

fix #16636: show dialog when system cant find a SAF file/folder select component

fix #16636: show dialog when system cant find a SAF file/folder select component

---

main/build.gradle
main/src/main/java/cgeo/geocaching/maps/mapsforge/AbstractMapsforgeMapSource.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/DownloadLayer.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/HillShadingLayerHelper.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/MultiRendererLayer.java
main/src/main/java/cgeo/geocaching/maps/mapsforge/v6/layers/RendererLayer.java

Update Mapsforge dependency on release to current v0.23 to make release branch compilable again

Update Mapsforge to v0.23 (rel. to #16629)

---

main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/TileProviderFactory.java

See https://github.com/cgeo/cgeo/pull/16614#issuecomment-2662286190

Fix missing (VTM) indicator when displayname is set (rel. to #16614)

---

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

If caches get removed from list, don't show them in list-map-view, so remove caches before adding new ones
Hopefully that does not have any performance impact
fix #16022
fix #12737

fix #16022: ReplaceSearchResult instead of add (UnifiedMap)

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
main/src/main/java/cgeo/geocaching/CachePopupFragment.java
main/src/main/java/cgeo/geocaching/models/Geocache.java

Refresh cache-detail-activity after list-assignement via list-activity
fix #8621

fix #8621: update cache lists after list-assignement

---

main/src/main/java/cgeo/geocaching/list/AbstractList.java
main/src/main/java/cgeo/geocaching/list/StoredList.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

When mapping a list and new caches get added to that list, the list count in list-chooser is not updated.
This PR updates the list counter, if changed caches is on the mapped list.

Update number of caches in list-counter of map

---

main/src/main/java/cgeo/geocaching/maps/RouteTrackUtils.java

How to reproduce the issue:
- create individual route
- long-tap on individual route => popup opens
- select "show elevation chart" => leads to crash

Fix NPE on opening elevation chart from map

---

main/src/main/java/cgeo/geocaching/connector/gc/GCLogAPI.java

fix #15878: dont pass favorite flag for add/edit log for basic members

fix #15878: dont pass favorite flag for add/edit log for basic members

---

main/src/main/java/cgeo/geocaching/storage/DataStore.java

fix #16557: add preventAskForListDeletion back to database query

fix #16557: add preventAskForListDeletion back to database query

---

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapViewModel.java
main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsFragment.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforge/MapsforgeFragment.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java

Update status info (# of caches) + update compact icon mode (if necessary) on zoom level changes

Track zoom level changes to update status info (fix #16679)

---

main/src/androidTest/java/cgeo/geocaching/connector/gc/GCParserTest.java
main/src/androidTest/java/cgeo/test/Compare.java
main/src/main/java/cgeo/geocaching/connector/gc/GCConstants.java
main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java
main/src/main/java/cgeo/geocaching/models/Geocache.java
main/src/main/java/cgeo/geocaching/models/Image.java
main/src/main/java/cgeo/geocaching/models/Trackable.java
main/src/main/java/cgeo/geocaching/ui/ImageGalleryView.java
main/src/main/java/cgeo/geocaching/utils/ImageUtils.java
main/src/main/res/values/strings.xml

fix #16662: gc.com, load first 20 images from gallery

fix #16662: gc.com, load first 20 images from gallery

---

main/src/main/java/cgeo/geocaching/SearchActivity.java
main/src/main/res/layout/search_card.xml

fix search by filter #16690

---

main/src/main/java/cgeo/geocaching/ui/dialog/CoordinatesCalculateGlobalDialog.java
main/src/main/java/cgeo/geocaching/utils/formulas/DegreeFormula.java
main/src/main/res/values/strings.xml
main/src/test/java/cgeo/geocaching/utils/formulas/DegreeFormulaTest.java

Adds a tool to replace x with multiplication sign to the plane tools in calculate coordinates
rel #13844 
To discuss:
* naming
* execute the tidy-up after replacing

Calculate Coordinate - Plane Tool: Add tool to replace x with multiplication sign (rel. #13844)

---

main/build.gradle
main/src/main/java/cgeo/geocaching/DBInspectionActivity.java
main/src/main/res/values/strings.xml

- Allow column selection in database search
- Display current search term in header

DBInspection: column filter + display search term

---

main/src/main/java/cgeo/geocaching/utils/MenuUtils.java

fix overflow menu icon color #16619

---

main/src/main/java/cgeo/geocaching/utils/MetadataUtils.java

Catch RuntimeException on metadata-extraction-problems

Catch RuntimeException on metadata-extraction-problems

---

main/src/main/java/cgeo/geocaching/storage/DataStore.java

Add database upgrade path so set adlabs DT rating to zero
PR #16680 
PR #16715 
Fix #16613
Tested on current master with a stored list made before #16715 was pushed and a list created today
This fixes the original issue reported in #16613

Add database update path for lab cache DT rating

---

main/src/main/java/cgeo/geocaching/ui/SearchCardView.java

Fix warning about unresolved theme attributes in `SearchCardView`

Fix theming warning in SearchCardView (fix #16729)

---

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

Alternative approach for #16360

UnifiedMap: Switch to offline mode on long tap (rel. to #16568)

---

main/build.gradle

in Steps.
Step 1: from 2.13.x to 2.14.x
Step 2: from 2.14.x to 2.15.x
Step 2 fails - reverting to step 1.
https://github.com/FasterXML/jackson-core/blob/master/release-notes/VERSION-2.x

jackson update

---

main/src/main/java/cgeo/geocaching/log/LogTemplateProvider.java
main/src/main/res/drawable/ic_menu_more.xml
main/src/main/res/menu/cache_options.xml

Logdate in placeholders

---

main/src/main/java/cgeo/geocaching/wherigo/WherigoUtils.java

Detect wherigo download links that lack leading "www." host name

Detect wherigo links without host name (fix #16775)

---

main/src/main/java/cgeo/geocaching/CacheListActivity.java
main/src/main/res/menu/cache_list_options.xml

Show entry "Remove past events" in all list-activity, when past events are stored in the list.
The entry is only visible, if there are stored past events in the list / selection.
fix #16554

Add "Remove past events" to list "all" (fix #16554)

---

.github/workflows/avd-build-and-cache.yml
.github/workflows/tests.yml
.github/workflows/watchdog.yml

Here are some fixes for the GitHub workflows to run the unit tests.
- I've added the workaround from `reactivecircus/android-emulator-runner@v2` action (`killall -INT crashpad_handler || true`)
- I disabled the parallelism for running on distinct API level as it was causing some tests to fail. Leading to a total running time of 27 min for testing on Android API 26, 29 and 30.
- I set the java version to use at 17 (if you need to test combination of Jave version / Android version it can also be doable, but will add ~7min per case)
- It also includes content from PR #15632.
Repeating the warning here
> [!warning]
> Note that this kind of label based verification is still prone to a race condition in which the attacker may push new changes after the workflow was approved (labeled), but has …

ci: Fix Github workflows

---

.github/workflows/tests.yml

ci: Add step to print env

---

.github/workflows/tests.yml

ci: debug concurrency groups

---

.github/workflows/tests.yml

Should prevent conflicts between workflows from master and PRs

ci: set concurrency groups key for PRs

---

main/src/androidTest/java/cgeo/geocaching/connector/ConnectorFactoryTest.java
main/src/main/java/cgeo/geocaching/connector/oc/OCBaseConnector.java
main/src/main/java/cgeo/geocaching/connector/oc/OCCZConnector.java
main/src/main/java/cgeo/geocaching/connector/oc/OCConnector.java

Splits `OCConnector` in online and offline (`OCBaseConnector`) part and let existing `OCCZConnector` derive from the latter

Switch OC.CZ connector to offline mode

---

main/src/main/java/cgeo/geocaching/connector/su/SuConnector.java

We have updated URLs a bit, old ones are still working and redirect to new ones, but let's use new ones 
directly.

chore: update gc.su URLs

---

.idea/checkstyle-idea.xml
main/build.gradle

Update checkstyle according to codacy

checkstyle 10.21.4

---

main/build.gradle

upgrade jackson to 2.13.x

---

main/proguard-project.txt

Lets test if the rules help against the error #16852.

add jackson proguard rules

---

.github/workflows/tests.yml

- ci: remove stacktrace option to gradlew testDebug
- ci: Add job summary as PR comment on-failure

Add job summary as PR comment on-failure

---

main/build.gradle

Compatibility of version 2.13 is only with MinSdk 24

downgrade jackson to 2.12.x

---

gradle.properties
main/proguard-project.txt

Tests the alternative described in https://github.com/cgeo/cgeo/issues/16867#issuecomment-2817796795

Return Gradle to fullMode on, keep some apache compress things

---

main/src/main/java/cgeo/geocaching/wherigo/WherigoDialogManager.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoThingDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoUtils.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoViewUtils.java

fix #16875: wherigo, allow target selection for thing action

fix #16875: wherigo, allow target selection for thing action

---

main/src/main/java/cgeo/geocaching/ui/dialog/NewCoordinateInputDialog.java
main/src/main/res/layout/new_coordinate_input_dialog.xml

Updates to layout recommended by @murggel in code review
1. Border / padding improved
2. Added degree & minute signs were appropriate
3. Added hints for all fields as per original dialog
Fix 11335 & PR 16799

New Coordinate Entry Dialog - fix layout issues from initial review

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
main/src/main/java/cgeo/geocaching/TrackableActivity.java
main/src/main/java/cgeo/geocaching/utils/OfflineTranslateUtils.java

Avoid automatic translation on refreshing / loading an untranslated listing. 
Translate only, if refresh is necessary. 
fix #16890
Automatic translation of refreshing an already translated listing would be a new / separate issue.

fix #16890: Check, if re-translation should be done

---

main/src/main/java/cgeo/geocaching/wherigo/kahlua/stdlib/BaseLib.java
main/src/main/java/cgeo/geocaching/wherigo/kahlua/vm/LuaState.java
main/src/main/java/cgeo/geocaching/wherigo/kahlua/vm/LuaTable.java
main/src/main/java/cgeo/geocaching/wherigo/kahlua/vm/LuaTableImpl.java
main/src/main/java/cgeo/geocaching/wherigo/openwig/EventTable.java
main/src/main/java/cgeo/geocaching/wherigo/openwig/ZonePoint.java
main/src/test/java/cgeo/geocaching/wherigo/kahlua/vm/LuaTableImplTest.java
main/src/test/java/cgeo/geocaching/wherigo/openwig/EventTableTest.java

Wherigo Kahlua: add debug infos

Wherigo Kahlua: add debug infos

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
main/src/main/java/cgeo/geocaching/TrackableActivity.java
main/src/main/java/cgeo/geocaching/log/LogsViewCreator.java
main/src/main/java/cgeo/geocaching/utils/OfflineTranslateUtils.java

Update the translation-status on abort downloading missing language and reset the progress indicator
rel #16746

Stop progress indicator on cancel downloading missing language

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
main/src/main/java/cgeo/geocaching/TrackableActivity.java
main/src/main/java/cgeo/geocaching/log/LogsViewCreator.java
main/src/main/java/cgeo/geocaching/settings/Settings.java
main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceCachedetailsFragment.java
main/src/main/java/cgeo/geocaching/utils/OfflineTranslateUtils.java
main/src/main/res/values/strings.xml

Add "application language" to selection of translation language

Add "application language" to selection of translation language

---

main/src/main/java/cgeo/geocaching/ui/ExpandableTextView.java
main/src/main/java/cgeo/geocaching/utils/OfflineTranslateUtils.java

Initialize view directly with the correct visibility to avoid flickering
CacheDetailActivity: translation box
LogView: Expand-drawable
rel #16917

Try to avoid flickering on refresh

---

main/src/test/java/cgeo/geocaching/utils/formulas/FormulaFunctionTest.java

Add unit tests to `FormulaFunctionTest` for the following functions: `SQRT`, `SIN`, `COS`, `TAN`, `ABS`, `ROUND`, `TRUNC`, and `LENGTH`
These tests ensure that the `FormulaFunction` class handles edge cases correctly and behaves as expected under various input conditions.

Add test case for FormulaFunction

---

.github/workflows/issue-comment.yml
.github/workflows/tests.yml
.github/workflows/unit-tests-rerun.yml

Implement workflow automatic re-run
#16937

ci: Implement workflow automatic re-run

---

main/src/main/java/cgeo/geocaching/utils/formulas/Formula.java

Add `–` (en dash) and `⋅` (dot operator) as supported subtraction and multiplication sign
fix #16999
| Operation | supported |
|---|---|
|Minus| `—`(em dash) `–` (en dash) |
|Multiply| `•` (Bullet)  `⋅` (dot operator)|
|Division| `/`  `:` `÷`|

(fix #16999) Add more calculation characters (en dash, dot-operator)

---

main/build.gradle
main/src/test/java/cgeo/geocaching/utils/html/HtmlUtilsJunitTest.java

and fix test error.
supersedes #16895

Update jsoup to 1.20.1

---

main/src/main/java/cgeo/geocaching/settings/Settings.java
main/src/main/java/cgeo/geocaching/ui/ExpandableTextView.java
main/src/main/res/values/numbers.xml
main/src/main/res/values/preference_keys.xml
main/src/main/res/values/strings.xml
main/src/main/res/xml/preferences_appearence.xml
main/src/main/res/xml/preferences_cachedetails.xml

Add settings to configure maximum number of lines to be shown for a log
Fix #16818

Fix #16818: Rearrange Appearance and CacheDetail and add settings for log line limit

---

main/src/main/java/cgeo/geocaching/maps/Tracks.java

Add check for some more track functions: Don't call action functions if route is null.

Handle more situations with null track (fix #17026)

---

main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapType.java

keep current caches waypoints visible when enabling live mode

---

main/src/main/java/cgeo/geocaching/ui/TextParam.java
main/src/main/java/cgeo/geocaching/ui/ViewUtils.java
main/src/main/java/cgeo/geocaching/unifiedmap/layers/WherigoLayer.java
main/src/main/java/cgeo/geocaching/utils/TextUtils.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoCartridgeDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoGame.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoThingDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoUtils.java
main/src/main/java/cgeo/geocaching/wherigo/openwig/EventTable.java
main/src/main/java/cgeo/geocaching/wherigo/openwig/Media.java
main/src/main/java/cgeo/geocaching/wherigo/openwig/Zone.java

fix #17025: wherigo: dont display invisible things when called via showscreen

fix #17025: wherigo: dont display invisible things when called via showscreen

---

main/src/main/java/cgeo/geocaching/location/GeopointFormatter.java

Never seen this before: A NPE in Play Store prelaunch report... This PR mitigates that situation.

Prevent Play Store prelaunch report NPE

---

main/build.gradle
main/src/test/java/cgeo/geocaching/utils/html/HtmlUtilsJunitTest.java

build(deps): bump org.jsoup:jsoup from 1.20.1 to 1.21.1 + fix unit tests
Replaces https://github.com/cgeo/cgeo/pull/17078

build(deps): bump org.jsoup:jsoup from 1.20.1 to 1.21.1 + fix unit tests

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
main/src/main/java/cgeo/geocaching/activity/TabbedViewPagerActivity.java
main/src/main/java/cgeo/geocaching/utils/OfflineTranslateUtils.java

try to fix #17040 and #17041: NPEs within OfflineTranslation routines

try to fix #17040 and #17041: NPEs within OfflineTranslation routines

---

main/src/main/java/cgeo/geocaching/utils/EmojiUtils.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoGame.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoThingDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoUtils.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoViewUtils.java

fix #17140: mark wherigo tasks as completed or failed

fix #17140: mark wherigo tasks as completed or failed

---

main/src/main/java/cgeo/geocaching/models/geoitem/GeoItemUtils.java
main/src/main/java/cgeo/geocaching/ui/ViewUtils.java
main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsFragment.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforge/MapsforgeFragment.java
main/src/main/java/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmFragment.java

Some quality of live UX improvements :)
- make small map lines actually clickable
- don't overlap long click popup with long tab location indicator (was only happening if actionbar hiding is disabled)

Unified map UX improvements

---

main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java
main/src/main/res/layout/install_wizard.xml

fixes https://github.com/cgeo/cgeo/issues/17158

install wizard icon size

---

README.md
main/src/main/java/cgeo/geocaching/AboutActivity.java
main/src/main/res/layout/about_version_page.xml
main/src/main/res/values/strings_not_translatable.xml

See https://github.com/cgeo/cgeo/issues/17150#issuecomment-3094470307. If someone wants to keep "twitter", maybe also just for archiving their original name, please raise your hand ;)

remove twitter references from c:geo

---

main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java

adds owners logs to the "friends/own logs" tab. As that tab already has a special meaning in the sense that you scan it for more relevant information imho it's ok to merge them in there - only question is whether we want to rename it.
Unfortunately GC decided to be stupid once again and requires *a different* user token for the showOwnerOnly logs page to load. So this is an additional 2 instead of 1 network requests :-(
fixes https://github.com/cgeo/cgeo/issues/17185

add owners logs to "friends/own logs" tab

---

main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java
main/src/main/java/cgeo/geocaching/ui/ViewUtils.java
main/src/main/res/layout/translationsettings_dialog.xml
main/src/main/res/values/strings.xml

fix lint errors

---

main/src/main/java/cgeo/geocaching/connector/gc/GCConnector.java

Fix OR-condition in `GCConnector::canDeleteLog`: add missing brackets for correct OR-condition
fix #17230

fix #17230: Fix condition for deleting logs

---

main/src/main/java/cgeo/geocaching/CacheListActivity.java
main/src/main/res/values/strings.xml

fix #17210: fix handling of load-more-caches-footers for offline lists

fix #17210: fix handling of load-more-caches-footers for offline lists

---

main/src/main/java/cgeo/geocaching/log/CacheLogsViewCreator.java

fixes https://github.com/cgeo/cgeo/issues/17238

add default constructor

---

main/src/main/java/cgeo/geocaching/network/Network.java

rel to #17164: log HTTP calls which take a long time (as of not that's 5 seconds)

rel to #17164: log HTTP calls which take a long time

---

main/src/main/java/cgeo/geocaching/VariablesViewPageFragment.java
main/src/main/java/cgeo/geocaching/settings/Settings.java
main/src/main/java/cgeo/geocaching/ui/VariableListView.java
main/src/main/java/cgeo/geocaching/utils/formulas/VariableList.java
main/src/main/res/layout/cachedetail_variables_page.xml
main/src/main/res/values/preference_keys.xml
main/src/main/res/values/strings.xml

Option to hide completed variables in variable-tab
Improve time of sorting the variables
fix #13868
=> new PR #17229

fix #13868:  Show only empty variables

---

main/src/androidTest/java/cgeo/geocaching/connector/gc/GCParserTest.java
main/src/main/java/cgeo/geocaching/connector/gc/GCConnector.java
main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java

fixes https://github.com/cgeo/cgeo/issues/17279
- add missing query param to cache listing page
- remove some obsolete parameters that are not interpreted by GC (anymore?)

fix unencrypted hint, remove obsolete query params

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
main/src/main/java/cgeo/geocaching/utils/OfflineTranslateUtils.java
main/src/main/res/values/strings.xml

fix #17280: Offline Translation, display correct messages on unidentified or unsupported source languages

fix #17280: Offline Translation, display correct messages on unidentified or unsupported source languages

---

main/src/main/res/layout/cachedetail_variables_page.xml
main/src/main/res/values/strings.xml

Use new short string for title in variable tab to avoid outdated translations
Add long text as tooltip
PR #17229

Use new short string for title in variable tab to avoid outdated translations

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
main/src/main/res/layout/cachedetail_waypoints_page.xml
main/src/main/res/values/strings.xml

* Use small buttons
* Add name and accuracy to toast for adding current location
* Scroll to added waypoint
* Hide "visited"-chip, if no waypoints are visited
rel #17252

Improve buttons and bevaiour for adding a waypoint

---

main/src/main/java/cgeo/geocaching/connector/gc/GCConstants.java
main/src/main/java/cgeo/geocaching/connector/gc/GCLoggingManager.java
main/src/main/java/cgeo/geocaching/connector/gc/GCParser.java
main/src/main/java/cgeo/geocaching/connector/gc/GCWebAPI.java

fixes https://github.com/cgeo/cgeo/issues/17184

get available TBs from log page instead of separate web call

---

main/src/main/java/cgeo/geocaching/connector/gc/GCLoggingManager.java
main/src/main/java/cgeo/geocaching/utils/offlinetranslate/ITranslateAccessor.java
main/src/main/java/cgeo/geocaching/utils/offlinetranslate/TranslateAccessor.java
main/src/main/java/cgeo/geocaching/utils/offlinetranslate/Translator.java
main/src/main/java/cgeo/geocaching/utils/offlinetranslate/TranslatorUtils.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java
main/src/main/res/layout/cachedetail_waypoints_page.xml
main/src/main/res/layout/wherigo_cartridge_details.xml
main/src/main/res/layout/wherigo_thing_details.xml
main/src/main/res/values/strings.xml

rel to #17276: wherigo: react on disabled translation, move button lower

rel to #17276: wherigo: react on disabled translation, move button lower

---

main/src/main/java/cgeo/geocaching/filters/core/GeocacheFilterContext.java
main/src/main/java/cgeo/geocaching/unifiedmap/LiveMapDataHandler.java
main/src/main/java/cgeo/geocaching/unifiedmap/LiveMapGeocacheLoader.java
main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

rel to #16656: UnifiedMap: apply new filter to live map before filtering existing

rel to #16656: UnifiedMap: apply new filter to live map before filtering existing

---

main/src/main/java/cgeo/geocaching/wherigo/openwig/formats/Savegame.java

fix #17359: Wherigo: redirect deserialization of old classes to new classes

fix #17359: Wherigo: redirect deserialization of old classes to new classes

---

main/src/main/java/cgeo/geocaching/list/AbstractList.java
main/src/main/java/cgeo/geocaching/list/PseudoList.java
main/src/main/java/cgeo/geocaching/list/StoredList.java
main/src/main/res/drawable/ic_menu_import.xml

- dedicated icon for "Create new list" entry when storing a cache
- 
- change the "import" icon from outline to solid to match the style of other icons
-

add icon to "Create new list" pseudolist

---

main/src/main/java/cgeo/geocaching/ImageEditActivity.java
main/src/main/java/cgeo/geocaching/downloader/DownloadSelectorActivity.java
main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java
main/src/main/java/cgeo/geocaching/log/LogTrackableActivity.java
main/src/main/java/cgeo/geocaching/ui/dialog/AbstractFullscreenDialog.java
main/src/main/java/cgeo/geocaching/ui/dialog/EditNoteDialog.java
main/src/main/res/layout-land/compass_activity.xml
main/src/main/res/layout-land/layout_settings.xml
main/src/main/res/layout-land/unifiedmap_activity.xml
main/src/main/res/layout/addresslist_activity.xml
main/src/main/res/layout/authorization_activity.xml
main/src/main/res/layout/authorization_credentials_activity.xml
main/src/main/res/layout/authorization_token_activity.xml
main/src/main/res/layout/cacheslist_activity.xml
main/src/main/res/layout/checkable_item_select_activity.xml
main/src/main/res/layout/compass_activity.xml
main/src/main/res/layout/downloader_activity.xml
main/src/main/res/layout/imageedit_activity.xml
main/src/main/res/layout/imagegallery_activity.xml
main/src/main/res/layout/layout_settings.xml
main/src/main/res/layout/logcache_activity.xml
main/src/main/res/layout/logtrackable_activity.xml
main/src/main/res/layout/map_mapsforge_v6.xml
main/src/main/res/layout/unifiedmap_activity.xml
main/src/main/res/layout/usefulapps_activity.xml

fix #17381: enable many activities and dialogs for edge-2-edge

fix #17381: enable many activities and dialogs for edge-2-edge

---

main/src/main/java/cgeo/geocaching/CacheListActivity.java
main/src/main/java/cgeo/geocaching/SearchActivity.java
main/src/main/java/cgeo/geocaching/activity/AbstractNavigationBarActivity.java
main/src/main/java/cgeo/geocaching/utils/HideActionBarUtils.java
main/src/main/res/layout-h390dp-land/activity_navigationbar.xml
main/src/main/res/layout-land/activity_navigationbar.xml
main/src/main/res/layout/activity_navigationbar.xml
main/src/main/res/layout/filter_sort_bar.xml
main/src/main/res/layout/main_activity.xml
main/src/main/res/layout/search_activity.xml

fix #17396, fix #17395: fix edge-2-edge glitches within map and wherigo status bar

fix #17396, fix #17395: fix edge-2-edge glitches within map and wherigo status bar

---

main/src/main/java/cgeo/geocaching/activity/AbstractActionBarActivity.java
main/src/main/java/cgeo/geocaching/activity/AbstractActivity.java
main/src/main/java/cgeo/geocaching/activity/AbstractNavigationBarActivity.java

fix #17396: Edge-2-Edge, consider navbar hiding and showing changes

fix #17396: Edge-2-Edge, consider navbar hiding and showing changes

---

main/src/main/java/cgeo/geocaching/ui/ImageParam.java
main/src/main/java/cgeo/geocaching/ui/TextParam.java
main/src/main/java/cgeo/geocaching/utils/EmojiUtils.java

SimpleDialog/TextParam: make sure to reset TextViews properly if they are reused eg in Recyclerview

SimpleDialog/TextParam: make sure to reset TextViews properly if they are reused eg in Recyclerview

---

main/src/main/java/cgeo/geocaching/wherigo/IWherigoDialogControl.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoActivity.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoCartridgeDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoDialogManager.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoGame.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoInputDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoPushDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoThingDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoThingType.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoUtils.java
main/src/main/res/layout/wherigo_activity.xml
main/src/main/res/layout/wherigo_cartridge_details.xml
main/src/main/res/layout/wherigo_thing_details.xml
main/src/main/res/menu/wherigo_options.xml

fix #17213: remove Offline Translation Options for Wherigo Player

fix #17213: remove Offline Translation Options for Wherigo Player

---

main/src/main/java/cgeo/geocaching/settings/Settings.java
main/src/main/java/cgeo/geocaching/ui/ImageParam.java
main/src/main/java/cgeo/geocaching/utils/ProcessUtils.java
main/src/main/java/cgeo/geocaching/utils/TranslationUtils.java
main/src/main/res/menu/waypoint_options.xml
main/src/main/res/values/strings.xml

External Translators: refactoring, enabling deepl web fallback and inclusion of icons, fix #17419

External Translators: refactoring, enabling deepl web fallback and inclusion of icons, fix #17419

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
main/src/main/java/cgeo/geocaching/TrackableActivity.java
main/src/main/java/cgeo/geocaching/settings/Settings.java
main/src/main/java/cgeo/geocaching/settings/fragments/PreferenceAppearanceFragment.java
main/src/main/java/cgeo/geocaching/utils/SystemInformation.java
main/src/main/java/cgeo/geocaching/utils/TranslationUtils.java
main/src/main/res/menu/cache_options.xml
main/src/main/res/menu/trackable_activity.xml

External Translator: add to menues, fix None label, add to sysinfo, try to do something for #17437

External Translator: add to menues, fix None label, add to sysinfo, try to do something for #17437

---

main/src/main/java/cgeo/geocaching/settings/Settings.java
main/src/main/java/cgeo/geocaching/utils/TranslationUtils.java
main/src/nofoss/java/cgeo/geocaching/utils/offlinetranslate/MLKitTranslateAccessor.java

External Translator: alternative implementation to PR #17428 for issue #17426 which probably fixes issue #17437
Not to be merged before decision about future of MLKit is completed

External Translator: alternative implementation for #17426 which probably fixes #17437

---

main/src/main/java/cgeo/geocaching/wherigo/IWherigoDialogProvider.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoDialogManager.java
main/src/main/java/cgeo/geocaching/wherigo/WherigoThingDialogProvider.java

fix #17439: Wherigo, allow animations on things done with showDialog

fix #17439: Wherigo, allow animations on things done with showDialog

---

main/src/main/res/layout/wherigo_cartridge_details.xml
main/src/main/res/layout/wherigo_media_view.xml
main/src/main/res/layout/wherigo_thing_details.xml

fix #17496: Wherigo Player, increase details text sizes

fix #17496: Wherigo Player, increase details text sizes

---

main/src/main/res/layout/wherigo_thing_details.xml

fix #17246: wherigo, make input options scrollable

fix #17246: wherigo, make input options scrollable

---

main/src/androidTest/java/cgeo/geocaching/downloader/DownloaderTest.java

fix brouter test

---

main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
main/src/main/java/cgeo/geocaching/SearchActivity.java
main/src/main/java/cgeo/geocaching/filters/gui/DistanceFilterViewHolder.java
main/src/main/java/cgeo/geocaching/log/LogTrackableActivity.java
main/src/main/java/cgeo/geocaching/ui/dialog/CoordinateInputDialog.java
main/src/main/java/cgeo/geocaching/ui/dialog/CoordinatesCalculateGlobalDialog.java

Set as much coordinate input data as possible in CoordinateInputDialog
fix #17503

fix #17503: Set geocode to get prefilled variable-list for edit waypoint 
