main/res/values-ca/strings.xml, main/res/values-cs/strings.xml, main/res/values-da/strings.xml, main/res/values-de/strings.xml, main/res/values-es/strings.xml, main/res/values-fr/strings.xml, main/res/values-hu/strings.xml, main/res/values-it/strings.xml, main/res/values-ja/strings.xml, main/res/values-lt/strings.xml, main/res/values-lv/strings.xml, main/res/values-nb/strings.xml, main/res/values-nl/strings.xml, main/res/values-pl/strings.xml, main/res/values-pt/strings.xml, main/res/values-ro/strings.xml, main/res/values-sk/strings.xml, main/res/values-sl/strings.xml, main/res/values-sv/strings.xml
downloaded 2015-01-03 13:50:38
=> crowdin: New translations

main/src/cgeo/geocaching/StaticMapsProvider.java
Just a small change to better fit preview image so it becomes larger.
Zoom level is still 15 - to be checked.
=> fixes #4072 -larger preview for larger display

main/src/cgeo/geocaching/AboutActivity.java
Added HW-accel. info in system information; also shows default value
=> [Systeminformation] Related to #4649

main/src/cgeo/geocaching/connector/trackable/AbstractTrackableLoggingManager.java, main/src/cgeo/geocaching/connector/trackable/GeokretyLoggingManager.java, main/src/cgeo/geocaching/connector/trackable/TrackableLoggingManager.java, main/src/cgeo/geocaching/connector/trackable/TravelBugLoggingManager.java
Make the AbstractTrackableLoggingManager's functions abstract.
Implement mising functions in TravelBugLoggingManager.
Removed unused hasLoaderError function.
=> fix #4788: problems logging TB with newest NBs

main/src/cgeo/geocaching/CacheDetailActivity.java, main/src/cgeo/geocaching/Trackable.java, tests/src/cgeo/geocaching/TrackableTest.java
Create a new getUniqueID() function.
Add unit test.
=> fix #4780: Wrong GC TB inventory

main/res/layout/logtrackable_activity.xml
=> fix #4786: Coordinate field in GK logging has no preset

main/src/cgeo/geocaching/connector/trackable/GeokretyConnector.java, main/src/cgeo/geocaching/connector/trackable/GeokretyLoggingManager.java, main/src/cgeo/geocaching/settings/Settings.java
List of supported locales: http://geokrety.org/rzeczy/lang/
Remove braces in toast messages
=> fix #4784: String not localized

tests/src/cgeo/geocaching/test/mock/GC1ZXX2.java, tests/src/cgeo/geocaching/test/mock/GC2CJPF.java, tests/src/cgeo/geocaching/test/mock/GC2JVEH.java, tests/src/cgeo/geocaching/test/mock/GC3XX5J.java
=> Add missing annotations on overriden methods

main/src/cgeo/geocaching/LogEntry.java, main/src/cgeo/geocaching/settings/Settings.java, tests/src/cgeo/geocaching/LogEntryTest.java
While working on #4911, I've found that LogEntry has no unit tests.
I wrote JavaDoc and some unit tests...
=> Add JavaDoc and unit tests to LogEntry class

main/src/cgeo/geocaching/CacheDetailActivity.java, main/src/cgeo/geocaching/DataStore.java, main/src/cgeo/geocaching/Geocache.java, main/src/cgeo/geocaching/LogEntry.java, main/src/cgeo/geocaching/Trackable.java, main/src/cgeo/geocaching/connector/gc/GCParser.java, main/src/cgeo/geocaching/connector/oc/OkapiClient.java, main/src/cgeo/geocaching/files/GPXParser.java, tests/src/cgeo/geocaching/GeocacheTest.java, tests/src/cgeo/geocaching/LogEntryTest.java, tests/src/cgeo/geocaching/TrackableTest.java
Create new functions for easy merging trackables.
* addInventoryItem()
* mergeInventory()
Use new function where appropriated.
=> Fix #4911: Cache inventory should be smarter ;)

.idea/modules.xml, build.gradle, gradle/wrapper/gradle-wrapper.properties, main/build.gradle, main/cgeo.iml, nine-old-androids/nine-old-androids.iml, undobar/undobar.iml
=> Fix #4931: Project fail to build on Idea since inclusion of undobar

main/src/cgeo/geocaching/CacheDetailActivity.java, main/src/cgeo/geocaching/Geocache.java, main/src/cgeo/geocaching/connector/gc/GCParser.java, main/src/cgeo/geocaching/connector/oc/OkapiClient.java, tests/src/cgeo/geocaching/GeocacheTest.java
Unit tests passed.
Do you imagine other test case?
=> Fix #4987: Trackables might not be removed from a cache on refresh

main/res/values/strings.xml, main/res/xml/preferences.xml
Added summaries for the rest of the menu items in Settings
=> Add summaries in Settings - Services menus fixes #4545

main/res/values/strings_not_translatable.xml, main/src/cgeo/geocaching/network/StatusUpdater.java
Only to be merged after new website is live.
=> DO NOT YET MERGE - Fix #4954 - New FAQ links

main/AndroidManifest.xml
Experimental change to test if it has any advantage/disadvantage on memory intense scenarios in c:geo.
Could someone check if the syntax is OK or reply if anyone does see a problem with it?
I will test and provide feedback based on the nightlies so we can decide to keep or revert.
=> Fix #5038 - Request large heap

main/AndroidManifest.xml, main/res/values/changelog_release.xml
=> Fix #5038 - Large heap size

main/res/values/strings.xml
This will also reset strings and enforce new translations on Crowdin
=> Fix #4950 - Better wording for send2cgeo import

main/res/values/preference_keys.xml, main/res/xml/preferences.xml, main/src/cgeo/geocaching/gcvote/GCVote.java, main/src/cgeo/geocaching/settings/CheckGCVoteCredentialsPreference.java, main/src/cgeo/geocaching/settings/SettingsActivity.java
Apologies for the delayed response. Check login feature is added for the issue #4607. Please verify the modified files and let me know for any changes.
Thanks
Madan
=> Check login feature is added for GCVote in settings

main/src/cgeo/geocaching/connector/oc/OCApiLiveConnector.java, main/src/cgeo/geocaching/connector/oc/OkapiClient.java, main/src/cgeo/geocaching/connector/oc/OkapiService.java
Allow upload of personal note to OC server #4873 is fixed. Please review my code and share your suggestions.
=> Upload Personal note for opencaching (Fixes the issue #4873)

main/src/cgeo/geocaching/CacheListActivity.java
Save the current list type between activity changes.
=> Fix #4969: Inconsistencies between lists

main/src/cgeo/geocaching/CompassActivity.java, main/src/cgeo/geocaching/DataStore.java, main/src/cgeo/geocaching/Geocache.java, main/src/cgeo/geocaching/Image.java, main/src/cgeo/geocaching/ImageSelectActivity.java, main/src/cgeo/geocaching/Intents.java, main/src/cgeo/geocaching/LogCacheActivity.java, main/src/cgeo/geocaching/Trackable.java, main/src/cgeo/geocaching/connector/ILoggingManager.java, main/src/cgeo/geocaching/connector/NoLoggingManager.java, main/src/cgeo/geocaching/connector/ec/ECLoggingManager.java, main/src/cgeo/geocaching/connector/gc/GCLoggingManager.java, main/src/cgeo/geocaching/connector/gc/GCParser.java, main/src/cgeo/geocaching/connector/oc/OkapiClient.java, main/src/cgeo/geocaching/connector/oc/OkapiLoggingManager.java, main/src/cgeo/geocaching/connector/trackable/AbstractTrackableLoggingManager.java, main/src/cgeo/geocaching/connector/trackable/GeokretyLoggingManager.java, main/src/cgeo/geocaching/connector/trackable/TrackableLoggingManager.java, main/src/cgeo/geocaching/connector/trackable/TravelBugLoggingManager.java, main/src/cgeo/geocaching/utils/ImageUtils.java, tests/src/cgeo/geocaching/ImageTest.java
Do you agree with such update?
=> Refactor: use Image class instead of local variables.

main/res/values/preference_keys.xml, main/res/values/strings.xml, main/res/xml/preferences.xml, main/src/cgeo/geocaching/apps/navi/GoogleNavigationApp.java, main/src/cgeo/geocaching/apps/navi/NavigationAppFactory.java
This is more like a feature request, as I didn't manage to setup eclipse properly to build this thing. Can someone with a proper setup have a look?
I want to add another entry in the navigation menu that opens google maps finding a route with public transport. It should be rather straight forward I think.
Another question: How are translations managed? Do I need to add an entry for each language?
Thanks!
=> navigation: add entry for google maps transit mode

main/src/cgeo/geocaching/ui/CacheListAdapter.java, main/src/cgeo/geocaching/utils/MapUtils.java
- remove superfluous code from CacheListAdapter
- create new insets and adapt inset handling to accomodate list and map
=> Fixes #5195, Bad overlay sizing

main/src/cgeo/geocaching/DataStore.java, main/src/cgeo/geocaching/connector/gc/GCParser.java
this adds the description from log Images
=> fix issue #5228: add log image description

main/res/layout/coordinatesinput_dialog.xml, main/res/layout/coords_input_title.xml, main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java
issue #5196: done button is now on top of the coord's input dialog and removed from bottom end. also added cancel button next to done button
=> Issue #5196

main/res/layout/logcache_activity.xml, main/res/values/strings.xml, main/src/cgeo/geocaching/LogCacheActivity.java, main/src/cgeo/geocaching/connector/AbstractConnector.java, main/src/cgeo/geocaching/connector/AbstractLoggingManager.java, main/src/cgeo/geocaching/connector/IConnector.java, main/src/cgeo/geocaching/connector/ILoggingManager.java, main/src/cgeo/geocaching/connector/gc/GCConnector.java, main/src/cgeo/geocaching/connector/gc/GCConstants.java, main/src/cgeo/geocaching/connector/gc/GCLoggingManager.java, main/src/cgeo/geocaching/connector/gc/GCParser.java
Fix for the issue "Allow adding favpoint in logging activity #4347". Please review and share your thought.
=> Add to favorite list check in log visit (Fixes #4347)

main/res/values/strings.xml, main/src/cgeo/geocaching/CacheDetailActivity.java, main/src/cgeo/geocaching/DataStore.java, main/src/cgeo/geocaching/Geocache.java, main/src/cgeo/geocaching/connector/gc/GCConstants.java, main/src/cgeo/geocaching/connector/gc/GCParser.java
In CacheDetailActivity you can now see "Cache is not on your watchlist (6 in total)" or "Cache is on your watchlist (7 in total)".
=> Show the number of people having a cache on watchlist (Fix Issue #4058)

main/res/values/strings.xml, main/src/cgeo/calendar/CalendarAddon.java, main/src/cgeo/geocaching/models/Geocache.java, tests/src-android/cgeo/geocaching/models/GeocacheTest.java
Asks the user if a cache event in the past should
be added to the calendar.
=> close #5172: Ask if past event should be added

main/src/cgeo/geocaching/connector/gc/GCLoggingManager.java
Code fix for the issue "Amount of favorite points not updated when awarding a favorite point in logging view #5264".
=> Bug fix for the issue #5264

README.md
Update prerequisites to current gradle build.
=> README: Update prerequisites.

cgeo-calendar/cgeo-calendar.iml, cgeo-contacts/cgeo-contacts.iml, main/main.iml, mapswithme-api/mapswithme-api.iml, showcaseview/showcaseview.iml
I started to use IntelliJ as well, but the current settings seem not to be aligned with the current project.
As I am not really experienced with IntelliJ, I'd like someone to cross-check that these are correct and don't create issues.
=> Update IntelliJ settings

.idea/runConfigurations/cgeo___tests.xml
The default configuration for Idea doesn't include cgeo unit tests.
=> Intellij Idea include android test configuration

main/res/values/strings.xml, main/src/cgeo/geocaching/CacheDetailActivity.java
Evaluating return value from Connector uploadPersonalNote to present correct message.
=> Fixed #5339 no feedback no personal note upload

main/res/layout/pocketquery_item.xml, main/src/cgeo/geocaching/connector/gc/PocketQueryListAdapter.java
I'm not an expert in UI design, but I wanted to give it a try.
What do you think about this design change? Now they are 'real' buttons and the options should be more clear to the user.
=> fix #5415: PQ import dialog not intuitive

main/src/cgeo/geocaching/files/ProgressInputStream.java, main/src/cgeo/geocaching/playservices/LocationProvider.java, main/src/cgeo/geocaching/search/SuggestionProvider.java, main/src/cgeo/geocaching/ui/EditNoteDialog.java, main/src/cgeo/geocaching/ui/dialog/DateDialog.java, main/src/cgeo/geocaching/ui/dialog/TimeDialog.java, main/src/cgeo/geocaching/utils/LeastRecentlyUsedSet.java, main/thirdparty/menion/android/locus/LocusDataStorageProvider.java
I only replaced org.eclipse.jdt.annotation.NonNull with android.support.annotation.NonNull if the superclasses already have an android.support.annotation.NonNull annotation, but maybe it's a good idea to replace them all?!  I can adapt the patches in such a way, if desired.
=> Fixed some issues related to @NonNull

main/src/cgeo/geocaching/ui/AnchorAwareLinkMovementMethod.java
=> fix #5516: LinkMovementMethod needs to be aritrary selectable

main/src/cgeo/geocaching/connector/AbstractConnector.java, main/src/cgeo/geocaching/connector/GeocachingAustraliaConnector.java, main/src/cgeo/geocaching/connector/GeocachingSuConnector.java, main/src/cgeo/geocaching/connector/IConnector.java, main/src/cgeo/geocaching/connector/trackable/AbstractTrackableConnector.java, main/src/cgeo/geocaching/connector/trackable/GeokretyConnector.java, main/src/cgeo/geocaching/connector/trackable/GeolutinsConnector.java, main/src/cgeo/geocaching/connector/trackable/TrackableConnector.java, main/src/cgeo/geocaching/connector/trackable/TravelBugConnector.java, main/src/cgeo/geocaching/connector/trackable/UnknownTrackableConnector.java, tests/src-android/cgeo/watchdog/WatchdogTest.java
Do checks using the connector general scheme usage.
Support proxy checks like GK/GKM
=> Refactor website connectors tests

main/src/cgeo/geocaching/CacheDetailActivity.java, main/src/cgeo/geocaching/models/Geocache.java, tests/src-android/cgeo/geocaching/CgeoApplicationTest.java
Geocache.searchByGeocode() didn't recognize already cached Geocache correctly.
=> fix #5541: don't reload after adding to list

main/project/rawimages/ic_menu_pocket_query.svg
=> added ic_menu_pocket_query svg rawimage

main/src/cgeo/geocaching/maps/CachesOverlay.java
See https://www.geocaching.com/about/guidelines.aspx.
=> Use precise minimum cache distance.

main/res/layout/cachedetail_description_page.xml, main/res/values/preference_keys.xml, main/res/values/strings.xml, main/res/xml/preferences.xml, main/src/cgeo/geocaching/CacheDetailActivity.java, main/src/cgeo/geocaching/settings/Settings.java
Long description systematically displayed.
=> Please test (#5462)

main/src/cgeo/geocaching/settings/AbstractClickablePreference.java, main/src/cgeo/geocaching/settings/CredentialsPreference.java, main/src/cgeo/geocaching/settings/OAuthPreference.java, main/src/cgeo/geocaching/settings/RegisterSend2CgeoPreference.java, main/src/cgeo/geocaching/settings/TokenPreference.java
Reverts cgeo/cgeo#5609
```
cgeo.geocaching E/AndroidRuntime: FATAL EXCEPTION: main
Process: cgeo.geocaching, PID: 24379
java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.settings.SettingsActivity}: android.view.InflateException: Binary XML file line #30: Error inflating class cgeo.geocaching.settings.CredentialsPreference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
at android.app.ActivityThread.access$900(ActivityThread.java:154)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at …
```
=> Revert "Use more specific parameter type to avoid casts"

main/res/menu/images_list_context.xml, main/src/cgeo/geocaching/ui/ImagesList.java
Added the Navigation menu entry to the image context menu on long click.
=> fix #5542: exif target navigation to picture context menu

main/src/cgeo/geocaching/storage/DataStore.java
This is not a complete fix, but should reduce the performance issues of #5536 .
I replaced the N-Selects of the `dbTableCachesLists` Table with one select with a `where in` clause.
Now the main remaining performance issue is `loadSpoilers()`.
=> an interim solution for #5536

main/src/cgeo/geocaching/CgeoApplication.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cgeo/cgeo/5635)
=> Useless comment fix

build.gradle, main/build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cgeo/cgeo/5597)
=> Upgrade build tools and android support annotations

main/src/cgeo/geocaching/utils/HtmlUtils.java
The commits should not change the behaviour of the method. However, I'm not convinced that the method behaves like expected (independent of my changes), e.g. it does not remove the tags for "<span><span>...</span></span>". Maybe some unit tests would be helpful?
=> Remove tags

main/res/values/strings.xml, main/src/cgeo/geocaching/settings/RegisterSend2CgeoPreference.java
How this string change should be handled? @rsudev the crowdin strings be should be uploaded then updated in master soon after merging this, isn't it?
=> Fix #5650: Send2cgeo PIN not showing up

main/src/cgeo/geocaching/storage/DataStore.java
See http://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html
for details.
=> Fix double-checked locking in init() method.

main/project/attributes_okapi/attribute-definitions.xml, main/src/cgeo/geocaching/connector/gc/GCMap.java
I also handled five other occurrences on crowdin.
=> Fix typo: whereigo -> wherigo

main/src/cgeo/geocaching/connector/trackable/TrackableConnector.java, main/src/cgeo/geocaching/network/Network.java
A small rebase exercise for @Bananeweizen ;-)
=> Fix typos in comments

main/src/cgeo/geocaching/connector/trackable/TravelBugConnector.java
- add five digit numbers to pattern for travelbug connector
Please review if this is a good idea or you rather think not.
=> Fix #5765, Numeric trackable secret code or five digit code not working

main/src/cgeo/geocaching/models/LogEntry.java, main/src/cgeo/geocaching/storage/DataStore.java, tests/src-android/cgeo/geocaching/models/LogEntryTest.java
I have two failing tests locally. As far as I remember they got fixed on `master` with other commits, but unrelated to this change.
=> cherry-pick #5562 for release

main/src/cgeo/geocaching/CacheListActivity.java, main/src/cgeo/geocaching/models/Geocache.java
moved the assignment of the (new) lists into the store method
=> fix #5760 wrong marker when canceling store

tests/src-android/cgeo/geocaching/test/mock/GC3XX5J.java, tests/src/cgeo/geocaching/test/mock/GC3XX5J.html
=> Fix #5868: Adapt unit tests

main/res/values/strings.xml
The explained functions are no longer new, therefore I slightly changed the content.
=> New strings for showcase

main/res/layout/cachedetail_details_page.xml, main/res/layout/popup.xml, main/src/cgeo/geocaching/CacheDetailActivity.java
Changed the arrangement of the list buttons (offline box) as proposed in #5893
=> fix #5893 arrangement of list buttons

main/src/cgeo/geocaching/settings/SettingsActivity.java
I've pushed a branch on upstream with a (possible) fix for this problem.
Let's merge on master, then on release if wanted.
=> Fix #5910: IAE: credentials are not valid

main/src/cgeo/geocaching/CachePopupFragment.java
- Guard updating of popup ui against the opup being dismissed already
=> Fix #5913, ISE: Fatal Exception thrown on Scheduler.Worker thread

main/src/cgeo/geocaching/maps/mapsforge/v6/caches/GeoitemLayers.java
- Make access to GeoitemLayers synchronized
While this should fix the reported issue (I was not able to reproduce it myself, but it clearly can happen) I wanted opinions from others on the approach and would also like to suggest a beta phase for it.
=> Fix #5907, Concurrent modification exception in new map

cgeo-calendar/AndroidManifest.xml, cgeo-calendar/build.gradle, cgeo-contacts/AndroidManifest.xml, cgeo-contacts/build.gradle, main/AndroidManifest.xml, main/build.gradle
Also, the SDK used for compiling is now 23.
=> Update target SDK version to 22

main/src/cgeo/geocaching/storage/DataStore.java
Ups, that were really a lot. I hope you have good eyes.
=> All SQL keywords to upper case

main/src/cgeo/geocaching/MainActivity.java, main/src/cgeo/geocaching/maps/AbstractMap.java, main/src/cgeo/geocaching/maps/DirectionDrawer.java, main/src/cgeo/geocaching/maps/brouter/BRouter.java, main/src/cgeo/geocaching/maps/brouter/BRouterServiceConnection.java, main/src/main/aidl/btools/routingapp/IBRouterService.aidl
BRouter integration for routing to waypoints (see #5958)
=> BRouter integration

main/src/cgeo/geocaching/apps/AbstractLocusApp.java
Small pull request to test rebase strategy.
=> Extend mapping to Locus cache types

main/res/values/strings.xml, main/src/cgeo/geocaching/export/PersonalnoteExport.java
Please give my attempt a short cross-check
=> Pluralize personal note upload message

main/res/values/strings.xml, main/src/cgeo/geocaching/maps/CachesOverlay.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
Catch errors requesting popup details and inform user in a toast
=> Fix #5948, Live map crashing

main/src/cgeo/geocaching/connector/gc/GCConstants.java
Updated the pattern to recognize the successful upload of log pictures.
Due to `Regression` I opened the PR against `release` branch, right?
=> fix #6024 recognize log picture upload success

tests/src-android/cgeo/geocaching/connector/gc/GCLoginTest.java
=> Add a test to confirm that the home location contains valid coordinates

main/res/layout/editwaypoint_activity.xml, main/src/cgeo/geocaching/EditWaypointActivity.java
Just removed the type checking.
=> Fix #6043, Support user modified coords for all cache types

main/src/cgeo/geocaching/connector/gc/GCLogin.java
Now this is the fix for branch `master`. Here only a proper fallback needed to be set.
As the PR for `release` can't be merged without conflicts to `master`, I was not sure what the proper way is. So I've sent a separate PR for `master`.
If you prefer I can also do a manual merge from `release` to `master` after the other PR is merged into `release`. Then I close this one.
=> fix #6065 no logs when gc custom date not detected

main/res/values/strings.xml
Noticed this when out caching today - this does not come across as fluent English.
=> Make "some seconds" more natural english

tests/src-android/cgeo/geocaching/CgeoApplicationTest.java, tests/src-android/cgeo/geocaching/connector/gc/GCBaseTest.java, tests/src-android/cgeo/geocaching/connector/gc/GCConstantsTest.java, tests/src-android/cgeo/geocaching/test/mock/GC3FJ5F.java, tests/src-android/cgeo/geocaching/test/mock/MockedCache.java, tests/src-android/cgeo/geocaching/utils/TextUtilsTest.java, tests/src/cgeo/geocaching/test/mock/GC3FJ5F.html
Using GC3FJ5F as a replacement for GC2JPF for some tests, because the latter has been archived.
=> fix #6095 GC2CJPF archived causing tests to fail

main/res/values/preference_keys.xml, main/src/cgeo/geocaching/list/StoredList.java, main/src/cgeo/geocaching/settings/Settings.java
Remembering the selected lists for the multi list selection dialog. I've decided to remember the selection in the Settings, similar to last used list.
=> fix #5975 remember last list selection

main/src/cgeo/geocaching/staticmaps/StaticMapsActivity.java
Also, do not block on UI thread.
=> fix #6111: manipulate UI elements on UI thread only

main/build.gradle, main/src/cgeo/geocaching/ui/CompassView.java
RxAndroid issue has been fixed.
=> fix #6087: crash on start of compass

README.md
Hello c:geo collaborateurs!
This is some complementary instructions for eclipse.
Please, let me know what you think about them!
/Anders
=> Adding some details to the installation instructions for eclipse.

main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapSource.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/cgeo/geocaching/maps/mapsforge/v6/layers/DownloadLayer.java, main/src/cgeo/geocaching/maps/mapsforge/v6/layers/ITileLayer.java, main/src/cgeo/geocaching/maps/mapsforge/v6/layers/RendererLayer.java
=> Online tiles 1st version

README.md
Original pull request that was mistakenly submitted for merge against release:
https://github.com/cgeo/cgeo/pull/6120
=> Information about ceased support for eclipse.

main/res/menu/map_activity.xml, main/res/values/strings.xml, main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/cgeo/geocaching/maps/routing/Routing.java, main/src/cgeo/geocaching/maps/routing/RoutingMode.java
- added item 'Straight line' to routing menu
=> Fix #6154, BRouter: UI implementation suggestion

main/src/cgeo/geocaching/connector/gc/IconDecoder.java
Temporary fix. Detection is less detailed, I'll provide better detection in few days.
=> New IconDecoder #6175

main/src/cgeo/geocaching/log/LogCacheActivity.java, main/src/cgeo/geocaching/log/LoggingUI.java, main/src/cgeo/geocaching/models/Geocache.java, main/src/cgeo/geocaching/storage/DataStore.java
- fix History count
- fix online Logs not visible in History
- fix "clearOfflineLogs" cleared also all visited
=> fixes #6181 history not working reliably

main/src/cgeo/geocaching/storage/DataStore.java
=> fixes #6185 list count for non detailed caches

main/src/cgeo/geocaching/CacheListActivity.java, main/src/cgeo/geocaching/storage/DataStore.java
=> fixes #5949 delete caches from history and search

main/src/cgeo/geocaching/connector/gc/IconDecoder.java
I have added retina icons. This new parser shall parse both versions
=> New retina icons on map

main/src/cgeo/geocaching/maps/CachesOverlay.java
Make the lock protecting against concurrent
modification of the caches list also guard the
super method.
=> Fix #4611, ArrayIndexOutOfBoundsException on map

main/src/cgeo/geocaching/CacheListActivity.java, main/src/cgeo/geocaching/log/LogCacheActivity.java, main/src/cgeo/geocaching/log/LoggingUI.java, main/src/cgeo/geocaching/models/Geocache.java, main/src/cgeo/geocaching/storage/DataStore.java
Work in progress, do not merge yet.
Changes as discussed in #6186:
1) clearOfflineLogs (not resetting visiteddate)
2) clearHistory (including offline logs)
3) remove (delete cache including offline log and visiteddate)
=> fix #6186 history

main/src/cgeo/geocaching/settings/CredentialsPreference.java
=> Clear cookies when revoking an authorization

main/res/menu/details_context.xml, main/res/values/strings.xml, main/src/cgeo/geocaching/CacheDetailActivity.java, main/src/cgeo/geocaching/TrackableActivity.java, main/src/cgeo/geocaching/activity/AbstractActivity.java, main/src/cgeo/geocaching/models/Geocache.java
Added an item to the text selection context menu. It looks like this:
=> fix #1249 extract waypoints from cache description

main/src/cgeo/geocaching/Intents.java, main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/MapOptions.java, main/src/cgeo/geocaching/maps/MapState.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/cgeo/geocaching/maps/mapsforge/v6/caches/CachesBundle.java
Implemented the same semantics as previously for the live map
=> Fix #5929, Live caches vanish when disabling updates

main/src/cgeo/geocaching/connector/AbstractConnector.java
Add new copy to clipboard option user action in Abstract Connector.
=> Fix issue #6359 - Add new copy to clipboard option user action

main/src/cgeo/geocaching/location/GeopointFormatter.java, tests/src/cgeo/geocaching/location/GeoPointFormatterTest.java
Replaces localized decimal comma with english decimal point.
=> fix #6368 export coords in raw format

main/src/cgeo/geocaching/activity/OAuthAuthorizationActivity.java, main/src/cgeo/geocaching/connector/gc/GCConstants.java, main/src/cgeo/geocaching/connector/gc/GCParser.java, main/src/cgeo/geocaching/connector/trackable/GeolutinsConnector.java, main/src/cgeo/geocaching/files/GPXParser.java
groupCount() depends on the pattern, but not on the match.
Thus, we know the result in advance in most cases.
Also removed some superfluous capturing groups.
=> Simplify handling of some regular expressions

main/res/xml/preferences.xml, main/src/cgeo/geocaching/settings/SettingsActivity.java
Similar to Settings - Navigation - "Standardnavigation"
=> fix #6425 improved Settings design for geocache data option

main/src/cgeo/geocaching/activity/Progress.java, main/src/cgeo/geocaching/settings/SettingsActivity.java, main/src/cgeo/geocaching/storage/LocalStorage.java
Added a progress dialog with percentage while moving the geocache data.
There are some additional ideas from @Lineflyer in https://github.com/cgeo/cgeo/issues/6426#issuecomment-288357770 (warning dialog and disk full handling), they are not included here.
=> fix #6426 add percentage progress dialog while moving geocache data

main/build.gradle, main/res/values/changelog_master.xml, main/src/cgeo/geocaching/location/Geopoint.java, main/src/cgeo/geocaching/speech/TextFactory.java
GeographicLib is released under the MIT/X11 License.
Fix #6123.
=> Use GeographicLib to compute distance, azimuth and projections

main/res/values/preference_keys.xml, main/res/values/strings.xml, main/res/xml/preferences.xml, main/src/cgeo/geocaching/settings/SettingsActivity.java, main/src/cgeo/geocaching/utils/FileUtils.java, main/src/cgeo/geocaching/utils/Formatter.java
- calculate size of geocache data directory
- show a list of available mount points with available space
- add a confirmation dialog prior performing the move
=> fix #6456 handling of disk space when moving data dir

main/res/values/strings_not_translatable.xml
...at least into "About c:geo" for now
=> Work on #6150 - Add attribution for OSM

README.md
It's a small thing, but still needs fixing ;-)
=> Fix Build Status Badge in README.md

main/res/values/strings.xml
The PR originates from https://github.com/cgeo/cgeo/pull/6540#discussion_r115148535. Feel free to prove me wrong.
=> Add missing definite articles

main/src/cgeo/geocaching/storage/LocalStorage.java, main/src/cgeo/geocaching/utils/FileUtils.java
I fixed a possible npe in FileUtils, too. Hope it's ok.
=> fix #6554 npe in localstorage

main/res/menu/cache_list_options.xml, main/res/values/strings.xml, main/src/cgeo/geocaching/CacheListActivity.java
- new menu structure of the cache list menu
- hides empty caches sub menu if there are no caches in the list
=> issue-6546: changes the cache list menu structure

main/src/cgeo/geocaching/CacheDetailActivity.java, main/src/cgeo/geocaching/connector/capability/PersonalNoteCapability.java, main/src/cgeo/geocaching/connector/gc/GCConnector.java, main/src/cgeo/geocaching/connector/gc/GCConstants.java, main/src/cgeo/geocaching/connector/oc/OCApiLiveConnector.java, tests/src/cgeo/geocaching/models/PersonalNoteTest.java
It also differentiates different limits for different connectors.
=> fix #6591 raise personal notes character limit

main/res/layout/logcache_activity.xml, main/res/values/strings.xml, main/src/cgeo/geocaching/log/LogCacheActivity.java
Also remove the quotes around the string.
I did not managed to test it properly, since I did not find the place where the string is used.
=> Fix #6596: Convert string to plurals

main/src/cgeo/geocaching/CacheDetailActivity.java
Iterates over the links in the description, looks for relative URLs and prepends them with the HostUrl from the Connector.
=> fix #6509 relative URLs in cache description

main/src/cgeo/geocaching/utils/AndroidRxUtils.java
This will work only for executors that we do control explicitly,
such as the network and the refresh executors.
=> fix #6388: silently discard tasks when shutting down executor

main/build.gradle, main/res/drawable/border.xml, main/res/layout-land/coordinatescalculate_dialog.xml, main/res/layout-land/coordinatesinput_dialog.xml, main/res/layout/coordinates_calculate.xml, main/res/layout/coordinates_equations.xml, main/res/layout/coordinates_input.xml, main/res/layout/coordinatescalculate_dialog.xml, main/res/layout/coordinatesinput_dialog.xml, main/res/values/colors.xml, main/res/values/dimens.xml, main/res/values/strings.xml, main/res/values/styles.xml, main/src/cgeo/geocaching/EditWaypointActivity.java, main/src/cgeo/geocaching/models/CalcState.java, main/src/cgeo/geocaching/models/Waypoint.java, main/src/cgeo/geocaching/storage/DataStore.java, main/src/cgeo/geocaching/ui/CalculateButton.java, main/src/cgeo/geocaching/ui/CalculatorVariable.java, main/src/cgeo/geocaching/ui/EditButton.java, main/src/cgeo/geocaching/ui/JSONAble.java, main/src/cgeo/geocaching/ui/JSONAbleFactory.java, main/src/cgeo/geocaching/ui/dialog/ClickCompleteCallback.java, main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateDialog.java, main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java, main/src/cgeo/geocaching/ui/dialog/CustomProgressDialog.java, main/src/cgeo/geocaching/ui/dialog/LongClickCompleteCallback.java, main/src/cgeo/geocaching/utils/CalculationUtils.java
=> Added a Coordinate Calculator: Issue #2038

main/src/cgeo/geocaching/ui/CalculatorVariable.java, main/src/cgeo/geocaching/utils/CalculationUtils.java, tests/src/cgeo/geocaching/utils/CalculationUtilsTest.java
Let's see if it solves the N-Path complexity of the `eval()` method which codacy reported
=> refactored CalculationUtils and added basic UnitTest

main/src/cgeo/geocaching/connector/AbstractConnector.java, main/src/cgeo/geocaching/connector/oc/OCApiConnector.java, main/src/cgeo/geocaching/connector/oc/OCCZConnector.java, main/src/cgeo/geocaching/connector/oc/OCConnector.java, main/src/cgeo/geocaching/connector/oc/OCDEConnector.java, tests/src-android/cgeo/geocaching/connector/ConnectorFactoryTest.java
Read geocode from `wp` URI parameter from OC URLs.
=> fix #6666 parse OC URLs

main/src/cgeo/geocaching/connector/gc/GCConstants.java, main/src/cgeo/geocaching/connector/gc/GCLogin.java, tests/src-android/cgeo/geocaching/CgeoApplicationTest.java, tests/src/cgeo/geocaching/test/mock/GC6K70B.html
GS has changed some style.
Adapt the regex to correspond to the new format.
=> Fix #6682: Failed to detect loggin status

main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java
Removed an unnecessary check that was preventing the calculator from opening when a caches location is unknown.
=> Unnecessary check

main/src/cgeo/geocaching/connector/gc/GCLogin.java, main/src/cgeo/geocaching/connector/gc/GCParser.java, tests/src-android/cgeo/geocaching/connector/gc/GCParserTest.java, tests/src/cgeo/geocaching/test/mock/GC5BRQK.html
GS has changed the top bar code, let's adapt our page parsing.
Moved to using Jsoup instead of old style regexp pattern.
We still have to adapt our unit tests (MockedCache.java) and certainly update mocked caches in /cgeo/geocaching/test/mock/
=> Fix #6682, #6702: Parse username using Jsoup

tests/src-android/cgeo/geocaching/CgeoApplicationTest.java
=> User blafoo has found 2 other webcam caches

main/src/cgeo/geocaching/CacheDetailActivity.java
add detecting problematic text colors in style attributes
As per our normal bug-fix guidelines I based this on release and first propose a merge to master, so that it can be checked on the nightlies but also be applied to release if necessary without hassles.
=> Fix #6724, Description of GC15GV4 unreadable

main/res/values/strings.xml, main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateDialog.java
As mentioned in #6664 it would be better to title the calculator as "Calculator" rather than "Coordinates".
=> Changed the calculator's title from "Coordinates" to "Calculator".

main/res/values/strings.xml, main/src/cgeo/geocaching/ImageSelectActivity.java, main/src/cgeo/geocaching/Intents.java, main/src/cgeo/geocaching/connector/AbstractLoggingManager.java, main/src/cgeo/geocaching/connector/ILoggingManager.java, main/src/cgeo/geocaching/connector/oc/OCApiConnector.java, main/src/cgeo/geocaching/connector/oc/OkapiClient.java, main/src/cgeo/geocaching/connector/oc/OkapiLoggingManager.java, main/src/cgeo/geocaching/connector/oc/OkapiService.java, main/src/cgeo/geocaching/log/LogCacheActivity.java, main/src/cgeo/geocaching/utils/ImageUtils.java
As I was working on the new logging page for GC, I saw the (sad) comment on this issue and I was wandering how image upload works for OC in comparison. Much simpler ;)
The only thing missing right now is the check of the server capabilities on max image size and dimensions. An unscaled image upload was working from my device to opencaching.de.
=> fix #4137 log picture for oc

tests/src-android/cgeo/geocaching/connector/trackable/GeokretyConnectorTest.java
Since GK website upgrade, GK are received in another order
=> Reorder GeoKrety tests

main/src/cgeo/geocaching/maps/CGeoMap.java
Removed hasUnsavedCaches check from store offline menu creation. Removed isOffline check for caches when storing from viewport.
=> #6654 Only unstored caches on live map view are stored in selected list

main/src/cgeo/geocaching/settings/SettingsActivity.java
=> Remove unused import

main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateDialog.java
" When opened first time on a waypoint, the calculator does not takeover the coordinates correctly" resolved.
=> Fixed #6759

main/build.gradle
=> Use intermediate dir for copying pref during builds

main/src/cgeo/geocaching/models/Geocache.java
Use also characters as waypoint prefixes.
=> fix #6784 more than 100 waypoints

main/src/cgeo/geocaching/location/GeopointFormatter.java, main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateDialog.java
#6781 Fixed: Blank section crash
=> #6781 Fixed: Blank section crash

main/src/cgeo/geocaching/ui/CalculateButton.java, main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateDialog.java
=> Remove Magic Char

main/res/layout-w1200dp/coordinatescalculate_dialog.xml, main/res/layout/coordinatescalculate_dialog.xml, main/res/values/strings.xml, main/res/values/strings_not_translatable.xml
Fixed #6796: Calculator Strings
=> Fixed #6796: Calculator Strings

main/src/cgeo/geocaching/ui/EditButton.java, main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateDialog.java
Fixed #6775: Allow non-standard letters to be use in equations
=> Fixed #6775: Allow non-standard letters to be use in equations

main/src/cgeo/geocaching/EditWaypointActivity.java, main/src/cgeo/geocaching/models/CalcState.java, main/src/cgeo/geocaching/settings/Settings.java, main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateDialog.java, main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java
I think I got it now. Tested forth and back. With new waypoints, existing waypoints, with and without userNotes, rotating the device, ...
=> fix #6821 forward user note to calculator

main/src/cgeo/geocaching/EditWaypointActivity.java, main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateDialog.java, main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java
Fixed  #6823: Calculator Notes Cleanup
=> Fixed  #6823: Calculator Notes Cleanup

main/src/cgeo/geocaching/CacheListActivity.java
See #5498 for steps how to reproduce and how to verify the fix.
=> fix #5498 only one loader should be active

main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateDialog.java
=> #6716 leading zero padding

main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateDialog.java
Fixes #6843: Calc cleared when restored from backgorund
=> Fixes #6843: Calculator does not save state on pause

main/src/cgeo/geocaching/EditWaypointActivity.java, main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateDialog.java, main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java
Resolves #6842 Implement "Result Highlighting" in the Calculator.
=> Resolves #6842: Implement "Result Highlighting" in the Calculator

main/src/cgeo/geocaching/EditWaypointActivity.java
The three AsyncTasks in the EditWaypointActivity were flagged with a warning in AS because they should be static to avoid memory leaks. That was an opportunity to convert them to RxJava code which we use throughout c:geo.
=> Replace AsyncTasks with RxJava

main/src/cgeo/geocaching/connector/gc/GCConstants.java, main/src/cgeo/geocaching/connector/gc/GCParser.java, tests/res/raw/gc2cjpf_html, tests/res/raw/gc352y3_owner_view.htm, tests/res/raw/gc366bq.html, tests/res/raw/own_cache.htm, tests/src-android/cgeo/geocaching/CgeoApplicationTest.java, tests/src-android/cgeo/geocaching/connector/gc/GCParserTest.java, tests/src-android/cgeo/geocaching/test/WhitespaceTest.java, tests/src/cgeo/geocaching/test/mock/GC1K1W4.html, tests/src/cgeo/geocaching/test/mock/GC1ZXX2.html, tests/src/cgeo/geocaching/test/mock/GC2CJPF.html, tests/src/cgeo/geocaching/test/mock/GC2JVEH.html, tests/src/cgeo/geocaching/test/mock/GC3FJ5F.html, tests/src/cgeo/geocaching/test/mock/GC3XX5J.html, tests/src/cgeo/geocaching/test/mock/GC5BRQK.html
There is one failing test: `CgeoApplicationTest.testSearchErrorOccured(CgeoApplicationTest.java:193)`
I'm not sure what this test should do. I suspect something with member status, but it's too late now.
=> fix 6865 waypoints not parsed and 6866 archived/disabled state

main/res/values/strings.xml, main/src/cgeo/geocaching/log/LogTemplateProvider.java
oh man! feeling like a noob ... thought I could reenter these lines lying on the sofa with my mobile ... Sorry!
I forgot to convert the float to a String ... 
Thanks,
Jan
=> Fix #6839: add D/T rating to log signature

main/res/menu/map_activity.xml, main/res/values/strings.xml, main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
Replaces the "Store Offline" menu entry with the two new menu entries "Store All" and "Store Unsaved" for the map.
This also fixes #6831
=> fix #6878 store all or unsaved on map

build.gradle, cgeo-contacts/build.gradle, gradle.properties, main/build.gradle
This requires to use Android Studio 3.0. You may also need to
rere-authenticate emulator/device debugging settings.
=> fix #6805 android-gradle-3.0

main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateDialog.java, main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java
Looks like I introduced it via 4c49c067d5b0628707347b4f50ad9a068ecbf3ff
While looking into it I found another issue.
=> 6904 calc crash on pause

gradle/wrapper/gradle-wrapper.properties, main/build.gradle
* use gradle 4.5
* upgrade multiple compile dependencies
* re-enable dex-count
=> upgrade dependencies

main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
It also addresses "Zoom out button is disabled at 10km" as reported in #6933.
=> fix #6311 max zoomlevel for osm:mapnik

main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java, main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapSource.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/cgeo/geocaching/maps/mapsforge/v6/layers/DownloadLayer.java, main/src/cgeo/geocaching/maps/mapsforge/v6/layers/ITileLayer.java, main/src/cgeo/geocaching/maps/mapsforge/v6/layers/RendererLayer.java
To address comment https://github.com/cgeo/cgeo/pull/6948#discussion_r172409286
=> Refactors MapforgeMapSource and TileLayer

main/src/cgeo/geocaching/connector/AbstractLogin.java, main/src/cgeo/geocaching/connector/ec/ECApi.java, main/src/cgeo/geocaching/connector/gc/GCConnector.java, main/src/cgeo/geocaching/connector/gc/GCConstants.java, main/src/cgeo/geocaching/connector/gc/GCLoggingManager.java, main/src/cgeo/geocaching/connector/gc/GCLogin.java, main/src/cgeo/geocaching/connector/gc/GCParser.java, main/src/cgeo/geocaching/connector/gc/GCWebAPI.java, main/src/cgeo/geocaching/log/LogTypeTrackable.java, main/src/cgeo/geocaching/network/Network.java, tests/src-android/cgeo/geocaching/connector/gc/TrackablesTest.java
This is work in progress for the new logging page #6519
It's a mixture of code provided by @johan974 and @samueltardieu 's PR #6548.
It's compiling and I managed to send my first log with it.
Open Issues/Tasks:
- favorites:
=> 6519 new logging page

main/res/values/strings_not_translatable.xml
I think this can be removed as the corresponding map type was removed.
=> Remove Opencyclemap from contributions

main/res/layout/logcache_activity.xml, main/res/values/strings.xml, main/src/cgeo/geocaching/connector/AbstractLoggingManager.java, main/src/cgeo/geocaching/connector/ILoggingManager.java, main/src/cgeo/geocaching/connector/NoLoggingManager.java, main/src/cgeo/geocaching/connector/ec/ECLoggingManager.java, main/src/cgeo/geocaching/connector/gc/GCLoggingManager.java, main/src/cgeo/geocaching/connector/gc/GCWebAPI.java, main/src/cgeo/geocaching/connector/oc/OkapiClient.java, main/src/cgeo/geocaching/connector/oc/OkapiLoggingManager.java, main/src/cgeo/geocaching/export/FieldNotes.java, main/src/cgeo/geocaching/log/LogCacheActivity.java, main/src/cgeo/geocaching/log/LogEntry.java, main/src/cgeo/geocaching/log/LoggingUI.java, main/src/cgeo/geocaching/log/ReportProblemType.java, main/src/cgeo/geocaching/models/Geocache.java, main/src/cgeo/geocaching/storage/DataStore.java, tests/src/cgeo/geocaching/log/ReportProblemTypeTest.java
Implements the "Report Problem" for the new GC logging page and also for OC (#5539).
It partly solves #4899 for those cases where a cacher wants to save e.g. a found and a needs maintenance offline or a DNF and a needs archived.
It also solves #6812 because I had to change the logic to save the log when the report problem changed.
=> fix #6973 log "Report Problem" a.k.a NM, NA

main/src/cgeo/geocaching/maps/mapsforge/v6/MfMapView.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
- Fix handling of MapZoom/real zoom when parceling
- Additionally replaces the handcraftet 'zoomToViewport' by mapsforge implementation
=> Fix #6984 Unwanted zoom-out on device rotation on new Mapsforge beta

main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/cgeo/geocaching/maps/mapsforge/v6/caches/AbstractCachesOverlay.java
- Mapstate was not always correctly/consistently filled when switching maps
=> Fix #6933, Caches disappear on map switch with new mapsforge beta

tests/src-android/cgeo/geocaching/connector/gc/WaypointsTest.java
Replaced GC33HXE, which is now PMO, with GC3KE70.
=> fix #7044 WaypointsTest

main/src/cgeo/geocaching/log/LogCacheActivity.java
Looks like more change than necessary. But there were three places where the Activity was set to default values. At start (onCreate), with clearOfflineLog and also after a log was successfully posted.
I've consolidated the "reset" logic into the `setDefaultValues()` method and reused that at those occasions.
=> fix #6996 clr offline log with rep. problem

main/src/cgeo/geocaching/log/LogCacheActivity.java
New approach, instead of cleaning the screen after posting the log online I've introduced a SaveMode with the following options:
- SMART: save when relevant changes are detected (default)
- FORCE: explicitly save, via menu or saveLog button
- SKIP: when log was posted and offline log cleared
=> fix #7055 empty logscreen while posting log

main/src/cgeo/geocaching/maps/mapsforge/v6/caches/AbstractCachesOverlay.java
- show waypoints in viewport as well
=> Fix #5900, Waypoints hidden on map even below selected limit

main/res/menu/abstract_logging_activity.xml
... and away from "Save offline" to prevent accidental activation
=> Fix #6987 Move "Repeat last log" next to "Clear"

main/res/values/strings.xml, main/src/cgeo/geocaching/AboutActivity.java
Workaround for problem discussed on team channels.
=> Use homepage link instead of paypal link

main/src/cgeo/geocaching/connector/gc/GCConstants.java
Based on analyze by @mucek4 
Untested.
=> Fix #7101 - Personal note parsing

main/res/values-el/strings.xml, main/res/values/strings.xml, main/src/cgeo/geocaching/maps/routing/Routing.java
Bugfix against release proposed for merge and test in master first.
=> Issue 7118

main/res/values/strings.xml, main/src/cgeo/geocaching/connector/AbstractLoggingManager.java, main/src/cgeo/geocaching/connector/ILoggingManager.java, main/src/cgeo/geocaching/connector/gc/GCLoggingManager.java, main/src/cgeo/geocaching/log/LogCacheActivity.java
Introduce network error handling for trackable
and remaining favorite point download
=> Fix #7122, Google Play Alert - java.io.IOexception

main/src/cgeo/geocaching/connector/su/GeocachingSuConnector.java, main/src/cgeo/geocaching/connector/su/GeocachingSuParser.java, tests/src/cgeo/geocaching/connector/su/SUConnectorTest.java, tests/src/cgeo/geocaching/connector/su/SUParserTest.java
I did the coding almost "blindly" without real testing but with help of tests it seems fine.
It would be cool if I can get build APK so I can test it by myself.
Parser test fails for me on "store" stage because there is no DB. I can either delete it or mock the db if you have any clue how.
**Content**
We introduced several new things on .SU:
- Two new cache types for "mystery" caches
- Size indicator
- Waypoints
So I tried to add it to c:geo.
=> Add new types, sizes and waypoints to SU

main/src/cgeo/geocaching/connector/gc/GCLogin.java
This has fixed the problem for me.
=> Fix #7155: Adapt login parameter name to website changes

main/src/cgeo/geocaching/log/LogCacheActivity.java
implement solution for Issue #6938 "Travel Bug status reset with screen rotation during cache log"
- add list of the TB IDs and their state in onSaveInstanceState
- load this list in onCreate
- set the state to saved state or to possible set setting AutoVisit
=> Fix #6938: Save trackable status in log activity

main/src/cgeo/geocaching/activity/OAuthAuthorizationActivity.java
Sometimes exchangeTokens() can be called twice, so it will lead to
failure in exchanging during the second try. Let's remember the last
verifier and if it was already used, skip exchange step
Fixes: #7115
=> OAuth: fix double exchanging tokens

main/src/cgeo/geocaching/CacheDetailActivity.java, main/src/cgeo/geocaching/utils/ColorUtils.java, tests/src-android/cgeo/geocaching/utils/ColorUtilsTest.java
Use W3 recommendations for determining contrast to decide whether to use neutral gray color.
Reference
https://www.w3.org/TR/2008/REC-WCAG20-20081211/#visual-audio-contrast-contrast
Fixes #7153
=> CacheDetailActivity: improve color detection

main/res/layout/about_help_page.xml, main/res/values/strings.xml, main/res/values/strings_not_translatable.xml, main/src/cgeo/geocaching/AboutActivity.java
added link to online manual to about:help-activity
=> fix #7091: added link to online manual to about:help-activity

main/res/layout/brouter_threshold_preference.xml, main/res/values/preference_keys.xml, main/res/values/strings.xml, main/res/xml/preferences.xml, main/src/cgeo/geocaching/maps/routing/Routing.java, main/src/cgeo/geocaching/settings/BrouterThresholdPreference.java, main/src/cgeo/geocaching/settings/Settings.java
Add a user option to settings/map configuration for max. distance (in km) up to which brouter gets involved.
Default value = 10 / max. value = 120 / 0 = disables route calculation
=>  Add user option to change max distance up to which brouter is used (fix  #6157)

.idea/checkstyle-idea.xml, cgeo-contacts/build.gradle, gradle.properties, main/build.gradle, main/res/layout/actionbar_popup.xml, main/res/layout/livemapinfo.xml, main/res/layout/pocketquery_item.xml, main/res/menu/main_activity_options.xml, main/res/values/strings.xml, main/res/values/themes.xml, main/src/cgeo/geocaching/CacheDetailActivity.java, main/src/cgeo/geocaching/CacheListActivity.java, main/src/cgeo/geocaching/CgeoApplication.java, main/src/cgeo/geocaching/MainActivity.java, main/src/cgeo/geocaching/TrackableActivity.java, main/src/cgeo/geocaching/connector/ConnectorFactory.java, main/src/cgeo/geocaching/connector/ec/ECConnector.java, main/src/cgeo/geocaching/connector/gc/GCConnector.java, main/src/cgeo/geocaching/maps/google/v1/GoogleMapActivity.java, main/src/cgeo/geocaching/permission/PermissionGrantedCallback.java, main/src/cgeo/geocaching/permission/PermissionHandler.java, main/src/cgeo/geocaching/permission/PermissionRequestContext.java, main/src/cgeo/geocaching/sensors/GeoData.java, main/src/cgeo/geocaching/sensors/GeoDataProvider.java, main/src/cgeo/geocaching/sensors/Sensors.java, tests/src-android/cgeo/geocaching/sensors/SensorsTest.java
Seems to work ok now (the memory leak was unrelated, but is now fixed).
Review comments already welcome, but I want to merge manually in any case.
Feature wise missing is the check for storage permission (we fallback to app storage, so to works, but backups will be deleted on uninstall).
Contains the build and theming changes as well.
=> Targetsdk 26 - first step

main/src/cgeo/contacts/ContactsAddon.java, main/src/cgeo/geocaching/CacheListActivity.java, main/src/cgeo/geocaching/connector/AbstractConnector.java, main/src/cgeo/geocaching/connector/IConnector.java, main/src/cgeo/geocaching/connector/UserAction.java, main/src/cgeo/geocaching/connector/gc/GCConnector.java, main/src/cgeo/geocaching/connector/oc/OCConnector.java, main/src/cgeo/geocaching/connector/trackable/AbstractTrackableConnector.java, main/src/cgeo/geocaching/connector/trackable/TrackableConnector.java, main/src/cgeo/geocaching/connector/trackable/TravelBugConnector.java, main/src/cgeo/geocaching/connector/trackable/UnknownTrackableConnector.java, main/src/cgeo/geocaching/ui/UserClickListener.java
- remove downcast from context to activity in UserAction
Before merging I'd like to create an issue and reference it in the commit message.
=> Fix crash on click user

main/res/layout/cachelist_spinneritem.xml
adjust fontsizes in cachelist spinner item (fix #7259)
=> adjust fontsizes in cachelist spinner item (fix #7259)

main/res/values/themes.xml
explicitly set actionbar title font size (fix #7260)
=> adjust actionbar font size (fix #7260)

main/res/values/styles.xml
set a smaller button font size (fix #7253)
=> adjust button font size (fix #7253)

main/src/cgeo/geocaching/MainActivity.java, main/src/cgeo/geocaching/activity/AbstractActivity.java
restore actionbar icons on main activity and cache details pages (fix #7256)
=> restore actionbar icons on main activity and cache details pages (fix #7256)

main/res/layout/trackable_item.xml
fix layout on cachedetail's trackable list page (fix #7281)
=> adjust cachedetails trackable list layout (fix #7281)

main/AndroidManifest.xml, main/res/values/strings_not_translatable.xml, main/res/xml/file_provider_paths.xml, main/src/cgeo/geocaching/ui/ImagesList.java, main/src/cgeo/geocaching/utils/ShareUtils.java
add FileProvider for sharing gpx files (fix #7302)
tested against API 19, 22, 26
=> add FileProvider for sharing gpx files and images list (fix #7302) (fix #7255)

build.gradle, gradle/wrapper/gradle-wrapper.properties, main/build.gradle
Adjust gradle with AS 3.3.
Use the gradle plugin 3.3 and gradle 4.10.2.
=> configuration for AS3.3 with gradle plugin 3.3 and gradle 4.10.2 (fix #7237)

main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
Update internal NewMap trailhistory as well,
in preparation for new start
Merging would be quite risk-less IMO, but mark as do not merge for the moment to keep overview over urgent topics
=> Fix  #7235, Map trail disappears when viewing cache details

main/src/cgeo/geocaching/settings/Settings.java
raised max value for waypoints to 200 / default unchanged
=> raise wp limit to 200 (fix #6810)

main/res/layout/coordinates_input.xml, main/res/values/styles.xml
fix #7311
set N/S E/W Buttons to fixed height and width
=> fix #7311 Coord input dialog broken for DMS format

gradle.properties, settings.gradle
fix #6477
- activate build cache
- configure cache dir and creanup time
=> configure gradle build cache (fix #6477)

main/src/cgeo/geocaching/ImageSelectActivity.java
switch selectImageFromCamera to FileProvider (fix #7341)
=> switch selectImageFromCamera to FileProvider (fix #7341)

.gitignore
New folder got created in PR #7339 but it was not added to .gitignore. Let's improve it
=> add build-cache to .gitignore

main/build.gradle
=> Revert "make Icons clickable an google maps again"

mapswithme-api/build.gradle
=> Align SDK versions of mapswithme to main app

main/res/layout/preference_category.xml, main/res/xml/preferences.xml, main/src/cgeo/geocaching/settings/SettingsActivity.java
Use PreferenceCategory instead of TextPreference for category infos
=> Move settings category infos to PreferenceCategory element (fix #5592)

main/src/cgeo/geocaching/connector/gc/GCConnector.java
Not sure if there is any dependency with this variable, which could lead to problems at other places.
Let CI test it first and review appreciated.
=> Fix #7379 - Change CACHE_URL_LONG to currently used scheme

main/src/cgeo/geocaching/connector/gc/GCWebAPI.java
=> fix #7249 group trackable logs by 10

main/src/cgeo/geocaching/settings/Settings.java
Fix #7349: no cache list selection dialog
=> set default value for "show cache list" preference to true

README.md, templates/private.properties
=> templates: add placeholder for SU

main/src/cgeo/geocaching/connector/su/SuParser.java, tests/src/cgeo/geocaching/location/DistanceParserTest.java
* hanging block formatting
* deprecated constructor
Also includes renaming a parameter and a test failure messages in the
same files.
=> fix checkstyle warnings

main/src/cgeo/geocaching/connector/oc/OkapiClient.java, main/src/cgeo/geocaching/connector/su/SuApi.java, main/src/cgeo/geocaching/export/GpxExport.java, main/src/cgeo/geocaching/utils/ImageUtils.java
=> close streams

main/src/cgeo/geocaching/CacheDetailActivity.java, main/src/cgeo/geocaching/EditWaypointActivity.java, main/src/cgeo/geocaching/connector/su/SuApi.java, main/src/cgeo/geocaching/connector/su/SuConnector.java, main/src/cgeo/geocaching/connector/su/SuLoggingManager.java, main/src/cgeo/geocaching/permission/PermissionHandler.java, main/src/cgeo/geocaching/sensors/GeoData.java, main/src/cgeo/geocaching/utils/ColorUtils.java, tests/src-android/cgeo/CGeoTestCase.java
* static imports from class defining the constant
* remove unused members
* javadoc missing arguments documentation
* unnecessarily nested block
* missing override
* empty method
=> fix more warnings

main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
- check location permission and start location provider even on map
- possibly fixes #7303 and #7300 as well
=> Fix #7391, Starting from live map widget crashes the app

tests/src-android/cgeo/geocaching/connector/su/SuConnectorTest.java, tests/src-android/cgeo/geocaching/connector/su/SuParserTest.java, tests/src-android/cgeo/geocaching/test/mock/MockedCache.java, tests/src-android/cgeo/geocaching/utils/TextUtilsTest.java
* more readable (left to right)
* more expressive (hasSize(), contains(), isEmpty()...)
* better error messages
* junit assert is deprecated
Really please don't introduce new assertions using plain junit assert.
=> use assertj

main/res/drawable/border_straight.xml, main/res/values/styles.xml
add progressdialog styling with border and non transparent background (fix #7434)
=> add progressdialog styling with border and non transparent background (fix #7434)

main/src/cgeo/geocaching/CacheDetailActivity.java, main/src/cgeo/geocaching/CacheListActivity.java, main/src/cgeo/geocaching/CompassActivity.java, main/src/cgeo/geocaching/EditWaypointActivity.java, main/src/cgeo/geocaching/NavigateAnyPointActivity.java, main/src/cgeo/geocaching/TrackableActivity.java, main/src/cgeo/geocaching/activity/AbstractActivity.java, main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/cgeo/geocaching/permission/PermissionRequestContext.java, main/src/cgeo/geocaching/permission/RestartLocationPermissionGrantedCallback.java
Fixes #7442 and #7443, NPE in specific activities on resume
=> Refactor and complete onResume location access handling

main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/MapOptions.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
don't show direction line when called from address search
show "enable live / disable live" menu entry when called from address search
=> fixes for opening map from address search (fix #7386) (fix #7387)

main/src/cgeo/geocaching/connector/su/SuApi.java
=> su: add find_date param during log posting

main/build.gradle, main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java, main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapSource.java, main/src/cgeo/geocaching/maps/mapsforge/v6/layers/DownloadLayer.java, main/src/cgeo/geocaching/maps/mapsforge/v6/layers/RendererLayer.java
Reference the new version
Adjust to some small API changes
=> Fix  #7494, Upgrade to mapsforge 0.11.0

main/src/cgeo/geocaching/maps/interfaces/MapViewImpl.java, main/src/cgeo/geocaching/maps/mapsforge/MapsforgePositionAndHistory.java
need to be merged before pr #7502 is accepted by checkstyle
=> some checkstyle fixes

tests/src-android/cgeo/geocaching/files/GPXParserTest.java, tests/src-android/cgeo/geocaching/filter/TerrainFilterTest.java, tests/src-android/cgeo/geocaching/models/GeocacheTest.java, tests/src-android/cgeo/geocaching/models/WaypointTest.java, tests/src/cgeo/geocaching/network/ParametersTest.java
Use more specialized assertj expectations than just .isTrue().
=> use assertj methods

main/src/cgeo/geocaching/connector/gc/GCMap.java, main/src/cgeo/geocaching/connector/gc/GCWebAPI.java, tests/src-android/cgeo/geocaching/CgeoApplicationTest.java, tests/src-android/cgeo/geocaching/connector/gc/GCConnectorTest.java
Referencing #7230, this is using the API used by the new map to load caches for the live map viewport. I'm not that comfortable with this project yet, so please review.
There are still some references to the tiles left in some functions calling my code, I left it intact to just be a drop-in replacement.
Please feel free to comment and give further advice, I'd like to help bring the c:geo project forward.
=> Updated Live Map to use new GC.com /play/map

main/res/values-ca/strings.xml, main/res/values-ceb/strings.xml, main/res/values-cs/strings.xml, main/res/values-da/strings.xml, main/res/values-de/strings.xml, main/res/values-el/strings.xml, main/res/values-es/strings.xml, main/res/values-fi/strings.xml, main/res/values-fr/strings.xml, main/res/values-hu/strings.xml, main/res/values-it/strings.xml, main/res/values-ja/strings.xml, main/res/values-ko/strings.xml, main/res/values-lt/strings.xml, main/res/values-lv/strings.xml, main/res/values-nb/strings.xml, main/res/values-nl/strings.xml, main/res/values-pl/strings.xml, main/res/values-pt/strings.xml, main/res/values-ro/strings.xml, main/res/values-ru/strings.xml, main/res/values-sk/strings.xml, main/res/values-sl/strings.xml, main/res/values-sv/strings.xml, main/res/values-tr/strings.xml, main/res/values/strings.xml
This was not removed in the commits for #5015
=> remove string for "Opencaching.com (Garmin)"

main/res/xml/preferences.xml, main/src/cgeo/geocaching/settings/Settings.java
=> Don't activate gc.com connector on install (Fix #7461)

main/src/cgeo/geocaching/TrackableActivity.java
Fix #7531 (Trackable "status" seems not localized)
=> localize TB status (Fix #7531)

main/src/cgeo/geocaching/storage/DataStore.java
Just had exactly one cache get disabled that was on my lists and it worked flawlessly, might need some more testing though.
I opted to not touch the `storeIntoDatabase` function because I did not want to disturb the `updated` value or any other data stored.
This could possibly be extended to also update the favorite count.
=> Fixes #7539, update disabled status in the database from live map

main/src/cgeo/geocaching/apps/navi/MapsMeApp.java
fix #7340 (Navigation with maps.me not starting)
=> get activity from ContextWrapper (fix #7340)

main/res/values/strings.xml, main/src/cgeo/geocaching/CacheListActivity.java
add confirmation dialog to batch upload modified coords function (fix#7585)
=> add confirmation dialog to batch upload modified coords function (fix#7585)

main/src/cgeo/geocaching/AboutActivity.java
=> move "Getting Started" in front of "Help"

main/src/cgeo/geocaching/CompassActivity.java, main/src/cgeo/geocaching/MainActivity.java, main/src/cgeo/geocaching/sensors/GnssStatusProvider.java, main/src/cgeo/geocaching/sensors/GpsStatusProvider.java, main/src/cgeo/geocaching/sensors/Sensors.java
Setting the 'Do not merge' tag until tested properly.
=>  Fix #7560: Use GNSS API if available

main/build.gradle
After upgrade the support library to v.25.x we can now upgrade here.
=> upgrade google play services

main/src/cgeo/geocaching/activity/AbstractActivity.java, main/src/cgeo/geocaching/activity/ActivityMixin.java
ActionBarActivity is deprecated in API level 25.1.0
we are now on API 25.4.0
changed from
android.support.v7.app.ActionBarActivity;
to
android.support.v7.app.AppCompatActivity;
=> ActionBarActivity is deprecated

main/res/layout/popup.xml, main/res/layout/waypoint_popup.xml, main/src/cgeo/geocaching/CachePopupFragment.java, main/src/cgeo/geocaching/WaypointPopupFragment.java, main/src/cgeo/geocaching/speech/SpeechService.java
We have tts navigation already in CompassActivity. This PR adds the same to the map's cache and waypoint popups. Tested with GMv1, MFv0.3 and NewMap.
=> add tts navigation to cache and waypoint popups

main/src/cgeo/geocaching/activity/AbstractActivity.java, main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/MapUtils.java, main/src/cgeo/geocaching/maps/mapsforge/v6/caches/AbstractCachesOverlay.java, main/src/cgeo/geocaching/maps/mapsforge/v6/caches/LiveCachesOverlay.java, main/src/cgeo/geocaching/maps/mapsforge/v6/caches/StoredCachesOverlay.java, main/src/cgeo/geocaching/maps/mapsforge/v6/caches/WaypointsOverlay.java, main/src/cgeo/geocaching/ui/CacheListAdapter.java, main/src/cgeo/geocaching/utils/MapMarkerUtils.java
add an cache-owner based filter to waypoint overlay for mapsforge v6
=> Fix #2558, Filter waypoints for owned caches

main/res/layout/popup.xml, main/res/layout/waypoint_popup.xml, main/res/menu/cache_options.xml, main/res/values/strings.xml, main/src/cgeo/geocaching/CacheDetailActivity.java, main/src/cgeo/geocaching/CachePopupFragment.java, main/src/cgeo/geocaching/WaypointPopupFragment.java
- switch to menu entry for tts on cache and waypoint popups instead of button
- add tts cache details page
Fixes #7674
=> tts menu entry instead of button (fix #7674)

main/res/values/strings.xml
added a hint for update or removal of authorization data, see marked box:
=> add hint for removal of authorization data (fix #7646)

main/res/menu/compass_activity_options.xml, main/res/values/strings.xml, main/src/cgeo/geocaching/CompassActivity.java
(a followup to https://github.com/cgeo/cgeo/pull/7680#discussion_r296318035)
=> switch tts in compass view to toggle

main/res/values/strings_not_translatable.xml, main/src/cgeo/geocaching/AbstractDialogFragment.java, main/src/cgeo/geocaching/CacheDetailActivity.java, main/src/cgeo/geocaching/models/Geocache.java
Fixes #4346 
Also remove "x" from the text on cache details page, and intention is to show fav points even if they're 0 (see #7439)
=> Add favorite percentage to cache details view

main/res/layout/about_contributors_page.xml, main/res/values/strings.xml, main/res/values/strings_not_translatable.xml, main/res/values/styles.xml, main/src/cgeo/geocaching/AboutActivity.java
Our contributors page has become out of sync lately. I updated the page, adding all contributors from 2018/19 according to github's contributors page, using their respective github user names.
=> update contributors page

main/src/cgeo/geocaching/location/ProximityNotification.java
- change TONE_NEAR signalling to four tones
- change output stream to STREAM_MUSIC (to see whether this influences volume at all)
=> proximity notification followup: output stream (volume), TONE_NEAR signalling

main/res/values/strings.xml, main/src/cgeo/geocaching/apps/AbstractLocusApp.java, main/src/cgeo/geocaching/enumerations/CacheType.java, tests/src/cgeo/geocaching/enumerations/CacheTypeTest.java
first part for #7704 Support new GC cache types
- implement GC cache type "Geocaching HQ Celebration"
- preparation for GC cache type "Community Celebration Event"
=> support new/changed GC cache types

main/AndroidManifest.xml, main/src/cgeo/geocaching/AbstractDialogFragmentWithProximityNotification.java, main/src/cgeo/geocaching/CachePopupFragment.java, main/src/cgeo/geocaching/CompassActivity.java, main/src/cgeo/geocaching/WaypointPopupFragment.java, main/src/cgeo/geocaching/location/ProximityNotification.java, main/src/cgeo/geocaching/location/ProximityNotificationByCoords.java, main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
This reverts commit 27ea6321b2fd3619bbf7db570093061810a10dd5.
=> Revert "respect silent mode settings for proximity notification (#7724)"

main/src/cgeo/geocaching/settings/SettingsActivity.java, main/src/cgeo/geocaching/utils/SharedPrefsBackupUtils.java
update settings backup menu after creating a backup (fix #7735)
=> update settings backup menu after creating a backup (fix #7735)

main/res/values/preference_keys.xml, main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/CachesOverlay.java, main/src/cgeo/geocaching/settings/Settings.java
Remember the circle preference setting
=> make map circle preference permanent (fix #6518)

main/src/cgeo/geocaching/maps/mapsforge/v6/caches/AbstractCachesOverlay.java
Only sync layers if there is something to do
(especially relevant for waypoints)
Fixes #7745
=> Fix Slightly "dancing" GPS location triggers syncLayers #7745

main/res/values/strings.xml, main/src/cgeo/geocaching/settings/AbstractProximityPreference.java, main/src/cgeo/geocaching/settings/AbstractSeekbarPreference.java, main/src/cgeo/geocaching/settings/BrouterThresholdPreference.java, main/src/cgeo/geocaching/settings/WpThresholdPreference.java
Make seekbar value editable (opens input dialog on touch)
Add @Override where applicable
=> Make seekbar value editable (opens input dialog on touch) (fix #7726)

main/res/layout/cachelist_listmarker_item.xml, main/res/menu/cache_list_options.xml, main/res/values/strings.xml, main/src/cgeo/geocaching/CacheListActivity.java, main/src/cgeo/geocaching/command/DeleteListCommand.java, main/src/cgeo/geocaching/list/ListMarker.java, main/src/cgeo/geocaching/list/StoredList.java, main/src/cgeo/geocaching/storage/DataStore.java, main/src/cgeo/geocaching/utils/MapMarkerUtils.java
Third part related to #7761: optionally assign icon marker to lists and display those markers on map and in cache lists
assign marker to list or remove it from list:
markers are shown in cache list...
... and on the map:
=> optionally assign icon marker to lists

build.gradle
set gradle plugin according to AS = Version 3.4.2
=> Update build.gradle for AS 3.4.2

gradle/wrapper/gradle-wrapper.properties, gradlew, gradlew.bat
latest gradle version is now 5.6
=> upgrade gradle to 5.6

main/res/layout/waypoint_popup.xml, main/res/values/strings.xml, main/src/cgeo/geocaching/WaypointPopupFragment.java
Followup to #2592 / #7791: Replace "set visited" button by checkbox + short toast
=> replace 'visited' button on popup by checkbox + toast

main/src/cgeo/geocaching/WaypointPopupFragment.java
followup to #7803: initialize "visited" checkbox according to current "visited" state
=> initialize visited checkbox

main/src/cgeo/geocaching/maps/CGeoMap.java
I don't know if an issue has been created for this but I experienced crashes when switching between map view types.
=> Fix #7510 -Crash when switching between map views.

gradle/wrapper/gradle-wrapper.properties
This is a patch to Version 5.6,
see https://docs.gradle.org/5.6.1/release-notes.html#fixed-issues
=> upgrade gradle to 5.6.1

main/src/cgeo/geocaching/connector/AbstractConnector.java
fix #7125 Owner actions not working
=> use owner displayName (according to cache details) to query owner actions

main/src/cgeo/geocaching/ui/UserClickListener.java
fix #7818 different usage of userName and displayName
=> Cache owner details - set owner name to displayName according to cache details

main/res/values/strings.xml, main/src/cgeo/geocaching/CacheListActivity.java
- separate menu entry from dialog title
- some minor adjustments
(see comments in 9a1fc4d11aed)
=> adjust menu entry, dialog title and warning for upload all coords function

main/res/xml/preferences.xml
automatically disable trailcolor preference setting if trailhistory preference is set to disabled
=> make trailcolor pref dependent on trailhistory pref

main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/google/v2/GoogleMapView.java
=> start live map loading when called from address center search (fix #7602)

main/build.gradle, tests/proguard-project.txt, tests/src-android/cgeo/geocaching/activity/AbstractEspressoTest.java, tests/src-android/cgeo/geocaching/activity/waypoint/AddWaypointActivityTest.java, tests/src-android/cgeo/geocaching/activity/waypoint/AddWaypointMultiTest.java, tests/src-android/cgeo/geocaching/activity/waypoint/AddWaypointMysteryTest.java, tests/src-android/cgeo/geocaching/activity/waypoint/EditWaypointActivityTest.java, tests/src-android/cgeo/geocaching/log/LogTrackableActivityTest.java
... from com.google.android.apps.common.testing.ui.espresso
to android.support.test.espresso
on the way to androidx test classes
=> change espresso test classes paths

build.gradle, main/src/cgeo/geocaching/CacheListActivity.java, main/src/cgeo/geocaching/loaders/NullGeocacheListLoader.java
fix #7865 Unable to start CacheListActivity from map (targetSDK28)
It is not necessary to create a loader for showing the list.
Therefore let's catch only the Exception.
=> create a "Null-Search-Loader" to present the result

build.gradle, cgeo-contacts/build.gradle, main/build.gradle, mapswithme-api/build.gradle
also fix #7878
- Set all projects to compileSdkVersion 28
- use supportLibraryVersion 28.0.0
- add useLibrary for tests
=> Switch to compileSdk 28 / support libraries 28.0.0

main/src/cgeo/geocaching/utils/MapMarkerUtils.java
=> calculate icon sizes with getIntrinsicXXX instead of getXXX

main/src/cgeo/geocaching/permission/PermissionGrantedCallback.java, main/src/cgeo/geocaching/permission/PermissionHandler.java, main/src/cgeo/geocaching/storage/LocalStorage.java, main/src/cgeo/geocaching/utils/SharedPrefsBackupUtils.java
- Need to reset publicCgeoDir var after storage permissions granted (fixes #7890)
- Need to create backup directory before writing the prefs backup file.
=> fix some storage problems

checkstyle.xml, main/src/cgeo/geocaching/connector/gc/GCConnector.java, main/src/cgeo/geocaching/connector/gc/GCLoggingManager.java, main/src/cgeo/geocaching/connector/gc/PocketQueryListAdapter.java, main/src/cgeo/geocaching/connector/oc/OCApiLiveConnector.java, main/src/cgeo/geocaching/connector/oc/OCConnector.java, main/src/cgeo/geocaching/connector/oc/OCDEConnector.java, main/src/cgeo/geocaching/connector/su/SuLoggingManager.java
- checkstyle.xml
- switch to the revised Doctype definition
- explicitly linefeed as line separator for check NewlineAtEndOfFile
- fix different code annotation warnings
("not annotated method overrides method annotated with ..." etc.)
=> fix Lint/Checkstyle issues

main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
draw direction line on GMv2 only when setting is enabled (fixes #7908)
=> respect isMapDirection() setting for GMv2 (fix #7908)

main/src/cgeo/geocaching/activity/ActivityMixin.java
Reverts cgeo/cgeo#7903 to be able to move #7916 to release
=> Revert "invalidateOptionsMenu(Activity activity) is deprecated"

main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
Reverts cgeo/cgeo#7916 to be able to move it to release branch
=> Revert "respect isMapDirection() setting for GMv2 (fix #7908)"

tests/src-android/cgeo/watchdog/WatchdogTest.java
Fixes #7929
exclude internal connector from website test
=> exclude internal connector from website test (fix #7929)

README.md
add GoogleMaps Key Source
make the text clearer
=> update README for API keys

main/src/cgeo/geocaching/storage/DataStore.java
While working on a different part I noticed that the dropDatabase method is missing some tables, therefore completed it.
=> complete dropDatabase / add missing tables

main/src/cgeo/geocaching/maps/google/v2/GoogleMapView.java
expand GMv2 by user defined cache long click
(long click on GMv2 map to open dialog to create a user defined cache)
=> expand GMv2 by user defined cache long click

main/src/cgeo/geocaching/utils/CheckerUtils.java
** Description of change: **
Add the geochecker geotjek.dk used in e.g. this cache
https://coord.info/GC2P6JZ
=> Add geochecker geotjek.dk

main/res/values/strings.xml, main/res/xml/preferences.xml
=> make trailcolor string translatable (fix #7960)

gradle/wrapper/gradle-wrapper.properties
5 issues have been fixed in Gradle 5.6.3.
see
https://docs.gradle.org/5.6.3/release-notes.html
=> update gradle to 5.6.3

main/src/cgeo/geocaching/maps/google/v2/GoogleMapView.java, main/src/cgeo/geocaching/maps/google/v2/GoogleOverlay.java, main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
Fixes #7944
Update real distance on coords change for GMv2
=> update real distance on coords change for GMv2 (fix #7944)

main/src/cgeo/geocaching/maps/google/v2/GoogleMapView.java, main/src/cgeo/geocaching/maps/google/v2/GoogleOverlay.java, main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
Reverts cgeo/cgeo#7965 on master branch to divert it to release branch
=> Revert "update real distance on coords change for GMv2 (fix #7944)"

main/res/values/strings_not_translatable.xml
instead of the old user guide page with only a few sentences of explanation
=> Link to new offline map tutorial

.gitignore, crowdin/README, crowdin/download, crowdin/globals, crowdin/update
- clarify the README
- optimize/fix download script
- fix bug for the "pr" parameter check
- add check for new languages
- add gitignore entry for cgeo-calendar strings
=> update crowdin process

main/build.gradle
=> make lint inspection happy

build.gradle, main/build.gradle
FindBugs is deprecated, SpotBugs the official successor.
see https://spotbugs.github.io/
=> replace FindBugs by SpotBugs

main/res/values/preference_keys.xml
resolve some lint issues by removing unused preference_keys
=> lint resolving: remove unused preference_keys

main/res/values/themes.xml
resolve some lint issues by removing unused themes
=> lint resolving: remove unused themes

main/res/layout/about_contributors_page.xml, main/res/layout/authorization_credentials_activity.xml, main/res/layout/authorization_token_activity.xml, main/res/layout/cachedetail_waypoints_header.xml, main/res/layout/coordinates_calculate.xml, main/res/layout/coordinates_equations.xml, main/res/layout/coordinates_input.xml, main/res/layout/coordinatescalculate_dialog.xml, main/res/layout/editwaypoint_activity.xml, main/res/layout/fragment_edit_note.xml, main/res/layout/imageselect_activity.xml, main/res/layout/logcache_activity.xml, main/res/layout/logtrackable_activity.xml, main/res/layout/main_activity.xml, main/res/layout/map_google.xml, main/res/layout/map_mapsforge.xml, main/res/layout/map_mapsforge_v6.xml, main/res/layout/popup.xml, main/res/layout/preference_seekbar.xml, main/res/layout/simple_dir_chooser.xml, main/res/layout/template_preference_dialog.xml, main/res/layout/waypoint_item.xml, main/res/values/strings.xml, main/res/values/strings_not_translatable.xml
resolves lint issues by adding missing layout attributes
=> lint resolving: fix a couple of layout attributes

main/src/cgeo/geocaching/location/DistanceParser.java, main/src/cgeo/geocaching/settings/AbstractProximityPreference.java, main/src/cgeo/geocaching/settings/AbstractSeekbarPreference.java, main/src/cgeo/geocaching/settings/BrouterThresholdPreference.java, main/src/cgeo/geocaching/ui/CacheListAdapter.java
Fix a couple of lint issues by
- adding missing locale (4x)
- changing text output from plain integer to String conversion to using String.format with locale (1x)
=> lint resolving: fix issues with missing locale

main/src/cgeo/geocaching/CompassActivity.java
Show current elevation in compass as additional info beside the current coordinate.
Elevation is calculated as average from the last five readings.
=> show elevation in compass (fix #7196)

main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
=> keep current camera position when autorotating map (fix #8040)

main/src/cgeo/geocaching/maps/CGeoMap.java
Fixes #8049 
tested both cycles:
- MF current => GMv2 => MF current
and 
- MFv0.3 => GMv2 => MFv0.3
=> set isStoreEnabled in MapState on map source change (fix #8049)

.idea/checkstyle-idea.xml, checkstyle.xml, main/src/cgeo/geocaching/connector/oc/OkapiClient.java, main/src/cgeo/geocaching/connector/su/SuApi.java, main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapView.java, main/src/cgeo/geocaching/settings/SettingsActivity.java, main/src/cgeo/geocaching/ui/CalculateButton.java, main/src/cgeo/geocaching/ui/CalculatorVariable.java, main/src/cgeo/geocaching/ui/EditButton.java, main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateDialog.java, main/src/cgeo/geocaching/utils/Formatter.java, suppressions.xml
fix #8032
- configure AS checkstyle to version to 8.26 as used on codacy
- set checkstyle output language fix to English
- change java import order rule (option under, severity info)
- update suppressions.xml doctype definition
- code formatting: xml intent to 4
For testfolders see #8052
maybe containes changes for #6946
=> checkstyle optimization

main/src/cgeo/geocaching/CacheDetailActivity.java, main/src/cgeo/geocaching/CacheListActivity.java, main/src/cgeo/geocaching/CompassActivity.java, main/src/cgeo/geocaching/MainActivity.java
fix SetTextI18n warnings
- suppress warnings for string concatenation (they are intentionally)
- fix a warning for not using locale
=> lint resolving: fix or suppress lint SetTextI18n warnings

main/src/cgeo/geocaching/settings/Settings.java
=> make Settings.getDefaultNavigationTool() more tolerant (fix #8069)

main/res/values/changelog_release.xml
=> Update changelog release

main/src/cgeo/geocaching/CompassActivity.java
=> add cache shortinfo to waypoint compass (fix #4674)

tests/src-android/cgeo/geocaching/log/LogTemplateProviderTest.java
=> correct check for year value

tests/src-android/cgeo/geocaching/CgeoApplicationTest.java, tests/src-android/cgeo/geocaching/test/mock/GC2JVEH.java, tests/src/cgeo/geocaching/test/mock/GC2JVEH.html
Please check before merging, if the failing test is really caused by a source change rather than a bug we introduced.
=> Work on #8091 - Test search trackable broken

main/res/values/strings.xml, main/src/cgeo/geocaching/connector/internal/InternalConnector.java
Fixes parts of #8082:
- add some explanation about what UDC ZZ0 is
- store ZZ0 in a new user defined list
=> create ZZ0 UDC in new list + with additional info

main/src/cgeo/geocaching/connector/internal/InternalConnector.java, main/src/cgeo/geocaching/storage/DataStore.java
last part to fix #8082:
on demand migration of "go to" history, with localized strings
must not be merged before #8095
=> add on demand migration of "go to" history

main/src/cgeo/geocaching/storage/DataStore.java
adds the missing import statement which got lost somehow during the last merges
=> fix merge artifact (fix #8103)

main/res/layout/fragment_edit_note.xml, main/res/menu/cache_options.xml, main/res/values/strings.xml, main/src/cgeo/geocaching/CacheDetailActivity.java, main/src/cgeo/geocaching/activity/AbstractActivity.java, main/src/cgeo/geocaching/models/Geocache.java, main/src/cgeo/geocaching/storage/DataStore.java, main/src/cgeo/geocaching/ui/EditNoteDialog.java
=> add option to prevent waypoint extraction from note (fix #8078)

main/build.gradle
=> downgrade jackson library

main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
=> set heading pointer direction back to heading, ignore map bearing

build.gradle, gradle/wrapper/gradle-wrapper.properties, main/src/cgeo/geocaching/connector/gc/GCWebAPI.java, main/src/cgeo/geocaching/network/Network.java
Add payload as json and use cookie authentication
=> Fix logging on geochaching.com

main/src/cgeo/geocaching/maps/mapsforge/v6/MfMapView.java, main/src/cgeo/geocaching/maps/mapsforge/v6/caches/AbstractCachesOverlay.java, main/src/cgeo/geocaching/maps/mapsforge/v6/caches/CachesBundle.java
proposal to fix #7034 and fix #8126
Do not merge for now, but field test first. Please look for possible side effects as well.
For details see https://github.com/cgeo/cgeo/issues/8126#issuecomment-605324757
=> synchronize map layer access for NewMap

crowdin.yml
First step before starting integration
=> Work on #3601 - Add crowdin integration configuration

main/proguard-project.txt
- removes build.gradle in showcaseview
- adapted proguard config
=> Repo cleanup: Remove showcaseview (fix #8201)

main/src/cgeo/geocaching/maps/routing/Route.java, main/src/cgeo/geocaching/maps/routing/RouteItem.java
=> Add class loader for unparceling Route/RouteSegment

main/res/values/preference_keys.xml, main/res/values/strings.xml, main/res/xml/preferences.xml, main/src/cgeo/geocaching/maps/google/v2/GoogleMapView.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/cgeo/geocaching/settings/Settings.java
Extend the existing switch for "long press on map for UDC" to individual routes.
=> make individual routing optional (fix #8235)

main/src/cgeo/geocaching/CgeoApplication.java
workaround for issuetracker.google.com/issues/154855417
as described in https://issuetracker.google.com/issues/154855417#comment179
=> workaround for google maps corrupted zoom data file bug

main/res/values/strings.xml, main/src/cgeo/geocaching/CacheDetailActivity.java
Show a "waypoint added" toast after waypoint has been created with "add current location"
=> show toast on 'add current location' (fix #8239)

main/res/values/strings.xml, main/src/cgeo/geocaching/filter/CountryFilterFactory.java, main/src/cgeo/geocaching/filter/FilterRegistry.java, main/src/cgeo/geocaching/storage/DataStore.java
Unconstrained, over all Countries extracted from the Location field on all caches.
Fixes #5257 
See #8210 for history.
=> Implemented Filtering by Country

main/src/cgeo/geocaching/storage/DataStore.java
Remove a couple of routines from the old "go to history" / "searched destinations" implementation, which are not used anymore.
=> Remove unused code from old goto history implementation

main/AndroidManifest.xml, main/res/values/strings_not_translatable.xml, main/src/cgeo/geocaching/helper/QueryMapFile.java
This is the c:geo part for https://github.com/cgeo/WhereYouGo/pull/146
=> Add helper for WhereYouGo offline map onboarding

main/src/cgeo/geocaching/CacheDetailActivity.java
=> prevent crash on opening details of unsaved cache (fix #8257)

main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/google/v2/GoogleMapView.java
add missing feature to GMv2: long tap on free space of single cache map to add waypoint
=> add to GMv2: add waypoint from single cache map (fix #8269)

main/res/values/strings.xml, main/src/cgeo/geocaching/filter/CountryFilterFactory.java
Avoids having an empty line in the country filter list.
=> label empty country filter with (empty)

main/src/cgeo/geocaching/CacheDetailActivity.java
- refresh waypoint view after creating new waypoint at current location
- also: do creation of new waypoint in background
=> refresh view after creating new waypoint at current location (fix #8266)

main/src/cgeo/geocaching/filter/CountryFilterFactory.java, main/src/cgeo/geocaching/storage/DataStore.java
Alternative to #8278
Cleaned up alternative implementations.
=> Sort country filter list, remove unused db fetch implementations

main/src/cgeo/geocaching/maps/AbstractMap.java, main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/cgeo/geocaching/maps/routing/BRouterServiceConnection.java, main/src/cgeo/geocaching/maps/routing/Route.java, main/src/cgeo/geocaching/maps/routing/Routing.java
- recalculate and repaint individual route after routing type changes (fix #8304)
- delay route calculation until BRouter connection is established (fix #8303)
=> fixes for update individual route (fix #8303, fix #8304)

main/src/cgeo/geocaching/maps/CGeoMap.java
=> fix NPE on showProgressHandler (fix #8317)

main/build.gradle
- update AndroidAnnotations to 4.7
- remove workaround introduced with #7993 to fix #7858
=> update AndroidAnnotations to 4.7 and remove workaround (fix #7997)

main/src/cgeo/geocaching/maps/CGeoMap.java
=> fix NPE in map initialization (fix #8319)

main/src/cgeo/geocaching/WaypointPopup.java
ignore sporadic RuntimeException / implement workaround for #8316 (waypoint popup) the same way we did for the cache popup
=> workaround for #8316

main/res/values/strings_not_translatable.xml, main/src/cgeo/geocaching/AboutActivity.java, main/src/cgeo/geocaching/helper/UsefulAppsActivity.java
(left out some links as they use invalid/outdated https certificates)
=> update several http resources to https

README.md
- update links from http to https
- replace old link to translation (which results in security error when used with https) by link to crowdin
=> update links in README.MD

main/src/cgeo/geocaching/maps/mapsforge/v6/caches/CachesBundle.java, main/src/cgeo/geocaching/maps/mapsforge/v6/caches/WaypointsOverlay.java
For OSM in single cache mode: show waypoints of owned caches even when hideOwn is set to true
=> show waypoints of owned cache on OSM SINGLE when hideOwn==true (fix #8333)

main/src/cgeo/geocaching/maps/routing/Route.java
=> fix crash on them options change (fix #8349)

main/src/cgeo/geocaching/models/Geocache.java
Seemed like a low-hanging fruit :)
Fixes #7742
=> fix: use proper equal comparison

main/src/cgeo/geocaching/location/Viewport.java, main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/mapsforge/v6/caches/LiveCachesOverlay.java
See https://github.com/cgeo/cgeo/issues/8260#issuecomment-634888573
=> restrict viewport calculation to GC live caches

main/src/cgeo/geocaching/connector/su/SuParser.java, tests/src-android/cgeo/geocaching/connector/su/SuParserTest.java
=> su: fix handling empty json

main/build.gradle
update okhttp to version 4 line (which requires minSDK 21)
=> update okhttp to v4

main/src/cgeo/geocaching/location/Viewport.java
merges the three nearly identical `containingXXX` methods internally into one
=> code deduplication for Viewport containingXXX methods

main/res/values/strings.xml, main/res/xml/preferences.xml
=> add summary for show additional lists preference (fix #8437)

main/src/cgeo/geocaching/CgeoApplication.java, main/src/cgeo/geocaching/ImageSelectActivity.java, main/src/cgeo/geocaching/settings/HwAccel.java, main/src/cgeo/geocaching/utils/ShareUtils.java, main/src/cgeo/geocaching/utils/SystemInformation.java
Remove old code, which is now unreachable due to our raised min SDK
=> remove code unreachable due to new min SDK

main/src/cgeo/geocaching/CgeoApplication.java
The fix is no longer needed, therefore remove stale code.
=> remove google maps zoom data fix

main/src/cgeo/geocaching/ui/AnchorAwareLinkMovementMethod.java
by setting `Intent.FLAG_ACTIVITY_NEW_TASK` on URL intents
=> open links from listing text in separate task (fix #8472)

main/src/cgeo/geocaching/maps/mapsforge/v6/layers/AbstractLineLayer.java
(Applies for track lines and individual route lines as well.)
=> avoid race condition for track line (fix #8478)

main/res/values/strings.xml, main/src/cgeo/geocaching/files/GPXTrackImporter.java, main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/cgeo/geocaching/utils/TrackUtils.java
Show a shot toast after call to loadTracks - either "Track loaded" or "Error loading track".
(see https://github.com/cgeo/cgeo/issues/8480#issuecomment-647101943)
=> add load track status toast

main/res/values/strings.xml, main/src/cgeo/geocaching/files/GPXTrackImporter.java, main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/cgeo/geocaching/utils/TrackUtils.java
see https://github.com/cgeo/cgeo/pull/8498#issuecomment-647194341
=> show number of trackpoints after successfully loading a track

main/src/cgeo/geocaching/maps/mapsforge/v6/layers/AbstractLineLayer.java
Switch to drawing paths instead of single line entities to avoid artifacts as shown in https://github.com/cgeo/cgeo/issues/8477#issuecomment-648646797. (OSM only, as Google Maps already uses paths.)
=> use path drawing functions on OSM map to avoid "dotted lines"

main/src/cgeo/geocaching/maps/mapsforge/v6/caches/GeoitemRef.java, main/src/cgeo/geocaching/storage/DataStore.java
remove two redundant local variables
=> fix redundant local variables

tests/src-android/cgeo/watchdog/WatchdogTest.java
Do not merge for now, due to https://github.com/cgeo/cgeo/issues/7732#issuecomment-632822577
- reactivate ec website test
- but move it to the end of the website tests to not block other website tests
=> reactivate ec website test as last website being tested

main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/cgeo/geocaching/utils/BRouterUtils.java
Extract common code regarding routing mode to a separate utility class.
=> code deduplication for routing mode settings

main/src/cgeo/geocaching/maps/mapsforge/v6/layers/NavigationLayer.java
similar to #8531, but for OSM direction line
=> prevent OSM dotted direction line

main/res/layout/view_settings_item.xml, main/src/cgeo/geocaching/settings/ViewSettingsActivity.java
(new try, after Codacy permanently failed on #8581)
=> add fast scroll to settings view

main/res/layout/cachedetail_waypoints_page.xml, main/res/layout/logs_page.xml, main/res/layout/usefulapps_activity.xml, main/src/cgeo/geocaching/CacheDetailActivity.java, main/src/cgeo/geocaching/CacheListActivity.java, main/src/cgeo/geocaching/log/LogsViewCreator.java, main/src/cgeo/geocaching/ui/FastScrollListener.java
- disable fastscroll by default (cache list, cache detail waypoint view, cache detail log view)
- enable new fastscroll behavior on demand for those views
- removed fastscroll for useful apps view
=> implement FastScrollListener (fix #8406)

main/src/cgeo/geocaching/ui/FastScrollListener.java
As `onScrollStateChange()` seems to miss a lot of `SCROLL_STATE_IDLE` notifications this alternative implementation (mostly) switches to `onScoll()`, setting a timer for 1s, and checks whether the last scroll position is the same as the current position. If so, fastscroll gets disabled, otherwise the timer is restarted.
Enabling fastscroll is unchanged compared to the current implementation.
Additional change is that the fast scroll bar is set to "always visible", so that as long as fast scroll mode is active, fast scroll bar is visible (instead of fading out, but still being active for some time). If you see the thinner position marker, fast scroll is disabled.
=> alt. implementation for fast scroll, mostly avoiding onScrollStateChange

tests/src-android/cgeo/geocaching/address/GeocoderTest.java
Fixes issue #7729 
With respect to the known open android bug, a workaround is implemented to ignore the "grpc fail" exceptions in test case
=> Fix issue 7729: CI fails constantly for Geocoder test

main/src/cgeo/geocaching/maps/mapsforge/v6/layers/HistoryLayer.java
similar to #8531 and #8574, this time for history track line on OSM
=> avoid dotted history track lines on OSM

main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java, main/src/cgeo/geocaching/maps/mapsforge/v6/layers/HistoryLayer.java
See https://github.com/cgeo/cgeo/issues/8648#issuecomment-660957768 (first sub issue)
=> history line: always draw from current to last recorded position

main/src/cgeo/geocaching/maps/mapsforge/v6/layers/HistoryLayer.java
Let's see if this can fix issue #8664
=> adapt history draw algorithm from GMv2 to NewMap

main/AndroidManifest.xml, main/res/layout/mapdownloader_activity.xml, main/res/layout/mapdownloader_item.xml, main/res/menu/map_activity.xml, main/res/values/strings.xml, main/src/cgeo/geocaching/activity/ActivityMixin.java, main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/MapProviderFactory.java, main/src/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/cgeo/geocaching/models/OfflineMap.java, main/src/cgeo/geocaching/settings/MapDownloadNotificationReceiver.java, main/src/cgeo/geocaching/settings/MapDownloadSelectorActivity.java, main/src/cgeo/geocaching/settings/ReceiveMapFileActivity.java, main/src/cgeo/geocaching/storage/DataStore.java, main/src/cgeo/geocaching/storage/extension/PendingDownload.java, main/src/cgeo/geocaching/utils/MapDownloadUtils.java
For detailed description and screenshots see #8610
=> OSM offline map files downloader (fix #8610)

main/src/cgeo/geocaching/maps/routing/RouteSortActivity.java
Following the discussion in https://github.com/cgeo/cgeo/issues/8670#issuecomment-664035421:
- remove left swipe action
- use long press on title/detail to delete
Way less code and easier to use.
=> Route sort: Delete action on long press instead of left swipe

main/src/cgeo/geocaching/settings/MapDownloadSelectorActivity.java
While testing for #8717 I've stumbled upon an error message which should be an info message only.
=> convert internal error message to warning

main/src/cgeo/geocaching/storage/DataStore.java
fix some db structure issues:
- add creation of extension table to `onCreate()` (which fixes #8706 and #8717)
- rename table `cg_table_route` to `cg_route` to comply with table name scheme
- recreate table `cg_extension` to fix table naming issue and two column type issues
=> fix some db structure issues (fix #8717, fix #8706)

main/res/menu/map_activity.xml, main/res/values/strings.xml, main/src/cgeo/geocaching/export/IndividualRouteExport.java, main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/cgeo/geocaching/maps/routing/Route.java, main/src/cgeo/geocaching/maps/routing/RouteSegment.java, main/src/cgeo/geocaching/utils/IndividualRouteUtils.java
First part for #8727: Export function for individual route
(Individual route gets exported as a regular GPX route file, but follows the convention to use the geocode as the route point's name to be able to import it accordingly later. Import is not part of this PR.)
=> export individual route as GPX

main/res/values/strings.xml
fix #8685 as discussed in https://github.com/cgeo/cgeo/issues/8685#issuecomment-668209792
=> Rename List "Internal caches" to "User Defined Caches"

main/src/cgeo/geocaching/log/LogEntry.java, main/src/cgeo/geocaching/log/OfflineLogEntry.java, main/src/cgeo/geocaching/storage/DataStore.java, tests/src-android/cgeo/geocaching/log/LogEntryTest.java
While working on Issue #2553 (Offline Log with image upload doesn't save image to log) I realized at some point that I need some more fundamental changes in order to implement this in a future-proof way. This became much too big for one Pull Request. Thus the idea is to push parts of this as independent pull requests and glueing the code pieces together once they are through. This also allows separate discussion with regards of different things I suggest to bring to the code.
This is one of those Pull Request.
Basics for Offline Log with image (and other data): the underlying data object OfflineLogEntry, complete with Parceable ability and inherited from LogEntry
=> [Part of Issue:#2553] Creating OfflineLogEntry on top of LogEntry

main/res/values/strings.xml, main/src/cgeo/geocaching/utils/IndividualRouteUtils.java
To avoid accidentally deleting your carefully crafted individual route...
=> add confirmation to clear individual route

main/AndroidManifest.xml, main/res/menu/map_activity.xml, main/res/values/strings.xml, main/src/cgeo/geocaching/SelectIndividualRouteFileActivity.java, main/src/cgeo/geocaching/files/GPXIndividualRouteImporter.java, main/src/cgeo/geocaching/files/GPXIndividualRouteParser.java, main/src/cgeo/geocaching/maps/routing/RouteItem.java, main/src/cgeo/geocaching/utils/IndividualRouteUtils.java
=> load individual route

main/res/values/strings.xml, main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/cgeo/geocaching/utils/TrackUtils.java
- add overwrite warning for load track
- and group all track related strings into a separate group
(both in accordance to individual routes)
=> add overwrite warning for load track

main/src/cgeo/geocaching/list/StoredList.java
=> place new list entry at top (fix #8751)

main/res/values/strings_not_translatable.xml
Welcome to our new contributors!
Let's update c:geo's internal contributors list accordingly.
=> update contributors list to 08/2020

main/src/cgeo/geocaching/ui/TextSpinner.java, tests/src/cgeo/geocaching/ui/TextSpinnerTest.java
Completely forgot to add unit testing to new classes in PR #8760 yesterday. Very sorry for that. Here is the addendum.
=> [PR:#8760] add unit testing for TextSpinner

tests/src-android/cgeo/geocaching/activity/ProgressTest.java
Possible fix for #8764 : suppress the problematic test case
=> [Issue:#8764] possible fix: Suppress ProgressTest

main/res/values/themes.xml
=> colorAccent in cache list selector

main/res/menu/map_activity.xml, main/res/values/strings.xml, main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/cgeo/geocaching/utils/MapUtils.java, main/src/cgeo/geocaching/utils/TrackUtils.java
- add "center on track" function to map menu (GMv2 / NewMap)
- group "load individual track", "unload individual track" and "center on track" into new submenu "individual track"
=> add center on track function (fix #8687)

main/src/cgeo/geocaching/export/IndividualRouteExport.java, main/src/cgeo/geocaching/export/TrailHistoryExport.java, main/src/cgeo/geocaching/utils/FileUtils.java
as mentioned in https://github.com/cgeo/cgeo/issues/8777#issuecomment-671432764
use 24 hour format in log / export files names. Regards
- logcat log file
- individual route export file
- history track export file
=> use 24 hour format for file names

main/res/values/strings.xml, main/src/cgeo/geocaching/utils/DebugUtils.java
=> add option to write complete logfile (fix #8777)

main/src/cgeo/geocaching/ui/dialog/Dialogs.java
Apply colorAccent-aware themeing also to the new dialog introduced by #8784.
=> apply themeing to new confirmation dialog

main/src/cgeo/geocaching/MainActivity.java, main/src/cgeo/geocaching/storage/DataStore.java
=> Include offline finds in total finds on home screen

main/src/cgeo/geocaching/utils/TrackUtils.java
remove two debug messages no longer needed
=> remove superflous debug info

main/res/menu/map_activity.xml, main/res/values/strings.xml, main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/cgeo/geocaching/utils/IndividualRouteUtils.java
add "center on route" function for individual routes (similar to #8687 for tracks)
=> add center on route function for individual routes

main/res/values/themes.xml
similar to #8816, but for Dialog_Alert themes
=> add text_color attribute to Dialog_Alert themes (fix #8819)

main/res/values/strings.xml, main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/MapProviderFactory.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/cgeo/geocaching/settings/Settings.java
=> support default language for OSM offline maps (fix #8814)

main/res/layout/cachedetail_description_page.xml, main/res/values/strings.xml, main/src/cgeo/geocaching/CacheDetailActivity.java, main/src/cgeo/geocaching/enumerations/WaypointType.java, main/src/cgeo/geocaching/location/Geopoint.java, main/src/cgeo/geocaching/models/Geocache.java, main/src/cgeo/geocaching/models/Waypoint.java, tests/src/cgeo/geocaching/models/WaypointTest.java
Aims to fix multiple issues related to "WayPoint Storage in PN":
* #8785 (uploaded WP list is missing closing tag)
* #8791 (too many waypoints created)
* #8790 (UI for waypoint storage)
* #8747 (only user-defined WPs are stored)
See these issues for more details
=> Fixes for waypoint storage in PN (fix #8785)(fix #8791)(fix #8790) (fix #8747)

main/src/cgeo/geocaching/log/LogCacheActivity.java
During development I noticed that log view does no longer adapt to log type change. This is the fix for this bug.
=> fix error: view did not adapt to log type change

main/res/values/strings.xml, main/src/cgeo/geocaching/settings/MapDownloadSelectorActivity.java, main/src/cgeo/geocaching/settings/ReceiveMapFileActivity.java, main/src/cgeo/geocaching/settings/Settings.java, main/src/cgeo/geocaching/utils/MapDownloadUtils.java
- do a "target dir writable?" check before opening the map selector
- do a "target dir writable?" check before copying received map file
- print more detailed info if copying received map file fails
=> additional checks for map downloader (fix #8821)

main/res/values/changelog_master.xml
=> issue_8871

main/res/layout/about_version_page.xml
=> change text color for text on black forest in About Activity

cgeo-contacts/build.gradle
part "enable the language" for #8878
the apk looks fine:
=> Activate chinese traditional for the contacts plugin

main/res/values/strings.xml, main/src/cgeo/geocaching/storage/DataStore.java, main/src/cgeo/geocaching/utils/DatabaseBackupUtils.java
First part of #8895:
Before starting a "restore database", check if database versions are compatible, meaning
- either version(backup) <= version(expected)
- or version(backup) can be downgraded to version(expected)
=> check database version before restore

main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
update distance info for Google Maps target even if distance line is disabled
fixes #8889
=> update distance info for GM target even if distance line disabled

main/res/menu/map_activity.xml, main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/MapProviderFactory.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
@fm-sys 
Can you test this APK in your environment?
I've implemented a different group marker for the "download map" menu item - maybe that works in your setting.
Also I've added some `Log.i()` calls to output some debug info about the menu items while adding the map sources.
=> change group setting for download map menu entry

main/build.gradle
related to #8896
- set also the ribbon color blue for nightly and debug
- set the ribbon text for rc to beta
=> change ribbon/icon color

main/res/layout-land/compass_activity.xml, main/res/layout/compass_activity.xml, main/res/values/strings.xml, main/res/values/styles.xml, main/src/cgeo/geocaching/CompassActivity.java, main/src/cgeo/geocaching/sensors/DirectionData.java, main/src/cgeo/geocaching/sensors/DirectionDataCalculator.java, main/src/cgeo/geocaching/sensors/GeoDirHandler.java, main/src/cgeo/geocaching/sensors/MagnetometerAndAccelerometerProvider.java, main/src/cgeo/geocaching/sensors/OrientationProvider.java, main/src/cgeo/geocaching/sensors/RotationProvider.java, main/src/cgeo/geocaching/sensors/Sensors.java, main/src/cgeo/geocaching/settings/Settings.java, main/src/cgeo/geocaching/ui/TextSpinner.java, tests/src-android/cgeo/geocaching/sensors/SensorsTest.java
=> Estimate device orientation and transform coords when upright (fix #7152)

main/src/cgeo/geocaching/log/LogCacheActivity.java, main/src/cgeo/geocaching/ui/TextSpinner.java
Fix for #8942 : handle also same-item-event
=> fix #8942: handle also same-item-event

main/res/values/strings.xml, main/src/cgeo/geocaching/log/LogTemplateProvider.java
fix #8947 for users who don't like the new template
=> add legacy number template

main/src/cgeo/geocaching/log/LogCacheActivity.java, main/src/cgeo/geocaching/storage/DataStore.java, main/src/cgeo/geocaching/utils/ContextLogger.java, main/src/cgeo/geocaching/utils/DebugUtils.java, main/src/cgeo/geocaching/utils/Log.java
First steps to analyze and solve #8632 
Does two things:
* removes duplicate "save" on saving offline log (by removing the "SaveMode" logic)
* adds verbose log information on how often savelog is called (and how much time it takes) as well as whether the class `androidx.appcompat.widget.ShareActionProvider` is accessible
=> Related to #8632: add verbose logging, remove SaveMode from OfflineLogging

main/src/cgeo/geocaching/activity/AbstractActivity.java, main/src/cgeo/geocaching/activity/ActivityMixin.java, main/src/cgeo/geocaching/log/LogCacheActivity.java
Fix #8962: offline log handling 
related to #8632: adding lots of verbose logging.
=> fix #8962: offline log handling and adding verbose logging

main/src/cgeo/geocaching/log/LogCacheActivity.java, main/src/cgeo/geocaching/log/OfflineLogEntry.java
(fix #8962)(fix #8973) add more guards and rules to handle special c:geo log saving
=> (fix #8962)(fix #8973) add more guards and rules to handle special c:geo log saving

main/src/cgeo/geocaching/ui/CacheVotingBar.java
fix #8983: handling null-case for votingConnector
=> fix #8983: handling null-case for votingConnector

main/src/cgeo/geocaching/storage/DataStore.java, main/src/cgeo/geocaching/utils/CollectionStream.java, main/src/cgeo/geocaching/utils/ContextLogger.java, main/src/cgeo/geocaching/utils/Log.java
related to #8632: add even more logging (in verbose)
It should theoretically be visible with these logs whether loading of cache data and/or logs is the cause for problems on magpiefourtytwo's device
=> related to #8632: add even more logging (in verbose)

main/res/layout/cacheslist_item.xml
=> multi-line cache title in cache list (fix #8966)

main/src/cgeo/geocaching/storage/DataStore.java, main/src/cgeo/geocaching/utils/Log.java
(related to #8990) Log: add iForce, add maxDepth param, rename pfile to log-properties.txt
Adjusted for release branch
=> (related to #8990) Log: add iForce, add maxDepth param, rename pfile to log-properties.txt

main/src/cgeo/geocaching/storage/DataStore.java
fix #8990: add Log.iForce message when duplicate col is found
=> fix #8990: add Log.iForce message when duplicate col is found

main/res/layout/about_version_page.xml
| before | now |
|-|-|
| ![Screenshot_20200911_232720_cgeo geocaching (Small)](https://user-images.githubusercontent.com/64581222/92977702-fff47b80-f48d-11ea-97a7-fe8ba5176d1e.jpg) | ![Screenshot_20200912_001224_cgeo geocaching (Small)](https://user-images.githubusercontent.com/64581222/92977704-008d1200-f48e-11ea-96fb-dcfc18b67a58.jpg) |
=> keep aspect ratio of background image in about versions

main/src/cgeo/geocaching/storage/DataStore.java
related to #8632: create indices to optimize cache-log-select
creates db version 86
=> related to #8632: create indices to optimize cache-log-select

main/res/layout/cacheslist_item.xml, main/src/cgeo/geocaching/ui/CacheListAdapter.java
=> allow single or multi-line cache title (fix #9007)

main/res/menu/cache_options.xml, main/res/values/strings.xml, main/src/cgeo/geocaching/CacheDetailActivity.java, main/src/cgeo/geocaching/models/Geocache.java
=> add option to delete all user-defined waypoints (fix #8994)

main/res/layout/logcache_activity.xml, main/res/values/strings.xml, main/src/cgeo/geocaching/log/LogCacheActivity.java
fix #8970: remove title prefix
=> fix #8970: remove title prefix

main/src/cgeo/geocaching/utils/SystemInformation.java
add a couple of additional info to about - system information:
- GPX import / export dir
- map file / map theme dir
- live map mode
- global filter mode
=> add more system info details (related to #9049)

main/src/cgeo/geocaching/maps/mapsforge/v6/MfMapView.java
=> Do not merge: Test: Remove zoom-level adaption mf<->google

main/src/cgeo/geocaching/ui/dialog/Dialogs.java
=> Focus text input in list creation dialog

main/src/cgeo/geocaching/maps/mapsforge/v6/MfMapView.java
CI breaks on CodeStyle check in file MfMapView for all pull requests currently.
(I do not know how one was able to introduce this due to Codacy...)
This very small PR intends to fix that, please merge as soon as possible...
=> fix broken ci

main/res/layout-land/compass_activity.xml, main/res/layout/compass_activity.xml, main/res/values/strings.xml
fix #9051: add maxLine=1 and shorten default translations
=> fix #9051: add maxLine=1 and shorten default translations

main/res/values/strings.xml, main/src/cgeo/geocaching/connector/gc/GCLogin.java, main/src/cgeo/geocaching/enumerations/StatusCode.java
- detect captcha on login
- fix detection of wrong username/password on login
=> provide #9039 and #9068 for legacy version (fix #9075)

main/src/cgeo/geocaching/activity/ActivityMixin.java
related to #9086: put safeguard before setSelection
=> related to #9086: put safeguard before setSelection

main/src/cgeo/geocaching/storage/DataStore.java
related to #9087: failfast on unrecoverable db opening issues
=> related to #9087: failfast on unrecoverable db opening issues

main/res/values/strings.xml, main/src/cgeo/geocaching/log/LogTemplateProvider.java
Add [TYPE] as a signature template, and also as a logging insertion option.
=>  Fix #7771: Support [TYPE] in signature

main/src/cgeo/geocaching/log/LogCacheActivity.java, main/src/cgeo/geocaching/utils/CollectionStream.java, tests/src/cgeo/geocaching/utils/CollectionStreamTest.java
fix #9101: add NPE guards to CollectionStream
=> fix #9101: add NPE guards to CollectionStream

main/src/cgeo/geocaching/storage/DataStore.java
While working on some other issues I recognized that I wasn't able to upgrade my database any longer. During investigation I found some common pitfalls:
- trying to create indices for tables not yet existing
- trying to change a table structure which has been created correctly (as the wrong step-in-between hadn't been executed as I was coming from an even older version)
This PR is created for `master` branch currently, to gain time for testing.
Shall I create it for `release` instead, to have it in the upcoming release?
=> fix some db upgrade pitfalls

main/src/cgeo/geocaching/ImageSelectActivity.java
related to #9145: fix camera issue
=> related to #9145: fix camera issue

main/src/cgeo/geocaching/connector/gc/GCConstants.java
https://github.com/eddiemuc/cgeo/pull/new/issues/ci-read-trackable-gui-for-release-9155
=> fix #9155: change GCParser to react on changed web page

main/src/cgeo/geocaching/log/LogsViewCreator.java
related to #9142: remove dateStr as possible parameter
@bekuno since you merged #9142 already I made an own PR for this. I hope that's ok?
=> related to #9142: remove dateStr as possible parameter

main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
- Adds a try/catch block for the suspected code lines for `RejectedExecutionException `, logs the exception message
- tries to help with #8402
=> add try/catch for RejectedExecutionException (related to #8402)

main/src/cgeo/geocaching/connector/gc/GCConstants.java, main/src/cgeo/geocaching/connector/gc/GCLogin.java
- updates link for retrieving avatar image
- removes outdated check for login (non-matching already today)
=> adapt to removal of old profile page (fix #9150)

main/res/layout/about_version_page.xml, main/res/values/strings.xml, main/res/values/strings_not_translatable.xml, main/src/cgeo/geocaching/AboutActivity.java
=> add GitHub link to about page (fix #9164)

main/build.gradle, main/src/cgeo/geocaching/connector/gc/GCConstants.java, main/src/cgeo/geocaching/settings/Settings.java, main/src/cgeo/geocaching/storage/LocalFolder.java, main/src/cgeo/geocaching/storage/LocalStorage.java, main/src/cgeo/geocaching/storage/PublicLocalStorage.java, main/src/cgeo/geocaching/utils/DebugUtils.java
trying to store/copy logcat logfile to public dir after storing it. This is a proof-of-concept/tryout only!
=> WIP try to store logfile to public dir

main/src/cgeo/geocaching/log/CacheLogsViewCreator.java, main/src/cgeo/geocaching/log/LogsViewCreator.java
related to #9151: restore one-click-edit for own logs in loglist
=> related to #9151: restore one-click-edit for own logs in loglist

cgeo-contacts/build.gradle
set compileSdkVersion and targetSdkVersion to 29 according to c:geo
=> update contacts to api29

main/res/layout/imagelist_fragment.xml, main/res/layout/imagelist_item.xml, main/res/layout/logcache_activity.xml, main/src/cgeo/geocaching/ImageSelectActivity.java, main/src/cgeo/geocaching/log/LogCacheActivity.java, main/src/cgeo/geocaching/models/Image.java, main/src/cgeo/geocaching/ui/ImageListFragment.java, main/src/cgeo/geocaching/ui/recyclerview/ManagedListAdapter.java, main/src/cgeo/geocaching/utils/ImageUtils.java
related to #8978 and #7064: 
* introduce ManagedListAdapter as a generic (RecyclerVIew) Adapter which can handle among other things drag/drop (for #8978)
* extract imagelist gui part to `ImageListFragment` (for usage later in trackable logs #7064 )
* add visual drag/drop capabilities for Log Cache Images (see https://github.com/cgeo/cgeo/issues/8978#issuecomment-711041267 for screenshots)
=> related to #8978 and #7064: introduce ManagedListAdapter, extract imagelist to imagelistfragment, add drag/drop for cachelog images

main/res/values/strings_not_translatable.xml
As we gained quite a few new contributors over the last couple of months, I've updated the list.
Please add a comment if I've missed some frequent & recent contributor.
=> update list of contributors as of 2020-10

main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java
Move the "Combined (Offline)" entry in map select menu to top of offline maps
=> move combined (offline) entry to top of offline maps list (fix #9200)

main/src/cgeo/geocaching/ui/CacheVotingBar.java
fix #9227: dont forward unchanged ratings in cachvotingbar
=> fix #9227: dont forward unchanged ratings in cachvotingbar

main/src/cgeo/geocaching/export/GpxSerializer.java, tests/src-android/cgeo/geocaching/export/GpxSerializerTest.java
fix #9233: format gpx xml on export
=> fix #9233: format gpx xml on export

main/src/cgeo/geocaching/storage/DataStore.java
fix #9222: set offline state to false
=> fix #9222: set offline state to false

main/res/layout/map_mapsforge.xml, main/res/layout/map_mapsforge_v6.xml, main/res/values/strings.xml, main/res/values/strings_not_translatable.xml, main/src/cgeo/geocaching/maps/AbstractMapSource.java, main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/interfaces/MapProvider.java, main/src/cgeo/geocaching/maps/interfaces/MapSource.java, main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java, main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapSource.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
fix #6150: add map attribution
=> fix #6150: add map attribution

cgeo-contacts/lint.xml, main/build.gradle, main/lint.xml, main/res/values/numbers.xml, main/res/values/preference_keys.xml, main/res/values/strings.xml
- configure lint for the crowdin process
- add 'ExtraTranslation' ignore rule in build.gradle for runtime check
- add 'ExtraTranslation' ignore rule in lint.xml for lint check
- remove 'MissingQuantity' ignore check
- remove 'ImpliedQuantity' ignore check
- edit 'UnusedQuantity' ignore check to all files
- add some unused images (png/xml) to the ignore list
- add 'ObsoleteLintCustomCheck' ignore rule
These warnings are only for external sources
- remove 'InvalidPackage' ignore rule for runtime check
This is fixed in the meantime
- delete some ' UnusedResources' strings
see https://ci.cgeo.org/job/cgeo%20pull%20request/3872/androidLintResult/type.-2046836529/package.-963969145/
@Lineflyer @moving-bits @eddiemuc @fm-sys 
Please check if I maybe did too much.
=> lint changes/fixes

main/src/cgeo/geocaching/connector/ConnectorFactory.java
remove leftover from viewport caching tests some time ago
=> remove unused local vars

main/src/cgeo/geocaching/connector/gc/GCConstants.java, main/src/cgeo/geocaching/connector/gc/GCParser.java
PR cherry-picked from master and targeted to release
=> support loading new TB pages (fix #9263)

main/res/values/strings.xml, main/src/cgeo/geocaching/TrackableActivity.java, main/src/cgeo/geocaching/connector/UserAction.java, main/src/cgeo/geocaching/connector/gc/GCConnector.java, main/src/cgeo/geocaching/connector/gc/GCConstants.java, main/src/cgeo/geocaching/connector/gc/GCParser.java, main/src/cgeo/geocaching/log/CacheLogsViewCreator.java, main/src/cgeo/geocaching/log/LogEntry.java, main/src/cgeo/geocaching/log/TrackableLogsViewCreator.java, main/src/cgeo/geocaching/models/Geocache.java, main/src/cgeo/geocaching/storage/DataStore.java, main/src/cgeo/geocaching/ui/UserClickListener.java, tests/src-android/cgeo/geocaching/CgeoApplicationTest.java, tests/src/cgeo/geocaching/connector/trackable/UnknownTrackableConnectorTest.java
It adds a link to the gc message center for cache owners, cache log authors, trackable owners, trackable last spotted users and trackable log authors (simply everywhere we use the user context menu) as discussed in #5352
=> link to the gc message center

main/src/cgeo/geocaching/maps/mapsforge/v6/MfMapView.java
related to #9270: fix IllegalArgumentException on lat/long span calculation
This PR intends to fix the IllegalArgumentExceptions issued permanently on calls to MfMapView.getLatitudeSpan()/getLongitudeSpan().
This was done in situations where the map as a whole (the "whole world") or one of its borders was smaller than the screen. This usually happens when zoomlevel is very small, 0 or 1. It also happens sometimes during some sort of "map initialization phase" where zoomlevel is temporary 0.
Fix can be seen in code. Part of review should be if it is well understood (and if it is correct of course)
=> related to #9270: fix IllegalArgumentException on lat/long span calculation

main/res/values/strings.xml, main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java
related to #9292: make attribution calc asynchronous
This makes calc to mal attribution asynchronous for single offline maps. In hope that this is the problems cause
=> related to #9292: make attribution calc asynchronous

main/build.gradle
=> ignore NonConstantResourceId lint messages

main/AndroidManifest.xml, main/src/cgeo/geocaching/ui/dialog/Dialogs.java
Black text color in input dialog when in lightmode (fix #9073) and hide keyboard at mainActivity when closing dialog (don't know if it's also tracked somewhere)
=> fix light mode text color in input dialog

main/res/values/preference_keys.xml, main/res/values/strings.xml, main/res/xml/preferences.xml, main/src/cgeo/geocaching/settings/Settings.java, main/src/cgeo/geocaching/utils/MapMarkerUtils.java, main/src/cgeo/geocaching/utils/builders/InsetBuilder.java, main/src/cgeo/geocaching/utils/builders/InsetsBuilder.java
Issue: #9274 
The last commit is a refactoring to a builder pattern to move the concern of building and positioning the insets to a new class. This removes some duplicate code. For me it is okay to revert this commit if this refactoring is too risky on this functionality.
=> Allow bigger smileys on map for found caches (fix #9274)

main/res/layout/logcache_activity.xml, main/res/values/strings.xml, main/src/cgeo/geocaching/log/LogCacheActivity.java, main/src/cgeo/geocaching/utils/TextUtils.java
=> show character counter starting from 3000 characters

main/res/values/strings.xml, main/src/cgeo/geocaching/NavigateAnyPointActivity.java, main/src/cgeo/geocaching/storage/DataStore.java
First entry is always "Create new cache", second always "Go to targets", followed by the other already existing UDC, sorted by last-changed-first.
=> select target on geo intent (fix #9290)

main/res/values/strings.xml, main/src/cgeo/geocaching/network/StatusUpdater.java
Cherry-picked from `master` for `release`
=> remove Android 11 warning (fix #9225)

main/res/layout/map_distanceinfo.xml, main/res/layout/map_google.xml, main/res/layout/map_mapsforge.xml, main/res/layout/map_mapsforge_v6.xml, main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/DistanceDrawer.java, main/src/cgeo/geocaching/maps/MapDistanceDrawerCommons.java, main/src/cgeo/geocaching/maps/google/v2/GoogleMapView.java, main/src/cgeo/geocaching/maps/interfaces/MapViewImpl.java, main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapView.java, main/src/cgeo/geocaching/maps/mapsforge/MapsforgeOverlay.java, main/src/cgeo/geocaching/maps/mapsforge/MapsforgePositionAndHistory.java, main/src/cgeo/geocaching/maps/mapsforge/v6/DistanceView.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
While working on #9282 I've stumbled upon the old, manual implementation of drawing distance infos in `CGeoMap`. Refactored this into using a couple of `TextView` elements, and merged layouts and drawing handling for all maps into one.
This is a prerequisite for #9282.
=> refactor map distance display

main/res/drawable/copyright.xml, main/res/layout/map_mapsforge.xml, main/res/layout/map_mapsforge_v6.xml, main/res/values/strings.xml, main/res/values/strings_not_translatable.xml, main/src/cgeo/geocaching/maps/AbstractMapSource.java, main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/interfaces/MapProvider.java, main/src/cgeo/geocaching/maps/interfaces/MapSource.java, main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java, main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapSource.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
related to #6150: change GUI to something Locus-alike
Will also fix #9327
For screenshots see https://github.com/cgeo/cgeo/issues/6150#issuecomment-720082544
=> related to #6150: change GUI to something Locus-alike

main/src/cgeo/geocaching/activity/AbstractActivity.java, main/src/cgeo/geocaching/settings/Settings.java, main/src/cgeo/geocaching/settings/SettingsActivity.java, main/src/cgeo/geocaching/storage/PublicLocalFolder.java, main/src/cgeo/geocaching/storage/PublicLocalStorage.java, main/src/cgeo/geocaching/utils/DebugUtils.java
First Draft of SAF for logfiles. Seems to work
=> First Draft of SAF for logfiles

main/src/cgeo/geocaching/activity/AbstractActivity.java, main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/cgeo/geocaching/settings/ReceiveMapFileActivity.java, main/src/cgeo/geocaching/settings/Settings.java, main/src/cgeo/geocaching/settings/SettingsActivity.java, main/src/cgeo/geocaching/storage/PublicLocalFolder.java, main/src/cgeo/geocaching/storage/PublicLocalStorage.java, main/src/cgeo/geocaching/storage/PublicLocalStorageActivityHelper.java, main/src/cgeo/geocaching/utils/DebugUtils.java, tests/src-android/cgeo/geocaching/SettingsTest.java
related to #8457: another day of coding for SAF
=> related to #8457: another day of coding for SAF

main/src/cgeo/geocaching/maps/mapsforge/v6/caches/LiveCachesOverlay.java, main/src/cgeo/geocaching/network/Network.java
fix #8682: handle movements correctly in OSM/Offline
=> fix #8682: handle movements correctly in OSM/Offline

main/src/cgeo/geocaching/CacheDetailActivity.java, main/src/cgeo/geocaching/CacheListActivity.java, main/src/cgeo/geocaching/CacheMenuHandler.java
A tiny first step towards #9283
=> replace case statements with resource ids by if/else (rel. to #9283)

main/src/cgeo/geocaching/connector/ConnectorFactory.java, main/src/cgeo/geocaching/maps/MapUtils.java
fix #9284: add explicit filter for user-defined caches, add shortcut not to hit servers
=> fix #9284: add explicit filter for user-defined caches, add shortcut not to hit servers

main/res/menu/cache_options.xml, main/src/cgeo/geocaching/CacheMenuHandler.java, main/src/cgeo/geocaching/models/Geocache.java
=> make cache share actions more consistent (fix #9339) 

main/res/values/strings.xml, main/src/cgeo/geocaching/storage/DataStore.java, main/src/cgeo/geocaching/ui/dialog/Dialogs.java, main/src/cgeo/geocaching/utils/BackupUtils.java, main/src/cgeo/geocaching/utils/ShareUtils.java
- fix #4705 (add share feature)
- simplify backup successful message
=> simplify backup successful message and add share feature

main/res/values/preference_keys.xml, main/res/xml/preferences.xml, main/src/cgeo/geocaching/activity/AbstractActivity.java, main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/cgeo/geocaching/settings/ReceiveMapFileActivity.java, main/src/cgeo/geocaching/settings/Settings.java, main/src/cgeo/geocaching/settings/SettingsActivity.java, main/src/cgeo/geocaching/storage/PublicLocalFolder.java, main/src/cgeo/geocaching/storage/PublicLocalStorage.java, main/src/cgeo/geocaching/storage/PublicLocalStorageActivityHelper.java, main/src/cgeo/geocaching/utils/MapDownloadUtils.java, main/src/cgeo/geocaching/utils/SystemInformation.java
related to #8457: midway of integrating SAF for offline maps
=> related to #8457: midway of integrating SAF for offline maps

main/src/cgeo/geocaching/maps/mapsforge/v6/MfMapView.java, main/src/cgeo/geocaching/settings/Settings.java
fix #9430: install safeguard for negative zoomlevels in settings
=> fix #9430: install safeguard for negative zoomlevels in settings

main/src/cgeo/geocaching/ui/CacheListAdapter.java
fix #9048: safehuard to prevent arrayindexoutofbounds
=> fix #9048: safeguard to prevent arrayindexoutofbounds

main/build.gradle
=> add Ukrainian to used languages

main/res/values/strings.xml
Addressed some issues from Crowdin contributors:
- Emoticons instead of smileys
- Fix some incorrect capitalization
- Omit unneeded user/owner in string
=> String changes based on crowdin issues

main/src/cgeo/geocaching/maps/mapsforge/v6/DistanceView.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/cgeo/geocaching/maps/mapsforge/v6/TargetView.java, main/src/cgeo/geocaching/models/ManualRoute.java, main/src/cgeo/geocaching/utils/IndividualRouteUtils.java
- reset auto-target from individual route on unchecking the auto-target option
- reset auto-target if removing the last point of individual route
=> reset auto-target in certain conditions (rel. to #9281)

main/src/cgeo/geocaching/connector/gc/GCConstants.java, main/src/cgeo/geocaching/connector/gc/GCParser.java, tests/src-android/cgeo/geocaching/CgeoApplicationTest.java
Parse owner for PM only caches, so that it can be used as logging template...
=> parse owner for PM only caches

main/src/cgeo/geocaching/maps/CGeoMap.java
fix #9459: install safeguard in case of null-viewport
=> fix #9459: install safeguard in case of null-viewport

main/src/cgeo/geocaching/settings/SettingsActivity.java
rel to #9465: repair wrong parsing of mapsource
=> rel to #9465: repair wrong parsing of mapsource

main/src/cgeo/geocaching/AboutActivity.java, main/src/cgeo/geocaching/utils/DebugUtils.java, main/src/cgeo/geocaching/utils/ShareUtils.java
=> automatically insert support email address if sending logfile

main/src/cgeo/geocaching/ui/CacheListAdapter.java, main/src/cgeo/geocaching/utils/Formatter.java
Format the favorite counter in cache list for caches having > 1000 founds with "1k" etc.
=> format high favorite cache count (fix #9466)

main/res/values/strings.xml, main/src/cgeo/geocaching/utils/SystemInformation.java
- fixes #9104 (optimize overwrite warning)
- fixes #9049 (add backup state to system information)
=> new backup handling - the last one ;-)

main/res/values/preference_keys.xml, main/res/values/strings.xml, main/res/xml/preferences.xml, main/src/cgeo/geocaching/connector/gc/GCConnector.java, main/src/cgeo/geocaching/connector/oc/OCConnector.java, main/src/cgeo/geocaching/models/Geocache.java, main/src/cgeo/geocaching/settings/Settings.java, main/src/cgeo/geocaching/settings/SettingsActivity.java, main/src/cgeo/geocaching/utils/ShareUtils.java
- fix #9419 (make custom tabs configurable)
- use custom tabs also for user context weblink actions
=> custom tabs optimization

main/res/values/strings.xml, main/res/xml/preferences.xml
=> reorganize cache details settings

main/src/cgeo/geocaching/connector/oc/OkapiClient.java, main/src/cgeo/geocaching/sensors/Sensors.java, main/src/cgeo/geocaching/settings/ReceiveMapFileActivity.java
rel to #9488: fix other problems 3, 4 and 5
=> rel to #9488: fix other problems 3, 4 and 5

main/src/cgeo/geocaching/settings/SettingsActivity.java
rel to #8457: remove outdated mapsourcesettings from settingsactivity
=> rel to #8457: remove outdated mapsourcesettings from settingsactivity

main/res/menu/main_activity_options.xml, main/res/values/strings.xml, main/src/cgeo/geocaching/MainActivity.java, main/src/cgeo/geocaching/storage/DataStore.java, main/src/cgeo/geocaching/ui/dialog/Dialogs.java, main/src/cgeo/geocaching/utils/DebugUtils.java, main/src/cgeo/geocaching/utils/ShareUtils.java
rel to #9488: report db problem to user
Changed c:geo code such that in case of fatal db problem user gets an error message asking him to report the problem by sending logfile. Code also makes sure that sending logfile is actually doable even when db is not accessible (this meant to safeguard some of db-using functions esp dbextension)
=> rel to #9488: report db problem to user

main/src/cgeo/geocaching/connector/trackable/GeokretyConnector.java
=> gk: always use CET timezone

main/res/values/themes.xml, main/src/cgeo/geocaching/MainActivity.java, main/src/cgeo/geocaching/settings/Settings.java, main/src/cgeo/geocaching/settings/SettingsActivity.java, main/src/cgeo/geocaching/utils/EnvironmentUtils.java, main/src/cgeo/geocaching/utils/SystemInformation.java
Additionally attempt to switch it off by default on Sailfish OS
Solves the c:geo start problem on Sailfish OS (part of #8752 )
=> Implement transparency through theme selection

main/src/cgeo/geocaching/filter/StoredFilterFactory.java
=> Fix: Filter stored before/after last 30 days doesn't work

main/res/xml/preferences.xml
=> buttonize settings-systems debug buttons

build.gradle, main/build.gradle, main/src/cgeo/geocaching/utils/ShareUtils.java
- Update AndroidX Browser 1.2.0 -> 1.3.0 ([changelog](https://developer.android.com/jetpack/androidx/releases/browser))
- Update AndroidX ExifInterface 1.3.1 -> 1.3.2 ([changelog](https://developer.android.com/jetpack/androidx/releases/exifinterface)) 
- Update GeographicLib-Java 1.50 -> 1.51 (no changelog, but you can use https://winmerge.org/ and compare the sources.jar files)
- Port upstream README changes from mapsme/api-android
- Fix some deprecations
- Use LayoutInflater.from instead of getSystemService where possible
=> Update some libraries, fix some deprecations

main/res/layout/map_settings_dialog.xml, main/src/cgeo/geocaching/maps/MapSettingsUtils.java
=> make map quick settings popup scrollable (fix #9540)

main/src/cgeo/geocaching/MainActivity.java
=> hide all other menu icons when search is active

README.md, mapswithme-api/README.MD
From https://github.com/cgeo/cgeo/pull/9531
Ported README changes from upstream mapsme/api-android.
Fixed a bunch of grammatical issues in regular README and cleaned up its layout. Fixed a bunch of older links.
Also, added the cgeo icon to the README for a little bit of flavor :)
Check out https://github.com/TacoTheDank/cgeo/tree/readme-changes to see how it looks.
=> README changes

main/src/cgeo/geocaching/CacheListActivity.java, main/src/cgeo/geocaching/CachePopupFragment.java, main/src/cgeo/geocaching/MainActivity.java, main/src/cgeo/geocaching/connector/gc/GCLoggingManager.java, main/src/cgeo/geocaching/connector/oc/OkapiLoggingManager.java, main/src/cgeo/geocaching/connector/su/SuLoggingManager.java, main/src/cgeo/geocaching/log/LogTrackableActivity.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/cgeo/geocaching/models/Geocache.java, main/src/cgeo/geocaching/settings/ColorpickerPreference.java, main/src/cgeo/geocaching/utils/ClipboardUtils.java, main/src/cgeo/geocaching/utils/FileUtils.java, main/src/cgeo/geocaching/utils/ProcessUtils.java
From https://github.com/cgeo/cgeo/pull/9531
=> Deprecation fixes and LayoutInflater.from

main/res/values/strings.xml, main/src/cgeo/geocaching/CacheDetailActivity.java, main/src/cgeo/geocaching/EditWaypointActivity.java, main/src/cgeo/geocaching/models/Geocache.java, main/src/cgeo/geocaching/ui/dialog/Dialogs.java
- fixes button labels for `confirmYesNo` dialogs
- adds prefix "Copy of" on waypoint copy from clipboard only if copied to same cache
=> copy waypoint fixes (fix #9407)

main/src/cgeo/geocaching/settings/SettingsActivity.java
fix #9560: fill mapsource values for selection in settings
=> fix #9560: fill mapsource values for selection in settings

main/res/values/strings.xml, main/res/xml/preferences.xml, main/src/cgeo/geocaching/settings/ReceiveMapFileActivity.java, main/src/cgeo/geocaching/settings/SettingsActivity.java, main/src/cgeo/geocaching/storage/PublicLocalFolder.java, main/src/cgeo/geocaching/storage/PublicLocalStorage.java, main/src/cgeo/geocaching/storage/PublicLocalStorageActivityHelper.java, main/src/cgeo/geocaching/ui/dialog/Dialogs.java, main/src/cgeo/geocaching/utils/DebugUtils.java, main/src/cgeo/geocaching/utils/FileNameCreator.java
related to #8457: a days work. Offline Map folder seems to work now in completeness
=> a days work

main/AndroidManifest.xml, main/build.gradle, main/src/cgeo/geocaching/settings/SettingsActivity.java, main/src/cgeo/geocaching/storage/PublicLocalFolder.java, main/src/cgeo/geocaching/storage/PublicLocalStorage.java, main/src/cgeo/geocaching/storage/PublicLocalStorageActivityHelper.java, main/src/cgeo/geocaching/utils/DebugUtils.java, main/src/cgeo/geocaching/utils/FileNameCreator.java, main/src/cgeo/geocaching/utils/MapDownloadUtils.java, main/src/cgeo/geocaching/utils/ShareUtils.java, main/src/cgeo/geocaching/utils/SystemInformation.java
related to #8457: finalize saf for offline maps and logfiles
=> related to #8457: finalize saf for offline maps and logfiles

main/src/cgeo/geocaching/maps/mapsforge/v6/layers/PositionLayer.java
fixes displaying the accuracy circle on OSM maps by replacing the self-drawn circle with the one provided by the Mapsforge lib
=> fix OSM accuracy circle

main/res/values/themes.xml
see https://github.com/cgeo/cgeo/issues/9576#issuecomment-751334802
=> use android:colorAccent in DialogAlert themes

main/res/values/strings.xml, main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/cgeo/geocaching/storage/extension/OneTimeDialogs.java
=> Add OneTimeDialog for map quick settings (fix #9593)

main/AndroidManifest.xml, main/res/layout/install_wizard.xml, main/res/layout/install_wizard_advanced.xml, main/res/layout/install_wizard_footer.xml, main/res/values/strings.xml, main/res/values/strings_not_translatable.xml, main/res/values/styles.xml, main/src/cgeo/geocaching/AboutActivity.java, main/src/cgeo/geocaching/InstallWizardActivity.java, main/src/cgeo/geocaching/MainActivity.java, main/src/cgeo/geocaching/SplashActivity.java, main/src/cgeo/geocaching/permission/PermissionRequestContext.java, main/src/cgeo/geocaching/settings/Settings.java
see #9589 for screenshots etc.
=> Add installation wizard

main/res/values/styles.xml
=> configure splash activity theme to not use activity transitions

main/res/values/colors.xml, main/res/values/preference_keys.xml, main/res/values/strings.xml, main/res/xml/preferences.xml, main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java, main/src/cgeo/geocaching/maps/mapsforge/v6/layers/PositionLayer.java, main/src/cgeo/geocaching/utils/MapLineUtils.java
For consistency (and for being wished for by @MagpieFourtyTwo, IIRC) add color config for accuracy circles as well.
=> make accuracy circle line configurable

main/res/values/strings.xml
see https://github.com/cgeo/cgeo/issues/9589#issuecomment-751450712
=> remove gcvote and geokrety from regular wizard text

main/res/values/preference_keys.xml, main/res/values/strings.xml
(identified by recent lint warnings)
=> remove some unused resources

main/res/values/strings.xml, main/src/cgeo/geocaching/MainActivity.java, main/src/cgeo/geocaching/SelectMapfileActivity.java, main/src/cgeo/geocaching/activity/AbstractActivity.java, main/src/cgeo/geocaching/helper/QueryMapFile.java, main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java, main/src/cgeo/geocaching/settings/Settings.java, main/src/cgeo/geocaching/settings/SettingsActivity.java, main/src/cgeo/geocaching/storage/FolderLocation.java, main/src/cgeo/geocaching/storage/PublicLocalFolder.java, main/src/cgeo/geocaching/storage/PublicLocalStorage.java, main/src/cgeo/geocaching/storage/PublicLocalStorageActivityHelper.java, main/src/cgeo/geocaching/utils/FileNameCreator.java, main/src/cgeo/geocaching/utils/ShareUtils.java, main/src/cgeo/geocaching/utils/SystemInformation.java
rel to 8457: another days work
=> rel to 8457: another days work

main/res/values/strings.xml, main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java, main/src/cgeo/geocaching/settings/ReceiveMapFileActivity.java, main/src/cgeo/geocaching/storage/FolderLocation.java, main/src/cgeo/geocaching/storage/PublicLocalFolder.java, main/src/cgeo/geocaching/storage/PublicLocalStorage.java, main/src/cgeo/geocaching/storage/PublicLocalStorageActivityHelper.java, main/src/cgeo/geocaching/utils/DebugUtils.java, main/src/cgeo/geocaching/utils/ShareUtils.java, main/src/cgeo/geocaching/utils/SystemInformation.java, main/src/cgeo/geocaching/utils/UriUtils.java, tests/src-android/cgeo/geocaching/connector/oc/OkapiClientTest.java, tests/src-android/cgeo/geocaching/storage/PublicLocaStorageTest.java, tests/src/cgeo/geocaching/utils/UriUtilsTest.java
=> cleanup, tests and stuff

main/src/cgeo/geocaching/utils/MapLineUtils.java
see https://github.com/cgeo/cgeo/pull/9601#issuecomment-751510152
=> fix accuracyCircleFillColor typo

main/src/cgeo/geocaching/storage/DataStore.java, main/src/cgeo/geocaching/storage/extension/DBDowngradeableVersions.java, main/src/cgeo/geocaching/storage/extension/FoundNumCounter.java, main/src/cgeo/geocaching/storage/extension/OneTimeDialogs.java, main/src/cgeo/geocaching/storage/extension/PendingDownload.java
For #9468 I need an extra field in the extension table, so I tweaked table and `DBExtension` class a bit.
Also introduces a copy constructor to save some boilerplate code in the derived classes.
=> extend DBExtension

main/src/cgeo/geocaching/storage/DataStore.java
stumbled upon it while working on #9468
=> fix DBExtension.getAll

main/src/cgeo/geocaching/storage/Folder.java, main/src/cgeo/geocaching/storage/FolderUtils.java, main/src/cgeo/geocaching/storage/PublicLocalStorage.java, main/src/cgeo/geocaching/utils/JsonUtils.java, main/src/cgeo/geocaching/utils/UriUtils.java, tests/src-android/cgeo/geocaching/storage/PublicLocalStorageTest.java, tests/src/cgeo/geocaching/utils/UriUtilsTest.java
added unit testing for copyAll
=> added unit tests for copyAll

main/src/cgeo/geocaching/WaypointViewHolder.java, main/src/cgeo/geocaching/list/StoredList.java, main/src/cgeo/geocaching/location/UTMPoint.java, main/src/cgeo/geocaching/log/LogCacheActivity.java, main/src/cgeo/geocaching/log/LogTemplateProvider.java, main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/MapSettingsUtils.java, main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/cgeo/geocaching/maps/mapsforge/v6/caches/GeoitemLayer.java, main/src/cgeo/geocaching/maps/mapsforge/v6/layers/MultiRendererLayer.java, main/src/cgeo/geocaching/models/Geocache.java, main/src/cgeo/geocaching/models/Route.java, main/src/cgeo/geocaching/models/RouteSegment.java, main/src/cgeo/geocaching/sensors/DirectionData.java, main/src/cgeo/geocaching/settings/ColorpickerPreference.java, main/src/cgeo/geocaching/settings/InfoPreferenceMap.java, main/src/cgeo/geocaching/settings/SeekbarPreference.java, main/src/cgeo/geocaching/settings/Settings.java, main/src/cgeo/geocaching/storage/DataStore.java, main/src/cgeo/geocaching/storage/extension/DBDowngradeableVersions.java, main/src/cgeo/geocaching/storage/extension/OneTimeDialogs.java, main/src/cgeo/geocaching/ui/FastScrollListener.java, main/src/cgeo/geocaching/ui/ImageActivityHelper.java, main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateDialog.java, main/src/cgeo/geocaching/utils/BackupUtils.java, main/src/cgeo/geocaching/utils/ContextLogger.java, main/src/cgeo/geocaching/utils/LogWriter.java
Do some code cleanup:
- add missing "final" keywords
- remove some unneeded temporary vars
- move some class level members to local vars
- simplify some if statements
- change some instance calls to static methods to direct calls
- remove some unnecessary explicit String conversion
(to be continued)
=> code cleanup

main/res/values/strings.xml, main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java, main/src/cgeo/geocaching/settings/SettingsActivity.java, main/src/cgeo/geocaching/storage/Folder.java, main/src/cgeo/geocaching/storage/FolderUtils.java, main/src/cgeo/geocaching/storage/PublicLocalFolder.java, main/src/cgeo/geocaching/storage/PublicLocalStorage.java, main/src/cgeo/geocaching/storage/PublicLocalStorageActivityHelper.java, main/src/cgeo/geocaching/utils/DebugUtils.java, main/src/cgeo/geocaching/utils/MapDownloadUtils.java, main/src/cgeo/geocaching/utils/SystemInformation.java, tests/src-android/cgeo/geocaching/storage/PublicLocalStorageTest.java
performance, refactoring publiclocalstorage, allow mutliple defaults
=> performance, refactoring publiclocalstorage, allow mutliple defaults

main/src/cgeo/geocaching/models/Waypoint.java, main/src/cgeo/geocaching/utils/MapMarkerUtils.java, main/src/cgeo/geocaching/utils/TextUtils.java
=> fix NotNull/NonNull/Nullable annotations

main/res/values/strings.xml
Based on feedback of a "new user". 
Feedback and other proposals welcome (you may push to this branch).
=> Related to #9589 - Wording proposals for installation wizard

main/src/cgeo/geocaching/CacheListActivity.java
=> skip PM-only caches on storing

main/src/cgeo/geocaching/settings/Settings.java, main/src/cgeo/geocaching/storage/ConfigurableFolder.java, main/src/cgeo/geocaching/storage/Folder.java, main/src/cgeo/geocaching/storage/FolderStorage.java, main/src/cgeo/geocaching/storage/FolderUtils.java, main/src/cgeo/geocaching/storage/LocalStorage.java, main/src/cgeo/geocaching/storage/PersistedDocumentUri.java, main/src/cgeo/geocaching/utils/DebugUtils.java, main/src/cgeo/geocaching/utils/FileUtils.java, main/src/cgeo/geocaching/utils/Log.java, main/src/cgeo/geocaching/utils/LogWriter.java, main/src/cgeo/geocaching/utils/ShareUtils.java, main/src/cgeo/geocaching/utils/SystemInformation.java, main/src/cgeo/geocaching/utils/UriUtils.java, tests/src-android/cgeo/geocaching/storage/FolderStorageTest.java
document performance, fixing single uri selection, documentation, finishing logfiles
=> document performance, fixing single uri selection, documentation, finishing logfiles

main/build.gradle
=> add Chinese Simplified to supported translations

main/src/cgeo/geocaching/settings/StartWebviewActivity.java, main/src/cgeo/geocaching/utils/ProcessUtils.java, main/src/cgeo/geocaching/utils/ShareUtils.java
As pointed out in https://github.com/cgeo/cgeo/issues/9592#issuecomment-754780054 there might be some more work to be done for #9592. Maybe we should also wait with the release?
=> exclude cgeo from intent chooser

main/src/cgeo/geocaching/maps/AbstractMap.java, main/src/cgeo/geocaching/maps/google/v2/GoogleMapView.java, main/src/cgeo/geocaching/maps/interfaces/MapViewImpl.java
=> directly show distance on 'set as target' in Google Maps (fix #9682)

main/res/values/preference_keys.xml, main/res/values/strings.xml, main/src/cgeo/geocaching/SelectTrackFileActivity.java, main/src/cgeo/geocaching/export/IndividualRouteExport.java, main/src/cgeo/geocaching/files/GPXIndividualRouteImporter.java, main/src/cgeo/geocaching/files/GPXTrackOrRouteImporter.java, main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/MapSettingsUtils.java, main/src/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java, main/src/cgeo/geocaching/maps/interfaces/MapActivityImpl.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/cgeo/geocaching/settings/Settings.java, main/src/cgeo/geocaching/storage/ConfigurableFolder.java, main/src/cgeo/geocaching/storage/ConfigurableFolderStorageActivityHelper.java, main/src/cgeo/geocaching/storage/FolderStorage.java, main/src/cgeo/geocaching/storage/PersistedDocumentUri.java, main/src/cgeo/geocaching/utils/FileNameCreator.java, main/src/cgeo/geocaching/utils/IndividualRouteUtils.java, main/src/cgeo/geocaching/utils/ShareUtils.java, main/src/cgeo/geocaching/utils/TrackUtils.java, main/src/cgeo/geocaching/utils/UriUtils.java, tests/src/cgeo/geocaching/utils/UriUtilsTest.java
migrate track file and indiv route
=> migrate track file and indiv route

main/src/cgeo/geocaching/models/Geocache.java
see https://github.com/cgeo/cgeo/pull/9678#discussion_r552693205 ff
=> tiny adjustments to findWaypoint

main/res/menu/cache_options.xml, main/src/cgeo/geocaching/CacheDetailActivity.java, main/src/cgeo/geocaching/CachePopupFragment.java
As a first step towards https://github.com/cgeo/cgeo/discussions/9692 lets remove the menu entries for store / refresh / remove from cache detail menu.
=> remove duplicated menu entries from cache detail menu

main/src/cgeo/geocaching/activity/AbstractViewPagerActivity.java
=> fix #9710: add npe guards

main/src/cgeo/geocaching/models/Waypoint.java
see https://github.com/cgeo/cgeo/issues/9041#issuecomment-756118022
- include trailheads in numbering for new waypoint names
- fix "*" to "+" in regular expression
=> include trailheads in waypoint numbering

main/src/cgeo/geocaching/utils/MapMarkerUtils.java
see https://github.com/cgeo/cgeo/issues/9685#issuecomment-757126689
=> stay with connector-dependent marker for caches with custom icons

main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/mapsforge/v6/caches/AbstractCachesOverlay.java, main/src/cgeo/geocaching/maps/mapsforge/v6/caches/WaypointsOverlay.java
the "add safeguards" part of #9738 for both NewMap and CGeoMap
=> add safeguards for invalid waypoint coordinates (rel. to #9738)

.github/dependabot.yml
Configure dependabot for the project and the 3 subprojects.
Add ignore entries vor commons-io.
=> add dependabot to c:geo

tests/src-android/cgeo/geocaching/connector/trackable/GeokretyConnectorTest.java
Reverts cgeo/cgeo#9785 as geokrety.org is back online...
=> Revert "temporarily deactivate failing geokrety test until geokrety.org is back"

main/src/cgeo/geocaching/settings/Settings.java, main/src/cgeo/geocaching/storage/ContentStorageActivityHelper.java, main/src/cgeo/geocaching/storage/DocumentContentAccessor.java
fix #9775: migrate previous folder uris
=> fix #9775: migrate previous folder uris

main/src/cgeo/geocaching/maps/google/v2/GoogleMapObjectsQueue.java
- due to #9374 (part 1, only related to Google Maps)
- reopens #9552
=> revert #9565

main/src/cgeo/geocaching/maps/google/v2/GoogleMapObjectsQueue.java
similar to #9565, but limited to accuracy circle objects
=> avoid redrawing accuracy circles (fix #9552)

main/res/layout/coordinates_equations.xml, main/src/cgeo/geocaching/ui/CalculatorVariable.java, main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateDialog.java
Implementing filters for calculator input fields.
=> #9791 setting case in calculator

main/src/cgeo/geocaching/utils/MapMarkerUtils.java
precedence is visited > archived > disabled > regular
=> show disabled/archived status on map also for waypoints (fix #5008)

main/res/values/strings.xml
Some proposals for string improvements/corrections:
- Add articles at places, where they have been omitted while its still a sentence (not only a toast, which should be kept short)
- Try to phrase some operations more understandable for users
- Remove the "See logfile for details" as no normal user would know hoe or where.
=> SAF string improvements

main/res/menu/cache_options.xml, main/res/values/strings.xml
see discussion in https://github.com/cgeo/cgeo/discussions/9692#discussioncomment-288989 / https://github.com/cgeo/cgeo/discussions/9692#discussioncomment-289243
=> restructure cache detail menu

main/src/cgeo/geocaching/maps/mapsforge/v6/layers/PositionLayer.java
=> avoid crash on invalid accuracy radius

main/src/cgeo/geocaching/CompassActivity.java, main/src/cgeo/geocaching/sensors/RotationProvider.java
Hopefully this fix doesn't introduce bugs on other devices, but at least for me everything works fine...
Edit: OK, I have thought again and by logic it should actually work for all devices!
=> fixes incorrect compass rose when turning screen while in upright mode (fix #6829)

main/res/layout/map_settings_dialog.xml, main/res/values/strings.xml, main/src/cgeo/geocaching/maps/MapSettingsUtils.java
Guide the user to the playstore if brouter is not yet installed. For screenshots see https://github.com/cgeo/cgeo/issues/9819#issuecomment-762661620
=> Guide user if brouter is not installed (fix #9819)

main/src/cgeo/geocaching/MainActivity.java
First part of #5407: On long pressing the "stored" icon also offer "history" list.
=> offer history list on main screen long press (rel. to #5407)

main/res/layout/about_changes_page.xml, main/res/layout/about_system_page.xml, main/res/values/styles.xml, main/src/cgeo/geocaching/AboutActivity.java
about:changes:
- enlarge font size from 12sp to 14sp for better readability
- extract styling to `styles.xml`
- change "List of all changes" link to a button
about:system
- applied identical styling to about:system buttons
=> update styling of about:changes / about:system pages

main/src/cgeo/geocaching/InstallWizardActivity.java
related to #9850 (but only a workaround)
=> reset stored external folder on requesting storage permission

main/res/values/strings.xml, main/res/xml/preferences.xml
- deletes two string resources no longer used (fixes #9860)
- fixes a typo in string resource name
=> fix some string resource issues (fix #9860)

.github/dependabot.yml
try another version numbering for the ignore pattern
=> dependabot optimizing

main/src/cgeo/geocaching/storage/ContentStorageActivityHelper.java
rel to #9889: remove cancel option in dialog after copy move
=> rel to #9889: remove cancel option in dialog after copy move

main/src/cgeo/geocaching/settings/Settings.java, main/src/cgeo/geocaching/storage/ContentStorage.java, main/src/cgeo/geocaching/storage/ContentStorageActivityHelper.java, main/src/cgeo/geocaching/storage/PersistableFolder.java, main/src/cgeo/geocaching/utils/SystemInformation.java, tests/src-android/cgeo/geocaching/storage/ContentStorageTest.java
rel to #9904: better migration handling of legacy values
=> rel to #9904: better migration handling of legacy values

main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java, main/src/cgeo/geocaching/storage/ContentStorage.java, main/src/cgeo/geocaching/storage/DocumentContentAccessor.java, main/src/cgeo/geocaching/utils/FileNameCreator.java, main/src/cgeo/geocaching/utils/OfflineMapUtils.java, tests/src-android/cgeo/geocaching/storage/ContentStorageTest.java
fix 9903: handle selection of Download folder
=> fix #9903: handle selection of Download folder

main/src/cgeo/geocaching/utils/UriUtils.java, tests/src/cgeo/geocaching/utils/UriUtilsTest.java
fix #9809: redesign format of uri display to users
The Leanings from app Signal were incorporated in this one
=> fix #9809: redesign format of uri display to users

main/res/values/strings.xml
Additionally one string shortening as requested in https://crowdin.com/translate/cgeo/162/en-pt#24300
=> Fix #9885 - Use folder instead of directory

main/res/values/strings.xml
only for the remaining strings not covered in #9889
=> use positional strings

build.gradle, main/build.gradle
As needed by #9919:
To use a special commit instead a release it is possible using jitpack.org.
First you have to integrate jitpack as maven source.
On jitpack you must select your commit.
Go to https://jitpack.io/#mapsforge/mapsforge, select commit, an "Get it" from th commit list.
=> use dedicated commit for the mapsforge library

main/res/values/strings.xml, main/res/xml/preferences.xml, main/src/cgeo/geocaching/maps/routing/Routing.java, main/src/cgeo/geocaching/settings/Settings.java
improved logging in the context of working issue_9868
=> merge "show direction" and routing modes (fix #9868)

main/res/values/strings.xml, main/res/values/strings_not_translatable.xml, main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java, main/src/cgeo/geocaching/models/OfflineMap.java, main/src/cgeo/geocaching/settings/AbstractDownloader.java, main/src/cgeo/geocaching/settings/AbstractMapDownloader.java, main/src/cgeo/geocaching/settings/MapDownloadSelectorActivity.java, main/src/cgeo/geocaching/settings/MapDownloaderElevate.java, main/src/cgeo/geocaching/settings/MapDownloaderMapsforge.java, main/src/cgeo/geocaching/settings/MapDownloaderOpenAndroMaps.java, main/src/cgeo/geocaching/settings/ReceiveMapFileActivity.java, main/src/cgeo/geocaching/storage/AbstractContentAccessor.java, main/src/cgeo/geocaching/storage/DocumentContentAccessor.java, main/src/cgeo/geocaching/storage/FileContentAccessor.java, main/src/cgeo/geocaching/utils/FileUtils.java, main/src/cgeo/geocaching/utils/OfflineMapUtils.java
implemented for OpenAndroMaps Elevate theme
It's saved as a zip file, which currently c:geo cannot work with yet, needs an ZipThemeRenderer enabled Mapsforge first to be applied for NewMap.
=> support downloading map theme files

main/src/cgeo/geocaching/storage/ContentStorageActivityHelper.java, main/src/cgeo/geocaching/utils/UriUtils.java, tests/src/cgeo/geocaching/utils/UriUtilsTest.java
See https://github.com/cgeo/cgeo/issues/9872#issuecomment-770776886 as reference...
=> convert file:/// to content:/// Uri so that it can be used as EXTRA_INITIAL_URI

main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
=> set Mapsforge buffer size to default

main/res/values/strings.xml, main/src/cgeo/geocaching/settings/AbstractDownloader.java, main/src/cgeo/geocaching/settings/MapDownloaderOpenAndroMaps.java, main/src/cgeo/geocaching/settings/ReceiveMapFileActivity.java
Last part for #9919: Offer downloading theme file "Elevate.zip" after downloading a map file from OpenAndroMaps (but only if "Elevate.zip" does not yet exist in theme folder).
=> Offer to download theme on OpenAndroMaps map downloads (fix #9919)

main/res/values/strings.xml, main/src/cgeo/geocaching/storage/ContentStorageActivityHelper.java, main/src/cgeo/geocaching/storage/FolderUtils.java
saf: make copying asynchronous and with progress bar
Snapshot of progress bar (this will change rapidly)
Snapshot of copy conclusion dialog
=> saf: make copying asynchronous and with progress bar

main/src/cgeo/geocaching/activity/OAuthAuthorizationActivity.java, main/src/cgeo/geocaching/activity/TokenAuthorizationActivity.java, main/src/cgeo/geocaching/settings/AbstractCredentialsAuthorizationActivity.java
Another step towards the viewbinding migration needed for the next Gradle version (and due to ButterKnife being discontinued). It changes ButterKnife @BindView to Android's viewbindings for the authorization activities.
=> replace ButterKnife w viewbindings for auth activities (rel to #9232)

main/src/cgeo/geocaching/utils/SystemInformation.java
Info grouped into sections:
- Device
- Sensor and location
- Program settings
- Services
- Permissions & paths
=> sort and structure system information (fix #9744)

main/AndroidManifest.xml, main/res/layout/mapdownloader_activity.xml, main/res/layout/mapdownloader_item.xml, main/src/cgeo/geocaching/HandleLocalFilesActivity.java, main/src/cgeo/geocaching/InstallWizardActivity.java, main/src/cgeo/geocaching/downloader/AbstractDownloader.java, main/src/cgeo/geocaching/downloader/AbstractMapDownloader.java, main/src/cgeo/geocaching/downloader/CompanionFileUtils.java, main/src/cgeo/geocaching/downloader/MapDownloadNotificationReceiver.java, main/src/cgeo/geocaching/downloader/MapDownloadSelectorActivity.java, main/src/cgeo/geocaching/downloader/MapDownloaderElevate.java, main/src/cgeo/geocaching/downloader/MapDownloaderMapsforge.java, main/src/cgeo/geocaching/downloader/MapDownloaderOpenAndroMaps.java, main/src/cgeo/geocaching/downloader/MapDownloaderReceiverSchemeMap.java, main/src/cgeo/geocaching/downloader/MapDownloaderReceiverSchemeMapTheme.java, main/src/cgeo/geocaching/downloader/MapDownloaderUtils.java, main/src/cgeo/geocaching/downloader/ReceiveMapFileActivity.java, main/src/cgeo/geocaching/downloader/package-info.java, main/src/cgeo/geocaching/maps/CGeoMap.java, main/src/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java, main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java, main/src/cgeo/geocaching/models/OfflineMap.java, main/src/cgeo/geocaching/settings/InfoPreferenceMap.java, main/src/cgeo/geocaching/settings/SettingsActivity.java
Refactored the several downloader related files into their own package "downloader" to keep them closely together.
=> refactor downloader into own package

main/res/layout/waypoint_popup.xml, main/src/cgeo/geocaching/CacheDetailActivity.java, main/src/cgeo/geocaching/WaypointPopupFragment.java, main/src/cgeo/geocaching/WaypointViewHolder.java, main/src/cgeo/geocaching/log/CacheLogsViewCreator.java, main/src/cgeo/geocaching/log/LogCacheActivity.java, main/src/cgeo/geocaching/log/LogViewHolder.java, main/src/cgeo/geocaching/log/LogsViewCreator.java, main/src/cgeo/geocaching/log/TrackableLogsViewCreator.java
Another step towards the viewbinding migration needed for the next Gradle version (and due to ButterKnife being discontinued). It changes ButterKnife @BindView to Android's viewbindings for the waypoint list, waypoint popup, cache logging and log views.
=> replace ButterKnife for waypoints, logging, log entries (rel. to #9232)

main/src/cgeo/geocaching/CompassActivity.java, main/src/cgeo/geocaching/MainActivity.java, main/src/cgeo/geocaching/StatusFragment.java
Another step towards the viewbinding migration needed for the next Gradle version (and due to ButterKnife being discontinued). It changes ButterKnife @BindView to Android's viewbindings for mainscreen, status and compass activity.
=> replace ButterKnife for mainscreen, status, compass (rel. to #9232)

main/res/xml/preferences.xml, main/src/cgeo/geocaching/settings/Settings.java
as discussed in https://github.com/cgeo/cgeo/issues/9895#issuecomment-774432183 ff
=> make multi-threaded OSM rendering default (rel. to #9895)

main/src/cgeo/geocaching/utils/SystemInformation.java
=> show system locale if no user-defined language is set

main/res/values/strings.xml, main/src/cgeo/geocaching/maps/MapSettingsUtils.java, main/src/cgeo/geocaching/maps/routing/RoutingMode.java, main/src/cgeo/geocaching/utils/SystemInformation.java
=> add textual info for routingmode in map quick settings popup

main/res/layout/map_settings_dialog.xml, main/res/values/styles.xml
see https://github.com/cgeo/cgeo/pull/9968#issuecomment-774707199
=> consistent spacing around map quick settings' headings

main/src/cgeo/geocaching/CacheDetailActivity.java, main/src/cgeo/geocaching/WaypointViewHolder.java, main/src/cgeo/geocaching/log/LogCacheActivity.java, main/src/cgeo/geocaching/log/LogViewHolder.java, main/src/cgeo/geocaching/log/LogsViewCreator.java, main/src/cgeo/geocaching/ui/CacheListAdapter.java, main/src/cgeo/geocaching/ui/TrackableListAdapter.java
Refactor: Simplify and unify viewbinding access in view holders
=> simplify and unify viewbinding access (rel. to #9932)

main/build.gradle, main/res/layout/imageselect_activity.xml, main/res/layout/logtrackable_activity.xml, main/src/cgeo/geocaching/ImageSelectActivity.java, main/src/cgeo/geocaching/SearchActivity.java, main/src/cgeo/geocaching/StatusFragment.java, main/src/cgeo/geocaching/activity/AbstractActivity.java, main/src/cgeo/geocaching/helper/UsefulAppsActivity.java, main/src/cgeo/geocaching/log/LogTrackableActivity.java, main/src/cgeo/geocaching/ui/AbstractViewHolder.java, main/src/cgeo/geocaching/ui/ImageListFragment.java, main/src/cgeo/geocaching/ui/recyclerview/AbstractRecyclerViewHolder.java
(including cleanup and removing dependency)
=> last bunch of migration from ButterKnife to viewbindings (fix #9932)

main/src/cgeo/geocaching/downloader/MapDownloaderUtils.java, main/src/cgeo/geocaching/storage/ContentStorage.java, main/src/cgeo/geocaching/storage/ContentStorageActivityHelper.java, main/src/cgeo/geocaching/storage/Folder.java, main/src/cgeo/geocaching/utils/SystemInformation.java, main/src/cgeo/geocaching/utils/UriUtils.java, tests/src/cgeo/geocaching/utils/UriUtilsTest.java
fix #9963: deactivate folder adjustment, fix uridisplay issue, fix pseudouri problem on windows
This PR effectively removes automatic adjustment of inaccessible public folder uris to default value. This should account for temporarily failing access to those uris.
=> fix #9963: deactivate folder adjustment, fix uridisplay issue, fix pseudouri problem on windows

main/res/values/strings.xml
fix lint error from last cgeo integration build
=> remove unused string

main/res/layout/folder_selection_dialog.xml, main/res/values/strings.xml, main/src/cgeo/geocaching/InstallWizardActivity.java, main/src/cgeo/geocaching/settings/Settings.java, main/src/cgeo/geocaching/storage/ContentStorage.java, main/src/cgeo/geocaching/storage/ContentStorageActivityHelper.java, main/src/cgeo/geocaching/storage/FolderUtils.java
for screenshots see https://github.com/cgeo/cgeo/issues/9872#issuecomment-778605172 etc.
=> rework SAF folder grant workflow (fix #9872)

main/res/layout/imagelist_item.xml, main/res/values/preference_keys.xml, main/res/values/strings.xml, main/src/cgeo/geocaching/ImageSelectActivity.java, main/src/cgeo/geocaching/Intents.java, main/src/cgeo/geocaching/MainActivity.java, main/src/cgeo/geocaching/log/LogCacheActivity.java, main/src/cgeo/geocaching/models/Image.java, main/src/cgeo/geocaching/settings/Settings.java, main/src/cgeo/geocaching/storage/DataStore.java, main/src/cgeo/geocaching/storage/LocalStorage.java, main/src/cgeo/geocaching/ui/ImageActivityHelper.java, main/src/cgeo/geocaching/ui/ImageListFragment.java, main/src/cgeo/geocaching/utils/FileNameCreator.java, main/src/cgeo/geocaching/utils/FileUtils.java, main/src/cgeo/geocaching/utils/ImageUtils.java
This PR is a major change for storing offline log images and tries to fix #9609 and fix #9806.
Description will follow in a comment
=> fix #9609, #9806: scale offline log images on upload only

main/res/values/strings.xml
=> add extra hint about displaying internal storage (fix #9881)

main/src/cgeo/geocaching/settings/Settings.java, main/src/cgeo/geocaching/storage/DataStore.java, main/src/cgeo/geocaching/storage/LocalStorage.java, main/src/cgeo/geocaching/utils/SystemInformation.java
Adds db/file/settings version info to system information
=> Add db/file/settings version info to system information

main/res/values/preference_keys.xml, main/res/values/strings.xml, main/src/cgeo/geocaching/models/Geocache.java, main/src/cgeo/geocaching/network/HtmlImage.java, main/src/cgeo/geocaching/settings/Settings.java, main/src/cgeo/geocaching/storage/LocalStorage.java, main/src/cgeo/geocaching/storage/PersistableFolder.java
fix #9719: migrate spoiler image folder to SAF
=> fix #9719: migrate spoiler image folder to SAF

main/src/cgeo/geocaching/connector/gc/GCConstants.java, main/src/cgeo/geocaching/connector/gc/GCParser.java, tests/src-android/cgeo/geocaching/CgeoApplicationTest.java
see https://github.com/cgeo/cgeo/issues/9150#issuecomment-779318569
IMHO it does not worth to release a new version just because of this small fix. Anyway, if we plan a bugfix-release it's targeted to release branch....
=> replace the last old profile link (fix #9150)

main/res/values/strings.xml
I stumbled upon another false use similar to "click" which is "press". 
So I suggest to also replace "press" by "tap" in our strings
=> Replace press by tap in strings

main/src/cgeo/geocaching/storage/DocumentContentAccessor.java
rel to #9720, saf: fix problem with tempoarary folder permission check
=> rel to #9720, saf: fix problem with tempoarary folder permission check

main/res/values/strings.xml, main/src/cgeo/geocaching/MainActivity.java, main/src/cgeo/geocaching/settings/SettingsActivity.java, main/src/cgeo/geocaching/storage/DataStore.java, main/src/cgeo/geocaching/storage/LocalStorage.java, main/src/cgeo/geocaching/utils/BackupUtils.java, main/src/cgeo/geocaching/utils/Formatter.java, main/src/cgeo/geocaching/utils/ShareUtils.java
My work is nearly done, although it was quite a lot to refactor. 
I took the opportunity to improve some code parts with what I learned about java in the last months (using `Consumer` for example - great stuff!)
I am currently stuck with having no access to the folder that is selected via the tree chooser intent. @eddiemuc Could you take a look at the code, if SAF is used correctly and why the tree chooser doesn't work? Is there something I need to do with the folder before it can be accessed?
Everything else seam to work fine with SAF...
=> migrate backup to SAF

main/src/cgeo/geocaching/InstallWizardActivity.java
On cancellation of folder select in migration wizard (by pressing "back" button several times)
- stay on calling wizard page
- and show a "skip" button
=> adapt wizard's behavior on cancelled folder selection (fix #10030)

main/res/values/preference_keys.xml, main/src/cgeo/geocaching/settings/Settings.java, main/src/cgeo/geocaching/storage/PersistableFolder.java
add map theme folder legacy migration
=> add map theme folder legacy migration

main/src/cgeo/geocaching/maps/mapsforge/v6/RenderThemeHelper.java
quickfix rel to #10070: search subfolders of theme folder too
=> quickfix rel to 10070: search subfolders of theme folder too

main/src/cgeo/geocaching/maps/mapsforge/v6/RenderThemeHelper.java, main/src/cgeo/geocaching/storage/FolderUtils.java
rel to #10070: introduce user display name for map themes.
More details will follow in a comment shortly.
=> rel to #10070: introduce user display name for map themes

main/src/cgeo/geocaching/apps/AbstractLocusApp.java, tests/src/cgeo/geocaching/apps/AbstractLocusAppTest.java
Now I wrote my first test class for Android. :-)
This is a standard JUnit test for the mapping of c:geo CacheType, CacheSize, WaypointType and Cache Attributes to Locus types. 
To get access to private methods for testing the `@VisibleForTesting` was set.
In non test mode the methods has the (default) access modifier `private`.
As result the locus connector got optimized and some bugs/problems fixed.
=> Locus connector test and optimization

main/src/cgeo/geocaching/maps/mapsforge/v6/RenderThemeHelper.java, main/src/cgeo/geocaching/storage/ContentStorage.java, main/src/cgeo/geocaching/storage/LocalStorage.java
fix #10093, rel to #10075: store mapthemes internal and fix npe on theme select
=> fix #10093, rel to #10075: store mapthemes internal and fix npe on theme select

main/src/cgeo/geocaching/maps/mapsforge/v6/RenderThemeHelper.java, main/src/cgeo/geocaching/storage/ContentStorage.java, main/src/cgeo/geocaching/utils/LocalizationUtils.java, main/src/cgeo/geocaching/utils/Log.java
fix #10101: avoid circular errors between Log and ContentStorag
=> fix #10101: avoid circular errors between Log and ContentStorage

main/res/values/changelog_master.xml
The corresponding FAQ entry is not yet existing.
Will take care of that next days (before beta release might occur).
I wanted to keep it as short as possible but
- Provide reason
- Advise to use wizard
- Link to more info (for those interested)
=> Proposal for SAF change message

main/src/cgeo/geocaching/storage/PersistableFolder.java
fix #10131: change default theme folder to (maps)/_themes
=> fix #10131: change default theme folder to (maps)/_themes

main/res/xml/file_provider_paths.xml
rel to #10126: add external app storage to fileprovider paths
=> rel to #10126: add external app storage to fileprovider paths
