main/src/cgeo/geocaching/apps/AbstractLocusApp.java

When exporting geocaches to Locus, some valuable information is lost.
- when waypoints are defined without coordinates, those waypoints aren't exported, causing the loss of the other defined information
- trackables aren't exported
- logs aren't exported.
This patch does export defined waypoints without coordinates, exports the name of trackables (no other information is currently available) and exports the logs.

Export waypoints to Locus when they don't have coordinates

---

main/res/values/strings.xml
main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/sorting/SortActionProvider.java
main/src/cgeo/geocaching/ui/CacheListAdapter.java

fix #4321: Sort by Event is missing in menu
fix #4335: Sorting selector sometimes not prefilled

fix #4321: Sort by Event is missing in menu

---

main/res/layout-land/compass_activity.xml
main/res/layout/compass_activity.xml
main/res/menu/compass_activity_options.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/CompassActivity.java

Discussions in #432 and #3675 as well as frequent reports from users show that:
- the user might not know or understand that the compass has been disabled and that only the GPS will be used for direction;
- the user might forget that they disabled the compass.
This PR, opened for testing, makes the *compass disabled* state transient (instead of saving it into the preferences), and switches to a always-visible toggle on the compass activity.
Please comment on feature and suggest style changes. It might be adapted easily for the `release` branch if needed. I have reused the `attribute_compass_yes` and `attribute_compass_no` strings so as not to require new translations if we decide to add it to the release, it will be changed later for specific strings after the release.

Visual compass state and transient status

---

main/res/values/strings.xml
main/src/cgeo/geocaching/connector/trackable/GeokretyParser.java

If whe only have userid, set the username to the (locally translated)
string "user Id: ####"
Remove unneeded cast user id to GeoKrety type...

Fix #4853: Do not show GK owner as "Unknown" when no information is present

---

main/src/cgeo/geocaching/LogTrackableActivity.java
main/src/cgeo/geocaching/connector/trackable/AbstractTrackableLoggingManager.java
main/src/cgeo/geocaching/connector/trackable/GeokretyLoggingManager.java
main/src/cgeo/geocaching/connector/trackable/TrackableLoggingManager.java

Create a loggingManager.isTrackingCodeNeededToPostNote() function.
Show/hide the tracking code field depending on Trackable properties.

Fix #4833: Write note for GC trackable no longer possible without tracking code

---

main/res/layout/logtrackable_activity.xml

Move the date and time buttons on a separate line.

Fix #4852: Log type field to small when logging a GK

---

main/res/values/strings.xml
main/src/cgeo/geocaching/LogTrackableActivity.java

Rework of the message given to the user.
Remove the toast. Display a Yes/No Dialog.

Fix #4854: Direct users to settings if they try to log a GK without login

---

main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/Intents.java
main/src/cgeo/geocaching/SearchActivity.java
main/src/cgeo/geocaching/TrackableActivity.java
main/src/cgeo/geocaching/connector/trackable/AbstractTrackableConnector.java
main/src/cgeo/geocaching/connector/trackable/TrackableConnector.java

The TrackableActivity try every connector and return the first one matching
the pattern. TravelBugConnector also match GK numbers as Tracking Code search.
This patch limit 'bad' requests made to GC services. It ONLY works if we open
the TrackableActivity from CacheDetailActivity as we know the brand of the
trackable we would open. This is not the case when opening trackableActivity
from the 'search bar', which is good. Issue #4822 still happens in this case.

Fix #4806: GK requests to GC

---

.gitignore

When building cgeo with gradle the file main/usage.txt is generated.
I think it should be ignored like the other generated files.

Ignore generated file (main/usage.txt)

---

send2cgeo/send2cgeo.user.js

I often download a complete search result or the 10 most faved caches in an area. With this modification a new column is added to the search results with a  send2cgeo image as link. Perhaps this feature is useful for a lot of people.

Include send2cgeo into search

---

cgeo-contacts/src/cgeo/contacts/ContactsActivity.java

Shows the "DisplayName" if it is present and not the same
as the foundName in the contact selection dialog.

fix #4655: Show Displayname when selecting contact

---

main/res/values/strings.xml
main/src/cgeo/geocaching/files/AbstractImportThread.java
main/src/cgeo/geocaching/files/GPXImporter.java
main/src/cgeo/geocaching/files/ImportGpxAttachmentThread.java
main/src/cgeo/geocaching/files/ImportGpxFileThread.java
main/src/cgeo/geocaching/files/ImportGpxZipAttachmentThread.java
main/src/cgeo/geocaching/files/ImportGpxZipFileThread.java
main/src/cgeo/geocaching/files/ImportLocAttachmentThread.java
main/src/cgeo/geocaching/files/ImportLocFileThread.java

Hello,
this is a proposal for feature #5246. I tested it with some of the GPX files in "tests\res\raw\".
Please have a look at the change in line 50 of AbstractImportThread.java. I didn't see the SearchResult object being used in the importStepHandler of the GPXImporter class, so I reused the msg.obj field for the "sourceDisplayName".
Can this change be made or are there some other places where the SearchResult object from the msg.obj was used?

Fix #5246: Show file name after cache import

---

main/src/cgeo/geocaching/CacheListActivity.java

Count the caches directly in the database to avoid problems with
filtered lists.

Fix #5312: Count caches in Datastore

---

main/res/values/strings.xml
main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/connector/gc/GCConstants.java
main/src/cgeo/geocaching/connector/gc/GCParser.java
main/src/cgeo/geocaching/files/ImportGpxZipAttachmentThread.java
main/src/cgeo/geocaching/models/PocketQueryList.java

Hi,
I wanted to look into the c:geo src for a long time. Maybe I should have contacted you before hand. But I didn't know if I can make it at all.
There is this issue https://github.com/cgeo/cgeo/issues/4267 which is one I like to have resolved. I used it as an example to get into the code and gave it a try.
Here is what I did:
When downloading the PQ page, it checks the table of downloadable PQs. When the user selects a PQ an option is presented to the user to download and import the PQ as a whole or to view the cache list as before. When the user chose to import it calls the CacheListActivity in the Attachement Mode like when you chose a gpx/zip file from outside of c:geo. The uri is the https URI to geocaching.com. I had to handle this in the getInputStream() method.
What do you think? …

Idea for Issue 4267

---

main/res/values/strings.xml
main/src/cgeo/geocaching/CacheListActivity.java

As discussed in Issue #5377 I enabled the "refresh all" menu item on the "all caches" list.
I added a Dialog with a warning, that this might cause high network traffic. The same Dialog applies for concrete Lists.

Fix #5377: "refresh all" on "all caches" list

---

main/AndroidManifest.xml
main/src/cgeo/geocaching/LogTrackableActivity.java
main/src/cgeo/geocaching/TrackableActivity.java
main/src/cgeo/geocaching/connector/ConnectorFactory.java
main/src/cgeo/geocaching/connector/trackable/AbstractTrackableConnector.java
main/src/cgeo/geocaching/connector/trackable/GeokretyConnector.java
main/src/cgeo/geocaching/connector/trackable/TrackableConnector.java
main/src/cgeo/geocaching/models/Trackable.java

Follow PR#5168
Code has been rebased.
@samueltardieu I've looked again at the call of `getGeocodeFromTrackingCode()`. The call is from `GeokretyConnector.searchTrackable()` which already deal with network calls. On the other side, `GeokretyConnector.searchTrackable()` is in turn called from inside `AppObservable.bindActivity()` in `TrackableActivity`. So I don't think this function is really problematic. May you please deeper look into this PR?

Support links encoded in some GeoKrety QRCode

---

main/res/layout/pocketquery_item.xml
main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/connector/gc/PocketQueryListAdapter.java
main/src/cgeo/geocaching/models/PocketQuery.java

According to the comment from @Bananeweizen at #4267 I made use of the new PocketQueryListActivity to get rid of the awkward dialog.
I made the download icon appear on the right side of the list item, if the pq is downloadable.
A click on the rest of the list item shows the cache list as before. 
No need for the extra dialog anymore.

Improve usability of pq download activity

---

main/src/cgeo/geocaching/EditWaypointActivity.java
main/src/cgeo/geocaching/models/Waypoint.java
main/src/cgeo/geocaching/utils/Formatter.java

Merging new and existing waypoints needs a unique waypoint prefix.

Fixed #5366: add ID to own-waypoints prefix

---

main/src/cgeo/geocaching/connector/gc/GCConnector.java
main/src/cgeo/geocaching/connector/gc/GCConstants.java
main/src/cgeo/geocaching/connector/trackable/TravelBugConnector.java
tests/src-android/cgeo/geocaching/connector/ConnectorFactoryTest.java

The codes do not contain the letters I, L, O, S, and U.

Use more precise regular expressions for GC/TB codes.

---

main/res/layout/cachedetail_description_page.xml
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/ui/DecryptTextClickListener.java
main/src/cgeo/geocaching/ui/IndexOutOfBoundsAvoidingTextView.java

with these changes it's possible to copy, share and translate only parts of description. I removed the separation of short and long description to be able to select both in a single selection.
Testing the new feature I run into https://code.google.com/p/android/issues/detail?id=137509 and https://code.google.com/p/android/issues/detail?id=23381. The workarounds are working fine.

fix #3819 (and #5202): make description text selectable

---

main/src/cgeo/geocaching/network/Network.java

It fixes all POST request without parameter body.
Other examples where this happend: favorites and ignorelist

fix #5477: crash when adding cache to watchlist

---

main/src/cgeo/geocaching/connector/gc/GCParser.java

Handling of empty download PQ table. Checking available table cells and download link.
I don't have an empty download table at the moment. If someone is able to double check, would be good.

fix #5472: error reading pq list, when no downloads available

---

main/src/cgeo/geocaching/storage/DataStore.java

Nested enum types are implicitly static.

Remove redundant static modifier.

---

main/build.gradle
main/res/layout/image_item.xml
main/src/cgeo/geocaching/ui/ImagesList.java

Added an Overlay to the images in the Cachlisting "images" tab if coordinates are available in the image.
Added onClick() and onLongClick() handler to start Navigation.
Unfortunately the Images are parsed twice (first to create the Bitmap and later to read the Exif data). I don't know if this is a problem. I couldn't recognize longer loading times on my device. 
Please test on yours.
If it's a problem maybe we should add a preference to turn it on and off.

fix #5483: show geotagged images on map

---

main/src/cgeo/geocaching/ui/AnchorAwareLinkMovementMethod.java

same fix, now based on release branch. Also removed the no longer needed workaround.

fix #5490: fix selection for LinkMovement enabled TextView

---

main/src/cgeo/geocaching/CacheDetailActivity.java

This restores the 'old' text selection for Andorid 2.3. Partially text selection is only possible for API11 and above. Android 2.3 is API 9 / 10.
I tested this in the emulator since I don't have a real device. Also crosschecked with Android 4.1 emulator where the partial text selection feature was available.

fix #5471: reenable text selection for Android 2.3

---

main/src/cgeo/geocaching/CacheDetailActivity.java

Allow edit and upload of personal cache note if cache has not been saved yet.
Refresh DetailsPage after autosave to default list.

fix #5543, #5546: upload personal note if cache not saved yet

---

main/src/cgeo/geocaching/network/Send2CgeoDownloader.java

The `listId` was not provided to the `Geocache.storeCache()` method, so the cache was not stored on any list.

fix #5564, send2Cgeo download

---

main/src/cgeo/geocaching/maps/CachesOverlay.java

The only possible exception is a NullPointerException but items is never null.

Remove superfluous try block.

---

main/src/cgeo/geocaching/storage/DataStore.java

Add code to cleanupIfNeeded() to also cleanup the caches_lists table.

fix #5583, cleanup non existing caches from lists

---

main/res/values-v19/themes.xml

The attribute android:fitsSystemWindows="true" for the MainActivity styles was the culprit.
See:
https://stackoverflow.com/questions/26599805/android-alert-dialog-not-styled-properly-on-lollipop
I can't see any problems after removing this attribute. I'm on Android 5.1. Should be tested with older versions, too.

fix #5371: dialogs out of shape on MainActivity

---

main/res/layout/main_activity.xml

I had removed the `android:fitsSystemWindows="true"` from the styles file in #5594 to fix the dialogs on MainActivity.
On my device with hardware buttons I couldn't see any drawback without this attribute.
In the [link here](https://stackoverflow.com/questions/26599805/android-alert-dialog-not-styled-properly-on-lollipop) it was mentioned that this attribute might be needed at the layout.xml file. 
So I tried to put it there and tested on Emulator with a device with soft buttons.
It seems to fix this issue.

fix #5614: main activity covering soft buttons

---

main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/CachePopupFragment.java

Temporary List was used instead of Standard List.

fix #5646: store to default list if list selection is disabled

---

main/src/cgeo/geocaching/connector/AbstractConnector.java
main/src/cgeo/geocaching/connector/IConnector.java
main/src/cgeo/geocaching/connector/gc/GCConnector.java
main/src/cgeo/geocaching/connector/trackable/AbstractTrackableConnector.java
main/src/cgeo/geocaching/connector/trackable/TrackableConnector.java
main/src/cgeo/geocaching/connector/trackable/TravelBugConnector.java
tests/src-android/cgeo/watchdog/WatchdogTest.java

Introduce a special test url, which does not redirect
there might be better possibilities, therefore as a PR

Fix watchdog tests for gc.com

---

main/src/cgeo/geocaching/enumerations/LoadFlags.java
main/src/cgeo/geocaching/models/Geocache.java
main/src/cgeo/geocaching/storage/DataStore.java

Removed the LoadFlag.SPOILERS which were introduced in #4633 and causing performance issues in #5536. 
While debugging the Issue #4633 I realized that the Cache was saved twice in the DB. And the second time there were no Spoilers. The code in `DataStore.saveSpoilersWithoutTransaction()` first deletes all existing Spoilers and then inserts the new ones. 
Now I don't delete Spoilers when the Cache currently beeing saved doesn't contain Spoilers (assuming it was not properly loaded). So the Spoilers are kept in the DB and properly loaded in the last Step when the CacheDetailsActivity is loaded again.
One possible downside might be that when the Spoilers where removed completely from geocaching.com and the Cache is refreshed. Then we would keep the old Spoiler(s).

Improves #5536, partly reverts #4633

---

main/res/layout/cachedetail_details_page.xml

This fixes to warnings from lint regarding overlapping due to localized text expansion.

fixes lint warning introduced by #5658

---

main/build.gradle

We need to upgrade to a recent version of the annotations. Butterknife 8.0.0 requires them transitively.
Creating a PR instead of normal commit, since I'm not sure if our slaves can handle the upgrade.

upgrade support annotations to 23.3.0

---

main/res/menu/images_list_context.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/ImagesActivity.java
main/src/cgeo/geocaching/Intents.java
main/src/cgeo/geocaching/TrackableActivity.java
main/src/cgeo/geocaching/ui/ImagesList.java

Geotagged images on the CacheDetailsActivity Images Page have now a new context menu entry "Add waypoint" which adds a new waypoint with the name of the image and its coordinates.

fix #5483 'add waypoint' context menu for geotagged images

---

main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/CachePopupFragment.java

Opening the List selection dialog when "manage" lists button is clicked even though in Settings "Ask for list" is disabled.

fix #5701 manage lists when "Ask for List" is disabled

---

main/src/cgeo/geocaching/CacheDetailActivity.java

In `CacheDetailActivity.onOptionsItemSelected()` several submenus are handled. 
Unfortunately the Sharing Submenu "See all" menu entry had the same Id as the Navigation Submenu "Locus". So Locus Navigation was triggered whenever "See all" was selected in "Share cache".
I don't know why the `NavigationAppFactory.onMenuItemSelected()` was handled in the "default" section of the switch, but I moved it to it's own case, so it's not triggered on other menus.
Issue #5644 is related, but unfortunately not completely fixed by this PR. Locus can now be selected as share target, but it opens an empty Address search Dialog. Other share targets work properly. I guess Locus doesn't understand our text Intent.

fix #5643 share cache "See all" opens Navigation to Locus

---

main/src/cgeo/geocaching/enumerations/LogType.java

This imitates the behavior of the geocaching.com website
that asks the user to confirm "needs maintenance" logs.

Let user confirm "needs maintenance" logs

---

main/src/cgeo/geocaching/filter/StateFilterFactory.java
tests/src-android/cgeo/geocaching/filter/StateDisabledFilterTest.java

I currently cannot test the patch on emulator/device but I hope the fix is quite obvious.

Fix #5734: Do not show archived caches when filtering for disabled ones

---

main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/GpxFileListActivity.java

Somehow the `CacheListActivity.refreshCurrentList()` has no effect when GPX was imported via the `GpxFileListActivity`. A `restartActivity()` was needed.

fix #5745 refresh list after import gpx

---

main/src/cgeo/geocaching/connector/gc/GCConstants.java

I tested a mystery, an event and a webcam cache and they are still identified as found (while GC6HP1Y is not).

Fix #5762: Use more precise found pattern

---

main/src/cgeo/geocaching/CacheDetailActivity.java

Sending an `notifyDataSetChanged()` to the waypoints page after personal note was updated with new waypoints.

fix #5683 update waypoints after personal note change

---

main/src/cgeo/geocaching/connector/gc/GCConnector.java
main/src/cgeo/geocaching/export/FieldnoteExport.java

- Evaluate return value from `exportFieldNotes()`
- Return false on login failure

fix #5141 error message when fieldnote upload fails

---

main/src/cgeo/geocaching/files/GPXImporter.java
main/src/cgeo/geocaching/filter/DistanceFilter.java
main/src/cgeo/geocaching/location/GeopointParser.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

Avoid declaring a variable if it is unreferenced before a possible exit
point.

Fix some codacy issues

---

main/res/values/strings.xml
main/src/cgeo/geocaching/TrackableActivity.java
main/src/cgeo/geocaching/connector/trackable/GeokretyParser.java
main/src/cgeo/geocaching/models/Trackable.java
tests/res/raw/geokret145_xml.xml
tests/res/raw/geokret47496_details_xml.xml
tests/src-android/cgeo/geocaching/connector/trackable/GeokretyParserTest.java

GKM api has been reworked, GK logbook is now available.
Not all available informations could be mapped into current `Trackable` `LogEntry`.
ex:
* comments on logs
* move traveled distance
* Lastlogid/lastmoveid (useful for #4867)
* Cache visit count
Example of full details https://api.gkm.kumy.org/gk/47496/details
Todo: add some unit tests with "complete" xml

Fix #4865: Show logbook of GK trackables

---

main/src/cgeo/geocaching/CacheListActivity.java

Vector documentation: If a thread-safe implementation is not needed, it
is recommended to use ArrayList in place of Vector.

Replace Vector by ArrayList

---

main/res/values/preference_keys.xml
main/res/values/strings.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/apps/navi/NavigationAppFactory.java
main/src/cgeo/geocaching/apps/navi/OsmAndApp.java

This adds the possibility to add a navigation marker to OsmAnd / OsmAnd+ through the navigation menu.
See API description here: [OsmAnd API demo](https://github.com/osmandapp/osmand-api-demo)
Also one small comment error for the "Sygic app" was fixed.

Add OsmAnd as navigation app

---

main/src/cgeo/geocaching/location/GeopointFormatter.java
main/src/cgeo/geocaching/location/GeopointParser.java
main/src/cgeo/geocaching/location/UTMPoint.java
main/src/cgeo/geocaching/ui/CoordinatesFormatSwitcher.java
tests/src/cgeo/geocaching/location/UTMPointConversionTest.java
tests/src/cgeo/geocaching/location/UTMPointFormatTest.java

Extended the `GeopointFormatter` and `CoordinatesFormatSwitcher` to support UTM coords.

fix #1914 include UTM format in cache details

---

main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/storage/DataStore.java

As #4086 might take longer, I'll send a fix for this separately.
When removing an offline log it also sets the `visiteddate` to 0 to remove it from History.

fix #4699 remove cache from history when offline log is deleted

---

main/src/cgeo/geocaching/connector/gc/GCMap.java

Version 2.0.0 of RxJava will prohibit using null values in any
Observable-like as mandated by the reactive streams specfication.

Do not pass null into an Observable-like

---

main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/location/GeopointFormatter.java
tests/src/cgeo/geocaching/location/GeoPointFormatterTest.java

Remove middle dot when copying waypoint coordinates to clipboard.

fix #5998 remove middle dot for waypoints

---

main/src/cgeo/geocaching/location/GeopointFormatter.java
tests/src/cgeo/geocaching/location/DistanceParserTest.java
tests/src/cgeo/geocaching/location/GeoPointFormatterTest.java
tests/src/cgeo/geocaching/location/GeoPointParserTest.java
tests/src/cgeo/geocaching/location/UTMPointConversionTest.java

Removed duplicate Constant `SEPARATOR`.
I first thought about pushing this small improvement directly to master, but decided otherwise.
Not sure about usage of the Constant in `GeoPointFormatterTest`. I replace the hard coded middle dot with the Constant, to be consistent with the other two test methods. But sometimes its better for Unittests to use redundant hard coded values. To ring the bell when someone accidentally changes the Constant.
What do you think?

Removed duplicate SEPARATOR Constant, cleanup of location tests

---

main/src/cgeo/geocaching/CacheListActivity.java

When Caches are refreshed on history list, they should not be put on the default list (additionaly).

fix #5981 refresh on history not put on default list

---

main/res/menu/cache_list_options.xml
main/res/menu/cache_options.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/export/PersonalnoteExport.java

There is a new Export submenu "Personal note" which can be used to mass upload personal notes.
The only issue is the 500 character warning in the original single upload function. Do you think it is necessary here? I could only scan all personal notes and if one of them is > 500 chars add such a message to the user. But I'm not a fan of it.
I'm not sure about the proper case for the word `notes`. We have `Personal notes`, but `Field Notes`. On geocaching.com I can find both version `Field Notes` and `field notes`.

fix #4564 mass upload of personal notes

---

main/src/cgeo/geocaching/connector/gc/GCParser.java
main/src/cgeo/geocaching/models/Geocache.java
main/src/cgeo/geocaching/storage/DataStore.java

When logging the `visiteddate` was set to the current timestamp, but it should be the data/time the user chose in the Log Dialog.

fix #5872 sort order for history

---

main/src/cgeo/geocaching/connector/gc/GCConstants.java

finally the pattern to find the <form> element didn't work anymore. They removed the "name" attribute.

fix #6029 no coords on nearby search

---

main/src/cgeo/geocaching/network/StatusUpdater.java
main/src/cgeo/geocaching/staticmaps/StaticMapsProvider.java

We now have a valid SSL certificate on status.cgeo.org for API calls.

fix #6036: use status.cgeo.org when possible

---

main/src/cgeo/geocaching/storage/DataStore.java

As long as we discuss a proper solution for #5955 I think it would help to see the Geocaches with offline logs (but `visiteddate` == `0`) in the history. These are swallowed right now. It gives the users the possibility to see and delete them manually.

show caches with offline logs to help with #5955

---

main/src/cgeo/geocaching/connector/gc/GCConstants.java
main/src/cgeo/geocaching/connector/gc/GCLogin.java

fixes #6065 in release. Needs to be done differently for master, after @samueltardieu jsoup changes (which I appreciate). This fix shows that Regex parsing of HTML can fail too often.
As suspected some GC profiles don't have a selected default date format. So the Regex fetches an option from another selection later on on the preferences page. 
First I fixed that the Regex to fetch only Date Format patterns, including ones with `&#32;`, and falling back to the default gc custom dateformat when something fails.
There is already the default `MM/dd/yyyy` but c:geo somehow used `dd.MM.yyyy` here, don't know where this comes from.

fix #6065 no logs when parsing gc custom date failed

---

main/res/values/strings.xml

"Drop" was only at two places, "Remove" is more often used and it is matching since those operations don't necessarily "Delete" the cache as it may still be on another list.

Fix #6084 - New wording "Remove"

---

main/src/cgeo/geocaching/loaders/HistoryGeocacheListLoader.java
main/src/cgeo/geocaching/log/LogCacheActivity.java
main/src/cgeo/geocaching/storage/DataStore.java
tests/src-android/cgeo/geocaching/storage/DataStoreTest.java

This is still WIP and I'm still testing it.
Don't know all side effects for saving caches which have `detailed = false`.
Looks a bit awkward, too, when such a Cache is viewed in CacheDetailActivity. I guess this can confuse users. Maybe a visible indication would be necessary that the Cache was not properly loaded and a hit on refresh can solve it.

4086 offline log for unsaved caches

---

main/src/cgeo/geocaching/network/HtmlImage.java

Looks like `onNext(bitmap)` was called with a null `bitmap`, which is not allowed.

fix #6092 crash when refreshing certain caches

---

main/src/cgeo/geocaching/location/Geopoint.java
tests/src/cgeo/geocaching/location/GeoPointFormatterTest.java
tests/src/cgeo/geocaching/location/GeopointTest.java

The latitude and longitude are now stored in micro-degrees. The test
suite has been extended to increase coverage.

fix #6098: do not make rounding errors on fractional parts

---

main/src/cgeo/geocaching/CgeoApplication.java
main/src/cgeo/geocaching/settings/Settings.java
main/src/cgeo/geocaching/settings/SettingsActivity.java
main/src/cgeo/geocaching/utils/OOMDumpingUncaughtExceptionHandler.java

The OkHttp exceptions thrown in background threads are now intercepted
by an UncaughtExceptionHandler.
Also, this handler checks the "debug" settings dynamically rather than
installing or uninstalling itself when they are toggled.
This is part of the fix for #6114.

Do not let uncaught OkHttp exceptions crash the application

---

main/src/cgeo/geocaching/storage/DataStore.java

With this cleanup I could reduce the 68 MB big sqlite file from https://github.com/cgeo/cgeo/issues/6186#issuecomment-270253650 to 48 MB. There were a lot of orphaned records left in the DB.
Adding FK constraints would be a next step.

fix #6226, fix #6129 cleanup orphaned records in db

---

main/src/cgeo/geocaching/AbstractDialogFragment.java
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/CompassActivity.java
main/src/cgeo/geocaching/log/LogCacheActivity.java
main/src/cgeo/geocaching/log/LoggingUI.java
main/src/cgeo/geocaching/models/Geocache.java

Saving the cache was not a problem, but updating the map popup took me quite some time.
Closing the Dialog of the one-click offline log didn't trigger the `onResume()` method of the `CachePopupFragment`. I didn't want to extend the `LoggingUI` with yet another view to update, so I refactored that class and used an `OnDismissListener` which can be provided. With this I could also remove the WeakReference of the `CacheListAdapter.ViewHolder` which was used to perform an update, too.
Maybe @Bananeweizen and/or @samueltardieu can have a quick look if this solution is ok.

fix #6232 one-click offline log does not save cache

---

main/res/values/preference_keys.xml
main/src/cgeo/geocaching/activity/AbstractActivity.java
main/src/cgeo/geocaching/connector/AbstractLogin.java
main/src/cgeo/geocaching/connector/gc/GCLogin.java
main/src/cgeo/geocaching/settings/DiskCookieStore.java
main/src/cgeo/geocaching/settings/Settings.java

Keeping the cookie store separate from the preferences allows not to
backup it with the backup manager.

fix #6259: do not save cookie store with Google

---

main/res/values/strings.xml
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/CachePopupFragment.java
main/src/cgeo/geocaching/list/StoredList.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/settings/Settings.java

This (proposed) change adds a third button on the list selection dialog to preselect the lists from last store.
It add a `fast-store` function on the store buttons triggered by a long press. The `fast-store` uses the last remembered list selection and stores immediately without showing a list selection. It falls back to show the dialog if there are no remembered lists.
The timeout for remembering the lists is removed.
The store menu items don't offer the `fast-store` option, see comment https://github.com/cgeo/cgeo/issues/6189#issuecomment-273444179

fix #6189 fast-store with preselection on long press

---

main/build.gradle
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/activity/AbstractActivity.java
main/src/cgeo/geocaching/location/UTMPoint.java
main/src/cgeo/geocaching/models/Geocache.java
main/src/cgeo/geocaching/models/Waypoint.java
main/src/cgeo/geocaching/storage/DataStore.java
tests/src-android/cgeo/geocaching/connector/gc/GCParserTest.java
tests/src-android/cgeo/geocaching/connector/gc/WaypointsTest.java
tests/src-android/cgeo/geocaching/models/GeocacheTest.java
tests/src-android/cgeo/geocaching/models/WaypointTest.java

Initially I just wanted to change the name of the parsed waypoints from the cache description from "Personal note #" to "Description #" as suggested in  https://github.com/cgeo/cgeo/issues/1249#issuecomment-274693217, but it got a bit more.
I wanted to add this to a UnitTest. Then I stumbled upon the `WaypointTest` class which didn't run. It took a while till I found out it was (accidentally) excluded by disabling the Espresso tests. The exclude pattern was to broad. Then I had to fix the test, because the UTM coordinate parsing caused a false match here. While at it I refactored a bit. Splitting tests, renaming methods to better reflect what they are doing.
Usually I prefer smaller changes, but here I came from one topic to the next.
I hope it's still ok, otherwise please object.
So, …

Waypoint naming when parsing text + unit test

---

main/res/layout/editwaypoint_activity.xml
main/res/layout/waypoint_item.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/EditWaypointActivity.java
main/src/cgeo/geocaching/WaypointViewHolder.java
main/src/cgeo/geocaching/connector/gc/GCParser.java
main/src/cgeo/geocaching/connector/oc/OkapiClient.java
main/src/cgeo/geocaching/enumerations/WaypointType.java
main/src/cgeo/geocaching/models/Geocache.java
main/src/cgeo/geocaching/models/Waypoint.java
main/src/cgeo/geocaching/storage/DataStore.java
tests/src-android/cgeo/geocaching/activity/waypoint/AddWaypointActivityTest.java
tests/src-android/cgeo/geocaching/activity/waypoint/EditWaypointActivityTest.java
tests/src-android/cgeo/geocaching/models/WaypointTest.java

Here is a proposal to change the waypoint storage to preserve local changes.
- Name (title): only editable if it is a user defined waypoint
- Coords: only editable if it is a user defined waypoint or if no coords were present (like finals)
- Note: only editable if it is a user defined waypoint
- User note: new field which is editable for all waypoints and not affected by server side changes
Migration:
Because we don't know which notes were edited locally, here I copy all `notes` into `user_note` and set the `note` to empty. On refresh the `note` field is set to the server side value and compared with the `user_note` field. If identical, the `user_note` field is emptied.
While testing this, it worked good for me. But of course I would like to have some feedback.

fix #5353, fix #6223 waypoint storage

---

main/src/cgeo/geocaching/utils/Formatter.java
main/src/cgeo/geocaching/utils/SystemInformation.java
tests/src-android/cgeo/geocaching/utils/FormatterTest.java

Changed `Log date format` in SystemInformation to `System date format` to make it clear what it is.
Used a cast to SimpleDateFormat to retrieve the data format pattern used.
Backed by a UnitTest.
I also resolved a warning in the `Formatter` class about a possible memory leak because the Context was stored in a static field.

fix #6284 log date format in system information

---

main/src/cgeo/geocaching/models/Geocache.java
tests/src-android/cgeo/geocaching/models/GeocacheTest.java

Scanning the cache description through all patterns and using the one which matches the earliest position in text.

fix #6285 calendar time recognition

---

main/res/layout/editwaypoint_activity.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/EditWaypointActivity.java

If coords are not editable hide the projection fields and offer a dialog to copy the coords to clipboard or duplicate the waypoint.

fix #6292 waypoint projection fields

---

main/src/cgeo/geocaching/models/Geocache.java
tests/src-android/cgeo/geocaching/models/GeocacheTest.java

If coords are only locally changed, the local changes are preserved now. The original coords are updated in the ORIGINAL waypoint.
If coords are changed locally and server side, the server side coords win.

fix #5476 locally changed coords replaced by server coords

---

README.md

opencaching.org.uk redirects to opencache.uk.

Update URL in README file

---

main/src/cgeo/geocaching/storage/DataStore.java

It just partly fixes #6276. It prevents the deletion of the logs we have in the database when the refresh returns an empty list because of an error.
The user should be informed by a Toast that the logs couldn't be updated. But I got lost in RxJava error handling.

#6276 prevent deletion of logs on error

---

main/src/cgeo/geocaching/network/HtmlImage.java

If an <img> tag has no src attribute getDrawable(null) is called.
Thus, we should not throw an exception in this case (and instead
return a transparent 1x1 image).

Fix #6316: Partially revert 59f584e60ab0a62923f3fbb2ee8ea780976c8d71

---

main/src/cgeo/geocaching/connector/gc/GCConstants.java
main/src/cgeo/geocaching/connector/gc/GCParser.java

It's more robust to have a single point of failure.

Fix #6333: Always infer cache id from geocode

---

main/src/cgeo/geocaching/storage/DataStore.java

While working on the local storage I found this wrong pattern. I think this should be corrected right away. The new storage refactoring takes longer.

fixed cache directory pattern

---

main/src/cgeo/geocaching/connector/gc/GCParser.java

If the cache is already stored on the device, we need to override the
cache ID.

Fix #6333: Override cache ID

---

main/src/cgeo/geocaching/CacheDetailActivity.java

Related to b930a5d? @Bananeweizen may you please cross check if this change doesn't break the `RecyclerView` logic ?
Branched from release, merging against master. https://github.com/cgeo/cgeo/wiki/How-to-get-a-bug-fix-into-the-release#procedure-for-direct-committers-who-want-to-work-directly-into-the-main-repository

WIP: Fix #6337: Geokret inventory stay empty

---

build.gradle

This is the most recent version of the gradle build support for Android.
It also requires updating SDK build to 25.0 or better. So it seems
reasonable to take the latest version of SDK build.
If you see local warnings, please also upgrade Android Studio itself to
2.3.
This change probably requires Jenkins nodes to be upgraded.

update to android-gradle 2.3

---

main/build.gradle

Related to Next feature release #6334.
Necessary to build `cgeo-legacy` branch

Declare a new build type - legacy

---

main/res/values/strings.xml

I could not find any string for the caption of the Geocache data section (like e.g. `<string name="init_datadir_title">`. I would like this to be renamed to "Geocache Data Location".
It seems hardcoded right now. Will open a dedicated issue after checking.

Fix #6438 - Improve strings for storage settings

---

main/src/cgeo/geocaching/storage/DataStore.java
main/src/cgeo/geocaching/storage/LocalStorage.java

Added more patterns from other platforms.
Removed pattern matching for orphaned files cleanup (we now have the GeocacheData directory with only cached Data).

fix #6437 add more prefixes to geocache data pattern

---

main/src/cgeo/geocaching/storage/LocalStorage.java

There was already a fallback to the emulated sdcard and internal storage, but there was a null check missing.

fix #6450, #6451 handling of missing sd card

---

main/res/values/strings.xml

For the database location:
The string now refers to "user storage". I did not mention external or internal as it is totally seperate from the possibilities the user has for the geocache data.
Still I kept the remark about "not accessible or removed" as it might still happen - on older devices - that this memory can be removed or disabled. Or the user might even delete the file by accident.
For the geocache date:
Here I refer only to "External storage" and add in parantheses that this might be a real external sd or an emulated external storage (as it happens to be on some devices).
The user will anyhow get more information about the locations if he opens the dialog.

Fix #6470 - Improve wording for storages

---

main/src/cgeo/geocaching/EditWaypointActivity.java

Allow selecting and copying waypoint name and description text for server defined (non-editable) waypoints.

fix #6471 allow copying waypoint description text

---

main/res/values/strings.xml
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/storage/LocalStorage.java

It's not fully fixing the issue, but presenting a warning on startup if the geocache data directory has less then 5 MB of free disk space.
It's only checking this directory because this is the biggest one (with all the images etc.). There could also be a problem with the internal one, but normally there is a warning from the device if it is running low on internal memory.
@Lineflyer please check if this is sufficient for now. Also the wording of the message and the 5 MB threshold.

for #6427 check diskspace on startup

---

main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/ui/dialog/Dialogs.java

Without starting the big rework of the filter(s), here is a proposed solution for this issue:
If a global type filter is active a click on the filter bar is now showing global type filter dialog. A push on the filter icon in the action bar is always showing the Filter Activity. With this solution a user is still able to combine both filters. It's not ideal because the filterbar behaves differently depending on context, but the best I could think of at the moment.

fix #6533 access global type filter in filter bar of cache list

---

main/res/values/changelog_release.xml
main/src/cgeo/geocaching/connector/gc/GCLogin.java

If no language is selected, no option is selected in the language
selection drop-down menu, and first() returns null.

Fix crash if no language has been selected on gc.com site

---

main/src/cgeo/geocaching/CacheListActivity.java

- Deleting the global cachetype filter didn't properly cleanup the filter bar.
- When the list filter was used then the global cachetype filter was always prepended in the filterbar text, resulting in something illogical like: "All Cache Types, Traditional Cache". So I've removed the global cachetype filter when it is `CacheType.ALL`.

#6533 cleanup global type filter in filter bar of cache list

---

main/src/cgeo/geocaching/storage/LocalStorage.java

It might happen, that the gpx export directory setting points to an outdated location (e.g. from a device migration).
If this directory is not available we use the default gpx directory as a fallback.

fix #6560 fallback for gpx export directory

---

main/res/values/strings.xml
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/settings/Settings.java

Showing a dialog on c:geo start when debug mode is active.  Explaining that this can cause instabilities and asking the user to return to normal mode.

fix #6552 confirm debug mode on start

---

main/res/values/changelog_release.xml
main/src/cgeo/geocaching/files/GPXParser.java

Parsing the coordinates is not necessary because we already know their
format in advance. Futhermore, directly parsing the coordinates as
double values also support integer values, which would not be recognized
as valid latitude/longitude by the coordinate parser.

Fix #6573: Parse GPX original coordinates as double values

---

main/src/cgeo/geocaching/calendar/CalendarEntry.java
main/src/cgeo/geocaching/models/Geocache.java
main/src/cgeo/geocaching/sorting/EventDateComparator.java
tests/src-android/cgeo/geocaching/models/GeocacheTest.java

Fixes #6530 - Changed 2 things to improve sorting:
- store calculated value (eventTimeMinutes) so it doesn't need to be recalculated for every compare in EventDateComparator
- store regex-patterns in a static list so they don't have to be evaluated _every time_ for _every cache_

fix #6530 event list sorting improved

---

main/res/menu/cache_list_options.xml
main/src/cgeo/geocaching/CacheListActivity.java

~~As discussed in #6578 hide/show toplevel menu items and enable/disable submenu items.~~
As discussed in https://github.com/cgeo/cgeo/pull/6602#issuecomment-309776332:
Hide menu items not applicable for current list type.
Disable menu items not applicable for current situation.
Except "invert selection" which is only shown in select mode.
Search Result main menu:
Search Result manage caches submenu:
Concrete List main menu:
Concrete List manage caches submenu:
Concrete List manage lists submenu:
Concrete List selection mode:
All caches main menu:
All caches manage lists submenu:
History main menu:
Default list (empty) main menu:
Default list (empty) manage caches submenu:
Default list (empty) manage caches submenu:

fix #6578 hide menu items by list type, disable items by current situation

---

main/res/values/changelog_master.xml
main/src/cgeo/geocaching/sorting/RatingComparator.java

Intended as a basis for discussion.
Not tested yet.

Fix #6606: Use weighted arithmetic mean to sort GCVote ratings

---

main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateDialog.java

It was caused by the 'findAndRemove(...)' method removing previously seen variables from the 'returnList' when it should have only been looking for them.
The method has been renamed 'getVariable(...) and now accepts a Boolean to indicate whether the found variable should be removed or not.

Fixed bug #6655

---

main/src/cgeo/geocaching/ui/CacheListAdapter.java

TextView ellipsis doesn't work with Spannable, which we use for styling disabled and archived caches with strike through and color red. An alternative is to use PaintFlags and TextColor on the TextView.

fix #6670 cache ellipsis with strike through and color

---

main/res/values/changelog_release.xml
main/src/cgeo/geocaching/connector/oc/OkapiClient.java

Parsing the coordinates is not necessary because we already know their
format in advance. Futhermore, directly parsing the coordinates as
double values also support integer values, which would not be recognized
as valid latitude/longitude by the coordinate parser.

Fix #6736: Parse OC coordinates as double values

---

main/src/cgeo/geocaching/connector/oc/OkapiClient.java
main/src/cgeo/geocaching/connector/oc/OkapiService.java

Until we have the the `image_url` in the response of the post image call as mentioned in https://github.com/cgeo/cgeo/issues/6744#issuecomment-333675587, we have to retrieve the log entry and extract the image url from there.

fix #6744 attach oc log image

---

main/src/cgeo/geocaching/connector/gc/GCConnector.java

It changes the result of `GCConnector.searchByGeocode()` in case the page is empty.
The page is empty because it has a 404 http return code.
But I have no idea why this behaviour changed.
The other error I mentioned in #6756 was resolved by a change in the `cgeo.geocaching-preferences.xml` file. I just had to use my own gc userid.

fix #6756 new build error

---

tests/src-android/cgeo/geocaching/files/GPXImporterTest.java

The reason for the duplicate iteration is still unclear to me. However,
by re-using the existing assertion and by creating a copy of the
collection, we should see way less exceptions.

fix #6701: CME in importer tests

---

main/src/cgeo/geocaching/ImageSelectActivity.java
main/src/cgeo/geocaching/Intents.java
main/src/cgeo/geocaching/connector/AbstractLoggingManager.java
main/src/cgeo/geocaching/connector/ILoggingManager.java
main/src/cgeo/geocaching/connector/oc/OkapiLoggingManager.java
main/src/cgeo/geocaching/log/LogCacheActivity.java

Let's just remove this check. We don't warn about downscaling of images by GC either.

fix #6741 remove check of OC rcmd_max_pixels param

---

main/src/cgeo/geocaching/connector/gc/GCConstants.java

Adjust the PATTERN to parse the long description from the page to also catch the new checker.

fix #6787 new checker crashes long description

---

main/src/cgeo/geocaching/network/HtmlImage.java

For scheme relative image URLs it takes the scheme of the geocache connector hostUrl.
If not exist it assumes "https".

fix #6793 handling of scheme relative image urls

---

main/src/cgeo/geocaching/models/Geocache.java
main/src/cgeo/geocaching/models/Waypoint.java
tests/src-android/cgeo/geocaching/models/WaypointTest.java

If there is a local user defined WP and the cache is refreshed with new waypoints from the server with conflicting WP prefixes, the local user defined WP gets a new prefix.
Before the local user defined WP got merged with the server defined one.

fix #6795 reassing wp prefixes on conflict

---

main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateDialog.java

Fixed #6776: Addressed the issue by guarding with 'null checks' rather than identifying the source, but you know, it's a solution.

Fixed #6776: Crashed on Rotation

---

main/res/layout/coordinatesinput_dialog.xml
main/src/cgeo/geocaching/EditWaypointActivity.java
main/src/cgeo/geocaching/models/CalcState.java
main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateDialog.java
main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java

Current data in the calculator notes is simply ignored. Possible data loss for nightly build users! But the calculator variables are still available, so the loss might not be too hard.
It also removes the calculate button from CoordinatesInputDialog when called from NavigateAnyPointActivity, SearchActivity and LogTrackableActivity. That caused a crash.

fix #6715 merge WP userNotes with Calculator notes

---

settings.gradle

Since some builds we see warnings when building a PR, since the
directory is named "cgeo pull request" automatically by Jenkins, which is
now an invalid name in gradle.

avoid gradle warning about root project name

---

main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/command/MoveToListAndRemoveFromOthersCommand.java

I've enabled the copy and move caches menu item for history. 
Now it is possible to copy caches from the History to any concrete list.
Move is a bit special, I decided to remove from all other lists and store it on the new list. You cannot remove it this way from History, because they have still the recent found status or the offline log. But I think it is usefull: imagine you want to move all found caches to a found list.

fix #6811 copy/move caches from history

---

main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/EditWaypointActivity.java

For user defined waypoints, the note is merged with the userNote and the original note be emptied.
Empty note fields get hidden, even for server defined waypoints.
For server defined notes gets preserved. They are not editable but we stripped html. Now html can be preserved.
Html in userNotes is not supported and "<" characters escaped.
This might solve #6791 as well.

fix #6826 remove superfluous waypoint note

---

main/src/cgeo/geocaching/location/GeopointParser.java
tests/src/cgeo/geocaching/location/GeoPointParserTest.java

I'm not up to date whether this PR should be against master or release, so I picked the same base as #6848.

Fix #6802: Use exact matching when parsing latitude/longitude

---

main/src/cgeo/geocaching/CacheListActivity.java

Fix the issue by destroying the initial loader unconditionally.
This listener method is only entered for the CacheListTypes that show the above issue.
Test steps
- Open a cache list of type NEARBY, ADDRESS, POCKET, OWNER, FINDER, KEYWORD, COORDINATE
- "Load more caches" twice to get 60 entries
- Select one of the caches in this list
- Optionally: to make the test deterministic place a breakpoint at the begin of AbstractSearchLoader.loadInBackground(). This makes sure that the two concurrent loaders always execute in the same order (before the fix).
- Leave the selected cache with the "Back" button
Without the fix:
- The breakpoint above hits twice for two different "ModernAsyncTask" threads
- The list shows 40 entries. If no breakpoinnt is used a few retries might be needed to get this …

6870 destroy initial loader when load more caches

---

main/res/values/strings.xml
main/src/cgeo/geocaching/EditWaypointActivity.java
main/src/cgeo/geocaching/location/Geopoint.java
main/src/cgeo/geocaching/models/CalcState.java
main/src/cgeo/geocaching/models/Waypoint.java
main/src/cgeo/geocaching/storage/DataStore.java
tests/src/cgeo/geocaching/location/GeopointTest.java

Adding the confirmation dialog was not an issue. But I saw that the calculator state was not included in the detection of changes in `isWaypointChanged(currentState)`. Adding it was a bigger challenge. 
Long story short I decided to go with the json string to compare before and after. Otherwise I would have to implement a deep copy and compare of this object. 
@S-Bartfast: maybe you can give some feedback here. Better ideas are welcome.
Another issue is the prefill of the coordinates if they are NULL which we want to tackle in #6861. At the moment the user needs to confirm an unsaved change here, even if he didn't change anything on purpose.
Sometimes there is a rounding issue in the Geopoint(Parser) class which results in a failing equals test even if the coords haven't been changed and …

fix #6844 confirm discard wp changes

---

main/res/layout/coordinatesinput_dialog.xml
main/res/layout/editwaypoint_activity.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/EditWaypointActivity.java
main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateDialog.java
main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java

The EditWaypointActivity is not anymore prefilled with the users location. Placeholders are visible on the latitude and longitude buttons.
If the user just wants to have the current location he has to open the CoordsInputDialog once and confirm.
The projection is only enabled if coordinates are set on the waypoint. Otherwise the projection fields are disabled. We can't do a projection from null coordinates.
I've also added a "Clear Coordinates" button on the CoordsInputDialog for convenience.
Invalid coordinates from the Calculator are now forwarded as null to the waypoint. No longer the users location is used in the meantime. This solves #6697 for me. I don't know if someone needs more visual clue.
Unfortunately the "simple" usecases like recording my current position as waypoint or a …

fix #6861 support null coords in waypoints

---

main/res/layout-land/coordinatesinput_dialog.xml
main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java

Simply added the 4th button `Clear coordinates` to the coordinates input landscape layout.
The button texts get more and more truncated now. Anyone with a better idea? A second button row maybe?

fix #6890 npe in coordsinput landscape

---

main/src/cgeo/geocaching/EditWaypointActivity.java
main/src/cgeo/geocaching/NavigateAnyPointActivity.java
main/src/cgeo/geocaching/SearchActivity.java
main/src/cgeo/geocaching/log/LogTrackableActivity.java
main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java

Follow up from #6861.
The CoordinatesInputDialog doesn't show anymore the user location as default. Which was confusing if the calculation was (temporarily) invalid.
Still the CoordinatesInputDialog feels "in the way" if the waypoint is beeing calculated. To be addressed in some other issue.

support for null in coordsinputdialog

---

main/src/cgeo/geocaching/connector/gc/GCConstants.java
main/src/cgeo/geocaching/connector/gc/GCParser.java

As c:geo doesn't know locked status and this is rather seldom I would propose to treat it like archived. Most of the time it superseeds archived anyway (like in the example of this issue). There are exceptions though.

fix #6889 treat locked caches as archived

---

main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java

I tried to fix this, so that no zero padding happens on format switch when there is no input at all in the fields. But padding on input done (check mark). The only fields I left unpadded are the degree fields. I believe these are the only mandatory fields of a coordinate which shouldn't be set to all zeros when left empty.

fix #6898 coords input zero padding

---

main/src/cgeo/geocaching/connector/gc/GCLogin.java

As discussed in #6259 this PR clears the cookies when a GCLogin failure is happening.
I don't know if this finally solves the issue because I cannot reproduce it myself. As users report that it is happening if c:geo wasn't used for quite some time. So we suspect stale session keys in the cookies.

#6259 reset cookies on GCLogin failure

---

main/src/cgeo/geocaching/CacheListActivity.java

Temporary lists didn't offer the "drop" action, even if the list contains stored caches.
This change makes the "drop" action available for temporary lists, like a list created from the map (view as list), if some of the caches are stored. It drops the caches from the device (remove from any list).

fix #5758 and fix #5757 drop from temp list

---

main/src/cgeo/geocaching/EditWaypointActivity.java

We ensure that the cache is saved already in the CacheDetailsActivity before going to the EditWaypointActivity. So this could be removed here.
But if the user selects to update the final coordinates of the cache we still update the save timestamp.

fix #6923 no update of save ts on new wp

---

main/res/values/strings.xml
main/src/cgeo/geocaching/CacheDetailActivity.java

Adds the following cases:
- "about 1 month ago"
- "about %d months ago" (from 2-11 months)
- "over a year ago" (if more than 365 days ago)

fix #6922 stored months/year ago

---

main/src/cgeo/geocaching/models/PersonalNote.java

The fields of the result are unconditionally set again after the removed
pieces of code, therefore the removed code doesn't have any effect on
the result.

remove superfluous code

---

.idea/checkstyle-idea.xml

This should enable a common checkstyle configuration for all users of Android Studio.

enable cgeo checkstyle in IDEA

---

main/src/cgeo/geocaching/log/CacheLogsViewCreator.java
main/src/cgeo/geocaching/ui/UserClickListener.java

This fixes the problem with username in cache logs, and takes care of
the one in trackable logs as well.

fix #6995: use user name as display name when no specific one exists

---

main/src/cgeo/geocaching/log/LogCacheActivity.java

Clear offline log does now also reset the selected report problem, so the offline log gets deleted completely.
There was also a problem when only the report problem was selected, but no logtext, then no log was saved for offline.

fix #7000 clear offline log, resets problem

---

main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

- Implement a ref-counting monitor
- Only clear the bitmap cache if now map is active any more

Fix #6969, App crash on map source change

---

main/res/values/changelog_release.xml
main/src/cgeo/geocaching/connector/gc/GCWebAPI.java

Still not all trackables are shown in LogCacheActivity, but the maximum is increased from 20 to 50.

fix #7068 increase trackables shown

---

main/res/values-el/strings.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/connector/AbstractLoggingManager.java
main/src/cgeo/geocaching/connector/ILoggingManager.java
main/src/cgeo/geocaching/connector/gc/GCLoggingManager.java
main/src/cgeo/geocaching/log/LogCacheActivity.java

Added error handling for trackable and favpoint download when logging.
Those have previously been taken from the log page and are now independent network requests which can fail as well.
Has been based on release (for being able to merge back) but first proposed for master (for testing).
To make this scheme work (again), merge has to be enabled in the project settings as suggested in #7113

Issue 7122

---

main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java
tests/src-android/cgeo/geocaching/connector/su/SUParserTest.java

Also use an appropriate base class for parser tests.

Fix #7161: Move test class into Android-specific test directory

---

main/AndroidManifest.xml
main/res/menu/map_activity.xml
main/res/values/preference_keys.xml
main/res/values/strings.xml
main/res/xml/theme_prefs.xml
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/RenderThemeSettings.java

Implement style menus for appropriate render themes
mainly according to mapsforge sample implementation.

Fix #5964, Support new map-themes with overlays/stylemenus in new map

---

main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

Do not restart on all preference changes,
only on theme-setting related ones

Fix #7200, Map reloading when popup opens

---

main/src/cgeo/geocaching/connector/oc/OkapiClient.java

poi = point of interest = intesting place; this is not a trailhead. Best mapping is "Reference point".
For trailheads, there is the new OC type "trailhead", e.g. in [OP6FEC](https://opencaching.pl/viewcache.php?cacheid=28657).

Update Okapi waypoint types

---

main/src/cgeo/geocaching/connector/gc/GCConstants.java

Seems the page shown to basic members when accessing a PMO cache has changed recently.
The used class item seems to be specific for this page, as I could not find it on other cache pages.
Change is not tested yet. Will test it with debug APK from CI.

Fix #7211 - PMO failure not detected

---

main/res/values/strings.xml
main/src/cgeo/geocaching/ImageSelectActivity.java

instead of a fixed MIME filter of "image/jpeg" set intent filter to "image/*" and check the file chosen by the user for MIME types "image/jpeg", "image/png" and "image/gif" (which are uploadeable for both geocaching.com as well as opencaching.* platforms)

allow jpg, png, gif for log foto uploads (fix #6955)

---

main/src/cgeo/geocaching/enumerations/WaypointType.java
main/src/cgeo/geocaching/files/GPXParser.java
tests/src-android/cgeo/geocaching/enumerations/WaypointTypeTest.java

This is dry-written code; I have no c:geo development environment (yet).
It allows to have the type of GPX child waypoints only in the `<type>` element, instead of redundantly in `<type>` and `<sym>`. Then Garmin and Groundspeak waypoint IDs can coexist in the same file.
(`<sym>` is an original Garmin GPX element, while Groundspeak added the `<type>`.)
Example:
```
<wpt lat="51.11847" lon="17.06827">
...
<sym>Trail Head</sym>
<type>Waypoint|Trailhead</type>
...
</wpt>
```
(Garmin "Trail Head" = Groundspeak "Trailhead")
Such GPX files are now produced by OKAPI at Opencaching.PL/NL/US/RO. Example:
https://opencaching.pl/okapi/services/caches/formatters/gpx?consumer_key=YourConsumerKey&cache_codes=OP601F&alt_wpts=true&ns_ground=true
(Insert your OC.PL consumer key, that you received via …

read child waypoint types from GPX <type>

---

main/res/values/strings.xml
main/src/cgeo/geocaching/maps/routing/Routing.java
main/src/cgeo/geocaching/settings/BrouterThresholdPreference.java

- restrict brouter threshold setting slider to a minimum of one km
- removed the check for zero value in routing routine
- remove mention of "0=disable" in settings string

restrict brouter threshold setting to a minimum of one km (fix #7239)

---

main/res/layout/usefulapps_item.xml

adjust alignment and sizes for useful apps view to not use a full screen's height for each program entry

adjust alignment and sizes for useful apps view (fix #7258)

---

main/res/values/styles.xml
main/src/cgeo/geocaching/activity/Progress.java
main/src/cgeo/geocaching/ui/dialog/CustomProgressDialog.java

fix for #7261 (GPX import dialog looks broken)
add styling to get gpx import dialog back to centered vertically + background non-transparent
It's not yet perfect - button styling differs from the rest of the program -, but at least import dialog works and is readable.

fix for broken GPX import dialog (fix #7261)

---

main/res/layout/popup.xml

Change height of "More details" button on cache popup to fixed height 40dip - the same height as the buttons below (offline refresh, ...)

Change height of "More details" button on cache popup to fixed height (fixes #7252)

---

main/res/layout/fragment_edit_note.xml

fixes #7254: Personal note dialog looks broken
Add "android:gravity="start"" to set the cursor to the first line

Set cursor position to "start" (fixes #7254)

---

main/src/cgeo/geocaching/connector/gc/GCConstants.java

- adapt regex after suggestion from @yoursunny

Fix #7305, Cache description still missing for caches with gc.com checker

---

main/res/xml/file_provider_paths.xml

add root /storage/ to support access to SD card for FileProvider (fix #7255, part two)

additional FileProvider path to support external SD card (fix #7255)

---

main/build.gradle

Update compileSdkVersion to "Google Inc.:Google APIs:24" and appcompat Libraries to '24.2.1'.
Using the old form of compileSdkVersion because of google maps v1 compatibility.
This is the latest version supporting google maps v1.

Update to compileSdkVersion 24 (Fix #7257)

---

main/src/cgeo/geocaching/activity/AbstractActivity.java

added status overlays on cache details page by using MapUtils.getCacheMarker() function

show cache status overlays on cache details page (fix #7004)

---

main/res/layout/addresslist_item.xml
main/src/cgeo/geocaching/address/AddressClickListener.java
main/src/cgeo/geocaching/address/AddressListActivity.java
main/src/cgeo/geocaching/address/AddressListAdapter.java
main/src/cgeo/geocaching/maps/DefaultMap.java
main/src/cgeo/geocaching/maps/MapOptions.java

Extends mainscreen's "search for address" functionality by adding a map icon to the result list. Clicking on this map icon directly leads to a map view, centered at the coordinates given by the clicked search result.

 Add Icon to address search result list to directly jump to map (fix #6400)

---

main/res/values/styles.xml
main/res/values/themes.xml
main/src/cgeo/geocaching/list/StoredList.java

- add theming/styling for AlertDialogs to get c:geo standard buttons as defined in styles
- use this theme for manually created AlertDialogs in StoredList (fix #7342)
- also restores white button text color for other AlertDialog popups (like GPX import, which got changed by fix for #7261)

change alert dialog styling (fix #7342)

---

main/res/values/styles.xml
main/res/values/themes.xml

- restore button borders for search dialog buttons
- but keep buttons on "save list" dialog borderless

restore button borders for search dialog (fix #7356)

---

main/build.gradle

Please doublecheck as described in #7359 whether this is the right file to change minSDK before merging.
I targeted this PR to `release` as I would like to have this change out asap. Android 4.0.x can no longer login and use online functions. A closeout warning has already been given to users since middle of last year.

Fix #7359 - Raise minSDK to Android 4.1 (SDK16)

---

main/res/xml/preferences.xml
main/src/cgeo/geocaching/settings/Settings.java
tests/src-android/cgeo/geocaching/files/GPXImporterTest.java

- settings provider always returns false for "static maps" and "static wp maps" to effectively disable static maps feature
- disable two menu entries in settings => offline data
This is a temporary disabling on purpose, so that we can later decide on either removing google static maps provider completely or replacing it by a different static maps provider.
Release note should mention that we have to disable static maps feature temporarily at least (and with google maps for sure) due to the licensing changes on google side.

temporarily disable static maps feature (fix #7332)

---

main/build.gradle

fix #7358 Icons not clickable on Google map
reset compileSdkVersion and SupportLibraries back to 23 / 23.4.0

make Icons clickable an google maps again

---

main/res/values/themes.xml

values for attributes "text_color" and "button" must be defined to inflate a layout which uses the "button" style (which is what gmap implementation does when creating an AlertDialog with its new styling)

add two attribute values to cgeo_gmap and cgeo_gmap_light themes to fix #7358

---

mapswithme-api/lint.xml

* Task :mapswithme-api:lint FAILED
Ran lint on variant debug: 3 issues found
Ran lint on variant release: 3 issues found
Wrote XML report to file:///C:/StudioProjects/cgeo/mapswithme-api/build/reports/lint-results.xml
* In the xml:
<issue id="LintError" severity="Error" message="Unknown issue id "AndroidGradlePluginVersion", found in C:\StudioProjects\cgeo\mapswithme-api\lint.xml" category="Lint" priority="10" summary="Lint Failure" explanation="This issue type represents a problem running lint itself. Examples include failure to find bytecode for source files (which means certain detectors could not be run), parsing errors in lint configuration files, etc.
These errors are not errors in your own code, but they are shown to make it clear that some checks were not completed.">
</issue> …

Make lint for mapswithme happy

---

.gitignore

add "captures" directory to .gitignore
("captures" directory is used by Android Studio for the Layout Inspector)

add layout captures directory of Android Studio to .gitignore

---

main/src/cgeo/geocaching/connector/ConnectorFactory.java
main/src/cgeo/geocaching/network/StatusUpdater.java

c:geo side of https://github.com/cgeo/cgeo-status/issues/20
Sending new "active_connectors" with comma-separated list of active connectors or empty string, if none.
Mention @samueltardieu 
Fixes #7214

status: add active connectors reporting

---

build.gradle

see https://developer.android.com/studio/releases/gradle-plugin :
3.3.2 (March 2019)
This minor update supports Android Studio 3.3.2 and includes various bug fixes and performance improvements. To see a list of noteable bug fixes, read the related post on the Release Updates blog.

Update gradle for AS 3.3.2

---

main/build.gradle
tests/src-android/cgeo/geocaching/location/GeopointAndroidTest.java

This enables features such as lambda expressions.

Allow Java 1.8 to be used in cgeo

---

main/res/values/strings.xml

Mapnik is the rendering software, not the style name
The internal names should be adapted, too. But this is not so important.
https://wiki.openstreetmap.org/wiki/Mapnik
Another possible name would be 
Osm:Carto
https://wiki.openstreetmap.org/wiki/Standard_tile_layer
But this would be confusing imo

Changed string osm:mapnik to osm:default

---

main/res/values/styles.xml

rebase progressdialog styling on Theme.Appcompat.Dialog.Alert and set our theme based colors for the attributes

fix styling for progressdialog (fix #7362)

---

main/src/cgeo/geocaching/connector/gc/GCLogin.java

That is slightly faster, even though we will never notice in practice.

use char based index lookup

---

gradle.properties
main/build.gradle

* tasks of type wrapper are deprecated (this is only shown with
--warning-mode all)
* variant.install() is deprecated. This is shown in every build. We can
silence the warning by adding one more indirection towards the new
installProvider()
The compile scope warning is still there and not fixed with this change.

fix gradle warnings

---

main/src/cgeo/geocaching/models/Geocache.java

Images loading was non-blocking leading to incorrect progress report
Fixes #7395
-------------
I'm somehow confused about `return`'s all around, seems like there can be case when wait will not be executed, however worked fine for me, so I assume it's ok...

add wait for images loading

---

main/res/xml/preferences.xml

All resources should use the auto resolution namespace nowadays.

lint: hard-coded package name

---

build.gradle
cgeo-contacts/build.gradle
main/build.gradle
main/proguard-project.txt

Since the switch to gradle 5.x and Java 8 we can again upgrade more
dependencies.

upgrade dependencies

---

build.gradle
main/build.gradle

Gradle is changing from immediate to lazy task creation and
configuration for better performance. This requires new API to be used
in build scripts.
This change converts some of our tasks. Unfortunately, most of the
Android plugins tasks are still created eagerly, so we only avoid a
small number of tasks to be created.

use task avoidance gradle API

---

main/build.gradle

We can upgrade the minor version of butterknife. 9.0.0 would require a
higher target however.

upgrade butterknife

---

main/src/cgeo/geocaching/AbstractDialogFragment.java
main/src/cgeo/geocaching/permission/PermissionRequestContext.java

Insert RestartLocationPermissionHandler
Re-assign callback id numbers
This is going to be tricky to test, as there is no direct venue into this code like calling the map from a shortcut. It is used e.g. in cache and waypoint popups

Fix NPE onResume in AbstractDialogFragment, #7466

---

main/res/menu/map_activity.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/PositionHistory.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/HistoryLayer.java
main/src/cgeo/geocaching/storage/DataStore.java

- log trail history to database
- restore when recreating map (implemented for CGeoMap and NewMap)
- menu option to clear history (implemented for CGeoMap and NewMap)
- limit number of trail points in database automatically (cleanup on open db)

make trail history persistent (fix #2958)

---

main/src/cgeo/geocaching/connector/su/SuConnector.java

change abbreviation for geocaching.su to GC.SU (according other sites like OC.DE) from current GCSU

change abbreviation for geocaching.su to GC.SU

---

main/res/drawable-v21/border_straight.xml

API < 21 get fixed color black background, API 22+ background is colored according to ?background_color

for straight_border drawable distinguish between API 21 and earlier (fix #7473)

---

build.gradle
cgeo-contacts/build.gradle
main/build.gradle

Downgrade commons-lang3 back to 3.5 to satisify API < 19 constraints
Requires downgrade of commons-text to 1.1 as well, as higher versions
depend on commons-lang3:3.6+

Fix #7491, Crash when trying to store cache list (Android 4.x)

---

main/res/menu/cache_list_options.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/export/BatchUploadModifiedCoordinates.java

add menu entry on cache list activity to batch upload all modified coords (if connector allows)

batch upload modified coords (fix #7028)

---

main/res/drawable/border_straight_light.xml
main/res/values/styles.xml
main/src/cgeo/geocaching/activity/Progress.java
main/src/cgeo/geocaching/ui/dialog/CustomProgressDialog.java

As I do need to create two xml files for themed drawables anyway, I can skip the parametrized drawable-v21 version.

split border_straight and progressdialog styles into light and dark themes (fix #7492)

---

main/AndroidManifest.xml
main/res/layout/map_google.xml
main/src/cgeo/geocaching/maps/MapProviderFactory.java
main/templates/keys.xml

- making the key placeholder for v2 Google Maps unique allows parallel development for both versions
- also helps with setting up the CI (see #7449)

rename Google Maps key placeholder to maps_api2_key to avoid conflicts with other branches

---

main/res/layout/popup.xml
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/CachePopupFragment.java

non intrusive way to show hint on cache popup:
- hint is not shown initially, but activated by pressing the new hint button
- hint button gets shown only if hint is available
- hint button is a toggle

add hint (+ toggle button for it) to cache popup (fix #7468)

---

main/src/cgeo/geocaching/maps/PositionDrawer.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/HistoryLayer.java

while drawing historytrail: checks distance of two consecutive points and draws line between them only, if their distance is less than 10 km (stored history itself is untouched)

Draw line between two consecutive trail points only up to max distance (fix #7506)

---

gradle.properties

When experimenting with gradle updates I still saw the welcome message on first build with new version. Therefore add a second variant of the property, as found on the Internet.

Disable gradle welcome message

---

main/res/layout/about_starting_page.xml
main/res/values/strings.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/AboutActivity.java
main/src/cgeo/geocaching/MainActivity.java

fix#4263 (1st impression in application is bad)
As before discussed in #7461 now separated the idea for an initial welcome screen.
I have created a "Getting Started" page that is displayed to the user the first time c:geo start after installation.
It is located in the "about c:geo" section, so the user can read it also later.
The initial text is split in 3 section - general, permission and platform information.
This could be extended if necessary, e.g. in German language to https://www.cachewiki.de/wiki/Hauptseite.
To make the cache platforms recognizable to other services, the corresponding section of the services page has been split.
The page is presented before the permissions questions (on map access).

Create a "Getting Started" page to display on first installation

---

main/src/cgeo/geocaching/MainActivity.java

Fix #7558 (About c:geo: "Back Arrow" displays release notes only)
remove false code line (copy/paste errror)
adjust comments

remove false code line (Fix #7558)

---

main/res/values/strings.xml
main/src/cgeo/geocaching/SearchActivity.java
main/src/cgeo/geocaching/connector/ConnectorFactory.java

- checks for any active connector before conducting a search for geocode (fix #7554)
- checks for any active trackable connector before conducting a search for trackables (fix #7555)
and shows a toast after pressing the search button, if none fitting active connector found

check for active connectors before geocode or trackable search (fix #7554) (fix #7555)

---

main/res/values/strings.xml

Do not use line breaks and leading whitespace in resource strings. Those _are_ contained in the resource and lead to visible rendering differences.

Fix layout of Getting Started

---

main/src/cgeo/geocaching/connector/su/SuConnector.java

fix #7535 (missing option to create account for geocaching.su)
@okainov Please be free to change it to api access if possible

create access to gc.su account creation web site

---

main/res/layout/popup.xml
main/src/cgeo/geocaching/CacheDetailActivity.java

"more details" and "hint" buttons in cache popup were slightly misaligned, so lets reuse "hint" button's margin settings and apply them mirroredly to the "more details" button

align more details and hint button to each other

---

main/src/cgeo/geocaching/AboutActivity.java

The subsequent .setData() call overrides the type of the intent.

Simplify intent creation

---

main/src/cgeo/geocaching/connector/trackable/TravelBugConnector.java

Implement `isActive()` for TravelBugConnector (fix #7592) Without implementing this function the connector always was counted as inactive.

implement isActive() for TravelBugConnector (fix #7592)

---

main/src/cgeo/geocaching/AbstractDialogFragment.java
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/models/Geocache.java
main/src/cgeo/geocaching/ui/CacheListAdapter.java

0 is a valid value for number of Favorite points, it should not be a special case
Also fix displaying of caches with unknown fav points as suggested in #7436

do not use 0 as initial fav. point value

---

build.gradle

* android svg meanwhile has a stable release
* google auto service no longer used (removed with invite a friend feature)

remove outdated dependency resolution strategy

---

main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

fix#7484 (Dialog "Store Unsaved" missing button "Last Selection")
- change headline to lists_title, when multi list selection is requestet
- let show "last selected" button (as implementedd in CGeoMap) for storing all or new caches to list(s) from map menu on NewMap

optimize for last selected list when saving caches to lists (fix#7484)

---

main/src/cgeo/geocaching/SearchActivity.java
main/src/cgeo/geocaching/connector/trackable/TravelBugConnector.java

Adding the `isActive()` function in `TravelBugConnector` needed for #7555 triggers side effects in `TravelBugConnector` due to an incomplete implementation of the connector, which leads to #7617.
Thus to be able to release I temporaribly disable the active trackable connector check for the search (which reopens #7555). Check for active geo connectors (#7554) is unharmed.

temporaribly disable check for active trackable connectors due to #7617

---

main/src/cgeo/geocaching/maps/PositionHistory.java

code cleanup: switch functions related to saving / clearing the history trail to/in database from AndroidRxUtils.andThenOnUi to AsyncTask, since the `andThenOnUi` part is not needed

switch to Schedulers.io().scheduleDirect from AndroidRxUtils.andThenOnUi

---

main/src/cgeo/geocaching/maps/AbstractMap.java
main/src/cgeo/geocaching/network/Network.java
main/src/cgeo/geocaching/network/StatusUpdater.java

The result of the checks are known at runtime because we have minSdk 16.

Remove superfluous SDK version checks

---

build.gradle

Update the gradle plugin according to AS 3.4.1
Info: Please let the experimental feature "Only sync the active vatiant" disabled.

gradle plugin update 3.4.1

---

main/res/values/strings.xml
main/res/values/strings_not_translatable.xml
main/src/cgeo/geocaching/network/Send2CgeoDownloader.java
main/src/cgeo/geocaching/settings/RegisterSend2CgeoPreference.java

I only changed the protocol, please double-check before merge if functional changes are needed, but I guess not.
Instead of adapting all translations I only changed the english string as I worked on the Github UI. Still this should invalidate the translations on Crowdin and trigger retranslation. 
If someone has a spare minute, feel free to change all other languages and push to the branch in my repo.

Fix #7636 - Use https for send2cgeo

---

main/res/layout/map_google.xml
main/res/layout/map_mapsforge.xml
main/res/layout/map_mapsforge_v6.xml
main/res/layout/map_progressbar.xml
main/res/values/styles.xml
main/src/cgeo/geocaching/maps/AbstractMap.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

adds a centered circular progress spinner to CGeoMap and NewMap which is shown while loading caches in live map (and which replaces the no longer supported actionbar based spinner) (fixes #7289)

add horizontal progress spinner to maps (fix #7289)

---

main/res/layout/map_google.xml
main/res/layout/map_mapsforge.xml
main/res/layout/map_mapsforge_v6.xml
main/res/layout/map_progressbar.xml
main/res/values/styles.xml
main/src/cgeo/geocaching/maps/AbstractMap.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

Reverts cgeo/cgeo#7639
Sorry, I reverted this as I was a bit fast with merging and overlooked, that it targeted the `release` branch.
While this is OK generally, I would like to have some more testing time with this one and rather like to have it on `master` only instead (also looking at the hopefully upcoming bugfix release for the OSM tile loading).
@moving-bits 
Can you target your PR to `master` please?
Sorry for the additional effort.

Revert "add horizontal progress spinner to maps (fix #7289)"

---

main/AndroidManifest.xml
main/res/values-ca/strings.xml
main/res/values-ceb/strings.xml
main/res/values-cs/strings.xml
main/res/values-da/strings.xml
main/res/values-de/strings.xml
main/res/values-el/strings.xml
main/res/values-es/strings.xml
main/res/values-fi/strings.xml
main/res/values-fr/strings.xml
main/res/values-hu/strings.xml
main/res/values-it/strings.xml
main/res/values-ja/strings.xml
main/res/values-ko/strings.xml
main/res/values-lt/strings.xml
main/res/values-lv/strings.xml
main/res/values-nb/strings.xml
main/res/values-nl/strings.xml
main/res/values-pl/strings.xml
main/res/values-pt/strings.xml
main/res/values-ro/strings.xml
main/res/values-ru/strings.xml
main/res/values-sk/strings.xml
main/res/values-sl/strings.xml
main/res/values-sv/strings.xml
main/res/values-tr/strings.xml
main/res/values/strings.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/connector/trackable/GeokretyConnector.java
main/src/cgeo/geocaching/settings/Settings.java

fix #7638 (api.geokretymap.org replaced by api.geokrety.org)
- change the references to api.geokretymap.org with api.geokrety.org
- change the text on the geokrety settings page
- AndroidManifest: remove the references to geokretymap.org, integrate into geokrety.org

api.geokretymap.org replaced by api.geokrety.org (fix #7638)

---

main/src/cgeo/geocaching/CacheDetailActivity.java

When pressing the cache popup's hint button: Do show the personal note as well (if given), not just the hint.

extend cache popup's hint view by personal note

---

main/res/layout/map_mapsforge_v6.xml
main/res/values/preference_keys.xml
main/res/values/strings.xml
main/res/values/styles.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/maps/DirectionDrawer.java
main/src/cgeo/geocaching/maps/DistanceDrawer.java
main/src/cgeo/geocaching/maps/PositionAndScaleOverlay.java
main/src/cgeo/geocaching/maps/google/v1/GoogleOverlay.java
main/src/cgeo/geocaching/maps/mapsforge/MapsforgeOverlay.java
main/src/cgeo/geocaching/maps/mapsforge/v6/DistanceView.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/NavigationLayer.java
main/src/cgeo/geocaching/settings/Settings.java

- calculate and display route length on map (in addition to direct distance) (optional) (fix #6017)
- add settings to enable/disable route length calculation and display
(implemented for GoogleMaps v1, Mapsforge v0.3 and NewMap)

optionally calculate and display route length on map (fix #6017)

---

main/src/cgeo/geocaching/connector/trackable/GeokretyConnector.java
main/src/cgeo/geocaching/settings/Settings.java
tests/src-android/cgeo/geocaching/connector/trackable/GeokretyConnectorTest.java

fix #7615 (replace deprecated GKM endpoint by new one)
GeokretyConnector
- getUrlCache() removed
- not more used
- searchTrackable()
- add test
- replace GKM export-details.php by new one
- GK export-details.php as fallback
- searchTrackables()
- replace GKM export2.php by new one
- GK export2.php as fallback
- getTrackableCodeFromUrl()
- finetuning the API call
- getGeocodeFromTrackingCode()
- replace GKM nr2id.php by new one
- some comment add/change/remove
GeokretyConnectorTest
- add tests for getTrackableCodeFromUrl()
Settings
- remove isGeokretyCacheActive()
- not more used

optimize GeokretyConnector

---

main/res/layout/preference_seekbar.xml
main/src/cgeo/geocaching/settings/AbstractSeekbarPreference.java
main/src/cgeo/geocaching/settings/BrouterThresholdPreference.java
main/src/cgeo/geocaching/settings/WpThresholdPreference.java

Extract common functions of BrouterThresholdPreference and WpThresholdPreference to a new AbstractSeekbarPreference and rebase the two on it.
This was actually part of PR 7625, in which a new nonlinear seekbar based on AbstractSeekbarPreference was introduced. Pushing this as separate change, as it is not necessarily bound to PR 7625 and PR 7625 needs to be rethought.

rebase settings using seekbar on new AbstractSeekbarPreference

---

main/res/menu/cache_options.xml
main/res/values/preference_keys.xml
main/res/values/strings.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/AbstractDialogFragmentWithProximityNotification.java
main/src/cgeo/geocaching/CachePopupFragment.java
main/src/cgeo/geocaching/CompassActivity.java
main/src/cgeo/geocaching/WaypointPopupFragment.java
main/src/cgeo/geocaching/location/ProximityNotification.java
main/src/cgeo/geocaching/location/ProximityNotificationByCoords.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/CachesOverlay.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/AbstractCachesOverlay.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/CachesBundle.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/WaypointsOverlay.java
main/src/cgeo/geocaching/settings/AbstractProximityPreference.java
main/src/cgeo/geocaching/settings/ProximityFarPreference.java
main/src/cgeo/geocaching/settings/ProximityNearPreference.java
main/src/cgeo/geocaching/settings/Settings.java

adds two types of proximity notifications:
a) general proximity notification
- available in map view
- checks distance to closest waypoint or cache
- beeps once when closest distance is below threshold (no repeats)
- is reset when distance > threshold
(a) is the "Garmin like" notification variant.)
b) specific proximity notification
- available in compass view and in map popups for cache or waypoint
- checks distance to currently active geopoint (cache / waypoint)
- supports two notification signals, bound to two different distances (far / near)
- sound is repeated after 10s (far) / 5s (near)
- is reset when distance > far threshold
Settings are on Settings => Map => Proximity notification:
- enable / disable general proximity notification
- enable / disable specific proximity …

proximity notifications

---

main/res/values/arrays.xml
main/res/values/preference_keys.xml
main/res/values/strings.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/maps/PositionDrawer.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/HistoryLayer.java
main/src/cgeo/geocaching/settings/Settings.java

make map trail color configurable (fix #7660)
map view:
settings menu: (Map => trail color)
select one of the predefined colors: (grey is default)

make map trail color configurable (fix #7660)

---

main/src/cgeo/geocaching/location/ProximityNotification.java
main/src/cgeo/geocaching/location/ProximityNotificationByCoords.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

general proximity notification changes:
- make general proximity notification parcelable
- ignore one time distance peaks
- use two different distances to play two different tones

general proximity notification changes (followup to #7699)

---

cgeo-contacts/lint.xml
main/lint.xml
main/res/layout-w1200dp/coordinatescalculate_dialog.xml
main/res/layout/authorization_credentials_activity.xml
main/res/layout/authorization_token_activity.xml
main/res/layout/coordinates_input.xml
main/res/layout/coordinatescalculate_dialog.xml

* silence warnings around unused plural versions depending on language (since our translators will do that anyway)
* silence all app indexing warnings, we cannot use app indexing on the geocaching web site
* silence gradle library upgrade warnings in lint, many of those cannot be upgraded with our current target
* add inputtype attributes to text fields

fix some lint warnings

---

main/res/layout/preference_seekbar.xml
main/res/values/strings.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/settings/AbstractProximityPreference.java
main/src/cgeo/geocaching/settings/AbstractSeekbarPreference.java

- move seekbar label to separate line
- move distances configuration above switches for general/specific proximity notifications
- change labels "1" and "2" to "far distance" and "near distance"

reorder menu entries for proximity notification configuration

---

main/src/cgeo/geocaching/maps/mapsforge/v6/caches/CachesBundle.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/WaypointsOverlay.java

getCacheGeocodes() always returned empty collection in wp.getClosestDistanceInM - needed to use getCacheGeocodes() on each overlay instead (base / stored / live overlay)

fix waypoint selection for proximity calculation (NewMap)

---

tests/src-android/cgeo/geocaching/connector/oc/OkapiClientTest.java
tests/src-android/cgeo/watchdog/WatchdogTest.java

Enable watchdog tests and integration tests for opencaching.us
The website should be in normal working state again
To be merged to `release` and upwards to `master` to have watchdog enabled for both branches on CI.

Fix #7676 - Reenable oc.us tests

---

main/res/values/strings.xml
main/src/cgeo/geocaching/utils/SharedPrefsBackupUtils.java

- use cgeo backup folder instead of general download dir
- replace toast messages with dialog boxes
- remove superflous Log.e() messages

put settings backup into cgeo's backup folder (fix #7736)

---

main/build.gradle
main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java
main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapSource.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/DownloadLayer.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/RendererLayer.java

Fixes #7494 
Upgrade Mapsforge to 0.11.0.
Mapsforge 0.9.1 fails on Android 9 with targetSdk 28.
See https://github.com/mapsforge/mapsforge/commit/b7b07619a6389886734acd5bcb8ae9b14dfce8c2 for reference.

Update Mapsforge to 0.11.0

---

main/src/cgeo/geocaching/activity/AbstractActivity.java

On some mobiles, requesting a deprecated indeterminate
progress does not lead to a 'denial', but to a crash instead.
Avoid making the whole app unusable, handle and log the
Exceptions instead.

Mitigate crashes due to #7460

---

main/res/drawable/mark_transparent.xml
main/res/layout/cacheslist_item.xml
main/src/cgeo/geocaching/ui/CacheListAdapter.java
main/src/cgeo/geocaching/utils/MapMarkerUtils.java

Fixes the two causes for ragged display in cache list:
- fix different icon sizes (by calculating inset padding at runtime to respect the actual scaling)
- always reserve space for offline marker in cache list (show transparent marker if needed)
This fix is also a prerequisite for PR #7577.

Fix Icon size in lists different with/without overlay (fix #5193)

---

main/src/cgeo/geocaching/CachePopup.java

Some devices throw an exception when requesting
this window feature for unknown and currently not
reproducible reasons. Catch and log it.
Fixes #7460

Mitigate Runtime exception for some devices

---

main/res/layout/logs_item.xml
main/src/cgeo/geocaching/log/LogViewHolder.java
main/src/cgeo/geocaching/log/TrackableLogsViewCreator.java

Currently the cache name info of trackable logs get cut off, only a small portion is shown. This PR moves the cache information in trackable log list to the main column to give it more space. Cache log list remains unchanged.
currently the list looks like this:
_(see the cache name "TB - Schlosshotel Rasthof Stillhorn" in the log of "michaundkaro" which got cut off to "TB - Schlossh.")_

trackable log list: move gc info to main column to give it more space

---

main/build.gradle
main/res/values/strings.xml
main/src/cgeo/geocaching/apps/AbstractLocusApp.java

fix #7721
build.gradle
- update to locus-api-android:0.3.17 (=latest)
- locus-api is no more a direct prereq, removed
AbstractLocusApp
- Update links
- chage code to make locus-api-android:0.3.17 happy
- Waypoint to Point
- PackWaypoints to PackPoints
- some changes for locus code changes (some java code is now kotlin, minor API changes)
- use the new method sendPacksFile without external storage permission for Locus version greater UPDATE_15
- implement permission checks for older locus installation
- add some Description for Waypoints
- add some c:geo to locus cache type migrations
- add some c:geo to locus (OC) cache size migrations
- sort some parameter
strings.xml
- add text for storage permission message

update the locus connector

---

main/res/values/strings.xml
main/src/cgeo/geocaching/storage/DataStore.java
main/src/cgeo/geocaching/utils/DatabaseBackupUtils.java

Currently c:geo silently fails when restoring a corrupt database. It even displays "restore successful", which, in this case, only means that copying the backup database file has been successful.
This PR changes this behaviour to perform a check after initializing the freshly copied backup file whether the `newlyCreatedDatabase` flag is set, and outputting a warning message if so.

output warning when restore database failed due to corrupt database

---

main/res/layout/waypoint_popup.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/WaypointPopupFragment.java

added a toggle button to the map's waypoint popup:
(label switches from "set visited" to "unset visited" according to current state)

add visit state toggle button to map's waypoint popup (fix #2592)

---

main/res/values/strings.xml
main/src/cgeo/geocaching/filter/FilterRegistry.java
main/src/cgeo/geocaching/filter/ListFilterFactory.java

Related to (but does not fully implement) #7761: Add a list membership filter to be able to use lists as tag replacement.

add list membership filter

---

main/res/menu/cache_list_options.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/export/BatchUploadModifiedCoordinates.java

This is a follow up PR related to the recent discussion in #7028:
Our current method to batch upload coords for caches relies on the internal flag in c:geo for "modified coords", which gets set by either manually storing a waypoint's coords as new final coords in c:geo or by using a GPX import which has the needed GSAK extensions (and data).
This PR adds a separate menu entry to upload the current coords for all / all selected caches.
To upload caches of a GPX without the proper GSAK extensions you can simply import this GPX to a new list and use the new "upload coordinates for all caches" menu entry.

add function to batch upload coords for all (selected) caches

---

main/res/menu/cache_list_options.xml
main/res/values/strings.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/settings/Settings.java

A followup to #7769:
- move "show additional lists" toggle from CacheList dot menu to preferences screen (offline data section)
- set default to true

move 'additional lists' setting to preferences

---

main/src/cgeo/geocaching/maps/mapsforge/v6/caches/CachesBundle.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/CachesOverlay.java

Fixes #7799 
In addition, on non-live maps when icons were switched, the cache markers just vanished. Now they switch correctly.

Fix missing map update on icon switch

---

main/src/cgeo/geocaching/maps/MapProviderFactory.java

Quick fix for Android 10 not supporting Google Maps v1 API by disabling Google Maps on systems running Android 10 (which automatically switches to OSM map provider).

disable Google Maps on Android 10

---

main/src/cgeo/geocaching/maps/mapsforge/v6/caches/CachesBundle.java

Triggers repaint of base overlay and related waypoints, if coming from waypoint popup on a single cache map. Fixes #7812

invalidate base overlay on wp popup from single cache map

---

main/src/cgeo/geocaching/maps/MapProviderFactory.java

We can re-enable Google Maps for Android 10 since the new Google Maps v2 API branch has been merged.

reenable Google Maps on Android 10

---

main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/CachesBundle.java
main/src/cgeo/geocaching/utils/SharedPrefsBackupUtils.java

Fix these 3 warnings:
~~~
\cgeo\main\src\cgeo\geocaching\maps\CGeoMap.java:532: warning: [unchecked] unchecked conversion
mapView = (MapViewImpl) activity.findViewById(mapProvider.getMapViewId());
^
required: MapViewImpl<CachesOverlayItemImpl>
found:    MapViewImpl
\cgeo\main\src\cgeo\geocaching\maps\mapsforge\v6\caches\CachesBundle.java:294: warning: [unchecked] unchecked conversion
Collection<String> baseGeocodes = Collections.EMPTY_LIST;
^
required: Collection<String>
found:    List
\cgeo\main\src\cgeo\geocaching\utils\SharedPrefsBackupUtils.java:78: warning: [unchecked] unchecked conversion
final HashSet<String> ignoreKeys = new HashSet();
^
required: HashSet<String>
found:    HashSet
~~~

fix "lint:unchecked" warnings

---

main/src/cgeo/geocaching/maps/CGeoMap.java

set circle state on GMv2 startup according to settings, if no mapstate is available

---

build.gradle

see  #7653
* Upgrade of supportLibs to version 7.1.1 (according to compileSdk 27)
* Minor other library updates
- com.github.ben-manes:gradle-versions-plugin: 0.24.0 -> 0.25.0
- com.gradle:build-scan-plugin: 2.4.1 -> 2.4.2

Upgrade supportLibs 

---

build.gradle

to fix #7860
The app crash was caused by upgrading the Support Library to the latest 27.x version. (27.1.0)
The last version without this problem is 27.0.2.

downgrade support library

---

main/res/values/strings.xml
main/src/cgeo/geocaching/settings/AbstractSeekbarPreference.java

If multiple format arguments are used, they need positions, otherwise there are new build warnings.

fix String formatting

---

cgeo-contacts/build.gradle
main/AndroidManifest.xml
main/build.gradle
main/res/values/changelog_master.xml
mapswithme-api/build.gradle

changes target SDK to 28 and adds "uses-library org.apache.http.legacy" to make it compilable with Google Maps
does NOT increase compileSDK to 28 as this requires a couple of further changes

set target SDK to 28

---

main/build.gradle
tests/AndroidManifest.xml

fix #7866 
- set minSdk/targetSdk for tests according to installation code
- use library android.test.runner /.base for tests
- update android.gms:play-services-location/play-services-maps

update the test environment in preparation of compileSdk 28 (fix #7866)

---

main/res/menu/map_activity.xml
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

So far compact icon mode has been available to NewMap only. After merging Google Maps v2 this can be extended to Google Maps as well.

extend compact icon mode to Google Maps v2 (fix #7847)

---

main/src/cgeo/geocaching/maps/CGeoMap.java

After the removal of `maps/CachesOverlay.java` during the move from GMv1 to GMv2 general proximity notification did not work for Google Maps any longer. This PR fixes this by adding implementation of and call to `getClosestDistanceInM()`.

fix general proximity notification for Google Maps v2 (fix #7844)

---

main/src/cgeo/geocaching/maps/google/v2/GoogleMapView.java

GMv2 needs a relatively recent Play services version and displays an error message requesting an update instead of the map, if not available. Clicking on that update button triggered an crash of c:geo since the `onSingleTapUp` handler tried to access the map which is not available in this case (=> NPE).

check if map is initialized in tap handler (fixes #7875)

---

main/res/layout/main_activity.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/MainActivity.java

Show a warning if not logged in yet. Message gets hidden automatically as soon as the first geocaching connector was able to log in.

show warning if not logged in yet (fix #7770)

---

main/src/cgeo/geocaching/AbstractDialogFragment.java
main/src/cgeo/geocaching/CacheDetailActivity.java

Fixes #7595
** Description of change: **
Caches that isn't able to have favorite points no longer shows the favorite points on cache details and cache popup. (As far as I know it's only caches of different event types.).
** Screenshot (if applicable): **
Caches with favorite points:
Caches that can't have favorite points:

#7595 Caches of different events don't show favorite points

---

main/AndroidManifest.xml

cleartextTraffic needs to be enabled explicitly as gc.com links uploaded listing images via http and OkHttp disables cleartext traffic by default in newer versions.

allow http connections via AndroidManifest (fix #7889)

---

main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/HistoryLayer.java

Fixes the following regressions and missing pieces for trail history:
- error in trail history routines of our Mapsforge map implementation, which prevented a correct distance calculation and also caused the current position to be connected with the beginning of the trail history
- trail history routines of Google Maps v2 implementation did not respect the maximum distance at all (as well as ignored the trail color setting)

fix some trail history issues (fix #7830)

---

main/src/cgeo/geocaching/connector/gc/GCParser.java

Many stored waypoints have an empty HTML document as note (e.g. opening and closing HTML, head, body tags), since the introduction of JSoup parsing for waypoint notes in commit 81d43038d9edc4a62291d42e596c1dc550a54247. The problem is that even for blank input JSoup returns an HTML document. Instead store an empty note when there is nothing to parse.
For reproduction of the bug, open any cache with a parking place waypoint (e.g. GC8406N) and use "Google Navigation (Driving)". In the upcoming selection dialog all the parking place waypoints have a description starting with "<html>...". The bad note is NOT visible in the waypoints list, however.

fix parsing of empty waypoint notes

---

main/res/values-de/strings.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/MainActivity.java

make 'not logged in' warning clickable (fix #7897)

make 'not logged in' warning clickable (fix #7897)

---

main/src/cgeo/geocaching/activity/ActivityMixin.java

from documentation:
static boolean 	invalidateOptionsMenu(Activity activity)
This method was deprecated in API level 27.1.0. Use invalidateOptionsMenu() directly.

invalidateOptionsMenu(Activity activity) is deprecated

---

main/src/cgeo/geocaching/activity/ActivityMixin.java

(restores 8dca18817c30e / #7903 on branch master)
from documentation:
static boolean 	invalidateOptionsMenu(Activity activity)
This method was deprecated in API level 27.1.0. Use invalidateOptionsMenu() directly.

invalidateOptionsMenu(Activity activity) is deprecated (#7903)

---

main/res/layout/main_activity.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/MainActivity.java

in regard to #7909:
- shorten "not logged in" warning on main screen to make it less obstructive
- tap on this message opens dialog with detailed info; "OK" on dialog leads to service configuration, "cancel" back to main screen
info message if not (yet) logged in:
dialog after tapping on above message:

shorten 'not logged in' info + add dialog to configure services

---

main/res/layout/main_activity.xml
main/src/cgeo/geocaching/MainActivity.java

Fixes #7909
Delay display of "not logged in" info box by 10 seconds.
A successful login switches off the info box.

delay "not logged in" message by 10 seconds (fix #7909)

---

main/res/menu/cache_list_options.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/CacheMenuHandler.java
main/src/cgeo/geocaching/connector/AbstractConnector.java
main/src/cgeo/geocaching/connector/ConnectorFactory.java
main/src/cgeo/geocaching/connector/IConnector.java
main/src/cgeo/geocaching/connector/internal/InternalConnector.java
main/src/cgeo/geocaching/connector/internal/package-info.java
main/src/cgeo/geocaching/enumerations/CacheType.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/models/Geocache.java
main/src/cgeo/geocaching/storage/DataStore.java

This PR introduces an internal geocache connector which allows the user to create their own caches.
- create new cache by long clicking on map (or using the menu entry "manage cache" -> "create user defined cache")
- caches are created with "ZZ" prefix and a consecutive number
- cache type is "user defined cache"
- cache name is editable (for this connector only)
- certain fields are empty (eg: attributes, d/t rating, favorite points)
- cache location is set to map's location you've tapped on (or none, if created via menu)
- cache is assigned to current list (if applicable) or standard list on first saving (can be changed later on)
- further cache handling is similar to regular caches - you can show it on the map,
create waypoints, change coordinates etc.
- cache is completely offline, so …

Allow creation of user defined caches

---

main/res/values/strings.xml
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/connector/internal/InternalConnector.java

Issue #3288 proposes replacing the "go to" menu by a waypoint view. With introduction of the internal connector and user defined caches with #7918 this can be implemented easily now.
Here are some screenshots:
a) After pressing "go to" button on mainscreen a waypoint view of the automatically created user defined cache opens:
(There is only one user defined cache created for all "go to" targets, so if you press "go to" again you will be directed to the same cache. If you delete this cache (which you are perfectly allowed to do) it will be recreated on next run.)
b) Waypoint handling is the same as you're used to:
c) And you may open the compass from waypoint view directly:
(And as this is a regular cache you may swipe to the cache's main page and open navigation and much more.)
Current …

replace go to menu by user defined cache and waypoint page

---

cgeo-contacts/AndroidManifest.xml
cgeo-contacts/build.gradle
cgeo-contacts/res/values/strings.xml
cgeo-contacts/src/cgeo/contacts/ContactsActivity.java
cgeo-contacts/src/cgeo/contacts/permission/PermissionHandler.java
cgeo-contacts/src/cgeo/contacts/permission/PermissionRequestContext.java
main/src/cgeo/geocaching/permission/PermissionRequestContext.java

It was stated in https://github.com/cgeo/cgeo/issues/7582#issuecomment-487609065:
As long as we support Api versions without permission requests, we IMO cannot integrate it
into the main app based on the same arguments we had for the separation initially.
My internal test showed that this is correct.
fixes #7193 (Raise Target SDK to 26 for contacts plugin (or reintegrate into main app))
fixes #7582 (Remove contacts plugin from useful apps list)
-> not remove, but reactivate
- build.gradle based on PR #7236
- adapt PermissionHandler and PermissionRequestContext from main for the contacts need
- inplement contacts permission handling in ContactsActivity
- minor code optimizations (Checkstyle suggestions) in selectContact and getContacts
tested on Android 4.3, 7.0 and 9
The *.apk is located …

Reactivate the contacts plugin (fix #7193)

---

main/src/cgeo/geocaching/utils/CheckerUtils.java

Geochecker URL of gc-apps.com has either changed or never worked with "geochecker" path (receiving a 404 error now), but works with "checker" path, so updated it in c:geo utils class.

update gc-apps.com geochecker url

---

main/res/values/preference_keys.xml
main/res/values/strings.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/maps/google/v2/GoogleMapView.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/settings/Settings.java

Part of #7952:
Longclick on map to create a user defined cache is disabled by default.
Go to settings - map - user defined caches to change this setting.

disable longclick on map to create UDC by default

---

main/res/values/strings.xml
main/src/cgeo/geocaching/connector/internal/InternalConnector.java
main/src/cgeo/geocaching/list/PseudoList.java

part of #7952: Put the pseudo cache created for "goto targets" into its own list instead of standard list. Cache will only be shown if you chose "All caches".
Other user defined caches behave unchanged, will get stored to either the current list (if available) or the standard list.

put goto target user defined cache into its own list

---

main/res/values/strings.xml
main/src/cgeo/geocaching/apps/cachelist/CacheListApps.java

Fixes #7963
removes menu entry cache list - show on map - Mapsforge Beta

remove cache list - show on map - Mapsforge Beta menu entry (fix #7963)

---

main/build.gradle
tests/src-android/cgeo/CGeoTestCase.java

- from 1.5.4 to 1.6.3
- remove call "createApplication();" from CGeoTestCase.setUp()
reason:
java.lang.UnsupportedOperationException: buildAndInstall() should only be called once.
at com.squareup.leakcanary.AndroidRefWatcherBuilder.buildAndInstall(AndroidRefWatcherBuilder.java:89)
at com.squareup.leakcanary.LeakCanary.install(LeakCanary.java:43)
at cgeo.geocaching.CgeoApplication.onCreate(CgeoApplication.java:52)
at android.test.ApplicationTestCase.createApplication(ApplicationTestCase.java:126)
at cgeo.CGeoTestCase.setUp(CGeoTestCase.java:22)
at junit.framework.TestCase.runBare(TestCase.java:132)
at junit.framework.TestResult$1.protect(TestResult.java:115)

update LeakCanary dependency

---

build.gradle

- use version 3.0, for gradle 5.x
- change to plugins{} syntax, also for the other plugins
- change order in build.gradle
because of:
"only buildscript {} and other plugins {} script blocks are allowed before plugins {} blocks, no other statements are allowed
See https://docs.gradle.org/5.6.2/userguide/plugins.html#sec:plugins_block for information on the plugins {} block"

update the gradle build-scan plugin

---

tests/src-android/cgeo/geocaching/CgeoApplicationTest.java

Test error:
~~~
V/InstrumentationResultParser: There was 1 failure:
V/InstrumentationResultParser: 1) testSearchByOwner(cgeo.geocaching.CgeoApplicationTest)
V/InstrumentationResultParser: java.lang.AssertionError:
V/InstrumentationResultParser: Expected size:<8> but was:<9> in:
~~~
Reason:
New mystery cache now by blafoo (GC8G0X7) from 15.11.19.

change CacheNumber on testSearchByOwner

---

main/res/values/strings.xml
main/src/cgeo/geocaching/maps/google/v2/GoogleMapView.java
main/src/cgeo/geocaching/ui/dialog/Dialogs.java

Quick solution if Google Play services are too old to support current Google Maps implementation: Inform the user about version conflict and offer to switch the default map to Mapsforge map provider. User has to manually restart the map activity then.
If user cancelled the info box, she/he can update the Play Services instead.
(fixes #7975)

switch to Mapsforge map provider if Google Play services are too old

---

main/src/cgeo/geocaching/maps/mapsforge/v6/caches/CachesBundle.java

ignore waypoint threshold setting on NewMap
if map is requested for a single cache
(fixes #7948)

ignore waypoint threshold setting on NewMap (fix #7948)

---

tests/src-android/cgeo/geocaching/CgeoApplicationTest.java

In case blafoo starts a 24 day Adventskalender (which would break this test again and again): update testSearchByOwner to use Lineflyer's earthcaches instead (5 caches as of today, all non-PMO)

change testSearchByOwner to use Lineflyer's earth caches

---

main/res/values-ca/strings.xml
main/res/values-ceb/strings.xml
main/res/values-cs/strings.xml
main/res/values-da/strings.xml
main/res/values-de/strings.xml
main/res/values-el/strings.xml
main/res/values-es/strings.xml
main/res/values-fi/strings.xml
main/res/values-fr/strings.xml
main/res/values-hu/strings.xml
main/res/values-it/strings.xml
main/res/values-ja/strings.xml
main/res/values-ko/strings.xml
main/res/values-lt/strings.xml
main/res/values-lv/strings.xml
main/res/values-nb/strings.xml
main/res/values-nl/strings.xml
main/res/values-pl/strings.xml
main/res/values-pt/strings.xml
main/res/values-ro/strings.xml
main/res/values-ru/strings.xml
main/res/values-sk/strings.xml
main/res/values-sl/strings.xml
main/res/values-sv/strings.xml
main/res/values-tr/strings.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapView.java
main/src/cgeo/geocaching/settings/SettingsActivity.java
main/src/cgeo/geocaching/ui/dialog/Dialogs.java
main/src/cgeo/geocaching/utils/MapUtils.java

improve Mapfsforge map version error handling (fix #7801)
- add supported map versions to map loading error message
- display error message as dialog instead of toast
- remove unused "deprecated mf 2.4 version" message

improve Mapfsforge map version error handling (fix #7801)

---

build.gradle
main/build.gradle

- activates Gradle plugin v3.5.3
- adds a workaround to avoid the "Could not find AndroidManifest.xml file using generation folder" error by pointing to AndroidManifext.xml file in gradle config (see https://github.com/androidannotations/androidannotations/issues/2034)
- please review first :-)

update to and workaround for Gradle plugin 3.5.3 (fix #7858)

---

main/src/cgeo/geocaching/maps/mapsforge/MapsforgeCachesList.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/AbstractCachesOverlay.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/CachesBundle.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/WaypointsOverlay.java

throttle distance calculation to prevent NewMap ANR (fix #7923)
on large caches/waypoints lists with activated proximity notification
- uses faster implementation of calculating min distance
- ensures a minimum timespan between two calculations

throttle distance calculation to prevent NewMap ANR (fix #7923)

---

main/res/values/changelog_master.xml
main/res/values/preference_keys.xml
main/res/values/strings.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/maps/google/v2/GoogleMapView.java
main/src/cgeo/geocaching/settings/Settings.java

fixes #7986
Adds menu option "Settings" - "Map" - "Manual rotation" to disable controls for manual rotation of map. (Currently only available for Google Maps v2, as our OSM implementation does not allow rotation at all.)

add option to disable controls for manual map rotation on GMv2

---

main/build.gradle

Fixes trivial gradle script TODO
** Description of change: **
Move all commit ID computation to dedicated class.
** Screenshot (if applicable): **
N/A

Move commit id computation to dedicated gradle class

---

main/src/cgeo/geocaching/apps/AbstractLocusApp.java

Locus is now written in kontlin, therefore chage from
https://github.com/asamm/locus-api/blob/master/locus-api-core/src/main/java/locus/api/objects/geocaching/GeocachingData.java
to
https://github.com/asamm/locus-api/blob/master/locus-api-core/src/main/java/locus/api/objects/geocaching/GeocachingData.kt

for locus integration - change doc ref to kotlin code

---

main/res/menu/map_activity.xml
main/res/values/changelog_master.xml
main/res/values/preference_keys.xml
main/res/values/strings.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java
main/src/cgeo/geocaching/maps/google/v2/GoogleMapView.java
main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
main/src/cgeo/geocaching/maps/interfaces/PositionAndHistory.java
main/src/cgeo/geocaching/maps/mapsforge/MapsforgePositionAndHistory.java
main/src/cgeo/geocaching/settings/Settings.java

Fixes #7507
When bearing between last rotation point and current location reaches +/- 15° map rotates accordingly. Auto rotation is enabled per default, and can be disabled using settings - map - map rotation - disable automatic map rotation.

map auto rotation for Google Maps v2

---

main/res/values/strings.xml
main/src/cgeo/geocaching/apps/AbstractLocusApp.java
main/src/cgeo/geocaching/enumerations/CacheType.java
tests/src/cgeo/geocaching/enumerations/CacheTypeTest.java

Fixes #8010
Add config to detect caches of the type "Locationless (Reverse) Cache" - the once only reintroduced cache type for GCFR0G. As it's probably only a single new cache, I did not created a new symbol for it but reused the "virtual cache" symbol.

add support for locationless cache type (fix #8010)

---

main/res/values/strings.xml

resolve some lint issues by removing unused strings in default locale
(unused strings in other locales will be removed automatically during the next crowdin cycle)

lint resolving: remove unused strings

---

main/res/layout-w1200dp/coordinatescalculate_dialog.xml

Resolve a lint issue by replacing "dp"  with "sp" in layout definition of text field.

lint resolving: use sp instead of dp in layout

---

main/src/cgeo/geocaching/CompassActivity.java
main/src/cgeo/geocaching/ImageSelectActivity.java
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/TrackableActivity.java
main/src/cgeo/geocaching/activity/OAuthAuthorizationActivity.java
main/src/cgeo/geocaching/activity/TokenAuthorizationActivity.java
main/src/cgeo/geocaching/log/LogCacheActivity.java
main/src/cgeo/geocaching/settings/AbstractCredentialsAuthorizationActivity.java
main/src/cgeo/geocaching/settings/InfoPreference.java
main/src/cgeo/geocaching/ui/CompassView.java

Fix a couple of lint issues by adding missing call to super functions of overriden methods.

lint resolving: add missing calls to super methods

---

main/src/cgeo/geocaching/ui/DistanceView.java
main/src/cgeo/geocaching/ui/IndexOutOfBoundsAvoidingTextView.java

Fixes two lint issues by switching from TextView to AppCompatTextView.

lint resolving: switch TextView to AppCompatTextView

---

main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java

set rotation of heading marker according to current map's bearing

adjust heading pointer to map's bearing (fix #8021)

---

main/res/layout/coordinates_input.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java

adjust input hints to available input formats:

adjust input hints to available input formats (fix #8037)

---

main/src/cgeo/geocaching/location/Viewport.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/google/v2/GoogleMapView.java
main/src/cgeo/geocaching/maps/interfaces/MapViewImpl.java
main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapView.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/storage/DataStore.java

If a map gets opened from a single cache: Set initial zoom level on map to include all of cache's waypoints (fixes #7949)

set initial zoom level on cache map to include its waypoints (fix #7949)

---

main/project/localization/findmissingtranslations.sh
main/project/localization/readme.txt

fix #8050
- add readme
- fix: findmissintraslations does not work with languages whose abbreviation is longer than 2 characters
- add as known false positives in readme (wont fix): findextratranslations finds 2 entries that are correct and therefore should not have been found

localization scripts (folder) optimization

---

main/src/cgeo/geocaching/storage/DataStore.java

As last step for our move to replace the old "go to" functionality by waypoints of a user defined cache this PR migrates the most recent "go to" targets into waypoints of UDC ZZ0 (up to 5 targets).
Table "cg_search_destination_history" is no longer used after that migration and therefore deleted.
Schema version gets pushed by 1, thus after this PR you cannot revert to an older version of c:geo (without having a proper backup of your database).

migrate history of up to 5 "go to" targets

---

main/res/values/strings.xml
main/src/cgeo/geocaching/maps/MapProviderFactory.java
main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/MultiRendererLayer.java

Added a new map source that displays a combination of all map files available in the map file directory. This allows users to download less map data if they just need several states or a few countries combined.
The screenshot shows my LiveMap with a map from Denmark and Germany showing simultaneously.
`OfflineMultiMapSource.getFileName()` is a bit rough but there don't seem to be any downsides to just returning the first map files name.

Allow the user to display a combination of all available offline map files

---

main/src/cgeo/geocaching/maps/CGeoMap.java

If a cache has no waypoints, the viewport spanned by this cache is just a dot (upper left corner identical to bottom right corner), which leads GMv2 to use world view on `zoomToBounds()`. Precheck for this condition and use the previous zoom instead of `zoomToBounds()` in this condition.

check if viewport is only a dot before zoomToBounds (fix #8068)

---

main/src/cgeo/geocaching/connector/internal/InternalConnector.java
main/src/cgeo/geocaching/list/PseudoList.java
main/src/cgeo/geocaching/storage/DataStore.java

- Create UDC for migrated 'go to' targets during migration
- UDC ZZ0 gets stored in standard list (instead of non visible virtual list)

Create UDC for migrated 'go to' targets during migration (fix #8042, fix #8067)

---

main/AndroidManifest.xml
main/res/xml/shortcuts.xml

Let the user go straight to the Live-Map from their app drawer or home screen.

Add an AppShortcut to directly launch the Live-Map

---

build.gradle

is no more used after switch to AndroidX

remove supportLibraryVersion

---

main/src/cgeo/geocaching/storage/DataStore.java

Second part of #8082: remove migration of "go to" targets from database scheme routines

remove migration of "go to" targets

---

main/build.gradle
main/src/cgeo/geocaching/CgeoApplication.java

Upgrade LeakCanary to version 2 (esp. 2.1).
LeakCanary 2 is a major rewrite. High level changes:
New heap analyzer, reimplemented from scratch to use 10 times less memory (see Shark).
APIs updated to simplify configuration and provide access to the new heap analyzer.
Internals rewritten to 100% Kotlin.
Multiple leaks detected in one analysis, grouped per leak type
The integration is now easier.
<strike>Additionally, the integration in instrumentation tests is activated.</strike>

upgrade LeakCanary

---

main/src/cgeo/geocaching/maps/CGeoMap.java

by uncoupling calculating the viewport center from setting the routing target

fix routing target being unattached (fix #8096) (fix #8111)

---

main/src/cgeo/geocaching/storage/DataStore.java

As mentioned in https://github.com/cgeo/cgeo/issues/8114#issuecomment-581035299 the migrated waypoints are saved in a chronological order newest to oldest. But as new waypoints are always added at the end and waypoint page currently does not sort by age, waypoint page lists them as 5 - 4 - 3 - 2 - 1 - 6 - 7 ...
This PR reverses the saving order for the migrated goto targets, so that the oldest migrated element gets saved first, then the second oldest and so forth.

Reverse migration create order

---

cgeo-contacts/build.gradle
cgeo-contacts/lint.xml
main/build.gradle
main/lint.xml
tests/lint.xml

- lint
- activate check GradleDependency, because we are "up do date" with targetSdk 28 and should be aware f outdated dependencies
- activate check GradleOverrides, this is ok with changes for targetSdk 28
- activate check InvalidPackage, no such problem is known
- dependencies
- set some "noinspection OldTargetApi" for dependencies that cannot yet be updated
- remove deactivated block for com.jakewharton.espresso:espresso . This project is archived.
- remove excludes for sourceSet androidTest
- updated
- com.jakewharton:butterknife*
- com.fasterxml.jackson.core:jackson-*
- junit:junit:4.*
- org.mapsforge:mapsforge-*
- com.drewnoakes:metadata-extractor
- com.squareup.okhttp3:okhttp:3.12.*
- com.google.android.gms:play-services-location, *-maps
- io.reactivex.rxjava2:rxjava

dependencies update

---

main/res/layout/cachedetail_waypoints_header.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/EditWaypointActivity.java
main/src/cgeo/geocaching/models/Waypoint.java

Add a button "add current location" to create a new waypoint with current coordinates, standard waypoint type and title.
Also moves method `getDefaultWaypointName()` from `EditWaypointActivity` private method to `Waypoint` public static method to make it reusable.

add button 'add current location' to waypoint list (fix #8114)

---

main/src/cgeo/geocaching/maps/google/v2/GoogleMapView.java

Indoor mode is set according to Google Maps mode:
- standard mode / map mode: on
- satellite mode: off

switch off indoor mode for Google Maps in standard mode (fix #7984)

---

main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/MapUtils.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/CachesBundle.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/WaypointsOverlay.java

Following the discussion in #8125: Extend the "filter waypoints" options to all map modes (eg: cache map and list map).

extend waypoint filters to all map modes

---

main/src/cgeo/geocaching/utils/SystemInformation.java

The new (and not so new) hiding features should be reflected in system info:
- hide disabled
- hide archived
- hide original waypoints
- hide parking waypoints
- hide visited waypoints
Changes "Hide own/found" to "Hide caches" and lists up to three options "own/found", "disabled", "archived", or "-" if none set.
Adds "Hide waypoints" with up to three options "original", "parking", "visited", or "-" if none set.

complete cache/waypoint hiding info in system info

---

main/res/values/preference_keys.xml
main/res/values/strings.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/settings/Settings.java

Add a toggle under settings - appearance to switch between transparent and solid background for mainscreen. Color of solid background is determined by c:geo's skin.

Allow solid background (fix #1361)

---

main/res/layout/map_mapsforge_v6.xml
main/res/menu/map_activity.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/DistanceDrawer.java
main/src/cgeo/geocaching/maps/google/v2/GoogleMapView.java
main/src/cgeo/geocaching/maps/google/v2/GoogleOverlay.java
main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
main/src/cgeo/geocaching/maps/interfaces/PositionAndHistory.java
main/src/cgeo/geocaching/maps/mapsforge/MapsforgePositionAndHistory.java
main/src/cgeo/geocaching/maps/mapsforge/v6/DistanceView.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/TapHandler.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/GeoitemLayer.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/GeoitemRef.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/RouteLayer.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/TapHandlerLayer.java
main/src/cgeo/geocaching/maps/routing/Route.java
main/src/cgeo/geocaching/maps/routing/RouteItem.java
main/src/cgeo/geocaching/maps/routing/Routing.java
main/src/cgeo/geocaching/storage/DataStore.java

This is a no frills implementation for the basics of #8020 (and includes a fix #7914):
- create individual routes by selecting multiple geoitems (waypoints and/or caches)
- calculate the route length and display the calculated distance
- make the route persistent
- only menu entry is for clearing a route
- implemented for Google Maps v2 and NewMap
Use cases (among others):
- visualize a planned day tour (and clear visited geoitems along the tour)
- calculate distance between two or more geoitems
(even if not having your current position at one of the geoitems)
Details:
- Add or remove a waypoint/cache from the route by long pressing on the waypoint/cache icon in the map. Added geoitems are appended at the end. No reordering or sorting.
- If the route consists of at least two geoitems, …

Allow individual routes

---

main/res/layout/preference_category.xml

Make settings subheadings a little larger and give them some top padding:

adjust styling of settings' subheadings (fix #8176)

---

main/res/values/strings.xml

per request of OSM operations team, see https://github.com/openstreetmap/operations/issues/371#issuecomment-598016057

Rename "OSM: Map" to "OpenStreetMap Standard" (fix #8181)

---

main/res/values/strings.xml
main/res/values/strings_not_translatable.xml

- move non translatable strings to according file and mark them as non-translatable
- also format strings in strings_not_translatable to have the `translatable="false"` attribute in front consistently to make reading and editing of that file easier

move non translatable strings to according file and mark them as non-translatable

---

cgeo-contacts/build.gradle
main/build.gradle

After the crowdin work we need some adjustments.
- languages ar=Arabic, fil=Filipino and in=Indonesian are at >74% translated and will be activated
- add info for other included but not activated languages: is=Icelandic, iw=Hebrew, zh=Chinese Simplified
Configure the same for cgeo-contacts

 supported language list

---

main/src/cgeo/geocaching/connector/ConnectorFactory.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/LiveCachesOverlay.java
tests/src-android/cgeo/geocaching/CgeoApplicationTest.java
tests/src-android/cgeo/geocaching/connector/gc/GCConnectorTest.java

- caching of map search results
- use factor 3 bounding box for viewport being searched
If you activate debug mode in c:geo you'll see messages for each call to searchByViewport with info whether a cached result could be reused or a new call has been issued.

WIP/testing only: reduce calls to online map search

---

main/res/values/strings.xml
main/src/cgeo/geocaching/network/StatusUpdater.java

- updated closeout message (and made it version independent)
- activate closeout message for systems running Android < 5.0

update & activate closeout message for Android < 5.0 (fix #8246)

---

main/res/menu/cache_options.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/models/Geocache.java
main/src/cgeo/geocaching/storage/DataStore.java

- Deletes all but the five most recent goto history entries
- Menu option is only shown for the "goto history" UDC (ZZ0)

Add option to clear the goto history (fix #8224)

---

main/res/values/strings.xml
main/res/values/strings_not_translatable.xml
main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java
main/src/cgeo/geocaching/maps/mapsforge/TileSourceCyclosm.java
main/src/cgeo/geocaching/maps/mapsforge/TileSourceOsmde.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

Extend our supported OSM based online maps by
- openstreetmap.de and
- cyclosm.org
Avaialble for NewMap only.
Also renamed "OpenStreetMap" to "OpenStreetMap.org" to distinguish from "OpenStreetMap.de".
Example screen shots:
OpenStreetMap.org (aka "OSM:Mapnik")
OpenStreetMap.de:
CyclOSM.org:

Support other OSM based online map sources (fix #8148)

---

main/res/menu/map_activity.xml
main/res/values/preference_keys.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/maps/MapProviderFactory.java
main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/settings/Settings.java

If the opened OSM offline map file supports multiple languages, a new menu entry "Map language" gets added to the map's menu, having the supported languages as entries of the sub menu.
Selecting one of those languages restarts the map, setting labels accordingly to the set language, if available:
Language set to "fr":
(The red box is just for better visualization in this info, it's not part of the actual map rendering!)
Language set to "de":
Selected language gets saved to preferences.
If the map does not support the language set in preferences, it switches to default language.
If a map does not support any languages, the menu entry "Map language" is not shown.

Add support for multilingual OSM maps (fix #8185)

---

main/res/values-v1/styles.xml
main/res/values-v21/styles.xml
main/res/values/styles.xml

Leave out two attributes for `cgeoProgressdialogTheme` and `cgeoProgressdialogTheme_light` stylings and re-add them only for API level 1 to 20.
Needs some extra testing on different physical devices, see https://github.com/cgeo/cgeo/issues/7533#issuecomment-618023674

adjust styling for API 21+ to fix progressdialog crash (fix #7533)

---

main/res/layout/cachedetail_waypoints_header.xml
main/res/menu/waypoint_options.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/models/Waypoint.java
main/src/cgeo/geocaching/utils/ClipboardUtils.java

- option to copy waypoint id to clipboard using longpress
- option to create new waypoint from waypoint id in clipboard
- optionally delete original waypoint after creating new one (only for user defined waypoints)
New popup menu option "Copy waypoint to clipboard":
If a waypoint id is available in the clipboard, waypoint list menu has an additional button "add from clipboard":
If waypoint creation has been successful and the original waypoint is user-defined: show option to delete the original waypoint:

copy waypoints between caches (fix #8155)

---

main/res/menu/map_activity.xml
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/maps/routing/Route.java

show 'clear individual route' menu entry only when non-empty individual route is available
(fix #8259)

show 'clear individual route' menu entry only when non-empty route is available (fix #8259)

---

main/src/cgeo/geocaching/maps/mapsforge/v6/layers/MultiRendererLayer.java

set maxZoom of a combined OSM offline map to the maximum of maxZoom values of the maps involved

allow max zoom on combined OSM map (fix #8263)

---

main/src/cgeo/geocaching/filter/CountryFilterFactory.java

Selecting the empty country filter line now means filtering for an empty/missing location info.

add filtering for empty locations to country filter (fix #8258)

---

main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java

skip validity check on pressing lat/lon buttons in wp editor

skip validity check on pressing lat/lon buttons (fix #8254)

---

main/src/cgeo/geocaching/maps/CGeoMap.java

trigger a repaint of the overlay involved after clearing the individual route

GMv2: repaint overlay after clearing individual route (fix #8267)

---

main/res/layout/coordinates_input.xml
main/res/values/styles.xml

adjust coordinate input dialog's styling to preserve lat/lon buttons (fix #8255)
- set button min width, reduce margin
- do not allow shrinking of the first table column (where the buttons are in)

adjust coordinate input dialog to preserve lat/lon buttons (fix #8255)

---

main/res/menu/map_activity.xml
main/res/values/arrays.xml
main/res/values/preference_keys.xml
main/res/values/strings.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java
main/src/cgeo/geocaching/maps/google/v2/GoogleMapView.java
main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
main/src/cgeo/geocaching/maps/interfaces/PositionAndHistory.java
main/src/cgeo/geocaching/maps/mapsforge/MapsforgePositionAndHistory.java
main/src/cgeo/geocaching/settings/Settings.java

Unify map rotation settings:
- There is a single setting & preference, which can be either "off", "manual" or "auto"
- Setting can be changed via Settings -> Map -> Map rotation
- or via the new menu entry "Map rotation"
Today's separate settings for "disable manual map rotation" and "disable auto map rotation" are NOT migrated. (Should be noted in release notes.)
Default value is "manual rotation".

unify map rotation settings (related to #8097)

---

main/src/cgeo/geocaching/WaypointPopupFragment.java

Shows the user note on waypoint popup:
If user note is empty, no user note field will be shown:

show user note on waypoint popup (fix #8290)

---

main/src/cgeo/geocaching/CacheDetailActivity.java

Make sure the cache change receiver is still available when creating a new waypoint from cache map. For this move the change notification setter from `onStart` to `onCreate`, and the receiver from `onStop` to `onDestroy`.

receive notification on waypoint creation from map (fix #8292)

---

main/res/values/strings.xml
main/src/cgeo/geocaching/maps/routing/Route.java

In single waypoint map mode we don't have the information available which is necessary for waypoint toggling in individual routes, therefore disable in this case.

disable individual route toggle in single waypoint mode (fix #8309)

---

main/src/cgeo/geocaching/network/HtmlImage.java

After the upgrade to RxJava3 the parameter of blockingLast cannot be null anymore.

Fix loading of Avatar images (#8313)

---

main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/activity/AbstractViewPagerActivity.java

reinitialize only the description page after update of personal note, instead of reinitializing the whole view pager.

reinit description page only after personal note update (fix #8324)

---

main/res/layout/about_system_page.xml
main/res/layout/about_version_page.xml
main/res/values/preference_keys.xml
main/res/values/strings.xml
main/res/values/strings_not_translatable.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/AboutActivity.java
main/src/cgeo/geocaching/settings/SettingsActivity.java
main/src/cgeo/geocaching/storage/LocalStorage.java
main/src/cgeo/geocaching/utils/CalendarUtils.java
main/src/cgeo/geocaching/utils/DebugUtils.java
main/src/cgeo/geocaching/utils/FileUtils.java
main/src/cgeo/geocaching/utils/ShareUtils.java

To make acquiring logcats easier I started implementing a little logcat functionality to c:geo. I tested in different emulated Android versions, and it seems to work starting from API level 24, but not up to 21 - although I'm not explicitly using any function with a higher API level. Android documentation on logcat itself is a bit sparse, though, so it may be due to a parameter not supported under those Android versions. - Therefore setting "WIP" for now to get some feedback first.
Logcat function is added to the c:geo - about - system screen:
(see the new "generate logfile" button at the bottom)
After successful write of the logfile to the new "logcat" directory a message confirms if you additionally want to send the file as e-mail:
When confirmed, the regular app chooser opens for you …

add logcat function to about-system screen (fix #8331)

---

main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java

Due to the changes necessary for #8303 and #8304 the overlay gets repainted earlier, in this case at a time where we do not have a current position, which leads to an NPE in drawing the history trail. Therefore check if we have a current position, and refrain from repainting the overlay if not.

avoid NPE during map initialization (fix #8328)

---

main/src/cgeo/geocaching/maps/CGeoMap.java

This is for the issue mentioned in #8300 only - so no general change or extension of cache/waypoint filtering yet.
Activate cache filtering when liveEnabled==true (which can be in `LIVE` map mode as well as in `SINGLE` map mode). Waypoint filtering is unchanged.

activate cache filtering in GMv2 when liveEnabled is set (fix #8300)

---

main/res/values/strings.xml
main/src/cgeo/geocaching/maps/google/v2/GoogleMapView.java

This is a proposal to get a grip on the auto rotation UI:
It catches a tap on the compass rose (if rotation mode is set to `AUTO` only) and ask the user if he/she wants to disable auto rotation.
This is a WIP only - @Lineflyer  Do you have a chance to test it?
Note: Currently it asks every time the user presses the compass rose (if rotation mode is set to `AUTO`) - we should sort of damp this, like only asking once or twice each session. - To be figured out yet what could work.

GMv2: disable autorotation on tap on compass rose

---

main/src/cgeo/geocaching/maps/DistanceDrawer.java
main/src/cgeo/geocaching/maps/ScaleDrawer.java
main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
main/src/cgeo/geocaching/maps/mapsforge/DirectionDrawer.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/GeoitemLayer.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/NavigationLayer.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/RouteLayer.java
main/src/cgeo/geocaching/utils/DisplayUtils.java

We query display metrics in several places, reusing the same duplicated code fragment several times. => Therefore moved it into utility class `DisplayUtils`.

Code cleanup: Move display metrics functions to DisplayUtils

---

main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
main/src/cgeo/geocaching/maps/mapsforge/DirectionDrawer.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/HistoryLayer.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/NavigationLayer.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/RouteLayer.java
main/src/cgeo/geocaching/utils/DisplayUtils.java

- unify the different stroke widths in GMv2 and OSM
- use a density based width for history line and route

unify map lines stroke width between GMv2 and OSM maps

---

main/src/cgeo/geocaching/connector/ConnectorFactory.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/LiveCachesOverlay.java
tests/src-android/cgeo/geocaching/CgeoApplicationTest.java
tests/src-android/cgeo/geocaching/connector/gc/GCConnectorTest.java

Refine viewport caching results: If we retrieved a sufficient amount of caches in searchByViewport (400+) do not longer use the queried viewport as cached area but the bounding box of caches returned.
(as described in https://github.com/cgeo/cgeo/issues/8260#issuecomment-629660662)

refine viewport caching searchresults (fix #8260)

---

main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java

For testing #8260/#8364:
- activate debug mode in c:geo settings
- go to Google Maps live map
- zoom out until max. number of caches got loaded => see red box around it
- red box will move when you start panning the map and caches get loaded additionally
see https://github.com/cgeo/cgeo/issues/8260#issuecomment-633713331 for examples

add mapcache bounding box for GMv2 when in debug mode

---

tests/src-android/cgeo/geocaching/test/mock/GC2JVEH.java
tests/src/cgeo/geocaching/test/mock/GC2JVEH.html

Description in original listing now has an integrated closing tag in the `<img>`-Tag

adapt mockfile for GC2JVEH to changed listing

---

tests/src-android/cgeo/geocaching/connector/trackable/GeolutinsParserTest.java

temporarily disabling the service connection test to geolutin
as the website returns http 403 since some time, breaking every PR test we have

temporarily disable geolutin service test

---

main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
main/src/cgeo/geocaching/maps/mapsforge/DirectionDrawer.java
main/src/cgeo/geocaching/maps/mapsforge/PositionDrawer.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/HistoryLayer.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/NavigationLayer.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/RouteLayer.java
main/src/cgeo/geocaching/utils/DisplayUtils.java

- made the common line base a bit smaller (4.0f instead of 5.0f)
- made the history line even smaller to match old GMv2 style (3.0f instead of 5.0f)
- expose widths for different targets (routing, history, direction etc.) as separate functions to be able to make them configurable separately later

adjust line widths and separate different targets (fix #8393)

---

main/src/cgeo/geocaching/utils/MapMarkerUtils.java

Use default waypoint type in `createWaypointMarker` if none is given.

avoid NPE in createWaypointMarker (fix #8412)

---

main/res/values/strings.xml
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/connector/AbstractConnector.java
main/src/cgeo/geocaching/connector/AbstractLoggingManager.java
main/src/cgeo/geocaching/connector/IConnector.java
main/src/cgeo/geocaching/connector/ILoggingManager.java
main/src/cgeo/geocaching/connector/ILoggingWithFavorites.java
main/src/cgeo/geocaching/connector/capability/IFavoriteCapability.java
main/src/cgeo/geocaching/connector/gc/GCConnector.java
main/src/cgeo/geocaching/connector/gc/GCLoggingManager.java
main/src/cgeo/geocaching/connector/su/SuApi.java
main/src/cgeo/geocaching/connector/su/SuApiEndpoint.java
main/src/cgeo/geocaching/connector/su/SuConnector.java
main/src/cgeo/geocaching/connector/su/SuLoggingManager.java
main/src/cgeo/geocaching/log/LogCacheActivity.java
main/src/cgeo/geocaching/models/Geocache.java

This is implementation of #7183 splitting Favorites functionality to separated interfaces in order to decouple it from geocaching.com and make it reusable for other services.
Also this implements favorites support using new interface in GC.SU connector.
Fixes #7183
Unblocks #3879

Refactor favorites

---

main/AndroidManifest.xml
main/res/layout/view_settings_item.xml
main/res/menu/view_settings.xml
main/res/values/preference_keys.xml
main/res/values/strings.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/activity/AbstractActivity.java
main/src/cgeo/geocaching/settings/SettingsActivity.java
main/src/cgeo/geocaching/settings/ViewSettingsActivity.java
main/src/cgeo/geocaching/utils/SettingsUtils.java
main/src/cgeo/geocaching/utils/SharedPrefsBackupUtils.java

During development and/or debugging I frequently have the need to see, change or remove certain settings. This PR adds a view under `prefs => System => Debug` to view settings:
This view lists all settings in alphabetical order of the key, and their according values:
If there is need to change or delete a setting you can do so after activating edit mode by pressing the edit button in the upper right. A warning message will be presented:
If confirmed, edit and delete buttons are added to the view:
(You can leave edit mode by pressing the edit button again. Edit and delete buttons will be removed then.)
On pressing the edit button a small edit dialog appears:
It's a simple text edit line, with some formatting rules for numeric values, but nothing fancy. It's a debug feature, after all.
If …

add view settings debug helper

---

main/build.gradle

Scanning the information linked to in #8382 I couldn't find any areas relevant to c:geo, and the tests ran fine locally, but still let's merge this early in this upcoming version to have time to fix any upcoming issues.

Set targetSDK and compileSDK to 29 (fix #8382)

---

main/res/values/strings.xml

Theoretically people should not be able to install c:geo on a device below Android 5.0 any longer. In case this however happens for some reason, let us just reuse the closeout warning as a note about incompatibility until we have the next closeout phase.

Change closeout warning to an incompatibility note

---

main/AndroidManifest.xml
main/res/layout/preference_map_icon.xml
main/res/values/attrs.xml
main/res/values/strings.xml
main/res/values/strings_not_translatable.xml
main/res/values/themes.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/HandleLocalFilesActivity.java
main/src/cgeo/geocaching/activity/Progress.java
main/src/cgeo/geocaching/files/FileType.java
main/src/cgeo/geocaching/files/FileTypeDetector.java
main/src/cgeo/geocaching/permission/PermissionRequestContext.java
main/src/cgeo/geocaching/settings/AbstractInfoPreference.java
main/src/cgeo/geocaching/settings/InfoPreference.java
main/src/cgeo/geocaching/settings/InfoPreferenceMap.java
main/src/cgeo/geocaching/settings/ReceiveMapFileActivity.java
main/src/cgeo/geocaching/storage/LocalStorage.java
main/src/cgeo/geocaching/ui/UrlPopup.java
main/src/cgeo/geocaching/utils/AbstractAsyncTaskWithProgress.java
main/src/cgeo/geocaching/utils/FileUtils.java

This is a WIP for beta testing only - do not merge
- integrate locally stored OSM map file into c:geo
- move to map dir (cancellable)
- set as current map source
- add preference link to download v3 OSM files
- improve handling of local files (forward detected file types internally, show an info message for the rest)
- smoke tested with different file types and Android versions from 4 to 10
For details and current status see #8180.

WIP ease offline maps onboarding

---

tests/src-android/cgeo/geocaching/connector/trackable/GeolutinsParserTest.java
tests/src-android/cgeo/watchdog/WatchdogTest.java

Should be merged to release and afterwards release upstream towards master to reenable tests on both branches.
I simply used git revert of the two commits used to disable the tests. Hope it will be fine.

Revert geolutin test disabling - Fix #8392

---

main/src/cgeo/geocaching/utils/TrackUtils.java

`loadTracks()` failed with NPE when no trackfile has ever been set yet (which would be the default scenario after upgrading to yesterday's nightly build)
Also fixed a potential NPE in `onActivityResult()`.

fix NPE on map start when no trackfile is defined (fix #8451)

---

main/res/layout/preference_colorpicker.xml
main/res/layout/preference_colorpicker_item.xml
main/res/values/arrays.xml
main/res/values/attrs.xml
main/res/values/colors.xml
main/res/values/numbers.xml
main/res/values/preference_keys.xml
main/res/values/strings.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/maps/google/v2/GoogleCacheOverlayItem.java
main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
main/src/cgeo/geocaching/maps/mapsforge/DirectionDrawer.java
main/src/cgeo/geocaching/maps/mapsforge/MapsforgeCachesList.java
main/src/cgeo/geocaching/maps/mapsforge/PositionDrawer.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/GeoitemLayer.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/AbstractLineLayer.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/HistoryLayer.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/NavigationLayer.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/RouteLayer.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/TrackLayer.java
main/src/cgeo/geocaching/settings/ColorpickerPreference.java
main/src/cgeo/geocaching/settings/MapLineWidthPreference.java
main/src/cgeo/geocaching/settings/Settings.java
main/src/cgeo/geocaching/utils/DisplayUtils.java
main/src/cgeo/geocaching/utils/MapLineUtils.java

Code cleanup + customization for map line colors and width:
- Default values are now constants in `colors.xml` (colors) resp. `numbers.xml` (widths).
- Google Maps and OSM use the same utility functions for colors and widths
- Colors and widths are customizable using settings => map => map lines customization
- Dialog works in dark and light theme
- Old trail color functions and resources removed
Preference dialog:
Color picker:
Available for:
- Trail history line
- Direction / navigation line
- Route line
- Track line
- Circle line / fill

Make map lines customizable (fix #8416)

---

main/res/layout/gpx_export_fragment.xml
main/res/layout/gpx_export_trail_dialog.xml
main/res/menu/map_activity.xml
main/res/values/preference_keys.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/export/TrailHistoryExport.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/settings/Settings.java
main/src/cgeo/geocaching/storage/DataStore.java

- Add function to export current trail history to GPX track file in GPX export folder.
- Add menu "Trail history" to map menus, including the existing "Clear trail history" and the new "Export trail history" as sub menu entries.
On calling this function the user gets the options
- to share the created GPX file (as in cache list => export), and
- to clear the history trail automatically after export.
During export a progress bar is shown.

Export trail history as GPX track (fix #8424)

---

main/res/menu/map_activity.xml
main/res/values/preference_keys.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/AbstractCachesOverlay.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/CachesBundle.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/CachesOverlay.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/LiveCachesOverlay.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/SinglePointOverlay.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/StoredCachesOverlay.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/WaypointsOverlay.java
main/src/cgeo/geocaching/settings/Settings.java
main/src/cgeo/geocaching/utils/CompactIconModeUtils.java

- Changed compact icon mode settings to off / on / auto, default=off
- If set to auto: Switches automatically between regular cache markers and compact icon markers.
Threshold is determined by screen size (in px^2) divided by cache marker size (in px^2) divided by 4, so a maximum of one fourth of the screen space is covered by cache markers until display switches to compact icon markers, if mode is set to AUTO.

auto select compact icon mode (optional) (fix #8261)

---

main/src/cgeo/geocaching/export/TrailHistoryExport.java

- set GPX version to 1.1
- actively suppress the auto generated namespace tags within `trkpt` elements
- set second element of `trkpt` to `lon`

fix some issues with exported trail GPX

---

main/src/cgeo/geocaching/HandleLocalFilesActivity.java
main/src/cgeo/geocaching/files/AbstractImportGpxZipThread.java
main/src/cgeo/geocaching/files/GPXImporter.java
main/src/cgeo/geocaching/files/GpxFileListActivity.java
main/src/cgeo/geocaching/utils/FileUtils.java

- fixes the error and suggestions mentioned in #8445
- adds the missing `.loc` file extension
- moves the known file extensions to `FileUtils`

fix duplicate extension checks

---

main/AndroidManifest.xml

Temporary workaround for #8457: use compatibility flag "legacyExternalStorage" to be able to access user data on Android Q devices again (like database backup etc.)
This is a temporary workaround only - we still need to investigate the new scoped storage concepts and adapt c:geo accordingly.

support legacy external storage as temporary fix

---

main/src/cgeo/geocaching/connector/tc/TerraCachingConnector.java
tests/src-android/cgeo/geocaching/files/GPXParserTest.java

Still can't see the cache's listing page as I have no account on tc.com, but with this change I don't get a 404, whereas without I get one.

update TerraCaching cache detail URL (fix #8449)

---

main/res/values/strings.xml

- added missing `zero`, `two`, `few` and `many` variations to all `plurals` sections to support languages with more than `one` / `other` variations for numbers
- changed all `plurals` values to pure numeric values (meaning "one" => "%d")

add missing plurals quantities, change all to pure numeric values

---

main/src/cgeo/geocaching/AbstractDialogFragment.java
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/CachePopupFragment.java
main/src/cgeo/geocaching/CreateShortcutActivity.java
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/SearchActivity.java
main/src/cgeo/geocaching/TrackableActivity.java
main/src/cgeo/geocaching/activity/OAuthAuthorizationActivity.java
main/src/cgeo/geocaching/command/RenameListCommand.java
main/src/cgeo/geocaching/export/GpxExport.java
main/src/cgeo/geocaching/location/ProximityNotification.java
main/src/cgeo/geocaching/log/LogCacheActivity.java
main/src/cgeo/geocaching/log/LogTrackableActivity.java
main/src/cgeo/geocaching/maps/google/v2/GoogleMapView.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/SinglePointOverlay.java
main/src/cgeo/geocaching/maps/routing/Route.java
main/src/cgeo/geocaching/network/HtmlImage.java
main/src/cgeo/geocaching/network/Network.java
main/src/cgeo/geocaching/sensors/GeoDirHandler.java
main/src/cgeo/geocaching/settings/SettingsActivity.java
main/src/cgeo/geocaching/storage/DataStore.java
main/src/cgeo/geocaching/ui/ImagesList.java
main/src/cgeo/geocaching/ui/dialog/Dialogs.java
main/src/cgeo/geocaching/utils/DatabaseBackupUtils.java
main/src/cgeo/geocaching/utils/ImageUtils.java
main/src/cgeo/geocaching/utils/RxUtils.java
tests/src-android/cgeo/geocaching/export/GpxSerializerTest.java
tests/src-android/cgeo/geocaching/files/InvalidXMLCharacterFilterReaderTest.java

Replace calls to lambda functions by method references (where possible) to make code more readable and to reduce the need for artificially named parameters

use method references

---

main/src/cgeo/geocaching/CacheDetailActivity.java

Current version of Android Studio does recognize that `StringUtils.isNotBlank()` does null check internally.

remove extra null check (no longer needed by compiler)

---

main/src/cgeo/geocaching/connector/gc/Tile.java

see also http://svn.openstreetmap.org/applications/viewer/jmapviewer/src/org/openstreetmap/gui/jmapviewer/OsmMercator.java (which is linked to from our source):
```
public long getMaxPixels(int aZoomlevel) {
return tileSize * (1 << aZoomlevel);
}
```

Simplify code by removing unnecessary factor

---

main/src/cgeo/geocaching/AbstractSelectFileActivity.java
main/src/cgeo/geocaching/Intents.java
main/src/cgeo/geocaching/files/SimpleDirChooser.java

Extend our `SimpleDirChooser` to also support selecting of files, so that `AbstractSelectFileActivity` also works, if no file manager supporting `open file management intents` is installed.

extend SimpleDirChooser to support choosing files (fix #8523)

---

main/src/cgeo/geocaching/connector/AbstractConnector.java
main/src/cgeo/geocaching/connector/ConnectorFactory.java
main/src/cgeo/geocaching/connector/IConnector.java
main/src/cgeo/geocaching/connector/ec/ECConnector.java
main/src/cgeo/geocaching/connector/ec/package-info.java
main/src/cgeo/geocaching/connector/ga/GeocachingAustraliaConnector.java
main/src/cgeo/geocaching/connector/ga/package-info.java
main/src/cgeo/geocaching/connector/ge/GeopeitusConnector.java
main/src/cgeo/geocaching/connector/ge/package-info.java
main/src/cgeo/geocaching/connector/internal/InternalConnector.java
main/src/cgeo/geocaching/connector/oc/OCAuthParams.java
main/src/cgeo/geocaching/connector/oc/OCConnector.java
main/src/cgeo/geocaching/connector/oc/OkapiClient.java
main/src/cgeo/geocaching/connector/su/SuApi.java
main/src/cgeo/geocaching/connector/su/SuAuthorizationActivity.java
main/src/cgeo/geocaching/connector/su/SuConnector.java
main/src/cgeo/geocaching/connector/su/package-info.java
main/src/cgeo/geocaching/connector/tc/TerraCachingConnector.java
main/src/cgeo/geocaching/connector/tc/package-info.java
main/src/cgeo/geocaching/connector/unknown/UnknownConnector.java
main/src/cgeo/geocaching/connector/unknown/package-info.java
main/src/cgeo/geocaching/connector/wm/WaymarkingConnector.java
main/src/cgeo/geocaching/connector/wm/package-info.java
tests/src-android/cgeo/geocaching/connector/ConnectorFactoryTest.java
tests/src-android/cgeo/geocaching/connector/su/SuParserTest.java

All cache connectors use now https addresses.
This needs to reflect in our code base.
Additionally, I did some refactoring to have all connectors in own package dirs with a package-info.

set all cache connector to https and code refactoring

---

main/build.gradle

See https://developer.android.com/studio/releases/build-tools.
~~~
If you're using Android plugin for Gradle 3.0.0 or higher, your project automatically uses a default version of the build tools that the plugin specifies.
~~~

remove buildToolsVersion

---

tests/src-android/cgeo/geocaching/utils/FormatterTest.java

The test testFormatStoredAgo only works on a device with language EN.
When testing (e.g. on a dedicated physical device) it fails on devices with other languages.
Therefore we should skip this test in this situation.

skip testFormatStoredAgo on non English device

---

main/res/values/strings.xml

Followup to / proposal for https://github.com/cgeo/cgeo/pull/8521#issuecomment-652264737:
- rename "history trail / trail history" to "history track"
- rename "track" to "individual track"
- add a description to "show history track" in map settings

rename history trail and track to history track and individual track

---

main/src/cgeo/geocaching/settings/ColorpickerPreference.java

As with the several seekbar slider preferences you can now manually enter the opaqueness value in the `ColorPreference`.

make opaqueness value editable in ColorPreference

---

main/src/cgeo/geocaching/CacheListActivity.java

Mitigation for the unintuitive behavior of fast scroll described in #8406:
- disable fast scroll after one second of not scrolling
- reenable after first scroll

automatically disable/enable fast scroll after grace period (fix #8406)

---

main/src/cgeo/geocaching/utils/SettingsUtils.java

Settings backup created with older c:geo versions created entries with `<int name="xxx" value="xxx" />` instead of `<integer ... />`, which cannot be restored by current c:geo versions. This PR adds compatibility to those old backups.

add compatibility for restore of early settings backup versions

---

main/res/layout/cacheslist_activity.xml
main/src/cgeo/geocaching/CacheListActivity.java

Following up the discussion in #8406 here's a tryout version for CacheListActivity:
- disable fastscroll by default
- activate on scrolling, but only in fling mode
- deactivate automatically after one second of not scrolling

tryout: new fastscroll mechanism for CacheListActivity

---

main/src/cgeo/geocaching/settings/ViewSettingsActivity.java

Fix for
> You scroll down half a page and the scroll position marker goes down half a page, too - which is obviously wrong, as the list is way longer than one page. Then, if you (slowly) scroll down more than a page, the scroll position marker leaves the page at the bottom ...
mentioned in https://github.com/cgeo/cgeo/issues/8406#issuecomment-654536314

fix setings view to linear movement

---

main/src/cgeo/geocaching/CacheListActivity.java

Followup to https://github.com/cgeo/cgeo/issues/8406#issuecomment-654536314:
Seems that every scroll movement ends up in fling mode, if you do not actively bring the movement to a halt, so let's add a minimum required movement as prerequisite to activate fastscroll move.

require minimum distance in fling mode to activate fastscroll

---

main/res/values/strings.xml
main/src/cgeo/geocaching/sorting/CacheComparator.java
main/src/cgeo/geocaching/sorting/DateComparator.java
main/src/cgeo/geocaching/sorting/DifficultyComparator.java
main/src/cgeo/geocaching/sorting/DistanceComparator.java
main/src/cgeo/geocaching/sorting/FindsComparator.java
main/src/cgeo/geocaching/sorting/GeocodeComparator.java
main/src/cgeo/geocaching/sorting/InventoryComparator.java
main/src/cgeo/geocaching/sorting/InverseComparator.java
main/src/cgeo/geocaching/sorting/NameComparator.java
main/src/cgeo/geocaching/sorting/PopularityComparator.java
main/src/cgeo/geocaching/sorting/PopularityRatioComparator.java
main/src/cgeo/geocaching/sorting/RatingComparator.java
main/src/cgeo/geocaching/sorting/SizeComparator.java
main/src/cgeo/geocaching/sorting/StateComparator.java
main/src/cgeo/geocaching/sorting/StorageTimeComparator.java
main/src/cgeo/geocaching/sorting/TerrainComparator.java
main/src/cgeo/geocaching/sorting/VisitComparator.java
main/src/cgeo/geocaching/sorting/VoteComparator.java
main/src/cgeo/geocaching/ui/CacheListAdapter.java
main/src/cgeo/geocaching/utils/CalendarUtils.java

Adds fastscroll thumbs to cache list view (similar to #8583) to make fastscroll in cache list view more visible + more useful.
What gets shown as thumb depends on the currently selected sorting, eg.:
- sort by name: shows the first two letters
- sort by date: shows year + month
- sort by rating: shows rating
etc.

show fastscroll thumbs in cachelist view

---

main/src/cgeo/geocaching/CacheListActivity.java

Set required minimum to `> 2` instead of `> 10`.
Follow up to https://github.com/cgeo/cgeo/issues/8406#issuecomment-655351332

lower minimum move requirement for fastscroll

---

build.gradle
main/build.gradle

fixes #8587
revert change of commons-io > 2.5.
It uses java.nio.file.Path - which is first contained in Android API26.

revert commons-io update

---

tests/src-android/cgeo/geocaching/CgeoApplicationTest.java

Congrat @Lineflyer to the new published earthcache ;-)
adapted the `testSearchByOwner` accordingly

adapt testSearchByOwner to new earthcache by Lineflyer

---

main/res/values/colors.xml
main/res/values/styles.xml
main/res/values/themes.xml

set colorAccent to new logo's orange tone in several places (may have missed some, though)
Some areas the new color shows up:
- map loading progress indicator
- cache list view fastscroll thumb
- import GPX progress bar

set colorAccent to new logo's orange tone

---

main/res/values/changelog_master.xml
main/res/values/changelog_release.xml
main/src/cgeo/geocaching/AboutActivity.java
main/src/cgeo/geocaching/utils/LiUtils.java

Add a bit of formatting to make changelog more readable. Among other things `<li>` are now allowed, even on low API devices, to support correct indenting. To ease migration, our currently used bullet points will be transformed into `<li>...</li>` internally.
Example picture is taken from API 21 emulated device:
Not much has to be changed in our changelog files, mainly surrounding our current manual lists with `<ul>` and `</ul>` and adding a `CDATA` frame. `\n` at the line ends are no longer needed.

allow LI tags in changelog

---

main/AndroidManifest.xml
main/res/xml/preferences.xml

- disables the changes introduced by #8183 
- restores the old AndroidManifest
which disables c:geo's possibility to read locally stored map files, but avoids the side effects described in #8467.
Also disables the menu entry "Download basic offline map" in settings => map, as it doesn't really make sense without the other part. Menu entry can be re-enabled and re-targeted when the new "map downloader" is merged.

disable #8183, restore old AndroidManifest

---

main/res/menu/cache_list_options.xml

move clear history menu entry to top level, end of menu (fix #8622)

---

main/src/cgeo/geocaching/ui/dialog/Dialogs.java
main/src/cgeo/geocaching/utils/DebugUtils.java

With this change, the logcat logfile feedback dialog reads sth. like "Logfile written successfully - send e-mail / ok" instead of "Logfile written successfully - cancel - send e-mail".

reword logcat dialog to send/ok instead of cancel/send (fix #8636)

---

main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
main/src/cgeo/geocaching/maps/mapsforge/PositionDrawer.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/HistoryLayer.java
main/src/cgeo/geocaching/utils/MapLineUtils.java

Make history track line consistent with the other map lines, therefore remove shadow.
Following a discussion in https://github.com/cgeo/cgeo/issues/8477#issuecomment-650517642 (and other places).

remove history track shadow

---

main/src/cgeo/geocaching/location/GeopointParser.java
tests/src/cgeo/geocaching/location/GeoPointParserTest.java

We now forbid all special characters of the coordinates to occur between the coordinate parts.

Fix #8589: Make coordinate parsing more strict

---

main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/HistoryLayer.java
main/src/cgeo/geocaching/storage/DataStore.java

- Remove superflous connection in history track by returning a track on restore in the same order as on writing.
- Also removes unnecessary duplicated current position on drawing a track as well as some duplicated length check.

remove superflous connection in history track (fix #8648)

---

main/src/cgeo/geocaching/utils/SharedPrefsBackupUtils.java

Auth keys / tokens etc. should not be part of the limited shared prefs backup, therefore exclude the geokrety auth token prefkey from it.
(Cause was: Auth token for geokrety seems to be handled a bit different than the other auth tokens, using a different prefkey structure, so it has been missed so far.)

remove geokrety auth token from limited shared prefs backup

---

main/res/values/strings.xml
main/src/cgeo/geocaching/network/StatusUpdater.java

If c:geo version string indicates a version year which is less than (current system year minus 1), then show a "version deprecated" warning on main screen:
This message is linked to our FAQ.
If c:geo can receive a message from our c:geo status server, that message is displayed instead.

add version check and info message (fix #8651)

---

main/src/cgeo/geocaching/settings/ViewSettingsActivity.java

Current settings view has the problem, that some buttons cannot be reached due to fast scroll with thumbs being activated. Applying our new fastscroll listener automatically disables fastscroll after one second of (fling mode) scrolling inactivity, which also solves the button problem.

apply fastscroll listener to settings view

---

main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/HistoryLayer.java
main/src/cgeo/geocaching/storage/DataStore.java

Using the original trail object lead to strange display artifacts, especially after returning from subview.
Now works on copy of trail for display, in both GMv2 and in NewMap.
Additionally return the correct segment of the trail on loading (most recent part, in correct order).
Attempts to fix #8663.

work on trail copy to display + return correct trail segment on load (fix #8663)

---

main/res/values/strings.xml
main/src/cgeo/geocaching/maps/routing/RouteSortActivity.java

Show replacement text instead (see last entry):

avoid NPE on unfinished elements in routesort view (fix #8672)

---

main/src/cgeo/geocaching/maps/routing/RouteSortActivity.java

- left swipe on routelist item swaps up/down buttons for delete button
- hitting delete button marks item as deleted (and removes it from view)
- right or vertical swipe restores the original buttons

add left swipe gesture to delete item in routesort view (fix #8670)

---

main/src/cgeo/geocaching/storage/DataStore.java

Sometimes there is the need to store a few values, mostly transiently, into the database. During my work on #8610 I've again stumbled upon this, so I created a minimalistic extension framework for this.
Base class is DataStore.DBExtension, which defines a simplistic key/value store with a type (enum), key (String) and two long + two string values (usable individually), and methods to access it. To use this, you should derive you own class from this and expose the parts you need under domain specific names.
Two examples for (possible) usage:
- For my maps downloader I need to store a temporary id from the download managerer + additional information regarding the selected map, so I created a `PendingDownload extends DBExtension` class, which uses the fields `key` (= id of pending download) …

add extension table

---

main/src/cgeo/geocaching/connector/AbstractConnector.java
main/src/cgeo/geocaching/ui/UserClickListener.java

Set to the old behavior - works for GC, works not for OC, unknown for other cache connectors
needs to create a better solution for all connectors
fixes #7998: "Caches hidden" fails to load with customized "cache owner" name
revert #7125: Owner actions not working
revert #7818: different usage of userName and displayName

userName/displayName in different meaning in GC and OC

---

main/AndroidManifest.xml
main/src/cgeo/geocaching/HandleLocalFilesActivity.java

On tapping a local file with extension ".map" this file gets copied to c:geo's map dir and set as default map.
(Includes a check for magic OSM map file string and a warning message, if magic string not found.)

reactivate local file handler for .map files (fix #8676)

---

main/res/values/strings.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/settings/AbstractInfoPreference.java
main/src/cgeo/geocaching/settings/InfoPreferenceMap.java
main/src/cgeo/geocaching/settings/SettingsActivity.java

Adds a button to map settings to start the new map downloader.
After pressing the button a short explanation and warning message is shown:
On pressing the "Choose map" button the new map downloader starts, following the same procedure as if started from map selector in map view. (For details on this see #8610.)

add map download button to map settings

---

main/res/values/attrs.xml
main/res/values/strings.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/settings/ColorpickerPreference.java

A follow-up to the discussion in https://github.com/cgeo/cgeo/issues/8699#issuecomment-666677719
Adds a button labelled "default" if the preference has an `app:defaultColor` entry in `preference.xml`:
On pressing the button the color picker returns to the default color (but does not store it yet - you can still decide to cancel).

add default function to ColorpickerPreference

---

main/res/menu/map_activity.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/settings/Settings.java
main/src/cgeo/geocaching/utils/MapLineUtils.java

A follow-up to the discussion in https://github.com/cgeo/cgeo/issues/8699#issuecomment-666677719:
Remove the map option to reset all map line colors to their defaults.
See #8720 for an alternative integrated into the `ColorpickerPreference`.

remove map option to reset all line colors

---

main/res/layout/cachedetail_description_page.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/enumerations/WaypointType.java
main/src/cgeo/geocaching/location/GeopointParser.java
main/src/cgeo/geocaching/models/Geocache.java
main/src/cgeo/geocaching/models/Waypoint.java
main/src/cgeo/geocaching/utils/TextUtils.java
tests/src-android/cgeo/geocaching/enumerations/WaypointTypeTest.java
tests/src-android/cgeo/geocaching/models/WaypointTest.java
tests/src-android/cgeo/geocaching/utils/TextUtilsTest.java
tests/src/cgeo/geocaching/location/GeoPointParserTest.java

This PR attempts to solve Issue #5688: https://github.com/cgeo/cgeo/issues/5688
The following "Waypoint text pattern" (for both creating and parsing) was created:
@name (type) coordinate\n"user note"
Example:
@my Waypoint (puzzle) N48 10.123 E11 05.456
"My User Note"
Additional notes:
- Regarding the @: if no @ is found during parse then no name is created from text (default name applies). If there would not be a name marker, then coords parsed from within text might get very strange names...
- Type: type will also be recognized when NOT in () like today, but will then additionally be part of the name. E.g. "@parking Spot N48 10.123 E11 05.456" will become waypoint of type "Parking" with name "Parking spot". Type in () will be filtered out in name creation.
- Type: for easier typing I …

Issues/5688: copy all modified waypoints to notes

---

main/res/values/strings.xml
main/src/cgeo/geocaching/CacheDetailActivity.java

this PR contains code which SHOULD fix #8729 (although I couldn't reproduce it I think this is caused by a not correctly initialized maxPersonalNoteSize variable), and in case it doesn't it contains code helping to analyze situation better (now the max size of personal note is added to the error toast)

Issue #8729: fix

---

main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

checking `R.id.menu_clear_individual_route` is already covered by calls to `IndividualRouteUtils.onOptionsItemSelected()` further down, no need to duplicate it here

remove duplicated calls to clearIndividualRoute

---

main/res/layout/twotexts_twobuttons_item.xml

Follow-up to the discussion in https://github.com/cgeo/cgeo/issues/8670#issuecomment-667132652:
> Unfortunately, a lot of these have looong names and, even worse, with the significant part of the name at the very end (in form of a counter), which makes it really hard to say, which one is which ... so what would you think about a line wrap for cache names that do not fit into the column?
This PR adds wrapping to the title, if needed:

add wrapping to title in route sort view

---

main/src/cgeo/geocaching/settings/ColorpickerPreference.java

Aims to fix https://github.com/cgeo/cgeo/pull/8720#issuecomment-668019749
Error cause seems to be a wrong preset of the `originalColor` value, so we now set it manually on startup.

fix pressing cancel in ColorpickerPreference

---

main/src/cgeo/geocaching/utils/CollectionStream.java
tests/src/cgeo/geocaching/utils/CollectionStreamTest.java

While working on Issue #2553 (Offline Log with image upload doesn't save image to log) I realized at some point that I need some more fundamental changes in order to implement this in a future-proof way. This became much too big for one Pull Request. Thus the idea is to push parts of this as independent pull requests and glueing the code pieces together once they are through. This also allows separate discussion with regards of different things I suggest to bring to the code.
This is one of those Pull Request.
This PR introduces Streaming-like functionality to cgeo for collections since Java streaming API is only available starting at API level 24. If approved, it will be heavily used in #2553 implementation and IMHO substantially dramatically increases code amintainability/readability

[Basics, related to Issue:#2553] provide Streaming-like functionality to cgeo

---

main/res/values-ar/strings.xml
main/res/values-ca/strings.xml
main/res/values-ceb/strings.xml
main/res/values-cs/strings.xml
main/res/values-da/strings.xml
main/res/values-de/strings.xml
main/res/values-el/strings.xml
main/res/values-es/strings.xml
main/res/values-fi/strings.xml
main/res/values-fil/strings.xml
main/res/values-fr/strings.xml
main/res/values-hu/strings.xml
main/res/values-in/strings.xml
main/res/values-is/strings.xml
main/res/values-it/strings.xml
main/res/values-iw/strings.xml
main/res/values-ja/strings.xml
main/res/values-ko/strings.xml
main/res/values-lt/strings.xml
main/res/values-lv/strings.xml
main/res/values-nb/strings.xml
main/res/values-nl/strings.xml
main/res/values-pl/strings.xml
main/res/values-ro/strings.xml
main/res/values-ru/strings.xml
main/res/values-sk/strings.xml
main/res/values-sl/strings.xml
main/res/values-tl/strings.xml
main/res/values-tr/strings.xml

Remove a couple of translation string which are no longer in use, but haven't been removed automatically by crowdin update yet. This is not a problem per se, and removing them does not change the resulting apk, but erases some warnings during compilation.

remove unused translations

---

main/src/cgeo/geocaching/files/GPXTrackImporter.java

Emit warning "error loading track" on loading either an empty track or an GPX route file.
Remove current track only on successfully loading a new track.

show warning on loading empty track (fix #8686)

---

main/src/cgeo/geocaching/location/GeopointFormatter.java
main/src/cgeo/geocaching/models/Waypoint.java
tests/src-android/cgeo/geocaching/models/WaypointTest.java

when storing WPs in PN, generated coordinates are not shorter
Format before: N xx° xx.xxx' - E xxx° xx.xxx'
Format after: Nx xx.xxx Ex xx.xxx

[related to Issue:#8787] shorten coordinates in PN Offline Waypoint storage

---

main/res/values/strings.xml
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/log/LogCacheActivity.java
main/src/cgeo/geocaching/log/LogTemplateProvider.java
main/src/cgeo/geocaching/storage/DataStore.java
main/src/cgeo/geocaching/storage/extension/FoundNumCounter.java

fix #987 
fix https://github.com/cgeo/cgeo/pull/8603#issuecomment-668718020
It uses the `DBExtension` to store the found number for each geocaching service. The values will be updated each time the main activity is called and a connection to a geocaching service is established.
when the signature variable is used, all offlinelogs of the specific connector will be summed up added to the cached found number
For additional description see https://github.com/cgeo/cgeo/issues/987#issuecomment-669544510

introduce [OFFLINENUM]

---

main/src/cgeo/geocaching/connector/gc/GCLoggingManager.java

'onCreateLoader' in GCLoggingManager usd to return null when no GC credentials are stored, this is apparently not allowed.
Now the Loader is returned even if no GC credentials are available. The activity logic will then handle this as if it were a "normal" network connectivity failure

[Issue:#8761] fix 'Fata exception of logging'

---

main/res/values/strings.xml
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/ui/dialog/Dialogs.java

fix #2288
it shows folowing dialog when trying to load a PM cache as basic member instead of "c:geo failed to download cache details. This Cache is only available to Geocaching.com Premium Members."

direct logging of PM-only caches from search

---

main/res/layout/fragment_edit_note.xml

Currently personal note edit window is set to a fixed height of eight lines.
This PR changes this to start with a minimum of eight lines, but let the window increase in length on demand:
(Tricky part was to keep the bottom text and checkbox on screen even for very long texts - that's what the `layout_weight` lines are for.)

change personal note edit size to minLines=8 (fix #8773)

---

main/src/cgeo/geocaching/ui/dialog/Dialogs.java

Several dialogs are based on `ui/Dialog.java`, which does not actively use a theme with the new `colorAccent`. This PR changes the dialogs to use the `Alert_Dialog` theme, which includes the new `colorAccent`. Two examples:

use themeing for ui.Dialog based dialogs to support colorAccent

---

main/res/values/themes.xml

In light mode the map icon for "Download offline map" setting is barely readable - should be the black variant instead:

use black map icon for map info preference in light mode

---

main/res/values/themes.xml

Tries to fix https://github.com/cgeo/cgeo/issues/8783#issuecomment-674456981 by adding colorAccent for themes using AppCompat attributes

apply colorAccent for preferences using AppCompat theme

---

settings.gradle

Fix this deprecation problem:
~~~
>gradlew help --warning-mode all
The BuildCacheConfiguration.local(Class, Action) method has been deprecated.
This is scheduled to be removed in Gradle 7.0.
Please use the local(Action) method instead.
Consult the upgrading guide for further information:
https://docs.gradle.org/6.6/userguide/upgrading_version_5.html#local_build_cache_is_always_a_directory_cache
at settings_345qrx4yukxdtqjjxixz57t1j$_run_closure1.doCall(...\cgeo\settings.gradle:20)
~~~

BuildCacheConfiguration.local(Class, Action) method has been deprecated

---

main/res/values/themes.xml

Adding `text_color` attribute helps for API level 21 in the emulator.

add text_color attribute (fix #8813)

---

main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/WaypointViewHolder.java
main/src/cgeo/geocaching/ui/CoordinatesFormatSwitcher.java

Stores the current setting of coordinate format in the waypoint list item view (transient)

waypoint coordinate format stays on scrolling (fix #8795)

---

main/res/values/changelog_master.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/network/StatusUpdater.java

Android 11 enforces storage spaces for all apps targeted to API 29 (which by itself is an upcoming requirement by Play Store). c:geo does not yet support storage spaces, which will lead to some of its data not being accessible by c:geo if running on Android 11. See #8457 for details.
I propose to add a info notice to our changelog to inform users not to upgrade their system to Android 11 for now (or at least only if they can live with the consequences regarding c:geo):

add Android 11 notice about storage spaces

---

tests/src-android/cgeo/geocaching/utils/TextUtilsTest.java

Fixes #8833 (missing SafeVarargs in TextUtilsTest)

fix #8833 (missing SafeVarargs in TextUtilsTest)

---

cgeo-contacts/build.gradle
main/build.gradle

- main
- update dependencies
- leakcanary to 2.4
- rxjava to 3.0.5
- appcompat to 1.2.0
- add leakcanary:plumber-android, see https://square.github.io/leakcanary/changelog/#plumber-android-is-a-new-artifact-that-fixes-known-android-leaks
- cgeo-contacts
- update dependencies
- commons-lang3 to 3.10
- (let commons-io stay at 2.5)
- appcompat to 1.2.0
changed:
- removed leakcanary-object-watcher-android, does not help for #8339
- remove compileSdkVersion and targetSdkVersion to 29 according for c:geo contacts

Update external references, configuration

---

main/src/cgeo/geocaching/ui/EditNoteDialog.java

Fixes bugs out of #8793 s reported by @fm-sys 
* headline of the personal note going out of range while editing when a lot of text is involved
* if started to edit somewhere in the upper half of the page, the last lines are covered by the keyboard
Issue should still stay open since it discusses introduction of a separate note window.

fixes bugs in #8793: note edit popup window

---

main/src/cgeo/geocaching/models/RouteItem.java
main/src/cgeo/geocaching/storage/DataStore.java

Part of fixing issue #8876 - make route loading more robust
Adds additional checks on loading individual route items:
- skip null entries
- if an entry has no/empty id string, resort to coordinates only

check for empty entries on loading individual route

---

main/src/cgeo/geocaching/utils/IndividualRouteUtils.java

Check result on individual route load file selector to detect cancelling the dialog and avoid NPE.

check for result on individual route load file selector (fix #8901)

---

main/src/cgeo/geocaching/storage/DataStore.java

second part of fixing #8876: Ignore waypoint route items on migrating route, which are no longer available in the database. (Such waypoints wouldn't have been shown as part of the route anyway, as no coordinates could have been determined.)

ignore invalid waypoints on route migration

---

main/src/cgeo/geocaching/storage/DataStore.java

Also related to #8876 (see https://github.com/cgeo/cgeo/issues/8876#issuecomment-681843301):
Throw an exception if any upgrade step fails (instead of just skipping the failing step).

throw exception on database upgrade error

---

main/res/menu/map_activity.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/google/v2/GoogleMapView.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/utils/HistoryTrackUtils.java

- move show history track checkbox to history track submenu (as show/hide menu entries)
- extract common history track functions to `HistoryTrackUtils`
- fix enabling/disabling history track display on Google Maps
- unify menu entry order for history track, GPX track/route, individual route
menu entry order now is:
|history track|GPX track/route|individual route|
|-------------|---------------|----------------|
|show         |load           |load            |
|             |               |sort            |
|             |center         |center          |
|export       |               |export          |
|hide         |unload         |                |
|clear        |               |clear           |

move show history track checkbox to history track submenu (fix #8517)

---

main/src/cgeo/geocaching/utils/Log.java

This PR adds the option to configure Logging by issuing a config file "log.properties" into the "logfiles" directory. Currently following options are supported:
```
/** Minimum log level. Value should be one of {@link LogLevel} in textual form */
public static final String PROP_MIN_LOG_LEVEL = "logging.minlevel";
/** Minimum log level to add callerinfo to log message. Value should be one of {@link LogLevel} in textual form */
public static final String PROP_MIN_CALLERINFO_LEVEL = "logging.mincallerinfolevel";
/** Whether to throw an exception when an error is logged. Value should be true or false */
public static final String PROP_THROW_ON_ERROR_LOG = "logging.throwonerror";
```
This attempts to solve #8851 while NOT going to the overhead of introducing a dedicated logging framework

Add configuration options to logging (fix #8851)

---

main/build.gradle

related to #8896
- change the ribbon color to blue
- add reference to the issue #8896 to have the problem visible for other
- remove the extra iconNames because this is already the default from AndroidManifest.xml

change ribbon color

---

main/res/layout/cachedetail_description_page.xml
main/src/cgeo/geocaching/CacheDetailActivity.java

partially fixes issue #8898:
- hide separator when personal note is empty
- apply onclick method to personal note text view
would be nice if this could be merged before merging branches, so that we have a nice UI in our beta version. If I'm to late we can also close this and create a new PR for merging this to release.
Edit: Clicking on links will still open them in browser, so there should be no regression. The onclick method does only impact normal text...

hide separator when personal note is empty

---

main/src/cgeo/geocaching/maps/DistanceDrawer.java

Found the NPE in the logfile attached to https://github.com/cgeo/cgeo/pull/8918#issuecomment-683797328
(This happens when DistanceDrawer gets initialized without a target - which will happen nowadays to display the length of an individual route.)

avoid NPE in DistanceDrawer if no target is set

---

main/src/cgeo/geocaching/log/LogCacheActivity.java

Handle null-value ratings in stored offline logs (fix #8935)

---

main/AndroidManifest.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/NavigateAnyPointActivity.java

On receiving a `geo:` intent in one of the following formats, c:geo creates a new "go to" history waypoint and opens the waypoint page, with the newly created waypoint on top. By tapping on the navigation symbol beside this waypoint, c:geo opens the map centered to this waypoint, and shows a navigation line (if BRoute is active).
Example, started from the "Lab Adventure" app:
- tap on navigation symbol in "Lab Adventure" app:
- c:geo is offered as navigation app (besides any other navigation app you have installed):
- Waypoint gets added to history, named accordingly (if given on opening intent), shown at the top of the list:
- If you tap on the navigation symbol beside the waypoint name, map view starts and direction or navigation line is shown: (configured to yellow in this test …

offer c:geo for navigation intents (fix #8925)

---

main/res/values/strings.xml
main/src/cgeo/geocaching/settings/MapDownloadSelectorActivity.java
main/src/cgeo/geocaching/settings/ReceiveMapFileActivity.java
main/src/cgeo/geocaching/utils/MapDownloadUtils.java

- uses the public `Download` dir as temporary storage (also makes temporary files visible)
- if the destination dir is not writable: ask user whether to continue with above default dir instead of skipping the download
Message shown _before_ map file selector, if destination dir is not writable:
Downloaded files are shown in the download manager / system default public Donwload dir:

adjust map download location (fix #8944)

---

main/src/cgeo/geocaching/storage/DataStore.java
tests/src-android/cgeo/geocaching/storage/DataStoreTest.java

fix #8950: falsely read update instead of date field when reading offline log

fix #8950: falsely read update instead of date field when reading offline log

---

main/src/cgeo/geocaching/utils/Log.java

fix #8953: wrong direction of loglevel ordinal comparison

fix #8953: wrong direction of loglevel ordinal comparison

---

main/src/cgeo/geocaching/models/ManualRoute.java
main/src/cgeo/geocaching/models/Route.java
main/src/cgeo/geocaching/models/RouteSegment.java

Remove `points` being unparcelled twice (maybe related to #8941)
Also adds own parcelling methods to `ManualRoute`.

fix unparcelling error in RouteSegment + add own parcelling to ManualRoute

---

main/res/layout/editwaypoint_activity.xml

fix #8969: allow negative bearing angles for waypoint projection

fix #8969: allow negative bearing angles for waypoint projection

---

main/src/cgeo/geocaching/location/GeopointParser.java
tests/src/cgeo/geocaching/location/GeoPointParserTest.java

We now separately parse the coordinates for each supported delimiter instead of normalizing the delimiters and parsing the coordinates once. Thus, we support parsing of coordinates with separators that contain other delimiters, e.g., the Locus Map format: Nxx° yy.zzz', Exx° yy.zzz'.

Fix #8845: Enable parsing for Locus Map coordinate format

---

main/src/cgeo/geocaching/log/LogCacheActivity.java
main/src/cgeo/geocaching/log/LogTemplateProvider.java
main/src/cgeo/geocaching/log/LogTrackableActivity.java
tests/src-android/cgeo/geocaching/log/LogTemplateProviderTest.java

- fix #7839
- don't show legacy number template for trackable logging (adapted to  normal NUMBER)
With this change, it doesn't count +1, if a LogEntry is provided and the log type is not found (or sth. equal)

[NUMBER template] don't add +1 for other types than FOUND_IT/ATTENDED/WEBCAM_PHOTO_TAKEN

---

mapswithme-api/build.gradle
mapswithme-api/lint.xml

- add lintOptions like in the other plugins
- delete 2 no more valid parameters
Info:
You can made local lint check by
(global or for sub project)
gradlew -q check
gradlew -q :cmapswithme-api:check

edit maps.me lint config

---

main/src/cgeo/geocaching/utils/LogWriter.java

Since logcat can hold strings up to a certain length only, it is not possible to log whole HTML pages returned by gc.com during the login process.
This PR adds a small logging utils class to log into separate files. Can be combined with the regular `Log` functions in c:geo: use `logWriter.d()` instead of `Log.d()` etc., or `logWriter.log()` to log to separate file only.
~PR also adds specific logging for the login process to (hopefully) catch the differences sometimes happening during login at gc.com. Tries to support research for #8818.~

add logWriter utility class for separate and extended logfiles

---

main/res/layout/dialog_text_checkbox.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/storage/extension/OneTimeDialogs.java
main/src/cgeo/geocaching/ui/dialog/Dialogs.java

fix #9013
New string (created from the comments in #9013):
Could someone please cross read if it sounds fine or any other changes are needed?

redesign onetime dialog and improve explanation text

---

main/res/values/strings.xml
main/src/cgeo/geocaching/CacheDetailActivity.java

Confirmation dialog extended, if "prevent waypoint extraction" is NOT set for this cache:
@eddiemuc 
Or is there an easy way to detect programatically if there would be any waypoints detected from personal note?
Then I would add this check and only show the extended info when "prevent waypoint extraction" is not set AND there would be waypoints detected/created from PN.

add warning about automatic waypoint extraction (fix #9026)

---

main/res/layout/cacheslist_item.xml

Following the discussion in https://github.com/cgeo/cgeo/issues/9029#issuecomment-696053797:
- double the width of the found marker line from 2dp to 4dp
- add a bottom margin of 10dp to more clearly separate this entry from the next
|Before|After|
|------|-----|
|![image](https://user-images.githubusercontent.com/3754370/93814485-e1903c00-fc54-11ea-8595-c408fe0cc533.png)|![image](https://user-images.githubusercontent.com/3754370/93814518-e94fe080-fc54-11ea-9dd7-ce97cfb20bf7.png)|

widen and shorten found marker line in cache list

---

main/src/cgeo/geocaching/utils/Formatter.java
main/src/cgeo/geocaching/utils/MapMarkerUtils.java

Follow-up to the discussion in #9029:
Replace the text "Offline" by floppy-disk overlay on the cache icon
|Before|After|
|------|-----|
|![image](https://user-images.githubusercontent.com/3754370/93814485-e1903c00-fc54-11ea-8595-c408fe0cc533.png)|![image](https://user-images.githubusercontent.com/3754370/93816273-9a577a80-fc57-11ea-8f3f-bb8b42c061d4.png)|

show floppy symbol instead of text offline in cache lists

---

main/src/cgeo/geocaching/utils/MapMarkerUtils.java

- restores the old "stored" icon overlay from before #9036,
- but leaves the textual info "Offline" removed.

restore old save icon overlay handling (fix #9050) (fix #9045)

---

tests/src-android/cgeo/watchdog/WatchdogTest.java

Their certificate is expired once again...

Disable extremcaching.com watchdog tests

---

main/src/cgeo/geocaching/CacheDetailActivity.java

After deleting all user-defined waypoints the ones stored in a personal note get recreated automatically (if not suppressed) - but only in memory (= bug). This PR fixes this by directly storing the cache to database, if any waypoints got recreated from personal note after calling the "delete user-defined waypoints" function.

store recreated waypoints to db (fix #9042)

---

main/src/cgeo/geocaching/connector/gc/GCLogin.java

See https://github.com/cgeo/cgeo/issues/8818#issuecomment-696409866
The "Your password or username/email is incorrect" string is always there and dynamically added to the div
with id #signup-validation-error via client-side JS, under the condition that this div is present in the page.
Fixes #8818

Properly detect failed signin because of invalid credentials in GC connector

---

main/res/values/strings.xml
main/src/cgeo/geocaching/connector/gc/GCLogin.java
main/src/cgeo/geocaching/enumerations/StatusCode.java

Detects if a captcha HTML code is found in the HTML returned during login process for gc.com and displays an suitable error message for this. Captcha check is the last check done before the "wrong username/password" check.

detect login captcha (related to #9056)

---

templates/private.properties

was forgotten when renaming in the keys.xml in abc8ad7dee9595e71dc5514678d6af2277500843,
see also https://github.com/bekuno/cgeo/blob/master/README.md#api-keys-installation

rename maps.api.key to maps.api2.key also in private.properties template

---

main/src/cgeo/geocaching/export/GpxSerializer.java
main/src/cgeo/geocaching/files/GPXParser.java

GSAK does not recognize with the current export, that a waypoint is user-defined. GSAK has an extension-element which indicates the user-flag.
This PR writes the element to the gpx.file and reads it on import to set the flag for user-defined waypoint.

sync flag for userdefined waypoint with GSAK

---

main/src/cgeo/geocaching/filter/AbstractFilter.java
main/src/cgeo/geocaching/storage/DataStore.java
main/src/cgeo/geocaching/utils/ContextLogger.java
main/src/cgeo/geocaching/utils/DebugUtils.java
main/src/cgeo/geocaching/utils/Log.java
tests/src-android/cgeo/geocaching/storage/DataStoreTestHelpers.java
tests/src/cgeo/geocaching/filter/SizeFilterTest.java

related to #9015: This PR
* improves in-memory-filtering performance for large cache lists
* adjusts logging in class DataStore
* adds logging of logcat command issued to extract c:geo logs via Settings-> System
* adds a helper class to create/remove artificial cache test data into developer databases

rel to #9015: impr in-memory-filter perf, adjusts datastore-logs, logs logcat command

---

main/res/layout/cacheslist_item.xml

- moves found marker to the total right also in selection mode
- align distance and favorite (& trackable) count vertically
| before | now |
|-|-|
| ![Screenshot_20200927_154633_cgeo geocaching (2)](https://user-images.githubusercontent.com/64581222/94370494-a5dff100-00f0-11eb-8b5b-665b2a5e3c87.jpg) | ![Screenshot_20200927_160709_cgeo geocaching (2)](https://user-images.githubusercontent.com/64581222/94370497-a8dae180-00f0-11eb-80ef-0134e2f2d11b.jpg)  |

[cachelist] center vertically and keep found marker allways right

---

main/src/cgeo/geocaching/filter/AbstractFilter.java
tests/src/cgeo/geocaching/filter/SizeFilterTest.java

related to #9015 and PR #9080: add missing unit test, adjust comment in AbstractFilter
As #okainov commented correctly in PR #9080, there should be corect commenting and unit testing also for large lists filtered to large lists (not only to slow lists). This PR adds that.
Thanks, @okainov , for the good assesment

related to #9015 and PR #9080: add missing unit test, adjust comment in AbstractFilter

---

main/src/cgeo/geocaching/export/GpxSerializer.java
main/src/cgeo/geocaching/files/GPXParser.java
main/src/cgeo/geocaching/models/Waypoint.java
tests/src/cgeo/geocaching/models/WaypointTest.java

For issue #6914 (user note for Waypoints):
because gpx and gsak has only one field for waypoint-notes, the server note (which is the description) and user note are concatenated on export. On import the note is analyzed and split up again in server note and the user note.
The same separator as for the PersonalNote is used ("\n--\n").
As on an empty server note, the first "\n" is removed within the "validate/trim"-functionality, there is a little "hack" to recognize this special case.
If someone has a better solution....
There is no merge of different user-notes on importing, so the user-note will be overwritten on merge
Probably this can be done in a different PR.

combine note and user note for export waypoint, on import split them up (#6914)

---

main/src/cgeo/geocaching/CacheDetailActivity.java

As we still have the currently unused resource strings for the personal note buttons in the `strings.xml`, I thought it would be useful to display them as a long click tooltip...
---
Further question: Should we display a tooltip for image buttons also in other places?

add tooltip to PN buttons

---

main/src/cgeo/geocaching/CacheMenuHandler.java

disable share menu on cache detail page for user-defined caches (fix #9095)

disable cache detail share menu for user-defined caches (fix #9095)

---

main/src/cgeo/geocaching/CompassActivity.java
main/src/cgeo/geocaching/models/Geocache.java

When gathering from another cache, if this cache wasn't detailed, and the other is,
the hint, etc. would never be copied. This fixes the case where the cache is stored
in the database.
Also, if there isn't a hint (or it isn't stored), don't show the show-hint icon on
the compass UI.

Fix #9069 - Hint is not displayed on compass view, when launched directly from map

---

main/src/cgeo/geocaching/SearchActivity.java

When entering a geocode, we now show the entered letters in upper case (same for trackable codes). The virtual keyboard shows lower-case letters though.

Transform geocode input to upper case

---

main/AndroidManifest.xml
main/build.gradle
main/res/values/preference_keys.xml
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/settings/Settings.java
main/src/cgeo/geocaching/storage/LocalStorage.java

This is a first step in trying to get a grip on the new storage framework requirements enforced with Android 11.
I've set up a new branch 'storage_framework' to be able to collaborate on this topic. Whether we merge this branch later on into `master` or put the findings into separate PR is to be decided later.
This PR includes the following first steps:
- Enforces using the new storage framework by setting `targetSDK` to 30 and removing the `requestLegacyExternalStorage` workaround.
- Creates a new base dir for public c:geo data beneath the `Download` directory.
- Tries to acquire access rights for all files in that directory and store the grant in settings.
- Tries to use this new base dir as replacement for our current base dir.
The first results are promising in some places, but not …

WIP grant access to base dir

---

main/src/cgeo/geocaching/export/TrailHistoryExport.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/PositionHistory.java
main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
main/src/cgeo/geocaching/maps/interfaces/PositionAndHistory.java
main/src/cgeo/geocaching/maps/mapsforge/MapsforgePositionAndHistory.java
main/src/cgeo/geocaching/maps/mapsforge/PositionDrawer.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/HistoryLayer.java
main/src/cgeo/geocaching/models/TrailHistoryElement.java
main/src/cgeo/geocaching/storage/DataStore.java

- stores the current timestamp in position history (unix epoch format)
- uses this timestamp on GPX export of position history

extend position history by timestamp + use timestamp on export (fix #9097)

---

main/res/values/strings.xml

as seen on CI console:
`/home/jenkins/slave/workspace/cgeo pull request/main/build/intermediates/incremental/mergeBasicDebugResources/merged.dir/values/values.xml:1523: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.`

missing string parameter & use string substitutes with positional parameters

---

main/res/layout/imageselect_activity.xml
main/src/cgeo/geocaching/ImageSelectActivity.java
main/src/cgeo/geocaching/log/LogCacheActivity.java
main/src/cgeo/geocaching/ui/ImageActivityHelper.java
main/src/cgeo/geocaching/utils/ImageUtils.java

Contains the NON-GUI-parts for #8978 :
* moves image select functionality in separate helper class `ImageActivityHelper` so it can be used elsewhere too
* ensures that EXIF information in images is ALWAYS removed
* adds delete-logic to ensure that no non-used image data is kept on users device
* some minor fixes (load image thumbnals asynchronously, ensure image default caption is correct on image deletion, center image view in image select activity)

related to #8978: fixing non-GUI-parts (img delete, remove exif, move img fct to helper)

---

build.gradle
main/build.gradle

- gradle plugin 4.0.1 to 4.0.2
for AS 4.0.2
- play-services-location 17.0.0 to 17.1.0
https://developers.google.com/android/guides/releases#september_23_2020
- spotbugs 4.5.0 to 4.5.1
https://github.com/spotbugs/spotbugs-gradle-plugin/releases/tag/4.5.1
- spotbugs-annotations 4.1.2 to 4.1.3
https://github.com/spotbugs/spotbugs/blob/4.1.3/CHANGELOG.md
- jackson 2.11.2 to 2.11.3
- leakCanary 2.4 to 2.5
https://square.github.io/leakcanary/changelog/#version-25-2020-10-01
- rxjava 3.0.6 to 3.0.7
https://github.com/ReactiveX/RxJava/releases/tag/v3.0.7

plugin updates

---

main/src/cgeo/geocaching/activity/AbstractActivity.java

When investigating #8752 I noticed a case where the onRestart method is overridden in AbstractActivity, but instead of calling the superclass method onRestart, the code calls onResume. 
This looks like a copy-paste error. I'm not sure if this bug has any consequences, but fixing it is surely the prudent thing to do. It looks like the bug was introduced in PR #8967.

Call the right superclass method when overriding onRestart

---

main/src/cgeo/geocaching/location/GeopointFormatter.java
main/src/cgeo/geocaching/models/Waypoint.java
tests/src/cgeo/geocaching/models/WaypointTest.java

fix #9193: hard-code point instead of language-specific separator

fix #9193: hard-code point instead of language-specific separator

---

main/res/layout/coordinates_equations.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/ui/CalculatorVariable.java
main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateDialog.java

Adds a button "lower-case" to the waypoint calculator dialog, which convert all variables in formulas (left pane) to lower case:

WP calc: lower-case all equation variables on demand (fix #9213)

---

main/src/cgeo/geocaching/models/Geocache.java

Root cause was a "change" flag being reset under certain circumstances.

update wp page on extract waypoints (fix #9184)

---

main/src/cgeo/geocaching/export/TrailHistoryExport.java
main/src/cgeo/geocaching/models/TrailHistoryElement.java

- store timestamp based on GMT internally (substract timezone delta)
- write timestamp based on GMT on export (set GMT timezone for export)

respect timezone info in position history (fix #9143)

---

main/project/xsd/cgeo.xsd
main/src/cgeo/geocaching/export/GpxSerializer.java
main/src/cgeo/geocaching/files/GPXParser.java
tests/res/raw/gc31j2h_wpts_empty_coord.gpx
tests/res/raw/ocddd2_empty_coord.gpx
tests/src-android/cgeo/geocaching/export/GpxSerializerTest.java
tests/src-android/cgeo/geocaching/files/GPXImporterTest.java
tests/src-android/cgeo/geocaching/files/GPXParserTest.java

fix #8409 
Waypoints with no / empty coordinates are no exported.
Since the gpx-schema does not allow empty lat / lon -attributes, "0" is written like OKAPI does.
In addition a cgeo-attribute is written, that indicates the empty coordinates explicitly. Hence the cgeo.xsd was changed.

(fix #8409) : export waypoint without coordinates

---

main/src/cgeo/geocaching/export/TrailHistoryExport.java
main/src/cgeo/geocaching/models/TrailHistoryElement.java
main/src/cgeo/geocaching/storage/DataStore.java

- extends db scheme to store elevation info for position history (default = 0.0)
- use the stored info on GPX export of position history

add elevation info to position history (fix #9140)

---

main/src/cgeo/geocaching/location/GeopointParser.java
main/src/cgeo/geocaching/location/GeopointWrapper.java
main/src/cgeo/geocaching/models/Waypoint.java
tests/src/cgeo/geocaching/location/GeoPointParserTest.java
tests/src/cgeo/geocaching/location/GeoPointWrapperTest.java
tests/src/cgeo/geocaching/models/WaypointTest.java

* use modifed string (after spaces are removed via GeopointParser:removeSpaceAfterSeparators) to extract user note from text. if there were spaces after points in the text, the determination of end-position was wrong
* use GeopointWrapper for transporting information about appropriate text and substring instead of Triple -> move to own file and add apprpriate text for start-end-position (different text due to parsedInput)

fix bug in extracting waypoint and user note from text (fix #9157)

---

main/src/cgeo/geocaching/export/IndividualRouteExport.java
main/src/cgeo/geocaching/export/TrailHistoryExport.java

#9238 add GPX output formatting for cache exports etc. only.
This PR adds it for exports of individual routes and position history.

add GPX formatting to position history / indiv. route exports

---

main/src/cgeo/geocaching/settings/ReceiveMapFileActivity.java

Map downloader now deletes the temporary map file in "downloads" after the copy operation has completed successfully.
(also increases buffer size for copy)

delete temporary map file after successful copy (fix #8712)

---

main/src/cgeo/geocaching/connector/gc/GCConstants.java
main/src/cgeo/geocaching/connector/gc/GCParser.java

- supports old TB page HTML (having TB type as "alt" attribute)
- and new TB page HTML (having TB type only in "title" tag)

support loading new TB pages (fix #9263)

---

main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/interfaces/MapSource.java
main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

related to #9270: use own MapFiles for map attribution and close them

related to #9270: use own MapFiles for map attribution and close them

---

main/src/cgeo/geocaching/AboutActivity.java
main/src/cgeo/geocaching/maps/AbstractMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/maps/routing/Routing.java

related to #9270: fix memory leak in Routing
The way passing of callback to Routing was handled, this lead to Routing keeping a reference to NewMap object even after destroy. Also, only the callback of last Activity calling "connect" was maintained. Both is fixed with this PR.

related to #9270: fix memory leak in Routing

---

main/src/cgeo/geocaching/enumerations/WaypointType.java
main/src/cgeo/geocaching/models/Waypoint.java
tests/src/cgeo/geocaching/models/WaypointTest.java

fix #9266: prevent parsing waypoints to type 'own'
Waypoints of type "reference Point" with name "reference point" in it where accidentally parsed as wptype "own" because it uses the same translated name. This lead to such waypoints becoming "own" when parsing them repeatedly from PN. This leads to switch type to "Parking" in waypoint edit dialog because "own" is not an allowed type in that list.
Prevented this by not allowing "own" (and "Original") as parsed wptypes any more. All allowed wptypes in parsing have different translations now

fix #9266: prevent parsing waypoints to type 'own'

---

main/src/cgeo/geocaching/connector/gc/GCWebAPI.java
main/src/cgeo/geocaching/location/Viewport.java

Returns an empty search result if viewport is just a dot (top/left equals bottom/right). The web search does not get called in this case.

avoid search for empty viewport (rel. to #9275)

---

main/res/values/strings.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/settings/Settings.java

Intermediate step towards #7836 (remove old mapsforge):
- remove settings for MF0.3
- querying the "use old MF map" switch always returns false
By this old Mapsforge map is hidden without actually removing its code.

hide old mapsforge implementation (without actually removing it yet)

---

main/src/cgeo/geocaching/maps/mapsforge/v6/MfMapView.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/settings/Settings.java

related to #9288: preserve zoom level
This PR is supposed to make the NewMap preserve last zoom levels and restore them when map is reopened.
However, I really wonder whether I oversaw something in the code, because if I fixed this the right way this means that zoom preserving was never enabled for NewMap before... and I cannot really believe that.
@moving-bits : can you please take a close look at this one?

related to #9288: preserve zoom level

---

main/src/cgeo/geocaching/CompassActivity.java
main/src/cgeo/geocaching/export/TrailHistoryExport.java
main/src/cgeo/geocaching/ui/CalculatorVariable.java
main/src/cgeo/geocaching/utils/ContextLogger.java
main/src/cgeo/geocaching/utils/Formatter.java
main/src/cgeo/geocaching/utils/Log.java

- categorie Correctness
- type DefaultLocale:
Implicitly using the default locale is a common source of bugs: Use `String.format(Locale, ...)` instead
- CalculatorVariable.java
- CompassActivity.java
- Log.java
- type SimpleDateFormat:
To get local formatting use `getDateInstance()`, `getDateTimeInstance()`, or `getTimeInstance()`, or use `new SimpleDateFormat(String template, Locale locale)` with for example `Locale.US` for ASCII dates.
- ContextLogger.java
- Formatter.java
- TrailHistoryExport.java
@eddiemuc @moving-bits 
Please check that the changes are set as intended in your PR´s.

lint changes/fixes

---

main/src/cgeo/geocaching/connector/internal/InternalConnector.java
main/src/cgeo/geocaching/maps/google/v2/GoogleMapView.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

fix #8678
One question though: I found the following comment: 
```
// temporary workaround for on demand migration of the old "go to" history
// should be removed after some grace period (maybe summer 2020?)
```
Should I remove the migration code along with my changes, or should we leave it inside for a few more months?

store UDC's from map to "user-defined caches" list

---

main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/models/Geocache.java

Related to https://github.com/cgeo/cgeo/issues/9289#issuecomment-719698767:
- remove "refresh" and "extract waypoints" menu entries for UDC
- remove "refresh" symbol in popup for UDC

remove some cache menu entries for UDC

---

main/src/cgeo/geocaching/settings/Settings.java

fix #9332: remove all restrictions for initial map zoom, comment code for future coders taggling this area

 fix #9332: remove all restrictions for initial map zoom

---

main/src/cgeo/geocaching/models/Geocache.java
main/src/cgeo/geocaching/models/Waypoint.java
tests/src-android/cgeo/geocaching/models/GeocacheTest.java
tests/src/cgeo/geocaching/models/WaypointTest.java

This PR improves the extraction of waypoint from PCN for own waypoint with empty coords:
Own waypoint with empty coords will be extracted. 
If already a waypoint with same name and type exists, the new waypoint will not be added.
(fix #9338)
So user can add waypoint with formula in PCN and it will be extracted to user-note of waypoint:
e.g. 
@Final (F) (NO-COORD)
"N50 57.(A+E)(B+B)(E) W001 21.(D)(B+D)(A+B+B)"

extract own wp with empty coords from PCN (fix #9338)

---

main/src/cgeo/geocaching/connector/gc/GCConstants.java
main/src/cgeo/geocaching/connector/gc/GCParser.java
tests/src-android/cgeo/geocaching/CgeoApplicationTest.java

fixes #9318
Parse Type, Name, Geocode, Difficulty, Terrain and Size for PM only caches - needed for corectly displaying the logCacheActivity and for supporting log templates...

avoid crash when trying to log a PM cache as basic member

---

main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java
main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapView.java
main/src/cgeo/geocaching/settings/ReceiveMapFileActivity.java
main/src/cgeo/geocaching/settings/Settings.java
main/src/cgeo/geocaching/settings/SettingsActivity.java
tests/src-android/cgeo/geocaching/SettingsTest.java

related to #8457: let Mapsforge use Uris instead of Files
Refactoring towards to SAF, no functional change: let MapsforgeMapProvider use Uris instead of Files

related to #8457: let Mapsforge use Uris instead of Files

---

main/build.gradle
main/src/cgeo/geocaching/AboutActivity.java
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/EditWaypointActivity.java
main/src/cgeo/geocaching/TrackableActivity.java
main/src/cgeo/geocaching/calendar/CalendarEntry.java
main/src/cgeo/geocaching/helper/HelperAppAdapter.java
main/src/cgeo/geocaching/log/LogsViewCreator.java
main/src/cgeo/geocaching/log/TrackableLogsViewCreator.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/models/Geocache.java
main/src/cgeo/geocaching/ui/CacheDetailsCreator.java
main/src/cgeo/geocaching/ui/ImagesList.java
main/src/cgeo/geocaching/utils/HtmlUtils.java
main/src/cgeo/geocaching/utils/ImageUtils.java
main/src/cgeo/geocaching/utils/LiUtils.java
main/src/cgeo/geocaching/utils/TextUtils.java
tests/src-android/cgeo/geocaching/test/CgeoTestsActivity.java

Since API24 the plain Html.fromHtml(string) is deprecated in favor of Html.fromHtml(string, int).
There is a wrapper class HtmlCompat where the method switch is done according to the Build version of the device.
The implementation uses now only the int FROM_HTML_MODE_LEGACY (value 0).
Maybe we can optimize later the code using some of the new parameters to solve issue #7306.

use HtmlCompat.fromHtml instead of deprecated Html.fromHtml

---

main/res/drawable/icon_bcg.xml
main/res/layout/map_distanceinfo.xml
main/res/values/preference_keys.xml
main/res/values/styles.xml
main/src/cgeo/geocaching/maps/MapDistanceDrawerCommons.java
main/src/cgeo/geocaching/maps/mapsforge/v6/DistanceView.java
main/src/cgeo/geocaching/settings/Settings.java

Optionally display current distance to navigation target in a super-sized font at the maps' head:
Supersize display can be switched either by using a menu item (Map Settings => Supersize distance) or by tapping on the distance shown in the upper right corner.

supersize distance view (fix #9282)

---

main/res/values/preference_keys.xml
main/src/cgeo/geocaching/maps/MapDistanceDrawerCommons.java
main/src/cgeo/geocaching/settings/Settings.java

- make all (up to) three tiny distance fields clickable
- add toggle cycle: first distance supersized => second distance supersized (if available) => no distance supersized

toggle supersize distances (fix #9367)

---

main/res/layout/map_distanceinfo.xml
main/res/values/styles.xml

- auto-resized font size in a range from 64sp to 120sp
- sets a smaller default font size for supersized distance display (72sp instead of 96sp) (fallback)

auto-adjust super-sized distance font (fix #9380)

---

main/res/layout/map_distanceinfo.xml
main/src/cgeo/geocaching/maps/MapDistanceDrawerCommons.java

follow-up to #9380, see https://github.com/cgeo/cgeo/issues/9380#issuecomment-727269485
bottom-align route distance info view if in supersize mode, to stay in white space.
Only applies if "show straight distance" is active, as otherwise the route distance is the only distance displayed beside the supersized one and can stay top-right in that case.

bottom-align route distance in supersize mode

---

main/res/layout/map_distanceinfo.xml
main/res/layout/map_mapsforge_v6.xml
main/res/values/styles.xml

- show second distance view below super size view
- move supersized text a bit down within its view to separate it a bit more from top text (target name, distance)

show second distance view below super size view

---

main/src/cgeo/geocaching/utils/ImageUtils.java

fix #9400: add zero-division guard for images with width and height 0 into ImageUtils

fix #9400: add zero-division guard for images with width and height 0 into ImageUtils

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

- Support AS 4.1.1,
see https://androidstudio.googleblog.com/2020/11/android-studio-411-available.html
The Issue #9273 is not fixed in AS 4.1.1.
- gradle 6.7 to 6.7.1
see https://docs.gradle.org/6.7.1/release-notes.html
- gradle plugin 4.1.0 to 4.1.1 (for AS 4.1.1)
(no ReleaseNotes)

gradle updates

---

main/src/cgeo/geocaching/MainActivity.java

This was already implemented but not working, as the icon was disabled as logo instead of an up Indicator. 
Just for info, this is the actual code part which was designed to start the AboutActivity...
https://github.com/cgeo/cgeo/blob/cac5eb2040623da6c66620eb2850b49b6afe21cc/main/src/cgeo/geocaching/MainActivity.java#L501-L507

open about activity on click at c:geo's logo

---

main/res/layout/map_distanceinfo.xml
main/res/layout/map_mapsforge_v6.xml
main/res/values/styles.xml
main/src/cgeo/geocaching/maps/MapDistanceDrawerCommons.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

Refactor map distance views:
- target info (OSM only) and non-supersized distance get displayed without extra grey background when in supersize mode
- distances in small views are right-aligned
- distance type indicators are displayed in the same TextView as their distance (fixes #9381)
- lots of code and layout file cleanup
Some screenshots of different combinations:

refactor map distance views

---

main/src/cgeo/geocaching/files/GPXTrackOrRouteImporter.java

"Unload" track (= remove remembered trackfile name from settings) on error loading trackfile

Remove track setting on unsuccessful load (fix #9410)

---

main/res/layout/view_settings_add.xml
main/res/menu/view_settings.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/settings/ViewSettingsActivity.java
main/src/cgeo/geocaching/ui/dialog/Dialogs.java
main/src/cgeo/geocaching/utils/SettingsUtils.java

- allow negative integer values
- remove "enter edit mode" icon when in edit mode
- allow adding new items
- apply standard `DialogAlert` theme to edit / add / delete dialogs
(note: `Dialogs.newBuilder()` can now be used for other `AlertDialog` usages as well)

Improve settings debug helper (fix #9123)

---

main/src/cgeo/geocaching/maps/PositionHistory.java
main/src/cgeo/geocaching/sensors/GeoData.java

do not record points coming from `HOME_PROVIDER` or `INITIAL_PROVIDER` in position history

skip artificial track points in position history (fix #9360)

---

main/src/cgeo/geocaching/export/FieldNoteExport.java
main/src/cgeo/geocaching/export/GpxExport.java
main/src/cgeo/geocaching/export/IndividualRouteExport.java
main/src/cgeo/geocaching/export/TrailHistoryExport.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/ui/dialog/Dialogs.java
main/src/cgeo/geocaching/utils/BackupUtils.java
main/src/cgeo/geocaching/utils/MapDownloadUtils.java

Many of our dialogs use the default theme implicitly, not the c:geo theme. This PR fixes this for a couple of `AlertDialog`s by using `Dialogs.newBuilder()` instead of `new AlertDialog.Builder()`.

fix several AlertDialog themes

---

main/res/menu/map_activity.xml
main/res/values/preference_keys.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/models/ManualRoute.java
main/src/cgeo/geocaching/settings/Settings.java
main/src/cgeo/geocaching/utils/IndividualRouteUtils.java

OSM implementation for #9281: Add option to "Individual route" map menu to automatically set the first route point as navigation target.

add auto-target option for individual routes on OSM (rel. to #9281)

---

main/src/cgeo/geocaching/utils/BackupUtils.java

Reverts styling of "restore database/settings" dialog to pre-#9422 state. Still not correct, as it's using the dark theme colors then, but at least readable even with light theme activated.

revert part of #9422 for BackupUtils

---

main/src/cgeo/geocaching/SelectMapfileActivity.java
main/src/cgeo/geocaching/helper/QueryMapFile.java
main/src/cgeo/geocaching/maps/AbstractMapSource.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/MapProviderFactory.java
main/src/cgeo/geocaching/maps/google/v2/GoogleMapProvider.java
main/src/cgeo/geocaching/maps/google/v2/GoogleMapView.java
main/src/cgeo/geocaching/maps/interfaces/MapSource.java
main/src/cgeo/geocaching/maps/mapsforge/AbstractMapsforgeMapSource.java
main/src/cgeo/geocaching/maps/mapsforge/MapGeneratorInternal.java
main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/settings/ReceiveMapFileActivity.java
main/src/cgeo/geocaching/settings/Settings.java
main/src/cgeo/geocaching/settings/SettingsActivity.java
tests/src-android/cgeo/geocaching/SettingsTest.java
tests/src-android/cgeo/geocaching/cgeo/geocaching/maps/MapsforgeMapProviderTest.java

related to #8457: remove map path from settings as one of many preliminaries for introducing SAF.
Additional cleanups:
* redesign mapsource-preselection based on stringids 
* redesigned numericId logic such that numers are guaranteed to be uniqueand uncolliding with other ressourceids
* introducing test class for MapsForgeProvider
* caching results of mapfile availablilty and map attributions to reduce repeated map file parsing

related to #8457: remove map path from Settings

---

main/src/cgeo/geocaching/utils/BackupUtils.java

#9439 had unfortunately introduced a bug, that the backup restore dialog can't be launched from within the MainActivity after a fresh installation without a crash... This problem will be solved with this PR.

avoid crash when starting restore dialog from MainActivity

---

main/res/values/strings.xml

renames the "hide individual track" menu entry to "hide GPX track/route" to make it consistent with the "GPX track/route" submenu

rename hide individual track to hide GPX track/route

---

main/res/values/strings.xml
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/models/ManualRoute.java
main/src/cgeo/geocaching/settings/Settings.java
main/src/cgeo/geocaching/utils/IndividualRouteUtils.java

On manually setting a target using the cache popup: Unset the "auto-target" for individual route and display an info message, if it has been set currently.
(Also renames the `getAutotargetIndividualRoute()` to the more standard compliant `isAutotargetIndividualRoute()`)

unset autotarget on manually setting a target

---

main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/CacheMenuHandler.java
main/src/cgeo/geocaching/models/Geocache.java

- fix #9453
- remove duplicated method in geocache class (`getCgeoUrl()` and `getUrl()` had both returned `getConnector().getCacheUrl(this)`, so I merged them into one...)

don't show "open in browser" for UDC's

---

main/res/layout/map_settings_item.xml

Fixes bug, that checkbox value is not applied when directly clicking on it. This PR sets `clickable` to "false" so that a click on the checkbox is handled by the superordinate view group which contains the on click listener...

Fixes map popup checkbox bug

---

main/src/cgeo/geocaching/maps/MapSettingsUtils.java

As the map popup settings are not "dangerous", there is no need why an explicit confirmation via the OK button should be requested (also mentioned by @MagpieFourtyTwo)...

apply map popup changes also when closing via clicking outside

---

main/res/values/strings.xml

The configuration of app directories has been moved out of `Settings > System`. Therefore, I updated the string correctly...

update outdated string

---

main/src/cgeo/geocaching/utils/FileUtils.java

fix #7404: switch field note encoding to UTF167LE

fix #7404: switch field note encoding to UTF167LE

---

main/res/layout/map_distanceinfo.xml

Setting a target from cache/waypoint popup could lead to overlapping target/distance info if the cache/waypoint title was too long.
This PR adjusts margins and widths of the related views to avoid this.

avoid overlapping of target and distanceinfo

---

main/src/cgeo/geocaching/AboutActivity.java
main/src/cgeo/geocaching/utils/DebugUtils.java
main/src/cgeo/geocaching/utils/ShareUtils.java

#9471 and #9495 had introduced the same feature, once at master and once at release. I should have rather targeted #9471 to release, then there wouldn't have been merge conflicts at all...  Sorry for that and thanks @moving-bits for stepping through merge hell!
This PR merges the duplicated methods and provides some cleanup...

remove duplicated method

---

main/res/menu/map_activity.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/models/ManualRoute.java
main/src/cgeo/geocaching/utils/IndividualRouteUtils.java
main/src/cgeo/geocaching/utils/functions/Action2.java

Menu item is shown if either a manual target is set (coming from cache/waypoint popup) or if the "auto set target" is set for an individual route. (Currently both OSM only)
When using this menu entry, both possible individual targets are cleared (and the menu entry hidden).

add map option to clear individual targets

---

main/res/values/themes.xml

applies to menu headline as well as to check boxes and radio items in menus
And will, after merging to master, also apply for the map quick settings popup:

apply colorAccent to Google Maps

---

main/res/layout/map_settings_dialog.xml
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/MapSettingsUtils.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/utils/IndividualRouteUtils.java

@MagpieFourtyTwo
Currently the last section ("individual route" + checkbox) is only shown if either
- an individual route is defined and/or
- "auto target individual route" is activated
Or should we always show this part?

make auto-target available in map quick settings (fix #9521)

---

main/src/cgeo/geocaching/CacheDetailActivity.java

Attempts to fix #9509 - do not create the new waypoint in a background thread, as that cannot upgrade the UI elements.

avoid crash on adding waypoint via clipboard (fix #9509)

---

main/src/cgeo/geocaching/CacheDetailActivity.java

Attempts to fix #9463 - do not create the new waypoint in a background thread, as that cannot upgrade the UI elements.

avoid crash on adding waypoint from current (fix #9463)

---

main/res/layout/preference_button.xml
main/res/values/themes.xml
main/res/xml/preferences.xml

If we want to make other texts in preferences look like buttons as well, we only need to add the `android:layout="@layout/preference_button"` in the appropriate places of `main/res/xml/preferences.xml` now.
"title" is required and used as button label, "summary" is supported additionally (to be display below the button).
The only thing that might be irritating a bit at first is that not only the button is clickable, but the whole preference line (as is the case with all preferences).

make backup/restore buttons look like buttons (fix #9486)

---

main/build.gradle
main/res/values/preference_keys.xml
main/res/values/strings.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/activity/AbstractActivity.java
main/src/cgeo/geocaching/connector/oc/OkapiClient.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/settings/Settings.java
main/src/cgeo/geocaching/settings/SettingsActivity.java
main/src/cgeo/geocaching/utils/ApplicationSettings.java
main/src/cgeo/geocaching/utils/SystemInformation.java
tests/src-android/cgeo/geocaching/connector/oc/OkapiClientTest.java

Adds an option to set c:geo's language independently from system language setting. Switches language on
- main screen
- settings activity
- map activities
accordingly.
Addresses #7991 ~and #9197~.
For now it's a proof-of-concept only. Language can be set by entering an ISO code (eg.: "de" for German) in "settings" - "appearance" - needs to be made more user-friendly later on.
Precedence is:
- "use English"
- user-defined locale (if "use English" is unchecked)
- system-default locale (if "use English" is unchecked and user-defined locale is empty)

Add option to user-select one of the integrated translations instead of auto-select by system-default

---

main/src/cgeo/geocaching/settings/SettingsActivity.java

I first thought about restarting c:geo directly after changing the language setting, but then I decided against it. With this implementation c:geo will be restarted automatically when leaving the settings activity. Therefore, it's easier to change it back if you accidentally select the wrong one...
...and the same is done for the "bigSmileys" option too.

restart c:geo after language change automatically when leaving settings

---

main/src/cgeo/geocaching/settings/SettingsActivity.java
main/src/cgeo/geocaching/utils/ProcessUtils.java
main/src/cgeo/geocaching/utils/ShareUtils.java

We currently have two identical functions used for opening a URL in browser:
- `ShareUtils.openUrl(Context, String)`
- `ProcessUtils.openUri(String, Activity)`
While `ShareUtils.openUrl` has optional custom tabs support and is used at most places the equivalent in `ProcessUtils ` has fallen into oblivion and is to be removed herewith...

remove outdated function

---

main/src/cgeo/geocaching/maps/AbstractMap.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/MapDistanceDrawerCommons.java
main/src/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java
main/src/cgeo/geocaching/maps/interfaces/MapActivityImpl.java
main/src/cgeo/geocaching/maps/interfaces/MapViewImpl.java

Setting a navigation target from cache/waypoint popup in Google Maps, similar to what we have for OSM maps.
Working mostly, but having some rough edges still.

allow setting target from cache/waypoint popup for GMv2 (fix #7969)

---

main/res/values/strings.xml

We should include, that the user shall also provide a description of the error.
Otherwise I assume we might get a lot of mails with sysinfo and logfiles but without additional details.

Request error description from user for problem report

---

main/lint.xml

Hide these warnings - the next complete update from crowdin will update the files accordingly.
Don´t hide in the english strings.xml.

avoid lint warning `UnusedResources` for non english strings.xml

---

main/src/cgeo/geocaching/maps/google/v2/GoogleMapObjectsQueue.java

Check if object to be drawn is already in map of drawn objects. If yes, do not draw the same object again.

avoid forgotten accuracy circles in GMv2 (fix #9552)

---

main/src/cgeo/geocaching/utils/Formatter.java

Only shorten favpoints beginning with 10k, because:
- That was my original proposal in #9466 (only had a typo in my proposal there)
- There is a higher probability to have several caches with >999 fav points in an area, so you can still compare the exact numbers on list. Caches with >9999 are more rare, so for most users it will be rare to see those on lists (as of today)
- There is enough room for 4 digits but not for 5

Related to #9466: Only use k-factor above 9999 favorite points

---

main/src/cgeo/geocaching/files/GPXParser.java
tests/res/raw/lab_stary_prostejov.gpx
tests/src-android/cgeo/geocaching/files/GPXParserTest.java

This PR fixes #9336, where for a labcache the geocode is wrongly found in the description. 
For finding a valid geocode the name, the description and the comment is used. 
This PR allows the unknown-connector (which allows any uppercase 5-letter-word as geocode) only for the name, but not for description and comment.

UNKNOWN_CONNECTOR not used for finding geocode in description

---

main/res/values/strings_not_translatable.xml

Updated contributors' list
- Updated active contributors list according to https://github.com/cgeo/cgeo/graphs/contributors?from=2020-01-01&to=2020-12-31&type=c and other known active contributors (tester etc.)
- added some missing Github links

update contributors' list

---

main/res/layout/gpx_export_fragment.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/export/FieldNoteExport.java
main/src/cgeo/geocaching/export/GpxExport.java
main/src/cgeo/geocaching/export/IndividualRouteExport.java
main/src/cgeo/geocaching/export/TrailHistoryExport.java
main/src/cgeo/geocaching/settings/Settings.java
main/src/cgeo/geocaching/ui/dialog/Dialogs.java
main/src/cgeo/geocaching/utils/DebugUtils.java
main/src/cgeo/geocaching/utils/MapUtils.java
main/src/cgeo/geocaching/utils/ShareUtils.java

I'm on the go to unify the design of all different export functionalities, to have a consistent UX...
GPX export for example has IMHO two main problems:
- "Open share menu after GPX export" may not be clear for everyone, and you have to decide in advance on something that will only be relevant later on
- The toast "GPX exported to: ..." is way too quick, so it has happened to me several times that I had to repeat the export, because I had too little time to remember the file name
Therefore, it makes sense to use the same UI as we already have for backup and logfiles:
To avoid additional clicks, can we possibly avoid the following pop-up completely. Is there a real reason why you should not include the found status? We can either move the function to the settings or remove it completely. I …

unify design of different export functionalities

---

main/res/menu/cache_options.xml
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/CacheMenuHandler.java

do not show 'delete' and 'prevent waypoints from note' entries in cache popup

clean-up cache popup (fix #9578)

---

main/res/layout/authorization_credentials_activity.xml

While working on a different issue I stumbled upon authorization activity still using the old c:geo icon => updated it

update authorization activity icon

---

main/src/cgeo/geocaching/SplashActivity.java

c:geo did not have set any transitions for `SplashActivity` calling `MainActivity`, but there seem to some system-specific default transitions. This PR sets the activity options to null, which should disable any transition.
@Lineflyer @SammysHP 
Regarding #9563 and #9392: As I can reproduce neither of it in my test environment - can you cross-check with this PR on the devices where those issues occurred? Thanks.

disable transitions for splashscreen

---

main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

Show "recalculating route" on map quick settings close only, if routing mode has changed and either individual route is configured and/or GPX track/route has been loaded.

show toast only if individual route or track loaded (fix #9594)

---

main/res/values/strings_not_translatable.xml
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/InstallWizardActivity.java
main/src/cgeo/geocaching/apps/cache/WhereYouGoApp.java
main/src/cgeo/geocaching/helper/HelperApp.java
main/src/cgeo/geocaching/helper/QueryMapFile.java
main/src/cgeo/geocaching/helper/UsefulAppsActivity.java

Refactoring:
- Some package names and URL had been stored twice in the app due to `HelperApp` requiring a string and other places requiring a resource id => refactored `HelperApp` to resource id
- Moved all package names to strings_not_translatable, removing duplicates along the way.
- Consistently named all Play Store package names starting with `package_` prefix.

remove duplicates in package names

---

main/build.gradle
main/src/cgeo/geocaching/apps/AbstractLocusApp.java

- Update the Locus integration to the 0.9.x series (refactoring Locus)
- Update the CacheType's
- Update the deprecated storage access for sending huge data to Locus (>1000 Caches)
The old implementation should not work with Android 10 and 11 (not tested)
(see https://developer.android.com/reference/android/os/Environment#getExternalStorageDirectory() )
Migrate to `context.getExternalFilesDir()`, therefore changed the data file location:
old path:
`/storage/emulated/0/Android/data/menion.android.locus.api/files/showIn.locus`
new path:
`/storage/emulated/0/Android/data/cgeo.geocaching/files/showIn.locus`
@Lineflyer: Please test using devices with Android 10 and 11
@eddiemuc: Please check if this fits in the SAF implementation

Update the Locus integration

---

tests/src-android/cgeo/geocaching/connector/oc/OkapiClientTest.java

use OC4711 instead of OU0331 to mitigate the current certificate problem with opencaching.us site

adapt OKAPI test to use OC instead of OU (fix #9630)

---

main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/storage/extension/OneTimeDialogs.java
main/src/cgeo/geocaching/ui/dialog/Dialogs.java
main/src/cgeo/geocaching/utils/BackupUtils.java

Extends the OneTimeDialogs framework so that dialogs can also be displayed only for new or updating users.
I have configured the existing OneTimeDialogs like this:
- explain offline found counter --> all users
- database overwrite notice --> of course also all users
- map quick settings --> only upgrading users
also see https://github.com/cgeo/cgeo/pull/9597#issuecomment-751507462
Sorry, but this PR will lead to one minor merge conflict, when merging it back to master. Unfortunately unavoidable...

Extends the OneTimeDialogs framework

---

main/src/cgeo/geocaching/connector/gc/GCParser.java
main/src/cgeo/geocaching/connector/oc/OkapiClient.java
main/src/cgeo/geocaching/connector/su/SuParser.java
main/src/cgeo/geocaching/files/GPXParser.java
main/src/cgeo/geocaching/log/LogCacheActivity.java
main/src/cgeo/geocaching/storage/DataStore.java
tests/src-android/cgeo/geocaching/export/ExportTest.java
tests/src-android/cgeo/geocaching/storage/DataStoreTest.java
tests/src-android/cgeo/geocaching/storage/DataStoreTestHelpers.java

Solves #9524, but also merges old logs on importing from other GPX files or updating a cache using the connector.
Merging is done by per-log deleting old logs from same author, same date, same type before storing the new logs.

merge old cache logs on importing GPX/PQ (fix #9524)

---

main/res/values/strings.xml
main/res/values/strings_not_translatable.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/MapUtils.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/settings/Settings.java
main/src/cgeo/geocaching/storage/extension/OneTimeDialogs.java
main/src/cgeo/geocaching/ui/dialog/Dialogs.java
main/src/cgeo/geocaching/utils/BackupUtils.java
main/src/cgeo/geocaching/utils/MapUtils.java

- sets default for "on long tap" map option to true
- shows a OneTimeMessage on opening map, content depending on current setting (see screenshots)
- extends the OneTimeMessage framework to (optionally) support a "more information" URL (see screenshots)
- code deduplication: moves the existing map OneTimeMessage messages to `maps/MapUtils`
"More information" will take to our user manual, map settings section.

set "on long tap" option default to true + add OneTimeMessage (fix #9615)

---

main/res/layout/dialog_title_button_button.xml
main/res/layout/emojiselector.xml
main/res/layout/emojiselector_item.xml
main/res/menu/cache_options.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/models/Geocache.java
main/src/cgeo/geocaching/storage/DataStore.java
main/src/cgeo/geocaching/storage/extension/EmojiLRU.java
main/src/cgeo/geocaching/utils/DisplayUtils.java
main/src/cgeo/geocaching/utils/EmojiUtils.java
main/src/cgeo/geocaching/utils/MapMarkerUtils.java

Allows using unicode characters as cache markers on a per-cache base.
Fixes #9523 and gives a mitigation for other issues requesting to set individual cache icons without the hassle of handling user-selected image files, and without blowing c:geo's APK size.
- New menu entry in cache menu "Select cache icon"
- opens a popup where you can select an "icon" (= unicode character) from a given list (*)
- at the bottom of this popup a "recently used" list builds (max. 10 entries)
- you can reset the chosen icon to default in this popup
- the selected "icon" is used as cache marker on the map (and other places)
- on the map it uses the usual insets, and the "squared" white background (the same that is used for OC caches and UDC)
- "big smileys" option has precedence over the user-selected icon
- …

option to use individual cache markers (fix #9523)

---

README.md

The link is already included at the end, but since the chat is also mentioned here, it would make sense to insert the link here as well...

add link to IRC chat to the Readme

---

main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

Fixes two errors on OSM custom theme loading:
- "Default" is now selectable and gets stored, even if no other theme is available
- On theme loading error map theme setting is reverted to "Default" (thus you won't get the loading error message any longer on subsequent map starts)

Fixes for theme loading errors (fix #3302)

---

main/src/cgeo/geocaching/connector/gc/GCParser.java

Posted in https://github.com/cgeo/cgeo/issues/9583#issue-774084772
> I do also see strange cache titles (e.g. for GC5G596) as presumably c:geo cannot resolve the unicode characters as it cannot open the PM cache.
Indeed, I forgot to unescape html characters while implementing the parsing for PM-only caches... This is now fixed with this PR!

correctly unescape HTML characters when parsing PM-only caches

---

main/src/cgeo/geocaching/settings/Settings.java

fix #9655: accomodate for legacy values in log image scale settings

fix #9655: accomodate for legacy values in log image scale settings

---

main/res/values/strings.xml

Changed only on `master` as it is no urgent change.

Fix #9683 - Make GPX track/route wording consistent

---

main/res/values/strings.xml
main/src/cgeo/geocaching/EditWaypointActivity.java
main/src/cgeo/geocaching/enumerations/WaypointType.java
main/src/cgeo/geocaching/models/Geocache.java
main/src/cgeo/geocaching/models/Waypoint.java

Optimizes name handling for new waypoints:
- uses a short name for new waypoints (as described in https://github.com/cgeo/cgeo/issues/9041#issuecomment-697926825, "new WP default name")
- counter for new waypoints is no longer wp type-specific, but "global" (within this cache)
- detecting the highest given number is no longer limited to 30 but done with a regular expression, so if a wp is named "Stage 47", the next waypoint will get index 48.
- for comparison old + new name scheme are used to stay compatible
I did not swap the order of name and number, as this would either create confusion or require a migration of the existing waypoints. Let's see, if the shortened default names are sufficient for visibility in window titles already.

optimize names for new waypoints (related to #9041)

---

main/src/cgeo/geocaching/utils/DisplayUtils.java
main/src/cgeo/geocaching/utils/EmojiUtils.java
main/src/cgeo/geocaching/utils/MapMarkerUtils.java

Currently a custom icon gets distorted (stretched horizontally) when drawn on the map, caused by the assumption of the underlying map markers being a square (which they aren't). This PR fixes that by handling height and width separately.

un-distort custom images on map

---

main/src/cgeo/geocaching/CacheDetailActivity.java

Related to https://github.com/cgeo/cgeo/discussions/9692:
Grey out the "vote" menu entry in cache details when either the GCVote connector is disabled or credentials are incomplete.
(It is already hidden when the current cache does not support GCVote.)

set 'vote' menu entry to greyed out, if connector inactive

---

main/src/cgeo/geocaching/CacheDetailActivity.java

Related to #9710:
- Disable menu entries "toggle speech" and "prevent waypoint from note" for "go to" UDC
- removed a duplicated setting of "prevent waypoint form note" menu title

cache detail menu cleanup for 'go to' UDC

---

main/res/layout/emojiselector.xml
main/res/layout/emojiselector_item.xml
main/src/cgeo/geocaching/utils/EmojiUtils.java

Implements a first version of characters for the custom icon selector according to the discussion in #9717:
- enlarge icon display
- implement a standard set of selectable chars (WIP)
- display them in categories in the selector
I've chosen the following categories:
- symbols
- places
- foot
- activity
- people
and assigned a couple of icons to each category (although not yet complete, but you get the impression).
I've taken all symbols from the Unicode v5.0 list, which, according to Google's own documentation should be supported even on API 21 devices. (But, at least in the emulator, are not. I need to check whether I can detect this at runtime and skip such icons.)
Here's a screenshot from current implementation:
The popup is divided into four sections:
- title bar (title and buttons …

cache icon selection + groups

---

main/res/values/strings.xml
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/connector/AbstractConnector.java
main/src/cgeo/geocaching/connector/IConnector.java
main/src/cgeo/geocaching/connector/internal/InternalConnector.java
main/src/cgeo/geocaching/models/Geocache.java

Simple text editor field for a quick change of UDC description:
Can be enabled on a per-connector base, default is "not supported".

support description edit for UDC (fix #9713)

---

main/res/menu/map_activity.xml

After this change, we will always have three items in the menu:
1. Show / Hide
2. Export
3. Clean
Now it is illogical:
1. Show
2. Export
3. Clean
and
1. Export
2. Hide
3. Clean

More logical order in menu "History track"

---

main/res/values/strings.xml
main/src/cgeo/geocaching/storage/extension/OneTimeDialogs.java
main/src/cgeo/geocaching/utils/EmojiUtils.java

- Android 6+: Automatically removes unsupported characters from emoji selector
- Android 5: Shows a OneTimeMessage about not being able to auto-filter unsupported characters
- Selected icons for icon groups which are supported even on Android 5
Android 5:
Android 6 vs. Android 10:

check glyph availability for custom icons

---

main/src/cgeo/geocaching/models/Geocache.java

- retains the stored value for assigned custom icon on cache reload (fix #9736)
- retains the stored value for "prevent waypoints from note" on cache reload (IIRC that's hidden somewhere in some comment, does not have its own issue)
Both are settings which are c:geo-internal, cannot be taken from a downloaded geocache page, and therefore got lost in the past.

retain prevWptFromNotes and assignedEmoji on cache reload (fix #9736)

---

main/res/values/strings.xml

We had used the `>` character also at other places in our strings to direct users to a settings sub menu, so it would be consistent to use them here as well. 
Example:
`"Settings" > "Logging"` in the offline counter one time message
While I'm quite sure that we should use the `>` instead of `-` I'm wondering if we also want to use quotation marks here...?

edit map behavior strings

---

main/res/menu/main_activity_options.xml

It is not really intuitive to have two identical icons with different meanings. As an unambiguous "configuration wizard icon" does not exist, it's the best to always hide the icon...
Before it was like this:

never show configuration wizard as menu action

---

main/src/cgeo/geocaching/ui/CacheListAdapter.java

fixes #4507 and partly #6672
It looks like this was explicitly introduced, but I can't find a reason for it. All my resorting tests work fine, also when in selection mode. Looking at the history, it is there since 2012. I have read through some issues linked in the old commit messages but it seems like as there was no real reason, so let's remove it...

allow sorting also when in selection mode

---

main/res/layout/emojiselector.xml

Before that the LRU was unreachable if the emoji list was too long...

correctly scroll in emoji selector

---

main/src/cgeo/geocaching/utils/EmojiUtils.java

Add `U+FE0F` (VARIATION SELECTOR-16) to all emojis to force emoji-style presentation 
Before:
Now:

emoji-style presentation 

---

main/src/cgeo/geocaching/maps/mapsforge/v6/caches/StoredCachesOverlay.java

reverts part of an unnecessary change introduced by #8389
See https://github.com/cgeo/cgeo/issues/9374#issuecomment-761205884 for more info.

do not reset last viewport on every location cycle (related to #9374)

---

main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

Fix max zoom level error: NewMap only set zoom boundaries for the zoom controls, but not for the map itself, thus changing zoom level while bypassing zoom level controls were still able to exceed the map's zoom boundaries.

fix OSM max zoom level issue (fix #9752)

---

main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

Checks whether current map zoom level is within zoom level bounds of selected OSM map source. Works for changes within OSM (offline/online) as well as from Google Maps to OSM.
see https://github.com/cgeo/cgeo/issues/9752#issuecomment-761805338

make sure map zoom level is within bounds on map source change

---

main/project/findbugs/exclusions.xml
main/src/cgeo/geocaching/activity/AbstractActivity.java
main/src/cgeo/geocaching/activity/OAuthAuthorizationActivity.java
main/src/cgeo/geocaching/apps/AbstractApp.java
main/src/cgeo/geocaching/apps/navi/OsmAndApp.java
main/src/cgeo/geocaching/connector/ec/ECLogin.java
main/src/cgeo/geocaching/connector/gc/GCConnector.java
main/src/cgeo/geocaching/connector/gc/GCLogin.java
main/src/cgeo/geocaching/connector/gc/GCParser.java
main/src/cgeo/geocaching/log/LogEntry.java
main/src/cgeo/geocaching/models/Geocache.java
main/src/cgeo/geocaching/sensors/GeoData.java
tests/src-android/cgeo/geocaching/CgeoApplicationTest.java
tests/src-android/cgeo/geocaching/connector/gc/GCParserTest.java
tests/src-android/cgeo/geocaching/connector/oc/OkapiClientTest.java
tests/src-android/cgeo/geocaching/connector/trackable/GeokretyConnectorTest.java
tests/src-android/cgeo/geocaching/connector/trackable/GeokretyParserTest.java
tests/src-android/cgeo/geocaching/connector/trackable/TravelBugConnectorTest.java
tests/src-android/cgeo/geocaching/files/GPXParserTest.java
tests/src-android/cgeo/test/Compare.java
tests/src-android/cgeo/watchdog/WatchdogTest.java

There were many null analysis assertions in the code which are not necessary anymore when using Android Studio. Lint has complained that this condition must always be true and should be removed, which is done with this PR...

Remove some relics from the time of Eclipse

---

main/src/cgeo/geocaching/CachePopupFragment.java

Userdefined cache icons were ignored in the CachePopup, therefore swich to MapMarkerUtils for suporting user-defined cache icons and listmarkers in the cache icon...

show correct MapMarker in CachePopup

---

main/res/menu/cache_options.xml
main/src/cgeo/geocaching/AbstractDialogFragment.java
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/CacheMenuHandler.java

- do not show cache detail submenus in map cache popup
- but show entries "share" and "caches around" (if applicable) as top level menu items in popup

hide cache submenus in popup (fix #9825)

---

.github/dependabot.yml
build.gradle

- dependabot configure assertj restriction
- make description for the assertj gradle restriction clearer
- remove fix for gradle plugin problem, it is no more necessary

configure dependabot and changes in result of dependabot PR
