cgeo/cgeo

main/res/layout/authorization_activity.xml
main/res/layout/authorization_credentials_activity.xml
main/res/layout/authorization_token_activity.xml
main/res/values/strings.xml
main/res/values/styles.xml
main/src/cgeo/geocaching/activity/OAuthAuthorizationActivity.java
main/src/cgeo/geocaching/activity/TokenAuthorizationActivity.java
main/src/cgeo/geocaching/settings/AbstractCredentialsAuthorizationActivity.java

Updated the different login / authentication pages:
- enlarged font size to 16sp
- added divider and spacing between login/start button and create button
- shortened explanation for gc.com authentication
- added explanation for create
- updated image for all login pages still using the old c:geo logo

make login pages more user-friendly (fix #9818)

---

main/res/values/strings.xml
main/src/cgeo/geocaching/CacheDetailActivity.java

Adds toasts for the "remove waypoints" button. Now all four combinations are covered:
- synch waypoints: waypoints were added to PN / no storable waypoints found
- remove waypoints: removed waypoints / no waypoints found to remove

add toasts for remove waypoints button (fix #9656)

---

main/src/cgeo/geocaching/storage/DataStore.java

always show waypoints of DNF caches, independent of "exclude found caches" filter

---

main/src/cgeo/geocaching/ImageSelectActivity.java
main/src/cgeo/geocaching/log/LogCacheActivity.java
main/src/cgeo/geocaching/models/Image.java
main/src/cgeo/geocaching/ui/ImageActivityHelper.java
main/src/cgeo/geocaching/ui/ImageListFragment.java
main/src/cgeo/geocaching/utils/ImageUtils.java
tests/src-android/cgeo/geocaching/models/ImageTest.java

This PR contains necessary refactorings in master before offline log images can be migrated to SAF.
Basically, ImageUtils and related classes are converted to use Uris & InputStreams instead of Files. Placeholder methods which will later converted to use SAF methods are marked accordingly with TODO tags.

rel to #9609: prepare offline log image migration to SAF

---

main/build.gradle
main/src/cgeo/geocaching/AboutActivity.java

This is a first shot at the viewbinding migration needed for the next Gradle version (and due to ButterKnife being discontinued). It changes ButterKnife `@BindView` to Android's viewbindings for our about pages.

replace ButterKnife with viewbindings in about pages (rel. to #9232)

---

main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java
main/src/cgeo/geocaching/utils/OfflineMapUtils.java

Skip map companion files on building list of user-installed offline map files to avoid unnecessary opening and parsing of files.

skip map companion files on map list build

---

gradle/wrapper/gradle-wrapper.properties

update gradle from 6.7.1 to 6.8.1
For the release notes see https://docs.gradle.org/6.8.1/release-notes.htm

gradle 6.8.1

---

main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java

and thus apply the same collator for sorting as in the pre-SAF version. Fixes https://github.com/cgeo/cgeo/issues/9870#issuecomment-767954053

use TextUtils.COLLATOR for map list sort (follow-up to #9870)

---

main/res/layout/cachedetail_activity.xml
main/res/layout/cachedetail_description_page.xml
main/res/layout/cachedetail_details_page.xml
main/res/layout/cachedetail_images_page.xml
main/res/layout/cachedetail_inventory_page.xml
main/res/layout/cachedetail_waypoints_page.xml
main/res/layout/logs_page.xml
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/activity/AbstractViewPagerActivity.java

As discussed in #8888 and #9880 this implements a pull-to-refresh gesture to refresh cache details. I've chosen a relative high threshold for pull down refresh - tests will show whether this distance is too large/small or just right. This is difficult to estimate on the emulator...

Introduce swipe to refresh gesture for cache details (fix #8888, fix #9880)

---

main/src/cgeo/geocaching/export/GpxSerializer.java
main/src/cgeo/geocaching/files/GPXParser.java
tests/res/raw/ocddd2_empty_coord.gpx
tests/src-android/cgeo/geocaching/connector/gc/GCParserTest.java
tests/src-android/cgeo/geocaching/export/GpxSerializerTest.java
tests/src-android/cgeo/geocaching/files/GPXImporterTest.java

Waypoints with empty coordinates are getting exported with #8409. 
Unfortunately the cache-coordinates were set to null, if originalCoords were empty.

fix #9849: set modified coordinates for originalEmptyCoordinates on import

---

main/src/cgeo/geocaching/storage/Folder.java
tests/src-android/cgeo/geocaching/storage/ContentStorageTest.java

fixes: saf duplicates folder names with spaces in it.
With fix SAF will accept spaces in foldernames
I am currently unable to find the issue where this was found, but I guess the fix is needed anyway...

fix: saf accept spaces in foldernames

---

main/res/values/strings.xml
main/src/cgeo/geocaching/InstallWizardActivity.java
main/src/cgeo/geocaching/storage/ContentStorageActivityHelper.java

@eddiemuc 
Works in general, but I'm facing two issues, therefore setting "WIP" label for now:
- In `InstallWizardActivity.requestBaseFolder()` I've tried calling `selectPersistableFolder()` with a callback. But the callback got called only on selecting "cancel", not on "ok". (So I changed the code to work without callback, but it's sort of a hack.)
- This may be related to my second, more important issue: Even if I select a folder and grant access to it, my selection does not get persisted. In wizard's summary the entry is still shown as error, and in the `MainActivity` the base folder check will open.
- Strange thing: If I select the very same base folder coming from `MainActivity` it get's persisted. So what is the difference?
@eddiemuc
Do you have an idea what I'm missing here?

Integrate SAF base folder query into wizard

---

main/AndroidManifest.xml
main/src/cgeo/geocaching/settings/MapDownloaderReceiverSchemeMap.java
main/src/cgeo/geocaching/utils/MapDownloadUtils.java

In addition to using the integrated MapDownloader you may now come from the OpenAndroMaps homepage and click on their "Install others" button to trigger download and installation of a map file:

add support for mf-v4-map scheme for downloading map files (fix #9918)

---

main/src/cgeo/geocaching/storage/ContentStorageActivityHelper.java
main/src/cgeo/geocaching/storage/FolderUtils.java
tests/src-android/cgeo/geocaching/storage/ContentStorageTest.java

Make `FolderUtils.copyAll` progressable and cancellable
This is the first PR for this topic. It enables the underlying method `FolderUtils.copyAll` to get cancelled inbetween and report its status during runtime. For details see JavaDoc on this method (part of this PR). This concludes the "business logic" part of the requirement. Unit tests were provided as well.
In a second PR, we have to build upon this both the execution of copyAll in a separate Thread and building a ProgressDialog showing its progress and providing a cancel button

Make copyAll progressable and cancellable

---

main/res/values/strings.xml
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/storage/ContentStorageActivityHelper.java

fixes #9808
Removes outdated saf basedir check fialog on startup:
Because it has be replaced by wizard dialog:

fix #9808: remove outdated basedir check dialog (replaced by wizard)

---

main/src/cgeo/geocaching/storage/DataStore.java

Only load downgradeableVersions when DB version needs to be downgraded (fix #9937)

fix downgradeableVersions issue

---

main/res/menu/cache_options.xml
main/src/cgeo/geocaching/CacheDetailActivity.java

Since we have this nice "pull to refresh" feature in cache details we do not need the "refresh" menu entry any longer

remove 'refresh' menu entry in cache details

---

main/src/cgeo/geocaching/InstallWizardActivity.java
main/src/cgeo/geocaching/SplashActivity.java

As discussed somewhere in the depths of #9872: Skip "services" and "advanced" screens in configuration wizard when in migration mode. Migration mode is entered on startup if "SAF base folder" is not set.
We may want to discuss whether to adapt some texts on wizard's opening and final screens when in migration mode.

installation wizard: skip some screens in migration mode

---

main/res/values/preference_keys.xml
main/res/values/strings.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/settings/Settings.java

For testing purposes only!
Set `NewMap` to 4 rendering threads (see #9895).
Fixed value, no user interface supplied, testing only.

add multithreaded map rendering for OSM (fix #9895)

---

main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/TrackableActivity.java
main/src/cgeo/geocaching/ui/CacheListAdapter.java
main/src/cgeo/geocaching/ui/TrackableListAdapter.java

Another step towards the viewbinding migration needed for the next Gradle version (and due to ButterKnife being discontinued). It changes ButterKnife @BindView to Android's viewbindings for the cache details, caches list, trackable details and trackables lists activities.

replace ButterKnife for caches & trackables (rel. to #9232)

---

main/res/layout/map_distanceinfo.xml
main/res/values/styles.xml

Instead of using a fixed with for the distance infos on the right:
Uses maximum available space for target cache title, limited only by the width of the widest distance info.

make distance layout more flexible (fix #7489)

---

main/res/layout/map_settings_dialog.xml

Currently the "compact icon mode" buttons in map quick settings popup look like this for OSM:
Google Maps do a better job here, although they share the popup's layout definition.
This PR changes the layout for compact icon mode buttons to look balanced for both maps:

make compact icon buttons same width in map quick settings

---

gradle/wrapper/gradle-wrapper.properties
main/build.gradle
settings.gradle

- gradle 6.8.1 to 6.8.2, see https://docs.gradle.org/6.8.2/release-notes.html and https://services.gradle.org/fixed-issues/6.8.2
- Gradle Enterprise Plugin 3.5.1 to 3.5.2, see https://docs.gradle.com/enterprise/gradle-plugin/#release_history
- spotbugs-annotations 4.2.0 to 4.2.1, see https://github.com/spotbugs/spotbugs/blob/4.2.1/CHANGELOG.md

library updates

---

main/res/layout/logcache_activity.xml
main/src/cgeo/geocaching/log/LogCacheActivity.java

`LogCacheActivity` (and some others) are a bit harder to tackle for the ButterKnife => viewbinding change. Using the regular approach with `Bindingclass.inflate()` did not work here, it constantly crashed, so I used the regular view creation and attached the viewbinding using the `bind` method. The way for finding the correct root view introduced with #9962 worked on my testing devices, but obviously not on all machines, so I switched to a different approach here, introducing an explicit id for the root view and querying it.

use different way of detecting view root (fix #9975)

---

main/res/layout/filter_activity.xml
main/res/layout/mapdownloader_activity.xml
main/src/cgeo/geocaching/address/AddressListAdapter.java
main/src/cgeo/geocaching/connector/gc/PocketQueryListAdapter.java
main/src/cgeo/geocaching/downloader/MapDownloadSelectorActivity.java
main/src/cgeo/geocaching/filter/FilterActivity.java
main/src/cgeo/geocaching/helper/HelperAppAdapter.java

Getting closer... Another step towards the viewbinding migration needed for the next Gradle version (and due to ButterKnife being discontinued). It changes ButterKnife @BindView to Android's viewbindings for filter / map downloader / address list / pocket query list and helper apps activities.

replace ButterKnife for several more files (rel. to #9232)

---

main/res/values/strings.xml
main/src/cgeo/geocaching/CacheListActivity.java

fix #10009: make explicit when caches are deleted completey in cache lists
If we are in a user-defined list, cache menu remove entries is unchanged:
If we are in a "special" list (All, Temporaray, History) then labels for remove-entries are different:

fix #10009: make explicit when caches are deleted completey in cache lists

---

main/src/cgeo/geocaching/storage/FolderUtils.java

Since it would be quite inconvenient if someone accidentally cancel the folder migration after he had already moved all the files to the new location, we shouldn't allow canceling in the CopyAllDoneDialog...
closes #9978

don't allow canceling the "copy done" dialog via clicking outside

---

main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

One minor glitch after introducing configurable cache markers: Multi-item selector in NewMap shows the generic icon instead of the cache-specific item:
|before|after|
|---|---|
|![image](https://user-images.githubusercontent.com/3754370/107989080-b9bdbe00-6fd1-11eb-984a-d30b294d7e6b.png)|![image](https://user-images.githubusercontent.com/3754370/107989097-c2ae8f80-6fd1-11eb-8d9b-9f8359b8e66c.png)|
(See the last entry, the UDC named "user-defined cache with some very long title")
Do we need to check the waypoint icons as well?

show actual cache marker in map multi-marker popup

---

main/res/values/strings.xml
main/src/cgeo/geocaching/InstallWizardActivity.java
main/src/cgeo/geocaching/utils/BackupUtils.java

There was a bug that restoring a backup always returned "database is broken" when triggering restore via the installation wizard.
Also, the "cgeo needs to be restarted" dialog had disturbed the installation workflow. 
Both ones are fixed in this PR. Along the way, it will also save some clicks for restoring, as "restore" will now start the restore directly instead of redirecting to the settings first.

better backup integration in installation wizard

---

main/res/values/themes.xml

The intermediate themes `cgeo_popup`, `cgeo.Translucent` and `cgeo.Translucent.Light`, which `popup_dark` and `popup_light` are based upon, are used on no other places, so let's remove them.

remove intermediate popup themes (rel. to #9373)

---

main/res/values/strings.xml

Taken from issues our translators opened on Crowdin:
- Map quick settings: 
- "Show..." is obsolete as 1. the meaning is clear by the checkboxes and 2. there is a caption "Show in map". Also smaller strings might fit better.
- The mentioned "Show in map" should be "Show on map" (grammar) and a double quote at the end is missing
- Search bar hint says "Search for caches" but you can also search trackables. Replace by "Search caches/trackables"
- More understandable explanation of signature templates
-

String improvements based on Crowdin feedback

---

main/res/values/strings.xml
main/res/values/strings_not_translatable.xml
main/src/cgeo/geocaching/downloader/AbstractDownloader.java
main/src/cgeo/geocaching/downloader/MapDownloaderFreizeitkarte.java
main/src/cgeo/geocaching/downloader/MapDownloaderFreizeitkarteThemes.java
main/src/cgeo/geocaching/downloader/MapDownloaderOpenAndroMaps.java
main/src/cgeo/geocaching/downloader/ReceiveMapFileActivity.java
main/src/cgeo/geocaching/models/OfflineMap.java

This is part 1: adding "freizeitkarte" maps to the downloader.
Next parts will be adding "freizeitkarte" themes to the downloader, and auto-downloading fzk-theme after downloading a fzk map. Keeping the "WIP" label until that is included as well.

Add freizeitkarte maps to downloader (rel. to #7529)

---

main/src/cgeo/geocaching/CacheDetailActivity.java

add long-click-behaviour to waypoint-coordinates to copy coordinates as for cache-coordinates (fix #6711)
If long click on the waypoint-coordinates open the copy-menu as for the cache-coordinates, should then the copy-entry in the menu be deleted?

Add long-click-behaviour to waypoint-coordinates to copy coordinates as for cache-coordinates

---

main/src/cgeo/geocaching/export/GpxSerializer.java
main/src/cgeo/geocaching/files/GPXParser.java
tests/res/raw/zz1000.gpx
tests/src-android/cgeo/geocaching/export/GpxSerializerTest.java

Empty coordinates are only valid for export / import if geocode is valid for InternalConnector (e.g. user-defined-cache)
(fix #9305)

fix #9305: export and import UDC with empty coordinates

---

main/src/cgeo/geocaching/ui/ImageActivityHelper.java

fix #10061: prevent add duplicate image when using Google Photos

fix #10061: prevent add duplicate image when using Google Photos

---

main/res/layout/pq_actionbar.xml
main/res/values/preference_keys.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/connector/gc/PocketQueryListActivity.java
main/src/cgeo/geocaching/settings/Settings.java

Add a toggle (switch) to the main screen's pq list to toggle display between "all" and "downloadable only":
This makes live easier for people like me who have dozens of pq, but only very few of them active.
Toggle will be displayed on main screen's pq list only, not when coming from a cache list (as then the list is always filtered to "downloadable only"). The toggle's value gets remembered in the preferences. Default value is "show all" (as it is today's behavior).

add toggle to pq list to display all/downloadable only

---

main/res/values/strings.xml
main/src/cgeo/geocaching/InstallWizardActivity.java

- renamed "skip" to "not now" on opening screen
- pressing the button will show an explanation + confirmation dialog with "back" and "ok" options
example (show for migration, but is similar in the first installation variant):

rename wizard 'skip' and add info/confirmation dialog (fix #9977)

---

main/res/values/preference_keys.xml
main/res/values/strings.xml
main/res/values/strings_not_translatable.xml
main/src/cgeo/geocaching/downloader/AbstractMapDownloader.java
main/src/cgeo/geocaching/downloader/MapDownloadSelectorActivity.java
main/src/cgeo/geocaching/downloader/MapDownloaderFreizeitkarte.java
main/src/cgeo/geocaching/downloader/MapDownloaderFreizeitkarteThemes.java
main/src/cgeo/geocaching/downloader/MapDownloaderOpenAndroMaps.java
main/src/cgeo/geocaching/downloader/MapDownloaderOpenAndroMapsThemes.java
main/src/cgeo/geocaching/downloader/MapDownloaderReceiverSchemeMapTheme.java
main/src/cgeo/geocaching/models/OfflineMap.java
main/src/cgeo/geocaching/settings/Settings.java

some polishing for the map downloader:
- set downloaded Freizeitkarte (FZK) theme as current theme on successful download (last part to fix #7529)
- offer to download missing FZK theme after successful FZK map download
- make naming of maps' and themes' variables and classes consistent
- remember last selected type in map downloader

some polishing for map downloader

---

main/build.gradle
main/src/cgeo/geocaching/maps/mapsforge/v6/RenderThemeHelper.java

map themes: upgrade mapsforge lib version to use new ZipProvider-method
Upgrade used mapsforge version to use new MEthod for Zip File Xml Theme scan.
Thanks @bekuno for his support!

map themes: upgrade mapsforge lib version to use new ZipProvider-method

---

main/res/values/strings.xml
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/downloader/MapDownloaderFreizeitkarteThemes.java
main/src/cgeo/geocaching/downloader/MapDownloaderOpenAndroMapsThemes.java
main/src/cgeo/geocaching/maps/mapsforge/v6/RenderThemeHelper.java
main/src/cgeo/geocaching/settings/SettingsActivity.java
main/src/cgeo/geocaching/storage/ContentStorage.java
main/src/cgeo/geocaching/storage/ContentStorageActivityHelper.java
main/src/cgeo/geocaching/storage/FolderUtils.java
main/src/cgeo/geocaching/utils/Formatter.java
main/src/cgeo/geocaching/utils/LocalizationUtils.java
tests/src-android/cgeo/geocaching/storage/ContentStorageTest.java

fix #10070: synchronize map theme folder in background
Synchronization of Map Themes is now done in the background, but still uses the same trigger points as before (on c:geo startup, on map theme folder change and after map theme download).
Instead of original GUI, user is informed via toast about map theme sync:
This PR also includes LocalizationUtils for localization methods useful when not having an activity around (so one does not have to deal with CGeoApplication).
It also fixes #10080, because this was just a parameter to add.

fix #10070, #10082, #10080: synchronize map theme folder in background

---

gradle/wrapper/gradle-wrapper.properties

update gradele from 6.8.2 to 6.8.3
For the release notes see https://docs.gradle.org/6.8.2/release-notes.htm

gradle 6.8.3

---

main/src/cgeo/geocaching/maps/mapsforge/v6/ContentResolverResourceProvider.java
main/src/cgeo/geocaching/maps/mapsforge/v6/RenderThemeHelper.java
main/src/cgeo/geocaching/storage/ContentStorage.java
tests/src-android/cgeo/geocaching/storage/ContentStorageTest.java

rel to #10075: load themes on startup, provide test mode for content themes
Also, while working on this I discovered a bnug in mapsforge ContentResolverResourceProvider: currently it will always root on the Tree root (not on the provided folder uri). Migitated this for now by copying class into c:geo and fixing error there, but needs to be fixed in mapsforge and then rerouted in c:geo as well.

rel to 10075: load themes on startup, provide test mode for content themes

---

main/src/cgeo/geocaching/utils/FileNameCreator.java
main/src/cgeo/geocaching/utils/Log.java

enable writing of own log files
Introduces a new option `logging.logfile` in `log-properties.txt`. If set to a value x, a log file will be written by c:geo (in addition to logging to logcat) into the logfiles directory.

enable writing of own log files

---

main/src/cgeo/geocaching/ImageSelectActivity.java
main/src/cgeo/geocaching/ui/ImageActivityHelper.java
main/src/cgeo/geocaching/ui/ImageListFragment.java

Fixes #9973 (camera image lost on device rotation), but to do that a deeper class desing issue had to be fixed. This fix is absolutely necessary because it may also produce strange problems in other areas of c:geo (which might not yet have been found), but it makes this a larger change than one would maybe expect when looking solely at the user.
Implementation detail: ImageActivityHelper was as of before not involved in Activity lifecycle and did not save/restore its state correctly. In case of rotation, the calling Activity (e.g. ImageListFragment or ImageSelectActivity) is internally destroyed and recreated, thus state got lost. This is the cause of the user-visible error.
Saving state of ImageActivityHelper was not straight-forward though because it contains callback lambdas which …

fix #9973: camera image lost on rotate, changed ActivityHelper design pattern to fix

---

tests/src-android/cgeo/geocaching/maps/MapsforgeMapProviderTest.java

Move class to the correct place (fix package name error).
Change from using TestCase to junit.Test.
This is enough, the extended possibilities of TestCase are not used.

Fix error & Optimize MFMProviderTest

---

main/res/values/strings.xml
main/src/cgeo/geocaching/connector/gc/GCConstants.java
main/src/cgeo/geocaching/connector/gc/GCParser.java
main/src/cgeo/geocaching/connector/trackable/AbstractTrackableConnector.java
main/src/cgeo/geocaching/connector/trackable/TrackableConnector.java
main/src/cgeo/geocaching/connector/trackable/TravelBugConnector.java
main/src/cgeo/geocaching/log/CacheLogsViewCreator.java
main/src/cgeo/geocaching/log/LogEntry.java
main/src/cgeo/geocaching/log/LogsViewCreator.java
main/src/cgeo/geocaching/log/TrackableLogsViewCreator.java
main/src/cgeo/geocaching/models/Trackable.java
tests/res/raw/tb3f206.htm
tests/res/raw/tbxatg.htm
tests/src-android/cgeo/geocaching/CgeoApplicationTest.java

~The only flaw in my implementation is, that the title doesn't look very nice with this very long log id. But we can either leave it like this (hey, it's only about trackables ;-) ), remove the log id also for caches completely from the title or need to introduce some magic (-> e. g. only show id's shorter than 10 characters)~

offer "open log in browser" also for trackables

---

main/res/values/preference_keys.xml
main/res/values/strings.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/downloader/MapDownloaderFreizeitkarteThemes.java
main/src/cgeo/geocaching/downloader/MapDownloaderOpenAndroMapsThemes.java
main/src/cgeo/geocaching/maps/mapsforge/v6/RenderThemeHelper.java
main/src/cgeo/geocaching/settings/Settings.java
main/src/cgeo/geocaching/settings/SettingsActivity.java
main/src/cgeo/geocaching/storage/ContentStorageActivityHelper.java
main/src/cgeo/geocaching/storage/FolderUtils.java
main/src/cgeo/geocaching/storage/LocalStorage.java
main/src/cgeo/geocaching/utils/SystemInformation.java
tests/src-android/cgeo/geocaching/storage/ContentStorageTest.java

fix #10123: make themes folder sync configurable:
- Takes out the sync by default
- Make a new setting under map themes folder to turn it on or off
- Adjust explanatory text for map theme folder (there is already one in the settings for it, it also points to FAQs)
- Implements an absolute maximum sync file size (5MB) as well as an "exclude" file filter (will not sync Files with suffix map)

fix #10123: make themes folder sync configurable

---

main/res/values/strings.xml
main/src/cgeo/geocaching/InstallWizardActivity.java
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/settings/Settings.java
main/src/cgeo/geocaching/settings/SettingsActivity.java
main/src/cgeo/geocaching/storage/ContentStorageActivityHelper.java
main/src/cgeo/geocaching/storage/PersistableFolder.java
main/src/cgeo/geocaching/utils/BackupUtils.java

On settings restore: Check if any of the `PersistableFolder` settings in the to-be-restored file differs from current settings and request access grant for those.
For every `PersistableFolder` with a different setting a popup will show while restoring settings, asking the user to either keep the existing value or restoring the old value, and starting SAF grant process in the latter case:

Request SAF permissions on settings backup restore (fix #10105)

---

main/build.gradle
main/lint-baseline.xml

rel to #8029: make build fail on lint error (defines baseline containing current errors)
This PR will switch build to fail if there are lint errors on it (it does not fail for warnings!)
Since current master has 84 lint errors and I can't fix them all right now (:-)), in order to not fail the build this PR also contains a baseline file which basically lets lint ignore those 84 errors when deciding whether to fail or not. But any new error from now on will fail the build.

rel to #8029: make build fail on lint error (defines baseline containing current errors)

---

main/lint.xml

Make build fail (as we stop on lint error now) if strings or incoming translations use `...` instead of the designates ellipsis character. This can currently not be forbidden/mitigated on Crowdin while translating and is an often made error made by translators.
Thus not detecting it will lead to more lint warning in the project (and more ugly strings).

Treat missing ellipsis character as lint error

---

main/res/values/strings.xml

I was wondering why quite some users still contact support and have no login information stored. Mostly they tell, that they see the warning on main screen but don't know how to login.
Maybe its just as simple as adding the help, that the message can be clicked (which will provide more info and guide to service settings).

Inform user that login problem prompt is clickable

---

main/res/values/strings.xml
main/res/values/strings_not_translatable.xml

Moving some strings into the non-translatable string file, as:
- Those does not contain translatable content (such as N° --.---..."
- Are own names and should not be translated (like Openstreetmap.org, Rmaps)
- Our app name should also not be fooled with on Crowdin
There have been occasions in the past where such strings have been translated and thus they are no longer correct (e.g. Rmaps to german Rkarten, Openstreetmap.de in spain to openstreetmap.es, etc.)
BTW:
This is my first PR which has been built locally on my machine before submitting it :)

Move some strings to non translatable

---

main/src/cgeo/geocaching/downloader/ReceiveMapFileActivity.java

- catch SecurityException on receiving download (fix #10246)
- also removes false "SUCCESS" state overriding IOException state

catch SecurityException on receiving download (fix #10246)

---

main/src/cgeo/geocaching/connector/trackable/TravelBugConnector.java
tests/src-android/cgeo/geocaching/connector/trackable/TravelBugConnectorTest.java

fixes #10192
- edit pattern to additional allow 9 digit tracking code formatted for logging of TB5EFXK
- more tests for 5 to 10 digits length
- fix a possible nullable problem
- switch test class to simple junit4 tests

allow TB special tracking code length 9

---

main/res/values/strings.xml
main/src/cgeo/geocaching/utils/BackupUtils.java

When you restore settings with multiple folders being different from current setting, and you selected "cancel" on one of them, c:geo did not ask you for the other diverging folders anymore during restore. This is fixed by this PR.
Also the dialog message is changed from "folder xxx has changed to yyy" to "folder xxx will be restored to yyy" to more accurately reflect what is happening.

fix cancel on restoring multiple folders

---

main/res/values/strings.xml
main/src/cgeo/geocaching/SearchActivity.java
main/src/cgeo/geocaching/TrackableActivity.java
main/src/cgeo/geocaching/log/LogTrackableActivity.java

If no trackable with matching tracking code is found, execute online cache name search afterwards...
fixes #10258
fixes #5083

optimize handling of wrongly detected tracking codes in global search

---

main/res/layout/settings_toolbar.xml
main/res/values/themes.xml
main/src/cgeo/geocaching/helper/QueryMapFile.java
main/src/cgeo/geocaching/maps/AbstractMap.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/MapActivity.java
main/src/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java
main/src/cgeo/geocaching/maps/google/v2/GoogleMapProvider.java
main/src/cgeo/geocaching/maps/interfaces/MapActivityImpl.java
main/src/cgeo/geocaching/maps/interfaces/MapProvider.java
main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/settings/SettingsActivity.java

Some preparations for #9373:
- rebase map activities to `AppCompatActivity`
- use cgeo-based theme for Google Maps (instead of `DeviceDefault`-based) (fix #7587)
- use cgeo-based theme for settings (instead of `DeviveDefault`-based)
- set toolbar for settings (fixes #5602)
Should also fix some theme problems with Google Maps and settings, e. g. #8783 (but that probably needs to be checked against physical devices).
Tested in the emulator against API 21, 23, 24 and 30.
Some screenshots for settings: (title bar adjusts to preferences screen)

switch map activities to AppCompatActivity (rel. to #9373)

---

build.gradle

checked also the aapt2-proto reference, is further necessary
Not yet useful release notes in https://androidstudio.googleblog.com/2021/03/android-studio-413-available.html

update gradle to version 4.1.3

---

main/src/cgeo/geocaching/brouter/codec/StatCoderContext.java
main/src/cgeo/geocaching/brouter/util/DenseLongMap.java
main/src/cgeo/geocaching/brouter/util/MixCoderDataInputStream.java
main/src/cgeo/geocaching/brouter/util/MixCoderDataOutputStream.java
tests/src-android/cgeo/geocaching/brouter/codec/LinkedListContainerTest.java
tests/src-android/cgeo/geocaching/brouter/codec/StatCoderContextTest.java
tests/src-android/cgeo/geocaching/brouter/core/OsmNodeNamedTest.java
tests/src-android/cgeo/geocaching/brouter/core/OsmNogoPolygonTest.java
tests/src-android/cgeo/geocaching/brouter/util/BitCoderContextTest.java
tests/src-android/cgeo/geocaching/brouter/util/ByteDataIOTest.java
tests/src-android/cgeo/geocaching/brouter/util/CheapAngleMeterTest.java
tests/src-android/cgeo/geocaching/brouter/util/CompactMapTest.java
tests/src-android/cgeo/geocaching/brouter/util/DenseLongMapTest.java
tests/src-android/cgeo/geocaching/brouter/util/MixCoderTest.java
tests/src-android/cgeo/geocaching/brouter/util/SortedHeapTest.java
tests/src-android/cgeo/geocaching/brouter/util/StringUtilsTest.java

Migrate the tests from original BRouter to c:geo-integrated BRouter.
One test is missing yet - `EncodeDecodeTest` - which should be adapted to SAF first. I'll open a separate issue for that.

BRouter integration: add tests for integrated brouter

---

main/AndroidManifest.xml
main/src/btools/routingapp/IBRouterService.aidl
main/src/cgeo/geocaching/brouter/IInternalRoutingService.aidl
main/src/cgeo/geocaching/brouter/InternalRoutingService.java
main/src/cgeo/geocaching/maps/routing/AbstractServiceConnection.java
main/src/cgeo/geocaching/maps/routing/InternalServiceConnection.java
main/src/cgeo/geocaching/maps/routing/Routing.java

Untangling the IDL files for external and internal `BRouterService` (the latter now being called `InternalRoutingService`), but based on a common `AbstractServiceConnection` to preserve a standardized usage pattern for `Routing`.

fix calling external routing service (fix #10281)

---

main/src/cgeo/geocaching/maps/routing/Routing.java

As agreed upon somewhere in our discussion about BRouter integration this PR restricts the check for missing routing tile data to the internal routing service to avoid the (depending on Android system version) pretty complicated configuration necessary for external BRouter and auto-tile-downloader to work together - and the support effort which would come with that probably.

restrict auto-downloading of tile data to internal routing service

---

main/res/values/strings_not_translatable.xml
main/res/xml/preferences.xml

related to #10224: Change link behind "more" on themes info to point to FAQ entry about syncing

change 'more' link for map themes (rel. to #10224)

---

main/res/values/strings.xml

string is targeted to "files", but still mentions "folders" => fixed

fix info string

---

main/res/values/strings.xml

Targeted to `master` to allow sufficient time for new translations, as we are almost final with `release`.

Fix #10296 - Better wording for removing caches from a list

---

main/src/cgeo/geocaching/location/Geopoint.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/AbstractCachesOverlay.java

fixes #10071
maybe helps #10307 (first NPE)
- add some NonNull attributes
- add unused atrribute, maxbe the method will later used
(by the way in AS the lint message for "unused" is wrong and a known bug
- instead attribute NonNull for the distanceTo method (used 35 times in c:geo, but seldom checked) swich to explicit return a value 0f

lint fixes/Null checks

---

main/src/cgeo/geocaching/downloader/ReceiveMapFileActivity.java

- avoid IOException on successful OAM downloads
- prints folder name in user-readable form on IOException

avoid IOException on successful OAM downloads (fix #10319)

---

main/res/values/strings.xml

Some improvement proposals:
- Keep caption short for theme sync (to fit on screen) and instead provide details in subtitle
- Replace "permanently" by "continously" (this is probably meant here) in confirmation dialog for theme sync
- Add explicit hint to pay attention to folder size in confirmation dialog for theme sync
- "Always set as target automatically" as option for the individual route was difficult to understand for many users. Replaced it with "Set route start as target"
- But verb "disabled" at the end of the route option toast message
This PR is targeted to `master` on purpose to avoid invalidating translations short before release. Alternatively we can wait and merge to `release` after the release is out to have it contained already in a potential bugfix release.

Improve some strings

---

main/src/cgeo/geocaching/InstallWizardActivity.java

Set individual titles for location and storage permissions in the wizard. (See https://github.com/cgeo/cgeo-guide/issues/25#issuecomment-814691333)
Existing strings are reused, so no need to wait for new translations here.

Set individual permissions titles in wizard

---

main/AndroidManifest.xml

I've targeted this to `release`, but if we want to test it a bit, we can retarget it to `master` as well.

add application/gpx to accepted MIME types (fix #10309)

---

main/AndroidManifest.xml
main/proguard-project.txt

- remove no more necessary "org.apache.http.legacy" from Android Manifest
- remove no more necessary "butterknife.*", "android.net.http.*" and "org.apache.http.*" from proguard config

clean up old configuration

---

main/src/cgeo/geocaching/models/Geocache.java
main/src/cgeo/geocaching/models/Waypoint.java
tests/src-android/cgeo/geocaching/models/GeocacheTest.java

Prefix should never be null. So if prefix is empty, no check for matching coordinate or name was done.
For coordinates: if searchWp has coordinates, no check for matching name was done, if no waypoint with matching coordinates was found.
The fix removes the wrong return null statement for coordinates and the useless null check for prefix.
- remove useless null-check for prefix
- set empty prefix instead of null
- if searchwaypoint does have coordinates and no waypoint is found, look for waypoint with same name
- add more testcases
Replaces PR #10343

fix Geocache.findWaypoint() no null-check for Prefix and Coordinates

---

main/src/cgeo/geocaching/brouter/InternalRoutingService.java
main/src/cgeo/geocaching/brouter/core/RoutingContext.java
main/src/cgeo/geocaching/brouter/expressions/BExpressionContext.java

- fix mapping for "motorcar-short" to "car-eco" (used in original storageconfig) instead of "moped" (as mentioned in the readme)
- restrict config to use either StdModel or internal KinematicModel only instead of user-supplied class name

fixes for internal routing engine

---

main/AndroidManifest.xml

Similar issue as in #10309 which happened to me in my file manager. Locus is listed but c:geo isn't. See also issue #527 as a reference, in which the MIME type was suggested/~added~ as well years before.

add application/gpx+xml to accepted MIME types

---

main/src/cgeo/geocaching/playservices/LocationProvider.java

Simplified LocationProvider code to not rely on deprecated GoogleApiClient anymore. Deleted boilerplate code related to GoogleApiClient connection.

Remove deprecated GoogleApiClient connection to Fused Location Provider

---

main/src/cgeo/geocaching/settings/CredentialsPreference.java

Tries to fix the oversized avatar image (#10369) by limiting their relative column width.
@Lineflyer 
Not sure if this works reliably, as I cannot reproduce the issue. Can you cross-check?

restrict avatar size

---

main/res/values/strings.xml
main/src/cgeo/geocaching/maps/routing/RouteSortActivity.java

When using RouteSort, I always struggle about how saving is implemented. This PR will:
- protect RouteSortActivity from unwanted discard of changes
- optimize the user workflow by finishing RouteSortActivity after saving automatically 
(Why should someone click `save` if he is not finished yet?)

Optimize RouteSortActivity

---

main/res/xml/preferences.xml

Since our decision that routing tile update should be available only to internal routing the dependency of the routing data folder preference should point to "use internal routing" instead of "use auto downloading"

fix: make routing folder preference dependent on internal routing

---

main/src/cgeo/geocaching/TrackableActivity.java

Avoid loop when using "open in browser" action, in case c:geo is set as default app for trackable links

avoid loop when using "open in browser" for trackables

---

main/src/cgeo/geocaching/brouter/BRouterWorker.java
main/src/cgeo/geocaching/brouter/core/RoutingEngine.java

- removes outFileBase and logFileBase from `RoutingEngine` (as they are always `null` for internal routing engine)
- switches internal logging of `RoutingEngine` to c:geo logging routine (`Log.i()`)

remove some unused parameters & switch logging to c:geo logging

---

main/res/menu/main_activity_options.xml
main/res/values/numbers.xml
main/res/values/preference_keys.xml
main/res/values/strings.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/downloader/DownloaderUtils.java
main/src/cgeo/geocaching/models/Download.java
main/src/cgeo/geocaching/settings/Settings.java

Adds an automatic update check for map and theme files downloaded with the integrated downloader
Also adds an menu option to manually trigger update checks for either routing tile data or map data (new menu "Update" in main menu with two sub options).

add automatic update check for maps and themes (fix #10354)

---

main/src/cgeo/geocaching/brouter/BRouterConstants.java
main/src/cgeo/geocaching/brouter/BRouterWorker.java
main/src/cgeo/geocaching/brouter/InternalRoutingService.java
main/src/cgeo/geocaching/brouter/core/RoutingEngine.java
main/src/cgeo/geocaching/brouter/mapaccess/NodesCache.java
main/src/cgeo/geocaching/downloader/BRouterTileDownloader.java

- removes some more unused code (segmentDir, ...), vars and unused/unsupported parameters ("fast")
- uses static var for file extension
- moves rawtrack files to app-internal folder (fixes #10400)
- fixes error in `PhysicalFile` when routing tile file did not exist

BRouter integration: more code cleanup & fixes

---

main/src/cgeo/geocaching/connector/gc/GCConstants.java
main/src/cgeo/geocaching/connector/gc/GCParser.java
tests/src/cgeo/geocaching/test/mock/GC1ZXX2.html
tests/src/cgeo/geocaching/test/mock/GC3FJ5F.html

Adapts our code to the website change of cache detail page regarding the cache type. It's now referenced using the waypoint type instead of the type guid.
related to #10421, but not completely fixing it, as there is also a change regarding the cache owner.

adapt cache type detection to website change (rel. to #10421)

---

main/src/cgeo/geocaching/storage/ContentStorageActivityHelper.java
main/src/cgeo/geocaching/storage/Folder.java
main/src/cgeo/geocaching/storage/PersistableFolder.java
main/src/cgeo/geocaching/utils/LocalizationUtils.java
main/src/cgeo/geocaching/utils/SystemInformation.java

- Use unlocalized (english) values
- Add hint that value is localized (at places where an english value isn't easily possible)
- Avoid html styling tags for attribution text
fix #10410

Sys info lang

---

main/src/cgeo/geocaching/connector/gc/GCLogin.java
main/src/cgeo/geocaching/connector/gc/GCParser.java

Since recent website changes both login page and other cache pages have the same way the username is stored in the page's source, so detection can be merged into one, saving some extra roundtrips/checks.
Also language detection is adapted to that the page does not include a language selector any longer, but checks server parameters instead.

adapt logged-in check for non-login pages (rel. to #10440)

---

main/src/cgeo/geocaching/connector/gc/GCConstants.java

Adapt to yet another cascade of changes on their login pages, changing the check from `dataLayer` to `headerSettings`. Current expression will now also work with either `window.varname` and `window['varname']` way of declaring, and with `username` being the last var or not.

adapt login regexp to yet another website change (rel. to #10440)

---

main/res/values/strings.xml
main/src/cgeo/geocaching/maps/routing/Routing.java

Show a toast on missing routing data for users of (external) BRouter.
Message is shown once per session per routing tile (e. g. "W5_N30.rd5")
(Users of internal routing engine can configure c:geo to offer automatic download for missing routing tiles, which we do not support for external BRouter - therefore this info message.)

show toast on missing routing data (fix #8562)

---

main/src/cgeo/geocaching/connector/gc/GCConstants.java

Tries to fix the remaining problem with owner identification (#10454).
Our current pattern looks for a string terminated with `&a=0">`, whereas in the current page source there may be more parameters after the `&a=0`, so I removed the closing tag. 
All caches opened from me with the changed pattern allowed me to do an owner search (and I tried caches from areas abroad where I haven't been there yet, so I expect to not have any owner info stored for their owners yet), but I cannot prove that it will work. If someone has a reproducable scenario: please cross-check.

adapt owner pattern to website change (rel. to #10454)

---

main/src/cgeo/geocaching/settings/SettingsActivity.java

Add an onChangeListener to the map source preference in settings to recognize a mapsource change without having the need to restart c:geo

recognize mapsource change in settings without restart (fix #10407)

---

main/src/cgeo/geocaching/settings/ViewSettingsActivity.java

adds a null pointer safeguard for building the settings'  list in `ViewSettingsActivity`

add NPE safeguard on building settings' list (fix #10464)

---

main/res/layout-w1200dp/coordinatescalculate_dialog.xml
main/res/layout/authorization_activity.xml
main/res/layout/authorization_credentials_activity.xml
main/res/layout/authorization_token_activity.xml
main/res/layout/cachedetail_description_page.xml
main/res/layout/coordinates_equations.xml
main/res/layout/logs_item.xml
main/res/layout/main_activity.xml
main/res/layout/mapdownloader_item.xml
main/res/layout/pocketquery_item.xml

Another bunch of lint fixes:
- use compound drawables (on mainscreen, ignore)
- use `app:drawableLeftCompat` instead of `android:drawableLeft`
- adjust layout width/height options for some calculator elements
- button borders for action buttons in pocket queries and downloader (ignore/keep)

More lint fixes

---

main/src/cgeo/geocaching/connector/lc/LCConnector.java

Support setting state to "found", "did not find" or removing those states for the LC connector (in the same way we have it for UDC)

support setting found state for LC connector (fix #10475)

---

main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/InstallWizardActivity.java
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/activity/AbstractActivity.java
main/src/cgeo/geocaching/maps/AbstractMap.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/settings/SettingsActivity.java
main/src/cgeo/geocaching/storage/ContentStorageActivityHelper.java
main/src/cgeo/geocaching/utils/BackupUtils.java
main/src/cgeo/geocaching/utils/IndividualRouteUtils.java
main/src/cgeo/geocaching/utils/TrackUtils.java

fixes #10413 
ContentStorageActivityHelper was not state-aware and thus not able to "survive" a "destroy/resume" cycle of the using activity. This was fixed.
Umfortunately, Lambda callback design is not possible in this state-aware design any more, thus it was replaced by code with preassigned actions independent of exchanged activity class. Unfortunately this also meant redesign of all classes using ContentStorageActivityHelper, specifically BackupUtils, TrackingUtils and IndividualRouteUtils had to be made state-aware as well. 
@fm-sys Unfortunatly BackupUtils had to be changed quite a bit, thus I would appreciate your review. Especially the "regrantAccess" logic was tricky, to re-enable the "cycle" logic even if corresponding activity anchor is recreated I had to store state in the …

fix #10413: make contentstorageactivityhelper state-aware, replace lambda callbacks with activity-restore-stable code

---

main/res/values/strings.xml
main/res/xml/preferences.xml

- adds some explanation about preconditions for LC availability (rel. to #10477)
- moves LC connector in settings directly beneath GC connector
- LC info text is never greyed-out, even if connector is not active

add info on LC preconditions + move LC close to GC in settings

---

main/res/values/changelog_master.xml
main/res/values/strings.xml
main/res/values/strings_not_translatable.xml

- Renames the LC connector to "Geocaching.com Adventure Lab" (I've chosen this variant to emphasize the relationship to the GC connector)
- Swaps the two info text parts (see screenshot) to make it a bit clearer

Rename LC connector and adjust info text (fix #10473)

---

main/res/values/strings.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/settings/Settings.java

- sets default for LC connector to activated==true (fixes #10477)
- removes an unused LC method in Settings
- adds info about required restart to the preferences screen

switch LC connector active default to true (fix #10477)

---

main/src/cgeo/geocaching/location/IConversion.java
main/src/cgeo/geocaching/settings/ProximityPreference.java

use correct  conversion factor for imperial length for the proximity notification and max routing distance.
For proximity use ft as unit (meter in metric system), for max routing distance use yd as unit (km in metric system)
#10341

correct imperial conversion in map settings (fix #10341)

---

main/res/layout/cachedetail_description_page.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/connector/AbstractConnector.java
main/src/cgeo/geocaching/connector/IConnector.java
main/src/cgeo/geocaching/connector/lc/LCConnector.java

Displays an extra description for LC caches on cache description page. Text is being displayed in a separate block beneath the cache's description:

display extra explanation for LC caches (fix #10472)

---

main/res/values/strings.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/settings/SettingsActivity.java

- moves the "offline routing" block from map settings to navigation settings
- renames "Navigation" to "Offline routing / Navigation" and adapts its description

move offline routing settings to navigation (fix #10502)

---

main/src/cgeo/geocaching/AbstractDialogFragment.java
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/NavigateAnyPointActivity.java
main/src/cgeo/geocaching/WaypointPopupFragment.java
main/src/cgeo/geocaching/activity/AbstractActivity.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/GeoitemRef.java
main/src/cgeo/geocaching/models/Geocache.java
main/src/cgeo/geocaching/models/Waypoint.java
main/src/cgeo/geocaching/utils/Formatter.java

Adventure Lab Caches use a UUID for identification in the place where other geocaches use a GC-code aka geocode. The UUID is required as an addressing component when fetching data from the geocaching.com servers. The problem with the UUID: It  looks ugly at the UI and it cannot be memorized by the human brain for instance on a tour when one cacher says to another: "Hey what's the GC code for that cache over there ....".
This PR addresses the UI aspects of ALC-UUIDs in the place where a geocode is shown for other caches. There are three relevant scenarios, pls refer to https://github.com/cgeo/cgeo/issues/10387 for a more detailed discussion of these three cases and how they are addressed by this PR. In summary: One case is addressed by a modification in the respective layout.xml file …

shortened ALC LC-codes issue_#10387

---

main/res/layout/waypoint_item.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/EditWaypointActivity.java
main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java

Show text "Calculate coordinates" in the waypoint list for the coordinates of a waypoint, if it has calculated coordinates.
CalcState is only saved, if it has equations / variables. 
In the CoordinatesInputDialog the button "Calculate" has italic font, if already a formula is given (I can change this to bold / colored, ... ).
#6833 , #9899 
Because there is no way to delete the calcState of the waypoint, I added the logic, that a calcState is only set, if it has equations.
Probably it should be extended to "delete the calcState, if the coordinates get cleared by user". But I an not sure about this, so this could be an extra PR.
I am working on showing a icon in addition (like the "tick" for "visited" waypoints), but I am not yet satisfied with the look and feel of that icon, I am not …

Indicate waypoint has calculated coordinates in waypoint list (rel #9899, #6833)

---

main/src/cgeo/geocaching/settings/SettingsActivity.java

disable/enable LC connector's "active" checkbox on state changes of GC connector's "active" checkbox or authorization

disable LC activation checkbox when GC is not active (fix #10477)

---

main/src/cgeo/geocaching/AbstractDialogFragment.java
main/src/cgeo/geocaching/CacheMenuHandler.java

- always show found state change menu entries in cache popup, even if cache is not yet saved
- on selecting such a menu entry, store cache to default list, if cache is not yet stored offline
- fixes #10501

store cache to default list on found state change (if needed)

---

main/src/cgeo/geocaching/InstallWizardActivity.java
main/src/cgeo/geocaching/maps/routing/AbstractServiceConnection.java
main/src/cgeo/geocaching/maps/routing/Routing.java
main/src/cgeo/geocaching/utils/SystemInformation.java

- do not throw away the connection variable, if connection could not be established in `bindService` directly (allow asynchronicity)
- distinguish between "is currently connected" and "is generally available" checks
- label the corresponding functions more clearly

fix availability/connected check for routing connection (fix #10503)

---

main/res/menu/map_activity.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/export/IndividualRouteExport.java
main/src/cgeo/geocaching/utils/FileNameCreator.java
main/src/cgeo/geocaching/utils/IndividualRouteUtils.java

- adds option "Export as track" to individual route menu on map
- renames option "Export individual route" to "Export as route" in individual route menu on map
- default filename for export as track is prefixed with "track" instead of "route"
- exported track has one track segment per waypoint of the individual route

add option to export individual route as track (fix #10516)

---

main/src/cgeo/geocaching/downloader/MapDownloadSelectorActivity.java

- Currently the back arrow in the map downloader closes both the map downloader an the map. c:geo returns to the main screen.
- PR configures the back arrow to just close the map downloader (and by this return to the map)

set back arrow in map downloader to return to map (fix #10327)

---

main/res/values/strings.xml
main/res/values/strings_not_translatable.xml
main/src/cgeo/geocaching/downloader/AbstractThemeDownloader.java
main/src/cgeo/geocaching/downloader/MapDownloaderFreizeitkarteThemes.java
main/src/cgeo/geocaching/downloader/MapDownloaderHylly.java
main/src/cgeo/geocaching/downloader/MapDownloaderHyllyThemes.java
main/src/cgeo/geocaching/downloader/MapDownloaderOpenAndroMapsThemes.java
main/src/cgeo/geocaching/downloader/MapDownloaderReceiverSchemeMap.java
main/src/cgeo/geocaching/downloader/MapDownloaderReceiverSchemeMapTheme.java
main/src/cgeo/geocaching/models/Download.java

- adds hylly soumi map & themes to the map downloader
- including update check and auto-install
- also supports `mf-v4-map` and `mf-theme` schemes for direct install from website
|Soumi map|Available in downloader
|---|---|
|![image](https://user-images.githubusercontent.com/3754370/116793463-26bbfc80-aac7-11eb-8391-31f244997f61.png)|![image](https://user-images.githubusercontent.com/3754370/116793468-33405500-aac7-11eb-8dff-c7f169d2703a.png)|
|Theme downloading|Update check|
|![image](https://user-images.githubusercontent.com/3754370/116793465-2d4a7400-aac7-11eb-9b85-a13c533f92cb.png)|![image](https://user-images.githubusercontent.com/3754370/116793472-3a676300-aac7-11eb-9bf9-05f284d3add8.png)|

add hylly suomi map & themes (fix #10511)

---

main/src/cgeo/geocaching/settings/SettingsActivity.java

- update the "active" display in services summary for LC connector according to the _effective_ state of LC connector
- active == true, if LC connector is active + GC connector is active + successful authorization as PM
- (see discussion in https://github.com/cgeo/cgeo/issues/10477#issuecomment-830838124 and following entries for details)

set LC 'active' info in services summary (rel. to #10477)

---

main/res/layout/cachedetail_description_page.xml
main/src/cgeo/geocaching/CacheDetailActivity.java

#10499 has caused the side effect, that a duplicated separator line is displayed for all non-LC caches:
This is fixed with this PR...

optimize LC extra description box in cachedetails

---

main/src/cgeo/geocaching/CacheDetailActivity.java

Avoids "loops back into c:geo" when using "Open Geochecker"
fixes #10526

support opening geochecker via webview

---

main/src/cgeo/geocaching/CachePopupFragment.java
main/src/cgeo/geocaching/utils/EmojiUtils.java

Allow changing the assigned cache icon in cache details popup via long click on the marker in the popups menu bar.

Long tab power user shortcut in cache details popup

---

main/res/values/strings.xml
main/src/cgeo/geocaching/log/LogsViewCreator.java
main/src/cgeo/geocaching/utils/TranslationUtils.java

The Google Translate App supports such cool "in-app translation popups" nowadays (appearance not configurable and dependents on the device):
---
Unfortunately (or maybe even fortunately to keep things simple ;-)) it doesn't allow configuring the target language, but since it remembers the last selected language(s) it is IMHO totally fine...
| before | after (if Translate App is installed) |
|-|-|
| ![grafik](https://user-images.githubusercontent.com/64581222/117031952-5f471a80-ad01-11eb-87cd-ac9b828a169b.png) | ![grafik](https://user-images.githubusercontent.com/64581222/117031930-59513980-ad01-11eb-9799-30513e199783.png) |
BTW, I also reordered the "share text" item, so the elements are in a more logical order.

make use of google translate in-app translation popup

---

tests/src-android/cgeo/geocaching/downloader/DownloaderTest.java

make downloader tests more flexible:
- accept a range for routing tiles between 1115 and 1130 (currently: 1121)
- test "non-dirs found" against `list.size()` instead of a specific number
- target this update to `release` to catch those tests as well

make downloader test more flexible (fix #10553)

---

main/res/layout/cacheslist_item_select.xml
main/res/values/themes.xml
main/src/cgeo/geocaching/activity/ActivityMixin.java
main/src/cgeo/geocaching/apps/navi/GoogleNavigationApp.java
main/src/cgeo/geocaching/ui/dialog/Dialogs.java
main/src/cgeo/geocaching/utils/BackupUtils.java

I hope we can refactor the base theme of cgeo rather soon, so that such kind of fixes aren't necessary anymore! 
Here we have another dialog which can be shown from one activity but not from another :-/
Anyway, a compromise of omitting attributes and adding them to the dialog theme, makes the "google maps navigation dialog" working fine...
---
The background in the dialog (uses the same resource file) never looked good anyway (which is also solved implicitly):
---
On the way, I've done some small cleanup, which makes usage of ContextThemeWrapper easier...

avoid crash when starting google maps navigation (fix #10550)

---

main/src/cgeo/geocaching/files/AbstractImportGpxZipThread.java

PR #10539 doesn't show the import progress while importing the GPX. 
After debugging, it seems that the file size is stored after the GPX file inside the ZIP. So to get the file size, the whole file needs to be streamed. Since nothing has to be done with the file content, this initial read-through is relatively quick and IMHO it definitely is worth it so that the progress can be displayed in the further processing. (Maybe 1-2 extra seconds, but in exchange the user knows in the following 20 seconds that the app has not got stuck but is still importing.) 
Furthermore, the entire file will be read only if the file size could not be found with the today's method, so it will not slow down existing functionality. The issue occurred to me when importing a bookmark list GPX-ZIP-file, but can …

handle case that no file size can be specified while importing zipped GPX files

---

main/res/layout/dialog_title_button_button.xml
main/res/values/styles.xml

With the recent addition of setting a cache icon directly in the map's "create UDC" popup, the title is no longer visible when using light theme. This PR defines an adapted style which uses black title color for this popup.
|before|after|
|---|---|
|![image](https://user-images.githubusercontent.com/3754370/117548360-e283ab80-b034-11eb-8145-b3f015e6d96f.png)|![image](https://user-images.githubusercontent.com/3754370/117548364-e7485f80-b034-11eb-979c-111d1929f7ad.png)|

use dark title color in UDC popup

---

main/src/cgeo/geocaching/connector/internal/InternalConnector.java

On long tap on the map the "Create UDC" popup will open. Currently the actual input field is hard to see, as there is no visual indicator for it. This PR automatically sets the focus to the input field, so that you get the blinking cursor as indicator.

auto-focus UDC create input field

---

main/src/cgeo/geocaching/connector/lc/LCApi.java

see #10557 for the associated discussion. In a nutshell: LC connector returned 100 caches hardcoded while other connectors returned only 20 which caused an unbalanced result on the map (LCs dominated). Now I am adjusting to `take=20` to be on par.

Optimize nearby results for ALC #10557

---

main/res/layout/dialog_title_button_button.xml
main/res/values/styles.xml

Follow up of #10562
Fixes dark text color in dark theme:

use correct title color in UDC popup / emoji chooser

---

main/src/cgeo/geocaching/storage/DataStore.java

The SQL build for a coordinates-based search will fail, if latitude and/or longitude are negative, as this leads to a double dash in the SQL, which will be interpreted as a comment. 
Something like this will be shown in the error log:
```
05-08 21:25:36.574 6321-6321/cgeo.geocaching E/SQLiteLog: (1) near "--122.084000))) ASC LIMIT 1000": syntax error
05-08 21:25:36.574 6321-6321/cgeo.geocaching E/cgeo: [main] DataStore.loadBatchOfStoredGeocodes
android.database.sqlite.SQLiteException: near "--122.084000))) ASC LIMIT 1000": syntax error (code 1): , while compiling: SELECT geocode FROM cg_caches t WHERE (geocode IN (SELECT geocode FROM cg_caches_lists WHERE list_id =11)) ORDER BY ((ABS(t.latitude - 37.421998) + ABS(t.longitude --122.084000))) ASC LIMIT 1000
at …
```

fix coords sql for negative latitude/longitude

---

main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/AbstractCachesOverlay.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/GeoitemRef.java
main/src/cgeo/geocaching/maps/routing/RouteSortActivity.java
main/src/cgeo/geocaching/models/RouteItem.java
main/src/cgeo/geocaching/utils/Formatter.java

Lots of description here: #10583
A word on "conditional D/T" texts: LC caches don't have D/T ratings. When the cache object is instantiated, the respective properties are left uninitialized. In various views this did the job and no D/T related strings were shown, however, in Map view when a target was set, `D 0.0 . T 0.0 .....` was shown. This PR addresses that bug in addition to showing short LC  code as reported in the referenced issue.

short LC names and conditional D/T texts (Fixes 10583)

---

main/src/cgeo/geocaching/WaypointPopupFragment.java

There are still occurences in the code where the long "geocode" associated with Adventure Lab Caches hit the surface. This PR tries to fix them one after another. 
At this time, the waypoint popup gets fixed.

More ugly lc fixes (Fixes #10601)

---

main/res/layout/udc_create.xml
main/res/values/preference_keys.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/apps/cachelist/InternalCacheListMap.java
main/src/cgeo/geocaching/connector/internal/InternalConnector.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/DefaultMap.java
main/src/cgeo/geocaching/maps/MapOptions.java
main/src/cgeo/geocaching/maps/google/v2/GoogleMapView.java
main/src/cgeo/geocaching/maps/interfaces/MapViewImpl.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/settings/Settings.java

When you are mapping a cache list using the map symbol, and create a UDC on that map, the dialog will now ask whether you want to store that UDC in the current list. If you don't check the checkbox, the new UDC will be stored in the UDC standard list.
The dialog remembers your selection.
If you are opening the map using a different way, no checkbox will be shown, and newly created UDC will be stored in the UDC standard list as before.
(UDC created from within a cache list will be stored in that list, as before.)
|mapping a cache list|any other way|
|---|---|
|![image](https://user-images.githubusercontent.com/3754370/117555189-44580b80-b05d-11eb-9d33-5a62a0cc772e.png)|![image](https://user-images.githubusercontent.com/3754370/117555191-49b55600-b05d-11eb-9346-fb60b47c9712.png)|

create UDC: offer "use current list" (if available) (fix #10427)

---

main/res/values/strings.xml
main/src/cgeo/geocaching/utils/BackupUtils.java

- Currently no backups can be created if the database does not contain any caches. This had been implemented as a safety measure to not overwrite the (at that time) only existing backup with an empty one.
- Meanwhile we can have several backups at the same time, so the safety measure is no longer needed (in most cases, at least).
- As one might to backup the settings, allow creating a backup even when there are no caches to back up. But to be on the safe side, ask the user if she/he really wants to create a backup.

Allow backup of empty database (fix #10590)

---

main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/settings/Settings.java

Happens for both brouter tiles and maps/themes.
PR fixes this by checking whether the "last check" value is already set or not. If not (meaning: first start after activating the respective update option) remember the current date/time as "last checked" and return silently. Otherwise: Check date/time and act accordingly. Fixes #10606.

Skip unnecessary update checks directly after activating auto-download checks

---

main/res/values/strings.xml
main/src/cgeo/geocaching/downloader/ReceiveDownloadActivity.java

- tries to fix issue #10615
- fixes a full scan on opening the zip (will now stop after first found map file)
- uses `BufferedOutput`
- avoids flooding UI with progress messages (zip had been updating in chunks of mostly less than 1k!, thus very frequently)
- outputs the processed size in K/M/G etc.
I'm not sure if that really fixes the original issue, but in several tests c:geo now stays responsive (where we had ANR before) on starting to transfer a downloaded file, and while the system's download manager took more than 10 minutes for a 590 MB file to download, unzipping to app. 700 MB and transferring it to c:geo was done in about 50s in the emulator.
@gcey:
Do you have a chance to test this build when it's compiled, to check whether it fixes the problem you described in #10615?

enhance user experience on receiving download (rel. to #10615)

---

main/src/cgeo/geocaching/enumerations/CacheSize.java
main/src/cgeo/geocaching/utils/Formatter.java

Add size info to map title for a given cache.
Uses `XXS` (nano , OC only) / `XS` (micro) / `S` (small) / `M` (regular) / `L` (large) / `XL` (extra large, OC only), `V` (virtual), - (none), `O` (other) and `?`. For screenshot see https://github.com/cgeo/cgeo/issues/10626#issuecomment-841710331

add size info to map title (fix #10626)

---

tests/src-android/cgeo/geocaching/brouter/expressions/EncodeDecodeTest.java

Since SAF-migration for internal routing engine is complete, we can now add the last missing test from the original BRouter test suite.

Migrate last missing brouter test (fix #10279)

---

main/src/cgeo/geocaching/Intents.java
main/src/cgeo/geocaching/storage/ContentStorageActivityHelper.java

Although this seems kind of hacky, it actually works... ;-)
Furthermore, the usage of it should be uncritical. The worst thing which could happen is that the EXTRA is simply ignored is new/some android versions.

force show internal storage on SAF folder selection (fix #10639)

---

main/src/cgeo/geocaching/storage/ContentStorageActivityHelper.java
main/src/cgeo/geocaching/utils/TrackUtils.java

fix #10684: make csah handle persisted uris correctly, switch trackutils to right action type

fix #10684: make csah handle persisted uris correctly, switch trackutils to right action type

---

main/src/cgeo/geocaching/downloader/AbstractDownloader.java
main/src/cgeo/geocaching/downloader/AbstractMapDownloader.java
main/src/cgeo/geocaching/downloader/DownloaderUtils.java
main/src/cgeo/geocaching/downloader/MapDownloaderFreizeitkarte.java
main/src/cgeo/geocaching/downloader/MapDownloaderHylly.java
main/src/cgeo/geocaching/downloader/MapDownloaderOpenAndroMaps.java
main/src/cgeo/geocaching/downloader/ReceiveDownloadActivity.java

- On downloading a map using the integrated downloader: automatically download theme file (if required and not yet installed)
- This replaces the (interactive) `onFollowup` method which was blocking using a background service for download.

automatically download map themes (if necessary) (fix #10694)

---

main/res/layout/mapdownloader_activity.xml

- Currently header for map downloader is unreadable in light theme.
- This PR defines the background color to fix this.
|before|after|
|---|---|
|![image](https://user-images.githubusercontent.com/3754370/119186431-6481c480-ba78-11eb-97af-615cb9f325d1.png)|![image](https://user-images.githubusercontent.com/3754370/119186503-76636780-ba78-11eb-8db8-44ec46f4a38d.png)|

set background color for downloader to fix light theme

---

main/res/raw/changelog_full.md
main/res/raw/changelog_master.md
main/res/raw/changelog_release.md
main/res/values/strings.xml
main/src/cgeo/geocaching/AboutActivity.java

This PR introduces a differentiation between to-be-published changelog and "full" changelog by providing the infrastructure for it. (No changes to `changelog_master.md` yet, but cleaned `changelog_release.md` to show a possible differentiation between full and shortened changelog.)
The "full" changelog is divided into sections "next release" (`release`), "current development" (`master`) and published releases. As it starts with our latest release `2021.05.20`, it also contains a link to our release history for older releases.
This page (`raw/changelog_full.md`) can be linked to from our website as official release history.

introduce full changelog (rel. to #10701, part b)

---

main/src/cgeo/geocaching/connector/lc/LCConnector.java

Our status updates queries all connectors for their `isActive()` state. LC connector reported this only according to the setting for LC, but as LC connector also depends on having an active GC connection as a PM, those connections needed to be checked additionally for the counter to be correct.

counting LC as active requires active GC connection as PM (fix #10707)

---

main/res/values/strings.xml
main/res/values/strings_not_translatable.xml
main/src/cgeo/geocaching/AboutActivity.java
main/src/cgeo/geocaching/utils/SystemInformation.java

Now that we are using MarkDown to format our version history, let's expand this to about:contributors and about:system info

use MarkDown for about:contributors and about:system info

---

main/build.gradle

Reverts cgeo/cgeo#10680
see https://ci.cgeo.org/job/cgeo%20pull%20request/5833/console
and Issue #10730

Revert "Bump core from 1.3.2 to 1.5.0"

---

main/src/cgeo/geocaching/files/GPXParser.java
tests/res/raw/ocddd2_empty_coord.gpx
tests/src-android/cgeo/geocaching/files/GPXImporterTest.java
tests/src-android/cgeo/geocaching/files/GPXParserTest.java

Set `original coordinates empty` for imported gpx (e.g. GSAK, not exported via c:geo) for waypoint with 0/0
Otherwise coordinates of owner defined waypoints with empty coordinates could not be assigned
fix #6915
Only with the flag original coordinates empty set, the user can edit pre-defined waypoints with empty coordinates.
In some cases (e.g. gpx exported from GSAK) the flag is not set: the flag is only set, if the cgeo-extension is contained in the gpx.

Fix: Enable editing of imported waypoints with empty coordinates (fix #6915)

---

main/src/cgeo/geocaching/InstallWizardActivity.java
main/src/cgeo/geocaching/MainActivity.java

Fix the lint error of missing calls to `super.onRequestPermissionsResult`

add missing super calls to onRequestPermissionsResult (fix #10732)

---

main/src/cgeo/geocaching/settings/SeekbarPreference.java

Fix wrong default value for proximity-preferences:
* avoid doubled conversion of the value, 'onGetDefaultValue' should return the default value, which is in this case the integer metric value (default value in the preferences.xml is defined as metric distance) and not the internal integer progress value.
* check for min/max on setting default-value
#10598

Fix wrong default value for proximity-preferences (fix #10598)

---

main/src/cgeo/geocaching/CacheDetailActivity.java

Keep new styles' background color for cache description instead of using plain white/plain black.

fix cache details background color (fix #10751)

---

main/res/values/styles.xml

fix #10760: text size of author in log

fix #10760: text size of author in log

---

main/res/values/themes.xml

Sets the status bar color for splash screen to pure black

set status bar color for splash screen to black (fix #10761)

---

main/res/values/styles.xml
main/res/values/themes.xml

fix #10739
As pointed out, changing the general button theme seems to be not that easy. As "quick fix" let's just apply the OutlinedButtonStyle  as base of our existing button style. This works like a charm as all existing buttons already use that style, but we need to add the `button`-style to every newly created button...
There might be better solutions, but this is the easiest for now.

use OutlinedButtonStyle for button theming

---

main/AndroidManifest.xml
main/res/layout/cachelist_spinneritem.xml
main/res/layout/settings_toolbar.xml
main/res/values-night/colors_dark.xml
main/res/values/colors.xml
main/res/values/colors_light.xml
main/res/values/styles.xml
main/res/values/themes.xml
main/src/cgeo/geocaching/activity/ActivityMixin.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/MapUtils.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/settings/SettingsActivity.java

Set the background color #FF202020 as suggested in https://github.com/cgeo/cgeo/issues/10752#issuecomment-848974727
Result would be like this:
And in conjunction with #10764 it would look like this:

set darker background for dark mode (fix #10752)

---

main/build.gradle

Switch used version of Mapsforge from specific build to official release 0.16.0

upgrade mapsforge to 0.16.0 (fix #10773)

---

main/res/layout/popup.xml
main/res/values-night/colors_dark.xml
main/res/values/colors_light.xml

Defines background color for cache / waypoint popup, using the same color as other dialogs (white in light theme, #424242 in dark theme)

define background color for cache/wpt popup (fix #10777)

---

main/res/layout/cache_information_item.xml
main/res/layout/cachedetail_description_page.xml
main/res/layout/cachedetail_details_page.xml
main/res/layout/logs_item.xml
main/res/layout/popup.xml
main/res/layout/waypoint_item.xml
main/res/values/styles.xml

Not setting `textColor` for certain elements lead to low-contrast texts in light mode, therefore added `textColor` to several elements in cache detail pages and cache popup.

fix some low contrast texts in light mode

---

main/res/layout/map_settings_dialog.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/maps/MapSettingsUtils.java
main/src/cgeo/geocaching/settings/Settings.java

- remove the text "Routing is only available if BRouter is installed" in map quick settings
- adds a blue "?" button right of routing mode buttons, if no routing is available
- pushing that button asks the user to activate internal routing and auto-download of routing data, and updates settings and the dialog's contents if activation is confirmed

replace brouter info with dialog (fix #10776)

---

main/res/layout/cache_information_item.xml

Increases text size in cache details list to `detailsPrimary` and increase the space between label and item:

cache detail list: increase textSize and spacing (fix #10759)

---

main/src/cgeo/geocaching/AbstractDialogFragment.java
main/src/cgeo/geocaching/WaypointPopupFragment.java

Displays the cache name in the cache popup to help with display of long cache names which get truncated in the popup's actionbar title.
|cache popup|waypoint popup|
|---|---|
|![image](https://user-images.githubusercontent.com/3754370/120035804-724ac300-bfff-11eb-8d38-3acbc364e35a.png)|![image](https://user-images.githubusercontent.com/3754370/120035823-7d055800-bfff-11eb-928e-ef81f8a213a7.png)|

show cache name in poup details (fix #10774)

---

main/res/layout/avpactivity.xml
main/src/cgeo/geocaching/AboutActivity.java
main/src/cgeo/geocaching/activity/AVPActivity.java
main/src/cgeo/geocaching/activity/AVPFragment.java

Reimplements c:geo's about pages using ViewPager2 and Material Tabs instead of the old viewpager.
Can be a base to remove the old viewpager completely (after having migrated `CacheDetailsActivity` to ViewpPager2 / Material Tabs as well.
This is a first shot at migration. Looks fully functional to me, but could use more safeguards, and I'm not sure yet, whether this approach will work for `CacheDetailActivity` as well. Just wanted to start with the easier part as a MVP...

implement about pages with ViewPager2 and material tabs

---

main/res/values/strings.xml
main/src/cgeo/geocaching/InstallWizardActivity.java

Changes the "advanced" page of the configuration wizard: Instead of pointing to the external BRouter app in Play Store shows a button to activate internal routing engine and auto-downloading of missing routing data (if no routing available currently).
|No routing engine available currently|Routing engine available currently|
|---|---|
|![image](https://user-images.githubusercontent.com/3754370/120038790-19315e00-c004-11eb-861b-517ef6b363ec.png)|![image](https://user-images.githubusercontent.com/3754370/120038313-58ab7a80-c003-11eb-9b99-5ee737b03c50.png)|

point wizard to internal routing engine (fix #10745)

---

main/res/layout/waypoint_popup.xml

Currently the "more details" button label in waypoint popup gets truncated, therefore change this button to "full width":

make waypoint 'more details' button full-width

---

main/res/layout/downloader_item.xml
main/src/cgeo/geocaching/downloader/DownloadSelectorActivity.java

- restores icon display for map downloader (fix #10805)
- sets correct font sizes for list entries

fixes for downloader layout (fix #10805)

---

main/res/layout/map_settings_item.xml

Reduces the linespacing in map quick settings menu for caches/waypoints settings by reducing the min-width for the checkbox
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/3754370/120544205-7440c780-c3ed-11eb-9d38-7c1721a17e47.png)|![image](https://user-images.githubusercontent.com/3754370/120544232-7a36a880-c3ed-11eb-8040-c4ca4067e78b.png)|
Before it was set to `minTouchTargetSize` by material theme (being 48dp), now it's set to 32dp.
Have not found a way yet to set this for all checkboxes, though.

reduce linespacing in map quick settings (fix #10809)

---

main/src/cgeo/geocaching/utils/SystemInformation.java

Due to a misplaced space the "settings" info was tangled with the "routing mode info":

fix small system info formatting error

---

main/src/cgeo/geocaching/downloader/DownloadNotificationReceiver.java

Related to #10815: Deletes broken downloads from system's download manager, which automatically deletes the partial file from storage as well.
Does not delete a partially copied file after a successful download (which is the other part of #10815), therefore not closing that issue yet.

remove failed download from download manager (rel. to #10815)

---

main/res/values/strings.xml
main/src/cgeo/geocaching/ui/dialog/Dialogs.java
main/src/cgeo/geocaching/utils/DebugUtils.java

Format the debug info for downloads which got initiated using the integrated downloader:
- replace dialog title by a translatable string
- remove the "invisible" icon in the dialog's header
- use markdown formatting for entries (basically the list mode)

apply some formatting to downloads' debug info

---

main/res/layout/map_settings_item.xml
main/res/values/styles.xml
main/res/values/themes.xml

Found a way to apply the reduced line spacing to all material checkboxes, which will make it work not only in the map quick settings, but in other places, too, e. g. in the cache type filter:
|before|after|
|---|---|
|![image](https://user-images.githubusercontent.com/3754370/120554915-a278d400-c3fa-11eb-864b-1fbb4439f710.png)|![image](https://user-images.githubusercontent.com/3754370/120554947-a99fe200-c3fa-11eb-8e33-7a3cd00cf3cc.png)|
The workaround (directly applying a new `minHeight` for the map quick settings item) can therefore be removed.

adjust minHeight of all material checkboxes

---

main/res/values/dimens.xml
main/res/values/styles.xml
main/res/values/themes.xml

- see https://github.com/cgeo/cgeo/pull/10826#issuecomment-853557166
- adjusts (decreases) the minimum height of material radiobuttons (same as #10826, but for radiobuttons)
- extracts this minimum height as a dimension, used for both checkboxes and radiobuttons

adjust minHeight of all material radioButtons

---

main/res/layout/about_version_page.xml

The label on top of the image in the about:version page is currently unreadable in both dark and light theme, text should always be white for this label.

fix image label color in about:version page

---

main/src/cgeo/geocaching/log/LogCacheActivity.java

fix #10831: move gui stuff out of async log send task into GUI thread

fix #10831: move gui stuff out of async log send task into GUI thread

---

main/src/cgeo/geocaching/ui/EditNoteDialog.java

- See https://github.com/cgeo/cgeo/commit/6c3a37b2a5cbf4685b85c0a808d0de3ae79532e8#commitcomment-51695604
- removes the offending call to "requestWindowFeature", which makes the dialog break at least on API 21 and seems not to be necessary anyway
- tested successfully against API 21 and API 30

remove breaking requestWindowFeature for edit PN

---

main/res/values/dimens.xml
main/res/values/styles.xml
main/res/values/themes.xml
main/src/cgeo/geocaching/ui/dialog/Dialogs.java

- introduce basic alertDialog theming (does not work if you set your own content view)
- reduce line spacing for "select list" dialogs

introduce basic alertDialog theming

---

main/res/values/styles.xml

Center icon in buttons styled with `button_icon`, see https://github.com/cgeo/cgeo/pull/10818#issuecomment-854489671

make icons in MaterialButton centered

---

main/res/color/settings_primary_selector_light.xml
main/res/color/settings_primary_selector_night.xml
main/res/color/settings_secondary_selector_light.xml
main/res/color/settings_secondary_selector_night.xml
main/res/values/styles.xml
main/res/values/themes.xml

adds color selectors for settings activity to be able to distinguish between enabled and disabled settings

change color for disabled settings to grey (fix #10845)

---

main/src/cgeo/geocaching/ui/ViewUtils.java

Currently slider label uses a color retrieved from (static) application context, which returns black always.
Make this context-aware to retrieve a theme-specific color.

make slider color context-aware (fix #10852)

---

main/res/drawable/copyright.xml

The copyright sign itself already uses black color on white background, so no tint needed (which was white in this case and covered the c sign).

remove tint from copyright sign (fix #10855)

---

main/res/layout/cachelist_spinneritem.xml

Adjust layout height of cachelist spinner to add some spacing between entries:

add spacing to cachelist spinner item (fix #10854)

---

main/res/layout/install_wizard.xml
main/res/values/styles.xml
main/src/cgeo/geocaching/InstallWizardActivity.java

- uses solid button for default action only
- pages without a default action (because of having several actions of equal importance) will no longer have any solid button at all (e. g.: services page, advanced settings page)

use solid button in wizard for default action only (fix #10835)

---

main/res/values/dimens.xml
main/res/values/styles.xml
main/res/values/themes.xml
main/src/cgeo/geocaching/list/StoredList.java
main/src/cgeo/geocaching/ui/dialog/Dialogs.java

- revert setting a global list line height
- add optional `styleRes` parameter to `Dialogs.newBuilder()`
- create a style `compactDialogs` based on `cgeo` and material alert dialogs with a reduced list line height and correct font colors and sizes
- and apply this style to the three "pick a list" dialogs

revert global listheight, format alertdialog lists (fix #10861)

---

main/res/values/strings_not_translatable.xml

Add attribution to material design icons in about:contributors' page

add attribution to material design icons (fix #10858)

---

main/src/cgeo/geocaching/models/Geocache.java
tests/src-android/cgeo/geocaching/models/GeocacheTest.java

Waypoint was not extracted, if already a waypoint with same name but different coordinates exist.
Don't compare name for waypoints with coordinates.
#10677
bug was introduced by me in PR #9337, there the waypoint-name-matching was introduced for waypoints with empty coordinates

Extract waypoint with same name but different coordinates from personal note (fix #10677)

---

main/src/cgeo/geocaching/models/WaypointParser.java
tests/src/cgeo/geocaching/models/WaypointParserTest.java

Exports the formula of a waypoint to the PN, even if all variables are defined and the coordinates could be calculated.
This would be to have the variables "archived" in the PN.
#9211 
#9633 
see comment of @Lineflyer  https://github.com/cgeo/cgeo/issues/9211#issuecomment-854134154

Export formula to PN instead of coordinates for completed formula

---

main/res/values/styles.xml
main/res/values/themes.xml

- fixes the "cannot use checkboxes in multi-select "pick a list" dialog
- reason: `checkedTextViewStyle` for `AlterDialog` with multi selection enabled must not inherit from `Widget.MaterialComponents.CompoundButton.CheckBox`

fix checkbox unreachable error in pick list (fix #10867)

---

main/res/layout/checkbox_item.xml

use smaller icon size in map-settings
has also affects in filter-activity and even there for the cache-type-icons. I am not sure, if that is ok as well. Otherwise I have to find a different solution
#10868

use smaller icon-size in map-settings (rel #10868)

---

main/res/layout/cache_filter_generic_string.xml
main/res/layout/editwaypoint_activity.xml
main/res/layout/search_activity.xml
main/res/values/styles.xml
main/src/cgeo/geocaching/EditWaypointActivity.java
main/src/cgeo/geocaching/activity/AbstractActivity.java

- use material TextInputLayout for edit waypoint page 
- replace old viewbindings (colliding with Gradle plugin 5) with ViewBinding class
|default|multi-line edit|with bearing + distance|
|---|---|---|
|![image](https://user-images.githubusercontent.com/3754370/121253536-83ba8780-c8a9-11eb-8dd5-80e17421896e.png)|![image](https://user-images.githubusercontent.com/3754370/121253585-946afd80-c8a9-11eb-992b-7fdd5c8edfeb.png)|![image](https://user-images.githubusercontent.com/3754370/121253632-a482dd00-c8a9-11eb-8c77-3d2d6f800e32.png)|
(First two screenshots are from editing a given waypoint, third screenshot is from creating a user-defined waypoint)
- use style `textinput_dropdown` if you are embedding a single line `AutoCompleteTextView`
- use style `textinput_edittext` if you are embedding …

use material TextInputLayout for edit waypoint page (rel. to #10763)

---

main/src/cgeo/geocaching/CacheDetailActivity.java

Reset cache description on reloading a cache to prevent doubling the contents.

prevent doubling cache description on reload (fix #10901)

---

main/res/layout/map_settings_dialog.xml

fix #10906: mapquicksettings layout on low res devices with SDK 21:

fix #10906: mapquicksettings layout on low res devices with SDK 21

---

tests/src-android/cgeo/geocaching/downloader/DownloaderTest.java

fix failing DownloadTest: new andromaps on server
There's a new andromap on server. from date, I assume it is `Scandinavia_NorthEast.zip`

fix failing DownloadTest: new andromaps on server

---

main/src/cgeo/geocaching/AboutActivity.java
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/activity/TabbedViewPagerFragment.java
main/src/cgeo/geocaching/log/LogsViewCreator.java

- Disable tabbed content view on view creation
- and enable it only after successful load of content
=> avoids "view skeletons" described in #10900

enable tabbed view on successful load only (fix #10900)

---

main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/SearchActivity.java
main/src/cgeo/geocaching/filters/core/GeocacheFilter.java
main/src/cgeo/geocaching/filters/gui/GeocacheFilterActivity.java
main/src/cgeo/geocaching/maps/MapUtils.java
main/src/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/settings/Settings.java

related to #10711: store only one global filter setting, no contexts any more
This PR will remove context-specific filter storage completely. There will only be one filter set stored (always the last one used) across all contexts: map, offline cache lists and online search results (nearby search, owner, user, search-by-filter).
This PR will not yet replace the current additional global cache type filter, this remains in parallel for now

rel to #10711: store only one global filter setting, no contexts any more

---

main/res/layout/cacheslist_activity.xml
main/res/layout/cacheslist_item.xml
main/res/layout/downloader_item.xml

Fix progress spinner not spinning (#10891) and give UI touch feedback in cache list and map downloader...

Move full screen progress spinner to CircularProgressIndicator

---

main/res/layout/cache_image_item.xml
main/res/layout/tabbed_viewpager_activity_refreshable.xml
main/src/cgeo/geocaching/AboutActivity.java
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/TrackableActivity.java
main/src/cgeo/geocaching/activity/TabbedViewPagerActivity.java

- support non-refreshable pages in `TabbedViewpager` & set about pages to non-refreshable
- fix setting content view for trackable pages
- fix cache details image page progress spinners

make about pages non-refreshable (fix #10903)

---

main/src/cgeo/geocaching/SearchResult.java
main/src/cgeo/geocaching/connector/lc/LCConnector.java
tests/src-android/cgeo/geocaching/downloader/DownloaderTest.java

fix #10567: make LCConnector consider totalcountGc, make SearchResult-takeover use larger number
Note that this whole "totalCountGC" logic in SearchResult is a bit mysterious to me, I would appreciate a review from someone knowing this a little better.
My assumption is that this is all no longer necessary once we remove "INextPage" capability

fix #10567: make LCConnector consider totalcountGc, make SearchResult-takeover use larger number

---

main/res/layout/about_version_page.xml

Before (string "canero" is black on black when using light theme):

Fix wrong text color in about activity (text "carnero" was invisible)

---

main/res/layout/gpx_export_individual_route_dialog.xml
main/src/cgeo/geocaching/export/IndividualRouteExport.java

Migrates the "Export individual route as GPX" filename dialog to material `TextInputLayout`
Does work generally, but the dialog actually shrinks on entering the text input field, leading to info text below the input field being cut off. - Any ideas?

migrate individual route export dialog to material

---

main/res/layout/dialog_edittext.xml
main/res/layout/gpx_export_individual_route_dialog.xml
main/res/values/styles.xml
main/src/cgeo/geocaching/export/IndividualRouteExport.java
main/src/cgeo/geocaching/filters/gui/GeocacheFilterActivity.java
main/src/cgeo/geocaching/list/StoredList.java
main/src/cgeo/geocaching/settings/SeekbarPreference.java
main/src/cgeo/geocaching/ui/dialog/SimpleDialog.java

migrate SimpleDialog.input to material TextInputLayout
The last one is not yet perfect, although it's using identical source code, but as settings are not based on `AppCompatActivity` I guess there's not much we can do about it.
@eddiemuc 
Can you cross-check if I haven't broken anything in `SimpleDialog.input`? Thanks.

migrate SimpleDialog.input to material TextInputLayout

---

tests/src-android/cgeo/geocaching/connector/gc/GCParserTest.java

temporarily disable GC watchcount test which fails due to website changes (see #10939)
(I'll add a reminder over there to re-enable this test after fixing the issue)

temporarily disable GC watchcount test 

---

main/res/layout/authorization_credentials_activity.xml
main/res/layout/authorization_token_activity.xml
main/res/layout/editwaypoint_activity.xml

- Adds `TextInputLayout` styling to credentials activity and authorization token activity, which migrates stlying for gc.com, gcvote and geokrety services. OAuth-based services are untouched as they do not use input fields within c:geo
- also simplifies some styling for EditWaypointActivity (separate commit)

migrate authentification activities to TextInputLayout (fix #10893)

---

main/res/layout/view_settings_add.xml
main/src/cgeo/geocaching/settings/ViewSettingsActivity.java

Fixes and migrates "add setting" dialog:
- make dialog scrollable (to keep radio buttons accessible on opening keyboard)
- migrate layout to viewbindings
- migrate text field to TextInputLayout
- fix some formatting errors in the layout file
Also migrates the "edit setting" dialog

fix and migrate 'add setting' dialog (fix #10953)

---

main/res/layout/logcache_activity.xml
main/src/cgeo/geocaching/log/LogCacheActivity.java

Migrates the "enter log" dialog to `TextInputLayout` and replace our self-built character counter with material built-in

migrate enter log to TextInputLayout (including counter)

---

main/res/values/styles.xml
main/res/values/themes.xml

A bit difficult to see, but before the overflow icon was gray while all other icons are white...
Before:
Now:

set correct tint for action bar overflow button

---

main/res/values/dimens.xml
main/res/values/styles.xml

As discussed in https://github.com/cgeo/cgeo/issues/10960#issuecomment-864392162: here's a proposal for a reduced button text font size.
|old font size|new font size|
|---|---|
|![image](https://user-images.githubusercontent.com/3754370/122655547-62805380-d153-11eb-8dc6-9e337297ee98.png)|![image](https://user-images.githubusercontent.com/3754370/122655549-67450780-d153-11eb-9aae-d5a06cc474e4.png)|
|![image](https://user-images.githubusercontent.com/3754370/122655559-7b890480-d153-11eb-8b55-49e13c9fde9f.png)|![image](https://user-images.githubusercontent.com/3754370/122655556-75932380-d153-11eb-9b98-566430011610.png)|

reduce button font size

---

main/res/layout/logtrackable_activity.xml
main/src/cgeo/geocaching/log/LogTrackableActivity.java

Migrates the "log trackable" dialog to `TextInputLayout`

migrate 'log trackable' to TextInputLayout

---

main/res/layout-w1200dp/coordinatescalculate_dialog.xml
main/res/layout/coordinates_calculate.xml
main/res/layout/coordinates_input.xml
main/res/layout/coordinatescalculate_dialog.xml
main/res/values/styles.xml
main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java

- migrates coordinates input dialogs to `TextInputLayout` (except the detailed variants, as discussed in our last meeting)
- removes `clear_text` ability from multi-line input dialogs, as discussed in https://github.com/cgeo/cgeo/pull/10955#issuecomment-864383257

migrate coordinates input dialogs to TextInputLayout

---

main/res/layout/fragment_edit_note.xml

Migrates "edit note" dialog to `TextInputLayout`
Same problem arises here as described in #10953: dialog gets truncated as the keyboard opens up immediately, hiding contents of the dialog. Depending on screen and keyboard size there may not even be a visual indicator, that something is outside the visible area and can be scrolled to (e. g.: the checkbox below the dialog).

migrate 'edit note' dialog to TextInputLayout

---

main/res/layout/imageselect_activity.xml

- Migrates "select image" dialog to `TextInputLayout`
- Adds character counters for both text fields (as they are limited on gc.com)

migrate 'select image' dialog to TextInputLayout + add counters

---

main/res/layout/template_preference_dialog.xml
main/res/values/colors.xml
main/res/values/themes.xml
main/src/cgeo/geocaching/settings/TemplateTextPreference.java

And now down into the more ugly parts of our preferences...
- Migrates the "log template" dialog to `TextInputLayout`. Needs some manual adjustments of colors.
- Adds some basic dialog styling for our old preferences.

migrate log template dialog (rel. to #10763)

---

main/res/values/styles.xml

As requested in one of the issues related to `TextInputLayout`:
Our full-width buttons should use the same margins as our input fields, which is what this PR adjusts styles to.

align full button margin to TextInputLayout margin

---

main/res/drawable/textinputlayout_bcg_active.xml
main/res/drawable/textinputlayout_bcg_default.xml
main/res/layout/coordinates_calculate.xml
main/res/layout/coordinates_input.xml
main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java

- related to #10763
- add a colored border around the coordinate input fields in coordinate calculator for consistency (both coordinates input and calculator input)
- there's no added functionality like `TextInputLayout` has, so no hint, no start/end icon etc.
- it has the same outer margins as `TextInputLayout`, but inner padding is made smaller deliberately, as so many input boxes are included which need space

add colored border to coordinates input (for consistency)

---

main/res/values/themes.xml

- make dialog windowBackground transparent and only set the dialog's own background to specified color
- force colorAccent on button labels' text

tweak settings' dialog theming (fix #10792)

---

main/src/cgeo/geocaching/ui/ViewUtils.java

There was a "hole" in the touch target of checkbox items, if you click the view between the text and the checkbox...

fix touch target "hole" in checkbox item

---

main/res/values/strings.xml

In the overflow menu we had changed the strings some time ago, but we forgot to do the same change for the popup as well...

[cachelist] make strings more consistent

---

main/res/values/styles.xml

The previous style looked quite squashed and like an unintentional bug, now the UI looks much more well-engineered ;-)
|before|now|
|-|-|
|![grafik](https://user-images.githubusercontent.com/64581222/122945614-faab5200-d378-11eb-8477-94e4a7da99b0.png)|![grafik](https://user-images.githubusercontent.com/64581222/122945811-20d0f200-d379-11eb-9031-eb133b267fc1.png)

add default margin for icon_button_style

---

main/src/cgeo/geocaching/connector/gc/GCParser.java

fix #10940: make gc watchlist add/remove work again:
adapt `GCParser` methods `addToWatchlist`/`removeFromWatchlist `to website changes on gc.com

fix #10940: make gc watchlist add/remove work again

---

main/res/layout/editwaypoint_activity.xml
main/res/values/styles.xml
main/res/values/themes.xml

- applies more room around waypoint type spinner
- apply dialog background to spinner popup to be distinguishable from background in dark mode

format waypoint type spinner (fix #10974)

---

main/res/drawable/cursor.xml
main/src/cgeo/geocaching/settings/TemplateTextPreference.java

Workaround for cursor not showing in our `TemplateTextPreference` in settings.
Slightly different solutions needed for API < 29 / API 29+ due to API changes.

workaround for cursor not showing in settings' edittext (fix #10984)

---

main/res/values/styles.xml

Aligns text fields styled with `textinput_embedded` to top-left.

align multi-line edittexts to top left (fix #11008)

---

main/src/cgeo/geocaching/activity/TabbedViewPagerActivity.java

ViewPager2 has a built-in caching mechanism. Enlarge this to cover `CacheDetailActivity` pages completely.
- fixes #10975
- fixes #10978
- fixes #10964

enlarge cache size for TabbedViewPagerActivity

---

main/src/cgeo/geocaching/files/GPXParser.java
main/src/cgeo/geocaching/storage/DataStore.java
main/src/cgeo/geocaching/utils/CalendarUtils.java

fix #9639 
fix #10028
- Store service-specific `log_id` on PQ / GPX import 
- avoid log entry duplicates while importing PQ / GPX
The second is done by don't search for a specific timestamp in the db anymore, but rather accept the whole time range of the log day while searching for duplicates.
It's currently targeted to master, as users seam not to be affected too much by this bug (~at least @Lineflyer hadn't reported any support requests~ there where really quite some requests at the start of this year which seem to  got lost). If we want to do another small bugfix release anyway, I can retarget the PR for sure...

Improve GPX log import

---

main/res/menu/cache_list_options.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/CacheListActivity.java

This PR will make the new filter system the default one and moves the old filter system to a "prio 2" position.
It will also rename corresponding new filter items to "Filter" (remove "experimental") and rename the old filter to "Filter (legacy)"

make new filter system the default

---

main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/connector/su/SuApi.java
main/src/cgeo/geocaching/connector/su/SuConnector.java
main/src/cgeo/geocaching/filters/core/GeocacheFilter.java
main/src/cgeo/geocaching/filters/core/StringGeocacheFilter.java
main/src/cgeo/geocaching/loaders/KeywordGeocacheListLoader.java

rel to #10951: convert keyword search to filter
This PR converts the "keyword" online search to the new filter system. This means:
* the search does NO LONGER use the global settings "exclude found/own/disabled/archived"
* instead it filters using the current global filter IN ADDITION (AND-combined) to the given keyword
* Also, when changing the filter in list view afterwards, the online search is retriggered
As part of this PR the SUConnector was enabled for ISearchByFilter
And one discussion point: I realized while implementing this that ISearchByFilter makes most other search capabilities superfluous (e.g. `ISearchByKeyword`, `ISearchByOwner`, ...), so I guess they can be removed one-by-one once `ISearchByFilter` takes over. This also means that most of the Search-Loaders used by …

rel to #10951: convert keyword search to filter

---

main/res/layout/cachedetail_waypoints_page.xml
main/res/values/dimens.xml

This is a proposal for how to handle the conflict between fastscroll handler and content accessibility - for waypoint list in this case. I've added a small extra padding of `5dp`, see screens below.
If this works out fine, we can apply the same for the other fastscroll-enabled views.
|without extra padding|with added fastscroll padding|
|---|---|
|![image](https://user-images.githubusercontent.com/3754370/123526141-29595d80-d6d6-11eb-96d7-8804491046af.png)|![image](https://user-images.githubusercontent.com/3754370/123526145-324a2f00-d6d6-11eb-8914-87d8a79470a5.png)|

add extra padding for easier fastscroll in wpt list (rel. to #9992)

---

main/res/layout/cachelist_spinneritem.xml

For better readability set cache list spinner popup background color to actionbar background color, so it stays consistent with actionbar, but has better contrast to cache list background.

set cache list spinner item bg color to actionbar bg (rel. to #10982)

---

main/res/values/preference_keys.xml
main/src/cgeo/geocaching/connector/lc/LCApi.java
main/src/cgeo/geocaching/settings/Settings.java

attached pls find an update that treats the consumer-key in a more intelligent way. The string constant in the earlier PR had no real meaning after all. This PR provides a way to actually make use of the key.

issue_11001 improved

---

build.gradle
gradle.properties

- switch to gradle plugin 4.2.1 (supersedes #10620 and #10537)
- use aapt2-proto:4.2.1 (supersedes #10619)
- use the parallel garbage collector (new in AS 4.2)
For the releaseNotes see
- AS: https://developer.android.com/studio/releases/#4-2-0
- AGP: https://developer.android.com/studio/releases/gradle-plugin#4-2-0
fix #10548
supersedes #10620 #10619 #10537
Remarks:
1. garbage collector:
I made a test as suggested in https://developer.android.com/studio/build/profile-your-build#gradle-profile-option .
You have to call the following commands with and without the `-XX:+UseParallelGC` part.
~~~
gradlew clean
gradlew --profile --offline --rerun-tasks assembleBasicDebug
~~~
On my dev machine (dual core) it shows sometime a time reducing. But I think this machine is not representative.
2. v3 …

switch to AndroidStudio 4.2.1

---

main/res/values/strings.xml
main/src/cgeo/geocaching/filters/core/GeocacheFilterType.java
main/src/cgeo/geocaching/filters/core/NumberRangeGeocacheFilter.java
main/src/cgeo/geocaching/filters/core/StatusGeocacheFilter.java
main/src/cgeo/geocaching/filters/core/StoredSinceGeocacheFilter.java
main/src/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java
main/src/cgeo/geocaching/filters/gui/StatusFilterViewHolder.java
main/src/cgeo/geocaching/models/Geocache.java
main/src/cgeo/geocaching/utils/LocalizationUtils.java

rel to #10952: add things to status filter, add stored since filter
Status filter can now filter for "has trackables", "has own vote" and "has offline log":
New filter "stored since" allows for filtering of storage date/timestamp:

rel to #10952: add things to status filter, add stored since filter

---

main/res/layout/navigation_action.xml

fix mssing touch-feedback for compass in cache-detail
(revert to style ?actionButtonStyle and add android:layout_gravity="center_vertical" to navigation_action
#11039
#10943
still for API 21 squared effect in popup.
in full cache-detail all is fine for API 21
but for API 30 all is fine

fix mssing touch-feedback for compass in cache-detail

---

main/res/values/themes.xml

The solution seems to be even too easy, but it works... 😁

use correct tint for progress dialogs (fix #10793)

---

main/src/cgeo/geocaching/settings/AbstractCredentialsAuthorizationActivity.java
main/src/cgeo/geocaching/utils/BackupUtils.java

Today I had the issue, that although I had restored a settings backup with a different user account, the old/wrong account was still logged in...
I thought, I had seen some similar issues in our issue tracker, but I cannot find them... 🤷‍♂️ 
Anyway, something that is worth to fix ;-)

logout from active connectors, when restoring a settings backup

---

build.gradle
main/build.gradle

Update viewpager lib on `release` (by cherry-picking @bekuno's PR) to be able to compile `release` again (even if the old viewpager is no longer cached locally)

replace viewpagerindicator by another one

---

main/res/layout/cacheslist_item.xml

- enlarge info column in cache list to accommodate four digit favo counters
- adapt favo counter styling to disallow ellipsizing

enlage cache list favo entry (fix #11044)

---

main/src/cgeo/geocaching/TrackableActivity.java

Avoid adding a trackable image twice (or multiple times) on refresh of trackable details page

avoid trackable image duplication on refresh (fix #11072)

---

main/res/drawable/map_circle.xml
main/res/drawable/map_hidetrack.xml
main/res/drawable/map_status_archived.xml
main/res/drawable/map_status_disabled.xml
main/res/layout/cache_filter_list_item.xml
main/res/layout/imagelist_item.xml
main/res/layout/twotexts_button_image_item.xml
main/res/values/dimens.xml
main/res/values/styles.xml
main/src/cgeo/geocaching/filters/core/StatusGeocacheFilter.java
main/src/cgeo/geocaching/maps/MapSettingsUtils.java
main/src/cgeo/geocaching/ui/ViewUtils.java
main/src/cgeo/geocaching/utils/EmojiUtils.java

* use icons from map for "Found", "Owned" and "Has Offline Log" in FilterView and QuickSettings
* Use different icons for "On watchlist" and "Own favorite"
API 21
fix #11060
Similar to GC

use same icons in filter and quick settings

---

main/res/values/colors_light.xml

Adjusts hint color used for cache info (popup / cache details) for light mode, see https://github.com/cgeo/cgeo/pull/11071#issuecomment-873540732

fine-tune cache hint color for light mode (rel. to #11069)

---

main/res/layout/cacheslist_item.xml

Give favo column another 5dp to avoid truncating a four-digit favo count, see https://github.com/cgeo/cgeo/issues/11044#issuecomment-873489753

enlarge favo column just another bit (rel. to #11044)

---

main/res/layout/cachelist_spinneritem.xml
main/res/values/colors.xml

- reverts additional spacing between entries to original value
- uses hint color for "number of caches" line
- see https://github.com/cgeo/cgeo/issues/10982#issuecomment-873549971 for screenshots

adjust cacheslist spinner formatting (fix #10982)

---

main/res/drawable/cursor.xml
main/res/layout/template_preference_dialog.xml
main/res/values/themes.xml
main/src/cgeo/geocaching/settings/TemplateTextPreference.java

Partly reverts the logtemplate migration to `TextInputLayout` to avoid the side-effects involved.
IMHO it's not worth the effort to try to fix those side-effects by introducing so many workarounds (and so much time needed to find still missing ones), but better to wait for migration of settings to `PreferenceFragment` first.
After this PR, logtemplate preference will look like this:

partly revert logtemplate migration to TextInputLayout (fix #11024)

---

main/res/layout/cachedetail_details_page.xml
main/res/values/styles.xml

Keep the icons' colors for linked apps' icons on cache details page

fix linked apps' icon being black/white (fix #11078)

---

main/res/layout/cache_information_item.xml
main/res/values/styles.xml

- explicitly set a tint for ratingbar to override our general accent color for it
- instead of the old red color, which may be hard to differentiate from grey background for color-blind people, I've chosen blue as tint
|dark mode|light mode|
|---|---|
|![image](https://user-images.githubusercontent.com/3754370/124366314-2834ad00-dc4f-11eb-839e-9b6d0366d015.png)|![image](https://user-images.githubusercontent.com/3754370/124366289-e99ef280-dc4e-11eb-90d1-51b973fd5811.png)|

set tint for ratingbar (fix #11063)

---

main/AndroidManifest.xml

- Adds a "queries" section to `AndroidManifest.xml` to remain being able to query certain packages with the PackageManager even with target SDK 30
- I've integrated all packages declared in `strings_not_translateble.xml` package section as well as some more I found in the `apps/navi` folder
- Feel free to add additional package names necessary here, I'll update the PR then

add queries section to AndroidManifest.xml (fix #11079)

---

main/res/menu/cache_list_options.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/CacheListActivity.java
tests/src-android/cgeo/geocaching/test/EmulatorStateTest.java

remove legacy filter access, see #11086 for next steps
This PR will remove the possibility to access the legacy filter from c:geo cache list. It will NOT remove the associated filter code from c:geo. The later shall only be done after it was proven (e.g. via beta or release) that this functionality really can be removed.
For the removal of the filter legacy code, issue #11086 was created

remove legacy filter access, see #11086 for next steps

---

main/res/values/themes.xml

Fixes broken dialog's background for settings in dark theme

set dialog background for settings in dark theme (fix #11096)

---

main/res/layout/cache_information_item.xml
main/res/layout/popup.xml
main/res/values/dimens.xml

See discussion in #11070
---
Fix some strange effects (before):
A bit larger icon button size (as seen in the screenshots, this change is even nearly invisible):

improve icon button size and popup layout

---

main/res/layout/addresslist_item.xml
main/res/layout/cacheslist_item.xml
main/res/layout/cacheslist_item_select.xml
main/res/layout/downloader_item.xml
main/res/layout/imagelist_item.xml
main/res/layout/pocketquery_item.xml
main/res/layout/trackable_item.xml
main/res/layout/twotexts_button_image_item.xml
main/res/layout/twotexts_twobuttons_item.xml
main/res/layout/waypoint_item.xml
main/res/values/colors.xml

- see https://github.com/cgeo/cgeo/issues/11124#issuecomment-875827189
- unify text colors across all lists using `textSize_listsPrimary` / `textSize_listsSecondary` - we have new color variables `textColor_listsPrimary` and `textColor_listsSecondary` (which point to our default text color for primary text and to the dimmed "hint color" for secondary text)

unify list colors based on primary/secondary info level

---

main/res/values/dimens.xml

- reduce font size for lists to 18sp (primary) / 16sp (secondary) instead of 20sp/16sp
- see https://github.com/cgeo/cgeo/issues/11124#issuecomment-875076492

reduce font sizes for lists to 18sp/16sp (rel. to #11124)

---

main/src/cgeo/geocaching/WaypointPopupFragment.java

- Displays the waypoint name in map's waypoint popup
- waypoint code remove from popup's content (as it is shown in the titlebar already)

add waypoint name to popup (fix #11110)

---

main/src/cgeo/geocaching/filters/core/FavoritesGeocacheFilter.java

fix #11154: make filter by fav percentage better visible

fix #11154: make filter by fav percentage better visible

---

main/src/cgeo/geocaching/filters/core/FavoritesGeocacheFilter.java

rel to #11153: make results without finds count inconclusive
filter by percentage fav with inconclusive-inclusion turned OFF (gc.com and oc.de) 
-> gc.com caches are excluded, only correctly filtered oc.de caches show (just one in tis case):
filter by percentage fav with inconclusive-inclusion turned ON (gc.com and oc.de) 
-> all gc.com caches are included together with the correctly filtered oc.de caches:

rel to #11153: make results without finds count inconclusive

---

main/res/layout/cacheslist_item.xml

Override some colors (\*) in caches list for better contrast
(\*) distance, tb count, favo count

override some colors in caches list (fix #11145)

---

main/src/cgeo/geocaching/AbstractDialogFragment.java
main/src/cgeo/geocaching/CachePopupFragment.java
main/src/cgeo/geocaching/WaypointPopupFragment.java

Remove geocode from cache popup (but keep it in waypoint popup)

show cache geocode in wp popup only (fix #11155)

---

main/res/values/styles.xml

Dims the color for log item details for better separation of log entries.
|before|after|
|---|---|
|![image](https://user-images.githubusercontent.com/3754370/125136964-0edaa780-e10c-11eb-86c5-40a04ef6bcde.png)|![image](https://user-images.githubusercontent.com/3754370/125137410-eb642c80-e10c-11eb-854c-5d569f87abec.png)|

change cache log details color (fix #11162)

---

main/res/layout/cache_filter_activity.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/filters/gui/DistanceFilterViewHolder.java
main/src/cgeo/geocaching/filters/gui/LogEntryFilterViewHolder.java
main/src/cgeo/geocaching/ui/ViewUtils.java
main/src/cgeo/geocaching/ui/dialog/Dialogs.java
main/src/cgeo/geocaching/ui/dialog/SimpleDialog.java

Convert leftover old edittext fields to material text layouts in distance and log entry filter:

convert leftover old edittext fields to material text layouts in distance and log entry filter

---

main/src/cgeo/geocaching/filters/gui/GeocacheFilterActivity.java
main/src/cgeo/geocaching/filters/gui/IFilterViewHolder.java
main/src/cgeo/geocaching/filters/gui/StatusFilterViewHolder.java

rel to #11133: add simplified status filter to basic filter
This PR adds a simplified version of the "Status" filter to the basic filter view. The basic filter view will then look as follows:
I included all elements which are also qvailable in map quick settings.
Downside is that the basic filter is now longer than a common phone screen

rel to #11133: add simplified status filter to basic filter

---

main/src/cgeo/geocaching/CacheDetailActivity.java

hides the page to view own and friends-log if the setting is not deactivated.
fix #11167 
keeping old behaviour: friends-logs are not fetched from server, so refreshing an offline stored cache is still necessary to show friends log on activating the setting

hide friends-log page if the setting is deactivated

---

main/res/values-night/colors_dark.xml
main/res/values/colors.xml
main/res/values/colors_light.xml

unify accent color using the current dark theme accent color for both themes, which results in a higher contrast for light theme compared to current light theme accent color
see https://github.com/cgeo/cgeo/issues/11170#issuecomment-877857919

unify accent color across themes (fix #11170)

---

main/res/values/preference_keys.xml
main/src/cgeo/geocaching/maps/MapProviderFactory.java
main/src/cgeo/geocaching/maps/mapsforge/MapsforgeMapProvider.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/settings/Settings.java

- remember last set map language
- store as string to be able to use it on opening the map file directly (no translation needed)
- changing the settings type (and name) will requires users which use a map language, to re-store it once after updating

remember last set map language (fix #11089)

---

main/res/values-night/colors_dark.xml
main/res/values/colors.xml
main/res/values/colors_light.xml

Proposal for action bar coloring, screenshots see https://github.com/cgeo/cgeo/issues/11014#issuecomment-878147799
I took:
- FF202020 for dark theme
- FF505050 for white theme
@moving-bits Please check if I understood the mechanic of `values-night` correctly to split up the color. At least it looks working on my emulator.
Fix #11014

Fix #11014 - Action bar coloring

---

main/res/drawable/helper_bcg.xml

To me it would look more consistent if the status notifcation (new version, etc) would use the action bar color, because then
- on black theme it is no longer in same color as the backgroun
- on white theme its no longer a dark black
|Current master|New look in combination with PR#11192|
|---|---|
|![Screenshot_1626089174](https://user-images.githubusercontent.com/949669/125281444-82e89b80-e316-11eb-8fd3-742c1fd147d3.png)|![Screenshot_1626089650](https://user-images.githubusercontent.com/949669/125281462-89771300-e316-11eb-8dfc-9c381a069471.png)
|Current master|New look in combination with PR#11192|
|---|---|
|![Screenshot_1626089187](https://user-images.githubusercontent.com/949669/125281513-998ef280-e316-11eb-99f4-bebf0442c50f.png)|![Screenshot_1626089483](https://user-images.githubuserc …

Let status notification background use ActionBarColor

---

main/res/layout/cacheslist_item.xml

I started looking through the layout while explicitly using the largest possible system font on my Google Pixel 3a.
This was one finding I tried to tackle here: The favorite count and also the inventory icon and count were cut off as they had a absolute height. I changed this to `wrap_content`. 
Furthermore added a 1dip margin below tbcount as otherwise it floats into the border of the favorite count.
Please review as these are my first steps into layout changes. :)
|Current release|This PR|
|---|---|
|![Screenshot_20210712-153827](https://user-images.githubusercontent.com/949669/125297392-79b3fa80-e327-11eb-8783-8753eecbda0a.png)|![Screenshot_20210712-153229](https://user-images.githubusercontent.com/949669/125297412-7f114500-e327-11eb-9d09-66d5d6d4e1f8.png)
None

Avoid cut off favcount and tbcount in lists

---

main/AndroidManifest.xml

Locus app uses several package names, depending on free/pro state and on distribution channel, see `LocusUtil` that comes with the integration files.
This PR adds the package names yet missing to `AndroidManifest.xml` to be able to query that package on Android 11 systems.

add more package names for Locus app (fix #11200)

---

main/res/values/strings.xml
main/src/cgeo/geocaching/CacheDetailActivity.java

Show wp count after the tab title instead of in front of

show wp count after tab title (fix #11175)

---

main/AndroidManifest.xml

Adds MapsWithMe package names to `AndroidManifest.xml` to be able to query those packages even when running on Android 11

add MapsWithMe package name to AndroidManifest.xml (fix #11134)

---

main/res/layout/cache_filter_activity.xml

The button text is quite long, so the text might not be understandable, especially when using large font sizes:
When adding an icon in front, the meaning is much easier to understand in such cases:

add "+" icon to "add filter criteria"

---

main/src/cgeo/geocaching/utils/MapMarkerUtils.java

Use the stored offline log information to display the needs maintanance / needs archive marker on cache icons.
#11226

Needs Archive / Needs Maintenance markers should win over Note marker

---

main/res/values/strings.xml

Follow-up to #11175: capitalize changed tab tile, see https://github.com/cgeo/cgeo/commit/48e48f7c783e7ccd15688853f61b4951d43be012#r53405011

Capitalize tab tile (follow-up to #11175)

---

main/res/layout/actionbar_popup.xml
main/res/values/styles.xml

Although my branch name points out, that I want to fix the elevation as well, I did not found a solution for it yet. But for now, let's start only with the coloring...

use correct color for toolbar overflow menu (fix #11046)

---

main/res/values-night/colors_dark.xml

As discussed in https://github.com/cgeo/cgeo/pull/11220#issuecomment-879400901 we should make the actionbar color a bit lighter in dark theme to be able to differentiate between regular background and actionbar dropdown background color:
|before|after|
|---|---|
|![image](https://user-images.githubusercontent.com/3754370/125682132-8026f944-8a9b-43c8-b78f-d31111906d5f.png)|![image](https://user-images.githubusercontent.com/3754370/125682149-5279d818-dd6f-4964-95ad-c873e0bed1df.png)|

make actionbar bg color a bit lighter in dark theme

---

main/src/cgeo/geocaching/ui/CompassMiniView.java
main/src/cgeo/geocaching/utils/CompactIconModeUtils.java

- Remove the need for certain images to be bitmaps.
- Applies to "compact icon mode threshold calculation" and "mini compass view"
- related to #11139
@ztNFny 
Can you cross check whether this unblocks opening cache list and map even after full migration to svg (meaning: if this PR fixes issue #11248)?

make some calculation vectordrawable compatible (fix #11248)

---

main/res/layout/cachelist_spinner_actionbar.xml
main/res/layout/cachelist_spinner_dropdownitem.xml
main/res/layout/pq_actionbar.xml
main/res/layout/settings_toolbar.xml
main/res/values/dimens.xml
main/res/values/styles.xml
main/src/cgeo/geocaching/CacheListSpinnerAdapter.java

Furthermore, I added the "Android Touch" effect to the spinner (like we have at many other places like cache list). I'm unsure about the background color. Both would easily possible:
action bar color (currently done in this PR)|popup background color
-|-

make actionbar font size independent of device settings

---

main/src/cgeo/geocaching/CacheListActivity.java

Removes the "remove list" dialog which is not only shown after removing all caches from a list, but also when entering an empty list

remove 'remove list' dialog (fix #11081)

---

main/res/layout/authorization_credentials_activity.xml
main/res/layout/authorization_token_activity.xml
main/res/layout/logtrackable_activity.xml

This also touches the broken geocode field in `logtrackable_activity.xml` as there is kind of the same problem. It does however not solve #11257

Fix #11267 - Wrong text field hint alignment

---

main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/connector/lc/LCApi.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/CachesOverlay.java

fix #11195: handle diverse cache 0 counter issues
* Also fixes update problem on maps from cache lists (counter was not updated on viewport move)
* Also catches NPE in case there's no response in Lab Connector

fix #11195: handle diverse cache 0 counter issues

---

main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/filters/core/StoredSinceGeocacheFilter.java

fix #11196: make storedsince range work for non-offline caches
also fixes the strange  "a few minutes ago" message on cache detail popup for caches stored much longer time before.

fix #11196: make storedsince range work for non-offline caches

---

main/res/layout/cache_filter_generic_string.xml
main/res/layout/editwaypoint_activity.xml
main/res/layout/logtrackable_activity.xml
main/res/layout/search_activity.xml
main/res/values/styles.xml

Fixes styling for geocode input box in trackable logging activity
(For embedded `AutoCompleteTextView` you need to use a different styling for the surrounding `TextInputLayout`)

fix tb log geocode box formatting (fix #11257)

---

main/res/values/strings_not_translatable.xml

We had quite some leftovers in our components section. AFAIK we don't use them anymore, but can someone cross-check?
Especially, I'm not sure about these two ones:
- [RRZE Icon set](https://github.com/RRZE-PP/rrze-icon-set) ([CC-BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/))
- The [Tango! Desktop Project](http://tango.freedesktop.org/Tango_Desktop_Project) (Public Domain)
Furthermore, I removed the "from the Noun Project" which was behind every listed icon. This information was superfluous, since all elements are listed in "the Noun Project" subcategory anyway.
|before|now|
|-|-|
| ![grafik](https://user-images.githubusercontent.com/64581222/122939008-8621e480-d373-11eb-8167-f1c4b158bfac.png) |![grafik](https://user-images.githubusercontent.com/64581222/122942304-6a6c0d80-d37 …

cleanup components section

---

main/src/cgeo/geocaching/settings/Settings.java

fix #11300: make migration of global filter settings work

fix #11300: make migration of global filter settings work

---

main/src/cgeo/geocaching/connector/oc/OkapiClient.java

fix #11291: save watchlistflag correctly and not to foundflag for okapiclient

fix #11291: save watchlistflag correctly and not to foundflag for okapiclient

---

main/src/cgeo/geocaching/filters/core/StatusGeocacheFilter.java
main/src/cgeo/geocaching/maps/DefaultMap.java

fix #11292: repair broken status filter wrt active, disabled, archived
This PR also fixes that previously opening map for single caches did open map viewer with LIVE filter, but should be opened with TRANSIENT (empty) filter

fix #11292: repair broken status filter wrt active, disabled, archived

---

main/res/drawable/outline_arrow_drop_down_24.xml
main/res/layout/logcache_activity.xml
main/res/layout/logtrackable_activity.xml
main/res/values/styles.xml

- Related to a discussion in https://github.com/cgeo/cgeo/issues/11276#issuecomment-885772840
- introduce a new outlined button style "button_full_spinner" based on "button_full"
- Switched "log cache" and "log trackable" type buttons to the new style

introduce spinner button (rel. to #11276)

---

main/src/cgeo/geocaching/AboutActivity.java
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/TrackableActivity.java
main/src/cgeo/geocaching/activity/AbstractActivity.java
main/src/cgeo/geocaching/activity/TabbedViewPagerActivity.java
main/src/cgeo/geocaching/activity/TabbedViewPagerFragment.java
main/src/cgeo/geocaching/log/CacheLogsViewCreator.java
main/src/cgeo/geocaching/log/LogsViewCreator.java
main/src/cgeo/geocaching/log/TrackableLogsViewCreator.java

PR attempts to fix the fragment instantiation error described in #11204 by
- adding common fragment constructor,
- removing weakReferences to calling activity in fragments,
- supporting indirect fragment instantiation and `getArguments()` for fragments that need parameters,
- rebuilding `fragmentMap` dynamically on configuration changes
- ...
For me the following steps worked reliably to force the error:
- open cache detail page
- switch to Android system's language selection screen and select a different language
- return to c:geo => configation change triggers the error described in the referenced issue

fix fragment instantiation exception in TabbedViewPager

---

main/res/layout/filter_bar.xml

Use funnel icon instead of the old school switch.
Thanks to XML that was an easy one.
#11323

Fix #11323 - Use funnel icon for filter bar

---

main/res/drawable/ic_expand_more_white.xml
main/src/cgeo/geocaching/ui/dialog/Dialogs.java

replaces the "x" icon on fully expanded dialog by a "v" icon, as discussed in #11222

switch map quick settings close icon to arrow-down (fix #11222)

---

main/src/cgeo/geocaching/ui/ViewUtils.java

fixes dark slider-scale color in dark-mode for API < 23
use Resource to get text-color for all API-version
fix #11342

use Resource to get text-color for all API-version (fix #11342)

---

main/res/color/button_strokecolor_selector.xml
main/res/values/styles.xml

Our outline button uses a border stroke color which is barely visible, at least in dark mode. This PR increases opacity for stroke color a bit to make the outline more visible.

make button outline more visible

---

main/src/cgeo/geocaching/filters/core/DifficultyAndTerrainGeocacheFilter.java

Fixes empty searches in some cases.
use GeoCacheFilterType.create to create the child-filters for the combined.
Otherwise the type is not set correct.
fix #11360 
fix #11331
To reproduce (thanks to @bekuno, see https://github.com/cgeo/cgeo/issues/11331#issuecomment-887697022):
- Open live map
- open filter
- switch to extended
- delete all filter criteria
- save
- open the search
- search for eg. Berlin
- result is empty (except for e.g. LabCaches)

correct initialisation of DifficultyAndTerrain-Filter

---

main/src/cgeo/geocaching/connector/lc/LCApi.java
main/src/cgeo/geocaching/connector/lc/LCConnector.java

This PR addresses getting the true "found it" state for adventure lab caches. This has been discussed before, however, with the way we interacted with the API initially, the true found state could not be acquired. With the new mechanisms, this is now possible to get that state.
In addition to adding this new function, the code in LCApi has been refactored to use more meaningful and more consistent names for variables and member functions.

get ALC True Found State

---

main/res/values/strings.xml

rel to #11369: fix material.io date picker bug by adding explicit string ok resource
See also https://github.com/material-components/material-components-android/issues/1346

rel to #11369: fix material.io date picker bug by adding explicit string ok resource

---

main/res/values/strings.xml
main/src/cgeo/geocaching/filters/gui/CheckboxFilterViewHolder.java
main/src/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java

rel to #11347: add active services to origin filter automatically
This PR will:
* add origins from active services to the list of selectable "origins" in origin filter automatically
* adds an "add all items" button to checkbox filters with "add more items" button (currently "origin" and "stored lists").
This PR will **not** completely solve #11347: a possibility to select all/none items in "add more items" dialog is not included. This feature deserves its own PR since it is not filter-specific.

rel to #11347: add active services to origin filter automatically

---

main/src/cgeo/geocaching/ui/ImagesList.java

fix #11386: prevent image duplication on cache refresh
I tried to test this for unwanted side effects, and it seems to work fine.
@moving-bits I would be thankful for a code review on this

fix #11386: prevent image duplication on cache refresh

---

main/res/drawable/ic_menu_swap_vert.xml
main/res/menu/menu_ok_cancel.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/maps/routing/RouteSortActivity.java

I frequently find myself in a situation where I have planned a route at some time in the past in a certain order, but when I actually start that tour, I would like to take it in exactly the opposite order. Swapping all positions can be done using the "route sort" activity, but is quite cumbersome, especially for tours of more than 10 caches...
This PR adds a "invert oder" button to `RouteSortActivity` which reverses all items of the route.

add 'invert order' to route sort

---

main/res/values/strings.xml
main/src/cgeo/geocaching/maps/routing/RouteSortActivity.java

I frequently find myself in a situation that I've planned a tour in a certain order some time ago, let's say in order "cache 1 - cache 10", but on starting the tour decide to start with "cache 3", continue to "cache 10", and do "cache 1" and "cache 2" only then. Reordering the tour is possible using the route sort activity, but can become quite cumbersome depending on route length and new entry point.
This PR adds a long tap action to the route sort activity, which will bring up a info message, and resorts the tour on confirmation.

add 'set as start' to route sort

---

main/src/cgeo/geocaching/downloader/DownloaderUtils.java

- related to #11184
- implements solution suggested in https://stackoverflow.com/questions/66050509/downloadmanager-throw-android-os-networkonmainthreadexception (changing download folder)
(works at least in API 30 emulator)

set downloader destination to ExternalFilesDir (rel. to #11184)

---

main/src/cgeo/geocaching/activity/TabbedViewPagerFragment.java

Makes viewpager fragment update on `notifyDatasetChanged` even if it's the currently active fragment

fix added waypoint not show immediately (fix #11201)

---

main/res/layout/search_activity.xml
main/res/values/styles.xml
main/src/cgeo/geocaching/SearchActivity.java

-    Filter as first entry
-    Geocode as second entry
-    Latitude/Longitude as a two row button
-    Headline text bold, line in 3dip
-    "Geocode" instead of "geo code"
-    "Coordinate" instead of "Coordinates"
-    "Keyword" instead of "Keywords"
fixes #11340
fixes #11354

Search GUI optimization

---

main/src/cgeo/geocaching/filters/core/DifficultyAndTerrainGeocacheFilter.java

use "d" and "t" as key instead of "difficulty" and "terrain" to shorten the config-output.
fix #11362 
if we want to use a shorter version, we should introduce it before releasing to avoid migrating effort.
Or we refactor the combined filter anyway and this here is not necessary

use shorter key for D/T-config (fix #11362)

---

main/res/values/strings.xml
main/src/cgeo/geocaching/connector/gc/GCLogin.java
main/src/cgeo/geocaching/settings/SettingsActivity.java

fix #11351: make lc connector detect premium after reconnect
basic problem was that serverparameters were not reset in GCConnector after logout - so they stayed the same even after re-login. This incluided the premium state.
But this was not enough, some fiddling inside Settings for LC connector was also necessary to get this running...
@baiti : I would appreciate a review for this PR

fix #11351: make lc connector detect premium after reconnect

---

main/src/cgeo/geocaching/CacheDetailActivity.java

Is there is only the background but no further spoilers, the previous text "spoiler" was misleading... Now, this case is handled specially:

detect special case that listing background image is the only spoiler

---

main/res/layout/search_activity.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/SearchActivity.java
main/src/cgeo/geocaching/utils/ClipboardUtils.java

Automatically prefill 'search by geocode' if clipboard content can be parsed as valid geocode.
Fix #6858

Geocode search

---

main/src/cgeo/geocaching/models/Waypoint.java

returns the id of the map marker (background) for the connector the current waypoint belongs to
(similar to `Geocache.getMapMarkerId()`, but for `Waypoint`)
needed to set correct marker (shape) for waypoints, as discussed in #11424 and yesterday's meetup

add getMapMarkerId() for waypoints (rel. to #11139)

---

main/src/cgeo/geocaching/utils/DisplayUtils.java

While playing a bit with https://github.com/ztNFny/cgeo/tree/vectorIcons I got crashes when setting an individual cache icon. Yet another method needed to be updated to be compatible with non-bitmaps.
#11139

make getDrawableDimensions() compatible to non-bitmaps (rel. to #11139)

---

main/src/cgeo/geocaching/storage/DataStore.java

Hm, I wonder why the string comparison had worked before at all...
```
-    if (ConnectorFactory.getConnector(geocode).getName() == serviceName) {
+    if (ConnectorFactory.getConnector(geocode).getName().equals(serviceName)) {

offline log counter - fixes and improvements

---

checkstyle.xml

In result of discussion in #11261 and different tests this check is to remove.
fix #11261
replaces #11425

remove checkstyle check "UnnecessaryParentheses"

---

main/res/layout-land/compass_activity.xml
main/res/layout/compass_activity.xml
main/res/values/dimens.xml

The `heading primary` text size leads to the compass direction/distance info be smaller compared to the old release. Therefore use explicit size for these text fields.
#11448
Additionally fixes the cut off direction info if it has three digits:

Fix #11448 - Enlarge compass info and add space for direction

---

main/res/values/strings.xml
main/res/xml/preferences.xml

Nearly every connector has its own string "Activate" as label for settings. It's sufficient to have this string only once in our resources, therefore let's remove the duplicates.

remove duplicated 'activate' strings

---

main/src/cgeo/geocaching/apps/cache/AbstractGeneralApp.java
main/src/cgeo/geocaching/apps/cache/WhereYouGoApp.java
main/src/cgeo/geocaching/apps/navi/AbstractPointNavigationApp.java
main/src/cgeo/geocaching/apps/navi/AbstractRadarApp.java
main/src/cgeo/geocaching/apps/navi/CacheNavigationApp.java
main/src/cgeo/geocaching/apps/navi/CompassApp.java
main/src/cgeo/geocaching/apps/navi/GeopointNavigationApp.java
main/src/cgeo/geocaching/apps/navi/GoogleMapsApp.java
main/src/cgeo/geocaching/apps/navi/GoogleMapsDirectionApp.java
main/src/cgeo/geocaching/apps/navi/GoogleNavigationApp.java
main/src/cgeo/geocaching/apps/navi/InternalMap.java
main/src/cgeo/geocaching/apps/navi/LocusApp.java
main/src/cgeo/geocaching/apps/navi/MapsMeApp.java
main/src/cgeo/geocaching/apps/navi/NavigationSelectionActionProvider.java
main/src/cgeo/geocaching/apps/navi/OruxMapsApp.java
main/src/cgeo/geocaching/apps/navi/OsmAndApp.java
main/src/cgeo/geocaching/apps/navi/StreetviewApp.java
main/src/cgeo/geocaching/apps/navi/SygicNavigationApp.java
main/src/cgeo/geocaching/apps/navi/WaypointNavigationApp.java

- reverts the change from `Context` to `Activity` for navigation apps (introduced by #11157)
- but keeps the changes introduced by #11397 (which fixes #11251, a side-effect of #11157)

revert #11157 (switching navigation apps' Context to Activity)

---

main/res/values/strings.xml
main/src/cgeo/geocaching/ui/ImageListFragment.java

Shorten scaling info for log images as described in referenced issue
|unscaled|scaled|
|---|---|
|![image](https://user-images.githubusercontent.com/3754370/129481740-5de65380-16df-4e45-b738-17bbf17f435e.png)|![image](https://user-images.githubusercontent.com/3754370/129481727-8acb8937-23b2-460d-ae80-ecff65c47129.png)|

shorten scaling info (fix #11350)

---

main/res/values/strings.xml

According to native speakers the abbreviation "Tradi"/"Tradis" is not used in English, but they commonly use "Trad"/"Trads".
#11477

Fix #11477 - Use more common english abbreviation for Traditional

---

main/src/cgeo/geocaching/connector/internal/InternalConnector.java
main/src/cgeo/geocaching/storage/DataStore.java

Determines next available UDC ID dynamically instead of relying on a sequence (which may not get updated on importing a GPX with UDC)

fix getting next available id for UDC creation (fix #11480)

---

main/res/values/preference_keys.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/connector/ConnectorFactory.java
main/src/cgeo/geocaching/connector/al/ALApi.java
main/src/cgeo/geocaching/connector/al/ALConnector.java
main/src/cgeo/geocaching/connector/al/package-info.java
main/src/cgeo/geocaching/settings/Settings.java
main/src/cgeo/geocaching/settings/SettingsActivity.java
main/src/cgeo/geocaching/storage/DataStore.java

- renames LC prefix to AL prefix for all stored ALC caches (including all references)
- renames LC connector to AL (including package name / folder)
- fixes #10911
I've added a wiki page which documents the connectors c:geo supports and the geocode prefixes they use: https://github.com/cgeo/cgeo/wiki/Supported-geocaching-platforms

fix lc/al connector prefix (fix #10911)

---

main/res/layout/waypoint_item.xml

While talking to other cachers about the new release, there was a IMHO relevant point: On the waypoint tab of caches, we have all text of the waypoint in a less contrast grey. The user said, that he has problems to read notes and coords and wonders why its different to the cache details page.
Looking at the details page, we use the `secondary` color for the captions, but stick to `primary` for the real individual information. I adapted the waypoint tab to use the same principal.
Screenshots before/after attached:
| Before | After  |  
|---|---|
|  ![color improve before](https://user-images.githubusercontent.com/949669/130334913-6a83cac9-64fd-4ea7-a766-cab0c85b5261.png) |![color improve after](https://user-images.githubusercontent.com/949669/130334917-e5046027-6365-48a2-8e45-4ba6eb72a777.p …

User white color for data on waypoint tab

---

main/res/layout/coordinates_input.xml

Restore equal font size by explicitly applying text size to all coord text input elements.
| Before | After  |  
|---|---|
| ![font_coords_before_white](https://user-images.githubusercontent.com/949669/130335283-0aa073d9-a998-4ed9-8c96-f5028d348024.png)| ![font_coords_after_white](https://user-images.githubusercontent.com/949669/130335290-74407053-8bf9-4b21-a70a-0750371ff75f.png)|
#11484

Work on #11484 - Restore font size in coord input

---

main/src/cgeo/geocaching/CacheDetailActivity.java

Disable the check if short description is part of long description and therefore no removing of short description, if it is contained.
In the previous release the check did not work. Therefore remove for now the check and so both description are shown as before.
The real problem should be solved separately.
Also tests are missing.
fixes #11455

disable check if short description is part of long description

---

main/src/cgeo/geocaching/log/LoggingUI.java

Usage of another unicode character for the quick offline log menu, which solves the device specific issue #7630
#7630 
Confirmed to be working on an affected device (Samsung S20, black theme, Android 11)

Fix #7630 - Use normal check mark to avoid wrong coloring

---

main/res/values/dimens.xml
main/res/values/styles.xml

Elements where user enter texts should IMHO deserve a larger font compared to pure reading as the user needs to validate the text while entering. At the same time the slight increase brings it close to the previous size (before UI rework).
- Define new dimensions for text input fields
- Increase main text size (primary) by 2sp (16 -> 18)
- Define secondary text size as before (16) for future use 
- Apply primary text input field font size to test input style
| Before | After  |  
|---|---|
|![textinput_before](https://user-images.githubusercontent.com/949669/130351659-252fc2fc-bb25-4a48-9271-fae16352fdcd.png)| ![textinput_after](https://user-images.githubusercontent.com/949669/130351668-a3d0ef63-7db4-4a80-bf37-b64764389d8f.png)|
|![waypoint_fontsize_before](https://user-images.githubuserco …

Fix #11484 - Define explicit font size for user text input

---

main/res/layout/coordinates_calculate.xml
main/res/layout/coordinates_input.xml
main/res/values/dimens.xml

With PR #11507 I misused an existing dimension definition for waypoint calculator to pimp the coordinate input.
For the sake of documentation I refactored this using a better naming and comment, to make clear its now used for plain coordinate input as well as for the waypoint calculator.
#11484

Work on #11484 - Refactor dimension naming

---

main/res/layout/select_or_delete_item.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/filters/gui/GeocacheFilterActivity.java
main/src/cgeo/geocaching/ui/dialog/Dialogs.java

Before, "delete" and "load" were equal from an accessibility point of view (both two clicks). Furthermore, the filter config was deleted without an additional warning. I added a warning, so "delete" will still require two clicks, while users now only need one single click instead of two to select a filter config, which improves the workflow by 50% ;-) 
I implemented the dialog in a generic way, as I need the same dialog for #118

implement generic 'select item dialog' with additional delete action

---

main/res/layout/dialog_title_button_button.xml
main/res/values/styles.xml
main/src/cgeo/geocaching/ui/dialog/Dialogs.java

Dialog header color

---

main/src/cgeo/geocaching/filters/gui/GeocacheFilterActivity.java

See #11378 - take over only filters which are actively filtering

Don't add not filtering initial filters when switching to "advanced"

---

main/src/cgeo/geocaching/CgeoApplication.java

According to the links provided in #11519 the appcompat packages somehow changed the handling of system specific configurations taken over.
I found this hack which (proven in emulator) solves the problem:
https://stackoverflow.com/questions/43763993/application-text-size-not-scaling-with-system-font-size
I have no idea what this change implies, so please review it before merge whether it has any drawbacks or causes regressions elsewhere.
Please also provide feedback whether you consider it to experimental for merging on `release` and it should go to `master` instead.
#11519

Fix #11519 - Respect system font size on low Android versions

---

main/src/cgeo/geocaching/activity/TabbedViewPagerActivity.java

Another shot at #11527: Set initial page for viewpager without transition (but in contrast to the first try, let transitions for the `TabLayoutMediator` be activated).
Observed behavior with this PR is:
- Initial page gets set directly, without transition.
- Sliding from tab to tab has transitions
- as well as activating a page by tapping on a tab.
- The tab indicator is centered to the tab label.
I've targeted this PR to `master` to have some time for cross-checking for unwanted side-effects...

set initial page without transition (fix #11527)

---

main/res/values/strings.xml
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/downloader/DownloaderUtils.java
main/src/cgeo/geocaching/settings/Settings.java

- offer "later/ok" instead of "cancel/ok" for update check
- when selected "later", c:geo will prompt in three days instead of on next restart of c:geo

add delay option for updates check (fix #11548)

---

main/src/cgeo/geocaching/connector/al/ALApi.java

As described in the related issue, AL connector currently returns 500 hits on each request, which covers a much wider area than GC connector. To reduce server impact and make it more compatible with GC connector, restrict limit to 100 lab adventures.

restrict AL connector to 100 results (fix #11538)

---

main/res/values/styles.xml

For some reason setting `marquee` does not work and I personally also think that marquee text is not so nice anyway.
To avoid ellipsis characters and get most possible room for the fields I suggest to simply disable ellipsizing at this place.
It should be a sufficient workaround for the problem described in #11584 without needing to increase the field size or similar.
#11584
If this later turns out not to be enough, there are AFAICS also possibilities to define a maximum font size scaling per text view.

Fix #11584 - Allow more space for log date by disabling ellipsis

---

main/src/cgeo/geocaching/CacheDetailActivity.java

Remove disabling the add/remove favo button - there's no need to, as the button's view gets already set to either `VISIBLE` or `GONE`.

remove disabling favo button (fix #11583)

---

main/res/values/preference_keys.xml
main/src/cgeo/geocaching/settings/Settings.java
main/src/cgeo/geocaching/settings/ViewSettingsActivity.java
main/src/cgeo/geocaching/utils/BackupUtils.java

- Contents of sensitive preference keys is no longer displayer in "settings => system => view settings" to avoid displaying sensitive data accidentally. "******" are being displayed instead.
- On editing such an entry, content is still being displayed to allow editing and lookup.
- Which fields are considered "sensitive" is shared between settings view and backup utils.

hide sensitive preference data in settings view (fix #11612)

---

main/proguard-project.txt

Fix R8 missing class warnings, probaly fixed in next OkHttp release,
see https://github.com/square/okhttp/pull/6792

add proguard rules related to OkHttp

---

main/res/layout/emojiselector_item.xml

Display emojis in custom icon selector without transparency
Fixes #11673

explicitly set textColor on Emojis as the default has some alpha

---

main/src/cgeo/geocaching/connector/gc/GCParser.java

In some occasions (unclear yeat) retrieving a bookmark list returns date/time formatting without fractions of seconds. Our date/time parsing fails in such cases. This PR extends date/time parsing for bookmark lists to be able to cope with both.

add fallback for bookmark list date parsing (fix #11628)

---

main/res/values/strings.xml
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/MapUtils.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/storage/extension/OneTimeDialogs.java

Display a one time message on opening map when live mode is disabled.

show info dialog in map when live mode is disabled (fix #7741)

---

main/src/cgeo/geocaching/connector/UserAction.java
main/src/cgeo/geocaching/connector/gc/GCConnector.java
main/src/cgeo/geocaching/ui/UserClickListener.java
tests/src/cgeo/geocaching/connector/trackable/UnknownTrackableConnectorTest.java

Adds geocode to "send message" links (long tap on cache owner or user name), if available.
Leads to opened message in message center having an initial text line referencing the cache from which this links has been opened:

add geocode to 'send message' link (fix #11677)

---

main/res/layout/cache_information_item.xml

Use `sp` for width of the name column to make it expand/shrink in same relation as the text. This avoids cut off single line names in that column.
I left the value same, it might need some fine tuning if e.g. some translations are much longer. However due to the original design I guess it will fit in most occasions now.
Fixes #11709

Fix #11709 - Make name column in cache details zoomable

---

main/src/cgeo/geocaching/filters/core/StatusGeocacheFilter.java

fix #11731: status filter solved mystery: handle only mysteries as inconclusive

fix #11731: status filter solved mystery: handle only mysteries as inconclusive

---

main/res/layout/editwaypoint_activity.xml
main/res/layout/search_activity.xml
main/res/values/dimens.xml
main/res/values/strings.xml
main/res/values/strings_not_translatable.xml
main/res/values/styles.xml
main/src/cgeo/geocaching/EditWaypointActivity.java
main/src/cgeo/geocaching/SearchActivity.java

Follow up to the design optimization for the coordinate selection presented in https://github.com/cgeo/cgeo/issues/11354#issuecomment-890254665 .
- replace the 2 coordinate buttons by a single double line button for the search activity and the editwaypoint activity
- Defining a slightly larger font for the coordinates for better readability
- fix some string problems
- "geo code" to "geocode"
- "cachename" to "cache name"
- "Keywords" to "Keyword" in search headline
- some upper case/lower case optimizations
There is no change to the problem coordinates vs. coordinate.
The opinions were different in #11390.
Releated to #11354
Releated to #11390
Fixes #11391

Compact latitude/longitude button

---

main/res/layout/cache_information_item.xml

Finetuning as mentioned in #11724 a bit of finetuning: Giving 10px more room will make it fit in german and some other languages (given the current translations).
There are still languages (e.g. greek) where we can never make it fit....but that's probably up to translators then to find a shorter term.
#11709

Related #11709 - Give 10sp more room to avoid ellipsize

---

main/src/cgeo/geocaching/CacheDetailActivity.java

On loading description texts for a cache, check if short description is contained in long description, and hide short description if so.
Fixes the non functional `potentiallyHideShortDescription` method.

prevent doubling short description (fix #11464)

---

main/res/layout-land/coordinates_input_dialog.xml
main/res/layout/coordinates_input.xml
main/res/layout/coordinates_input_dialog.xml
main/res/layout/coordinates_input_single.xml
main/res/values/styles.xml
main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java

Refactored coordinates input dialog
- to use `LinearLayout` with `layout_weight` instead of `TableLayout`
- and extracted a couple of styles to `styles.xml`
Works for both portrait and landscape mode.

refactor coordinates input dialog (fix #11596)

---

main/src/cgeo/geocaching/CompassActivity.java
main/src/cgeo/geocaching/address/AddressListActivity.java
main/src/cgeo/geocaching/apps/navi/InternalMap.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/DefaultMap.java
main/src/cgeo/geocaching/maps/MapOptions.java

fix #11424
on the way, I've touched some methods where the name was misleading, or some parameters were always `null`
Tested on OSM and GMap

[waypoint marker] use correct connector shape in singlePointMode

---

main/res/drawable/white_bcg.xml
main/res/drawable/zoomin.xml
main/res/drawable/zoomin_fg.xml
main/res/drawable/zoomout.xml
main/res/drawable/zoomout_fg.xml
main/res/values/colors.xml
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

Adapt styling of OSM zoom controls to look more similar to GM zoom controls:
- use vertical arrangement (zoom in on top, zoom out below)
- use +/- symbols as zoom controls
- use semi-transparent white box as background
- disable auto-hide of zoom controls

adapt styling of OSM zoom controls (fix #11696)

---

main/src/cgeo/geocaching/InstallWizardActivity.java
main/src/cgeo/geocaching/storage/ContentStorage.java
main/src/cgeo/geocaching/storage/PersistableFolder.java

rel to #11227: dont initialize default folders at startup - it takes very long time
Although this is a bug in production, I would prefer to put this fix to master. The reason is that it changes core parts of `ContentStorage`, and I want to use the beta phase to check unwanted side effects before pushing this out to all end users.

rel to #11227: dont initialize default folders at startup - it takes very long time

---

main/res/layout/variables_list_item.xml

Today, I wanted to use the new Variables feature for the first time. It worked pretty well (thanks @eddiemuc!), but I was strongly disappointed, that there was no possibility to copy the result. It was a mystery with multiple lines of `rot13` text encryption, so it was not really possible to use the brain as clipboard ;-)
This PR will allow text selection.

[Variables] allow selection of formula result value

---

main/res/layout/filter_sort_bar.xml
main/src/cgeo/geocaching/CacheListActivity.java

fix #11991: display sort order in upper right corner

fix #11991: display sort order in upper right corner

---

build.gradle

As we are currently not able to switch to gradle 7 lets install this small gradle plugin fix
(including aapt2-proto prerequisite).

gradle plugin 4.2.2 Upgrade

---

main/res/layout/filter_sort_bar.xml

extend clickable area of filters view (fix #12052)

---

build.gradle

see https://github.com/bjoernQ/unmock-plugin#versions
- renaming plugin (classpath), switch to mavenCentral
- Gradle 7 compatibility fixes

UnMockPlugin update

---

main/src/cgeo/geocaching/command/AbstractCommand.java

Use bottom navigation layout element as anchor view to position the snackbar above it.
If bottom navigation layout element is not found (null) placement will be as today.

position snackbar above bottom navigation (fix #12014)

---

main/res/layout-h390dp-land/activity_bottom_navigation.xml
main/res/layout-land/activity_bottom_navigation.xml
main/res/layout/activity_bottom_navigation.xml
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/ui/RelativeLayoutWithInterceptTouchEventPossibility.java

When the search dropdown is in expand mode without keyboard being active, the search view gets closed when clicking in the textarea. Instead, the keyboard should get opened again...
To get this working, I had to create a small extension of `RealtiveLayout`, which supports setting a `onInterceptTouchEventListener` on demand.

fix some minor search view bugs

---

main/src/cgeo/geocaching/MainActivity.java

The start page should never be opened as sub-activity. If c:geo had been open already, start from the last used activity instead. 
The same check was introduced long ago, but seem to no longer work on some modern launchers.

(hopefully) fix wrong activity stack (fix #12010)

---

main/src/cgeo/geocaching/connector/gc/GCWebAPI.java
main/src/cgeo/geocaching/location/Units.java

fix #11631 - Use rounded distance for premium cache BM heuristic
These values have always been just a blind guess. Therefore, it makes no sense to display extremely accurate distances...
before|now
-|-
(does also work for imperial units)
Some more examples how values will be rounded:
```
E/cgeo: [network--10] before 0.0	next 0.114486255	|  result: 0.1
E/cgeo: [network--10] before 2.2910788	next 2.98085		|  result: 2.6
E/cgeo: [network--10] before 5.601692	next 6.563045		|  result: 6.1
E/cgeo: [network--10] before 7.8604755	next 8.457116		|  result: 8.2
E/cgeo: [network--10] before 9.295073	next 9.41279		|  result: 9.4
E/cgeo: [network--10] before 9.41279	next 9.525498		|  result: 9.5
E/cgeo: [network--10] before 11.103125	next 11.355427		|  result: 11.2
E/cgeo: [network--10] before …
```

Use rounded distance for premium cache BM heuristic

---

main/src/cgeo/geocaching/ui/AvatarUtils.java

Avatar URL can be blank instead of null. Handle this case correctly...
before|now
-|-

Enhance UI for users without an avatar image

---

main/src/cgeo/geocaching/downloader/DownloadSelectorActivity.java

Avoids a `CursorIndexOutOfBoundsException` in map downloader, which has app. 180 occurrences for versions `2021.10.08`, `2021.09.27` and current RC over the last 30 days.
(Reason for this exception is that the requested columns sometimes were not available in the query, thus `cursor.getInt()` triggered that exception.)

avoid CursorIndexOutOfBoundsException in map downloader

---

main/res/values/strings.xml
main/src/cgeo/geocaching/utils/MapMarkerUtils.java

rel. to #10924
This will look like this:
@ztNFny are you ok with this implementation?

Display caches with corrected coords with enlarged "blue flag" marker

---

main/src/cgeo/geocaching/log/LogTemplateProvider.java
main/src/cgeo/geocaching/settings/TemplateTextPreference.java

Log "insert" menu contains an item "Log text". That placeholder was added in #3368 and should be available for Twitter only. Inserting the log text into the log text doesn't make any sense.
fixes #12066

remove "Log Text" from log insert menu

---

main/src/cgeo/geocaching/filters/gui/BaseFilterViewHolder.java
main/src/cgeo/geocaching/filters/gui/GeocacheFilterActivity.java
main/src/cgeo/geocaching/filters/gui/IFilterViewHolder.java
main/src/cgeo/geocaching/filters/gui/StatusFilterViewHolder.java

fix #12073 again: stabilize filter switch basic/advanced logic
The first fix to #12073 was itself wonky and will produce itself other wonkynesses. A larger change was necessary to fix this in a proper way. This PR will do that.

fix #12073 again: stabilize filter switch basic/advanced logic

---

main/src/cgeo/geocaching/filters/core/LogsCountGeocacheFilter.java
main/src/cgeo/geocaching/filters/gui/LogsCountFilterViewHolder.java

fix #12086: logscount filter: store all correctly, dont return caches without logs count in db

fix #12086: logscount filter: store all correctly, dont return caches without logs count in db

---

main/src/cgeo/geocaching/files/GPXIndividualRouteParser.java
main/src/cgeo/geocaching/files/GPXRouteParser.java
main/src/cgeo/geocaching/files/GPXTrackParser.java
main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/AbstractRouteLayer.java
main/src/cgeo/geocaching/models/IndividualRoute.java
main/src/cgeo/geocaching/models/Route.java
main/src/cgeo/geocaching/models/RouteSegment.java

If a GPX file contains multiple tracks, display them separately instead of connecting them into one track:
|before|now|
|---|---|
|![image](https://user-images.githubusercontent.com/3754370/141651016-8a8f0187-9b11-446d-a66d-19825b4df5b1.png)|![image](https://user-images.githubusercontent.com/3754370/141650989-44e182d3-e014-4f06-8ea2-ec58950dbbaf.png)|
(for testing see the GPX file provided in https://github.com/cgeo/cgeo/issues/10432#issuecomment-841788817)

Display of multiple separate tracks in single GPX file (fix #10432)

---

main/src/cgeo/geocaching/files/GPXTrackOrRouteImporter.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/utils/TrackUtils.java

Automatically resets "hide track" setting to `false` on loading a new track.
PR is targeted to `master` currently, but based on `release`, so it can still be re-targeted and merged to `release` if requested.

auto unhide track on loading new track (fix #12111)

---

main/src/cgeo/geocaching/utils/EmojiUtils.java

Provide numbers 0-9 as user-defined cache symbols, e. g. for numbering stages of a lab adventure or a multi cache.
As the original numbers have a rather small display size, I increase font size for those symbols by 40%.

provide numbers as cache symbols (fix #12099)

---

gradle/wrapper/gradle-wrapper.properties

Update gradle from 6.8.3 to 7.9.1.
Using it on the release branch to have bugs fixed there.
This is a backport release from gradle 7.x to 6.x.
No problems so far found in tests and from the ReleaseNotes.
For ReleaseNotes see
- https://docs.gradle.org/6.9/release-notes.html
- https://docs.gradle.org/6.9.1/release-notes.html

gradle 6.9.1

---

main/src/cgeo/geocaching/downloader/MapDownloaderFreizeitkarte.java

Related to #11817: Use "latest" subfolder instead of "yymm" subfolder - helps avoiding folder naming errors on server side like that one that happened recently / always downloads the most recent version

use 'latest' subfolder for FZK downloads (rel. to #11817)

---

main/res/drawable/white_bcg.xml
main/res/layout/map_settings_button.xml
main/res/values/styles.xml

Use ImageButton instead of Button to remove outlines on map settings buttons
fixes #12041 
fixes #11907

style quick settings buttons like zoom buttons

---

main/src/cgeo/geocaching/downloader/DownloaderUtils.java

As discussed in our last dev call: Put the call to `DownloadManager.enqueue` into background when called by the automatic update check, trying to avoid the `NetworkOnMainThreadException` which occur on some Samsung devices running Android 10.
Attempts to fix the error described #11184, but let's keep the issue open to see if the error is really resolved (as we cannot reproduce it here).
The change should be non-problematic, but I've targeted it to `master` anyway, to not force it into our upcoming release without having seen it in a couple of nightlies before.

put DownloadManager.enqueue in background in update check

---

main/res/drawable/ic_menu_select_next.xml
main/res/menu/cache_list_options.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/ui/CacheListAdapter.java

As discussed in #12077: Add an option to select the next 20 caches in the cache list.
Selecting this menu entry will check the first 20 unchecked caches, honoring the current sort order. Selecting this menu entry multiple times will select 40, 60, 80 etc. caches (20 more on each call).

add 'selext next 20 caches' to cache list (rel. to #12077)

---

main/res/layout/downloader_confirmation.xml

Make the `AlertDialog` window with routing/map update info scrollable
~@Lineflyer 
Can you cross-check (as time permits) - cannot test here, only have 20 or so tiles downloaded :-)~
Just did a retest with font size set to maximum - view is now scrollable as expected.

make map/tile update info scrollable (fix #12165)

---

main/res/values/preference_keys.xml
main/res/values/strings.xml
main/res/xml/preferences.xml
main/src/cgeo/geocaching/downloader/DownloaderUtils.java
main/src/cgeo/geocaching/settings/Settings.java

As described in https://github.com/cgeo/cgeo/issues/12153#issuecomment-978190309:
- change settings => navigation => update interval to "0 = no update check at all" ("automatic download" does not have to be active to trigger query for update, but update check will only cover tiles downloaded by the automatic download, as only then the required metadata is created)
- change settings => map = >update interval in the same way
- remove "automatic download" checkbox on map page (as its use-case is covered by aforementioned's setting being 0 or non-zero)
Additionally migrate related settings:
- if `mapAutoDownloads` have been disabled: set `mapAutoDownloadInterval` to 0
- remove `mapAutoDownloads` key
- if `routingTileAutoDownloads` have been disabled: set `routingTileAutoDownloadsInterval` to …

avoid repeated update checks for interval=0 (fix #12153)

---

main/src/cgeo/geocaching/location/GeopointFormatter.java
main/src/cgeo/geocaching/models/Geocache.java
main/src/cgeo/geocaching/utils/CheckerUtils.java

Pass the current cache coordinates to geocheckers for checkers supporting that.
Entering coordinates into the checker is quite annyoing on the small phone screen - but something done often to verify that the final coords are still correct or to get the spoiler image.
geocheck.org/geotjek.dk and geochecker.com support a url parameter to pass a coordinate to be checked.
fixes #6782

pass current cache coordinates to geochecker

---

main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/SearchResult.java
main/src/cgeo/geocaching/connector/al/ALConnector.java
main/src/cgeo/geocaching/connector/gc/GCConnector.java
main/src/cgeo/geocaching/connector/gc/GCMap.java
main/src/cgeo/geocaching/connector/gc/GCParser.java
main/src/cgeo/geocaching/connector/gc/GCWebAPI.java
main/src/cgeo/geocaching/connector/oc/OCApiLiveConnector.java
main/src/cgeo/geocaching/connector/oc/OkapiClient.java
main/src/cgeo/geocaching/enumerations/CacheListType.java
main/src/cgeo/geocaching/sorting/InverseComparator.java
main/src/cgeo/geocaching/ui/CacheListAdapter.java

fix #11941: allow loading more caches for new gc search and oc
This PR extends the "load more caches" functionality to the new GC search as well as OC search. Initially 200 caches are loaded per (active) connector, each "load more" will try to load 50 more caches from each connector

fix #11941: allow loading more caches for new gc search and oc

---

main/src/cgeo/geocaching/utils/calc/Calculator.java
main/src/cgeo/geocaching/utils/calc/CalculatorUtils.java
tests/src/cgeo/geocaching/utils/calc/CalculatorMapTest.java
tests/src/cgeo/geocaching/utils/calc/CalculatorTest.java
tests/src/cgeo/geocaching/utils/calc/CalculatorUtilsTest.java

rel to #12146: introduce overflow character _ into calculator
In order to replace the special "blank" symbol (used as an overflow/spillover placeholder) needed for button-bound calculated variable, we need to introduce same capacity to the new calculator engine. character _ is used for that

rel to #12146: introduce overflow character _ into calculator

---

main/build.gradle
main/res/layout/cache_information_item.xml
main/src/cgeo/geocaching/ui/CacheDetailsCreator.java

Enable content of right column in cache popup to wrap
|regular font size|largest font size|
|---|---|
|![image](https://user-images.githubusercontent.com/3754370/143784457-56954a5e-d00d-4781-a3d9-29a8d0b69bd6.png)|![image](https://user-images.githubusercontent.com/3754370/143784450-b0c6b8a3-f609-421d-80e3-2ec36729c502.png)|
Tested in emulator with a Pixel 2 (at 480 x 800 px resolution)

enable line breaks in cache popup stars (fix #12164)

---

main/res/values/strings.xml
main/src/cgeo/geocaching/AttributesGridAdapter.java
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/enumerations/CacheAttribute.java
main/src/cgeo/geocaching/filters/gui/AttributesFilterViewHolder.java

Sort attributes in cache details page and in attribute filter according to the attribute categories:
|cache details: icons|cache details: texts|attribute filter|
|---|---|---|
|![image](https://user-images.githubusercontent.com/3754370/143786146-31047178-b2f7-41fb-bf56-9075237c452e.png)|![image](https://user-images.githubusercontent.com/3754370/143786150-090082b5-622d-48c8-b515-72fa6ec9b0a7.png)|![image](https://user-images.githubusercontent.com/3754370/143786155-f2de697b-ef29-4b27-a5b1-de52f85ab60e.png)|
(also fixes one category assignment)

attributes sorting in cache details and attribute filter (fix #12189)

---

main/res/drawable/ic_menu_paste_search.xml
main/res/menu/main_activity_options.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/SearchActivity.java
main/src/cgeo/geocaching/connector/AbstractConnector.java
main/src/cgeo/geocaching/connector/ConnectorFactory.java
main/src/cgeo/geocaching/connector/IConnector.java
main/src/cgeo/geocaching/connector/gc/GCConnector.java
main/src/cgeo/geocaching/connector/gc/GCConstants.java
main/src/cgeo/geocaching/connector/oc/OCConnector.java
tests/src-android/cgeo/geocaching/CgeoApplicationTest.java
tests/src-android/cgeo/geocaching/connector/gc/GCConnectorTest.java
tests/src-android/cgeo/geocaching/connector/oc/OCConnectorTest.java

Improves loading a geocode from clipboard by "recognizing" geocodes in text.
There's 3 parts to this commit:
1. fixes to the pattern(s) used for recognizing a GC-code in URLs
2. extension of the existing functionality in "Search" activity to auto-fill the geocode field with a geocode from clipboard. This now works not just for plain geocodes but also geocode-urls (e.g. https://coord.info/GC123) and geocodes contained in text ("Check out GC123"), see https://github.com/cgeo/cgeo/blob/3e311ec09ffc46158781fa5572733639495b1d3f/tests/src-android/cgeo/geocaching/connector/gc/GCConnectorTest.java#L115 for some more text examples
3. add a "paste" button to the quicksearch field in main activity. The button only shows up if clipboard contains a geocode (either pure, url or in text) and directly …

quick-load geocode from clipboard text

---

main/res/layout/template_preference_dialog.xml
main/src/cgeo/geocaching/settings/TemplateTextPreference.java
main/src/cgeo/geocaching/settings/fragments/PreferenceLoggingFragment.java
main/src/cgeo/geocaching/settings/fragments/PreferenceMapFragment.java
main/src/cgeo/geocaching/settings/fragments/PreferenceOfflinedataFragment.java

- show current signature as summary (fix #12118)
- fix signature edit dialog (fix #12243)
- apply material design to signature edit dialog
- fix template insert dialog
|Edit dialog|Templates inserted|Summary updated|
|---|---|---|
|![image](https://user-images.githubusercontent.com/3754370/144741641-9a914fb9-6ab1-4716-94ec-418f8516f422.png)|![image](https://user-images.githubusercontent.com/3754370/144741673-4af503f1-3c07-4157-9316-390b56eda508.png)|![image](https://user-images.githubusercontent.com/3754370/144741686-481d34d1-a72b-482d-960b-4a10bde496fd.png)

reenable signature editing

---

main/src/cgeo/geocaching/AttributesGridAdapter.java
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/ui/CacheListAdapter.java

Seems that enabling a tooltip overrides short click set with `setOnItemClickListener`, therefore this PR set short clicks directly

reenable attribute view toggling in cache details (fix #12248)

---

main/src/cgeo/geocaching/settings/fragments/PreferenceMapFragment.java
main/src/cgeo/geocaching/settings/fragments/PreferenceNavigationFragment.java
main/src/cgeo/geocaching/settings/fragments/PreferenceOfflinedataFragment.java
main/src/cgeo/geocaching/settings/fragments/PreferenceSystemFragment.java

Setting "base" folder was still missing in settings - this PR reenables it.

reenable setting base folder (fix #12123)

---

main/AndroidManifest.xml

For testing whether the "open in browser not working" is related to not having listed those apps in our manifest, this PR adds
- Firefox browser
- Samsung browser
- Via browser
to the `<query>` section of our manifest to make those packages visible to c:geo
@Lineflyer 
Can you cross-check whether this works in your test scenario or in those of the two users on support?

add generic browser query to manifest (fix #12209)

---

main/res/layout/preference_seekbar.xml
main/res/values/attrs.xml
main/res/xml/preferences_backup.xml
main/res/xml/preferences_map.xml
main/res/xml/preferences_navigation.xml
main/res/xml/preferences_offlinedata.xml
main/src/cgeo/geocaching/settings/BackupSeekbarPreference.java
main/src/cgeo/geocaching/settings/ProximityPreference.java
main/src/cgeo/geocaching/settings/SeekbarPreference.java
main/src/cgeo/geocaching/settings/fragments/PreferenceBackupFragment.java
main/src/cgeo/geocaching/utils/BackupUtils.java

Restoring some old settings' code, upgrading it to AndroidX, to reenable our former `SeekbarPreference` capabilities:
- enable setting value by tapping on the value field right beside the slider
- enable logarithmic scaling (where applicable)
- enable value conversion (where applicable)
- enable displaying texts for min/max value in `BackupSeekbarPreference`

Restore old SeekbarPreference capabilities

---

main/build.gradle

from changelog:
- Fix: Don't fail HTTP/2 responses if they complete before a RST_STREAM is sent.
This should go to the release branch to have this bug fix in the next release
supersedes #12158

Bump okhttp from 4.9.2 to 4.9.3 on release branch

---

main/res/layout/template_preference_dialog.xml
main/res/values/preference_keys.xml
main/res/values/strings.xml
main/res/xml/preferences_logging.xml
main/src/cgeo/geocaching/log/AbstractLoggingActivity.java
main/src/cgeo/geocaching/log/LogTemplateProvider.java
main/src/cgeo/geocaching/settings/Settings.java
main/src/cgeo/geocaching/settings/TemplateTextPreference.java
main/src/cgeo/geocaching/settings/fragments/PreferenceLoggingFragment.java

I have added 5 additional templates that work in the same way "Signature" does in defining them in preferences.
They do show up in the "insert" menu right below signature - but only if they are non-empty - from where you can insert them manually.
Showing the title is currently done in an ugly way, using one preference to store template name and text with a divider - I couldn't find any good way to have two associated preference keys (for title and text). If someone has an idea on that please feel free to pick up the code in PR (#12071). Due to this I've marked the PR as Draft for now.
(Also the number of templates is fixed now as it's using preferences, implementing title and text as some form of objects would probably allow making that dynamic)

Log templates

---

main/res/values/strings.xml
main/src/cgeo/geocaching/maps/mapsforge/v6/RenderThemeSettingsFragment.java

For setting map theme options, the "Elevate" and "Elements" themes have grouped the options and indicate that group by a prepended letter. This PR adds a short explanation to the map theme options menu, if either "Elevate" or "Elements" theme is selected:

add category info for elevate theme options

---

main/res/layout/cache_filter_activity.xml
main/res/layout/cachedetail_variables_page.xml
main/src/cgeo/geocaching/filters/gui/GeocacheFilterActivity.java

fix #12242: name viewroots uniquely to allow correct state reconstruction on resume

fix #12242: name viewroots uniquely to allow correct state reconstruction on resume

---

main/src/cgeo/geocaching/storage/ContentStorageActivityHelper.java

fix #11846: skip asking user for copymove if zero files in source

fix #11846: skip asking user for copymove if zero files in source

---

Jenkinsfile

This PR updates the `Jenkinsfile` in our repository (at this moment for `master` only).
It was originally created back in 2017 to try pipeline building on Jenkins.
While it technically does exactly the same as our current CI jobs do, it could have some advantages:
* While using pipelines the build configuration is stored in our repository, which allows proper versioning and we could also easily apply different build configurations for different branches/repositories in case of need
* The build history has a quite good visualization like this:
#6587
The `Jenkinsfile` in this PR is a combination of the historic file, changes we had meanwhile in our build workflow and some cosmetic. Part of the stages used need more work and finetuning for sure. I would still like to have this on `master` to …

Update Jenkinsfile for new experimental pipeline

---

main/res/values/preference_keys.xml
main/res/values/strings.xml
main/res/xml/preferences_cachedetails.xml
main/src/cgeo/geocaching/models/PersonalNote.java
main/src/cgeo/geocaching/settings/Settings.java

see referenced issue #10193.
In a nutshell: Provide a preference setting to tell cgeo not to merge personal cache notes data coming down from the provider with what cgeo already might have stored locally. The datamodel behind this is that there is only one authoritative source for that data and that is in the provider's database. On refresh, take what comes down verbatim. If local changes are made, make sure to push them to the provider manually. The functionality to push, is already there, even for lists.

don't merge PCN (resolves #10193)

---

main/src/cgeo/geocaching/utils/MapMarkerUtils.java

add some more padding around the standalone waypoint icons to avoid cutting them off
follow-up on #12216

increase padding on standalone waypoint icon (fixes #12288)

---

main/src/cgeo/geocaching/ui/ViewUtils.java

Use `TooltipCompat` to enable tooltips on systems below API 26 ("O")

enable tooltips for API < 26

---

main/src/cgeo/geocaching/storage/LocalStorage.java

rel to #12340: emergency fix, skip migration
This PR is an emergency fix for #12340: it simply SKIPS the migration to local storage version 3 (this means that there will be leftover svg files on the user's device from mapsforge cache. They won't do any harm except they take away device space)

DO NOT MERGE, rel to #12340: emergency fix, skip migration

---

main/src/cgeo/geocaching/storage/LocalStorage.java

fix #12340: skip deletion of old svg cache files during migration

fix #12340: skip deletion of old svg cache files during migration

---

crowdin.yml

Append keyword to commit messages to make CI pull request builder ignore those commits.
Needs to be checked in practice whether the PR builder still checks the PR once or how to achieve this (dont run a build for each commit but only once after all commits have been added to the PR).
#12391

Fix #12391 - Let CI ignore crowdin commits

---

main/src/cgeo/geocaching/downloader/DownloadNotificationReceiver.java
main/src/cgeo/geocaching/storage/DataStore.java

While researching and testing the issues in PR #12307, I found some `range` type lints errors in the current master.
These errors are addressed and fixed here.
Details:
getColumnIndex can result to -1. This is now checked or replaced by getColumnIndexOrThrow with a try/catch block.

fix lint errors of type `Range`

---

main/src/cgeo/geocaching/brouter/BRouterConstants.java
main/src/cgeo/geocaching/brouter/InternalRoutingService.java
main/src/cgeo/geocaching/maps/routing/Routing.java

Use a different parameter name for routing service profile as the one used so far seems to be in use now, starting with BRouter 1.63, effectively preventing c:geo to use the external routing service.

Use different parameter name for routing service profile (fix #12410)

---

main/res/raw/changelog_base.md
main/src/cgeo/geocaching/ui/CacheListAdapter.java

Increase the limit for detection whether a cache list contains a series of caches (`isSeriesList`) from 50 to 500 caches.
#12431

Fix #12431 - Increase detection of cache series to a max of 500 caches

---

cgeo-contacts/AndroidManifest.xml
main/AndroidManifest.xml

fixes #12354
Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined.
We already set `android:exported="true"` if this is necessary.
Add this value also for the remaining intents.
(edited)

set android:exported="true" if this is required

---

main/res/menu/map_activity.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/downloader/BRouterTileDownloader.java
main/src/cgeo/geocaching/downloader/DownloaderUtils.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/MapUtils.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

- adds a menu entry "Check for missing routing data" to the map
- if selected, c:geo checks whether routing data is available for the whole viewport currently visible, and offers to download missing files
- checking is done in background
- if you select to download missing files, this triggers our regular integrated downloader

check for missing routing data for current viewport (fix #12172)

---

main/src/cgeo/geocaching/ui/CacheListAdapter.java

Replaces the cache list attribute overview `AlertDialog` by a `BottomSheetDialog`:

replace cachelist attribute overview AlertDialog by BottomSheetDialog

---

main/src/cgeo/geocaching/utils/formulas/FormulaUtils.java
tests/src/cgeo/geocaching/utils/formulas/FormulaUtilsTest.java

The PR fixes some issues with the formula scanner:
- The Regex doesn't accept trailing `.` anymore
- Trailing whitespace is removed from the resulting formulas

Fix #12449: Improve formula scan

---

main/src/cgeo/geocaching/ui/FastScrollListener.java

- Reduce the time until fast scroll is disabled from 1000ms to 500ms to decrease the probability to interfere with nearby touch targets (see #9992).
- Could also help to improve #11497
#9992 
#11497
The alternative would be to disable the fastscroll for the waypoint tab, but this would mean there is no longer any possibility to quickly scroll through a long list (e.g. caches with hundreds of waypoints). Therefore I think this workaround is the way to go for now.

Fix #9992 - Reduce fast scroll bar active time

---

main/src/cgeo/geocaching/settings/Settings.java
main/src/cgeo/geocaching/settings/fragments/PreferenceLoggingFragment.java

Latest CI runs are showing this checkstyle report:
~~~
> Task :main:checkstyle
[ant:checkstyle] [INFO] /home/jenkins/slave/workspace/cgeo-CI_PR-build/main/src/cgeo/geocaching/settings/Settings.java:63:1: Wrong order for 'java.io.File' import. [ImportOrder]
[ant:checkstyle] [INFO] /home/jenkins/slave/workspace/cgeo-CI_PR-build/main/src/cgeo/geocaching/settings/fragments/PreferenceLoggingFragment.java:5:1: Wrong order for 'cgeo.geocaching.R' import. [ImportOrder]
Checkstyle rule violations were found. See the report at: file:///home/jenkins/slave/workspace/cgeo-CI_PR-build/main/build/reports/checkstyle/checkstyle.html
Checkstyle files with violations: 2
Checkstyle violations by severity: [info:2]
~~~
Fixed now.

Fix checkstyle problems

---

main/AndroidManifest.xml
main/res/menu/settings_activity_options.xml
main/res/values/preference_keys.xml
main/res/xml/preferences_cachedetails.xml
main/res/xml/preferences_logging.xml
main/res/xml/preferences_map.xml
main/res/xml/preferences_navigation.xml
main/res/xml/preferences_offlinedata.xml
main/res/xml/preferences_system.xml
main/res/xml/searchable_settings.xml
main/src/cgeo/geocaching/Intents.java
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/search/BaseSearchSuggestionCursor.java
main/src/cgeo/geocaching/search/BaseSuggestionsAdapter.java
main/src/cgeo/geocaching/search/GeocacheSearchSuggestionCursor.java
main/src/cgeo/geocaching/search/GeocacheSuggestionsAdapter.java
main/src/cgeo/geocaching/search/SearchUtils.java
main/src/cgeo/geocaching/settings/SettingsActivity.java
main/src/cgeo/geocaching/settings/fragments/BasePreferenceFragment.java
main/src/cgeo/geocaching/settings/fragments/PreferenceAppearanceFragment.java
main/src/cgeo/geocaching/settings/fragments/PreferenceBackupFragment.java
main/src/cgeo/geocaching/settings/fragments/PreferenceCachedetailsFragment.java
main/src/cgeo/geocaching/settings/fragments/PreferenceLoggingFragment.java
main/src/cgeo/geocaching/settings/fragments/PreferenceMapFragment.java
main/src/cgeo/geocaching/settings/fragments/PreferenceNavigationFragment.java
main/src/cgeo/geocaching/settings/fragments/PreferenceOfflinedataFragment.java
main/src/cgeo/geocaching/settings/fragments/PreferenceServicesFragment.java
main/src/cgeo/geocaching/settings/fragments/PreferenceSystemFragment.java
main/src/cgeo/geocaching/settings/fragments/PreferencesFragment.java
main/src/cgeo/geocaching/storage/DataStore.java

(updated description)
- enables search with preferences, using a suggestion provider
- at least three characters are required to trigger the search suggestion provider
- automatically scrolls to the selected preference
- highlights the title of that preference
- pressing enter in searchbar selects and opens the first found entry
(for screenshots see below: https://github.com/cgeo/cgeo/pull/12441#issuecomment-1003582062)
~Setting WIP label for now, as I'm not sure about the colors. I was looking for a color which highlights a text in both dark and light mode, and which is neither red nor green nor our accent color. A sort of turquoise is the best I've come up so far, but I'm open for other solutions.~
~Alternatively to a color, the found preference could be highlighted by a short animation …

enable search in preference screen (rel. to #12335)

---

main/src/cgeo/geocaching/filters/core/LogsCountGeocacheFilter.java

fix #12463: filter gc found=0 caches correctly in logscount filter

fix #12463: filter gc found=0 caches correctly in logscount filter

---

main/res/values/preference_keys.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/enumerations/CacheAttribute.java
main/src/cgeo/geocaching/filters/gui/AttributesFilterViewHolder.java
main/src/cgeo/geocaching/settings/Settings.java
main/src/cgeo/geocaching/ui/CacheListAdapter.java

Allow filtering attributes by the connector that uses them in filters "Cache Attributes" dialog.
GC uses 70 attributes, OC (okapi) 89 for a total of 124. For a GC-only cacher that means there are currently 54 unused icons shown in the list.
This feature allows the user to have only those attributes relevant for him visible, controllable with buttons in the filter dialog itself.
The default setting is based on enabled connectors (I'm open to removing this depending on feedback - this is where it started but with a GUI element I'm not too fixed on it)
This also fixes #12425 and #12433 along with some layout changes to "Attributes Overview" and attributes text view in cache details
GC only:
OC only:
GC + OC:
Attributes text view in cache:
Attribute overview:

in attributes filter allow selecting from which connectors attributes are shown 

---

main/src/cgeo/geocaching/maps/mapsforge/v6/RenderThemeSettingsFragment.java
main/src/cgeo/geocaching/settings/Settings.java

Persists the selected new style value before updating the view

fix map theme style options not updated on change (fix #12457)

---

main/src/cgeo/geocaching/VariablesViewPageFragment.java
main/src/cgeo/geocaching/utils/formulas/FormulaUtils.java
tests/src/cgeo/geocaching/utils/formulas/FormulaUtilsTest.java

The PR fixes two issues with the formula scanner:
- HTML tags are stripped before scanning for formulas
- The scanner now accepts not only spaces but all horizontal whitespace characters

Fix formula scanning for GC93DAV

---

main/res/values/preference_keys.xml
main/res/xml/preferences_appearence.xml
main/res/xml/preferences_backup.xml
main/res/xml/preferences_logging.xml
main/res/xml/preferences_offlinedata.xml
main/res/xml/preferences_services_geocaching_com_adventure_lab.xml
main/res/xml/preferences_system.xml
main/src/cgeo/geocaching/settings/OCPreferenceKeys.java
main/src/cgeo/geocaching/settings/Settings.java
main/src/cgeo/geocaching/settings/SettingsActivity.java
main/src/cgeo/geocaching/settings/fragments/PreferenceBackupFragment.java
main/src/cgeo/geocaching/settings/fragments/PreferenceLoggingFragment.java
main/src/cgeo/geocaching/settings/fragments/PreferenceServiceGeocachingComAdventureLabsFragment.java
main/src/cgeo/geocaching/settings/fragments/PreferenceSystemFragment.java

While working on #12488 I've stumbled upon our somewhat messy list of preferences. This PR does a cleanup/consolidation as far as possible without migration:
- sorted and grouped all preference keys according to preference screen and category
- consolidate all preference screen keys to name scheme "preference_screen_xxx"
- consolidate all category keys (not many given) to name scheme "preference_category_xxx_yyy"
- consolidate preference keys given in `preferences.xml`, but not actually storing a value, to name scheme "pref_fakekey_xxx" as variable name and "fakekey_xxx" as value
- did not consolidate all other prefs except some grouping
- deleted preference keys no longer in use
- related to this: remove opencaching "register" pref keys and configuration
- related to this: removes …

consolidate preference keys (without migration)

---

main/src/cgeo/geocaching/settings/fragments/BasePreferenceFragment.java

Auto-creates missing preference keys that are only needed to support search in settings.

auto-create missing preference keys to support search (fix #12488)

---

main/res/values/strings.xml
main/src/cgeo/geocaching/maps/mapsforge/v6/legend/ThemeLegendFreizeitkarte.java

Cleanup some of the strings for map theme legends:
- remove one duplicate
- remove some unnecessary prefixes in string values
- remove some unnecessary infixes in string names
- resort some of the strings (grouping)

cleanup some map theme legend strings

---

main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/activity/AbstractBottomNavigationActivity.java
main/src/cgeo/geocaching/enumerations/CacheListType.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/MapOptions.java
main/src/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

(dev call agreement: https://github.com/cgeo/cgeo/issues/12443#issuecomment-1008432061)
fix #12443, fix #12423
Furthermore in this PR:
- don't manipulate activity stack, even if bottom navigation activity was already alive (rel. to #11926)
- don't show cache name in map action bar but rather in our 'target view' after 'live' was turned on

Improve in which cases a bottom navigation should be shown

---

main/res/values/preference_keys.xml
main/res/values/strings.xml
main/res/xml/preferences_services.xml
main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/loaders/CoordsGeocacheListLoader.java
main/src/cgeo/geocaching/settings/Settings.java

Adds a setting to Settings => Services => Nearby search to define a limit up to which the services return caches on nearby search. A value of 0 means "unlimited" and is the default.
(Limit will get applied for nearby search only, neither for coord search or address search.)

add setting for nearby search distance limit (fix #11489)

---

main/build.gradle

Since our fixes are included in officially released mapsforge version, we scan switch our build back to the official release

switch back to official mapsforge, v0.17.0.0 (fix #12524)

---

main/src/cgeo/geocaching/settings/fragments/BasePreferenceFragment.java
main/src/cgeo/geocaching/utils/MapMarkerUtils.java

Fixes the 33 lint messages regarding unused resources/values related to cache ratings by creating a dummy enum referencing the drawables (which in itself use the color values).
Additionally fixes an older CheckStyle error about wrong import order.

fix lint: unused drawables and values for cache ratings

---

mapswithme-api/res/values/strings.xml

The old address does not more exist.
Instead there is a link on the home page to the map store.

correct maps.me download

---

main/lint.xml
main/src/cgeo/geocaching/utils/MapMarkerUtils.java

related to #12533
instead of adding code to reference the cache rating markers config lint to ignore those seemingly unused resources

adapt lint config for false positives on cache rating markers

---

main/res/values/strings.xml

A cache owner contacted us on support mail:
He owns and knows many caches, which use the "chirp attribute" but do not contain a chirp but some other transmitting related stuff like Wifi or NFC. As can be seen in many examples the attribute is also used for such kind of caches.
Users looking for such caches do contact him as they are confused by c:geo reporting, that CacheWolf is needed as it is a chirp cache, while it is not.
I suggest to give a short hint in the text used to link to CacheWolf, that it **might** be a chirp cache.
None
Support ticket 463619

Improve strings for caches with chirp attribute

---

main/res/drawable/center.xml

IMHO, the meaning of the old center icon was not clear enough, so I suggest using a different one... 
|before|now|
-|-

[MultiTrackFiles] use better "center" icon

---

.github/dependabot.yml
cgeo-contacts/build.gradle
main/build.gradle

Downgrade used version of commons-lang3 to 3.11 which was tested to make c:geo work again on API 21-23
Fixes #12577 
Reverts #10100
Please check if any `noinspection` or similar needs to be defined.

Fix #12577 - Downgrade commons-lang3 to 3.11

---

main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/ui/CacheListAdapter.java

Replaces `<h5>`/`<h6>` formatting of attribute category titles by bold/underline to remove spacing after title.
Cache details page:
|before|after|
|---|---|
|![image](https://user-images.githubusercontent.com/3754370/150690326-04ccc28c-ac05-4798-b43e-da3011d3d2d9.png)|![image](https://user-images.githubusercontent.com/3754370/150690332-e8aa1e42-02f4-4ef6-bcf5-d113649bd937.png)|
Cache list page:
|before|after|
|---|---|
|![image](https://user-images.githubusercontent.com/3754370/150690307-875fa968-0e61-45b8-af55-c4e8bd3d143a.png)|![image](https://user-images.githubusercontent.com/3754370/150690312-c58534c4-1e96-4d1a-b342-f6735f526472.png)|

remove spacing after attribute group titles (fix #12601)

---

main/src/cgeo/geocaching/settings/SettingsActivity.java

Sets foreground color on settings' search hit. Fixes non-legible text when search hit is a preference button:

set foreground color on settings search hit (fix #12590)

---

main/res/layout/main_activity.xml
main/res/layout/mainactivity_action_item.xml
main/res/values/numbers.xml
main/res/values/preference_keys.xml
main/res/values/strings.xml
main/res/xml/preferences_backup.xml
main/src/cgeo/geocaching/CgeoApplication.java
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/activity/AbstractBottomNavigationActivity.java
main/src/cgeo/geocaching/downloader/DownloaderUtils.java
main/src/cgeo/geocaching/settings/Settings.java
main/src/cgeo/geocaching/settings/fragments/PreferenceBackupFragment.java
main/src/cgeo/geocaching/utils/BackupUtils.java

(screenshots in this entry are outdated, the reminder is no longer being shown as a modal `AlertDialog`)
Adds an automatic backup reminder to c:geo which offers you to either create an automated backup now or postpone it a bit:
There's not much to configure: You can set the interval to 0 (effectively disabling automatic backup reminders) or to a certain amount of days when to be reminded next:
The default interval is "14 days", and you will be reminded for your first automatic backup 14 days after your first start of the new version (at least if you do not reset the preference value for `automaticBackupLastCheck` manually).
The maximum number of backups is set to 5, and "include account data" setting will be shared with manual backups.
Automatic backups are stored in a subfolder `auto` …

automatic backup reminder (fix #6315)

---

main/src/cgeo/geocaching/connector/gc/GCConstants.java
main/src/cgeo/geocaching/connector/gc/GCLogin.java
main/src/cgeo/geocaching/settings/GCAuthorizationActivity.java
main/src/cgeo/geocaching/ui/AvatarUtils.java
tests/src-android/cgeo/geocaching/connector/gc/GCLoginTest.java

fix #12620
While with this PR the avatar image will always stay in sync, we will even do less network requests. Reason is, that the avatar URL is always contained in the so called `serverparams` which we request all the time anyway, so no separate request is needed...
This also removes some legacy code which is no longer in use.

update avatar when loading server params

---

main/src/cgeo/geocaching/connector/gc/GCLogin.java

fix regression introduced by #12621
While using the latest nightly, I noticed that the avatar is displayed with a way worse resolution than before. Thus, this will change the code to use the high-res version of avatar image again...

use high-res version of avatar image 

---

main/src/cgeo/geocaching/utils/formulas/FormulaFunction.java

Fixes wrong "Roman" label for "Vanity" function in "insert function" dialog on variables tab:

fix label for vanity function

---

main/res/xml/preferences_backup.xml
main/res/xml/preferences_map.xml
main/res/xml/preferences_navigation.xml
main/src/cgeo/geocaching/settings/SeekbarPreference0Off.java

Displays "off" for value 0 instead of reusing the regular backup slider's value of "only recent"

display 'off' state in autobackup slider (fix #12624)

---

main/res/layout/variable_list_item_advanced.xml

Use "𝑓" symbol instead of "..." as label for "insert function" button

use math f as 'insert function' symbol (fix #12494)

---

main/res/drawable-v26/sc_map.xml
main/res/drawable-v26/sc_nearby.xml
main/res/drawable-v26/sc_search.xml
main/res/drawable-v26/sc_stored.xml
main/res/drawable/sc_goto.xml
main/res/drawable/sc_history.xml
main/res/drawable/sc_map.xml
main/res/drawable/sc_nearby.xml
main/res/drawable/sc_search.xml
main/res/drawable/sc_stored.xml
main/src/cgeo/geocaching/CreateShortcutActivity.java

supports adaptive icon shapes for shortcuts in SDK26+
fixes display of Widgets
follow-up on https://github.com/cgeo/cgeo/pull/12623#issuecomment-1025009003
Widget icons are always round as they must be generated from static resourcves

add adaptive shortcut icons for SDK26+

---

main/res/values/preference_keys.xml
main/res/values/strings.xml
main/res/xml/preferences_appearence.xml
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/settings/Settings.java

Allow users to activate current system wallpaper as dashboard background
Default value is `false` = "do not use wallpaper as background"

optionally use wallpaper as dashboard background (fix #11867)

---

main/src/cgeo/geocaching/ui/dialog/SimpleDialog.java

fix #12636: SimpleDialog, define different item types for normal and group heading

fix #12636: SimpleDialog, define different item types for normal and group heading

---

main/res/layout/map_progressbar.xml
main/res/values/styles.xml

Use Material progress bar for better visibility, as suggested in https://github.com/cgeo/cgeo/issues/12573#issuecomment-1025196125
It has a 2x stroke width compared to the old one and is directly attached to the top instead of being floating inside the map.
Before:
Now:

use material progress indicator for better visibility on map

---

main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/downloader/DownloadNotificationReceiver.java
main/src/cgeo/geocaching/downloader/DownloaderUtils.java
main/src/cgeo/geocaching/settings/fragments/PreferenceSystemFragment.java
main/src/cgeo/geocaching/utils/DebugUtils.java

Sometimes (map / routing data) downloads are finished, but somehow c:geo did not get triggered, as described in the related issue.
This PR adds a check to program start to query the system's `DownloadManager` for any finished, but not yet transmitted downloads, and ~asks the user, if they want to import them now~ directly triggers receiving such files, if any are pending.
~Currently it's realized as a dialog box, but will be changed to a dashboard notification, after PR #12632 has been merged. Therefore setting WIP label for now.~
(Additionally moves the `dumpDownloadmanagerInfos` method from `DebugUtils` to `DownloaderUtils` as it has a closer relationship.)

resume finished downloads (fix #12109)

---

main/res/layout/main_activity.xml
main/res/layout/mainactivity_action_item.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/downloader/DownloaderUtils.java
main/src/cgeo/geocaching/utils/BackupUtils.java

Fine-tuning for dashboard messages regarding backup & update reminder:
- remove action button => tapping on message activates action
- adapted messages accordingly
- fix: only one message could be shown at a time - now all (up to three) can be displayed

fine-tune dashboard status messages (fix #12631)

---

main/res/layout-h390dp-land/activity_bottom_navigation.xml
main/res/layout-land/activity_bottom_navigation.xml
main/res/layout/activity_bottom_navigation.xml
main/src/cgeo/geocaching/MainActivity.java

Instead of using the wallpaper image as background drawable add an `ImageView` to the bottom navigation activity, so that we are able to use `scaleType=centerCrop`, which centers the image and crops everything that got too large. It's probably still not 100% the same for some launchers, but comes pretty close to what the default launcher does with the wallpaper.
|Resulting image is like this:|instead of this:|
|---|---|
|![image](https://user-images.githubusercontent.com/3754370/152238620-94b2e244-d488-4584-951b-a409bbb8603c.png)|![image](https://user-images.githubusercontent.com/3754370/151707413-899a88da-a069-4158-9442-08eda66e5143.png)|

centerCrop wallpaper on home screen (fix #12654)

---

main/src/cgeo/geocaching/CacheListActivity.java

Don't use the extend method for the action bar on cache lists to allow wider list names (and reenable textual description if enough room (e.g. on landscape):
Portrait:
| Before | After |
| --- | --- |
| ![final_list_portrait_with](https://user-images.githubusercontent.com/949669/152638602-4d48e869-0918-4b34-ac14-5a16c98451fd.png)| ![final_list_portrait_wo](https://user-images.githubusercontent.com/949669/152638608-efa06dee-167d-4871-8135-d1a174a33256.png)|
Landscape:
| Before | After |
| --- | --- |
|![final_list_landscape_with](https://user-images.githubusercontent.com/949669/152638629-1fee28fc-6498-47e1-a682-ddc1bfc016c0.png)|![final_list_landscape_wo](https://user-images.githubusercontent.com/949669/152638623-67f743a8-251f-40c7-9373-6846b37fe344.png)|
For the map action bar the method …

Fix #12613 - Do not modify list action bar

---

main/src/cgeo/geocaching/connector/gc/GCWebAPI.java

rel to #12673: fix sending of normal logs (without images) for emulator API 29

rel to #12673: fix sending of normal logs (without images) for emulator API 29

---

main/res/layout/imageselect_activity.xml
main/res/menu/menu_ok_cancel.xml
main/res/values/strings.xml

Fixes #12569 by supplying our own strings for "Ok" and "Cancel" (which we already did before, but the were not used by the buttons mentioned in the issue).

offer label strings for ok and cancel (fix #12569)

---

main/src/cgeo/geocaching/TrackableActivity.java

Fix NPE in `TrackableActivity` introduced with the changes for enabling line breaks on cache/trackable item overview pages

fix NPE in TrackableActivity (fix #12452)

---

main/src/cgeo/geocaching/downloader/DownloadSelectorActivity.java

Avoid a `CursorIndexOutOfBounds` exception still happening in `DownloadSelectorActivity` as reported on Play Console

mitigate CursorIndexOutOfBounds exception in DownloadSelector

---

main/AndroidManifest.xml
main/res/menu/cache_list_options.xml
main/res/menu/map_activity.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/HandleLocalFilesActivity.java
main/src/cgeo/geocaching/downloader/ReceiveDownloadService.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/service/AbstractForegroundIntentService.java
main/src/cgeo/geocaching/service/CacheDownloaderService.java
main/src/cgeo/geocaching/service/IAbstractForgreoundIntentService.java
main/src/cgeo/geocaching/ui/dialog/CheckboxDialogConfig.java
main/src/cgeo/geocaching/ui/dialog/Dialogs.java
main/src/cgeo/geocaching/ui/notifications/Notifications.java

First alpha version for #330
From some quick tests in the emulator, I can tell that it already works quite good.
The only bug / intended feature (?) I've discovered is, that refreshed caches will only reflect the update if the foreground activity gets restarted.
However, I've decided to start as "nightly only" feature for now and have added some deterrent warning ;-)
|download running|download finished|
-|-

Download caches as non blocking service

---

main/res/menu/map_activity.xml
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/legend/RenderThemeLegend.java

Fixes a few errors where "map legend" menu entry was displayed in situations not supporting a map legend:
- hide "map legend" menu entry by default (fixes displaying it on Google Maps)
- do not only check whether the current map supports themes, but additionally check whether the selected theme supports a legend

fix displaying legend menu for unsupported maps/themes (fix #12704)

---

main/res/menu/map_activity.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/RouteTrackUtils.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

Enables the "routes/tracks" quick button when a navigation target is set, which gives you a quick access to the "clear manual targets" option.
Also fixes a hard-coded label for the "Routes / Tracks" menu item.
The whole `mapOptions` and setting a target is pretty confusing to me. In the end I basically added something like 
```
final Geocache temp = getCurrentTargetCache();
if (temp != null) {
lastNavTarget = temp.getCoords();
}
```
to both map implementations (under certain conditions).
A review / some testing would be welcomed to check whether this has unwanted side-effects.

display routes/tracks button if target is set (fix #12701)

---

main/res/menu/bottom_navigation_menu.xml
main/res/values/strings.xml
main/res/xml/shortcuts.xml
main/src/cgeo/geocaching/CreateShortcutActivity.java

rel. to #12725
- Use `Map` for bottom navigation
- Continue using the old `Live-Map` label for launcher shortcuts (is this the wanted behavior? IMHO "live" makes it sound more like c:geo, so I would prefer this on as launcher shortcut label. Last but not least to avoid unnecessary confusion for our users ;-))
@Lineflyer

avoid usage of string references

---

main/res/values/strings.xml
main/src/cgeo/geocaching/log/LoggingUI.java
main/src/cgeo/geocaching/settings/Settings.java

add a menu item to the "Quick offline log" dialog to insert a Found log with text taken from template.
The menu item is shown only if any log template is defined.

Log templates in offline log dialog

---

tests/src-android/cgeo/geocaching/downloader/DownloaderTest.java

New file size of tested routing tile exceeds the limits set so far, therefore increase limits tested against

adapt tile downloader test to new data on server (fix #12732)

---

main/res/layout/logtrackable_activity.xml
main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateGlobalDialog.java
main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java

fix #12741: restore coordinate button for trackable logs

fix #12741: restore coordinate button for trackable logs

---

main/src/cgeo/geocaching/LooperLogger.java

fix #12745: prevent possible division by zero in looperlogger

fix #12745: prevent possible division by zero in looperlogger

---

main/src/cgeo/geocaching/ui/CacheListAdapter.java

avoid NPE on unknown attribute in cache list attribute overview (fix #12753)

avoid NPE on unknown attr in cache list attribute overview (fix #12753)

---

main/res/values/strings.xml
main/src/cgeo/geocaching/files/GPXTrackOrRouteImporter.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/RouteTrackUtils.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

- removes "loading track/route in background" toast, and
- removes "track/route loaded (xxx trackpoints)" toast, but
- keeps toast on error

remove track load/success toasts (fix #12761)

---

main/src/cgeo/geocaching/activity/TabbedViewPagerFragment.java

avoid flicker in cache description page
This should be tested in the nightlies before publishing a new bugfix release. The bug fix seems to be too obvious, but maybe the now added line had been left out to avoid some side-effects, can't say any more. A quick test in both standard mode and "show last detail page as default" mode seem to work fine, though.

avoid flicker in cache description page (fix #10985)

---

main/src/cgeo/geocaching/models/Geocache.java

fix #12792: keep original coord on geocache merge

fix #12792: keep original coord on geocache merge

---

main/src/cgeo/geocaching/settings/SettingsActivity.java
main/src/cgeo/geocaching/settings/fragments/PreferenceBackupFragment.java

Restore the disabled "restore a different backup" function, which got uncoupled during settings migration
Due to migrating settings to fragments and the `BackupPreferenceFragment` using its own instance of `BackupUtils` ContentStorageActivityHelper was no longer able to identify the request correctly.

restore 'restore a different backup' function (fix #12791)

---

main/res/layout/routes_tracks_item.xml
main/src/cgeo/geocaching/maps/RouteTrackUtils.java

Switches the "route sort" icon to a "route edit" icon in route/track quick settings:

switch route sort icon to edit icon in route quick settings (fix #12812)

---

main/src/cgeo/geocaching/maps/CGeoMap.java

fix #12749: let mapstate coord take precedende over geocode when centering google map
If cgeomap has both a geocode and a coordinate (in this case of a waypoint), it centered on geocode main coord (cache coord) instead of given coordinate (from waypoint). Fixed by switching order of checks

fix #12749: let mapstate coord take precedende over geocode when centering google map

---

main/src/cgeo/geocaching/export/IndividualRouteExport.java

Add caches as waypoint, when exporting an individual route as track/route. This makes the exported GPX useful in context of other outdoor apps:
Individual Route in c:geo|Garmin Cycle Computer |Locus
-|-|-
Note: This is the MVP approach currently. Only a waypoint with the geocode as name is added to the GPX, not the full cache...
fix #12824

fix #12824: include waypoints in gpx for IndividualRouteExport

---

main/src/cgeo/geocaching/maps/RouteTrackUtils.java

If a trackfile cannot be read any longer, returned route is `null` which leads to a crash on trying to apply the hidden flag to it. This PR fixes this.

add missing null check (fix #12846)

---

main/res/layout/main_activity.xml
main/res/values/attrs.xml
main/res/values/preference_keys.xml
main/res/values/strings_not_translatable.xml
main/res/values/styles.xml
main/res/values/themes.xml
main/res/xml/preferences_appearence.xml
main/src/cgeo/geocaching/AboutActivity.java
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/enumerations/QuickLaunchItem.java
main/src/cgeo/geocaching/settings/Settings.java
main/src/cgeo/geocaching/settings/fragments/PreferenceAppearanceFragment.java

Add support for quick launch icons on homescreen.
- set of up to eight buttons, in a fixed order
- being displayed at the bottom of the home screen, centered horizontally, above location info
- configurable using settings => appearance => quick launch buttons
- button sections being displayed only if at least one quick launch setting is selected
- default configuration is "none selected"
|home screen|settings|select items|none selected|
|---|---|---|---|
|![image](https://user-images.githubusercontent.com/3754370/155897081-63bd8e47-84e5-4cbe-a8bb-425eeb7ec643.png)|![image](https://user-images.githubusercontent.com/3754370/155897103-e6915deb-ff1b-451f-84b6-1283f18e997d.png)|![image](https://user-images.githubusercontent.com/3754370/155897112-be334dd7-82b1-4601-9bc7-e991628e913e.png)|![image …

support quick launch buttons on the home screen (fix #12790)

---

main/res/xml/preferences_map.xml
main/src/cgeo/geocaching/maps/google/v2/GoogleMapView.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

Make map's "long tap adds waypoint" function honor the map's "long tap enabled/disabled" setting.

extend map's 'long tap' setting to waypoints (fix #12821)

---

main/res/layout/main_activity.xml

adds bottom margin to quick launch buttons (see https://github.com/cgeo/cgeo/pull/12817#issuecomment-1066425651):

add bottom margin to quick launch buttons (fix #12817)

---

main/res/raw/changelog_bugfix.md
main/res/values/strings.xml
main/src/cgeo/geocaching/AboutActivity.java
main/src/cgeo/geocaching/utils/BranchDetectionHelper.java

Proposal for easier version number handling for bugfix releases - not to be merged yet.
@Lineflyer 
Please have a look at `BranchDetectionHelper.java` and `changelog_bugfix.md` - would this type of version number handling for bugfix releases be ok for you?
- `BranchDetectionHelper.java` contains a string array with version numbers for bugfix releases (will be empty´for feature release)
- `changelog_bugfix.md` contains `##` placeholders only at the places where version numbers will be inserted
Magic configuration line in `BranchDetectionHelper.java` would look like this for current release:
```
// should contain version names of active bugfix releases since last feature release, newest first
// leave curly brackets empty if not a bugfix release
public static final String[] …
```

WIP make bugfix version number handling easier (fix #12852)

---

main/src/cgeo/geocaching/maps/mapsforge/v6/caches/AbstractCachesOverlay.java

Map throws an IllegalStateException on stopping the map (lifecycle method) if a layer is not assigned internally, leading to random crashes as described in #12848. This PR catches that exception, so that the map can be shut down normally.

catch IllegalStateException in map lifecycle (rel. to #12848)

---

tests/src-android/cgeo/geocaching/downloader/DownloaderTest.java

Currently build on CI fails due to a specific FZK map file having exceeded the file size limits being tested against.
This PR increases the limit (with some buffer for further growth).

Adapt FZK-download test to increased file size

---

main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/models/WaypointParser.java
main/src/cgeo/geocaching/ui/dialog/EditNoteDialog.java
tests/src/cgeo/geocaching/models/WaypointParserTest.java

* don't add doubled new line at beginning of personal note when adding parseable waypoint
* trim personal note 
fix #12838
trimming the personal note on setting it would make the removing of the doubled new line superfluous, but I thought it would be clearer to have both code-locations adpated

remove blank lines at beginning of personal note (fix #12838)

---

main/build.gradle
main/src/cgeo/geocaching/CgeoApplication.java
main/src/cgeo/geocaching/log/AbstractLoggingActivity.java

fixes #12856
Removal of complete emoji compat Implementation.
Disadvantage: Up to API 27, two emoji are without a picture.
This is a alternative implementation compared to #12897.

remove emoji compat (bundled)

---

build.gradle

Optimize the output of `gradlew dependencyUpdates` by applying default exclude rules (e.g. for RC or alpha versions).
So there are excluded now
- com.android.tools.build:gradle [4.2.2 -> 7.3.0-alpha04]
- com.squareup.okhttp3:mockwebserver [4.9.3 -> 4.10.0-RC1]
- com.squareup.okhttp3:okhttp [4.9.3 -> 4.10.0-RC1]

use gradle-versions-filter

---

main/res/layout/logs_item.xml

Enables selecting log texts (or part of it) by long-tapping on the text.
(Short tap on the log text still opens the context menu.)

enable text selection in logs (fix #12911)

---

main/res/drawable/geochecker_available.xml
main/res/layout/cachedetail_description_page.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/connector/gc/GCParser.java

- fixes gc checker link for Android 12
- no longer add such a link on reloading the cache
- display a "geochecker available in browser" button below the description where applicable (valid for all detected geocheckers, not only gc.com geochecker)
|gc checker link for stored cache, not updated|gc checker, listing updated|non-gc checker|
|:---:|:---:|:---:|
|![image](https://user-images.githubusercontent.com/3754370/166117789-516ee1f8-98af-46c8-b133-d754c925f32c.png)|![image](https://user-images.githubusercontent.com/3754370/166117796-f9d70da6-382d-4435-b90e-36326cd1a05c.png)|![image](https://user-images.githubusercontent.com/3754370/166117805-84c39fc5-9c3a-44f8-99ca-444475e91fe0.png)|
|1|2|3|
1) for stored caches, not updated: link is still shown, but reverted to same functionality as …

fix gc checker link for Android 12 (fix #12889)

---

main/src/cgeo/geocaching/utils/formulas/FormulaUtils.java
tests/src/cgeo/geocaching/utils/formulas/FormulaUtilsTest.java

rel to #12958: handle german umlauts in lettervalue
This PR, if merged, will assign values 27-30 to german umlats äöüß in lettervalue

rel to #12958: handle german umlauts in lettervalue

---

main/src/cgeo/geocaching/activity/AbstractActivity.java
main/src/cgeo/geocaching/activity/AbstractBottomNavigationActivity.java

As agreed in #12813:
- When navigating via the bottom navigation, the whole activity stack will be cleared
- When the current activity is the task root, pressing back will navigate to the dashboard

Clear activity stack when navigating via the bottom navigation (fix #12813)

---

main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/models/Geocache.java
main/src/cgeo/geocaching/utils/ImageUtils.java

fix #12938: consider as spoiler images only those not used in listing or containing spoiler

fix #12938: consider as spoiler images only those not used in listing or containing spoiler

---

main/res/layout/button_icon_view.xml
main/res/layout/button_view.xml
main/res/layout/cache_filter_activity.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/filters/core/GeocacheFilterContext.java
main/src/cgeo/geocaching/filters/core/GeocacheFilterType.java
main/src/cgeo/geocaching/filters/core/LogicalGeocacheFilter.java
main/src/cgeo/geocaching/filters/gui/FilterViewHolderCreator.java
main/src/cgeo/geocaching/filters/gui/GeocacheFilterActivity.java
main/src/cgeo/geocaching/filters/gui/LogicalFilterViewHolder.java
main/src/cgeo/geocaching/utils/SystemInformation.java

Advantage: Users can now combine `AND` and `OR` within one filter.
- Fix #11275
- Fixes #12090 implicitly as well
|Normal "toplevel" filter|Sub-filter|
-|-
This example will evaluate to `([:inconclusive=false:advanced=true]AND(OR(difficulty_terrain:d=-:d=3.0:t=-:t=3.0;status:found_yes);type:TRADITIONAL))`
There is no limit how deep a filter can be nested, so users can get really creative. ;-)
Example (build with the new UI): `([:inconclusive=false:advanced=true]AND(OR(NOT(AND(name::contains)))))`
Sidenote: This was rather easy to implement, as the backend luckily had already supported the parsing of nested filters. Only the frontend was missing until now.

Support building nested filters

---

main/res/values/preference_keys.xml
main/res/values/strings.xml
main/res/xml/preferences_map.xml
main/src/cgeo/geocaching/settings/Settings.java

Introduce a new setting key for the now extended setting (https://github.com/moving-bits/cgeo/commit/5a2b8097dfec1544051f68c6e5936b503640ee9d) to avoid update-problems described in #12821
Also rename the strings to include "waypoints" which are now affected by this
fixes #12821

introduce a new setting key for the extended "long tap on map" and update strings

---

main/src/cgeo/geocaching/CacheDetailActivity.java

add the count of friends/own logs on that tab
Variables, waypoints and images tabs already have the count - friends/own logs tab shouldn't be discriminated against ;-)

add count on friends/own logs tab

---

main/res/drawable/bearing_indicator.xml
main/res/layout/map_bearingindicator.xml
main/res/layout/unifiedmap_mapsforgevtm.xml
main/src/cgeo/geocaching/unifiedmap/AbstractUnifiedMapView.java
main/src/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmView.java

Display a bearing indicator on UnifiedMap VTM, if bearing != 0.
Tapping on bearing indicator resets bearing to 0 (and hides bearing indicator until bearing != 0).

add bearing indicator for VTM/UnifiedMap (fix #12925)

---

main/src/cgeo/geocaching/connector/unknown/UnknownConnector.java

Activates setting found state for UnknownConnector (which gets triggered for all caches not related to one of the other connectors, thus especially for caches imported via Lab2Gpx when using one of the "free" prefixes)

support setting found state for UnknownConnector (fix #13029)

---

main/src/cgeo/geocaching/activity/AbstractActivity.java

I noticed that using normal broadcasts to manipulate our activity stack isn't a good idea. Broadcasts are global, thus every app could theoretically listen to whether a user currently navigates in c:geo (→ privacy issue) and - IMHO even worse - kill cgeo at any time by sending this broadcast. 
This security fix should be included into the beta.

Make activity stack broadcasts local

---

main/src/cgeo/geocaching/utils/BackupUtils.java

fix #13050: prevent npe, handle case when backup file can't be opened  for writing

fix #13050: prevent npe, handle case when backup file can't be opened  for writing

---

main/res/menu/map_downloader.xml
main/res/values/preference_keys.xml
main/res/values/strings.xml
main/res/xml/preferences_map.xml
main/src/cgeo/geocaching/downloader/ReceiveDownloadService.java
main/src/cgeo/geocaching/maps/CacheMarker.java
main/src/cgeo/geocaching/maps/DefaultMap.java
main/src/cgeo/geocaching/settings/Settings.java
main/src/cgeo/geocaching/settings/fragments/PreferenceMapFragment.java
main/src/cgeo/geocaching/unifiedmap/AbstractGeoitemLayer.java
main/src/cgeo/geocaching/unifiedmap/AbstractUnifiedMapView.java
main/src/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/cgeo/geocaching/unifiedmap/UnifiedMapType.java
main/src/cgeo/geocaching/unifiedmap/googlemaps/GoogleGeoitemLayer.java
main/src/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsView.java
main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeGeoitemLayer.java
main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeVtmView.java
main/src/cgeo/geocaching/unifiedmap/tileproviders/TileProviderFactory.java

- define `UnifiedMapType` for transmitting and storing map type state (rel. to #13041)
- add global integration setting for `UnifiedMap` (rel. to #12975) - adds checkbox entry (`useUnifiedMap`) to Settings => Map, when setting `showUnifiedMap` is true; can be used as switch for `CacheDetailActivity` and others to switch between map implementations
- add `UnifiedGeoitemLayer` as prerequisite to display geoitems (caches so far) (rel. to #12928)
- display a single cache (including its overlays) on the map, activated via cache details => navigate => map (rel. to #12926)
- allow more toolbar icons (fix #13066)
- add downloaded map to selection (fix #13067)

Several extensions to UnifiedMap

---

main/src/cgeo/geocaching/log/LogCacheActivity.java

we're currently using only the cache type, status and connector to determine the available log types.
This leads to situations where more log types are available in c:geo than on the platform, e.g. archived events (https://github.com/cgeo/cgeo/issues/13080) but also normal GC caches where c:geo shows 5 logtypes, including NM and NA - which on GC are only available as a "report problem" option.
This PR updates the list of available log types to match what's available online.

show only logtypes that are available online

---

main/res/values/strings.xml
main/src/cgeo/geocaching/service/AbstractForegroundIntentService.java
main/src/cgeo/geocaching/speech/SpeechService.java
main/src/cgeo/geocaching/ui/notifications/Notifications.java

Running the SpeechService as foreground makes it less likely of getting killed if screen is off...
fix #7057
fix #10781

Make SpeechService more robust against getting killed 

---

main/res/layout/main_activity.xml
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/utils/BackupUtils.java

Make auto-backup less intrusive...
- remove toasts if everything went right
- if something went wrong, show the toast longer than currently 
This does only affect auto-backup, not the normal backup functionality!

[Autobackup] remove unnecessary toasts

---

main/src/cgeo/geocaching/utils/CheckerUtils.java

The `Geocache.hasFinalDefined()` method seems to be unreliable. It sometimes returns true even if no final waypoint with coords can be found, which results in a NPE as described in #13112.

Fix NPE in CheckerUtils (fix #13112)

---

main/src/cgeo/geocaching/settings/fragments/PreferenceSystemFragment.java
main/src/cgeo/geocaching/utils/BranchDetectionHelper.java

Currently, the unit test directory setting is displayed for developer and nightly builds. Show it only for developer builds instead.

Don't show unit test directory in nightly builds

---

main/res/values/strings.xml
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/models/WaypointParser.java
tests/src-android/cgeo/geocaching/models/GeocacheTest.java
tests/src/cgeo/geocaching/models/WaypointParserTest.java

Remove the size-limitation on export of waypoints to personal note.
Instead show toast on upload with character-count, which exceeds the size-limit (so user knows, how many characters he has to remove to avoid shortening on upload)
fix #10981

remove size-limit check while storing waypoints in PN

---

main/src/cgeo/geocaching/ImageViewActivity.java
main/src/cgeo/geocaching/models/Image.java
main/src/cgeo/geocaching/ui/ImageGalleryView.java
main/src/cgeo/geocaching/utils/UriUtils.java

rel to #12783: make image detection more reliable
URLs where Mime-Type is not discoverable (e.g. without suffix) were handled as non-image-URLs by ImageGallery before. With this PR they are handled as images (making this the default)

rel to #12783: make image detection more reliable

---

main/build.gradle

- raise compile SDK to 31 to be able to upgrade some material libs to the most-recent versions
- leave target SDK at 30 for now to avoid behavioral changes (see #13036 for this)

raise compile SDK to 31

---

main/src/cgeo/geocaching/downloader/DownloaderUtils.java

Avoid NPE in checkPendingDownloads on DownloadManager failing to return a valid cursor

avoid NPE in checkPendingDownloads (fix #13123)

---

main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/caches/AbstractCachesOverlay.java
main/src/cgeo/geocaching/models/Geocache.java
main/src/cgeo/geocaching/models/Waypoint.java
tests/src-android/cgeo/geocaching/models/GeocacheTest.java

don't show distance circles for waypoints, if the cache itselft does not need to show distance circles
fix #13117

don't show distance circle for waypoints of archived caches

---

main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

Store filter context in savedInstanceState of `NewMap` and `CGeoMap` and restore it in `onCreate` to avoid losing filters on config changes for temporary filters, as described in #13147

maps: put filter context into savedInstanceState (fix #13147)

---

main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgeThemeHelper.java

Avoid NPE in `MapsforgeVtmView.onDestroy` if no theme is loaded (or not yet loaded).

avoid NPE on VTM map destroy if no theme is loaded

---

main/src/cgeo/geocaching/settings/CapabilitiesPreference.java

Disables the doubled scroll bar for `CapabilitiesPreference` summary, see #12338

disable vertical scroll bar (fix #12338)

---

main/build.gradle
main/src/cgeo/geocaching/AbstractDialogFragment.java
main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/ImagesActivity.java
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/StatusFragment.java
main/src/cgeo/geocaching/TrackableActivity.java
main/src/cgeo/geocaching/activity/AbstractActivity.java
main/src/cgeo/geocaching/log/LogCacheActivity.java
main/src/cgeo/geocaching/log/LogTrackableActivity.java
main/src/cgeo/geocaching/maps/AbstractMap.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/service/CacheDownloaderService.java
main/src/cgeo/geocaching/service/GeocacheRefreshedBroadcastReceiver.java
main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java
main/src/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/cgeo/geocaching/utils/CompositeLifecycleDisposable.java

Adding LifecycleObservers so consumers of a class don't need to remember to call it in onPause/onDestroy.

Use lifecycle observers to clean up code

---

main/src/cgeo/geocaching/log/CacheLogsViewCreator.java

If tapping on log text directly set focus to this field to avoid the need for double tap to edit the log entry (offline logs) resp. open the context menu (all other log types).
See https://stackoverflow.com/questions/22653641/using-onclick-on-textview-with-selectable-text-how-to-avoid-double-click
This PR is an alternative to PR #13150 and keeps ability to select text in offline logs.

avoid need for double tab to edit offline log (fix #13141)

---

main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/TapHandler.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/TapHandlerLayer.java

Prevent displaying a map marker on long tap if an existing map item got hit (OSM only).

prevent long tap marker on OSM if map item got hit (fix #13168)

---

main/src/cgeo/geocaching/models/WaypointParser.java
tests/src/cgeo/geocaching/models/WaypointParserTest.java

fix #13180: personal node var parsing: accept only numeric without $
See unit tests for exact behaviour

fix #13180: personal node var parsing: accept only numeric without $

---

main/res/menu/map_activity.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/downloader/DownloaderUtils.java
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/MapProviderFactory.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/settings/Settings.java
main/src/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
main/src/cgeo/geocaching/unifiedmap/tileproviders/AbstractMapsforgeTileProvider.java
main/src/cgeo/geocaching/unifiedmap/tileproviders/TileProviderFactory.java

Add option to delete an installed offline map to map menu for all map types (GM, NewMap, UnifiedMap).
Removes both map file and its companion file (if present) and updates list of available offline maps.
Currently active map cannot be deleted.

add option to delete offline maps (fix #13163)

---

main/src/cgeo/geocaching/utils/FileNameCreator.java

Close #13191 
Fixes typo for prefix.

fix typo in FileNameCreator (fix 13191)

---

main/res/layout/filter_sort_bar.xml
main/res/layout/map_distanceinfo.xml
main/res/layout/map_google.xml
main/res/layout/map_mapsforge_v6.xml
main/res/layout/map_progressbar.xml

Fixes map lon tap popup positioning problem described in #13171 and #13168 by changing filter bar into a map overlay, positioning the following map overlays relative to it.
This PR superseeds #13171.

fix long tap popup position (fix #13168)

---

main/build.gradle
main/src/cgeo/geocaching/AboutActivity.java
main/src/cgeo/geocaching/maps/AbstractMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/maps/routing/Routing.java
main/src/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

Uses lifecycle observers to automatically call `Routing.disconnect()`. This uses the Lifecycle aware component API to listen for `onDestroy()` and call disconnect without relying on the activity.
https://developer.android.com/topic/libraries/architecture/lifecycle

Auto-disconnect Routing using Lifecycle observer

---

main/src/cgeo/geocaching/activity/ActivityMixin.java
main/src/cgeo/geocaching/calendar/CalendarEntry.java

API 30 changes `Toast` behavior:
Doing a `Toast.setGravity` is not only ignored visually starting API 30, but additionally leads to an error entry in the log file for every toast being decorated that way.
This PR skips `setGravity` for toasts when running on API 30+

avoid error log entries due to Toast.setGravity on API > 29

---

main/build.gradle

After updating some of the AndroidX classes suddenly kotlin version of lifecycle defaults to a different version, leading to class duplication. Fix it by explicitly stating the same version number for both, Java and Kotlin, version of the lib.

fix duplicate lifecycle.viewmodel class build error

---

main/src/cgeo/geocaching/maps/CGeoMap.java

The new BroadcastReceiver init code from #13184 had been placed in CGeoMap class initialization, but needs to be called after async map view initialization has been finished. Therefore moving it to `initializeMap()`.

move CGeoMap BroadcastReceiver code to deferred map initialization (fix #13209)

---

.github/dependabot.yml

VTM uses jts-core 1.15.1 and accepts up to 1.16.1 due to an API-breaking change in jts-core 1.17. So let's dependabot ignore any upcoming changes to jts-core for now.
See https://github.com/mapsforge/vtm/discussions/935 for details

prevent dependabot updates for jts-core to stay vtm-compatible

---

cgeo-contacts/build.gradle

Set compileSDK for cgeo-contacts to 31, same value as in the main cgeo project.
(Required to mitigate build errors on rebuild)

set contacts compileSDK to 31

---

main/res/values/strings.xml
main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/downloader/ReceiveDownloadService.java
main/src/cgeo/geocaching/service/AbstractForegroundIntentService.java
main/src/cgeo/geocaching/service/CacheDownloaderService.java
main/src/cgeo/geocaching/ui/notifications/NotificationChannels.java

IIRC there were support tickets claiming that the background downloader makes too much sound. This makes notifications silent and less intrusive. (Proximity notifications are not affected)
Furthermore, fix a bug where the "download pending" icon was not shown correctly.

Make notifications less disturbing

---

main/src/cgeo/geocaching/downloader/DownloadSelectorActivity.java
main/src/cgeo/geocaching/storage/extension/PendingDownload.java

Our download selector activity uses a recycler view, which causes the progress bar to vanish as soon as the view is scrolled out of the screen. With this PR, the progress bar gets reloaded, as soon as the view becomes visible again.

[map downloader] fix progress indicator getting lost on scroll

---

main/res/menu/map_activity.xml
main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

We already show quite some cache specific options if the map is displayed in single-cache mode. However, the mostly used feature "log visit" was missing...
This PR will add  "log visit" / "quick offline log" to the maps overflow menu, if only one specific cache should be displayed.

show "log visit" menu entry in single cache map

---

main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/CachePopupFragment.java
main/src/cgeo/geocaching/CompassActivity.java
main/src/cgeo/geocaching/WaypointPopupFragment.java
main/src/cgeo/geocaching/speech/SpeechService.java

Using lifecycle observers to automatically check for `onDestroy`. This lets us make the start/stop functions private in SpeechService.

Automatically stop speech service on destroy

---

main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/HistoryLayer.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/NavigationLayer.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/RouteLayer.java
main/src/cgeo/geocaching/maps/mapsforge/v6/layers/TrackLayer.java
main/src/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsPositionLayer.java
main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgePositionLayer.java
main/src/cgeo/geocaching/utils/MapLineUtils.java

Make map line widths in `UnifiedMap` a bit smaller to make them comparable in size to `NewMap`

fix UnifiedMap line widths (fix #13277)

---

main/res/values/strings.xml

Adjusts the info text for "solved mystery" status filter as described in #13285.
Also removes a leading space before the second sentence which lead to unwanted indentation.
@eddiemuc: Is this text ok for you?

Adjust info text for 'solved mystery' status filter (fix #13285)

---

main/src/cgeo/geocaching/maps/CGeoMap.java
main/src/cgeo/geocaching/maps/RouteTrackUtils.java
main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
main/src/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java

fix "routes" button sporadically missing by replacing lazy `invalidateOptionsMenu` calls with explicit triggering of the show/hide commands

fix #12652 - "routes" button sporadically missing

---

mapswithme-api/src/com/mapswithme/maps/api/MapsWithMeApi.java

maps.me integration code displays a dialog box if it cannot find maps.me on the system. The dialog says something about "we have partnered with MAPS.ME" and asks the user to download the app (see screenshot below).
Since version 13.x of maps.me they seem to have changed their interface (without updating their integration code), so that the integration code is no longer able to detect maps.me. This leads to c:geo displaying this dialog on every call to maps.me API, even if maps.me is already installed. This is not only annoying, leading to many tickets on support, but also to negative reports on our Play Store entry.
This PR replaces the misleading maps.me message, explains the reason why it is not working currently, and links to our FAQ:
|before|after|
|---|---| …

Replace misleading maps.me dialog (rel. to #13209)

---

main/src/cgeo/geocaching/AboutActivity.java

Add `trim()` on reading bugfix changelog, as we would get an empty `Next release` block before otherwise.

Add trim to bugfix changelog to avoid empty release block

---

main/src/cgeo/geocaching/settings/fragments/PreferenceSystemFragment.java

Previously, a restart was necessary to apply the setting

directly handle change of debug setting

---

main/src/cgeo/geocaching/unifiedmap/mapsforgevtm/MapsforgePositionLayer.java

Take map rotation into account for heading indicator on UnifiedMap OSM

UnifiedMap OSM: Take map rotation into account (fix #13276)

---

main/res/values/preference_keys.xml
main/res/values/strings.xml
main/res/xml/preferences_navigation_navigation.xml
main/src/cgeo/geocaching/apps/navi/NavigationAppFactory.java
main/src/cgeo/geocaching/apps/navi/OtherMapsApp.java

Adds a new navigation app to the navigation menu: "Other external apps (coords only)"
This is for navigation apps like Here WeGo, which start an (unwanted) textual search for the label text if both coords and label are given. This new navigation entry triggers the external app with coordinates only, which does work even with more recent versions of Here WeGo.
related to #12810 (actually a workaround, as you will have to use the new menu entry instead of navigation (driving))

New navigation app 'other (coords only)' (rel. to #12810)

---

main/AndroidManifest.xml

Add an additional entry point to our settings to Android's app info for c:geo.
UX seems to be vendor specific, see the screenshot provided in https://github.com/cgeo/cgeo/issues/13308#issuecomment-1207195623 as well as this screenshot taken from emulated Nexus 5X:

Add additional entry point for settings (rel. to #13308)

---

main/src/cgeo/geocaching/utils/formulas/Formula.java
main/src/cgeo/geocaching/utils/formulas/FormulaFunction.java
main/src/cgeo/geocaching/utils/formulas/FormulaUtils.java
main/src/cgeo/geocaching/utils/formulas/Value.java
main/src/cgeo/geocaching/utils/formulas/ValueList.java
tests/src/cgeo/geocaching/utils/formulas/FormulaTest.java

fix #13313: use long instead of int in formulas, make int parsing aware of long-limits

fix #13313: use long instead of int in formulas, make int parsing aware of long-limits

---

.idea/checkstyle-idea.xml

Codacy changed their used checkstyle to version 10.3.1, so we should use the same version.
For AS you need the "CheckStyle-IDEA" plugin in Version >= 5.6.0.

AndroidStudio checkstyle in sync to Codacy

---

main/res/values/strings.xml
main/src/cgeo/geocaching/downloader/AbstractDownloader.java
main/src/cgeo/geocaching/downloader/MapDownloaderJustDownload.java
main/src/cgeo/geocaching/downloader/MapDownloaderJustDownloadThemes.java
main/src/cgeo/geocaching/downloader/MapDownloaderReceiverSchemeMap.java
main/src/cgeo/geocaching/downloader/MapDownloaderReceiverSchemeMapTheme.java
main/src/cgeo/geocaching/models/Download.java

Support downloading of generic `mf-v4-map://` prefixed map files / `mf-theme://` prefixed map theme files using the internal downloader.
As the update mechanism for the specific source is unknown, this is "download only", no upgrades supported.

Support generic mf-v4-map and mf-theme downloads (fix #13298)

---

main/res/menu/abstract_logging_activity.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/log/LogCacheActivity.java
main/src/cgeo/geocaching/log/LogTrackableActivity.java

disable the "Send" button in log activity while it's not yet available (loading TBs and log types), enable it once that is loaded.
partially fixes #13337 - there's no progress shown yet during the operation to indicate to the user that something is happening.
I noticed showProgress(true) in the code of that class which sounds quite fitting, but not sure what it's supposed to do. Legacy stuff, broken?

disable the "Send" button in log activity while it's not yet available

---

main/res/layout/editwaypoint_activity.xml
main/src/cgeo/geocaching/EditWaypointActivity.java

Removes the "clear" icon on "disabled" edit fields (name & note for system-defined waypoints)

Remove clear icon on name edit for system waypoints (fix #13344)

---

main/res/layout/editwaypoint_activity.xml

fixes three lint errors in editWaypoint layout
(ignore message, as label is provided by surrounding element)

fix lint 'labelFor' in editWaypoint layout

---

main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java

Attempts to fix #13356 by checking availability of `routeLayer` on returning from (async) reload

Prevent NPE on indiv. route reload (fix #13356)

---

main/res/menu/abstract_logging_activity.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/log/LogCacheActivity.java
main/src/cgeo/geocaching/log/LogTrackableActivity.java

don't disable the send button in log screens anymore.
Now that the log screen has a progress indicator it's easily visible to the user that "something" is ongoing.
For those users that don't know that this prevents logging the dialog with explanation is more useful than a disabled send-button
fixes #13370

revert fa4087fa, always enable "Send" button

---

main/src/cgeo/geocaching/maps/mapsforge/TileSourceOsmde.java

As requested by OSM team in https://github.com/openstreetmap/operations/issues/737 apps should not use a/b/c tileservers but those stated on https://wiki.openstreetmap.org/wiki/Tile_servers
This also applies to non-org servers per the issue above
fixes #13376

adjust OSM.de tile source

---

main/src/cgeo/geocaching/connector/gc/GCConnector.java
tests/src-android/cgeo/geocaching/models/GeocacheTest.java

No longer present "needs maintenance" and "needs archive" log types for gc connetor

suppress nm/na log type defaults for gc connector (rel. to #13343)

---

main/src/cgeo/geocaching/location/GeopointParser.java

fix #13311: decimal values separated by = shall not be parsed as coords

fix #13311: decimal values separated by = shall not be parsed as coords

---

main/src/cgeo/geocaching/TrackableActivity.java
main/src/cgeo/geocaching/connector/gc/GCParser.java
main/src/cgeo/geocaching/connector/trackable/GeokretyParser.java
main/src/cgeo/geocaching/export/FieldNotes.java
main/src/cgeo/geocaching/files/GPXParser.java
main/src/cgeo/geocaching/log/LogEntry.java
main/src/cgeo/geocaching/log/LoggingUI.java
main/src/cgeo/geocaching/models/Geocache.java
tests/src-android/cgeo/geocaching/connector/gc/TrackablesTest.java
tests/src-android/cgeo/geocaching/connector/su/SuParserTest.java
tests/src-android/cgeo/geocaching/connector/trackable/GeokretyParserTest.java
tests/src-android/cgeo/geocaching/files/GPXParserTest.java
tests/src-android/cgeo/geocaching/log/LogEntryTest.java

Replace usages of deprecated `LogEntry.getType()` by accessing the final property `logType` directly

replace usages of deprecated LogEntry.getType()

---

main/src/cgeo/geocaching/settings/Settings.java

Replaces the deprecated private `Settings.isLightSkin()` method, which is only used once, and only for migration purposes, by an inline call.

replace usage of deprecated Settings.isLightSkin

---

main/src/cgeo/geocaching/connector/gc/GCConstants.java
main/src/cgeo/geocaching/connector/gc/GCParser.java
main/src/cgeo/geocaching/files/FileParser.java
main/src/cgeo/geocaching/models/Geocache.java
main/src/cgeo/geocaching/sorting/AbstractCacheComparator.java

replace usages of deprecated `GCConstants.gccodeToGCId` by `GCUtils.gcLikeCodeToGcLikeId` (which is also deprecated, but then you have one indirection less)

replace usages of deprecated GCConstants.gccodeToGCId

---

main/src/cgeo/geocaching/log/LogEntry.java
main/src/cgeo/geocaching/models/Geocache.java
main/src/cgeo/geocaching/storage/DataStore.java
tests/src-android/cgeo/geocaching/connector/gc/TrackablesTest.java
tests/src-android/cgeo/geocaching/connector/oc/OkapiClientTest.java
tests/src-android/cgeo/geocaching/connector/trackable/GeokretyParserTest.java
tests/src-android/cgeo/geocaching/log/LogEntryTest.java

Replace usages of deprecated `LogEntry.getLogImages()` by directly accessing the final property `logImages`

replace usages of deprecated LogEntry.getLogImages()

---

main/src/cgeo/geocaching/models/Geocache.java
main/src/cgeo/geocaching/storage/DataStore.java

- Prevents duplicate waypoint prefixes on copy to/add from clipboard
- Database cleanup routine for stored data

Fix duplicate waypoint prefixes on copy to/add from clipboard (fix #13383)

---

main/res/menu/map_activity.xml
main/res/values/strings.xml

- optimize string for cache downloader (the previous string "Store all" is no longer fitting and not understandable enough IMHO)
- fix capitalization mistakes (make capitalization more consistent with other menu items)

optimize string for cache downloader and fix capitalization mistakes

---

main/res/values/preference_keys.xml
main/res/xml/preferences_services_geocaching_com.xml
main/src/cgeo/geocaching/connector/gc/GCLogin.java
main/src/cgeo/geocaching/settings/Settings.java
tests/src-android/cgeo/geocaching/connector/gc/GCLoginTest.java

Remove language switch. Language switch will from now on only be used by unit tests (which should be extended to test parsing in multiple languages). See #13228 for reference.

remove language switch

---

main/res/values/strings.xml
main/src/cgeo/geocaching/settings/fragments/PreferenceOfflinedataFragment.java
main/src/cgeo/geocaching/storage/DataStore.java

rel. to #11429
- add `VACUUM` and `REINDEX` to our manual maintenance routine
- add blocking progress dialog while maintenance is running

[Performance] possibility to vacuum and reindex db

---

main/src/cgeo/geocaching/storage/DataStore.java

Adds method to delete orphaned UDC and call it on every restart of c:geo (as it has been before PR #13225, though accidentally)

delete orphaned UDC on c:geo restart (fix #13352)

---

main/AndroidManifest.xml
main/res/layout/generic_recyclerview.xml
main/res/layout/twotexts_twobuttons_item.xml
main/res/menu/main_activity_options.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/downloader/PendingDownloadsActivity.java
main/src/cgeo/geocaching/storage/extension/PendingDownload.java

Adds a view for pending downloads to the main menu. This view lists all pending downloads handled by the internal download manager (eg: maps, routing tiles) with current status info. Pending downloads can be cancelled.
In the long run this shall be extended with an automatic check for pending downloads at start of c:geo, offering this view optionally, if there are any stuck or broken downloads currently.
This will also replace our current debug view for pending downloads in the future.

Add view for pending downloads

---

main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/CacheListActivity.java
main/src/cgeo/geocaching/export/GpxExport.java

Adds cache / list name to filename on GPX export:
This is a first step towards #2724 (actually fulfilling the original request). Next step would be to make the filename editable (as we have for individual routes).

Add cache/list name to GPX file name (rel. to #2724)

---

main/res/values/strings.xml
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/downloader/DownloaderUtils.java
main/src/cgeo/geocaching/downloader/PendingDownloadsActivity.java
main/src/cgeo/geocaching/maps/MapUtils.java
main/src/cgeo/geocaching/models/Download.java
main/src/cgeo/geocaching/storage/extension/PendingDownload.java

Checks on c:geo startup whether there are any pending downloads not currently running (ie: being paused or failed). Prompts the user to open the "pending downloads view" if such downloads have been found. Within that view the user can cancel downloads.

check pending downloads on init

---

main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateGlobalDialog.java
main/src/cgeo/geocaching/utils/TextParser.java
main/src/cgeo/geocaching/utils/formulas/DegreeFormula.java
tests/src/cgeo/geocaching/utils/formulas/DegreeFormulaTest.java

fix #13459, fix #13460: consider nbsp as whitespace when parsing formulas
Both issues show symptoms of this bug. The formula  of the cache in question contains nbsp characters in HTML sourcecode.

fix #13459, fix #13460: consider nbsp as whitespace when parsing formulas

---

main/src/cgeo/geocaching/models/WaypointParser.java
tests/src/cgeo/geocaching/models/WaypointParserTest.java

fix #13452: avoid scanning inner formulas for normal coords

fix #13452: avoid scanning inner formulas for normal coords

---

main/res/values/preference_keys.xml
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/settings/Settings.java

- Restrict pending downloads check in `MainActivity` to twice a day
- Therefore changed the "check intervals" methods to a hour-based interface (instead of day-based)

Restrict pending downloads check to twice a day

---

main/src/cgeo/geocaching/models/WaypointParser.java
tests/src/cgeo/geocaching/models/WaypointParserTest.java

fix #13461: allow parsing of vars with empty expression

fix #13461: allow parsing of vars with empty expression

---

main/res/layout-land/compass_activity.xml
main/res/layout/compass_activity.xml

Make details text line in compass views (portrait & landscape) scalable, so that it automatically adjusts its height according to font size setting:
||portrait|landscape|
|---|---|---|
|default font size|![image](https://user-images.githubusercontent.com/3754370/194136059-581066cf-56c2-4446-a3ef-e9ba0a1916cf.png)|![image](https://user-images.githubusercontent.com/3754370/194136155-b78e5cb2-caad-44ed-97af-341b90d0ef2e.png)|
|large font size|![image](https://user-images.githubusercontent.com/3754370/194136116-667e61ce-938b-4d0b-b6e0-ed6b81fa64de.png)|![image](https://user-images.githubusercontent.com/3754370/194136190-88ede473-090e-49ba-b1bf-0f1d41e45934.png)|

Make details text line in compass scalable (fix #13420)

---

main/src/cgeo/geocaching/calendar/CalendarEntry.java

Creating a calendar entry for an event adds the URL and shortdesc as the entries description.
While for OC shortdesc usually contains some information for GC it has nothing but the date. With this PR if shortdesc doesn't have any meaningful content (defined by being <150 chars) description is used for the calendar entry instead.
Before:
After:

for calendar entries if event shortdesc is very short use normal description

---

main/src/cgeo/geocaching/CompassActivity.java
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/utils/GeoHeightUtils.java

- Display current elevation on home screen (right of location info), if available
- As in compass mode we display an averaged elevation (arithmetic mean of last five readings)
- If no elevation info is available (as is the case for AS emulator) no elevation info is displayed

display elevation on home screen (fix #13470)

---

main/res/values/strings.xml

Adapt the string to accommodate the new feature, that files to retry download can now be selected. 
#13473

Fix #13473 - Better strings for download retry

---

main/res/values/strings.xml

Android 12+ supports coarse and fine location permission. To be able to use GPS, c:geo needs to be granted fine location permission. It cannot be used without.
Therefore extend explanation to note "fine location".

be more specific about location permission required

---

main/src/cgeo/geocaching/calendar/CalendarEntry.java
main/src/cgeo/geocaching/models/Geocache.java
main/src/cgeo/geocaching/sorting/EventDateComparator.java
main/src/cgeo/geocaching/utils/EventTimeParser.java
tests/src-android/cgeo/geocaching/utils/EventTimeParserTest.java

GC listings for some while now contain the events start and end time in a standard format. This allows for reliable determination of both these dates.
By knowing the end date we are now able to create calendar entries with the proper end time.
I chose to parse short description instead of the listing (where the same information is available in 2 more places) because that is already stored in DB - the other 2 places would require an additional DB entry with little additional value.

get event end time for correct calendar entries

---

main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/storage/extension/PendingDownload.java

Silently removes pending downloads no longer recognized by the system's download manager, if the download date is before app. Oct 10th, 2022.

add housekeeping for stale downloads (rel. to #13438)

---

main/src/cgeo/geocaching/utils/UnknownTagsHandler.java

Currently, table cells identified by `<td>` are separated by a "|" for displaying a cache listing.
This PR adds the same for table cells identified by `<th>`.

Improve handling of th elements in table formatting (fix #13498)

---

cgeo-contacts/AndroidManifest.xml
main/AndroidManifest.xml

`<activity>` tags in `AndroidManifest.xml` reuse label from surrounding `<application>`, no need to repeat them on every `<activity>`

fix lint: redundant labels in AndroidManifest.xml

---

main/res/values/dimens.xml

Generally texts should use `sp` instead of `dp` to support text scalability.
We have one place in our layout config (toolbar) where we force using `dp` to avoid readability problems with large font sizes, therefore declare this as exception.

fix lint: dp usage for text size in resource instead of sp

---

main/src/cgeo/geocaching/ImageViewActivity.java
main/src/cgeo/geocaching/downloader/DownloaderUtils.java

Normally manual text concatenation should not be used due to internationalization issues, but it may be ok in specific situations. Declare exceptions for those places.

fix lint: allow text concatenation in certain places

---

main/src/cgeo/geocaching/ui/ViewUtils.java

We are overriding Android default behavior in overflow icon placement intentionally in one place - mark this as lint exception.

fix lint: always show action

---

main/res/layout/imageview_image.xml
main/res/layout/variable_list_view.xml

Stacking empty layouts is normally unnecessary. PR marks the exceptions.

fix lint: ignore 'uselessparent' in specific places

---

main/src/cgeo/geocaching/storage/DataStore.java

Lint SQL syntax checking cannot cope with concatenating a const value so it reports a false-positive syntax error => PR suppresses it for the variable declaration involved.

fix lint: false positive on sql syntax error

---

tests/src-android/cgeo/geocaching/CgeoApplicationTest.java

Removing our website-language switching is incomplete as of now, causing two trackable-related tests to constantly fail.
This is not only annoying, but also distracting from actual build problems.
Therefore let's temporarily disable the parts of the two tests which lead to making the tests fail, to get green builds back.
We already do have an issue as reminder to put those tests back into active state: #13458.

temporarily disable spotted user tb tests (rel. to #13458, #13228)

---

main/src/cgeo/geocaching/filters/gui/DistanceFilterViewHolder.java
main/src/cgeo/geocaching/filters/gui/FavoritesFilterViewHolder.java
main/src/cgeo/geocaching/filters/gui/LogsCountFilterViewHolder.java
main/src/cgeo/geocaching/settings/SeekbarPreference.java
main/src/cgeo/geocaching/ui/ContinuousRangeSlider.java
main/src/cgeo/geocaching/ui/dialog/SimpleDialog.java

Tapping on either thumb of a range slider allows manual setting of its value.
Ranges of given slider are honored. Out-of-bound values are reset to slider's min/max values.
Setting this to draft for now, as it always uses the given range, not the "display version of given range", which makes a difference for a percentage-based range, where internal range is 0.0 to 1.0, whereas displayed range is 0 to 100 (percent).
@eddiemuc : Would it be sufficient to apply the `labelMapper` function to the internal min/max value?

allow manual setting of range slider values (fix #12808)

---

main/src/cgeo/geocaching/maps/RouteTrackUtils.java
main/src/cgeo/geocaching/maps/Tracks.java
main/src/cgeo/geocaching/storage/extension/Trackfiles.java

Tapping on a track's display name opens a dialog box where the user can change the display name.
The (copied) file in the (private part of the) file system will not be renamed.

allow change of track's display name (fix #12587)

---

main/src/cgeo/geocaching/utils/UnknownTagsHandler.java

Adds some basic formatting for definition lists (new line, and some marker for definition titles).
Cache description from the related issue will then look like this:

Add minimal formatting for definition lists (fix #6807)

---

main/src/cgeo/geocaching/ui/ContinuousRangeSlider.java

Restrict displayed values in edit mask of `ContinuousRangeSlider` to (rounded) integer values (but still allow entering exact values within the given range of the slider).
|---|---|
|favorite filter, percent mode|favorite filter, absolute mode|
|![image](https://user-images.githubusercontent.com/3754370/196049263-f21229bf-8471-4433-bcab-480847570b43.png)|![image](https://user-images.githubusercontent.com/3754370/196049253-03fbe821-2ba8-439f-a96c-57ed76bf06bd.png)|

restrict displayed values to integers (rel. to #13517)

---

main/src/cgeo/geocaching/CacheDetailActivity.java
main/src/cgeo/geocaching/models/Geocache.java
main/src/cgeo/geocaching/ui/AnchorAwareLinkMovementMethod.java
main/src/cgeo/geocaching/utils/ImageUtils.java

- Use ShareUtils for listing link handling (⇾ will use Chrome WebView if the relevant setting was enabled by the user)
- Open ImageViewActivity when clicking on listing images (fix #9019) 
* ImageViewActivity will only be used if the image isn't wrapped into an `<a href="..">...</a>` link tag
-  avoid image duplication in image gallery (fix cgeo#13088)

Listing link and image handling

---

main/src/cgeo/geocaching/files/GPXParser.java
tests/res/raw/gc31j2h_wpts_original.gpx
tests/src-android/cgeo/geocaching/files/GPXParserTest.java

set the flag _setUserModifiedCoords_ if gpx contains a waypoint of type ORIGINAL, so the upload of modified coordinates works properly and on update the waypoint does not get lost
fix #13302

update "set user modified coordinates" for cache on gpx-import 

---

main/res/layout/cachedetail_description_page.xml
main/res/values/strings.xml
main/src/cgeo/geocaching/CacheDetailActivity.java

rel to #13138: make load of cache description asynchronous and limited
* Cache listings will now be rendered aynchronously. 
* Very long listings will now be shortened to first 100000 chars. A warning will be displayed that listing was cutted and option is given to re-render the full listing

rel to #13138: make load of cache description asynchronous and limited

---

main/src/cgeo/geocaching/CompassActivity.java
main/src/cgeo/geocaching/MainActivity.java
main/src/cgeo/geocaching/utils/GeoHeightUtils.java

- Displays height on home screen only when full readings (at least 5) are available
- Prepends "~" in compass height view, if less than five readings have been used

improve height display ( #13526)

---

main/res/values/strings.xml

by adding tools:ignore="PluralsCandidate"

Fix lint warning PluralsCandidate

---

main/build.gradle

Sets `targetSDK` to 31 as required by Play Store guidelines starting Nov 1st, 2022 to be able to upload new versions. For details see related issue #13036.
November 1st is closing in, so I propose to get this change into the nightlies to check whether there are any loose ends not being taken care of yet.

set targetSDK to 31 (rel. to #13036)
